# Introduction

Large Language Models (LLMs) have revolutionized natural language processing, but their massive size and computational requirements present significant challenges for fine-tuning and deployment. As models scale to billions of parameters, efficient optimization has become a critical discipline that combines mathematical optimization, hardware awareness, and systems engineering. This tutorial project provides a comprehensive exploration of the optimization methods used to fine-tune and deploy LLMs, with practical implementations using Google's Gemma-3-270m and Meta's Llama-3.2-1B models.

The project covers the full spectrum of optimization techniques—from precision training and quantization to parameter-efficient fine-tuning, architectural optimizations, and deployment-specific strategies. Through hands-on code examples and detailed explanations, you'll learn how to reduce memory footprint, accelerate training and inference, and make LLMs accessible on consumer-grade hardware.

# Objectives

By completing this tutorial project, you will be able to:
- **Understand the theoretical foundations** of various LLM optimization techniques, including mixed precision training, quantization, and parameter-efficient fine-tuning
- **Implement practical optimization workflows** using industry-standard libraries such as Hugging Face Transformers, PEFT, bitsandbytes, DeepSpeed, and vLLM
- **Apply memory reduction techniques** including 4-bit quantization (QLoRA), gradient checkpointing, and optimizer state optimization to fit large models on limited hardware
- **Utilize parameter-efficient fine-tuning methods** like LoRA, DoRA, and IA3 to adapt models with minimal computational resources
- **Deploy optimized models** using high-performance inference engines like vLLM, with techniques such as continuous batching and speculative decoding
- **Measure and compare optimization effectiveness** using comprehensive metrics for memory footprint, throughput, latency, and accuracy

# Table of Contents

**Part 1: Foundations and Setup**

* **LLM Optimization Methods**
* **Optimization Methods Used in the Project**
* **LLMs Used in the Project**
* **Project Remarks**
* **Data Dictionary**
* **Environment Setup and Library Installation**
* **Hardware Detection and Resource Monitoring**
* **Dataset Preparation (StackOverflow Q&A)**
* **Data Preprocessing and Tokenization**
* **Resource Monitoring Class Implementation**

**Part 2: Precision Training and Quantization**

* **Baseline Fine-tuning (FP32)**
* **Automatic Mixed Precision (AMP) with BF16/FP16**
* **BF16-FP32 Hybrid Training**
* **Dynamic Loss Scaling**
* **Gradient Clipping Integration**
* **4-bit Quantization with bitsandbytes**
* **QLoRA: 4-bit Quantized LoRA**
* **Double Quantization and Paged Optimizers**

**Part 3: Parameter-Efficient Fine-Tuning (PEFT)**

* **LoRA (Low-Rank Adaptation)**
* **DoRA (Weight-Decomposed LoRA)**
* **VeRA (Vector-based Random Matrix Adaptation)**
* **AdaLoRA (Adaptive Rank Allocation)**
* **LoRA+ (Decoupled Learning Rates)**
* **LoHa (Low-rank Hadamard Product)**
* **KronA (Kronecker Adaptation)**
* **IA3 (Infused Adapter)**
* **BitFit (Bias-Only Fine-tuning)**

**Part 4: Prompt-Based Methods**

* **Simple Prompt Tuning**
* **Multi-task Prompt Sharing (P-Tuning v2)**
* **Prefix Tuning with Projection**
* **Attention-Guided Prefix Allocation**
* **Hierarchical Prompt Structures**
* **Dynamic Prompt Generation**
* **Prompt Ensembling**

**Part 5: Memory and Compute Optimization**

* **Gradient Checkpointing Strategies**
* **Gradient Accumulation with Variable Steps**
* **Activation Compression and Offloading**
* **8-bit Optimizers (AdamW8bit)**
* **Per-parameter Optimizer Precision**
* **ZeRO-1: Optimizer State Sharding**
* **ZeRO-2: Gradient + Optimizer Sharding**
* **ZeRO-3: Full Parameter Partitioning**
* **CPU Offloading with ZeRO-Infinity**

**Part 6: Model Compression**

* **Structured Pruning (Head/Layer Removal)**
* **Magnitude Pruning with Regrowth**
* **Token Merging (ToMe)**
* **Knowledge Distillation (Multi-teacher)**
* **Self-Distillation**
* **Adaptive Temperature Distillation**
* **Attention Map Transfer**

**Part 7: Architectural Optimizations**

* **Multi-Query Attention (MQA) Conversion**
* **Grouped-Query Attention (GQA)**
* **FlashAttention Integration**
* **Mixture of Experts (MoE) Optimization**
* **Top-k Gating with Capacity Factor**
* **Expert Load Balancing**

**Part 8: Distributed Training**

* **FSDP (Fully Sharded Data Parallel)**
* **torch.compile with FSDP**
* **JAX JIT Compilation**
* **JAX vmap (Vectorization)**
* **JAX pmap (Device Parallelism)**
* **Combined JAX Optimizations (JIT + vmap + pmap)**
* **DeepSpeed with ZeRO-3 and CPU Offload**

**Part 9: Deployment Optimizations**

* **Continuous/Paged Batching with vLLM**
* **Speculative Decoding**
* **Medusa Heads (Tree-based Verification)**
* **Evaluation Metrics and Interpretation**
* **Performance Comparison and Analysis**

**Part 10: Advanced Topics and Automation**

* **Adaptive Precision Based on Gradient Variance**
* **Layer-wise Precision Adaptation**
* **Sequence Length Curriculum Learning**
* **Federated Averaging**
* **Personalized Federated Learning**
* **Hyperparameter Optimization Strategies**

# LLMs Optimization Methods

As Large Language Models continue to scale in both capability and size, efficient fine-tuning and deployment have become a critical discipline that combines mathematical optimization, hardware awareness, and systems engineering. This guide provides a comprehensive taxonomy of fine-tuning optimization methods, with special emphasis on mixed precision training and other advanced techniques.

#### **I. PRECISION TRAINING and QUANTIZATION**

These approaches focus on reducing the numerical bit-width of model parameters to save memory and accelerate computation without sacrificing significant accuracy.

##### **A. Mixed Precision** (Fine-tuning and Deployment)

This approach uses lower-precision formats like FP16 or BF16 for the heavy lifting of forward and backward passes while maintaining FP32 master weights to ensure numerical stability. By utilizing Automatic Mixed Precision (AMP) and Dynamic Loss Scaling, practitioners can prevent gradient underflow and overflow, significantly reducing the VRAM footprint and increasing training speed on modern GPUs.

**Core Strategies:**

- **Automatic Mixed Precision (AMP):** Automatic conversion between FP32/BF16/FP16 based on operation sensitivity.
- **BF16/FP16-FP32 Hybrid:** BF16/FP16 for forward/backward passes with FP32 master weights for stable optimization.
- **Dynamic Loss Scaling:** Automatically adjusts scale factor to prevent gradient underflow (common in AMP implementations).
- **Gradient Clipping Integration:** Combined with mixed precision to prevent overflow during low-precision operations.

**Advanced Techniques:**

- **Per-Layer/Component Precision Selection:** Critical layers (attention output, LM head) kept in higher precision.
- **Attention-Specific Precision:** Higher precision for attention query/key calculations, lower for value projections.
- **Gradient Accumulation in FP32:** Accumulate gradients in high precision before weight updates.
- **Selective High Precision:** Critical operations (layer norm, softmax) kept in higher precision.
- **FP8 Fine-Tuning:** Experimental but promising for 2 times memory reduction during training.
- **Stochastic Rounding:** Reduces bias in low-precision training.
- **Hybrid Precision Schedules:** Progressive reduction from FP32 to lower precision as training stabilizes.
- **Adaptive Precision:** Dynamically adjust precision based on gradient variance.
- **Layer-wise Precision Adaptation:** Different precision per model component based on sensitivity analysis.

**Memory-Optimized Precision:**

- **Activation Checkpointing with Precision:** Store checkpoints in lower precision, recompute in higher.
- **Gradient Compression:** Store gradients in reduced precision during backward pass.
- **Optimizer State Quantization:** 8-bit optimizers (Adam8bit, Lion8bit) for reduced memory footprint.
- **Activation Precision Management:** Store activations in lower precision while maintaining gradient calculation.

##### **B. Quantization-Aware Fine-Tuning (QAT)** (Fine-tuning and Deployment)

Unlike post-training quantization, QAT introduces quantization noise during the fine-tuning process itself using Fake Quantization and Straight-Through Estimators (STE). This "teaches" the model to be resilient to the loss of precision it will encounter during deployment, allowing for extreme compression (e.g., down to 4-bit) with minimal performance degradation.

**Quantization Simulation:**

- **Fake Quantization:** Insert quantization/dequantization operations during forward pass.
- **Straight-Through Estimator (STE):** Approximate gradient through quantization function.
- **Learnable Quantization Parameters:** Model learns optimal scaling factors and zero-points.
- **Progressive Quantization:** Gradual reduction of precision during training.
- **Layer-wise Quantization Schedule:** Different layers quantized at different times.

**Advanced QAT Methods:**

- **Differentiable Quantization:** Soft quantization using Gumbel-Softmax relaxation.
- **Vector Quantization Fine-tuning:** Learn codebook representations during adaptation.
- **Mixed-Precision QAT:** Different quantization strategies per layer or tensor type.
- **Hessian-Aware Quantization:** Use second-order information to guide precision allocation.
- **Sensitivity-based Allocation:** More bits for sensitive layers.
- **Dynamic Precision Adjustment:** Change precision during training based on metrics.

#### **II. PARAMETER-EFFICIENT FINE-TUNING (PEFT)** (Fine-tuning)

PEFT is the most critical category for modern fine-tuning optimization. Instead of updating all billions of parameters, these methods target less than 1 percent of the model's weights. PEFT methods are designed to adajust massive models by updating only a tiny fraction of the total parameters, making fine-tuning accessible on consumer-grade hardware.

##### **A. Low-Rank Adaptation (LoRA)**

This subcategory uses rank-decomposition matrices to mimic the updates of a full weight matrix. Advanced versions like QLoRA allow for tuning on 4-bit base models, while DoRA decomposes updates into magnitude and direction for better stability, and AdaLoRA dynamically allocates parameters where they are most needed.

**Enhanced LoRA Variants:**

- **LoRA:** Adds small, trainable rank-decomposition matrices to the model's layers.
- **LoRA+:** Dynamic rank adaptation based on layer sensitivity with layer-specific learning rates.
- **AdaLoRA:** Adaptive rank allocation based on parameter importance.
- **MoRA:** Memory-optimized LoRA with tensor decomposition.
- **Sparse LoRA:** Combines sparsity with low-rank adaptation for extreme efficiency.
- **Dynamic LoRA:** Adjusts rank and alpha parameters during training based on gradient signals.

**QLoRA Extensions:**

- **QLoRA:** Fine-tunes a LoRA adapter on top of a 4-bit quantized base model, allowing 70B models to be tuned on consumer GPUs.
- **Double Quantization:** Quantize quantization constants for additional memory savings.
- **Paged QLoRA:** Handle large adapters that exceed GPU memory.
- **Distributed QLoRA:** Share adapter parameters across multiple GPUs.
- **QLoRA with Gradient Checkpointing:** Combined memory optimization.

**Novel Adaptation Methods:**

- **DoRA (Weight-Decomposed Low-Rank Adaptation):** Decomposes weight updates into magnitude and direction, allowing for more stable and expressive learning than standard LoRA.
  - *Enhancements:* Adaptive magnitude scaling, direction orthogonalization, layer-coupled DoRA.
- **VeRA (Vector-based Random Matrix Adaptation):** Uses frozen random matrices with tiny trainable scaling vectors (0.01% of parameters).
- **LoHa (Low-rank Hadamard Product):** Hadamard product of low-rank matrices.
- **KronA (Kronecker Adaptation):** Kronecker product decomposition for parameter efficiency.

##### **B. Prefix and Prompt-Based Methods**

These techniques avoid changing the base model weights entirely. Prompt Tuning learns a continuous "soft prompt" vector at the input level, while Prefix Tuning prepends trainable tensors to every layer of the transformer, effectively steering the model's internal activations toward specific task behaviors.

**Advanced Prompt Tuning:**

- **Prompt Tuning:** Learns continuous "soft prompt" embeddings prepended to input.
- **Multi-task Prompt Sharing/Tuning:** Shared prompt banks across related tasks.
- **Hierarchical Prompt Structures:** Different prompt lengths per layer based on sensitivity.
- **Dynamic Prompt Generation:** Generate prompts conditionally based on input.
- **Prompt Compression:** Apply pruning and quantization to learned prompts.
- **Prompt Ensembling:** Combine multiple prompt vectors for improved performance.

**Prefix Tuning Improvements:**

- **Prefix Tuning:** Prepends trainable tensors to every layer of the transformer.
- **Depth-Adaptive Prefixes:** Variable prefix sizes for different layers.
- **Attention-Guided Prefix Allocation:** More parameters for high-attention layers.
- **Prefix Quantization:** Store prefixes in 4-bit or 8-bit precision.
- **Sparse Prefix Tuning:** Only update a subset of prefix parameters.

##### **C. Adapter and Scaling Methods**

This group focuses on inserting small, modular bottleneck layers (Adapters) or simple scaling vectors (like IA3) into the existing architecture. These methods allow for multi-task learning by simply swapping out small, task-specific modules while keeping the massive backbone model frozen.

**Efficient Scaling Methods:**

- **IA3 (Infused Adapter by Inhibiting and Amplifying Inner Activations):** Scales internal activations (Key, Value, and Feed-Forward) using learned vectors.
- **IA3++:** Extends IA3 with learned scaling for attention matrices.
- **(IA)$^3$:** An even more parameter-lean version of activation scaling.
- **Bias-Only Fine-tuning:** Update only bias parameters (0.1% of total).
- **LayerScale Adaptation:** Fine-tune only layer normalization parameters.

**Advanced Adapter Architectures:**

- **HyperAdapters/HyperLoRA:** Generate adapter parameters using a hypernetwork.
- **Conditional Adapters:** Adapter parameters conditioned on input features/characteristics.
- **Recurrent Adapters:** Temporal sharing of adapter parameters across time steps.
- **Compacter:** Parameterized hypercomplex multiplication layers for efficient adaptation.

#### **III. MODEL COMPRESSION & DISTILLATION** (Fine-tuning and Deployment)

These techniques start during fine-tuning but primarily serve deployment goals of reducing model size and inference cost. These techniques prioritize the reduction of the model's physical size and computational complexity for the purpose of efficient deployment.

##### **A. Progressive Pruning Strategies**

Pruning involves identifying and removing uninformative weights or structural components like attention heads or layers. Methods range from Magnitude Pruning, which cuts the smallest values, to Token Pruning, which drops unhelpful data tokens mid-inference to save on sequence processing time.

**Weight Pruning During Fine-tuning:**

- **Magnitude Pruning with Regrowth:** Prune small weights, allow regrowth of important connections.
- **Gradient-based Pruning:** Remove weights with consistently small gradients.
- **Lottery Ticket Hypothesis:** Find and fine-tune sparse subnetworks.
- **Structured Pruning:** *(Deployment: Hardware-friendly speedups)* Remove entire attention heads, neurons, or layers.

**Token & Sequence Optimization:**

- **Dynamic Token Pruning (DTP):** Learn to drop uninformative tokens during processing.
- **Attention-based Token Selection:** Use attention scores to identify important tokens.
- **Token Merging (ToMe):** Combine similar tokens to reduce sequence length.
- **Sequence Length Curriculum:** Gradually increase sequence length during training.
- **Sliding Window Attention:** *(Deployment: Memory-efficient inference)* Local attention with fixed context window.

##### **B. Knowledge Distillation**

Distillation transfers knowledge from a large teacher to a smaller student model, primarily for deployment efficiency. This  approach involves a "Teacher" model (a large LLM) transferring its knowledge to a smaller "Student" model. Through Feature Alignment and Attention Map Transfer, the student learns to approximate the teacher's outputs and internal logic, resulting in a compact model that retains much of the original's capability.

**Distillation Techniques:**

- **Teacher Assistant Distillation:** Intermediate-sized models bridge gap between large teacher and small student.
- **Multi-teacher Distillation:** Combine knowledge from multiple specialized teachers.
- **Cross-modal Distillation:** Transfer knowledge from vision-language models to text-only models.
- **Self-Distillation:** Use same model at different training stages as teacher and student.
- **Real-time Knowledge Transfer:** Teacher generates outputs during student training.
- **Adaptive Temperature:** Adjust distillation temperature based on training progress.

**Feature Alignment Techniques:**

- **Attention Map Transfer/Distillation:** Force student to mimic teacher's attention patterns.
- **Hidden State Projection:** Learn linear transformations to align representations.
- **Gradient Matching:** Align gradient directions between teacher and student.
- **Contrastive Distillation:** Use contrastive learning to match representations.
- **Multi-modal Distillation:** Cross-modal alignment, modality-specific adapters, joint training.

Architectural changes focus on rewriting the "math" of the model to work more efficiently with modern hardware.

#### **IV. ARCHITECTURAL OPTIMIZATIONS** (Fine-tuning and Deployment)

These methods involve rewriting the fundamental "math" of the transformer to be more hardware-aware and memory-efficient.

##### **A. Efficient Attention Mechanisms**

This approach addresses the quadratic bottleneck of the attention mechanism. FlashAttention optimizes how data moves through GPU memory, while Grouped-Query Attention (GQA) reduces the memory used by the "KV cache," allowing for much longer context windows.

**Memory-Efficient Attention:**

- **FlashAttention Integration:** *(Both)* Optimize attention computation (2-4× speedup for long sequences).
- **Sparse Attention Patterns:** Learn which attention connections to prioritize.
- **Linear Attention Variants:** Approximate attention with linear complexity.
- **Memory Compressed Attention:** Reduce KV cache memory during training.

**Attention-Specific Optimizations:**

- **Multi-Query Attention (MQA):** *(Deployment: Faster inference)* Share key/value heads across queries.
- **Grouped-Query Attention (GQA):** *(Both)* Balance between MQA and multi-head attention (4-8 queries share KV heads).
- **Dilated Attention:** Sparse attention with dilation patterns.
- **Linear Attention Adaptation:** Convert standard attention to linear variants.

##### **B. Mixture of Experts Optimization**

MoE models substitute dense layers with sparse "experts." Optimization focuses on the Router, which ensures that only a few experts are active for any given word, allowing the model to have massive capacity without a massive compute cost.

**MoE Fine-tuning Strategies:**

- **Expert Specialization:** Each expert specializes in different domains or tasks.
- **Routing Optimization:** Fine-tune routing mechanisms without touching expert weights.
- **Sparse/Partial Expert Updates:** Only update activated/selected experts.
- **Expert Load Balancing:** Ensure balanced utilization across experts.

**Efficient MoE Training:**

- **Top-k Gating with Capacity Factor:** Control expert capacity to prevent overflow.
- **Auxiliary Losses:** Add load balancing and importance losses.
- **Expert Dropout:** Regularize by randomly dropping experts.
- **Gradient Accumulation for MoE:** Handle varying computational requirements.

#### **V. MEMORY & COMPUTE OPTIMIZATION** (Primarily Fine-tuning)

Systems-level optimizations that focus on managing the physical resources of the GPU during the training and fine tuning process.

##### **A. Gradient and Activation Management**

Techniques like Gradient Checkpointing trade compute for memory by deleting intermediate calculations and re-running them only when needed. Gradient Accumulation allows users to simulate large "batches" of data on GPUs with limited VRAM.

**Gradient Checkpointing Strategies:**

- **Selective Checkpointing:** Store only critical activations, recompute others.
- **Layer-wise Checkpointing:** Different strategies per layer type.
- **Dynamic Checkpointing:** Adapt based on available memory.

**Gradient Accumulation Optimization:**

- **Variable Accumulation Steps:** Adjust based on batch size and memory constraints.
- **Gradient Accumulation in CPU:** Offload gradient accumulation for very large models.
- **Asynchronous Gradient Updates:** Overlap computation and gradient application.
- **Gradient Accumulation Across Nodes:** Simulate larger global batch sizes.

**Activation Management:**

- **Full vs. Partial Recomputation:** Trade-off between compute and memory.
- **Layer-wise Recomputation:** Different strategies for attention vs. MLP layers.
- **Activation Compression:** Quantization, pruning, offloading.

##### **B. Optimizer State Optimization**

This involves reducing the memory footprint of the optimization algorithms (like Adam). Using 8-bit Optimizers or ZeRO-Offload moves memory-heavy data to the CPU, freeing up the GPU to focus on model weights.

**8-bit Optimizers:**
- **AdamW8bit/Lion8bit:** 8-bit versions of common optimizers.
- **Dynamic Quantization:** Adjust optimizer state precision during training.
- **Per-parameter Optimizer Precision:** Different precision for different parameter types.

**Optimizer State Partitioning:**
- **ZeRO-Offload:** Move optimizer states to CPU.
- **Optimizer State Sharding:** Distribute across multiple GPUs.
- **Delayed Optimizer Updates:** Update weights less frequently.

#### **VI. DISTRIBUTED TRAINING OPTIMIZATIONS** (Fine-tuning)

When a model is too large for one machine, these strategies shard the workload across dozens or hundreds of GPUs.

##### **A. Advanced Parallelism Strategies**

This includes 3D Parallelism, which splits data, layers (pipeline), and tensors across different devices. ZeRO (Zero Redundancy Optimizer) is the industry standard here, removing data duplicates across GPUs to allow for near-infinite scaling.

**Hybrid Parallelism:**

- **3D Parallelism:** Combined data, tensor, and pipeline parallelism.
- **Sequence Parallelism:** Split sequence dimension across devices.
- **Selective Replication:** Some layers replicated, others sharded.
- **Adaptive Strategy Selection:** Choose optimal parallel strategy per layer.

**ZeRO Optimization Levels:**

- **ZeRO-1:** Optimizer state partitioning (4× memory reduction).
- **ZeRO-2:** Gradient + optimizer state partitioning (8× reduction).
- **ZeRO-3:** Full parameter, gradient, and optimizer state partitioning (N× reduction).
- **ZeRO-Offload/Infinity:** CPU and NVMe offloading for extreme memory savings.

##### **B. Communication Optimization**

To prevent GPUs from waiting on each other, this sub-category uses Gradient Compression and Asynchronous Updates to minimize the time spent sending data over the network.

**Gradient Communication:**

- **Gradient Compression:** Reduce communication overhead with quantization.
- **Sparsified Gradients:** Only communicate gradients above threshold.
- **Asynchronous Updates:** Non-blocking gradient synchronization.
- **Hierarchical All-Reduce:** Optimize for multi-node clusters.

**Federated Fine-tuning:**

- **Differential Privacy:** Add noise to gradients for privacy preservation.
- **Federated Averaging:** Aggregate updates from multiple clients.
- **Personalized Federated Learning:** Client-specific model adaptation.

#### **VII. REGULARIZATION and STABILIZATION** (Fine-tuning)

These mathematical guardrails ensure that the model doesn't "break" or overfit during the sensitive fine-tuning process.

##### **A. Advanced Regularization Methods**

Methods like LayerDrop or Weight Decay prevent the model from memorizing the training data. This ensures the model remains flexible and "smart" when faced with real-world queries it hasn't seen before.

**Dropout Variants:**

- **Attention Dropout:** Regularize attention weights specifically.
- **Embedding Dropout:** Drop entire embedding vectors.
- **LayerDrop:** Randomly skip entire layers during training.
- **Stochastic Depth:** Varying network depth per sample.

**Weight Regularization:**

- **Selective Weight Decay:** Different decay rates for different parameter types.
- **Orthogonal Regularization:** Encourage orthogonality in weight matrices/updates.
- **Spectral Regularization:** Control spectral norm for stability.

##### **B. Optimization Stability**

Techniques like Gradient Clipping and Learning Rate Warmup prevent the mathematical updates from becoming too aggressive, which can lead to "catastrophic forgetting" or model collapse.

**Gradient Management:**

- **Gradient Clipping:** Norm-based or value-based clipping to prevent explosion.
- **Gradient Noise Injection:** Add noise for better generalization.
- **Lookahead Optimization:** Maintain slow and fast weight copies.

**Learning Rate Strategies:**

- **Layer-wise Learning Rates:** Different rates for different layers.
- **Warmup Strategies:** Linear, cosine, or exponential warmup.
- **Cosine Annealing with Restarts:** Periodic learning rate resets.

#### **VIII. DEPLOYMENT-SPECIFIC OPTIMIZATIONS** (Primarily Deployment)

These are the final-mile optimizations used to make a model production-ready for thousands of simultaneous users

##### **A. Inference Optimizations**

This includes Speculative Decoding, where a tiny model "guesses" the next word and the big model confirms it, and PagedAttention, which manages memory like an operating system to prevent wasted space during long conversations.

**Serving Optimizations:**

- **Continuous/Paged Batching:** Variable-length sequences with non-contiguous memory (vLLM).
- **Speculative Decoding:** Draft model proposes tokens, large model verifies (2-3 times speedup).
- **Medusa:** Multiple prediction heads + tree-based verification.
- **Prefix Caching:** Reuse KV cache for identical prompt prefixes.
- **KV Cache Quantization:** INT8/FP8 for keys/values to handle long contexts.

**Hardware Deployment:**

- **TensorRT-LLM:** NVIDIA GPU optimization with kernel fusion and quantization.
- **MLC-LLM:** Cross-platform deployment.
- **CoreML/TFLite Conversion:** For Apple Silicon/Android deployment.

##### **B. Production Considerations**

This focuses on Hardware-Aware compilation, such as using TensorRT-LLM to fuse operations together into a single, lightning-fast kernel that is specifically tuned for the user's specific GPU architecture.

**Hardware-Aware Optimization:**

- **Memory Hierarchy Optimization:** Optimize for limited VRAM (consumer GPUs).
- **Kernel Fusion:** Reduce memory bandwidth requirements.
- **Instance Selection:** Choose optimal cloud instance types.
- **Spot Instance Strategies:** Handle preemptions gracefully.

**Production Readiness:**

- **Deterministic Training:** Ensure consistent results.
- **Checkpoint Management:** Save and restore training state.
- **Experiment Tracking:** Log all optimization decisions.
- **Scalability:** From single GPU to cluster.

#### **IX. FRAMEWORK-SPECIFIC OPTIMIZATIONS**

These are the core system-level techniques implemented directly within deep learning frameworks to accelerate training and inference through smarter computation, memory management, and hardware utilization.

##### **A. PyTorch Optimizations**

This includes **`torch.compile`**, which transforms your Python code into an optimized computation graph for massive speedups, and **FSDP (Fully Sharded Data Parallel)**, which automatically splits a model across multiple GPUs to train models far larger than the memory of any single device.

**`torch.compile` Features:**

*   **Graph Optimization:** Automatic kernel fusion and memory optimization by capturing the entire computation into a single, efficient graph.
*   **Dynamic Shapes:** Efficient handling of variable sequence lengths without recompilation.
*   **Custom Backends:** Optimization for specific hardware (e.g., NVIDIA GPUs, AMD GPUs, CPUs).

**FSDP (Fully Sharded Data Parallel):**

*   **Optimization State Sharding:** Distributes optimizer states across GPUs to reduce per-GPU memory.
*   **Activation Checkpointing Integration:** Combines sharding with gradient checkpointing for maximal memory savings.
*   **CPU Offloading:** Automatically moves unused tensors to CPU memory during training.

**PyTorch Ecosystem Tools:**

*   **`torch.compile`:** The primary graph compilation engine.
*   **FSDP:** The standard for memory-efficient distributed training.
*   **TensorRT-LLM:** NVIDIA's dedicated inference optimization toolkit.
*   **Triton:** A language and compiler for writing highly efficient custom GPU kernels.

##### **B. JAX/Flax Optimizations**

This leverages **Just-In-Time (JIT) compilation** to fuse operations and generate optimal machine code, and functional transformations like **`vmap`** (for automatic batching) and **`pmap`** (for parallelizing across devices), which enable clean, high-performance code.

**JIT Compilation Strategies:**

*   **Static vs. Dynamic Compilation:** Choose based on whether input shapes are fixed or variable.
*   **Custom Compilation Passes:** Add domain-specific optimization rules to the compiler.
*   **Multi-device Compilation:** Automatically optimize computation for multi-GPU or multi-TPU setups.

**`pmap` / `vmap` Optimization:**

*   **Automatic Vectorization (`vmap`):** Handles batch dimensions automatically, turning a single-example function into a batched one.
*   **Device Mesh Management:** Optimizes data movement and computation across a mesh of devices (e.g., a TPU pod).
*   **Gradient Aggregation Optimization:** Efficiently collects and reduces gradients from multiple devices.

**JAX/Flax Ecosystem Tools:**

*   **`jax.jit`:** The core Just-In-Time compilation decorator.
*   **`jax.vmap`:** For automatic vectorization/batching.
*   **`jax.pmap`:** For parallelizing functions across multiple devices (GPUs/TPUs).
*   **`pjit`:** A more flexible SPMD (Single Program, Multiple Data) programming model for complex parallelism.

##### **C. Specialized Libraries**

These are third-party suites that provide state-of-the-art, integrated optimization strategies, often acting as a middleware layer between your framework code and the hardware.

**DeepSpeed (Microsoft):**

DeepSpeed (Microsoft) is a fine-tuning essential that can offload data to CPUs to save VRAM.

*   **ZeRO-3 Optimizations:** Partitions the full model state (parameters, gradients, optimizer states) across all GPUs to eliminate memory redundancy.
*   **Offload Engine:** Automatically offloads data to CPU or NVMe storage to train models exceeding total GPU memory.
*   **Pipeline Parallelism:** Splits model layers across GPUs for efficient training of colossal models.

**Hugging Face Ecosystem:**

For deployment, `vLLM and llama.cpp` integrate with model from HuggingFace libraries are the leaders in high-speed inference, using specialized memory management like PagedAttention to serve users faster.

*   **Accelerate:** Simplifies multi-device (CPU/GPU/TPU) and mixed-precision training with automatic device placement and gradient accumulation.
*   **Optimum:** Provides hardware-accelerated inference backends for partners like Intel, Qualcomm, and Graphcore.
*   **`vLLM`:** A high-throughput, memory-efficient inference server utilizing PagedAttention.
*   **`llama.cpp`:** An efficient C++ implementation for CPU and edge device inference with quantized models.

#### **X. EVALUATION, TRADE-OFFS & AUTOMATION**

These are the metrics, analyses, and automated systems used to measure the impact of optimizations, balance competing goals like speed and accuracy, and intelligently search for the best configuration.

##### **A. Performance Metrics & Trade-off Considerations**

Optimization is a balancing act. You must track Throughput (how fast you train/generate) against Accuracy (model quality). For deployment, Latency (time to first word) is the most critical metric for user experience, often requiring a trade-off in model size via compression.

**Core Performance Metrics:**

*   **Memory Footprint:** `Parameters × Precision + KV Cache`. The total memory required to load and run the model.
*   **Throughput:** Tokens/second (inference) or TFLOPS (training). How much work is done per unit of time.
*   **Latency:** Time to first token + generation speed. The delay experienced by an end-user.
*   **Accuracy:** Perplexity (intrinsic) and task-specific metrics (extrinsic, e.g., F1, accuracy).

**Key Trade-offs:**

*   **Quality vs. Size:** Aggressive compression (quantization, pruning) typically reduces model quality.
*   **Training vs. Inference:** The optimal strategy for fast training (e.g., large batch parallelism) differs from that for fast inference (e.g., small batch latency).
*   **Hardware Constraints:** Must respect GPU memory limits, interconnect speeds (NVLink vs. PCIe), and compute capability.
*   **Use Case:** Real-time chat requires low latency, while batch processing prioritizes high throughput.

##### **B. Automated Optimization**

Instead of manually guessing settings, tools use Bayesian Optimization or Meta-learning to find the best hyperparameters. This ensures that the fine-tuning process is as efficient as possible without wasting expensive GPU hours.

**Hyperparameter Optimization (HPO):**

*   **Bayesian Optimization:** An efficient, model-based search of the hyperparameter space.
*   **Population-based Training (PBT):** Multiple training jobs (a population) run in parallel and periodically exchange hyperparameters.
*   **Meta-learning:** Learns optimal hyperparameter settings from similar tasks or models.

**Adaptive Strategy Selection:**

*   **Performance Prediction:** Uses proxies or small-scale experiments to predict which optimization will be most beneficial.
*   **Cost-benefit Analysis:** Quantifies the expected speedup or memory saving against the implementation or runtime overhead.
*   **Dynamic Strategy Adjustment:** Changes optimization strategies (e.g., switching batching methods) during training or inference based on live metrics.

#### **XI. DATA & COMPUTE EFFICIENCY**

These are the fundamental techniques for optimizing the data pipeline (how data is loaded and processed) and the compute kernels (how mathematical operations are executed on hardware), which provide foundational speedups across all frameworks. This category addresses the "plumbing" of AI—how data flows into the model and how math is executed on the chip.

##### **A. Data Optimization (Fine-tuning)**

Fine-tuning speed is often limited by how fast you can feed the GPU. Dynamic Batching prevents wasted computation on short sentences, while Streaming Data Loading allows you to fine-tune on datasets that are too large to fit in your computer's RAM.

**Efficient Data Processing:**

*   **Dynamic Batching:** Groups sequences of similar lengths into batches to minimize padding and wasted computation.
*   **Curriculum Learning:** Presents easier examples to the model before harder ones, potentially improving convergence.
*   **Active Learning:** Selects the most informative data points for labeling, maximizing fine-tuning efficiency.
*   **Data Augmentation:** Creates synthetic training data via text perturbation, back-translation, or synonym replacement.

**Memory-Efficient Data Loading:**

*   **Streaming Data Loading:** Processes data in a continuous stream rather than loading entire datasets into RAM.
*   **Memory Mapping (`mmap`):** Uses memory-mapped files for fast, random access to large datasets on disk.
*   **Compressed Data Formats:** Stores data in compressed formats (e.g., parquet, tfrecord) and decompresses on-the-fly.
*   **On-the-fly Preprocessing:** Applies transformations (tokenization, augmentation) during data loading, not as a separate preprocessing step.

##### **B. Compute Optimization (Fine-tuning and Deployment)**

This involves deep hardware tweaks. Kernel Fusion merges multiple math steps into one to reduce memory "traffic" on the GPU. FlashAttention is a prime example of a custom kernel that dramatically speeds up the core transformer math for both phases.

**Kernel-Level Optimizations:**

*   **Custom CUDA Kernels:** Hand-written, highly optimized GPU kernels for specific, performance-critical operations (e.g., FlashAttention).
*   **Kernel Fusion:** Combines multiple consecutive operations (e.g., add + layer norm) into a single kernel to reduce memory reads/writes.
*   **Memory Access Optimization:** Organizes computations to maximize data reuse (temporal locality) and enable coalesced memory access (spatial locality).
*   **Asynchronous Operations:** Overlaps computation on the GPU with data transfers between host and device (CPU/GPU).

**Hardware-Specific Optimizations:**

*   **Tensor Core Utilization:** Specifically structures computations to use NVIDIA's Tensor Cores for peak FLOPs on matrix multiplications.
*   **Memory Hierarchy Awareness:** Optimizes data placement and movement between GPU HBM (high-bandwidth memory), L2 cache, and registers.
*   **Multi-GPU Optimization:** Tailors communication patterns for specific interconnects like high-speed NVLink or standard PCIe.
*   **Mixed Device Training:** Strategically uses a combination of GPUs, CPUs, and specialized accelerators (e.g., TPUs, IPUs) within a single training run.


#### **XII. PRACTICAL DEPLOYMENT STRATEGIES**

These are the considerations and techniques for moving from a research model to a robust, scalable production system, focusing on the target hardware environment and operational requirements. These strategies are deployment-specific, focusing on the environment where the model will actually "live" and provide service for customers.

##### **A. Hardware-Aware Optimization**

Deployment looks different on a Consumer GPU (where memory is tight and you need 4-bit quantization) versus the Cloud (where you might use Auto-scaling and Spot Instances to keep costs low while handling millions of requests).

**Consumer GPU Deployment:**

*   **Memory Hierarchy Optimization:** Aggressively manages limited VRAM through quantization, checkpointing, and efficient kernels.
*   **Kernel Fusion:** Reduces memory bandwidth requirements, which is often the bottleneck on consumer cards.
*   **Mixed Precision:** Uses lower precision (FP16/BF16) to save memory and increase speed, balancing numerical stability.
*   **Checkpointing Strategies:** Optimizes the frequency and storage of model checkpoints for recovery and deployment.

**Cloud Deployment:**

*   **Instance Selection:** Chooses the optimal cloud instance type (e.g., memory-optimized vs. compute-optimized) for cost-performance.
*   **Spot Instance Strategies:** Implements checkpointing and job migration to handle preemptions of cheaper, interruptible spot instances.
*   **Multi-region Deployment:** Distributes models across geographic regions to reduce latency for global users.
*   **Auto-scaling:** Automatically scales the number of inference instances up or down based on request demand.

##### **B. Production Considerations**

Moving to production requires Reproducibility (ensuring the model behaves the same way every time) and Fault Tolerance, so the system can automatically recover if a GPU fails during a live session.

**Reproducibility:**

*   **Deterministic Training:** Uses fixed seeds and deterministic algorithms to ensure identical results across runs.
*   **Checkpoint Management:** A system for saving, versioning, and restoring exact training states.
*   **Experiment Tracking:** Logs all code, data, hyperparameters, and optimization decisions (e.g., using MLflow, Weights & Biases).
*   **Version Control:** Tracks versions of model weights, training datasets, and inference code together.

**Scalability & Robustness:**

*   **From Single GPU to Cluster:** Ensures optimization strategies (e.g., data loading, parallelism) scale effectively.
*   **Elastic Training:** Allows the training job to dynamically adapt to a changing number of available GPUs (nodes joining/leaving).
*   **Fault Tolerance:** Implements mechanisms to resume training seamlessly after hardware or software failures.
*   **Monitoring and Alerting:** Tracks system health, training progress, and inference metrics, triggering alerts for anomalies.


#### **XIII. IMPLEMENTATION ROADMAP & ADVANCED TECHNIQUES**

This section provides a strategic timeline for applying these methods. This is a phased guide for practitioners, moving from essential single-GPU techniques to advanced multi-system production deployment, along with specialized strategies for core training and fine-tuning stability.

##### **A. Phased Implementation Roadmap** (From Fine-Tuning to Deployment)

Implementation moves from Foundation (using QLoRA and Mixed Precision on one GPU) to Intermediate (adding Multi-GPU sharding) and finally Production (hardware-specific tuning and automated serving).

**Phase 1: Foundation (Single GPU)**

*   **Start with QLoRA:** 4-bit quantized base model + Low-Rank Adaptation for memory-efficient fine-tuning.
*   **Add Gradient Checkpointing:** Trade computation time for memory to enable larger batch sizes or sequence lengths.
*   **Implement Mixed Precision:** Use BF16 for forward/backward passes and FP32 for master weights to maintain stability.
*   **Apply Basic Regularization:** Attention dropout and weight decay to prevent overfitting.

**Phase 2: Intermediate Optimization (Multi-GPU)**

*   **Add ZeRO Optimization:** Level 2 or 3 for efficient multi-GPU training by sharding optimizer states or full parameters.
*   **Implement Advanced LoRA:** Use AdaLoRA (adaptive rank allocation) or DoRA (weight decomposition) for better parameter efficiency.
*   **Add Knowledge Distillation:** Train a smaller, faster "student" model using the larger "teacher" model if a smaller deployment model is needed.
*   **Optimize Data Pipeline:** Implement dynamic batching and memory-mapped data loading for maximum throughput.

**Phase 3: Advanced Optimization (Large-Scale)**

*   **Implement 3D Parallelism:** Combine Data, Tensor (Pipeline), and Sequence Parallelism for models with hundreds of billions of parameters.
*   **Add QAT (Quantization-Aware Training):** Simulate quantization during fine-tuning for higher accuracy when deploying to quantized hardware.
*   **Integrate Model Compression:** Apply gradual pruning or sparse training during fine-tuning.
*   **Optimize Communication:** Use gradient compression (e.g., 1-bit Adam) and asynchronous updates to reduce multi-node communication overhead.

**Phase 4: Production Deployment**

*   **Hardware-Specific Tuning:** Re-optimize kernels and configuration for the exact target deployment hardware (e.g., specific GPU generation).
*   **Automated Optimization:** Use hyperparameter tuning and automated strategy selection to find the optimal deployment configuration.
*   **Monitoring and Adaptation:** Implement continuous A/B testing and runtime metric analysis to adapt strategies dynamically.
*   **Fault Tolerance:** Build robust, resumable training and inference pipelines for production environments.

##### **B. Advanced Training Optimizations** (Fine-Tuning)

These focus on stability. During fine-tuning, the goal is to avoid Catastrophic Forgetting—where the model learns a new task but forgets its basic language skills. This is managed through lower learning rates and selective layer unfreezing.

**Training vs. Fine-tuning Use Cases:**

*   **Training Focus:** Stability over long runs, fast convergence, preventing overfitting on vast datasets, choosing optimizers for scale (e.g., AdamW, LAMB).
*   **Fine-tuning Focus:** Avoiding catastrophic forgetting of pre-trained knowledge, adapting efficiently to a specific task's "loss landscape," preventing overfitting to small datasets, specialized learning rate schedules.

**When to Use Specific Techniques:**

*   **In Training:**

    *   **AdamW Optimizer:** Use as the default for most large-scale pre-training tasks due to its robust handling of weight decay. Tune beta parameters (`betas=(0.9, 0.95)` is common for LLMs) and weight decay (typically `0.1`).
    *   **Learning Rate Warmup:** Essential during early training to prevent instability, typically for 0.5-2% of total steps. Use when training from random initialization to allow gradient statistics to stabilize.
    *   **Learning Rate Decay (Cosine/Linear):** Apply after warmup when you observe a plateau in training loss. Cosine decay works well when training for a fixed budget, while step decay helps if training progress stalls at specific intervals.
    *   **Gradient Clipping:** Use when encountering loss spikes or training divergence, particularly in the first few thousand steps. Crucial for stability with large batch sizes (>1024) or high learning rates.
    *   **Weight Averaging (EMA/SWA):** Apply during the final 10-25% of training when you want improved generalization. Particularly effective when training curves show oscillation near convergence.
    *   **Batch Size Scaling:** Increase batch size when throughput is limited by data parallelism overhead, typically when using 8+ GPUs. Scale learning rate proportionally (`lr ∝ √batch_size`).

*   **In Fine-tuning:**

    *   **Lower Learning Rates:** Use when adapting pre-trained models, typically 1e-5 to 1e-3 (vs 1e-4 to 1e-3 for pre-training). More aggressive tasks require higher rates within this range, while minor adaptations benefit from lower rates.
    *   **Cosine Annealing:** Ideal for short fine-tuning runs (1-10 epochs) where you want smooth adaptation without abrupt learning rate drops that could destabilize pre-trained weights.
    *   **Selective Unfreezing:** Use when fine-tuning small datasets (<10k examples). Start with only unfreezing the final layer or attention outputs, then gradually unfreeze deeper layers if underfitting persists.
    *   **Early Stopping:** Critical when fine-tuning on datasets <100k examples to prevent catastrophic forgetting of pre-trained knowledge. Monitor validation loss closely and stop when it plateaus or begins increasing.
    *   **Layer-wise Learning Rate Decay:** Apply when fine-tuning all layers, decreasing learning rates for earlier layers (e.g., 0.95 decay per layer backward). Helps preserve foundational knowledge while adapting upper layers.
    *   **Gradient Accumulation:** Use when hardware constraints prevent desired batch sizes. Accumulate gradients over multiple micro-batches to simulate larger effective batch sizes without OOM errors.

**Advanced Contextual Applications:**

*   **When Training with Long Context Windows (>8k tokens):** Use FlashAttention-2, gradient checkpointing, and sequence parallelism simultaneously. Consider switching from AdamW to Lion optimizer for better memory efficiency.
*   **When Fine-tuning with Limited Data (<1k examples):** Combine LoRA with strong regularization (dropout=0.3-0.5), use K-fold cross-validation, and apply mixup or manifold mixup in embedding space.
*   **When Training MoE Models:** Use higher learning rates (1.5-2× standard), expert balancing loss, and router z-loss for stability. Implement capacity factor scheduling to handle varying token distributions.
*   **When Fine-tuning for Multiple Tasks Simultaneously:** Use adapter composition, task embeddings with hypernetworks, or gradient surgery to prevent interference between task gradients.
*   **When Training with Noisy or Web-Scale Data:** Implement robust optimization (SAM, ASAM), use graduated optimization with curriculum learning, and apply loss truncation or dynamic data selection.

**Timing & Orchestration:**

*   **Phase-based Optimization:** Start with conservative settings (low LR, no clipping) and introduce optimizations reactively based on monitoring: add gradient clipping if loss spikes occur, introduce weight averaging after initial convergence.
*   **Diagnostic-Driven Selection:** Use gradient norm monitoring to determine if gradient clipping is needed; track weight updates relative to weight magnitudes to adjust learning rates; monitor attention entropy to determine if different layer learning rates are warranted.
*   **Resource-Aware Configuration:** With limited GPU memory, prioritize gradient checkpointing over batch size scaling; with fast interconnects (NVLink), favor data parallelism over model parallelism; with heterogeneous hardware, use pipeline parallelism across different GPU types.

#### **XIV. PRACTICAL DECISION FRAMEWORK**

This is a step-by-step guide to help choose the right optimization path, followed by concrete, actionable recommendations for common real-world scenarios.

##### **A. Decision Trees**

**For Pre-training a New LLM:**

1. **Start** by determining model size and hardware constraints.
2. **Choose Architecture** between Dense for standard training or Mixture of Experts for sparse activation.
3. **Add Mixed Precision** using FP8 or BF16 for compute efficiency with FP32 master weights for stability.
4. **Add Attention Optimization** using FlashAttention-2 for training with long sequences.
5. **Add Parallelism Strategy**: Begin with Data Parallelism for moderate GPU clusters, then incorporate Tensor Parallelism for larger setups, and finally implement Pipeline Parallelism for extensive multi-GPU systems.
6. **Add Gradient Checkpointing** when dealing with sequence lengths beyond two thousand tokens or when facing memory constraints.
7. **Add Regularization** including dropout, weight decay, and gradient clipping.
8. **Train** with learning rate warmup, cosine decay scheduling, and the AdamW optimizer.
9. **Apply Post-training Optimization** through quantization, pruning, and knowledge distillation.
10. **Deploy** with appropriate serving infrastructure.

**For Fine-tuning an Existing LLM:**

1. **Start** by evaluating dataset size, task complexity, and hardware availability.
2. **Choose PEFT Method**: Select LoRA for standard use, QLoRA for memory-constrained environments, or full fine-tuning for large datasets.
3. **Add Mixed Precision** using BF16 for computational efficiency.
4. **Add Gradient Accumulation** to simulate larger batch sizes.
5. **Evaluate the Need for Distillation** if your deployment target has memory constraints, then proceed to knowledge distillation.
6. **Add Task-specific Tuning** including extended context handling, specialized tokenization, and task prompts.
7. **Add Deployment Optimization** through quantization-aware fine-tuning if targeting quantized deployment.
8. **Deploy** using either adapter merging or separate adapter hosting.

**Conditional Branches:**

* When training on GPUs with limited memory, default to the QLoRA path.
* When working with very long sequences, always implement FlashAttention with gradient checkpointing.
* When dealing with small datasets, enforce strong regularization and early stopping.
* When building multi-task systems, implement multiple LoRA adapters with a routing mechanism.
* When latency is critical, implement TensorRT-LLM with speculative decoding.

##### **B. Key Differences: Training vs. Fine-tuning**

Understanding the distinct goals and constraints is crucial. The **primary goal** differs fundamentally: training aims to **learn a general language representation** from scratch, while fine-tuning seeks to **adapt a pre-trained model to a specific task or domain**.
- Training operates on billions of tokens with a compute budget spanning months across thousands of GPUs, whereas fine-tuning typically uses thousands to millions of tokens over hours or days on a smaller cluster of GPUs.
- Consequently, the optimization priorities shift. Training focuses on throughput optimization and stability, emphasizing raw speed, while fine-tuning prioritizes parameter efficiency and task accuracy, with a core focus on fitting the model into available memory.
- The scope of changes also varies. Training involves fundamental architectural decisions, while fine-tuning makes only lightweight modifications, primarily through Parameter-Efficient Fine-Tuning methods.
- Finally, the risk tolerance differs. Training has lower tolerance for failure as restarting is extremely costly, while fine-tuning offers higher tolerance as experiments can be retried easily with different adapters or data.

##### **C. Specific Scenarios & Recommendations**

**Scenario 1: Training a 70B Parameter Model from Scratch**

* Use 3D parallelism combining Data, Tensor, and Pipeline Parallelism with ZeRO-3 optimization, BF16 mixed precision, FlashAttention-2, gradient checkpointing, AdamW with specific beta parameters, and weight decay.
* Avoid pruning or quantization during training, PEFT methods, and low-precision optimizers.
* Consider pipeline bubble optimization through interleaving, activation recomputation strategy, and gradient accumulation for large global batch sizes.

**Scenario 2: Fine-tuning GPT-4 for Medical QA with Sensitive Data**

* Use QLoRA with specific rank and alpha settings, BF16 precision, gradient accumulation with eight steps, causal attention mask preservation, and differential privacy.
* Consider task-specific architectural tuning such as extending context windows, specialized medical tokenization, and retrieval-augmented generation integration.
* Avoid full fine-tuning due to cost, low-rank adaptation that may lose medical nuance, and aggressive quantization before proper evaluation.

**Scenario 3: Deploying Llama-3 to Mobile Phones for Offline Chat**

* Use INT4 quantization through GPTQ or AWQ methods, structured pruning with fifty percent sparsity, vocabulary pruning to thirty-two thousand tokens, knowledge distillation from larger models, and CoreML or TFLite conversion.
* Follow crucial steps: first fine-tune on conversational data, then apply progressive compression through pruning, quantization, and distillation, and finally test on-device with memory and thermal constraints.
* Target metrics including model size under five hundred megabytes, response time under two seconds, RAM usage under one gigabyte, and battery drain under five percent per hour.

**Scenario 4: Enterprise Multi-Task Assistant for Code, Documentation, and Support**

* Use modular LoRA adapters per domain, Mixture of Experts routing, model soups for stable ensemble creation, and PEFT with task-conditioned attention.
* Implement a strategy using a base model with extended context windows, separate adapters for different programming languages and document types, dynamic routing based on query type, and weighted ensembles for ambiguous queries.
* Deploy with adapter hosting featuring hot-swapping capabilities, request-based adapter loading, and caching for frequent task combinations.

**Scenario 5: Academic Research with Limited GPU Resources**

* For training, only consider models under seven billion parameters using 3D parallelism within nodes, gradient checkpointing, and CPU offloading for larger models.
* For fine-tuning, focus on QLoRA for models up to seventy billion parameters, efficient data pipelines, selective adaptation targeting only attention layers, and hyperparameter tuning.
* Follow an optimal path starting with pre-trained models, applying QLoRA on domain-specific data, comparing adapters across tasks, and distilling the best adapter to smaller models when necessary.

**Scenario 6: Real-Time Translation Service with High Request Rates**

* Use vLLM with paged attention, continuous batching, FP8 KV cache quantization, tensor parallel inference across multiple GPUs, and request prioritization queues.
* Implement optimizations including prefix caching for common language pairs, speculative decoding with compact draft models, model warm-up to prevent cold starts, and regional model sharding.
* Establish service level objectives targeting specific latency percentiles, token throughput per GPU, system availability, and graceful degradation under load.

**Scenario 7: Financial Analysis with Strict Determinism Requirements**

* Use fully deterministic training with fixed seeds and deterministic algorithms, model checkpointing with hash verification, and experiment tracking with comprehensive reproducibility manifests.
* Maintain constraints including no dropout during inference, fixed quantization seeds, version-controlled data pipelines, and audit trails for all predictions.
* Validate through backtesting on historical data, sensitivity analysis to random seeds, and statistical equivalence tests across multiple runs.

**Scenario 8: Edge AI on NVIDIA Jetson for Robotics Applications**

* Use TensorRT-LLM compilation, INT8 quantization with calibration, layer fusion, persistent kernel compilation, and power-optimized execution profiles.
* Account for constraints including thermal throttling management, memory bandwidth optimization, mixed precision with FP16 fallbacks, and real-time scheduling requirements.
* Deploy with model partitioning across GPU and CPU resources, adaptive batch sizing based on system load, and failure recovery without requiring system reboot.

**Scenario 9: Continual Learning System with Streaming Data**

* Use elastic weight consolidation, progressive neural networks, experience replay buffers, and regularization-based continual learning approaches.
* Implement strategies including base models with expanding adapter architectures, task-conditioned masking, catastrophic forgetting monitoring, and automated task detection.
* Deploy with rolling window fine-tuning, adapter versioning, performance preservation weighting, and drift detection algorithms.

**Scenario 10: Cross-Platform Deployment Across Web, Mobile, and Desktop**

* Use ONNX Runtime universal export, platform-specific optimizations for different hardware, and adaptive model selection based on client capabilities.
* Follow an approach creating a single trained model, multiple compiled versions, client capability detection, and appropriate model delivery.
* Optimize through model slicing for progressive loading, differential updates, cache-aware partitioning, and bandwidth-adaptive quality levels.

#### **IX. IMPLEMENTATION ROADMAP**

**Phase 1: Foundation (Single GPU)**
1. **Start with QLoRA:** 4-bit quantization + LoRA adaptation.
2. **Add Gradient Checkpointing:** Reduce memory for larger batch sizes.
3. **Implement Mixed Precision:** BF16 for forward/backward, FP32 master weights.
4. **Apply Basic Regularization:** Attention dropout and weight decay.

**Phase 2: Intermediate Optimization**
1. **Add ZeRO Optimization:** Level 2 or 3 for multi-GPU training.
2. **Implement Advanced LoRA:** AdaLoRA or DoRA for better parameter efficiency.
3. **Add Knowledge Distillation:** If smaller deployment model needed.
4. **Optimize Data Pipeline:** Dynamic batching and efficient loading.

**Phase 3: Advanced Optimization**
1. **Implement 3D Parallelism:** For very large models.
2. **Add QAT:** For deployment to quantized hardware.
3. **Integrate Model Compression:** Pruning during fine-tuning.
4. **Optimize Communication:** Gradient compression and asynchronous updates.

**Phase 4: Production Deployment**
1. **Hardware-Specific Tuning:** Optimize for target deployment hardware.
2. **Deployment Optimizations:** Quantization, pruning, compilation.
3. **Serving Infrastructure:** vLLM, TensorRT-LLM, speculative decoding.
4. **Monitoring and Adaptation:** Continuous optimization based on runtime metrics.

# Optimization Methods Used in the Project

The tutorial implements a wide range of optimization methods across multiple categories:

**Precision Training and Quantization**
- **Automatic Mixed Precision (AMP)**
- **Dynamic Loss Scaling**
- **4-bit Quantization (NF4)**
- **Double Quantization**

**Parameter-Efficient Fine-Tuning (PEFT)**
- **LoRA (Low-Rank Adaptation)**
- **QLoRA**
- **DoRA (Weight-Decomposed LoRA)**
- **VeRA (Vector-based Random Matrix Adaptation)**
- **AdaLoRA**
- **IA3 (Infused Adapter)**
- **BitFit (Bias-Only Fine-tuning)**
- **Prompt Tuning and Prefix Tuning**

**Memory and Compute Optimization**
- **Gradient Checkpointing**
- **Gradient Accumulation**
- **8-bit Optimizers (AdamW8bit)**
- **ZeRO Optimization (Stage 1-3)**
- **CPU Offloading**

**Distributed Training**
- **FSDP (Fully Sharded Data Parallel)**
- **DeepSpeed Integration**
- **JAX Optimizations**

**Deployment Optimizations**
- **vLLM with PagedAttention**
- **Continuous Batching**
- **Speculative Decoding**
- **KV Cache Quantization**

**Model Compression**
- **Pruning (Structured/Unstructured)**
- **Token Merging (ToMe)**
- **Knowledge Distillation**

# LLM Models Used in the Project

**Primary Demonstration Models**

**google/gemma-3-270m** 

- The main model used throughout the tutorial for demonstrating optimization techniques. This is Google's lightweight 270 million parameter model, chosen for its manageable size that allows rapid experimentation while maintaining representative LLM behavior. It serves as the foundation for exploring all optimization methods, including mixed precision training, quantization, and parameter-efficient fine-tuning.

**google/gemma-3-270m-it** 

- The instruction-tuned variant of the 270 million parameter model, used in scenarios requiring conversational capabilities and task-specific behaviors. This version is particularly useful for demonstrating fine-tuning on question-answering datasets and evaluating the impact of optimizations on instruction-following performance.

**google/gemma-3-1b-it** 

- A larger 1 billion parameter instruction-tuned model used as a teacher model in knowledge distillation experiments. It serves as a baseline for comparing optimization effectiveness across different model scales and demonstrates how larger models can transfer knowledge to smaller student models.

**google/gemma-3-1b-pt** 

- The pre-trained (non-instruction tuned) version of the 1 billion parameter Gemma model, used in specific optimization scenarios where base model behavior is preferred over instruction-tuned variants, such as in certain pruning and quantization experiments.

**google/gemma-3-4b-it** 

- A 4 billion parameter instruction-tuned model referenced in multi-teacher distillation setups. While not fully executed in all experiments due to computational constraints, it represents the larger teacher models that would be used in production distillation pipelines.

**meta-llama/Llama-3.2-1B** 

- Meta's 1 billion parameter Llama 3.2 model, used as an alternative demonstration platform for optimizations requiring different architectural characteristics. It features Grouped-Query Attention (GQA) with 32 query heads and 8 KV heads, providing a 4x KV cache compression ratio. This model is employed in experiments involving structural pruning, attention mechanism optimization, and comparative analysis with Gemma architectures.

**meta-llama/Llama-3.2-1B-Instruct** 

- The instruction-tuned version of Llama 3.2 1B, used in scenarios requiring conversational abilities. This model demonstrates how optimization techniques apply to models specifically trained for dialogue and instruction-following tasks.

**meta-llama/Llama-2-7b-hf** 

- A 7 billion parameter Llama 2 model used in more computationally intensive optimization experiments, particularly in structured pruning demonstrations where its larger size makes pruning effects more visible. It features 32 layers, 32 attention heads per layer, and an intermediate size of 11008, making it representative of mid-sized production LLMs.

**microsoft/Phi-tiny-MoE-instruct** 

- A small Mixture-of-Experts model used to demonstrate MoE-specific optimization techniques. This model contains multiple expert networks with a router that selects which experts to activate per token. It is employed in experiments involving top-k gating, capacity factor management, expert load balancing, and sparse expert updates. The model's architecture allows demonstration of auxiliary loss coefficients and expert specialization techniques without the computational overhead of larger MoE models.

**openai-community/gpt2** 

- The classic GPT-2 model used in specific experiments where architectural simplicity is beneficial, particularly in attention-guided prefix allocation demonstrations. Its well-understood architecture makes it ideal for illustrating fundamental concepts without the complexity of modern architectural optimizations.

**Qwen/Qwen2-0.5B-Instruct** 

- A 500 million parameter instruction-tuned model from the Qwen family, used in sparse prefix tuning experiments. Its smaller size makes it suitable for demonstrating extreme parameter efficiency techniques where only a tiny fraction of parameters are updated during fine-tuning.

**Model Characteristics Summary**

The tutorial leverages models ranging from 270 million to 7 billion parameters, spanning multiple families (Gemma, Llama, Phi, GPT-2, Qwen) to demonstrate optimization techniques across different architectures. The primary focus is on Gemma-3-270m for most demonstrations due to its balanced size and modern architecture, while larger models like Llama-2-7b and Gemma-3-1b serve as teachers or platforms for more advanced techniques like pruning and distillation.

Each model was selected to highlight specific optimization challenges: Gemma models demonstrate modern architectural features like GQA, Phi-tiny-MoE showcases sparse expert activation, and GPT-2 provides a simpler baseline for fundamental concept explanations.

# Project Remarks

Due to most of optimization techniques in this notebook will use google/gemma-3-270m for demonstration, its tokenizer will be written as a function for easy application. Some optimization methods that have to use another model will have its own tokenizer within those optimization sections.

This notebook is structured as a tutorial project, so the required libraries and modules will be imported within each optimization method section, allowing for an isolated and clear exploration of each technique.

**Gemma-3-270m Tokenizer Function**

The primary model used throughout this tutorial is google/gemma-3-270m. This is a small, efficient version of Google's Gemma 3 family, containing approximately 270 million parameters, making it suitable for demonstration on a variety of hardware.

For convenience and code reusability, a dedicated tokenization function is defined for the google/gemma-3-270m model. This function takes a raw text example from the Q&A dataset and formats it into a structure the model can understand. It wraps the question and answer with special tokens like <bos> (beginning of sequence) and <eos> (end of sequence), and adds labels for training. The function then uses the model's tokenizer to convert this text into input_ids and an attention_mask, truncating or padding the sequences to a consistent maximum length. The tokenized output is returned as PyTorch tensors.

**A Note on Tokenizers in this Tutorial**

While the gemma-3-270m tokenizer is the default, some optimization techniques, such as Multi-Teacher Distillation, require loading larger "teacher" models like google/gemma-3-1b-it or google/gemma-3-4b-it. In those specific sections, the necessary tokenizer for that particular model will be loaded and used independently, ensuring that all tokenization is appropriate for the models involved in the optimization. This modular approach keeps the code clear and functional for each distinct optimization method.

# Data Dictionary

The structure of the folder shown in the images is as follows:

    \main
        \Answers.csv (1.61 GB)
        \Questions.csv (1.92 GB)
        \Tags.csv

**Answers.csv**

This file contains approximately 2.01 million responses to questions.

<style type="text/css">
.tg  {border-collapse:collapse;border-spacing:0;}
.tg td{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
  overflow:hidden;padding:10px 5px;word-break:normal;}
.tg th{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
  font-weight:normal;overflow:hidden;padding:10px 5px;word-break:normal;}
.tg .tg-0thz{border-color:inherit;font-weight:bold;text-align:left;vertical-align:bottom}
.tg .tg-j6zm{font-weight:bold;text-align:left;vertical-align:bottom}
.tg .tg-7zrl{text-align:left;vertical-align:bottom}
.tg .tg-0lax{text-align:left;vertical-align:top}
</style>
<table class="tg"><thead>
  <tr>
    <th class="tg-0thz">Column</th>
    <th class="tg-j6zm">Data Type</th>
    <th class="tg-j6zm">Description</th>
    <th class="tg-j6zm">Key Statistics</th>
  </tr></thead>
<tbody>
  <tr>
    <td class="tg-7zrl">Id</td>
    <td class="tg-7zrl">Integer</td>
    <td class="tg-7zrl">Unique identifier for the answer.</td>
    <td class="tg-0lax">Range: 92 to 40M</td>
  </tr>
  <tr>
    <td class="tg-7zrl">OwnerUserId</td>
    <td class="tg-7zrl">Integer</td>
    <td class="tg-7zrl">Unique identifier of the user who wrote the answer.</td>
    <td class="tg-0lax">469k unique users</td>
  </tr>
  <tr>
    <td class="tg-7zrl">CreationDate</td>
    <td class="tg-7zrl">DateTime</td>
    <td class="tg-7zrl">The date and time when the answer was posted.</td>
    <td class="tg-0lax">Aug 2008 – Oct 2016</td>
  </tr>
  <tr>
    <td class="tg-7zrl">ParentId</td>
    <td class="tg-7zrl">Integer</td>
    <td class="tg-7zrl">The Id of the question this post is answering (Foreign Key).</td>
    <td class="tg-0lax">Matches Question Id</td>
  </tr>
  <tr>
    <td class="tg-7zrl">Score</td>
    <td class="tg-7zrl">Integer</td>
    <td class="tg-7zrl">The net upvotes/downvotes received for the answer.</td>
    <td class="tg-0lax">Mean: 2.48 (Max: 5718)</td>
  </tr>
  <tr>
    <td class="tg-7zrl">Body</td>
    <td class="tg-7zrl">String/HTML</td>
    <td class="tg-7zrl">The full text content of the answer.</td>
    <td class="tg-0lax">2.01M unique entries</td>
  </tr>
</tbody></table>

**Questions.csv**

This file contains approximately 1.26 million original questions.

<style type="text/css">
.tg  {border-collapse:collapse;border-spacing:0;}
.tg td{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
  overflow:hidden;padding:10px 5px;word-break:normal;}
.tg th{border-color:black;border-style:solid;border-width:1px;font-family:Arial, sans-serif;font-size:14px;
  font-weight:normal;overflow:hidden;padding:10px 5px;word-break:normal;}
.tg .tg-0thz{border-color:inherit;font-weight:bold;text-align:left;vertical-align:bottom}
.tg .tg-j6zm{font-weight:bold;text-align:left;vertical-align:bottom}
.tg .tg-7zrl{text-align:left;vertical-align:bottom}
.tg .tg-0lax{text-align:left;vertical-align:top}
</style>
<table class="tg"><thead>
  <tr>
    <th class="tg-0thz">Column</th>
    <th class="tg-j6zm">Data Type</th>
    <th class="tg-j6zm">Description</th>
    <th class="tg-j6zm">Key Statistics</th>
  </tr></thead>
<tbody>
  <tr>
    <td class="tg-7zrl">Id</td>
    <td class="tg-7zrl">Integer</td>
    <td class="tg-7zrl">Unique identifier for the question.</td>
    <td class="tg-0lax">Range: 80 to 40M</td>
  </tr>
  <tr>
    <td class="tg-7zrl">OwnerUserId</td>
    <td class="tg-7zrl">Integer</td>
    <td class="tg-7zrl">Unique identifier of the user who asked the question.</td>
    <td class="tg-0lax">631k unique users</td>
  </tr>
  <tr>
    <td class="tg-7zrl">CreationDate</td>
    <td class="tg-7zrl">DateTime</td>
    <td class="tg-7zrl">The date and time when the question was posted.</td>
    <td class="tg-0lax">Aug 2008 – Oct 2016</td>
  </tr>
  <tr>
    <td class="tg-7zrl">ClosedDate</td>
    <td class="tg-7zrl">DateTime</td>
    <td class="tg-7zrl">The date/time the question was closed (if applicable).</td>
    <td class="tg-0lax">96 percent are "NA" (Open)</td>
  </tr>
  <tr>
    <td class="tg-7zrl">Score</td>
    <td class="tg-7zrl">Integer</td>
    <td class="tg-7zrl">The net upvotes/downvotes received for the question.</td>
    <td class="tg-0lax">Mean: 1.78 (Max: 5190)</td>
  </tr>
  <tr>
    <td class="tg-7zrl">Title</td>
    <td class="tg-7zrl">String</td>
    <td class="tg-7zrl">The short summary or headline of the question.</td>
    <td class="tg-0lax">1.26M unique titles</td>
  </tr>
  <tr>
    <td class="tg-7zrl">Body</td>
    <td class="tg-7zrl">String/HTML</td>
    <td class="tg-7zrl">The detailed text description of the problem.</td>
    <td class="tg-0lax">1.26M unique entries</td>
  </tr>
</tbody></table>

**Tags.csv** 

It contains the tags on each of these questions

# Setup Environment

In [5]:
%%capture
!pip install polars beautifulsoup4 markdownify
!pip install rouge-score nltk
#!pip install transformers

# Upgrade Libraries to compatible with new version of pre-trained model
!pip install --upgrade polars beautifulsoup4 markdownify
#!pip install --upgrade numpy
!pip install --upgrade transformers datasets huggingface-hub peft accelerate bitsandbytes evaluate
#!pip install jax

# Check CUDA compatible with your PyTorch version if you have to upgrade PyTorch in your environment
# https://pytorch.org/get-started/previous-versions/
#!pip install torch==2.9.1 torchvision==0.24.1 torchaudio==2.9.1 --index-url https://download.pytorch.org/whl/cu126
#!pip install --uograde torch==2.9.1 torchvision==0.24.1 torchaudio==2.9.1 --index-url https://download.pytorch.org/whl/cu126

# For model fine tuning optimization
!pip install deepspeed
!pip install --upgrade deepspeed
!apt-get update -y
!apt-get install -y libaio-dev

In [1]:
import os
import collections
import math
import logging
import numpy as np
import pandas as pd
import polars as pl
from bs4 import BeautifulSoup
from sklearn.model_selection import train_test_split

# Resource monitoring
import time
import threading
import psutil
import platform
import sys
import subprocess
import importlib.util
import deepspeed
from zipfile import ZipFile

# huggingface ecosystem
import torch
from datasets import Dataset, DatasetDict
from huggingface_hub import login
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    TrainingArguments,
    Trainer,
    TrainerCallback,
    DataCollatorForLanguageModeling,
    AutoConfig
)
import transformers
import transformers.utils.import_utils

os.environ["TOKENIZERS_PARALLELISM"] = "false"

login("YOUR_HUGGINGFACE_ACCESS_TOKEN")

nltk.download('punkt', quiet=True)

/usr/local/lib/python3.11/dist-packages/torchvision/io/image.py:13: UserWarning: Failed to load image Python extension: 'Could not load this library: /usr/local/lib/python3.11/dist-packages/torchvision/image.so'If you don't plan on using image functionality from `torchvision.io`, you can ignore this warning. Otherwise, there might be something wrong with your environment. Did you have `libjpeg` or `libpng` installed before building `torchvision` from source?
  warn(

True

In [3]:
def get_os_info():
    return platform.system(), platform.release()

def get_python_info():
    return sys.version.split()[0]

def get_cpu_info():
    return platform.processor(), psutil.cpu_count(logical=False), psutil.cpu_count(logical=True)

def get_memory_info():
    mem = psutil.virtual_memory()
    return mem.total / (1024 ** 3), mem.available / (1024 ** 3)

def get_gpu_info():
    """Detailed GPU check for LLM suitability."""
    try:
        # Query Name, Driver, and Total Memory
        result = subprocess.run(
            ["nvidia-smi", "--query-gpu=name,driver_version,memory.total", "--format=csv,noheader,nounits"],
            capture_output=True, text=True, check=True
        )
        gpus = []
        for line in result.stdout.strip().split('\n'):
            name, driver, mem_total = line.split(', ')
            gpus.append({
                'name': name, 
                'driver': driver, 
                'vram_gb': float(mem_total) / 1024
            })
        
        # Get CUDA version
        cuda_result = subprocess.run(["nvidia-smi"], capture_output=True, text=True)
        cuda_version = "N/A"
        for line in cuda_result.stdout.split('\n'):
            if "CUDA Version" in line:
                cuda_version = line.split(":")[-1].strip().split()[0]
                break
        return gpus, cuda_version
    except Exception:
        return "N/A", "N/A"

def check_jax():
    """Checks if JAX can see GPUs for parallelism."""
    try:
        import jax
        backend = jax.lib.xla_bridge.get_backend().platform
        devices = jax.device_count()
        return f"Detected (Backend: {backend}, Devices: {devices})"
    except Exception:
        return "Not Installed or No GPU Backend"

def check_deepspeed():
    return deepspeed.__version__ if importlib.util.find_spec("deepspeed") else "Not Installed"

# Execution
os_name, os_version = get_os_info()
python_ver = get_python_info()
cpu_name, cpu_cores, cpu_threads = get_cpu_info()
total_mem, avail_mem = get_memory_info()
gpus, cuda_ver = get_gpu_info()
jax_status = check_jax()
ds_version = check_deepspeed()

print(f"--- System: {os_name} {os_version} | Python: {python_ver} ---")
print(f"--- CPU: {cpu_name} ({cpu_cores} Cores) | RAM: {total_mem:.2f} GB ---")

print("\n--- GPU & Parallelism Optimization ---")
if gpus == "N/A":
    print("No NVIDIA GPU detected.")
else:
    for i, g in enumerate(gpus):
        # Optimization Check: LLMs usually need > 16GB for comfortable fine-tuning
        suitability = "High" if g['vram_gb'] >= 24 else "Medium/Low (Needs LoRA/Quantization)"
        print(f"GPU {i+1}: {g['name']} | VRAM: {g['vram_gb']:.2f} GB | Suitability: {suitability}")
    print(f"CUDA Version: {cuda_ver}")

print(f"\n--- Frameworks ---")
print(f"JAX Parallelism: {jax_status}")
print(f"DeepSpeed: {ds_version}")

# Final Verdict for Parallelism
if isinstance(gpus, list) and len(gpus) > 1:
    print("\nVERDICT: Multi-GPU detected. Parallelism (FSDP/JAX pmap) is AVAILABLE.")
else:
    print("\nVERDICT: Single GPU or No GPU. Parallelism restricted to single-device optimizations.")

--- System: Linux 5.19.0-45-generic | Python: 3.11.7 ---
--- CPU: x86_64 (8 Cores) | RAM: 44.08 GB ---

--- GPU & Parallelism Optimization ---
GPU 1: NVIDIA RTX A4000 | VRAM: 15.99 GB | Suitability: Medium/Low (Needs LoRA/Quantization)
CUDA Version: 12.4

--- Frameworks ---
JAX Parallelism: Not Installed or No GPU Backend
DeepSpeed: 0.18.6

VERDICT: Single GPU or No GPU. Parallelism restricted to single-device optimizations.

# Download Dataset

In [ ]:
# configuring the path of Kaggle.json file
!mkdir -p ~/.kaggle
!cp kaggle.json ~/.kaggle/
!chmod 600 ~/.kaggle/kaggle.json

In [ ]:
%%capture
# Download dataser via API
!pip install kaggle
#!/bin/bash
!kaggle datasets download stackoverflow/stacksample

In [ ]:
# extracting the compessed Dataset
dataset = 'stacksample.zip'

with ZipFile(dataset,'r') as zip:
  zip.extractall()
  print('The dataset is extracted')

# Data Loading

This section performs data extraction, filtering, and cleaning for a Question & Answer dataset. It focuses on isolating high-quality content while managing computational resources.

**1. HTML Cleaning Function**

The `clean_html` function handles the conversion of raw web text into a readable format.
- Safety Check: It returns an empty string if the input is null or empty.
- Parsing: It uses the BeautifulSoup library to interpret the HTML tags.
- Extraction: The `get_text` method removes tags like `<div>, <p>, or <code>`.
- Formatting: The `separator=' '` ensures that words separated by tags don't get smashed together (e.g., `<li>A</li><li>B</li>` becomes "A B" instead of "AB"), and `strip=True` removes unnecessary whitespace.

**2. Question Data Loading (Questions.csv)**

The code uses the Polars library (an extremely fast alternative to Pandas) to read the data.
- Encoding: It uses utf8-lossy to handle any corrupted characters or symbols often found in technical forum posts.
- Selection: It only pulls specific columns (`Id, Title, Body, Score`) into memory to save VRAM/RAM.
- Quality Filter: It applies `.filter(pl.col("Score") > 5)`, ensuring that only questions with a positive community rating are kept.

**3. Answer Data Loading (Answers.csv)**

Similar to the questions, the answer dataset is loaded and filtered.
- Relational Mapping: It includes the ParentId column, which is necessary to link these answers back to their corresponding questions.
- Quality Filter: It also enforces a Score > 5 rule to ensure the model eventually learns from "good" answers rather than downvoted ones.

**4. Sampling and Resource Management**

To ensure the script runs within "computational limitations," the final step narrows the scope.
- Sorting: It sorts the questions by Score in descending order.
- Top-K Selection: It takes only the top 200 highest-rated questions. By training or evaluating on a small subset of the "best" data, the script ensures high-quality results without requiring a supercomputer to process thousands of rows.

In [3]:
def clean_html(text):
    if not text:
        return ""
    soup = BeautifulSoup(text, 'html.parser')
    return soup.get_text(separator=' ', strip=True)

# Load with proper encoding (filter for answer score more than 5)
questions = pl.read_csv(
    "Questions.csv",
    encoding="utf8-lossy",
    columns=["Id", "Title", "Body", "Score"]
).filter(pl.col("Score") > 5)

answers = pl.read_csv(
    "Answers.csv",
    encoding="utf8-lossy",
    columns=["Id", "ParentId", "Body", "Score"]
).filter(pl.col("Score") > 5)

# Only samples data due to computational limitation
questions = questions.sort("Score", descending=True).head(200)

# Data Preprocessing

This section performs the final transformation and merging steps to create a clean, paired dataset for training or evaluation. It leverages the Polars library's expression system to process text and link related data points.

**1. Applying Text Cleaning**

The code uses the `with_columns` method to modify existing data without changing the structure of the dataframe.
- Cleaning HTML: It applies the previously defined `clean_html` function to the "Body" column of both questions and answers using `map_elements`. The `return_dtype=pl.Utf8` tells Polars to expect a string (UTF-8) back, which helps maintain the library's speed and type safety.
- Stripping Whitespace: For question titles, it uses the built-in `.str.strip_chars()` method. This is a vectorized operation that efficiently removes leading and trailing spaces or newline characters.

**2. Inner Join (Linking Answers to Questions)**

The most critical part of this block is the join operation, which connects the two datasets.
- Key Alignment: It matches ParentId from the answers table with Id from the questions table.
- Join Strategy (`how="inner"`): This ensures that only pairs exist in the final result. If an answer exists but its parent question was filtered out (or vice versa), that record is discarded.

**3. Column Renaming and Selection**

After the join, Polars automatically renames overlapping column names (like "Body" and "Score") by adding a suffix. The select block organizes and clarifies the resulting data:
- Aliasing: It renames columns to be more descriptive for a machine learning pipeline (e.g., `Body_right` becomes `question_body`, and the original answer Body becomes answer).
- Feature Retention: It keeps the "Score" for both the question and the answer, which allows for further filtering or weighting based on quality later in the pipeline.

**4. Data Summary**

Finally, the print statements provide a quick health check of the process.
- `questions.height`: Shows how many unique high-quality questions were processed.
- `answers.height`: Shows the total number of high-quality answers.
- `qa_pairs.height`: Shows the final number of pairs. This number is often larger than the number of questions if a single high-quality question has multiple high-quality answers.

In [4]:
questions = questions.with_columns([
    pl.col("Body").map_elements(clean_html, return_dtype=pl.Utf8),
    pl.col("Title").str.strip_chars()
])

answers = answers.with_columns(
    pl.col("Body").map_elements(clean_html, return_dtype=pl.Utf8)
)


# Simple join and select
qa_pairs = answers.join(
    questions,
    left_on="ParentId",
    right_on="Id",
    how="inner"
).select([
    pl.col("ParentId").alias("question_id"),  # Use ParentId as question_id
    pl.col("Title").alias("question_title"),
    pl.col("Body_right").alias("question_body"),
    pl.col("Score_right").alias("question_score"),
    pl.col("Id").alias("answer_id"),
    pl.col("Body").alias("answer"),
    pl.col("Score").alias("answer_score")
])

print(f"Questions: {questions.height:,}")
print(f"Answers: {answers.height:,}")
print(f"Q&A pairs: {qa_pairs.height:,}")

Questions: 200
Answers: 154,002
Q&A pairs: 1,860

In [6]:
if qa_pairs.height > 0:
    q_id = qa_pairs[0, "question_id"]
    q_data = qa_pairs.filter(pl.col("question_id") == q_id)
    
    print("QUESTION WITH ANSWERS")
    print("\n" + "-"*80)
    
    print(f"\nTitle: {q_data[0, 'question_title']}")
    print(f"Score: {q_data[0, 'question_score']}")
    print(f"\nBody:")
    print("-" * 40)
    print(q_data[0, "question_body"][:800])
    print("-" * 40)
    
    print(f"\nAnswers ({q_data.height}):")
    for i in range(q_data.height):
        print(f"\nAnswer {i+1} (Score: {q_data[i, 'answer_score']}):")
        print("-" * 30)
        print(q_data[i, "answer"][:500])
        print("-" * 30)

QUESTION WITH ANSWERS

--------------------------------------------------------------------------------

Title: How do you disable browser Autocomplete on web form field / input tag?
Score: 1614

Body:
----------------------------------------
How do you disable autocomplete in the major browsers for a specific input (or form field )?
----------------------------------------

Answers (18):

Answer 1 (Score: 1637):
------------------------------
Firefox 30 ignores autocomplete="off" for passwords, opting to prompt the user instead whether the password should be stored on the client. Note the following commentary from May 5, 2014: The password manager always prompts if it wants to save a password. Passwords are not saved without permission from the user. We are the third browser to implement this change, after IE and Chrome. According to Mozilla developer documentation the form element attribute autocomplete prevents form data from being
------------------------------

Answer 2 (Score: 11):
------------------------------
<form autocomplete="off" ... was a none standard way to do this (I think mozilla and IE still support it) but messing with the users expectations is normally a bad idea. If the user enters their credit card details into a form and then let's someone else use that browser it's not your concern :)
------------------------------

Answer 3 (Score: 6):
------------------------------
Use a non-standard name and id for the fields, so rather than "name" have "name_". Browsers will then not see it as being the name field. The best part about it is that you can do this to some but not all fields and it will autocomplete some but not all fields.
------------------------------

Answer 4 (Score: 77):
------------------------------
<form name="form1" id="form1" method="post"
      autocomplete="off" action="http://www.example.com/form.cgi"> This will work in IE and FF, the downside is that it is not XHTML standard.
------------------------------

Answer 5 (Score: 12):
------------------------------
Just set autocomplete="off" . There is a very good reason for doing this: You want to provide your own autocomplete functionality!
------------------------------

Answer 6 (Score: 13):
------------------------------
On a related, or actually, on the completely opposite note - if you're the user of the aforementioned form and want to re-enable the autocomplete functionality, use the 'remember password' bookmarklet from this bookmarklets page . It removes all 'autocomplete="off"' attributes from all forms on the page. Keep fighting the good fight!
------------------------------

Answer 7 (Score: 11):
------------------------------
We did actually use sasb 's idea for one site. It was a medical software web app to run a doctor's office. However, many of our clients were surgeons who used lots of different workstations, including semi-public terminals. So, they wanted to make sure that a doctor who doesn't understand the implication of auto-saved passwords or isn't paying attention can't accidentally leave their login info easily accessible. Of course, this was before the idea of private browsing that is starting to be feat
------------------------------

Answer 8 (Score: 177):
------------------------------
In addition to autocomplete=off , you could also have your form fields names be randomized by the code that generates the page, perhaps by adding some session-specific string to the end of the names.  When the form is submitted, you can strip that part off before processing them on the server side. This would prevent the web browser from finding context for your field and also might help prevent XSRF attacks because an attacker wouldn't be able to guess the field names for a form submission.
------------------------------

Answer 9 (Score: 45):
------------------------------
As others have said, the answer is autocomplete="off" However I think it's worth stating why it's a good idea to use this in certain cases as some answers to this and duplicate questions have suggested it's better not to turn if off. Stopping browsers storing credit card numbers shouldn't be left to users. Too many users won't even realise it's a problem. It's particularly important to turn it off on fields for credit card security codes. As this page states "Never store the security code ... it
------------------------------

Answer 10 (Score: 7):
------------------------------
In order to avoid the invalid XHTML you can set this attribute using javascript. Example using jQuery: <input type="text" class="noAutoComplete" ... />

$(function() {
    $('.noAutoComplete').attr('autocomplete', 'off');
}); The problem is that users without javascript will do get the autocomplete functionality.
------------------------------

Answer 11 (Score: 7):
------------------------------
Adding the autocomplete="off" to the form tag will disable the browser autocomplete (what was previously typed into that field) from all input fields within that particular form. Tested on: Firefox 3.5, 4 BETA Internet Explorer 8 Chrome
------------------------------

Answer 12 (Score: 12):
------------------------------
I think autocomplete=off is supported in HTML 5. Ask yourself why you want to do this though - it may make sense in some situations but don't do it just for the sake of doing it. It's less convenient for users and not even a security issue in OS X (mentioned by Soren below). If you're worried about people having their passwords stolen remotely - a keystroke logger could still do it even though your app uses autcomplete=off . As a user who chooses to have a browser remember (most of) my informati
------------------------------

Answer 13 (Score: 19):
------------------------------
I'd have to beg to differ with those answers that say to avoid disabling auto-complete. The first thing to bring up is that auto-complete not being explicitly disabled on login form fields is a PCI-DSS fail. In addition, if a users' local machine is compromised then any autocomplete data can be trivially obtained by an attacker due to it being stored in the clear. There is certainly an argument for usability, however there's a very fine balance when it comes to which form fields should have auto
------------------------------

Answer 14 (Score: 16):
------------------------------
Three options:
First: <input type='text' autocomplete='off' /> Second: <form action='' autocomplete='off'> Third (javascript code): $('input').attr('autocomplete', 'off');
------------------------------

Answer 15 (Score: 10):
------------------------------
None of the solutions worked for me in this conversation. I finally figured out a pure HTML solution that requires no Javascript , works in modern browsers (except IE; there had to at least 1 catch, right?), and does not require you to disable autocomplete for the entire form. Simply turn off autocomplete on the form and then turn it ON for any input you wish it to work within the form. For example: <form autocomplete="off">
    <!-- these inputs will not allow autocomplete and chrome

------------------------------

Answer 16 (Score: 118):
------------------------------
Most of the major browsers and password managers (correctly, IMHO) now ignore autocomplete=off . Why? Many banks and other "high security" websites added autocomplete=off to their login pages "for security purposes" but this actually decreases security since it causes people to change the passwords on these high security sites to be easy to remember (and thus crack) since autocomplete was broken. Long ago most password managers started ignoring autocomplete=off , and now the browsers are startin
------------------------------

Answer 17 (Score: 57):
------------------------------
Sometimes even autocomplete=off would not prevent to fill in credentials into wrong fields, but not user or nickname field. This workaround is in addition to apinstein's post about browser behavior. fix browser autofill in: readonly and set writeble on focus (click and tab) <input type="password" readonly
     onfocus="this.removeAttribute('readonly');"/> Because, Browser auto fills credentials to wrong text field!? I notice this strange behavior on Chrome and Safari, when there are password f
------------------------------

Answer 18 (Score: 15):
------------------------------
I've been trying endless solutions, and then I found this: Instead of autocomplete="off" just simply use autocomplete="false" As simple as that, and it works like a charm in Google Chrome as well!
------------------------------

**Note** : I selected sample of the dataset for demonstration becuase dataset is too large, which takes more computational resource and time.

In [ ]:
qa_selected = qa_pairs.select([
    "question_title", 
    "question_body", 
    "answer"
])

print(f"\nSelected columns Q&A pairs: {qa_selected.height:,}")
print("\nColumns in selected dataframe:")
print(qa_selected.columns)

Selected columns Q&A pairs: 1,860

Columns in selected dataframe:
['question_title', 'question_body', 'answer']

In [8]:
if qa_selected.height > 0:
    print("\n" + "="*80)
    print("SAMPLE Q&A (Selected Columns Only)")
    print("="*80)
    
    for i in range(min(3, qa_selected.height)):
        print(f"\nQ&A Pair #{i+1}:")
        print("-" * 40)
        print(f"Question Title: {qa_selected[i, 'question_title']}")
        print(f"\nQuestion Body:")
        print("-" * 20)
        print(qa_selected[i, 'question_body'][:300] + ("..." if len(qa_selected[i, 'question_body']) > 300 else ""))
        print(f"\nAnswer:")
        print("-" * 20)
        print(qa_selected[i, 'answer'][:400] + ("..." if len(qa_selected[i, 'answer']) > 400 else ""))
        print("="*80)

================================================================================
SAMPLE Q&A (Selected Columns Only)
================================================================================

Q&A Pair #1:
----------------------------------------
Question Title: How do you disable browser Autocomplete on web form field / input tag?

Question Body:
--------------------
How do you disable autocomplete in the major browsers for a specific input (or form field )?

Answer:
--------------------
Firefox 30 ignores autocomplete="off" for passwords, opting to prompt the user instead whether the password should be stored on the client. Note the following commentary from May 5, 2014: The password manager always prompts if it wants to save a password. Passwords are not saved without permission from the user. We are the third browser to implement this change, after IE and Chrome. According to M...
================================================================================

Q&A Pair #2:
----------------------------------------
Question Title: How do you disable browser Autocomplete on web form field / input tag?

Question Body:
--------------------
How do you disable autocomplete in the major browsers for a specific input (or form field )?

Answer:
--------------------
<form autocomplete="off" ... was a none standard way to do this (I think mozilla and IE still support it) but messing with the users expectations is normally a bad idea. If the user enters their credit card details into a form and then let's someone else use that browser it's not your concern :)
================================================================================

Q&A Pair #3:
----------------------------------------
Question Title: How do you disable browser Autocomplete on web form field / input tag?

Question Body:
--------------------
How do you disable autocomplete in the major browsers for a specific input (or form field )?

Answer:
--------------------
Use a non-standard name and id for the fields, so rather than "name" have "name_". Browsers will then not see it as being the name field. The best part about it is that you can do this to some but not all fields and it will autocomplete some but not all fields.
================================================================================

# Dataset Splitting

This section performs a grouped data split to ensure that there is no "data leakage" between the training and testing phases. It ensures that if a specific question appears in the training set, it (and any of its associated answers) will never appear in the test or validation sets.

**1. Extracting Unique Identifiers**

The code first isolates unique question titles into a list.
- Reasoning: In datasets where one question can have multiple high-score answers, splitting the rows randomly would likely put one answer in "Train" and another answer for the same question in "Test." This would allow the model to "cheat" by seeing parts of the test data during training. By splitting unique titles, the code treats each question as an atomic unit.

**2. The Three-Way Split Strategy**

The code uses `train_test_split` twice to divide the data into three distinct buckets:
- First Split: It takes the unique questions and reserves 80% for Training and 20% for a "Temp" set.
- Second Split: It takes that 20% "Temp" set and splits it further (70/30). This results in approximately 14% for Testing and 6% for Validation.

**3. Filtering the Original Data**

Once the lists of titles are finalized (`train_questions, test_questions, val_questions`), the code goes back to the full dataset (`qa_selected`) and uses the `.filter()` and `.is_in()` methods.
- Mapping: It pulls every row (question + answer pair) where the title matches the respective bucket list.
- Outcome: This expands the list of unique titles back into a full dataframe of question-answer pairs while maintaining the strict separation established in the previous step.

**4. Verification and Statistics**

The final print statements compare the number of unique questions to the number of rows in the resulting dataframes.
- Data Expansion: Notice that the "rows" count in the final dataframes will likely be higher than the "unique questions" count. This confirms that questions with multiple valid answers were successfully kept together in the same split.

In [9]:
unique_questions = qa_selected["question_title"].unique().to_list()
print(f"Unique questions: {len(unique_questions):,}")

train_questions, temp_questions = train_test_split(
    unique_questions, 
    test_size=0.2,  
    random_state=42
)

test_questions, val_questions = train_test_split(
    temp_questions,
    test_size=0.3,  
    random_state=42
)

print(f"\nSplit sizes:")
print(f"Train questions: {len(train_questions):,} ({len(train_questions)/len(unique_questions)*100:.1f}%)")
print(f"Test questions: {len(test_questions):,} ({len(test_questions)/len(unique_questions)*100:.1f}%)")
print(f"Validation questions: {len(val_questions):,} ({len(val_questions)/len(unique_questions)*100:.1f}%)")

train_data = qa_selected.filter(
    pl.col("question_title").is_in(train_questions)
)

test_data = qa_selected.filter(
    pl.col("question_title").is_in(test_questions)
)

val_data = qa_selected.filter(
    pl.col("question_title").is_in(val_questions)
)

print(f"\nData splits by question-title:")
print(f"Train data: {train_data.height:,} rows")
print(f"Test data: {test_data.height:,} rows")
print(f"Validation data: {val_data.height:,} rows")

Unique questions: 200

Split sizes:
Train questions: 160 (80.0%)
Test questions: 28 (14.0%)
Validation questions: 12 (6.0%)

Data splits by question-title:
Train data: 1,331 rows
Test data: 244 rows
Validation data: 285 rows

# Tokenization (gemma-3-270m)

Due to most of optimzation techniques in this notebook, it will use google/gemma-3-270m for demonstration, so tokenize function of this model will be create. This section transforms raw text data into a numerical format that the Gemma-3 model can understand. This process, known as preprocessing, prepares the dataset for Causal Language Modeling (where the model learns to predict the next word in a sequence).

**1. Tokenizer Setup**

The code initializes the tokenizer for the gemma-3-270m model.
- Special Tokens: It sets the pad_token to be the same as the eos_token (End Of Sentence). This is necessary because many decoder-only models (like Gemma) do not have a default padding token.
- Vocab Size: The print statement confirms the size of the model's internal "dictionary" of sub-word units.

**2. Prompt Formatting**

Inside the `tokenize_examples` function, the code wraps the raw question and answer data into a specific template:

    <bos>Question: {Title} {Body} Answer: {Answer}<eos>
    <bos> and <eos>: These are "Beginning of Sequence" and "End of Sequence" markers. They help the model learn exactly where a conversation starts and where it should stop generating.

Instructional Structure: By including the labels "Question:" and "Answer:", the code teaches the model the relationship between a query and its response.

**3. Tokenization Parameters**

The `tokenizer()` call converts the formatted strings into `input_ids` (numbers).
- Truncation: If the text is longer than 128 tokens, it cuts off the end to fit the model's memory limits.
- `Padding="max_length"`: If the text is shorter than 128 tokens, it adds "padding tokens" at the end so that every example in the batch is exactly the same length. This is required for efficient GPU computation.
- `return_tensors="pt"`: This returns the data as PyTorch Tensors, which are the standard data format for training models on NVIDIA GPUs.

**4. Label Creation for Self-Supervised Learning**

    tokenized["labels"] = tokenized["input_ids"].clone()

This is a crucial step for Causal Language Modeling. In this training style, the "label" (the correct answer) is simply a copy of the input itself. During training, the model will look at a sequence of tokens and try to predict the very next token in that same sequence.

**5. Dataset Organization**

Finally, the code packages the tensors into a Hugging Face DatasetDict.

- `input_ids`: The numerical representation of the words.
- `attention_mask`: A binary mask (1s and 0s) that tells the model which tokens are actual text and which are just "padding" to be ignored.
- `labels`: The target values used to calculate the loss (how wrong the model is) during training.

**Reference**
- [Huggingface:google/gemma-3-270m](https://huggingface.co/google/gemma-3-270m)

In [3]:
# Configuration
MODEL_NAME = "google/gemma-3-270m"
MAX_LENGTH = 128

# Load tokenizer
print(f"Loading tokenizer: {MODEL_NAME}")
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
tokenizer.pad_token = tokenizer.eos_token
print(f"Tokenizer loaded. Vocab size: {len(tokenizer)}")

# Tokenization
def tokenize_examples(df, max_length=MAX_LENGTH):
    texts = []
    for row in df.iter_rows(named=True):
        text = f"""<bos>Question: {row['question_title']}
{row['question_body']}
Answer: {row['answer']}<eos>"""
        texts.append(text)

    tokenized = tokenizer(
        texts,
        truncation=True,
        max_length=max_length,
        padding="max_length",
        return_tensors="pt"
    )
    tokenized["labels"] = tokenized["input_ids"].clone()
    return tokenized


print("Tokenizing training data...")
train_tokenized = tokenize_examples(train_data)

print("Tokenizing validation data...")
val_tokenized = tokenize_examples(val_data)

dataset_dict = DatasetDict({
    "train": Dataset.from_dict({
        "input_ids": train_tokenized["input_ids"],
        "attention_mask": train_tokenized["attention_mask"],
        "labels": train_tokenized["labels"]
    }),
    "validation": Dataset.from_dict({
        "input_ids": val_tokenized["input_ids"],
        "attention_mask": val_tokenized["attention_mask"],
        "labels": val_tokenized["labels"]
    })
})

print(f"Train examples: {len(dataset_dict['train']):,}")
print(f"Validation examples: {len(dataset_dict['validation']):,}")

Loading tokenizer: google/gemma-3-270m

config.json:   0%|          | 0.00/1.35k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/1.16M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/33.4M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/35.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/662 [00:00<?, ?B/s]

Tokenizer loaded. Vocab size: 262145
Tokenizing training data...
Tokenizing validation data...
Train examples: 1,331
Validation examples: 285

# Monitoring Functions

The monitoring code you provided is a comprehensive resource tracker designed for Large Language Model (LLM) training and inference. It captures metrics across four main domains: System Resources, Memory Footprint, Throughput/Latency, and Computational Efficiency (FLOPs).

**1. System Resource Metrics**

These metrics track the health and utilization of the host machine's hardware.
- Average CPU Usage (`avg_cpu_percent`): The percentage of the CPU's capacity being utilized. High CPU usage alongside low GPU utilization often indicates a bottleneck in data preprocessing or loading.
- Average System Memory (`avg_memory_percent`): The percentage of the host's RAM being used. This is critical to monitor when using "Offloading" techniques (like DeepSpeed ZeRO-Offload) that move data from the GPU to the system RAM.

**2. Model Memory Footprint Metrics**

These metrics calculate the theoretical memory requirements based on the model's architecture.
- Total Parameters (`total_parameters`): The count of all learnable weights in the model.
- Precision Bytes (`precision_bytes`): The number of bytes used per parameter based on the data type (e.g., 4 bytes for float32, 2 bytes for float16 or bfloat16).
- Parameters Memory (`parameters_memory_gb`): The VRAM required just to store the model weights ($Parameters \times Precision$).
- KV Cache Memory (`kv_cache_memory_gb`): An estimate of the memory required to store the Key-Value cache during generation. This grows with the sequence length and is a common cause of "Out of Memory" (OOM) errors.
- Total Memory Footprint (`total_memory_gb`): The sum of parameter memory and estimated KV cache memory.

**3. Throughput & Latency Metrics**

These measure the speed of the model in terms of data processing.
- Throughput (`tokens_per_second`): The rate at which the model processes or generates text. It is calculated as $Tokens / Time$. High throughput is the goal of batching and parallelization.
- Latency (`avg_latency`): The total time taken for a single inference request (from start to finish).
- Time to First Token (`time_to_first_token`): The duration between the initial request and the generation of the very first token. This is a vital metric for user-facing chat applications.

**4. Computational Efficiency (FLOPs)**

FLOPs (Floating Point Operations) measure the actual mathematical "work" being done by the hardware.
- Total FLOPs (`total_flops_tflops`): The total number of floating-point operations performed during a training step or epoch, usually expressed in TeraFLOPs ($10^{12}$).
- TFLOPS per Second (`teraflops_per_second`): The "compute speed." This tells you how well you are utilizing the raw power of your GPU (e.g., how close you are to the hardware's theoretical peak).
- FLOPs per Token (`flops_per_token`): The amount of compute required to generate a single token. This helps compare the efficiency of different model architectures (like MoE vs. Dense models).

**Summary of Statistical Aggregations**

The code also provides several statistical views of the metrics above to help identify performance stability:
- Min/Max/Avg: Used for throughput and latency to identify "jitter" or outlier batches that take significantly longer than others.
- Epoch Summary: A tabular view that aligns losses with resource usage to see if performance degrades as training progresses.

## Resource Monitoring

In [4]:
class ResourceMonitor(threading.Thread):
    def __init__(self, interval=2.0, model=None):
        super().__init__(daemon=True)
        self.interval = interval
        self.running = False
        self.model = model
        
        self.cpu_samples = collections.deque(maxlen=1000)
        self.memory_samples = collections.deque(maxlen=1000)
        self.throughput_samples = collections.deque(maxlen=1000)
        self.latency_samples = collections.deque(maxlen=1000)
        self.flops_samples = collections.deque(maxlen=1000)
        self.tokens_processed = 0
        self.total_flops = 0
        self.start_time = None
        
    def run(self):
        self.running = True
        while self.running:
            self.cpu_samples.append(psutil.cpu_percent(interval=self.interval))
            self.memory_samples.append(psutil.virtual_memory().percent)
        
    def stop(self):
        self.running = False
        
    def get_average(self):
        cpu_avg = sum(self.cpu_samples) / len(self.cpu_samples) if self.cpu_samples else 0
        mem_avg = sum(self.memory_samples) / len(self.memory_samples) if self.memory_samples else 0
        return cpu_avg, mem_avg
    
    def clear(self):
        self.cpu_samples.clear()
        self.memory_samples.clear()
        self.throughput_samples.clear()
        self.latency_samples.clear()
        self.flops_samples.clear()
        self.tokens_processed = 0
        self.total_flops = 0
        
    def calculate_model_memory_footprint(self):
        if not self.model:
            return {}
            
        total_params = sum(p.numel() for p in self.model.parameters())
        
        dtype_map = {
            torch.float32: 4,
            torch.float16: 2,
            torch.bfloat16: 2
        }
        
        model_dtype = getattr(self.model, 'dtype', torch.float32)
        precision_bytes = dtype_map.get(model_dtype, 4)
        
        kv_cache_memory = 0
        if hasattr(self.model, 'config'):
            config = self.model.config
            
            if hasattr(config, 'max_position_embeddings'):
                seq_length = config.max_position_embeddings
                hidden_size = getattr(config, 'hidden_size', 2048)
                num_layers = getattr(config, 'num_hidden_layers', 28)
                
                kv_cache_memory = 2 * seq_length * hidden_size * num_layers * precision_bytes
        
        params_memory = total_params * precision_bytes
        total_memory_footprint = params_memory + kv_cache_memory
        
        return {
            'total_parameters': total_params,
            'precision_bytes': precision_bytes,
            'parameters_memory_bytes': params_memory,
            'parameters_memory_gb': params_memory / (1024**3),
            'kv_cache_memory_bytes': kv_cache_memory,
            'kv_cache_memory_gb': kv_cache_memory / (1024**3),
            'total_memory_bytes': total_memory_footprint,
            'total_memory_gb': total_memory_footprint / (1024**3)
        }
    
    def estimate_model_flops(self, batch_size=1, sequence_length=512):
        """Estimate FLOPs for transformer forward pass"""
        if not self.model or not hasattr(self.model, 'config'):
            return 0
            
        config = self.model.config
        total_params = sum(p.numel() for p in self.model.parameters())
        
        # Get model configuration
        hidden_size = getattr(config, 'hidden_size', 2048)
        num_layers = getattr(config, 'num_hidden_layers', 28)
        num_attention_heads = getattr(config, 'num_attention_heads', 8)
        intermediate_size = getattr(config, 'intermediate_size', hidden_size * 4)
        vocab_size = getattr(config, 'vocab_size', 262144)
        
        # Attention FLOPs per layer
        # QKV projections: 3 * batch * seq_len * hidden_size^2
        qkv_flops = 3 * batch_size * sequence_length * hidden_size * hidden_size * 2
        
        # Attention mechanism: batch * seq_len^2 * hidden_size
        attention_flops = batch_size * sequence_length * sequence_length * hidden_size * 2
        
        # Output projection: batch * seq_len * hidden_size^2
        output_proj_flops = batch_size * sequence_length * hidden_size * hidden_size * 2
        
        # FFN layer: 2 * batch * seq_len * hidden_size * intermediate_size
        ffn_flops = 2 * batch_size * sequence_length * hidden_size * intermediate_size * 2
        
        # Total per layer FLOPs
        layer_flops = qkv_flops + attention_flops + output_proj_flops + ffn_flops
        
        # Total FLOPs for all layers
        total_layer_flops = layer_flops * num_layers
        
        # Embedding and output projection FLOPs
        embedding_flops = batch_size * sequence_length * hidden_size * vocab_size * 2
        
        # Total FLOPs for forward pass
        total_flops = total_layer_flops + embedding_flops
        
        return total_flops
    
    def record_inference_start(self):
        self.start_time = time.time()
        
    def record_inference_end(self, tokens_generated=0):
        if not self.start_time:
            return 0
            
        latency = time.time() - self.start_time
        self.latency_samples.append(latency)
        
        if tokens_generated > 0:
            throughput = tokens_generated / latency
            self.throughput_samples.append(throughput)
            self.tokens_processed += tokens_generated
            
        self.start_time = None
        return latency
    
    def record_training_flops(self, batch_size, sequence_length):
        """Record FLOPs for a training step"""
        flops = self.estimate_model_flops(batch_size, sequence_length)
        self.flops_samples.append(flops)
        self.total_flops += flops
        return flops
    
    def get_throughput_stats(self):
        if not self.throughput_samples:
            return {
                'tokens_per_second': 0,
                'min_throughput': 0,
                'max_throughput': 0,
                'avg_throughput': 0,
                'total_tokens_processed': self.tokens_processed
            }
        
        return {
            'tokens_per_second': self.throughput_samples[-1],
            'min_throughput': min(self.throughput_samples),
            'max_throughput': max(self.throughput_samples),
            'avg_throughput': sum(self.throughput_samples) / len(self.throughput_samples),
            'total_tokens_processed': self.tokens_processed
        }
    
    def get_latency_stats(self):
        if not self.latency_samples:
            return {
                'time_to_first_token': 0,
                'generation_speed': 0,
                'last_latency': 0,
                'min_latency': 0,
                'max_latency': 0,
                'avg_latency': 0
            }
        
        generation_speed = self.throughput_samples[-1] if self.throughput_samples else 0
        
        return {
            'time_to_first_token': self.latency_samples[0],
            'generation_speed': generation_speed,
            'last_latency': self.latency_samples[-1],
            'min_latency': min(self.latency_samples),
            'max_latency': max(self.latency_samples),
            'avg_latency': sum(self.latency_samples) / len(self.latency_samples)
        }
    
    def get_flops_stats(self):
        """Get FLOPs statistics"""
        if not self.flops_samples:
            return {
                'total_flops': 0,
                'avg_flops_per_step': 0,
                'min_flops': 0,
                'max_flops': 0,
                'total_flops_tflops': 0,
                'avg_flops_tflops': 0
            }
        
        total_flops = self.total_flops
        avg_flops = total_flops / len(self.flops_samples) if self.flops_samples else 0
        
        return {
            'total_flops': total_flops,
            'avg_flops_per_step': avg_flops,
            'min_flops': min(self.flops_samples),
            'max_flops': max(self.flops_samples),
            'total_flops_tflops': total_flops / 1e12,
            'avg_flops_tflops': avg_flops / 1e12,
            'flops_samples': len(self.flops_samples)
        }
    
    def get_computational_efficiency(self, epoch_time):
        """Calculate computational efficiency metrics"""
        if epoch_time <= 0:
            return {
                'total_flops': 0,
                'flops_per_second': 0,
                'flops_per_token': 0
            }
        
        flops_stats = self.get_flops_stats()
        total_flops = flops_stats['total_flops']
        
        return {
            'total_flops': total_flops,
            'flops_per_second': total_flops / epoch_time,
            'flops_per_token': total_flops / self.tokens_processed if self.tokens_processed > 0 else 0,
            'teraflops_per_second': (total_flops / epoch_time) / 1e12,
            'teraflops_per_token': (total_flops / self.tokens_processed) / 1e12 if self.tokens_processed > 0 else 0
        }
    
    def get_all_metrics(self):
        memory_metrics = self.calculate_model_memory_footprint()
        throughput_stats = self.get_throughput_stats()
        latency_stats = self.get_latency_stats()
        flops_stats = self.get_flops_stats()
        avg_cpu, avg_memory = self.get_average()
        
        return {
            'memory_footprint': memory_metrics,
            'throughput': throughput_stats,
            'latency': latency_stats,
            'flops': flops_stats,
            'system': {
                'avg_cpu_percent': avg_cpu,
                'avg_memory_percent': avg_memory,
                'cpu_samples': len(self.cpu_samples),
                'memory_samples': len(self.memory_samples)
            }
        }


class EpochMonitor(TrainerCallback):
    def __init__(self, model=None):
        self.start_time = time.time()
        self.epoch_data = []
        self.current_epoch = None
        self.model = model
        self.monitor = ResourceMonitor(interval=1.0, model=model)
        
        self.epoch_tokens = 0
        self.epoch_steps = 0
        self.batch_start_time = None
        
    def on_train_begin(self, args, state, control, **kwargs):
        self.monitor.start()
        
        if self.model:
            initial_memory = self.monitor.calculate_model_memory_footprint()
            print("Initial Model Memory Footprint:")
            print(f"  Parameters: {initial_memory.get('total_parameters', 0):,}")
            print(f"  Precision: {initial_memory.get('precision_bytes', 4)} bytes")
            print(f"  Total Memory: {initial_memory.get('total_memory_gb', 0):.2f} GB")
            print(f"    - Parameters: {initial_memory.get('parameters_memory_gb', 0):.2f} GB")
            print(f"    - KV Cache (est): {initial_memory.get('kv_cache_memory_gb', 0):.2f} GB")
            
            # Estimate FLOPs for standard batch
            batch_flops = self.monitor.estimate_model_flops(batch_size=8, sequence_length=512)
            print(f"  Estimated FLOPs per forward pass (batch=8, seq=512): {batch_flops/1e12:.2f} TFLOPS")
        
    def on_epoch_begin(self, args, state, control, **kwargs):
        self.epoch_start = time.time()
        self.current_epoch = state.epoch
        self.epoch_tokens = 0
        self.epoch_steps = 0
        self.monitor.clear()
        
    def on_step_begin(self, args, state, control, **kwargs):
        self.batch_start_time = time.time()
        
    def on_step_end(self, args, state, control, **kwargs):
        if not self.batch_start_time:
            return
            
        step_time = time.time() - self.batch_start_time
        batch_size = getattr(args, 'per_device_train_batch_size', 1)
        seq_length = 512
        
        tokens_this_step = batch_size * seq_length
        self.epoch_tokens += tokens_this_step
        self.epoch_steps += 1
        
        if step_time > 0:
            throughput = tokens_this_step / step_time
            self.monitor.throughput_samples.append(throughput)
            self.monitor.tokens_processed += tokens_this_step
            
            # Record FLOPs for this training step
            flops = self.monitor.record_training_flops(batch_size, seq_length)
        
        self.batch_start_time = None
        
    def on_epoch_end(self, args, state, control, **kwargs):
        epoch_time = time.time() - self.epoch_start
        avg_cpu, avg_memory = self.monitor.get_average()
        
        epoch_throughput = self.epoch_tokens / epoch_time if epoch_time > 0 else 0
        metrics = self.monitor.get_all_metrics()
        computational_efficiency = self.monitor.get_computational_efficiency(epoch_time)
        
        epoch_entry = {
            'epoch': self.current_epoch,
            'time': epoch_time,
            'avg_cpu': avg_cpu,
            'avg_memory': avg_memory,
            'tokens_processed': self.epoch_tokens,
            'training_steps': self.epoch_steps,
            'epoch_throughput_tokens_per_second': epoch_throughput,
            'detailed_metrics': metrics,
            'computational_efficiency': computational_efficiency
        }
        
        self.epoch_data.append(epoch_entry)
        
        # Display epoch summary in table format
        print(f"\n{'='*60}")
        print(f"Epoch {int(self.current_epoch)} Summary")
        print(f"{'='*60}")
        
        summary_data = [
            ['Duration (s)', f"{epoch_time:.2f}"],
            ['Tokens Processed', f"{self.epoch_tokens:,}"],
            ['Throughput (token/s)', f"{epoch_throughput:.0f}"],
            ['Training Steps', f"{self.epoch_steps:,}"],
            ['Avg CPU (%)', f"{avg_cpu:.1f}"],
            ['Avg Memory (%)', f"{avg_memory:.1f}"]
        ]
        
        # Add computational efficiency metrics
        if computational_efficiency['total_flops'] > 0:
            summary_data.extend([
                ['Total FLOPs', f"{computational_efficiency['total_flops']/1e12:.2f} TFLOPS"],
                ['TFLOPS (per second)', f"{computational_efficiency['teraflops_per_second']:.2f}"],
                ['FLOPs (per token)', f"{computational_efficiency['flops_per_token']/1e9:.2f} GFLOPS"]
            ])
        
        # Add latency if available
        if metrics['latency'].get('avg_latency', 0) > 0:
            summary_data.append(['Avg Latency (ms)', f"{metrics['latency']['avg_latency']*1000:.1f}"])
        
        # Print table
        max_label_len = max(len(row[0]) for row in summary_data)
        max_value_len = max(len(row[1]) for row in summary_data)
        
        for label, value in summary_data:
            print(f"  {label:<{max_label_len}} : {value:>{max_value_len}}")
        
    def on_train_end(self, args, state, control, **kwargs):
        self.monitor.stop()
        total_time = time.time() - self.start_time
        
        print("\n" + "="*60)
        print("TRAINING COMPLETE")
        print("="*60)
        print(f"Total Training Time: {total_time:.2f}s")
        print(f"Total Epochs: {len(self.epoch_data)}")
        
        if self.epoch_data:
            avg_epoch_time = sum(e['time'] for e in self.epoch_data) / len(self.epoch_data)
            total_tokens = sum(e['tokens_processed'] for e in self.epoch_data)
            avg_throughput = total_tokens / total_time if total_time > 0 else 0
            
            # Calculate total computational efficiency
            total_flops = sum(e.get('computational_efficiency', {}).get('total_flops', 0) for e in self.epoch_data)
            avg_tflops_per_second = total_flops / total_time / 1e12 if total_time > 0 else 0
            
            print(f"Average Epoch Time: {avg_epoch_time:.2f}s")
            print(f"Total Tokens Processed: {total_tokens:,}")
            print(f"Average Throughput: {avg_throughput:.0f} tokens/second")
            
            if total_flops > 0:
                print(f"Total FLOPs: {total_flops/1e12:.2f} TFLOPS")
                print(f"Average TFLOPS (per second): {avg_tflops_per_second:.2f}")
                print(f"Overall FLOPs (per token): {total_flops/total_tokens/1e9:.2f} GFLOPS" if total_tokens > 0 else "")
            
            final_metrics = self.monitor.get_all_metrics()
            
            print("\nFinal Metrics:")
            if final_metrics['memory_footprint']:
                print(f"Memory Footprint: {final_metrics['memory_footprint'].get('total_memory_gb', 0):.2f} GB")
            
            if final_metrics['throughput'].get('avg_throughput', 0) > 0:
                print(f"Inference Throughput: {final_metrics['throughput']['avg_throughput']:.0f} tokens/second")
            
            if final_metrics['latency'].get('avg_latency', 0) > 0:
                print(f"Avg Latency: {final_metrics['latency']['avg_latency']*1000:.1f}ms")
            
            if final_metrics['flops'].get('total_flops', 0) > 0:
                print(f"Total Training FLOPs: {final_metrics['flops']['total_flops_tflops']:.2f} TFLOPS")
    
    def record_inference(self, tokens_generated):
        return self.monitor.record_inference_end(tokens_generated)
    
    def get_metrics_summary(self):
        return {
            'epoch_summary': self.epoch_data,
            'final_metrics': self.monitor.get_all_metrics(),
            'training_duration': time.time() - self.start_time,
            'total_epochs': len(self.epoch_data)
        }

## Summarized Training Results

In [5]:
def summarize_training_results(trainer, monitor):
    """
    Generate and display a comprehensive summary of training results,
    including per-epoch metrics and overall statistics.
    
    Parameters:
    -----------
    trainer : transformers.Trainer
        The trained Trainer instance (to access log_history)
    monitor : EpochMonitor
        The callback instance that collected epoch-level metrics
    """
    # Extract validation losses from log history
    log_history = trainer.state.log_history
    validation_losses = [log.get('eval_loss') for log in log_history if 'eval_loss' in log]

    # Build per-epoch results table
    results_data = []
    for i, epoch in enumerate(monitor.epoch_data):
        val_loss = validation_losses[i] if i < len(validation_losses) else None
        comp_eff = epoch.get('computational_efficiency', {})

        results_data.append({
            'Epoch': math.ceil(epoch['epoch']),
            'Training Loss': round(log_history[i*2]['loss'], 4) if i*2 < len(log_history) else None,
            'Validation Loss': round(val_loss, 4) if val_loss else None,
            'Time (s)': round(epoch['time'], 2),
            'Tokens Processed': f"{epoch['tokens_processed']:,}",
            'Throughput (token/s)': int(epoch['epoch_throughput_tokens_per_second']),
            'TFLOPS (per second)': round(comp_eff.get('teraflops_per_second', 0), 2),
            'Avg CPU (%)': round(epoch['avg_cpu'], 1),
            'Avg Memory (%)': round(epoch['avg_memory'], 1),
            'Training Steps': epoch['training_steps']
        })

    results_df = pd.DataFrame(results_data)

    # Print formatted table
    print("\n" + "=" * 100)
    print("TRAINING RESULTS SUMMARY TABLE")
    print("=" * 100)
    print(results_df.to_string(
        index=False,
        formatters={
            'Epoch': lambda x: f"{int(x):>3}",
            'Training Loss': lambda x: f"{x:>10.4f}" if x is not None else " " * 10,
            'Validation Loss': lambda x: f"{x:>12.4f}" if x is not None else " " * 12,
            'Time (s)': lambda x: f"{x:>8.2f}",
            'Tokens Processed': lambda x: f"{x:>15}",
            'Throughput (token/s)': lambda x: f"{x:>15}",
            'TFLOPS (per second)': lambda x: f"{x:>10.2f}",
            'Avg CPU (%)': lambda x: f"{x:>10.1f}",
            'Avg Memory (%)': lambda x: f"{x:>12.1f}",
            'Training Steps': lambda x: f"{x:>12}"
        }
    ))

    # Overall statistics 
    if monitor.epoch_data:
        total_time = sum(epoch['time'] for epoch in monitor.epoch_data)
        avg_time = total_time / len(monitor.epoch_data)
        avg_cpu = sum(epoch['avg_cpu'] for epoch in monitor.epoch_data) / len(monitor.epoch_data)
        avg_memory = sum(epoch['avg_memory'] for epoch in monitor.epoch_data) / len(monitor.epoch_data)
        total_tokens = sum(epoch['tokens_processed'] for epoch in monitor.epoch_data)
        avg_throughput = total_tokens / total_time if total_time > 0 else 0

        # Computational metrics
        total_flops = sum(
            epoch.get('computational_efficiency', {}).get('total_flops', 0)
            for epoch in monitor.epoch_data
        )
        avg_tflops_per_second = total_flops / total_time / 1e12 if total_time > 0 else 0

        print("\n" + "-" * 100)
        print("TRAINING STATISTICS:")
        print("-" * 100)
        print(f"Total Training Time:      {total_time:.1f} s")
        print(f"Average Epoch Time:       {avg_time:.1f} s")
        print(f"Total Tokens Processed:   {total_tokens:,}")
        print(f"Average Throughput:       {avg_throughput:.0f} tokens/second")
        print(f"Average CPU Usage:        {avg_cpu:.1f}%")
        print(f"Average Memory Usage:     {avg_memory:.1f}%")

        if total_flops > 0:
            print(f"Total Training FLOPs:     {total_flops / 1e12:.2f} TFLOPS")
            print(f"Average TFLOPS (per sec): {avg_tflops_per_second:.2f}")
            if total_tokens > 0:
                print(f"Overall FLOPs (per token): {total_flops / total_tokens / 1e9:.2f} GFLOPS")

    print("\n" + "=" * 100 + "\n")

# Initial Model Fine Tuning

#### The Model: Gemma 3 (270M)

The specific model being loaded is google/gemma-3-270m. This is a small, efficient version of Google's Gemma 3 family, containing roughly 270 million parameters.

#### AutoModelForCausalLM

AutoModelForCausalLM is a class factory. Instead of you having to manually specify `Gemma3ForCausalLM`, this class looks at the MODEL_NAME and automatically selects the correct architecture. "Causal Language Modeling" refers to the task where the model learns to predict the next token in a sequence, looking only at the tokens that came before it.Key parameters used during model loading:

**Core Identity and Configuration**

- `pretrained_model_name_or_path`: The string identifier (e.g., "google/gemma-3-270m") or a local path to the model weights.
- `config`: An optional PretrainedConfig object. If not provided, the library automatically downloads the config.json associated with the model name.
- `cache_dir`: The directory where downloaded models and configurations are stored.
- `force_download`: A boolean that, if True, forces the library to re-download the files even if they already exist in the cache.
- `resume_download`: A boolean to resume an interrupted download of the model files.

**Hardware and Memory Management**

- `device_map`: Determines how model layers are distributed across available hardware. Common values include `"auto", "balanced", "sequential"`, or a custom dictionary mapping layers to specific GPU IDs.
- `low_cpu_mem_usage`: A boolean that uses a "meta-tensors" approach to load weights. It prevents the system from loading the entire model into CPU RAM before moving it to the GPU, which is essential for very large models.
- `offload_folder`: A path to a folder where weights can be temporarily stored on the hard drive if the model is too large to fit in both GPU and CPU RAM.
- `max_memory`: A dictionary specifying the maximum amount of memory to use on each device (e.g., {0: "10GiB", "cpu": "30GiB"}).

**Numerical Precision and Quantization**

- `torch_dtype`: Sets the floating-point precision. Options include `torch.float32, torch.float16, and torch.bfloat16`. Using lower precision reduces VRAM usage by half.
- `quantization_config`: Used for loading models in 4-bit or 8-bit mode (typically via BitsAndBytesConfig). This allows massive models to run on consumer-grade hardware.
- `load_in_8bit / load_in_4bit`: Simple boolean flags to enable basic quantization (though using quantization_config is now preferred).

**Behavior and Architecture Hooks**

- `trust_remote_code`: A boolean required for models that use custom Python code for their architecture not yet merged into the main library.
- revision: A specific git branch, tag, or commit hash of the model on the Hugging Face Hub.
- `use_safetensors`: A boolean to ensure the model loads using the .safetensors format rather than standard PyTorch .bin files (improves security and loading speed).
- `attn_implementation`: Allows you to explicitly choose the attention mechanism, such as `"eager", "sdpa" (Scaled Dot Product Attention), or "flash_attention_2"`.

**Inference and Generation Specifics**

- `is_decoder`: Usually defaults to True for Causal LM; it tells the model it is part of an encoder-decoder setup if necessary.
- `output_attentions`: A boolean that, if True, forces the model to return the attention weights for every layer.
- `output_hidden_states`: A boolean that forces the model to return the hidden states (embeddings) of every layer.

#### DataCollatorForLanguageModeling

The Data Collator is a specialized function that takes a list of data samples and "collates" them into a batch for the model. Its job is to ensure every sequence in a batch has the same length by adding padding. Configuration used:

- `tokenizer`: Passes the tokenizer used for encoding the text so the collator knows which padding token ID to use.
- `mlm=False`: Masked Language Modeling (MLM) is used for models like BERT. For Causal models like Gemma, we set this to False because we are training on the next-token prediction task, not filling in blanks.
- `mlm_probability`: Only relevant if mlm=True. This defines the percentage of tokens that will be masked or replaced during training. The standard practice (from the BERT paper) is 15%.
- `pad_to_multiple_of`: If set, it pads the sequence to a multiple of the provided value. This is highly recommended for hardware efficiency. For example, setting this to 8 can significantly speed up training on NVIDIA Tensor Cores or TPUs, as these hardwares are optimized for matrix operations with dimensions divisible by 8.
- `return_tensors`: Specifies the type of tensors to return. Options include:
    - `"pt"`: PyTorch tensors.
    - `"tf"`: TensorFlow tensors.
    - `"np"`: Numpy arrays.
- `label_pad_token_id`: The ID used to mask the loss for padding tokens in the labels. PyTorch's loss functions (like CrossEntropyLoss) ignore the index -100 by default, ensuring the model isn't penalized for failing to predict "nothingness" (padding).

#### Trainer

The Trainer is the high-level API that coordinates the entire training process. It bridges the gap between the model, the data, and the hardware.Instead of writing a manual loop to move tensors to the GPU, calculate the loss, perform backpropagation, and update weights, the Trainer manages all of that internally. By passing your monitor (the EpochMonitor callback) into the callbacks list, the Trainer allows your custom monitoring code to run at specific intervals (like the end of every step or epoch).

**TrainingArguments**

This object holds all the hyperparameters that control the behavior of the training loop. These settings determine how fast the model learns and how it manages hardware resources.

- `num_train_epochs=3`: The total number of times the training process will cycle through your entire dataset.
- `per_device_train_batch_size=8`: The number of training examples processed simultaneously on each GPU. Increasing this uses more VRAM but can stabilize training.
- `learning_rate=2e-5`: The "step size" the optimizer takes when updating model weights. A value of $2 \times 10^{-5}$ is a standard, conservative rate for fine-tuning LLMs.
- `warmup_ratio=0.1`: This tells the trainer to use the first 10% of the training steps to gradually increase the learning rate from zero to its target value. This prevents the model from "diverging" or breaking early on due to unstable gradients.
- `lr_scheduler_type="cosine"`: After the warmup period, the learning rate will gradually decrease following the curve of a cosine function, helping the model settle into a more precise solution.
- `weight_decay=0.01`: A regularization technique that penalizes very large weights, effectively helping the model avoid "overfitting" (memorizing the data).
- `gradient_accumulation_steps=1`: If you had a very small GPU, you could increase this to 4 or 8 to simulate a larger batch size without actually needing more VRAM.

**Additional Important TrainingArguments**

- `fp16=True or bf16=True`: Enables mixed-precision training. This uses 16-bit floats for most calculations, which significantly speeds up training and reduces VRAM usage without sacrificing model quality. bf16 is recommended if you are using newer NVIDIA GPUs (Ampere architecture and later).
- `gradient_checkpointing=True`: A memory-saving technique that trades compute for VRAM. It avoids storing all intermediate activations during the forward pass and recomputes them during the backward pass, allowing you to fit much larger models or batch sizes.
- `eval_strategy="steps" or "epoch"`: Defines when to run the evaluation loop. "steps" allows you to evaluate every few hundred batches, while "epoch" waits until the end of a full pass through the data.
- `eval_steps=500`: Only used if eval_strategy="steps". Specifies exactly how many training steps to wait before running an evaluation.
- `logging_steps=10`: Controls how often training metrics (like loss) are printed to the console or sent to your monitoring tool. Frequent logging helps you catch training issues early.
- `save_total_limit=2`: Limits the number of checkpoints stored in your OUTPUT_DIR. This prevents your hard drive from filling up by automatically deleting older checkpoints and keeping only the most recent ones.
- `load_best_model_at_end=True`: At the end of training, the Trainer will automatically load the weights of the version that performed best on the validation set, ensuring your final model is the highest quality version produced.
- `metric_for_best_model="eval_loss"`: Specifies which metric (e.g., loss or accuracy) should be used to determine which checkpoint is the "best" when `load_best_model_at_end` is enabled.

**Reference**
- [Huggingface:google/gemma-3-270m](https://huggingface.co/google/gemma-3-270m)

## Gemma-3-270m

In [ ]:
# Configuration
MODEL_NAME = "google/gemma-3-270m"   
OUTPUT_DIR = "./gemma-3-270m-finetuned-qa"

# Load model
print(f"Loading {MODEL_NAME}...")
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    device_map="auto",
    torch_dtype=torch.float32,
    low_cpu_mem_usage=True,
)

# Training setup
monitor = EpochMonitor(model=model)

data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=8,         
    per_device_eval_batch_size=8,
    gradient_accumulation_steps=1,
    learning_rate=2e-5,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_strategy="epoch",
    run_name="gemma-3-270m-qa",
    warmup_ratio=0.1,  # Uses the first 10% of steps to ramp up the LR
    lr_scheduler_type="cosine", # Smoothly decays the LR after the warmu
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
    callbacks=[monitor],
)

total_params = sum(p.numel() for p in model.parameters())
trainable_params = total_params
print(f"Total parameters: {total_params:,}")
print(f"Trainable parameters: {trainable_params:,}")
print(f"Batch size: {training_args.per_device_train_batch_size}")
print("Starting training...")

train_result = trainer.train()

trainer.save_model()
tokenizer.save_pretrained(OUTPUT_DIR)

print("\nTraining completed!")

Loading google/gemma-3-270m...

`torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors:   0%|          | 0.00/536M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/236 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/133 [00:00<?, ?B/s]

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Total parameters: 268,098,176
Trainable parameters: 268,098,176
Batch size: 8
Starting training...
Initial Model Memory Footprint:
  Parameters: 268,098,176
  Precision: 4 bytes
  Total Memory: 3.81 GB
    - Parameters: 1.00 GB
    - KV Cache (est): 2.81 GB
  Estimated FLOPs per forward pass (batch=8, seq=512): 2.05 TFLOPS

============================================================
Epoch 0 Summary
============================================================
  Duration (s)         :         49.96
  Tokens Processed     :       684,032
  Throughput (token/s) :         13690
  Training Steps       :           167
  Avg CPU (%)          :          21.0
  Avg Memory (%)       :          10.5
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          6.85
  FLOPs (per token)    :   0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================
Epoch 1 Summary
============================================================
  Duration (s)         :         51.54
  Tokens Processed     :       684,032
  Throughput (token/s) :         13272
  Training Steps       :           167
  Avg CPU (%)          :          20.2
  Avg Memory (%)       :          10.5
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          6.65
  FLOPs (per token)    :   0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================
Epoch 2 Summary
============================================================
  Duration (s)         :         51.85
  Tokens Processed     :       684,032
  Throughput (token/s) :         13192
  Training Steps       :           167
  Avg CPU (%)          :          24.6
  Avg Memory (%)       :          10.6
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          6.61
  FLOPs (per token)    :   0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['lm_head.weight'].

============================================================
TRAINING COMPLETE
============================================================
Total Training Time: 180.05s
Total Epochs: 3
Average Epoch Time: 51.12s
Total Tokens Processed: 2,052,096
Average Throughput: 11398 tokens/second
Total FLOPs: 1027.47 TFLOPS
Average TFLOPS (per second): 5.71
Overall FLOPs (per token): 0.50 GFLOPS

Final Metrics:
Memory Footprint: 3.81 GB
Inference Throughput: 15562 tokens/second
Total Training FLOPs: 342.49 TFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Training completed!

In [11]:
summarize_training_results(trainer, monitor)

====================================================================================================
TRAINING RESULTS SUMMARY TABLE
====================================================================================================
Epoch Training Loss Validation Loss Time (s) Tokens Processed Throughput (token/s) TFLOPS (per second) Avg CPU (%) Avg Memory (%) Training Steps
    0        1.7769          4.3435    49.96          684,032                13690                6.85        21.0           10.5            167
    1        0.6745          5.5878    51.54          684,032                13272                6.65        20.2           10.5            167
    2        0.4533          6.0664    51.85          684,032                13191                6.61        24.6           10.6            167

----------------------------------------------------------------------------------------------------
TRAINING STATISTICS:
----------------------------------------------------------------------------------------------------
Total Training Time:      153.4 s
Average Epoch Time:       51.1 s
Total Tokens Processed:   2,052,096
Average Throughput:       13381 tokens/second
Average CPU Usage:        21.9%
Average Memory Usage:     10.6%
Total Training FLOPs:     1027.47 TFLOPS
Average TFLOPS (per sec): 6.70
Overall FLOPs (per token): 0.50 GFLOPS

====================================================================================================

# Mixed Precision

In Large Language Model (LLM) training and inference, Mixed Precision is a technique that uses multiple numerical formats—specifically 16-bit and 32-bit floating-point numbers—to speed up computations and reduce memory consumption without sacrificing model accuracy.

Standard deep learning models traditionally use FP32 (Single Precision). Mixed Precision switches most operations to a lower-precision format like FP16 or BF16.

**The Numerical Formats**

To understand mixed precision, you have to look at how numbers are stored in bits (Sign, Exponent, and Mantissa).

- FP32 (Full Precision): Uses 32 bits. It is highly accurate but slow and memory-intensive.
- FP16 (Half Precision): Uses 16 bits. It is much faster and uses 50% less VRAM, but it has a narrow "dynamic range," meaning it can easily cause numerical errors (overflow/underflow).
- BF16 (Brain Floating Point): Also uses 16 bits but allocates more bits to the exponent. This gives it a dynamic range similar to FP32, making it much more stable for training LLMs.

**How It Works: The "Mixed" Approach**

You don't just switch everything to 16-bit that would make the model unstable. Instead, the system uses a Master Copy strategy:

- Forward Pass: Model weights are converted to 16-bit for calculation. Matrix multiplications happen in 16-bit, which modern GPU Tensor Cores handle significantly faster.
- Loss Calculation: The loss is calculated in 32-bit to maintain precision.
- Backward Pass: Gradients are calculated in 16-bit to save time and memory.
- Weight Update: To ensure tiny updates aren't "lost" due to low precision, a Master Copy of the weights is maintained in FP32. The 16-bit gradients are applied to this 32-bit master copy.

**Key Benefits**

- Memory Reduction: By using 16-bit for activations and weights, you cut VRAM requirements nearly in half. This allows for larger batch sizes or larger models on the same hardware.
- Speed: Modern GPUs have dedicated hardware (Tensor Cores) designed specifically to crunch 16-bit numbers 2x to 5x faster than 32-bit.
- Reduced Bandwidth: Moving smaller 16-bit numbers between GPU memory and the processor is faster than moving 32-bit numbers.

**Loss Scaling (For FP16)**

Because FP16 has a small dynamic range, gradients can often become so small they turn into zeros (underflow). To prevent this, Mixed Precision uses Loss Scaling:

- The loss is multiplied by a large factor (e.g., 1024) before backpropagation to "push" the gradients into a range FP16 can represent.
- The gradients are then unscaled (divided by that same factor) before updating the FP32 master weights.

## Core Mixed Precision Strategies

### Automatic Mixed Precision (AMP)

Automatic Mixed Precision (AMP) is a computational strategy that optimizes Large Language Model (LLM) training by using different numerical formats for different mathematical operations. Instead of performing every calculation in standard 32-bit floating point (FP32), AMP automatically identifies which operations can be handled in 16-bit (FP16 or BF16) to increase speed and reduce VRAM usage, while retaining critical steps in 32-bit to preserve model accuracy.

**Operation Sensitivity: How AMP Works**

Deep learning operations are categorized based on their tolerance for precision loss:
- Computational-Intensive (Precision Insensitive): Linear layers and matrix multiplications (the bulk of LLM work) are highly tolerant. AMP runs these in 16-bit. Modern GPUs utilize hardware-level Tensor Cores to process these significantly faster than FP32.
- Precision-Sensitive: Operations like Softmax, LayerNorm, and Loss calculations are prone to numerical instability. Running these in 16-bit can lead to "overflow" (numbers becoming too large) or "underflow" (numbers becoming zero). AMP keeps these in FP32 to ensure the model remains stable.

**The Mechanics: Master Weights and Scaling**

AMP maintains numerical integrity through two primary mechanisms:
- FP32 Master Weights: While the "work" (forward and backward passes) happens in 16-bit, the model maintains a master copy of weights in 32-bit. This ensures that the tiny updates from the optimizer are not rounded to zero by low precision.
- Loss Scaling (for FP16): Standard FP16 has a narrow dynamic range. AMP uses a "GradScaler" to multiply the loss by a large factor before backpropagation, pushing small gradients into a range that 16-bit can represent, then unscaling them before updating the weights.

**Implementation Automatic Mixed Precision (AMP)**

The code implements a hardware-aware version of AMP through the following steps:

**Hardware Detection**

The script first probes the GPU architecture:

`bf16_supported = torch.cuda.is_bf16_supported()`

BF16 (Bfloat16) is preferred for LLMs because it has the same exponent range as FP32, eliminating the need for complex loss scaling. If supported (Ampere architecture or newer), the code selects it; otherwise, it falls back to FP16.

**Optimized Model Loading**

`model = AutoModelForCausalLM.from_pretrained(..., torch_dtype=model_dtype)`

By setting `torch_dtype` during initialization, the model weights are loaded directly in 16-bit. This prevents a "memory spike" that typically occurs when loading a full FP32 model into RAM before converting it to a smaller format.

**Trainer Configuration**

In `TrainingArguments`, the code activates the AMP engine via two specific flags:
- `bf16=use_bf16 / fp16=use_fp16`: These flags instruct the Trainer to wrap the execution in a torch.autocast context manager. This manager intercepts every operation and decides the appropriate bit-depth on the fly.
- `max_grad_norm=1.0`: Since 16-bit math can be prone to sudden numerical spikes, Gradient Clipping is enabled to prevent "exploding gradients" from corrupting the model weights.

**Data Bottleneck Mitigation**

`dataloader_pin_memory=cuda_available`

Since AMP makes the GPU math much faster, the CPU often becomes a bottleneck. "Pinning memory" allows the system to transfer data batches to the GPU more efficiently, ensuring the processor doesn't sit idle waiting for data.

**When to use it?**

- Default for Modern GPUs: Use this whenever training on modern NVIDIA GPUs (Volta architecture and newer, such as V100, A100, H100, or RTX 30/40 series).
- Balancing Speed and Accuracy: Use it when the goal is to maximize throughput (more tokens per second) without manually identifying which layers of the model are numerically sensitive.
- Why: It is a "set it and forget it" solution. It automatically keeps sensitive operations like Softmax and LayerNorm in FP32 to prevent the model from crashing, while accelerating heavy matrix multiplications in 16-bit.

Automatic Mixed Precision (AMP) is already integrated into the Hugging Face Trainer. It handles the conversion between different precisions (FP32, BF16, and FP16) based on the operation's sensitivity to numerical stability.How it Works in TrainerThe Trainer leverages PyTorch’s native torch.autocast. When you enable mixed precision, the system automatically:Casts to Lower Precision: Runs compute-heavy operations (like Matrix Multiplications/GEMMs) in FP16 or BF16 to utilize Tensor Cores.Keeps High Precision: Keeps numerically sensitive operations (like Softmax, LayerNorm, or loss calculations) in FP32 to prevent divergence or "NaN" errors.Master Weights: Maintains a "master copy" of weights in FP32 to ensure that small gradient updates aren't lost due to rounding.How to Enable ItYou don't need to write custom loops; you simply toggle the flags in TrainingArguments.FeatureArgumentBest For...FP16 AMPfp16=TrueOlder GPUs (V100, T4) or when memory is very tight.BF16 AMPbf16=TrueModern GPUs (A100, H100, 30/40-series) for better stability.CPU AMPuse_ipex=TrueIntel CPUs supporting AVX-512/AMX.

In [ ]:
# Environment setup
import torch
from datasets import Dataset, DatasetDict
from transformers import (
    AutoTokenizer, 
    AutoModelForCausalLM,
    DataCollatorForLanguageModeling,
    Trainer,
    TrainingArguments
)

In [ ]:
# Configuration
MODEL_NAME = "google/gemma-3-270m"   
OUTPUT_DIR = "./gemma-3-270m-finetuned-qa-amp"

# Check GPU capabilities for AMP
cuda_available = torch.cuda.is_available()
bf16_supported = torch.cuda.is_bf16_supported() if cuda_available else False

print("Hardware Configuration:")
print(f"  CUDA Available: {cuda_available}")
if cuda_available:
    print(f"  GPU: {torch.cuda.get_device_name(0)}")
    print(f"  BF16 Supported: {bf16_supported}")

# Determine AMP settings
if bf16_supported:
    use_bf16 = True
    use_fp16 = False
    print("Using BF16 mixed precision")
elif cuda_available:
    use_bf16 = False
    use_fp16 = True
    print("Using FP16 mixed precision")
else:
    use_bf16 = False
    use_fp16 = False
    print("Using FP32")

# Load model with optimal dtype
model_dtype = torch.bfloat16 if use_bf16 else torch.float16 if use_fp16 else torch.float32
print(f"Loading {MODEL_NAME} with dtype: {model_dtype}")
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    device_map="auto" if cuda_available else None,
    torch_dtype=model_dtype,
    low_cpu_mem_usage=True,
)

# Training setup
monitor = EpochMonitor(model=model)

data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

# Configure training with AMP
training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    gradient_accumulation_steps=1,
    learning_rate=2e-5,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_strategy="epoch",
    run_name="gemma-3-270m-qa-amp",
    warmup_ratio=0.1,
    lr_scheduler_type="cosine",
    
    # AMP Configuration
    bf16=use_bf16,                         # Enable BF16 mixed precision
    fp16=use_fp16,                         # Enable FP16 mixed precision (if BF16 not available)
    
    # Gradient settings for AMP stability
    max_grad_norm=1.0,                     # Gradient clipping for stability
    optim="adamw_torch",                   # Recommended optimizer for AMP
    
    # Performance optimizations
    dataloader_pin_memory=cuda_available,
    dataloader_num_workers=2 if cuda_available else 0,
    
    # Optional: For even more memory savings
    # fsdp="full_shard" if cuda_available else None,  # Fully Sharded Data Parallel
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
    callbacks=[monitor],
)

total_params = sum(p.numel() for p in model.parameters())
print(f"Total parameters: {total_params:,}")
print(f"Batch size: {training_args.per_device_train_batch_size}")
print(f"AMP Mode: {'BF16' if use_bf16 else 'FP16' if use_fp16 else 'FP32'}")

if cuda_available:
    print(f"GPU Memory Total: {torch.cuda.get_device_properties(0).total_memory / 1024**3:.2f} GB")

print("Starting training...")

# Train with AMP
train_result = trainer.train()

# Save model
trainer.save_model()
tokenizer.save_pretrained(OUTPUT_DIR)

print("Training completed.")

`torch_dtype` is deprecated! Use `dtype` instead!

Hardware Configuration:
  CUDA Available: True
  GPU: NVIDIA RTX A4000
  BF16 Supported: True
Using BF16 mixed precision
Loading google/gemma-3-270m with dtype: torch.bfloat16

Loading weights:   0%|          | 0/236 [00:00<?, ?it/s]

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Total parameters: 268,098,176
Batch size: 8
AMP Mode: BF16
GPU Memory Total: 15.72 GB
Starting training...
Initial Model Memory Footprint:
  Parameters: 268,098,176
  Precision: 2 bytes
  Total Memory: 1.91 GB
    - Parameters: 0.50 GB
    - KV Cache (est): 1.41 GB
  Estimated FLOPs per forward pass (batch=8, seq=512): 2.05 TFLOPS

============================================================
Epoch 0 Summary
============================================================
  Duration (s)         :         27.66
  Tokens Processed     :       684,032
  Throughput (token/s) :         24729
  Training Steps       :           167
  Avg CPU (%)          :          18.5
  Avg Memory (%)       :          10.4
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :         12.38
  FLOPs (per token)    :   0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================
Epoch 1 Summary
============================================================
  Duration (s)         :         27.43
  Tokens Processed     :       684,032
  Throughput (token/s) :         24938
  Training Steps       :           167
  Avg CPU (%)          :          20.3
  Avg Memory (%)       :          10.4
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :         12.49
  FLOPs (per token)    :   0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================
Epoch 2 Summary
============================================================
  Duration (s)         :         27.62
  Tokens Processed     :       684,032
  Throughput (token/s) :         24766
  Training Steps       :           167
  Avg CPU (%)          :          18.8
  Avg Memory (%)       :          10.8
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :         12.40
  FLOPs (per token)    :   0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['lm_head.weight'].

============================================================
TRAINING COMPLETE
============================================================
Total Training Time: 97.34s
Total Epochs: 3
Average Epoch Time: 27.57s
Total Tokens Processed: 2,052,096
Average Throughput: 21081 tokens/second
Total FLOPs: 1027.47 TFLOPS
Average TFLOPS (per second): 10.56
Overall FLOPs (per token): 0.50 GFLOPS

Final Metrics:
Memory Footprint: 1.91 GB
Inference Throughput: 30003 tokens/second
Total Training FLOPs: 342.49 TFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Training completed.

In [9]:
summarize_training_results(trainer, monitor)

====================================================================================================
TRAINING RESULTS SUMMARY TABLE
====================================================================================================
Epoch Training Loss Validation Loss Time (s) Tokens Processed Throughput (token/s) TFLOPS (per second) Avg CPU (%) Avg Memory (%) Training Steps
    0        2.5064          3.1454    27.66          684,032                24728               12.38        18.5           10.4            167
    1        1.6570          3.4862    27.43          684,032                24937               12.49        20.3           10.4            167
    2        1.4683          3.5521    27.62          684,032                24766               12.40        18.8           10.8            167

----------------------------------------------------------------------------------------------------
TRAINING STATISTICS:
----------------------------------------------------------------------------------------------------
Total Training Time:      82.7 s
Average Epoch Time:       27.6 s
Total Tokens Processed:   2,052,096
Average Throughput:       24811 tokens/second
Average CPU Usage:        19.2%
Average Memory Usage:     10.5%
Total Training FLOPs:     1027.47 TFLOPS
Average TFLOPS (per sec): 12.42
Overall FLOPs (per token): 0.50 GFLOPS

====================================================================================================

**Reference**
- [Arxiv: Accelerating Bangla NLP Tasks with Automatic Mixed Precision: Resource-Efficient Training Preserving Model Efficacy](https://www.arxiv.org/abs/2512.00829)
- [PyTorch:Automatic Mixed Precision](https://docs.pytorch.org/tutorials/recipes/recipes/amp_recipe.html)
- [Huggingface: Mixed precision trainner](https://huggingface.co/docs/transformers/en/perf_train_gpu_one)
- [Huggingface:Trainner](https://huggingface.co/docs/transformers/v4.33.0/main_classes/trainer)

### BF16/FP16-FP32 Hybrid

The BF16/FP16-FP32 Hybrid approach, often referred to as Mixed Precision Training, is a strategy designed to combine the high speed and low memory footprint of 16-bit formats with the numerical stability of 32-bit formats. In this system, the "heavy lifting" (math-intensive calculations) is done in 16-bit, while the critical "source of truth" (model weights) is maintained in 32-bit.

**The Core Components**

The hybrid system relies on three distinct numerical formats, each chosen for a specific task:

- FP32 (Single Precision): Uses 32 bits. It provides the high precision necessary for storing weights and accumulating tiny gradient updates.
- FP16 (Half Precision): Uses 16 bits. It is very fast on hardware like NVIDIA Tensor Cores but has a limited range, which can lead to "overflow" or "underflow."
- BF16 (Brain Floating Point): Uses 16 bits but maintains the same exponent range as FP32. This makes it significantly more stable for LLMs than FP16 because it handles large values without needing complex loss scaling.

**How the Hybrid System Works**

The hybrid process follows a specific cycle during each training step:

- The Master Copy: A set of Master Weights is stored in FP32.
- Conversion: For the forward pass, these weights are converted (casted) to BF16/FP16.
- Forward/Backward Passes: All matrix multiplications and hidden state calculations are performed in 16-bit. This reduces VRAM usage by roughly 50% and increases speed by 2x to 5x.
- Gradient Calculation: Gradients are calculated in 16-bit.
- The Update: The optimizer takes the 16-bit gradients and applies them to the FP32 Master Weights. Because the master weights are in 32-bit, tiny updates (e.g., 0.00002) are preserved rather than being rounded to zero by 16-bit limitations.

**Implementation BF16/FP16-FP32 Hybrid**

The script automates this hybrid workflow using the Hugging Face Trainer and PyTorch's backend.

**Hardware-Aware Selection**

The code first detects if the GPU supports BF16:

`bf16_supported = torch.cuda.is_bf16_supported()`

If supported, it sets `model_dtype = torch.bfloat16`. BF16 is the preferred hybrid partner for LLMs like Gemma because its numerical range matches FP32, preventing the model from "diverging" or crashing during training.

**Low-Memory Loading**

`model = AutoModelForCausalLM.from_pretrained(..., torch_dtype=model_dtype)`

By loading the model in bfloat16, the script ensures that the active weights used for calculations are already in the 16-bit format, saving significant system RAM and VRAM from the moment the script starts.

**Activation**

In TrainingArguments, the hybrid logic is triggered by:

- `bf16=bf16_supported`: This flag tells the Trainer to use the torch.autocast context. This automatically handles the conversion between the 16-bit math passes and the 32-bit weight updates.
- `optim="adamw_torch"`: This optimizer is designed to handle the "Master Weight" logic. It keeps the optimizer states (momentum and variance) in 32-bit to ensure the training remains stable over thousands of steps.
- `max_grad_norm=1.0`: This provides Gradient Clipping. Even with BF16 stability, hybrid training can produce large gradients; clipping them ensures the 32-bit master weights are not "shattered" by an oversized update.

**When to use BF16 (Brain Float 16)?**

- Standard for Large-Scale LLMs: This is the current industry standard. Use it if the GPU supports it (NVIDIA Ampere architecture or newer, like A100/RTX 30-series).
- Maximum Stability: Use it for long training runs where "loss spikes" are a concern. Because BF16 has the same exponent range as FP32, it handles large values much better than standard FP16.

**When to use FP16 (Standard Half Precision)?**

- Legacy Hardware Support: Use this only if the GPU is older (e.g., Tesla V100 or T4) and does not support BF16.
- VRAM Constraints: Use it when memory is extremely limited, though it requires more careful tuning than BF16.

In [ ]:
# Environment Setup
import torch
from datasets import Dataset, DatasetDict
from transformers import (
    AutoTokenizer, 
    AutoModelForCausalLM,
    DataCollatorForLanguageModeling,
    Trainer,
    TrainingArguments
)

In [ ]:
# Configuration
MODEL_NAME = "google/gemma-3-270m"   
OUTPUT_DIR = "./gemma-3-270m-finetuned-qa-hybrid"

# Check GPU capabilities for BF16
cuda_available = torch.cuda.is_available()
bf16_supported = torch.cuda.is_bf16_supported() if cuda_available else False

print("Hardware Configuration:")
print(f"CUDA Available: {cuda_available}")
if cuda_available:
    print(f"GPU: {torch.cuda.get_device_name(0)}")
    print(f"BF16 Supported: {bf16_supported}")

# Select precision
if bf16_supported:
    model_dtype = torch.bfloat16
    print("Using BF16-FP32 Hybrid: BF16 forward/backward, FP32 master weights")
else:
    model_dtype = torch.float32
    print("BF16 not supported, using FP32")

# Load model in BF16
print(f"Loading {MODEL_NAME}...")
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    device_map="auto" if cuda_available else None,
    torch_dtype=model_dtype,
    low_cpu_mem_usage=True,
)

# Training setup
monitor = EpochMonitor(model=model)

data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

# Configure BF16-FP32 Hybrid training
training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    gradient_accumulation_steps=1,
    learning_rate=2e-5,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_strategy="epoch",
    run_name="gemma-3-270m-qa-hybrid",
    warmup_ratio=0.1,
    lr_scheduler_type="cosine",
    
    # BF16-FP32 Hybrid configuration
    bf16=bf16_supported,  # BF16 forward/backward passes
    fp16=False,           # Disable FP16
    optim="adamw_torch",  # AdamW with PyTorch implementation
    
    # Stability settings for hybrid training
    max_grad_norm=1.0,
    
    # Performance optimizations
    dataloader_pin_memory=cuda_available,
    dataloader_num_workers=2 if cuda_available else 0,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
    callbacks=[monitor],
)

total_params = sum(p.numel() for p in model.parameters())
print(f"Total parameters: {total_params:,}")
print(f"Model dtype: {model.dtype}")
print(f"Batch size: {training_args.per_device_train_batch_size}")
print(f"BF16 Enabled: {bf16_supported}")

print("Starting training with BF16-FP32 Hybrid...")

train_result = trainer.train()

trainer.save_model()
tokenizer.save_pretrained(OUTPUT_DIR)

print("Training completed.")

Hardware Configuration:
CUDA Available: True
GPU: NVIDIA RTX A4000
BF16 Supported: True
Using BF16-FP32 Hybrid: BF16 forward/backward, FP32 master weights
Loading google/gemma-3-270m...

Loading weights:   0%|          | 0/236 [00:00<?, ?it/s]

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Total parameters: 268,098,176
Model dtype: torch.bfloat16
Batch size: 8
BF16 Enabled: True
Starting training with BF16-FP32 Hybrid...
Initial Model Memory Footprint:
  Parameters: 268,098,176
  Precision: 2 bytes
  Total Memory: 1.91 GB
    - Parameters: 0.50 GB
    - KV Cache (est): 1.41 GB
  Estimated FLOPs per forward pass (batch=8, seq=512): 2.05 TFLOPS

============================================================
Epoch 0 Summary
============================================================
  Duration (s)         :         27.48
  Tokens Processed     :       684,032
  Throughput (token/s) :         24892
  Training Steps       :           167
  Avg CPU (%)          :          18.8
  Avg Memory (%)       :          10.8
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :         12.46
  FLOPs (per token)    :   0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================
Epoch 1 Summary
============================================================
  Duration (s)         :         27.55
  Tokens Processed     :       684,032
  Throughput (token/s) :         24825
  Training Steps       :           167
  Avg CPU (%)          :          18.0
  Avg Memory (%)       :          10.8
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :         12.43
  FLOPs (per token)    :   0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================
Epoch 2 Summary
============================================================
  Duration (s)         :         27.81
  Tokens Processed     :       684,032
  Throughput (token/s) :         24593
  Training Steps       :           167
  Avg CPU (%)          :          25.4
  Avg Memory (%)       :          10.9
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :         12.31
  FLOPs (per token)    :   0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['lm_head.weight'].

============================================================
TRAINING COMPLETE
============================================================
Total Training Time: 97.58s
Total Epochs: 3
Average Epoch Time: 27.62s
Total Tokens Processed: 2,052,096
Average Throughput: 21030 tokens/second
Total FLOPs: 1027.47 TFLOPS
Average TFLOPS (per second): 10.53
Overall FLOPs (per token): 0.50 GFLOPS

Final Metrics:
Memory Footprint: 1.91 GB
Inference Throughput: 29893 tokens/second
Total Training FLOPs: 342.49 TFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Training completed.

In [11]:
summarize_training_results(trainer, monitor)

====================================================================================================
TRAINING RESULTS SUMMARY TABLE
====================================================================================================
Epoch Training Loss Validation Loss Time (s) Tokens Processed Throughput (token/s) TFLOPS (per second) Avg CPU (%) Avg Memory (%) Training Steps
    0        2.5062          3.1417    27.48          684,032                24891               12.46        18.8           10.8            167
    1        1.6569          3.4874    27.55          684,032                24824               12.43        18.0           10.8            167
    2        1.4681          3.5583    27.81          684,032                24593               12.31        25.4           10.9            167

----------------------------------------------------------------------------------------------------
TRAINING STATISTICS:
----------------------------------------------------------------------------------------------------
Total Training Time:      82.8 s
Average Epoch Time:       27.6 s
Total Tokens Processed:   2,052,096
Average Throughput:       24769 tokens/second
Average CPU Usage:        20.7%
Average Memory Usage:     10.8%
Total Training FLOPs:     1027.47 TFLOPS
Average TFLOPS (per sec): 12.40
Overall FLOPs (per token): 0.50 GFLOPS

====================================================================================================

**Reference**
- [Arxiv: Defeating the Training-Inference Mismatch via FP16](https://arxiv.org/html/2510.26788v1)
- [Arxiv:Give Me FP32 or Give Me Death? Challenges and Solutions for Reproducible Reasoning](https://arxiv.org/html/2506.09501v1)
- [Huggingface: Mixed precision trainner](https://huggingface.co/docs/transformers/en/perf_train_gpu_one)
- [Huggingface:Trainner](https://huggingface.co/docs/transformers/v4.33.0/main_classes/trainer)

### Dynamic Loss Scaling

Dynamic Loss Scaling is a numerical safety mechanism used primarily in 16-bit floating-point (FP16) training. It prevents a phenomenon called gradient underflow, where the small mathematical updates necessary for learning become so tiny that they round to zero, effectively "stalling" the model's training.

By automatically inflating and deflating the loss value, Dynamic Loss Scaling keeps the model’s gradients within the narrow "representable range" of the FP16 format.

**The Underflow Problem in FP16**

FP16 uses only 16 bits to store numbers. While this is fast, its range is limited. In deep learning, gradients often become extremely small (e.g., $10^{-7}$ or $10^{-10}$).
- FP16 Limit: The smallest positive number FP16 can represent is roughly $6×10^−8).
- The Result: Any gradient smaller than this limit becomes exactly 0.0. If 30 percent of your gradients become zero, the model stops learning and the training likely fails (diverges).

**How Dynamic Loss Scaling Works**

Instead of manually picking a "safe" number to multiply your loss by, the Dynamic algorithm automates the process:
- Scale Up: Before the backward pass, the loss is multiplied by a large scale factor (e.g., 65,536). Because of the Chain Rule in calculus, this scales every gradient in the network by that same factor, pushing them into the safe FP16 range.
- Check for Overflows: After the backward pass, the system checks the gradients for Inf (infinity) or NaN (Not a Number).
- If an overflow is found: The scale was too high. The optimizer skips that training step, divides the scale factor by 2, and tries again.
- If no overflow is found: The step is successful. The gradients are "unscaled" (divided by the factor) before being applied to the weights.
- Gradual Increase: If training is stable for a set number of steps (e.g., 2,000 steps without an overflow), the algorithm attempts to increase the scale factor to ensure gradients stay as far from the "zero-zone" as possible.

**Implementation Dynamic Loss Scaling**

The code handles this complex logic through two specific configurations in the TrainingArguments:

The Precision Logic

    if bf16_supported:
        use_bf16 = True
        use_fp16 = False
    else:
        use_bf16 = False
        use_fp16 = cuda_available
        
- BF16 Case: If the GPU supports BF16 (like an A100 or RTX 30/40 series), the code prioritizes it. BF16 does not need loss scaling because it has the same exponent range as FP32, meaning it can represent the same tiny numbers as 32-bit math.
- FP16 Case: If only standard FP16 is available (older GPUs), the code enables `use_fp16 = True`.

**The Trainer Integration**

    training_args = TrainingArguments(
        ...
        fp16=use_fp16,  # Activates automatic dynamic loss scaling
        bf16=use_bf16,  # BF16 ignores scaling logic
        ...
    )
    
When `fp16=True` is passed to the Hugging Face Trainer, it automatically initializes a torch.cuda.amp.GradScaler. You do not need to write the "multiply/divide/check" logic yourself; the Trainer intercepts the `loss.backward() and optimizer.step()` calls to manage the scale factor in the background.

**When to use it?**

- Mandatory for FP16: If training is conducted in FP16, this must be used. Without it, the small gradients common in deep networks will "underflow" (become zero), and the model will stop learning.
- Avoid with BF16: Do not use this with BF16. BF16’s wide dynamic range naturally prevents underflow, so adding a scaling factor is redundant and can occasionally cause unnecessary computation overhead.
- Why: It acts as a protective buffer. By multiplying the loss by a large factor, it "pushes" tiny gradients into the range that 16-bit floats can actually represent.

In [ ]:
# Environment Setup
import torch
from datasets import Dataset, DatasetDict
from transformers import (
    AutoTokenizer, 
    AutoModelForCausalLM,
    DataCollatorForLanguageModeling,
    Trainer,
    TrainingArguments
)

In [ ]:
# Configuration
MODEL_NAME = "google/gemma-3-270m"   
OUTPUT_DIR = "./gemma-3-270m-finetuned-qa-dynamic"

# Check GPU capabilities
cuda_available = torch.cuda.is_available()
bf16_supported = torch.cuda.is_bf16_supported() if cuda_available else False

print("Hardware Configuration:")
print(f"CUDA Available: {cuda_available}")
if cuda_available:
    print(f"GPU: {torch.cuda.get_device_name(0)}")

# Select precision mode
if bf16_supported:
    use_bf16 = True
    use_fp16 = False
    print("Using BF16 (no dynamic loss scaling needed)")
else:
    use_bf16 = False
    use_fp16 = cuda_available
    print("Using FP16 with dynamic loss scaling")

# Load model
print(f"Loading {MODEL_NAME}...")
model_dtype = torch.bfloat16 if use_bf16 else torch.float16 if use_fp16 else torch.float32
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    device_map="auto" if cuda_available else None,
    torch_dtype=model_dtype,
    low_cpu_mem_usage=True,
)

# Training setup
monitor = EpochMonitor(model=model)

data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

# Configure training with automatic dynamic loss scaling
training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    gradient_accumulation_steps=1,
    learning_rate=2e-5,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_strategy="epoch",
    run_name="gemma-3-270m-qa-dynamic",
    warmup_ratio=0.1,
    lr_scheduler_type="cosine",
    
    # AMP configuration with automatic dynamic loss scaling
    fp16=use_fp16,          # FP16 with automatic loss scaling
    bf16=use_bf16,          # BF16 (no loss scaling needed)
    
    # Dynamic loss scaling settings (only applies to FP16)
    fp16_full_eval=False,   # Use FP16 for evaluation when training with FP16
    
    # Optimization settings
    max_grad_norm=1.0,
    optim="adamw_torch",
    
    # Performance settings
    dataloader_pin_memory=cuda_available,
    dataloader_num_workers=2 if cuda_available else 0,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
    callbacks=[monitor],
)

total_params = sum(p.numel() for p in model.parameters())
print(f"Total parameters: {total_params:,}")
print(f"Model dtype: {model.dtype}")
print(f"Batch size: {training_args.per_device_train_batch_size}")
print(f"FP16 with dynamic scaling: {use_fp16}")
print(f"BF16: {use_bf16}")

print("Starting training...")

train_result = trainer.train()

trainer.save_model()
tokenizer.save_pretrained(OUTPUT_DIR)

print("Training completed.")

Hardware Configuration:
CUDA Available: True
GPU: NVIDIA RTX A4000
Using BF16 (no dynamic loss scaling needed)
Loading google/gemma-3-270m...

Loading weights:   0%|          | 0/236 [00:00<?, ?it/s]

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Total parameters: 268,098,176
Model dtype: torch.bfloat16
Batch size: 8
FP16 with dynamic scaling: False
BF16: True
Starting training...
Initial Model Memory Footprint:
  Parameters: 268,098,176
  Precision: 2 bytes
  Total Memory: 1.91 GB
    - Parameters: 0.50 GB
    - KV Cache (est): 1.41 GB
  Estimated FLOPs per forward pass (batch=8, seq=512): 2.05 TFLOPS

============================================================
Epoch 0 Summary
============================================================
  Duration (s)         :         28.00
  Tokens Processed     :       684,032
  Throughput (token/s) :         24427
  Training Steps       :           167
  Avg CPU (%)          :          26.0
  Avg Memory (%)       :          11.9
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :         12.23
  FLOPs (per token)    :   0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================
Epoch 1 Summary
============================================================
  Duration (s)         :         27.93
  Tokens Processed     :       684,032
  Throughput (token/s) :         24487
  Training Steps       :           167
  Avg CPU (%)          :          22.7
  Avg Memory (%)       :          11.6
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :         12.26
  FLOPs (per token)    :   0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================
Epoch 2 Summary
============================================================
  Duration (s)         :         27.99
  Tokens Processed     :       684,032
  Throughput (token/s) :         24442
  Training Steps       :           167
  Avg CPU (%)          :          20.5
  Avg Memory (%)       :          11.6
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :         12.24
  FLOPs (per token)    :   0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['lm_head.weight'].

============================================================
TRAINING COMPLETE
============================================================
Total Training Time: 98.94s
Total Epochs: 3
Average Epoch Time: 27.97s
Total Tokens Processed: 2,052,096
Average Throughput: 20742 tokens/second
Total FLOPs: 1027.47 TFLOPS
Average TFLOPS (per second): 10.39
Overall FLOPs (per token): 0.50 GFLOPS

Final Metrics:
Memory Footprint: 1.91 GB
Inference Throughput: 29620 tokens/second
Total Training FLOPs: 342.49 TFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Training completed.

In [13]:
summarize_training_results(trainer, monitor)

====================================================================================================
TRAINING RESULTS SUMMARY TABLE
====================================================================================================
Epoch Training Loss Validation Loss Time (s) Tokens Processed Throughput (token/s) TFLOPS (per second) Avg CPU (%) Avg Memory (%) Training Steps
    0        2.5059          3.1462    28.00          684,032                24426               12.23        26.0           11.9            167
    1        1.6562          3.4810    27.93          684,032                24486               12.26        22.7           11.6            167
    2        1.4672          3.5534    27.99          684,032                24442               12.24        20.5           11.6            167

----------------------------------------------------------------------------------------------------
TRAINING STATISTICS:
----------------------------------------------------------------------------------------------------
Total Training Time:      83.9 s
Average Epoch Time:       28.0 s
Total Tokens Processed:   2,052,096
Average Throughput:       24452 tokens/second
Average CPU Usage:        23.1%
Average Memory Usage:     11.7%
Total Training FLOPs:     1027.47 TFLOPS
Average TFLOPS (per sec): 12.24
Overall FLOPs (per token): 0.50 GFLOPS

====================================================================================================

**Reference**
- [Arxiv: Dynamic Loss-Based Sample Reweighting for Improved Large Language Model Pretraining](https://arxiv.org/html/2502.06733v1)
- [Huggingface:Trainner](https://huggingface.co/docs/transformers/v4.33.0/main_classes/trainer)

### Gradient Clipping Integration

Gradient Clipping Integration is a technique used to ensure the stability of Large Language Models (LLMs) during training by preventing gradients from becoming excessively large. When training in mixed precision (FP16 or BF16), the model is highly susceptible to numerical "explosions" where weight updates exceed the maximum value the hardware can store, leading to NaN (Not a Number) errors that effectively break the training process.

**How Gradient Clipping Works**

Gradient clipping acts as a safety valve for the optimizer. The most common method used in LLMs is Global Norm Clipping. Instead of looking at individual parameters, the system treats all model gradients as a single, massive vector. It calculates the L2 Norm (total magnitude) of this vector.

If this magnitude exceeds a predefined threshold—in the provided code, `max_grad_norm=1.0`—the system rescales the entire vector down so that its magnitude equals the threshold. This preserves the relative direction of the learning steps (the "path" the model takes to improve) while ensuring the size of the step never becomes dangerously large.

**Implements Gradient Clipping**

The code implements Dynamic Loss Scaling specifically through the `fp16=use_fp16` argument in `TrainingArguments`. This is necessary for FP16 training because its numerical range is narrow, causing small gradients to "vanish" (become zero). The process works as follows:
- Scaling Up: Before the backward pass, the loss is multiplied by a large scale factor. This "pushes" the gradients into a range that FP16 can represent.
- Overflow Check: If the gradients result in an "Infinity" (overflow), the Trainer (via the GradScaler) catches it, skips the update to prevent model corruption, and reduces the scale factor.
- Unscaling and Clipping: Before updating the weights, the gradients are unscaled (returned to their original size). It is at this precise moment that the `max_grad_norm=1.0` is applied. The clipping is performed on the unscaled gradients to ensure the threshold is mathematically meaningful.

**When to Use Gradient Clipping**

This combination of mixed precision and gradient clipping should be used in the following scenarios:
- Fine-Tuning LLMs (Gemma, Llama, etc.): LLMs are sensitive to large weight updates. Clipping is considered standard practice to prevent the model from "forgetting" pre-trained knowledge due to a single bad batch of data.
- Using FP16 or BF16: Whenever Mixed Precision is enabled to save memory, clipping is essential. In low-precision environments, the "numerical floor" and "ceiling" are much closer together, making spikes more lethal to the model.
- High Learning Rates: If a higher learning rate is required to speed up training, gradient clipping acts as a guardrail to keep the updates manageable.
- Unstable Loss Curves: If the training loss shows sudden, massive spikes (spiky loss), gradient clipping can help smooth the optimization path.

**Summary of the Combined Logic**

In the provided code, the script first determines the best hardware precision (BF16 or FP16). By passing these choices into the Trainer, it activates a coordinated dance: the GradScaler handles the precision range (Dynamic Loss Scaling), while `max_grad_norm` handles the magnitude of the updates (Clipping).

In [ ]:
# Environment Setup
import torch
from datasets import Dataset, DatasetDict
from transformers import (
    AutoTokenizer, 
    AutoModelForCausalLM,
    DataCollatorForLanguageModeling,
    Trainer,
    TrainingArguments
)

In [ ]:
# Configuration
MODEL_NAME = "google/gemma-3-270m"   
OUTPUT_DIR = "./gemma-3-270m-finetuned-qa-clipped"

# Check GPU capabilities
cuda_available = torch.cuda.is_available()
bf16_supported = torch.cuda.is_bf16_supported() if cuda_available else False

print("Hardware Configuration:")
print(f"CUDA Available: {cuda_available}")
if cuda_available:
    print(f"GPU: {torch.cuda.get_device_name(0)}")

# Select precision
use_bf16 = bf16_supported
use_fp16 = cuda_available and not bf16_supported

# Load model
model_dtype = torch.bfloat16 if use_bf16 else torch.float16 if use_fp16 else torch.float32
print(f"Loading {MODEL_NAME} in {model_dtype}...")
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    device_map="auto" if cuda_available else None,
    torch_dtype=model_dtype,
    low_cpu_mem_usage=True,
)

# Training setup
monitor = EpochMonitor(model=model)

data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

# Configure training with gradient clipping and mixed precision
training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    gradient_accumulation_steps=1,
    learning_rate=2e-5,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_strategy="epoch",
    run_name="gemma-3-270m-qa-clipped",
    warmup_ratio=0.1,
    lr_scheduler_type="cosine",
    
    # Mixed precision configuration
    fp16=use_fp16,
    bf16=use_bf16,
    
    # Gradient clipping integration
    max_grad_norm=1.0,  # Critical for mixed precision stability
    
    # Optimization settings
    optim="adamw_torch",
    
    # Performance settings
    dataloader_pin_memory=cuda_available,
    dataloader_num_workers=2 if cuda_available else 0,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
    callbacks=[monitor],
)

total_params = sum(p.numel() for p in model.parameters())
print(f"Total parameters: {total_params:,}")
print(f"Model dtype: {model.dtype}")
print(f"Batch size: {training_args.per_device_train_batch_size}")
print(f"Gradient clipping: max_grad_norm={training_args.max_grad_norm}")
print(f"Mixed precision: {'BF16' if use_bf16 else 'FP16' if use_fp16 else 'FP32'}")

print("Starting training with gradient clipping...")

train_result = trainer.train()

trainer.save_model()
tokenizer.save_pretrained(OUTPUT_DIR)

print("Training completed.")

Hardware Configuration:
CUDA Available: True
GPU: NVIDIA RTX A4000
Loading google/gemma-3-270m in torch.bfloat16...

Loading weights:   0%|          | 0/236 [00:00<?, ?it/s]

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Total parameters: 268,098,176
Model dtype: torch.bfloat16
Batch size: 8
Gradient clipping: max_grad_norm=1.0
Mixed precision: BF16
Starting training with gradient clipping...
Initial Model Memory Footprint:
  Parameters: 268,098,176
  Precision: 2 bytes
  Total Memory: 1.91 GB
    - Parameters: 0.50 GB
    - KV Cache (est): 1.41 GB
  Estimated FLOPs per forward pass (batch=8, seq=512): 2.05 TFLOPS

============================================================
Epoch 0 Summary
============================================================
  Duration (s)         :         27.99
  Tokens Processed     :       684,032
  Throughput (token/s) :         24434
  Training Steps       :           167
  Avg CPU (%)          :          18.1
  Avg Memory (%)       :          11.6
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :         12.23
  FLOPs (per token)    :   0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================
Epoch 1 Summary
============================================================
  Duration (s)         :         27.88
  Tokens Processed     :       684,032
  Throughput (token/s) :         24533
  Training Steps       :           167
  Avg CPU (%)          :          21.1
  Avg Memory (%)       :          11.7
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :         12.28
  FLOPs (per token)    :   0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================
Epoch 2 Summary
============================================================
  Duration (s)         :         28.07
  Tokens Processed     :       684,032
  Throughput (token/s) :         24365
  Training Steps       :           167
  Avg CPU (%)          :          20.0
  Avg Memory (%)       :          11.6
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :         12.20
  FLOPs (per token)    :   0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['lm_head.weight'].

============================================================
TRAINING COMPLETE
============================================================
Total Training Time: 99.29s
Total Epochs: 3
Average Epoch Time: 27.98s
Total Tokens Processed: 2,052,096
Average Throughput: 20668 tokens/second
Total FLOPs: 1027.47 TFLOPS
Average TFLOPS (per second): 10.35
Overall FLOPs (per token): 0.50 GFLOPS

Final Metrics:
Memory Footprint: 1.91 GB
Inference Throughput: 29739 tokens/second
Total Training FLOPs: 342.49 TFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Training completed.

In [15]:
summarize_training_results(trainer, monitor)

====================================================================================================
TRAINING RESULTS SUMMARY TABLE
====================================================================================================
Epoch Training Loss Validation Loss Time (s) Tokens Processed Throughput (token/s) TFLOPS (per second) Avg CPU (%) Avg Memory (%) Training Steps
    0        2.5062          3.1506    27.99          684,032                24434               12.23        18.1           11.6            167
    1        1.6563          3.4858    27.88          684,032                24532               12.28        21.1           11.7            167
    2        1.4670          3.5552    28.07          684,032                24364               12.20        20.0           11.6            167

----------------------------------------------------------------------------------------------------
TRAINING STATISTICS:
----------------------------------------------------------------------------------------------------
Total Training Time:      84.0 s
Average Epoch Time:       28.0 s
Total Tokens Processed:   2,052,096
Average Throughput:       24444 tokens/second
Average CPU Usage:        19.7%
Average Memory Usage:     11.6%
Total Training FLOPs:     1027.47 TFLOPS
Average TFLOPS (per sec): 12.24
Overall FLOPs (per token): 0.50 GFLOPS

====================================================================================================

**Reference**
- [Arxiv: Why gradient clipping accelerates training: A theoretical justification for adaptivity](https://arxiv.org/abs/1905.11881)
- [Arxiv:Revisiting Gradient Clipping: Stochastic bias and tight convergence guarantees](https://arxiv.org/abs/2305.01588)
- [Huggingface:Trainer](https://huggingface.co/docs/transformers/en/main_classes/trainer)

## Advanced Mixed Precision Techniques

### Per-Layer/Component Precision Selection

Per-Layer/Component Precision Selection is an optimization strategy that assigns different numerical precisions to specific parts of a model based on their "sensitivity" or importance to the final output. In Large Language Models (LLMs), not all layers are equally robust to the noise introduced by compression (quantization). While the bulk of the model’s knowledge can be stored in low-precision formats (like 4-bit) to save memory, certain "critical" components—such as the final classification layer (LM head) or normalization layers—require higher precision (like 16-bit or 32-bit) to prevent the model's logic from collapsing.

**How Per-Layer Precision Works**

This method treats the model as a heterogeneous collection of parts rather than a uniform block of data.
- Quantized Layers: The majority of the model’s parameters (attention projections and feed-forward networks) are compressed to 4-bit or 8-bit formats. Because there are millions of these parameters, the tiny mathematical errors introduced by compression tend to average out across the network.
- Critical "High-Precision" Layers: The LM Head (which selects the final token) and Input Embeddings are usually kept in 16-bit (BF16/FP16) or 32-bit (FP32). If these layers are over-compressed, the model loses its "vocabulary" or its ability to differentiate between similar word meanings.
- The Computation Bridge: While weights are stored in low precision, the actual "math" is performed in a higher compute_dtype (like BF16). Weights are "de-quantized" on the fly for the calculation and then discarded, keeping VRAM usage low throughout the process.

**Implements Per-Layer Precision Selection**

The provided script uses QLoRA (Quantized Low-Rank Adaptation) via the bitsandbytes and peft libraries to execute this fine-grained control.

**1. Initial Quantization (The Storage Layer)**

    quantization_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_compute_dtype=compute_dtype,
    )
    
This configuration forces the massive weight matrices of Gemma-3-270m into a 4-bit "NormalFloat" format for storage. However, notice `bnb_4bit_compute_dtype=compute_dtype`. This ensures that whenever a calculation happens, the hardware uses BF16/FP16 to maintain accuracy.

**2. Automatic Component Protection**

    model = prepare_model_for_kbit_training(model)
    
This is the most critical line for per-layer precision. This function automatically scans the model architecture and identifies modules that must remain in high precision for training to succeed. It ensures that LayerNorm and the LM Head are cast to FP32. Without this, the gradients would likely explode or "NaN" during the very first training step.

**3. Targeted Learning (Adapters)**

    lora_config = LoraConfig(
        target_modules=["q_proj", "k_proj", "v_proj", ...],
        task_type="CAUSAL_LM",
    )
    
By using LoRA, the code does not actually train the 4-bit weights. Instead, it freezes the base 4-bit model and attaches 16-bit trainable adapters to specific layers. This results in a hybrid state: 95% of the model is frozen 4-bit, but the 5% that is actually "learning" exists in high-precision 16-bit.

**When to Use It?**

This method is the "gold standard" for fine-tuning on consumer hardware or when resources are constrained.
- VRAM Limitations: Use this when a model is technically too large for your GPU (e.g., training a 7B model on a single 16GB RTX 4080).
- Maintaining Reasoning Performance: Use this instead of "standard" quantization when the model needs to perform complex tasks like coding or math. Keeping the critical layers and adapters in high precision prevents the "lobotomy effect" often seen in purely 4-bit models.
- Latency-Critical Prototyping: Use this when you need to run many experiments quickly. Because it uses less memory, you can increase the batch size or sequence length compared to full 16-bit training.

In [ ]:
# Environment Setup
import torch
from datasets import Dataset, DatasetDict
from transformers import (
    AutoTokenizer, 
    AutoModelForCausalLM,
    DataCollatorForLanguageModeling,
    Trainer,
    TrainingArguments
)

In [ ]:
# Configuration
MODEL_NAME = "google/gemma-3-270m"   
OUTPUT_DIR = "./gemma-3-270m-finetuned-qa-bitsandbytes"

# Check GPU capabilities
cuda_available = torch.cuda.is_available()
print(f"CUDA Available: {cuda_available}")

# Configure BitsAndBytes for per-layer precision
from transformers import BitsAndBytesConfig
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training

# Configure mixed precision and critical layer handling
compute_dtype = torch.bfloat16 if torch.cuda.is_bf16_supported() else torch.float16

quantization_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=compute_dtype,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_storage=torch.uint8,
)

print(f"Loading {MODEL_NAME} with 4-bit quantization...")
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    quantization_config=quantization_config,
    device_map="auto" if cuda_available else None,
    low_cpu_mem_usage=True,
)

# Prepare model for k-bit training
model = prepare_model_for_kbit_training(model)

# Configure LoRA for trainable adapters (keeps critical layers trainable)
lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
)

# Apply LoRA to the quantized model
model = get_peft_model(model, lora_config)

# Training setup
monitor = EpochMonitor(model=model)

data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

# Configure training
training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    gradient_accumulation_steps=2,
    learning_rate=2e-4,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_strategy="epoch",
    run_name="gemma-3-270m-qa-bitsandbytes",
    warmup_steps=50,
    lr_scheduler_type="cosine",
    
    # Mixed precision configuration
    bf16=torch.cuda.is_bf16_supported(),
    fp16=not torch.cuda.is_bf16_supported() and cuda_available,
    
    # Optimization settings
    max_grad_norm=0.3,
    optim="paged_adamw_8bit",
    
    # Performance settings
    dataloader_pin_memory=cuda_available,
    dataloader_num_workers=2 if cuda_available else 0,
    
    # Gradient checkpointing for memory efficiency
    gradient_checkpointing=True,
    gradient_checkpointing_kwargs={"use_reentrant": False},
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
    callbacks=[monitor],
)

# Print configuration
total_params = sum(p.numel() for p in model.parameters())
trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f"Total parameters: {total_params:,}")
print(f"Trainable parameters: {trainable_params:,}")
print(f"Trainable percentage: {100 * trainable_params / total_params:.2f}%")
print(f"Batch size: {training_args.per_device_train_batch_size}")
print(f"Gradient accumulation steps: {training_args.gradient_accumulation_steps}")
print(f"Quantization: 4-bit NF4")
print(f"Compute dtype: {compute_dtype}")
print(f"Mixed precision: {'BF16' if torch.cuda.is_bf16_supported() else 'FP16' if cuda_available else 'FP32'}")

print("Starting training with per-layer precision (LoRA adapters)...")

train_result = trainer.train()

# Save LoRA adapters
model.save_pretrained(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)

print("Training completed.")

CUDA Available: True
Loading google/gemma-3-270m with 4-bit quantization...

Loading weights:   0%|          | 0/236 [00:00<?, ?it/s]

Total parameters: 221,760,128
Trainable parameters: 3,796,992
Trainable percentage: 1.71%
Batch size: 4
Gradient accumulation steps: 2
Quantization: 4-bit NF4
Compute dtype: torch.bfloat16
Mixed precision: BF16
Starting training with per-layer precision (LoRA adapters)...
Initial Model Memory Footprint:
  Parameters: 221,760,128
  Precision: 4 bytes
  Total Memory: 3.64 GB
    - Parameters: 0.83 GB
    - KV Cache (est): 2.81 GB
  Estimated FLOPs per forward pass (batch=8, seq=512): 2.05 TFLOPS

============================================================
Epoch 0 Summary
============================================================
  Duration (s)         :        114.50
  Tokens Processed     :       342,016
  Throughput (token/s) :          2987
  Training Steps       :           167
  Avg CPU (%)          :          20.3
  Avg Memory (%)       :          11.7
  Total FLOPs          : 171.25 TFLOPS
  TFLOPS (per second)  :          1.50
  FLOPs (per token)    :   0.50 GFLOPS

============================================================
Epoch 1 Summary
============================================================
  Duration (s)         :        113.16
  Tokens Processed     :       342,016
  Throughput (token/s) :          3022
  Training Steps       :           167
  Avg CPU (%)          :          20.8
  Avg Memory (%)       :          11.7
  Total FLOPs          : 171.25 TFLOPS
  TFLOPS (per second)  :          1.51
  FLOPs (per token)    :   0.50 GFLOPS

============================================================
Epoch 2 Summary
============================================================
  Duration (s)         :        113.15
  Tokens Processed     :       342,016
  Throughput (token/s) :          3023
  Training Steps       :           167
  Avg CPU (%)          :          20.8
  Avg Memory (%)       :          11.9
  Total FLOPs          : 171.25 TFLOPS
  TFLOPS (per second)  :          1.51
  FLOPs (per token)    :   0.50 GFLOPS

============================================================
TRAINING COMPLETE
============================================================
Total Training Time: 363.16s
Total Epochs: 3
Average Epoch Time: 113.61s
Total Tokens Processed: 1,026,048
Average Throughput: 2825 tokens/second
Total FLOPs: 513.74 TFLOPS
Average TFLOPS (per second): 1.41
Overall FLOPs (per token): 0.50 GFLOPS

Final Metrics:
Memory Footprint: 3.64 GB
Inference Throughput: 3098 tokens/second
Total Training FLOPs: 171.25 TFLOPS
Training completed.

In [17]:
summarize_training_results(trainer, monitor)

====================================================================================================
TRAINING RESULTS SUMMARY TABLE
====================================================================================================
Epoch Training Loss Validation Loss Time (s) Tokens Processed Throughput (token/s) TFLOPS (per second) Avg CPU (%) Avg Memory (%) Training Steps
    0        2.3570          4.0729   114.50          342,016                 2986                1.50        20.3           11.7            167
    1        1.1012          6.4386   113.16          342,016                 3022                1.51        20.8           11.7            167
    2        0.7771          6.9578   113.15          342,016                 3022                1.51        20.8           11.9            167

----------------------------------------------------------------------------------------------------
TRAINING STATISTICS:
----------------------------------------------------------------------------------------------------
Total Training Time:      340.8 s
Average Epoch Time:       113.6 s
Total Tokens Processed:   1,026,048
Average Throughput:       3011 tokens/second
Average CPU Usage:        20.6%
Average Memory Usage:     11.8%
Total Training FLOPs:     513.74 TFLOPS
Average TFLOPS (per sec): 1.51
Overall FLOPs (per token): 0.50 GFLOPS

====================================================================================================

**Reference**
- [Arxiv:Efficient and Effective Methods for Mixed Precision Neural Network Quantization for Faster, Energy-efficient Inference](https://arxiv.org/html/2301.13330v2)
- [Huggingface:Trainner](https://huggingface.co/docs/transformers/v4.33.0/main_classes/trainer)

### Attention-Specific Precision

Attention-Specific Precision is a high-efficiency optimization strategy that surgically applies higher numerical precision to the most sensitive parts of the attention mechanism while compressing the rest. In the self-attention layer of an LLM, the calculations that determine where to look (Query and Key) are far more delicate than the actual information being looked at (Value).

**How it Works?**

The attention mechanism functions through three vectors: 
- Query ($Q$), Key ($K$), and Value ($V$).Query/Key (The "Search"): These are multiplied together and passed through a Softmax function to create an attention map. Because Softmax is highly sensitive to small numerical changes, any "noise" or rounding errors in $Q$ or $K$ (from low precision) can cause the model to attend to the wrong words, destroying logical coherence.
- Value (The "Payload"): Once the attention map is decided, the model retrieves the "Value" info. This step is numerically robust; even if $V$ is in low precision (4-bit), the weighted sum usually averages out errors, making it safe to compress.

**Implements Attention-Specific Precision**

The provided code achieves this specific balance through Targeted LoRA (Low-Rank Adaptation) on top of a 4-bit quantized base.

**1. Global Compression (The Base)**

The BitsAndBytesConfig first quantizes the entire model, including all $Q$, $K$, and $V$ projections, into 4-bit (NF4). This provides the massive memory savings needed to run the model on a single GPU.2. Selective High-Precision InjectionThe LoraConfig is configured to target only the query and key projections:

    lora_config = LoraConfig(
        target_modules=["q_proj", "k_proj"],  # Precision is upgraded here
        ...
    )
    
By selecting only q_proj and k_proj, the code attaches 16-bit (BF16/FP16) trainable adapters to those specific layers.
- Result: The $Q$ and $K$ layers become "Hybrid" (4-bit base + 16-bit adapter), which allows them to maintain high-precision attention scores.
- Result: The $V$ layers remain purely 4-bit, saving VRAM because no high-precision adapters are created for them.

**When to Use It?**

This targeted approach is an "expert-tier" optimization for specific resource-limited scenarios:
- Long-Context Fine-Tuning: Use this when training on long documents (e.g., 2000+ tokens). Attention memory grows quadratically; keeping Value projections in 4-bit significantly reduces the memory footprint of the attention matrix.
- Logic and Reasoning Tasks: Use this for coding, mathematics, or legal analysis. These tasks require "sharp" attention to maintain strict logic, so $Q$ and $K$ need the extra precision provided by the adapters.
- Extreme Memory Constraints: Use this when you have just enough memory to add some adapters, but not enough to target every layer in the model. Prioritizing $Q$ and $K$ gives you the most "intelligence per megabyte."
- Stabilizing Low-Bit Training: If your 4-bit model is generating nonsensical text during fine-tuning, upgrading $Q$ and $K$ via LoRA is often the fastest way to restore coherence.

In [ ]:
# Environment Setup
import torch
from datasets import Dataset, DatasetDict
from transformers import (
    AutoTokenizer, 
    AutoModelForCausalLM,
    DataCollatorForLanguageModeling,
    Trainer,
    TrainingArguments,
    TrainerCallback,
    BitsAndBytesConfig
)
from peft import LoraConfig, get_peft_model, TaskType

In [ ]:
# Configuration
MODEL_NAME = "google/gemma-3-270m"   
OUTPUT_DIR = "./gemma-3-270m-finetuned-qa-attention"

# Check GPU capabilities
cuda_available = torch.cuda.is_available()
bf16_supported = torch.cuda.is_bf16_supported() if cuda_available else False

print("Hardware Configuration:")
print(f"CUDA Available: {cuda_available}")
if cuda_available:
    print(f"GPU: {torch.cuda.get_device_name(0)}")

# Configure attention-specific precision with BitsAndBytes
from transformers import BitsAndBytesConfig
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training

# Determine compute precision
compute_dtype = torch.bfloat16 if bf16_supported else torch.float16 if cuda_available else torch.float32

# Configure BitsAndBytes with attention-specific precision
quantization_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=compute_dtype,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_storage=torch.uint8,
)

print(f"Loading {MODEL_NAME} with attention-specific precision...")
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    quantization_config=quantization_config,
    device_map="auto" if cuda_available else None,
    low_cpu_mem_usage=True,
)

# Prepare model for k-bit training
model = prepare_model_for_kbit_training(model)

# Configure LoRA with attention-specific targeting
# Query/Key projections get higher precision via LoRA adapters
# Value projections can use lower precision
lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    target_modules=["q_proj", "k_proj"],  # Focus on query/key for higher precision
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
)

# Apply LoRA for attention-specific precision control
model = get_peft_model(model, lora_config)

# Training setup
monitor = EpochMonitor(model=model)

data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

# Configure training with attention-specific precision
training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    gradient_accumulation_steps=2,
    learning_rate=2e-4,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_strategy="epoch",
    run_name="gemma-3-270m-qa-attention",
    warmup_steps=50,
    lr_scheduler_type="cosine",
    
    # Mixed precision configuration
    bf16=bf16_supported,
    fp16=cuda_available and not bf16_supported,
    
    # Attention-specific precision via LoRA targeting
    # Query/Key: Higher precision via LoRA adapters
    # Value: Lower precision via base quantization
    
    # Optimization settings
    max_grad_norm=0.3,
    optim="paged_adamw_8bit",
    
    # Performance settings
    dataloader_pin_memory=cuda_available,
    dataloader_num_workers=2 if cuda_available else 0,
    
    # Memory optimization
    gradient_checkpointing=True,
    gradient_checkpointing_kwargs={"use_reentrant": False},
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
    callbacks=[monitor],
)

# Print configuration
total_params = sum(p.numel() for p in model.parameters())
trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f"Total parameters: {total_params:,}")
print(f"Trainable parameters: {trainable_params:,}")
print(f"Trainable percentage: {100 * trainable_params / total_params:.2f}%")
print(f"Batch size: {training_args.per_device_train_batch_size}")
print(f"Compute dtype: {compute_dtype}")
print(f"Attention-specific precision:")
print(f"  Query/Key projections: Higher precision via LoRA adapters")
print(f"  Value projections: Lower precision via 4-bit quantization")
print(f"  Mixed precision: {'BF16' if bf16_supported else 'FP16' if cuda_available else 'FP32'}")

print("Starting training with attention-specific precision...")

train_result = trainer.train()

# Save model with attention-specific adapters
model.save_pretrained(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)

print("Training completed.")

Hardware Configuration:
CUDA Available: True
GPU: NVIDIA RTX A4000
Loading google/gemma-3-270m with attention-specific precision...

Loading weights:   0%|          | 0/236 [00:00<?, ?it/s]

Total parameters: 218,700,416
Trainable parameters: 737,280
Trainable percentage: 0.34%
Batch size: 4
Compute dtype: torch.bfloat16
Attention-specific precision:
  Query/Key projections: Higher precision via LoRA adapters
  Value projections: Lower precision via 4-bit quantization
  Mixed precision: BF16
Starting training with attention-specific precision...
Initial Model Memory Footprint:
  Parameters: 218,700,416
  Precision: 4 bytes
  Total Memory: 3.63 GB
    - Parameters: 0.81 GB
    - KV Cache (est): 2.81 GB
  Estimated FLOPs per forward pass (batch=8, seq=512): 2.05 TFLOPS

============================================================
Epoch 0 Summary
============================================================
  Duration (s)         :         81.52
  Tokens Processed     :       342,016
  Throughput (token/s) :          4196
  Training Steps       :           167
  Avg CPU (%)          :          19.6
  Avg Memory (%)       :          11.6
  Total FLOPs          : 171.25 TFLOPS
  TFLOPS (per second)  :          2.10
  FLOPs (per token)    :   0.50 GFLOPS

============================================================
Epoch 1 Summary
============================================================
  Duration (s)         :         81.20
  Tokens Processed     :       342,016
  Throughput (token/s) :          4212
  Training Steps       :           167
  Avg CPU (%)          :          18.8
  Avg Memory (%)       :          11.5
  Total FLOPs          : 171.25 TFLOPS
  TFLOPS (per second)  :          2.11
  FLOPs (per token)    :   0.50 GFLOPS

============================================================
Epoch 2 Summary
============================================================
  Duration (s)         :         82.17
  Tokens Processed     :       342,016
  Throughput (token/s) :          4162
  Training Steps       :           167
  Avg CPU (%)          :          21.8
  Avg Memory (%)       :          11.6
  Total FLOPs          : 171.25 TFLOPS
  TFLOPS (per second)  :          2.08
  FLOPs (per token)    :   0.50 GFLOPS

============================================================
TRAINING COMPLETE
============================================================
Total Training Time: 263.71s
Total Epochs: 3
Average Epoch Time: 81.63s
Total Tokens Processed: 1,026,048
Average Throughput: 3891 tokens/second
Total FLOPs: 513.74 TFLOPS
Average TFLOPS (per second): 1.95
Overall FLOPs (per token): 0.50 GFLOPS

Final Metrics:
Memory Footprint: 3.63 GB
Inference Throughput: 4286 tokens/second
Total Training FLOPs: 171.25 TFLOPS
Training completed.

In [19]:
summarize_training_results(trainer, monitor)

====================================================================================================
TRAINING RESULTS SUMMARY TABLE
====================================================================================================
Epoch Training Loss Validation Loss Time (s) Tokens Processed Throughput (token/s) TFLOPS (per second) Avg CPU (%) Avg Memory (%) Training Steps
    0        3.1374          3.4729    81.52          342,016                 4195                2.10        19.6           11.6            167
    1        2.7722          3.5558    81.20          342,016                 4212                2.11        18.8           11.5            167
    2        2.6310          3.5775    82.17          342,016                 4162                2.08        21.8           11.6            167

----------------------------------------------------------------------------------------------------
TRAINING STATISTICS:
----------------------------------------------------------------------------------------------------
Total Training Time:      244.9 s
Average Epoch Time:       81.6 s
Total Tokens Processed:   1,026,048
Average Throughput:       4190 tokens/second
Average CPU Usage:        20.1%
Average Memory Usage:     11.6%
Total Training FLOPs:     513.74 TFLOPS
Average TFLOPS (per sec): 2.10
Overall FLOPs (per token): 0.50 GFLOPS

====================================================================================================

**Reference**
- [Arxiv:LATTE: Low-Precision Approximate Attention with Head-wise Trainable Threshold for Efficient Transformer](https://arxiv.org/html/2404.07519v1)
- [NeurIPS:NoMAD-Attention: Efficient LLM Inference on CPUs Through Multiply-add-free Attention](https://neurips.cc/virtual/2024/poster/96623)
- [Arxiv:Why Low-Precision Transformer Training Fails: An Analysis on Flash Attention](https://arxiv.org/html/2510.04212v1)
- [Huggingface:Trainner](https://huggingface.co/docs/transformers/v4.33.0/main_classes/trainer)
- [Huggingface:LoRA](https://huggingface.co/docs/peft/en/package_reference/lora)
- [Huggingface:BitsAndBytesConfig](https://huggingface.co/docs/transformers/en/main_classes/quantization#transformers.BitsAndBytesConfig)

### Gradient Accumulation in FP32

Gradient Accumulation in FP32 is an optimization strategy that allows researchers to simulate large batch sizes on limited hardware by splitting a single training step into several smaller "micro-batches." While the individual forward and backward passes may happen in a lower precision (like BF16 or FP16) to save memory, the resulting gradients are summed together in FP32 (Single Precision). This ensures that the small adjustments to the model's weights remain accurate and do not get lost due to numerical rounding errors.

**How Gradient Accumulation Works**

When training an LLM, the "Effective Batch Size" determines how stable the learning process is. If the GPU memory is too small to hold a large batch, Gradient Accumulation solves this by:

- Iterative Processing: Processing a small "micro-batch" (e.g., 4 samples).
- Gradient Calculation: Performing the backward pass to find the gradients.
- The Accumulator: Instead of updating the model weights immediately, these gradients are added to a "buffer" stored in FP32.
- Repeat: Repeating this for several steps (e.g., 4 steps).
- The Step: Once the desired effective batch size is reached (4 steps x 4 samples = 16), the accumulated FP32 gradients are used to update the master weights, and the buffer is cleared.

**Implements Gradient Accumulation in FP32**

The provided code automates this logic through the Hugging Face Trainer and TrainingArguments.

**1. Defining the Effective Batch Size**

    per_device_train_batch_size=4,
    gradient_accumulation_steps=4,
    
These settings tell the system to process only 4 samples at a time on the GPU to keep memory usage low, but to wait for 4 iterations before performing a weight update. This creates an effective batch size of 16.

**2. Ensuring FP32 Precision**

The script uses a hybrid precision approach. While the model is loaded in 16-bit (`model_dtype`), the Trainer class is designed to handle the accumulation buffer in FP32 by default when mixed precision (`bf16 or fp16`) is enabled.

When `bf16=True` or `fp16=True` is used, the optimizer (`AdamW`) maintains its internal states and the gradient sum in 32-bit. This is critical because if you accumulated 16-bit gradients over many steps, the tiny values would eventually "underflow" or round incorrectly, leading to a model that fails to converge.

**When to Use It?**

Gradient Accumulation is one of the most essential tools for LLM fine-tuning and should be used in the following cases:
- VRAM Constraints: Use it whenever your desired batch size causes an "Out of Memory" (OOM) error. It allows you to use a batch size of 1 on the GPU while mathematically simulating a batch size of 32 or 64.
- Small Sample Training: LLMs often require larger batch sizes to "smooth out" the noise in the data. If your batch size is too small (e.g., 1 or 2), the model's loss curve will be extremely jagged and training may be unstable.
- Maintaining High Accuracy: Use the FP32 accumulation variant specifically when training with low-precision formats (FP16/BF16). It ensures that the "micro-updates" from each small batch are preserved accurately before the final weight update.
- Maximizing Hardware Utility: Use it to fill your GPU memory as much as possible with the largest possible `per_device_train_batch_size`, then use accumulation to reach the theoretical batch size recommended for that specific model architecture.

In [ ]:
# Environment Setup
import torch
from datasets import Dataset, DatasetDict
from transformers import (
    AutoTokenizer, 
    AutoModelForCausalLM,
    DataCollatorForLanguageModeling,
    Trainer,
    TrainingArguments,
    TrainerCallback,
)

In [ ]:
# Configuration
MODEL_NAME = "google/gemma-3-270m"   
OUTPUT_DIR = "./gemma-3-270m-finetuned-qa-accum"

# Check GPU capabilities
cuda_available = torch.cuda.is_available()
bf16_supported = torch.cuda.is_bf16_supported() if cuda_available else False

print("Hardware Configuration:")
print(f"CUDA Available: {cuda_available}")
if cuda_available:
    print(f"GPU: {torch.cuda.get_device_name(0)}")

# Load model with mixed precision
model_dtype = torch.bfloat16 if bf16_supported else torch.float16 if cuda_available else torch.float32
print(f"Loading {MODEL_NAME} in {model_dtype}...")
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    device_map="auto" if cuda_available else None,
    torch_dtype=model_dtype,
    low_cpu_mem_usage=True,
)

# Training setup
monitor = EpochMonitor(model=model)

data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

# Configure training with gradient accumulation in FP32
training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    gradient_accumulation_steps=4,
    learning_rate=2e-5,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_strategy="epoch",
    run_name="gemma-3-270m-qa-accum",
    warmup_steps=50,
    lr_scheduler_type="cosine",
    
    # Mixed precision configuration
    bf16=bf16_supported,
    fp16=cuda_available and not bf16_supported,
    
    # Gradient accumulation in FP32 is automatic with these settings
    
    # Optimization settings
    max_grad_norm=1.0,
    optim="adamw_torch",
    
    # Performance settings
    dataloader_pin_memory=cuda_available,
    dataloader_num_workers=2 if cuda_available else 0,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
    callbacks=[monitor],
)

# Print configuration
total_params = sum(p.numel() for p in model.parameters())
effective_batch_size = training_args.per_device_train_batch_size * training_args.gradient_accumulation_steps
print(f"Total parameters: {total_params:,}")
print(f"Per-device batch size: {training_args.per_device_train_batch_size}")
print(f"Gradient accumulation steps: {training_args.gradient_accumulation_steps}")
print(f"Effective batch size: {effective_batch_size}")
print(f"Mixed precision: {'BF16' if bf16_supported else 'FP16' if cuda_available else 'FP32'}")
print(f"Gradient accumulation: FP32 (automatic with Trainer)")

print("Starting training with FP32 gradient accumulation...")

train_result = trainer.train()

trainer.save_model()
tokenizer.save_pretrained(OUTPUT_DIR)

print("Training completed.")

Hardware Configuration:
CUDA Available: True
GPU: NVIDIA RTX A4000
Loading google/gemma-3-270m in torch.bfloat16...

Loading weights:   0%|          | 0/236 [00:00<?, ?it/s]

Total parameters: 268,098,176
Per-device batch size: 4
Gradient accumulation steps: 4
Effective batch size: 16
Mixed precision: BF16
Gradient accumulation: FP32 (automatic with Trainer)
Starting training with FP32 gradient accumulation...
Initial Model Memory Footprint:
  Parameters: 268,098,176
  Precision: 2 bytes
  Total Memory: 1.91 GB
    - Parameters: 0.50 GB
    - KV Cache (est): 1.41 GB
  Estimated FLOPs per forward pass (batch=8, seq=512): 2.05 TFLOPS

============================================================
Epoch 0 Summary
============================================================
  Duration (s)         :        34.59
  Tokens Processed     :      172,032
  Throughput (token/s) :         4973
  Training Steps       :           84
  Avg CPU (%)          :         19.6
  Avg Memory (%)       :         11.2
  Total FLOPs          : 86.14 TFLOPS
  TFLOPS (per second)  :         2.49
  FLOPs (per token)    :  0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================
Epoch 1 Summary
============================================================
  Duration (s)         :        35.10
  Tokens Processed     :      172,032
  Throughput (token/s) :         4901
  Training Steps       :           84
  Avg CPU (%)          :         21.4
  Avg Memory (%)       :         11.2
  Total FLOPs          : 86.14 TFLOPS
  TFLOPS (per second)  :         2.45
  FLOPs (per token)    :  0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================
Epoch 2 Summary
============================================================
  Duration (s)         :        35.58
  Tokens Processed     :      172,032
  Throughput (token/s) :         4835
  Training Steps       :           84
  Avg CPU (%)          :         20.3
  Avg Memory (%)       :         11.2
  Total FLOPs          : 86.14 TFLOPS
  TFLOPS (per second)  :         2.42
  FLOPs (per token)    :  0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['lm_head.weight'].

============================================================
TRAINING COMPLETE
============================================================
Total Training Time: 123.47s
Total Epochs: 3
Average Epoch Time: 35.09s
Total Tokens Processed: 516,096
Average Throughput: 4180 tokens/second
Total FLOPs: 258.41 TFLOPS
Average TFLOPS (per second): 2.09
Overall FLOPs (per token): 0.50 GFLOPS

Final Metrics:
Memory Footprint: 1.91 GB
Inference Throughput: 5323 tokens/second
Total Training FLOPs: 86.14 TFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Training completed.

In [21]:
summarize_training_results(trainer, monitor)

====================================================================================================
TRAINING RESULTS SUMMARY TABLE
====================================================================================================
Epoch Training Loss Validation Loss Time (s) Tokens Processed Throughput (token/s) TFLOPS (per second) Avg CPU (%) Avg Memory (%) Training Steps
    0        2.7632          3.0560    34.59          172,032                 4972                2.49        19.6           11.2             84
    1        1.9051          3.2713    35.10          172,032                 4900                2.45        21.4           11.2             84
    2        1.6936          3.3101    35.58          172,032                 4835                2.42        20.3           11.2             84

----------------------------------------------------------------------------------------------------
TRAINING STATISTICS:
----------------------------------------------------------------------------------------------------
Total Training Time:      105.3 s
Average Epoch Time:       35.1 s
Total Tokens Processed:   516,096
Average Throughput:       4902 tokens/second
Average CPU Usage:        20.4%
Average Memory Usage:     11.2%
Total Training FLOPs:     258.41 TFLOPS
Average TFLOPS (per sec): 2.45
Overall FLOPs (per token): 0.50 GFLOPS

====================================================================================================

**Reference**
- [Huggingface:Efficient Training on a Single GPU](https://huggingface.co/docs/transformers/v4.23.0/en/perf_train_gpu_one)
- [Arxiv:Memory Efficient Mixed Precision Optimizers](https://arxiv.org/html/2309.12381)
- [Arxiv:MIXED PRECISION TRAINING](https://arxiv.org/pdf/1710.03740)
- [Huggingface:Trainner](https://huggingface.co/docs/transformers/v4.33.0/main_classes/trainer)

### Selective High Precision

Selective High Precision is a numerical optimization strategy that identifies specific mathematical operations within a Large Language Model (LLM) that are highly sensitive to rounding errors and forces them to run in 32-bit floating point (FP32). Meanwhile, the computationally heavy matrix multiplications—which make up the vast majority of the model—are performed in lower precision (FP16 or BF16) to maximize speed and reduce memory usage.

**How Selective High Precision Works**

Deep learning operations vary in their "numerical range" requirements.
- The Matrix Multiplication (Low Precision): Standard linear layers (projections) are generally robust. Using 16-bit for these operations offers a massive performance boost with negligible impact on accuracy.
- The Critical Ops (High Precision): 
    - Softmax: This involves exponentiation ($e^x$). Small changes in the input can lead to massive changes in the output. In 16-bit, this often causes "overflow" (values becoming infinity).
    - Layer Normalization: This involves calculating means and variances. Summing many small squares can lead to "underflow" or precision loss if performed in a low-bit format.
    - Loss Functions: The final calculation of error must be exact to ensure the gradients used for learning are correct.

The system uses a "dispatch" logic: when it encounters a sensitive operator, it "upscasts" the input tensors to FP32, performs the calculation, and then "downcasts" the result back to 16-bit for the next layer.

**Implements Selective High Precision**

The script utilizes this strategy through the interaction between `torch_dtype` and the Trainer engine.

**1. Base Precision Selection**

    model_dtype = torch.bfloat16 if bf16_supported else torch.float16 if cuda_available else torch.float32
    
The model weights are loaded in 16-bit (BF16 or FP16). This saves half the VRAM immediately compared to full FP32.

**2. Automatic Autocasting**

    bf16=bf16_supported,
    fp16=cuda_available and not bf16_supported,
    
By passing these flags to `TrainingArguments`, the Hugging Face Trainer activates `torch.autocast`. Autocast is the engine behind Selective High Precision. It monitors every operation during the forward pass. If it sees a Linear layer, it uses the low-precision `model_dtype`. If it sees a `LayerNorm or Softmax`, it ignores the `model_dtype` and forces the math into FP32.

**When to Use It?**

Selective High Precision is the standard operational mode for fine-tuning modern LLMs like Gemma, Llama, or Mistral. It should be used:
- During Mixed Precision Training: It is essentially the "safety net" for AMP (Automatic Mixed Precision). You use it to get 16-bit speeds without the 16-bit instability.
- When Encountering NaNs: If your training loss suddenly becomes NaN (Not a Number), it is often because a sensitive operation was accidentally run in low precision. Selective High Precision prevents this by isolating those operations.
- Fine-Tuning Sensitive Models: Models that have been heavily quantized or have very deep architectures (like the 270M Gemma variant) are more prone to numerical drift. Selective precision keeps the "anchor points" of the model (norms and attention heads) stable.
- Maximizing Batch Size: Because it keeps the bulk of the activations in 16-bit, you can fit larger batches into VRAM than you could with pure FP32, while maintaining identical convergence properties.

In [ ]:
# Environment Setup
import torch
from datasets import Dataset, DatasetDict
from transformers import (
    AutoTokenizer, 
    AutoModelForCausalLM,
    DataCollatorForLanguageModeling,
    Trainer,
    TrainingArguments
)

In [ ]:
# Configuration
MODEL_NAME = "google/gemma-3-270m"   
OUTPUT_DIR = "./gemma-3-270m-finetuned-qa-selective"

# Check GPU capabilities
cuda_available = torch.cuda.is_available()
bf16_supported = torch.cuda.is_bf16_supported() if cuda_available else False

print("Hardware Configuration:")
print(f"CUDA Available: {cuda_available}")
if cuda_available:
    print(f"GPU: {torch.cuda.get_device_name(0)}")

# Load model with selective high precision
model_dtype = torch.bfloat16 if bf16_supported else torch.float16 if cuda_available else torch.float32
print(f"Loading {MODEL_NAME} in {model_dtype}...")
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    device_map="auto" if cuda_available else None,
    torch_dtype=model_dtype,
    low_cpu_mem_usage=True,
)

# Training setup
monitor = EpochMonitor(model=model)

data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

# Configure training with selective high precision
training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    gradient_accumulation_steps=1,
    learning_rate=2e-5,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_strategy="epoch",
    run_name="gemma-3-270m-qa-selective",
    warmup_steps=50,
    lr_scheduler_type="cosine",
    
    # Mixed precision with selective high precision
    bf16=bf16_supported,
    fp16=cuda_available and not bf16_supported,
    
    # Trainer automatically uses selective high precision for critical ops
    
    # Optimization settings
    max_grad_norm=1.0,
    optim="adamw_torch",
    
    # Performance settings
    dataloader_pin_memory=cuda_available,
    dataloader_num_workers=2 if cuda_available else 0,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
    callbacks=[monitor],
)

# Print configuration
total_params = sum(p.numel() for p in model.parameters())
print(f"Total parameters: {total_params:,}")
print(f"Batch size: {training_args.per_device_train_batch_size}")
print(f"Mixed precision: {'BF16' if bf16_supported else 'FP16' if cuda_available else 'FP32'}")

print("Starting training with selective high precision...")

train_result = trainer.train()

trainer.save_model()
tokenizer.save_pretrained(OUTPUT_DIR)

print("Training completed.")

Hardware Configuration:
CUDA Available: True
GPU: NVIDIA RTX A4000
Loading google/gemma-3-270m in torch.bfloat16...

Loading weights:   0%|          | 0/236 [00:00<?, ?it/s]

Total parameters: 268,098,176
Batch size: 8
Mixed precision: BF16
Starting training with selective high precision...
Initial Model Memory Footprint:
  Parameters: 268,098,176
  Precision: 2 bytes
  Total Memory: 1.91 GB
    - Parameters: 0.50 GB
    - KV Cache (est): 1.41 GB
  Estimated FLOPs per forward pass (batch=8, seq=512): 2.05 TFLOPS

============================================================
Epoch 0 Summary
============================================================
  Duration (s)         :         28.05
  Tokens Processed     :       684,032
  Throughput (token/s) :         24388
  Training Steps       :           167
  Avg CPU (%)          :          17.6
  Avg Memory (%)       :          11.1
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :         12.21
  FLOPs (per token)    :   0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================
Epoch 1 Summary
============================================================
  Duration (s)         :         28.38
  Tokens Processed     :       684,032
  Throughput (token/s) :         24105
  Training Steps       :           167
  Avg CPU (%)          :          20.5
  Avg Memory (%)       :          11.1
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :         12.07
  FLOPs (per token)    :   0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================
Epoch 2 Summary
============================================================
  Duration (s)         :         28.45
  Tokens Processed     :       684,032
  Throughput (token/s) :         24046
  Training Steps       :           167
  Avg CPU (%)          :          24.5
  Avg Memory (%)       :          11.1
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :         12.04
  FLOPs (per token)    :   0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['lm_head.weight'].

============================================================
TRAINING COMPLETE
============================================================
Total Training Time: 101.12s
Total Epochs: 3
Average Epoch Time: 28.29s
Total Tokens Processed: 2,052,096
Average Throughput: 20293 tokens/second
Total FLOPs: 1027.47 TFLOPS
Average TFLOPS (per second): 10.16
Overall FLOPs (per token): 0.50 GFLOPS

Final Metrics:
Memory Footprint: 1.91 GB
Inference Throughput: 29126 tokens/second
Total Training FLOPs: 342.49 TFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Training completed.

In [23]:
summarize_training_results(trainer, monitor)

====================================================================================================
TRAINING RESULTS SUMMARY TABLE
====================================================================================================
Epoch Training Loss Validation Loss Time (s) Tokens Processed Throughput (token/s) TFLOPS (per second) Avg CPU (%) Avg Memory (%) Training Steps
    0        2.5028          3.1477    28.05          684,032                24388               12.21        17.6           11.1            167
    1        1.6561          3.4891    28.38          684,032                24104               12.07        20.5           11.1            167
    2        1.4684          3.5477    28.45          684,032                24045               12.04        24.5           11.1            167

----------------------------------------------------------------------------------------------------
TRAINING STATISTICS:
----------------------------------------------------------------------------------------------------
Total Training Time:      84.9 s
Average Epoch Time:       28.3 s
Total Tokens Processed:   2,052,096
Average Throughput:       24179 tokens/second
Average CPU Usage:        20.9%
Average Memory Usage:     11.1%
Total Training FLOPs:     1027.47 TFLOPS
Average TFLOPS (per sec): 12.11
Overall FLOPs (per token): 0.50 GFLOPS

====================================================================================================

**Reference**
- [Selective High-Precision Control of Process Variables in Automated Experimentation](http://www-dsc.naist.jp/dsc_naist/wp-content/uploads/2025/09/P-13-Hiiro-Sugita-short-abstract.pdf)
- [Arxiv:Dynamic Selective Positioning for High-Precision Accuracy in 5G NR V2X Networks](https://arxiv.org/abs/2102.10426)
- [Huggingface:Trainner](https://huggingface.co/docs/transformers/v4.33.0/main_classes/trainer)

### FP8 Fine-Tuning

FP8 Fine-Tuning is a cutting-edge numerical optimization that uses 8-bit floating-point precision to compress model weights, activations, and even gradients during the training process. While standard mixed-precision training uses 16-bit (BF16 or FP16), FP8 cuts the data size in half again. On modern hardware like NVIDIA’s Hopper (H100) or Blackwell (B200) architectures, this results in a 2x reduction in VRAM and up to a 2x speedup in training throughput compared to BF16.

**How FP8 Fine-Tuning Works**

Unlike simple integer quantization (INT8), FP8 preserves a floating-point structure with a sign bit, an exponent, and a mantissa. To maintain accuracy despite the very narrow numerical range, it uses a Hybrid Strategy:
- E4M3 (4-bit exponent, 3-bit mantissa): Used for Forward Passes (Weights and Activations). It provides higher precision to capture the subtle nuances of the model's internal data.
- E5M2 (5-bit exponent, 2-bit mantissa): Used for Backward Passes (Gradients). The extra bit in the exponent allows for a wider "dynamic range," which is necessary to prevent gradients from disappearing (underflow) or exploding (overflow).
- Dynamic/Delayed Scaling: Because FP8's range is so small (max value $\approx 448$ for E4M3), the system tracks the maximum absolute values (amax) of tensors over time and applies a scaling factor to "shift" the data into the representable 8-bit window.

**Implements FP8 Fine-Tuning**

The provided script uses the Hugging Face Accelerator and Trainer to tap into specialized backends like NVIDIA's Transformer Engine (TE) or MS-AMP.

**1. The Accelerator Entry Point**

    accelerator = Accelerator(mixed_precision="fp8")
    
This line is the master switch. It tells the training environment to wrap all linear layers and matrix multiplications in an FP8 "autocast" context. Behind the scenes, Accelerator detects your hardware and prepares the scaling buffers for the amax history.

**2. Backend Handlers**

The commented-out sections in the code refer to `TERecipeKwargs (Transformer Engine) or MSAMPRecipeKwargs`. These define the "recipe" for how often the scaling factors are updated and which format (Hybrid or E4M3-only) is used.
- Transformer Engine (TE): Performs 8-bit matrix multiplications (GEMMs) natively on H100 Tensor Cores.
- MS-AMP: Can further optimize the optimizer states, storing the first-order momentum in 8-bit to save even more memory.

**3. Automatic Model Conversion**

When `trainer.train()` is called under an FP8-enabled Accelerator, the linear layers of Gemma-3-270m are converted into specialized FP8-aware modules. These modules perform the "cast-calculate-unscale" loop automatically, ensuring that the heavy math is 8-bit while the weight updates remain precise.

**When to Use It?**

FP8 is currently considered an "experimental" feature and should be used under specific conditions:
- Hopper/Blackwell Architecture: You must have an NVIDIA H100, B200, or newer. On older GPUs (like A100 or 3090/4090), the hardware does not support native FP8 math, and the code will likely fall back to slower 16-bit simulation.
- Massive Models or Data: Use it when you are training models with billions of parameters where VRAM is the primary bottleneck. It allows you to double your batch size on the same number of GPUs.
- Training Speed is Top Priority: If you are running large-scale pre-training or extensive fine-tuning and need to cut your cloud compute costs in half.
- Memory-Hungry Optimizers: Use it in conjunction with MS-AMP if you want to use the standard Adam optimizer but cannot afford the 4x-8x memory overhead of storing optimizer states in FP32.

**Reference**
- [Huggingface:Fine-grained FP8](https://huggingface.co/docs/transformers/en/quantization/finegrained_fp8)
- [Huggingface:FP8-LM: Training FP8 Large Language Models](https://huggingface.co/papers/2310.18313)
- [Huggingface:Trainner](https://huggingface.co/docs/transformers/v4.33.0/main_classes/trainer)
- [Huggingface:Low Precision Training Methods](https://huggingface.co/docs/accelerate/en/usage_guides/low_precision_training)

In [24]:
%%capture
!pip install transformer-engine
!pip install msamp

In [ ]:
# Environment Setup
import torch
from datasets import Dataset, DatasetDict
from transformers import (
    AutoTokenizer, 
    AutoModelForCausalLM,
    DataCollatorForLanguageModeling,
    Trainer,
    TrainingArguments,
    TrainerCallback,
)
from accelerate import Accelerator

In [ ]:
# Configuration
MODEL_NAME = "google/gemma-3-270m"
OUTPUT_DIR = "./gemma-3-270m-finetuned-qa"

# Accelerator with FP8
#accelerator = Accelerator(mixed_precision="fp8")   # enables FP8 where supported
#from accelerate.utils import MSAMPRecipeKwargs
#kwargs = [MSAMPRecipeKwargs()]
# Or to specify the backend as `TransformersEngine` even if MS-AMP is installed
# kwargs = [TERecipeKwargs()]
# Or to use torchao
# kwargs = [AORecipeKwargs()]
# accelerator = Accelerator(mixed_precision="fp8")

# Model
print(f"Loading model: {MODEL_NAME}")
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    device_map="auto",
    low_cpu_mem_usage=True,
)

total_params = sum(p.numel() for p in model.parameters())
print(f"Total parameters: {total_params:,}")

# Training setup
data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

monitor = EpochMonitor(model=model)

training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    gradient_accumulation_steps=1,
    learning_rate=2e-5,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_strategy="epoch",
    warmup_ratio=0.1,
    lr_scheduler_type="cosine",
    #fp8=True
    #fp8_autocast_backend="msamp"#"transformer_engine",  # or "msamp" if preferred
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
    callbacks=[monitor]
)

# Train 
print("Starting FP8 fine-tuning...")
trainer.train()

# Save
trainer.save_model()
tokenizer.save_pretrained(OUTPUT_DIR)

print("Fine-tuning completed.")

Loading model: google/gemma-3-270m

Loading weights:   0%|          | 0/236 [00:00<?, ?it/s]

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Total parameters: 268,098,176
Starting FP8 fine-tuning...
Initial Model Memory Footprint:
  Parameters: 268,098,176
  Precision: 2 bytes
  Total Memory: 1.91 GB
    - Parameters: 0.50 GB
    - KV Cache (est): 1.41 GB
  Estimated FLOPs per forward pass (batch=8, seq=512): 2.05 TFLOPS

============================================================
Epoch 0 Summary
============================================================
  Duration (s)         :         28.40
  Tokens Processed     :       684,032
  Throughput (token/s) :         24087
  Training Steps       :           167
  Avg CPU (%)          :          17.8
  Avg Memory (%)       :          11.0
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :         12.06
  FLOPs (per token)    :   0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================
Epoch 1 Summary
============================================================
  Duration (s)         :         28.55
  Tokens Processed     :       684,032
  Throughput (token/s) :         23956
  Training Steps       :           167
  Avg CPU (%)          :          22.0
  Avg Memory (%)       :          11.0
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :         11.99
  FLOPs (per token)    :   0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================
Epoch 2 Summary
============================================================
  Duration (s)         :         28.69
  Tokens Processed     :       684,032
  Throughput (token/s) :         23839
  Training Steps       :           167
  Avg CPU (%)          :          23.1
  Avg Memory (%)       :          11.1
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :         11.94
  FLOPs (per token)    :   0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['lm_head.weight'].

============================================================
TRAINING COMPLETE
============================================================
Total Training Time: 100.65s
Total Epochs: 3
Average Epoch Time: 28.55s
Total Tokens Processed: 2,052,096
Average Throughput: 20388 tokens/second
Total FLOPs: 1027.47 TFLOPS
Average TFLOPS (per second): 10.21
Overall FLOPs (per token): 0.50 GFLOPS

Final Metrics:
Memory Footprint: 1.91 GB
Inference Throughput: 31106 tokens/second
Total Training FLOPs: 342.49 TFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Fine-tuning completed.

In [26]:
summarize_training_results(trainer, monitor)

====================================================================================================
TRAINING RESULTS SUMMARY TABLE
====================================================================================================
Epoch Training Loss Validation Loss Time (s) Tokens Processed Throughput (token/s) TFLOPS (per second) Avg CPU (%) Avg Memory (%) Training Steps
    0        2.4992          3.1551    28.40          684,032                24087               12.06        17.8           11.0            167
    1        1.6229          3.5269    28.55          684,032                23956               11.99        22.0           11.0            167
    2        1.4209          3.6162    28.69          684,032                23839               11.94        23.1           11.1            167

----------------------------------------------------------------------------------------------------
TRAINING STATISTICS:
----------------------------------------------------------------------------------------------------
Total Training Time:      85.6 s
Average Epoch Time:       28.5 s
Total Tokens Processed:   2,052,096
Average Throughput:       23961 tokens/second
Average CPU Usage:        20.9%
Average Memory Usage:     11.0%
Total Training FLOPs:     1027.47 TFLOPS
Average TFLOPS (per sec): 12.00
Overall FLOPs (per token): 0.50 GFLOPS

====================================================================================================

### Adaptive Precision

Adaptive Precision is an advanced optimization strategy that dynamically switches between different numerical formats (e.g., FP32, BF16, FP16, or FP8) during the training of a Large Language Model (LLM). Unlike static mixed precision, which uses a fixed configuration, adaptive precision monitors the "health" of the training—specifically gradient variance—to decide when the model needs the safety of high precision or can benefit from the speed of low precision.

**How it Works**

Adaptive precision treats the training process as a non-stationary environment where different phases require different levels of care.
- Variance Monitoring: The system tracks the statistical variance of gradients over a sliding window of training steps.
- Stability Assessment: 
    - High Variance (Unstable): If gradients are fluctuating wildly, it indicates the model is in a "sharp" or unstable region of the loss landscape. The system may "upshift" to higher precision (e.g., FP32) to ensure weight updates don't cause a loss spike or catastrophic divergence.
    - Low Variance (Stable): If gradients are consistent, the model is in a "flat" or stable region. The system "downshifts" to lower precision (e.g., FP8 or 4-bit) to save VRAM and accelerate throughput.
- Automatic Scaling: It often works alongside dynamic loss scaling, adjusting the representable range of numbers to prevent underflow or overflow before they happen.

**Implements Adaptive Precision**

The provided code uses a Custom Trainer to implement a "Monitor-and-Log" version of adaptive precision logic.

**1. The Gradient History Buffer**

    class AdaptivePrecisionTrainer(Trainer):
        def __init__(self, *args, **kwargs):
            super().__init__(*args, **kwargs)
            self.gradient_history = []
        
The trainer creates a internal memory (`gradient_history`) to store the norm of gradients from the most recent 100 steps.

**2. Real-Time Statistical Analysis**

    # Calculate variance of the last 20 steps
    recent_grads = self.gradient_history[-20:]
    grad_variance = torch.var(torch.tensor(recent_grads)).item()
    
Inside the `training_step`, the code intercepts the process after the backward pass. It calculates the variance of the gradients. If `grad_variance` exceeds a threshold (e.g., 1e-4), it flags the training as "unstable."

**3. Precision Decision Logic**

While the provided code primarily logs the status, a full implementation would use the status ("stable" vs "unstable") to trigger an internal cast:
- If unstable, the trainer would tell the autocast engine to stay in FP32.
- If stable, it would enable BF16 or FP8 for the next batch.

**When to Use It**

Adaptive precision is most valuable when training budgets are tight and model stability is unpredictable:
- Preventing Loss Spikes: Use it during pre-training or large-scale fine-tuning to avoid "catastrophic forgetting" or the need to restart training from a checkpoint because of a sudden gradient explosion.
- Hyperparameter Exploration: Use it when trying aggressive learning rates. The adaptive mechanism can act as a "braking system," switching to higher precision to navigate difficult optimization zones that would otherwise crash a static 16-bit run.
- Heterogeneous Training Data: If your dataset contains a mix of high-quality and noisy data, the model may experience varying stability. Adaptive precision adjusts to the difficulty of the current data batch.
- Maximizing Throughput: Use it in the later stages of training. As models converge, gradients typically become more stable, allowing you to run almost the entire tail-end of training in low precision for maximum speed.

In [ ]:
# Environment Setup
import torch
from datasets import Dataset, DatasetDict
from transformers import (
    AutoTokenizer, 
    AutoModelForCausalLM,
    DataCollatorForLanguageModeling,
    Trainer,
    TrainingArguments,
    TrainerCallback,
)

In [ ]:
# Configuration
MODEL_NAME = "google/gemma-3-270m"   
OUTPUT_DIR = "./gemma-3-270m-finetuned-qa-adaptive"

# Check GPU capabilities
cuda_available = torch.cuda.is_available()
bf16_supported = torch.cuda.is_bf16_supported() if cuda_available else False

print("Hardware Configuration:")
print(f"CUDA Available: {cuda_available}")
if cuda_available:
    print(f"GPU: {torch.cuda.get_device_name(0)}")

# Load model with adaptive precision foundation
model_dtype = torch.bfloat16 if bf16_supported else torch.float16 if cuda_available else torch.float32
print(f"Loading {MODEL_NAME} in {model_dtype}...")
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    device_map="auto" if cuda_available else None,
    torch_dtype=model_dtype,
    low_cpu_mem_usage=True,
)

# Training setup
monitor = EpochMonitor(model=model)

data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

# Configure adaptive precision training
training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    gradient_accumulation_steps=2,
    learning_rate=2e-5,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_strategy="epoch",
    run_name="gemma-3-270m-qa-adaptive",
    warmup_steps=50,
    lr_scheduler_type="cosine",
    
    # Adaptive precision foundation
    bf16=bf16_supported,
    fp16=cuda_available and not bf16_supported,
    
    # Settings that support adaptive behavior
    max_grad_norm=1.0,
    optim="adamw_torch",
    
    # Performance settings
    dataloader_pin_memory=cuda_available,
    dataloader_num_workers=2 if cuda_available else 0,
)

# Custom trainer for adaptive precision
class AdaptivePrecisionTrainer(Trainer):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.gradient_history = []
        self.precision_mode = "mixed"
        
    def training_step(self, model, inputs, num_items_in_batch):
        # Call parent training_step
        loss = super().training_step(model, inputs, num_items_in_batch)
        
        # Analyze gradient statistics after backward pass
        if hasattr(model, 'module'):
            model_for_grads = model.module
        else:
            model_for_grads = model
        
        # Collect gradient statistics
        grad_stats = []
        for param in model_for_grads.parameters():
            if param.grad is not None:
                grad_norm = param.grad.norm().item()
                grad_stats.append(grad_norm)
        
        if grad_stats:
            avg_grad = sum(grad_stats) / len(grad_stats)
            self.gradient_history.append(avg_grad)
            
            # Keep only recent history
            if len(self.gradient_history) > 100:
                self.gradient_history.pop(0)
            
            # Adaptive logic based on gradient variance
            if len(self.gradient_history) >= 20:
                recent_grads = self.gradient_history[-20:]
                grad_variance = torch.var(torch.tensor(recent_grads)).item()
                
                # Log precision decisions
                if self.state.global_step % 100 == 0:
                    status = "stable" if grad_variance < 1e-4 else "unstable"
                    print(f"Step {self.state.global_step}: Grad variance {grad_variance:.2e} ({status})")
        
        return loss

trainer = AdaptivePrecisionTrainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
    callbacks=[monitor],
)

# Print configuration
total_params = sum(p.numel() for p in model.parameters())
print(f"Total parameters: {total_params:,}")
print(f"Batch size: {training_args.per_device_train_batch_size}")
print(f"Base precision: {model_dtype}")
print(f"Adaptive precision monitoring: Enabled")
print(f"Gradient accumulation steps: {training_args.gradient_accumulation_steps}")

print("Starting training with adaptive precision monitoring...")

train_result = trainer.train()

trainer.save_model()
tokenizer.save_pretrained(OUTPUT_DIR)

print("Training completed.")

Hardware Configuration:
CUDA Available: True
GPU: NVIDIA RTX A4000
Loading google/gemma-3-270m in torch.bfloat16...

Loading weights:   0%|          | 0/236 [00:00<?, ?it/s]

Total parameters: 268,098,176
Batch size: 8
Base precision: torch.bfloat16
Adaptive precision monitoring: Enabled
Gradient accumulation steps: 2
Starting training with adaptive precision monitoring...
Initial Model Memory Footprint:
  Parameters: 268,098,176
  Precision: 2 bytes
  Total Memory: 1.91 GB
    - Parameters: 0.50 GB
    - KV Cache (est): 1.41 GB
  Estimated FLOPs per forward pass (batch=8, seq=512): 2.05 TFLOPS

============================================================
Epoch 0 Summary
============================================================
  Duration (s)         :         26.95
  Tokens Processed     :       344,064
  Throughput (token/s) :         12766
  Training Steps       :            84
  Avg CPU (%)          :          19.1
  Avg Memory (%)       :          11.2
  Total FLOPs          : 172.27 TFLOPS
  TFLOPS (per second)  :          6.39
  FLOPs (per token)    :   0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Step 100: Grad variance 2.82e-03 (unstable)
Step 100: Grad variance 3.42e-03 (unstable)

============================================================
Epoch 1 Summary
============================================================
  Duration (s)         :         26.97
  Tokens Processed     :       344,064
  Throughput (token/s) :         12758
  Training Steps       :            84
  Avg CPU (%)          :          25.6
  Avg Memory (%)       :          11.7
  Total FLOPs          : 172.27 TFLOPS
  TFLOPS (per second)  :          6.39
  FLOPs (per token)    :   0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Step 200: Grad variance 3.72e-03 (unstable)
Step 200: Grad variance 4.38e-03 (unstable)

============================================================
Epoch 2 Summary
============================================================
  Duration (s)         :         26.93
  Tokens Processed     :       344,064
  Throughput (token/s) :         12775
  Training Steps       :            84
  Avg CPU (%)          :          21.0
  Avg Memory (%)       :          11.2
  Total FLOPs          : 172.27 TFLOPS
  TFLOPS (per second)  :          6.40
  FLOPs (per token)    :   0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['lm_head.weight'].

============================================================
TRAINING COMPLETE
============================================================
Total Training Time: 96.96s
Total Epochs: 3
Average Epoch Time: 26.95s
Total Tokens Processed: 1,032,192
Average Throughput: 10646 tokens/second
Total FLOPs: 516.81 TFLOPS
Average TFLOPS (per second): 5.33
Overall FLOPs (per token): 0.50 GFLOPS

Final Metrics:
Memory Footprint: 1.91 GB
Inference Throughput: 14353 tokens/second
Total Training FLOPs: 172.27 TFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Training completed.

In [28]:
summarize_training_results(trainer, monitor)

====================================================================================================
TRAINING RESULTS SUMMARY TABLE
====================================================================================================
Epoch Training Loss Validation Loss Time (s) Tokens Processed Throughput (token/s) TFLOPS (per second) Avg CPU (%) Avg Memory (%) Training Steps
    0        2.7628          3.0530    26.95          344,064                12765                6.39        19.1           11.2             84
    1        1.9044          3.2549    26.97          344,064                12758                6.39        25.6           11.7             84
    2        1.6925          3.3072    26.93          344,064                12774                6.40        21.0           11.2             84

----------------------------------------------------------------------------------------------------
TRAINING STATISTICS:
----------------------------------------------------------------------------------------------------
Total Training Time:      80.9 s
Average Epoch Time:       27.0 s
Total Tokens Processed:   1,032,192
Average Throughput:       12766 tokens/second
Average CPU Usage:        21.9%
Average Memory Usage:     11.3%
Total Training FLOPs:     516.81 TFLOPS
Average TFLOPS (per sec): 6.39
Overall FLOPs (per token): 0.50 GFLOPS

====================================================================================================

**Reference**
- [Arxiv:Model-Based Adaptive Precision Control for Tabletop Planar Pushing Under Uncertain Dynamics](https://arxiv.org/abs/2510.03768)
- [Arxiv:ADiP: Adaptive Precision Systolic Array for Matrix Multiplication Acceleration](https://arxiv.org/html/2510.10623v2)
- [Huggingface:Trainner](https://huggingface.co/docs/transformers/v4.33.0/main_classes/trainer)

### Layer-wise Precision Adaptation

Layer-wise Precision Adaptation is a strategic optimization that moves away from "one-size-fits-all" precision (like pure 16-bit) by assigning specific numerical bit-widths to different model components based on their individual sensitivity. In large transformer models, certain layers (like embeddings or output heads) are mathematically "brittle" and require high precision, while others (like the middle feed-forward blocks) are "robust" and can be compressed significantly without losing intelligence.

**How it Works**

The core of this method is Sensitivity Analysis. Before or during training, the model's layers are ranked by how much their precision affects the final output error:
- Critical Layers (High Precision): Components that handle initial data input (Embeddings) or final probability distribution (LM Head) are kept in FP32 or BF16. This preserves the foundational features and the nuances of the output.
- Structural Layers (High Precision): LayerNorm and the Softmax operations in Attention are kept in high precision to prevent numerical drift (overflow/underflow) which can crash training.
- Redundant Layers (Low Precision): Many of the middle layers in an LLM provide incremental refinement. These can often be "down-cast" to lower formats like INT8, FP8, or even 4-bit (via quantization) because the model's residual connections help recover any small errors introduced by the lower precision.

**Implements Layer-wise Precision Adaptation**

The provided code sets the groundwork for this adaptation by establishing a Sensitivity Mapping and a Custom Monitoring Trainer.

**1. The Sensitivity Map**

    layer_sensitivity = {
        "embed_tokens": 10,  # Critical: Max Precision
        "lm_head": 10,       # Critical: Max Precision
        "mlp": 7,            # Robust: Lower Precision
        ...
    }
    
The script explicitly defines which parts of the Gemma-3-270m model are sensitive. It uses a 1–10 scale to decide the "Budget" for each layer. In a full implementation, these scores would be used to programmatically cast model.embed_tokens to torch.float32 while leaving model.mlp in torch.bfloat16.

**2. Hardware-Aware Base**

    model_dtype = torch.bfloat16 if bf16_supported else torch.float16
    
The code identifies the best available global precision (BF16 for stability or FP16 for speed) as the "floor," ensuring that no layer accidentally falls back to a precision that the specific GPU hardware cannot handle efficiently.

**3. Custom Monitoring Trainer**

    class LayeredPrecisionTrainer(Trainer):
        def _log_layer_precision_stats(self):
            # Monitoring logic here
            
The `LayeredPrecisionTrainer` intercepts the training loop to monitor how these layers behave. By overriding `compute_loss`, it allows the developer to track if specific sensitive layers are causing "gradient spikes," which would signal that their precision needs to be "up-shifted" in real-time.

**When to Use It**

Layer-wise Precision Adaptation is an advanced technique used when standard mixed precision isn't enough:
- Post-Training Quantization (PTQ): Use this when you want to squeeze a model into a very small device (like a phone). You can keep the first and last layers in 8-bit while the middle layers are pushed to 4-bit to maintain accuracy.
- Training Large Models on Consumer Hardware: If you have limited VRAM (e.g., 24GB), you can use this to keep only the most important 20% of the model in high precision, allowing you to fit a much larger model than standard 16-bit training would permit.
- Stability in Low-Bit Training: If you are experimenting with ultra-low precision (FP8 or 4-bit training) and the model is failing to converge, use layer-wise adaptation to "rescue" the model by reverting the Attention layers back to 16-bit.
- Domain-Specific Fine-Tuning: In tasks like Medical or Legal analysis, where every word matters, keeping the Embedding and Output layers in FP32 ensures the model doesn't lose the ability to distinguish between highly similar technical terms.

In [ ]:
# Environment Setup
import torch
from datasets import Dataset, DatasetDict
from transformers import (
    AutoTokenizer, 
    AutoModelForCausalLM,
    DataCollatorForLanguageModeling,
    Trainer,
    TrainingArguments,
    TrainerCallback,
)

In [ ]:
# Configuration
MODEL_NAME = "google/gemma-3-270m"   
OUTPUT_DIR = "./gemma-3-270m-finetuned-qa-layered"

# Check GPU capabilities
cuda_available = torch.cuda.is_available()
bf16_supported = torch.cuda.is_bf16_supported() if cuda_available else False

print("Hardware Configuration:")
print(f"CUDA Available: {cuda_available}")
if cuda_available:
    print(f"GPU: {torch.cuda.get_device_name(0)}")

# Load model with base precision
model_dtype = torch.bfloat16 if bf16_supported else torch.float16 if cuda_available else torch.float32
print(f"Loading {MODEL_NAME} in {model_dtype}...")
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    device_map="auto" if cuda_available else None,
    torch_dtype=model_dtype,
    low_cpu_mem_usage=True,
)

# Analyze model components for sensitivity
print("Analyzing model components for precision adaptation...")

# Define layer sensitivity mapping
layer_sensitivity = {
    "embed_tokens": 10,
    "lm_head": 10,
    "norm": 9,
    "attention": 8,
    "mlp": 7,
    "q_proj": 8,
    "k_proj": 8,
    "v_proj": 7,
    "o_proj": 7,
    "gate_proj": 6,
    "up_proj": 6,
    "down_proj": 6,
}

# Print layer sensitivity analysis
print("Layer sensitivity analysis:")
for layer_type, sensitivity in sorted(layer_sensitivity.items()):
    precision = "Higher" if sensitivity >= 8 else "Mixed" if sensitivity >= 6 else "Lower"
    print(f"  {layer_type:12s}: {sensitivity}/10 -> {precision} precision")

# Training setup
monitor = EpochMonitor(model=model)

data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

# Configure training
training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    gradient_accumulation_steps=1,
    learning_rate=2e-5,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_strategy="epoch",
    run_name="gemma-3-270m-qa-layered",
    warmup_steps=50,
    lr_scheduler_type="cosine",
    
    # Mixed precision
    bf16=bf16_supported,
    fp16=cuda_available and not bf16_supported,
    
    # Optimization settings
    max_grad_norm=1.0,
    optim="adamw_torch",
    
    # Performance settings
    dataloader_pin_memory=cuda_available,
    dataloader_num_workers=2 if cuda_available else 0,
)

# Custom trainer for layer-wise precision awareness
class LayeredPrecisionTrainer(Trainer):
    def compute_loss(self, model, inputs, return_outputs=False, num_items_in_batch=None):
        # Forward pass with layer sensitivity awareness
        outputs = model(**inputs)
        
        # Log precision usage by layer type
        if self.state.global_step % 100 == 0:
            self._log_layer_precision_stats()
        
        # Calculate loss
        labels = inputs.get("labels")
        logits = outputs.logits
        shift_logits = logits[..., :-1, :].contiguous()
        shift_labels = labels[..., 1:].contiguous()
        
        loss_fct = torch.nn.CrossEntropyLoss()
        loss = loss_fct(
            shift_logits.view(-1, shift_logits.size(-1)),
            shift_labels.view(-1)
        )
        
        return (loss, outputs) if return_outputs else loss
    
    def _log_layer_precision_stats(self):
        # Log precision statistics for monitoring
        print(f"Step {self.state.global_step}: Layer-wise precision monitoring")

trainer = LayeredPrecisionTrainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
    callbacks=[monitor],
)

# Print configuration
total_params = sum(p.numel() for p in model.parameters())
print(f"Total parameters: {total_params:,}")
print(f"Batch size: {training_args.per_device_train_batch_size}")
print(f"Base model precision: {model_dtype}")
print(f"Layer-wise precision strategy: Monitoring")
print(f"Mixed precision: {'BF16' if bf16_supported else 'FP16' if cuda_available else 'FP32'}")

print("Starting training with layer-wise precision monitoring...")

train_result = trainer.train()

trainer.save_model()
tokenizer.save_pretrained(OUTPUT_DIR)

print("Training completed.")

`torch_dtype` is deprecated! Use `dtype` instead!

Hardware Configuration:
CUDA Available: True
GPU: NVIDIA RTX A4000
Loading google/gemma-3-270m in torch.bfloat16...

Loading weights:   0%|          | 0/236 [00:00<?, ?it/s]

Analyzing model components for precision adaptation...
Layer sensitivity analysis:
  attention   : 8/10 -> Higher precision
  down_proj   : 6/10 -> Mixed precision
  embed_tokens: 10/10 -> Higher precision
  gate_proj   : 6/10 -> Mixed precision
  k_proj      : 8/10 -> Higher precision
  lm_head     : 10/10 -> Higher precision
  mlp         : 7/10 -> Mixed precision
  norm        : 9/10 -> Higher precision
  o_proj      : 7/10 -> Mixed precision
  q_proj      : 8/10 -> Higher precision
  up_proj     : 6/10 -> Mixed precision
  v_proj      : 7/10 -> Mixed precision
Total parameters: 268,098,176
Batch size: 8
Base model precision: torch.bfloat16
Layer-wise precision strategy: Monitoring
Mixed precision: BF16
Starting training with layer-wise precision monitoring...
Initial Model Memory Footprint:
  Parameters: 268,098,176
  Precision: 2 bytes
  Total Memory: 1.91 GB
    - Parameters: 0.50 GB
    - KV Cache (est): 1.41 GB
  Estimated FLOPs per forward pass (batch=8, seq=512): 2.05 TFLOPS
Step 0: Layer-wise precision monitoring

Step 100: Layer-wise precision monitoring

============================================================
Epoch 0 Summary
============================================================
  Duration (s)         :         31.67
  Tokens Processed     :       684,032
  Throughput (token/s) :         21601
  Training Steps       :           167
  Avg CPU (%)          :          18.6
  Avg Memory (%)       :          10.1
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :         10.82
  FLOPs (per token)    :   0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Step 200: Layer-wise precision monitoring
Step 300: Layer-wise precision monitoring

============================================================
Epoch 1 Summary
============================================================
  Duration (s)         :         31.74
  Tokens Processed     :       684,032
  Throughput (token/s) :         21551
  Training Steps       :           167
  Avg CPU (%)          :          19.1
  Avg Memory (%)       :          10.2
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :         10.79
  FLOPs (per token)    :   0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Step 400: Layer-wise precision monitoring
Step 500: Layer-wise precision monitoring

============================================================
Epoch 2 Summary
============================================================
  Duration (s)         :         31.78
  Tokens Processed     :       684,032
  Throughput (token/s) :         21527
  Training Steps       :           167
  Avg CPU (%)          :          26.0
  Avg Memory (%)       :          10.2
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :         10.78
  FLOPs (per token)    :   0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['lm_head.weight'].

============================================================
TRAINING COMPLETE
============================================================
Total Training Time: 113.19s
Total Epochs: 3
Average Epoch Time: 31.73s
Total Tokens Processed: 2,052,096
Average Throughput: 18130 tokens/second
Total FLOPs: 1027.47 TFLOPS
Average TFLOPS (per second): 9.08
Overall FLOPs (per token): 0.50 GFLOPS

Final Metrics:
Memory Footprint: 1.91 GB
Inference Throughput: 25570 tokens/second
Total Training FLOPs: 342.49 TFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Training completed.

In [9]:
summarize_training_results(trainer, monitor)

====================================================================================================
TRAINING RESULTS SUMMARY TABLE
====================================================================================================
Epoch Training Loss Validation Loss Time (s) Tokens Processed Throughput (token/s) TFLOPS (per second) Avg CPU (%) Avg Memory (%) Training Steps
    0        2.5203          3.1717    31.67          684,032                21600               10.82        18.6           10.1            167
    1        1.6677          3.5085    31.74          684,032                21551               10.79        19.1           10.2            167
    2        1.4786          3.5685    31.78          684,032                21527               10.78        26.0           10.2            167

----------------------------------------------------------------------------------------------------
TRAINING STATISTICS:
----------------------------------------------------------------------------------------------------
Total Training Time:      95.2 s
Average Epoch Time:       31.7 s
Total Tokens Processed:   2,052,096
Average Throughput:       21560 tokens/second
Average CPU Usage:        21.2%
Average Memory Usage:     10.2%
Total Training FLOPs:     1027.47 TFLOPS
Average TFLOPS (per sec): 10.79
Overall FLOPs (per token): 0.50 GFLOPS

====================================================================================================

**Reference**
- [Arxiv:DP-LLM: Runtime Model Adaptation with Dynamic Layer-wise Precision Assignment](https://arxiv.org/abs/2508.06041)
- [Huggingface:Trainner](https://huggingface.co/docs/transformers/v4.33.0/main_classes/trainer)

## Memory-Optimized Precision

### Optimizer State Quantization

Optimizer State Quantization is a memory-saving technique that converts the high-precision numbers an optimizer uses (like the moving averages of gradients) from 32-bit floats down to 8-bit integers.

In Large Language Models (LLMs), the optimizer typically consumes more memory than the model weights themselves. For example, the standard AdamW optimizer stores two "states" (momentum and variance) for every single parameter. At 32-bit precision, this requires 12 bytes of VRAM per parameter—three times the memory needed to store a 16-bit model. Quantizing these states to 8-bit reduces that overhead to just 2 or 3 bytes per parameter, effectively cutting the optimizer's memory footprint by 75%.

**How it Works**

Standard 8-bit quantization can be unstable for optimizers because gradients vary wildly in scale. To solve this, 8-bit optimizers (primarily from the bitsandbytes library) use three core mechanisms:
- Block-wise Quantization: Instead of quantizing the entire layer at once, the optimizer divides parameters into small blocks (e.g., 2048 elements). Each block is quantized independently with its own scaling factor, which isolates "outlier" gradients and prevents them from ruining the precision of other values.
- Dynamic Quantization: The system dynamically rescales the range of the 8-bit values based on the current magnitude of the gradients, ensuring that both very small and very large updates are captured accurately.
- Element-wise Dequantization: During the actual weight update, the 8-bit states are temporarily "upscaled" to 32-bit inside the GPU registers to perform the math, then immediately converted back to 8-bit for storage. This ensures the update is as precise as a standard optimizer.

**Implements Optimizer State Quantization**

The provided code activates this feature simply by changing the optim flag in the `TrainingArguments`.

**1. Selecting the 8-bit Backend**

    training_args = TrainingArguments(
        ...
        optim="adamw_8bit",  # This triggers bitsandbytes 8-bit AdamW
        ...
    )

When you set `optim="adamw_8bit"`, the Hugging Face Trainer automatically replaces the standard PyTorch AdamW with the bitsandbytes version. It handles all the complex block-wise quantization and scaling logic behind the scenes.

**2. Paged Variants (Optional)**

The code comments also mention `paged_adamw_8bit`. This is a "safety" version that uses NVIDIA's Unified Memory. If the optimizer states still exceed your GPU's VRAM, it will "page" them out to your system's RAM instead of crashing with an Out-of-Memory (OOM) error.

**3. Automatic Stability Safeguards**

By default, the `adamw_8bit` implementation in this code includes a "minimum size" safeguard. It keeps very small layers (like biases or LayerNorm parameters) in full 32-bit precision because they are so small that quantizing them saves no noticeable memory but could harm the model's stability.

**When to Use It?**

Optimizer State Quantization is one of the most effective "free" wins in LLM training and should be used in almost every scenario:
- Limited VRAM: If you are trying to fine-tune a model on a consumer GPU (like an RTX 3090 or 4090) and keep hitting OOM errors, this is usually the first setting to change.
- Maximizing Batch Size: Even if your model fits in memory, using an 8-bit optimizer frees up several gigabytes of VRAM that you can use to increase your `per_device_train_batch_size`, which speeds up training and makes the model more stable.
- Full Parameter Fine-Tuning: While LoRA reduces memory by training fewer weights, if you must do full-parameter fine-tuning (FFT), an 8-bit optimizer is mandatory to avoid needing massive GPU clusters.
- Low-Rank Adaptation (LoRA): Even with LoRA, you are still storing optimizer states for the adapters. Using `adamw_8bit` allows you to use a much higher LoRA rank (`r=128 or r=256`) without significantly increasing memory usage.

In [ ]:
# Environment Setup
import torch
from datasets import Dataset, DatasetDict
from transformers import (
    AutoTokenizer, 
    AutoModelForCausalLM,
    DataCollatorForLanguageModeling,
    Trainer,
    TrainingArguments,
    TrainerCallback,
)

In [ ]:
# Configuration
MODEL_NAME = "google/gemma-3-270m"   
OUTPUT_DIR = "./gemma-3-270m-finetuned-qa-8bit"

# Check GPU capabilities
cuda_available = torch.cuda.is_available()
print(f"CUDA Available: {cuda_available}")

# Load model with appropriate precision
bf16_supported = torch.cuda.is_bf16_supported() if cuda_available else False
model_dtype = torch.bfloat16 if bf16_supported else torch.float16 if cuda_available else torch.float32
print(f"Loading {MODEL_NAME} in {model_dtype}...")
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    device_map="auto" if cuda_available else None,
    torch_dtype=model_dtype,
    low_cpu_mem_usage=True,
)

# Training setup
monitor = EpochMonitor(model=model)

data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

# Configure training with 8-bit optimizer
training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    gradient_accumulation_steps=1,
    learning_rate=2e-5,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_strategy="epoch",
    run_name="gemma-3-270m-qa-8bit",
    warmup_steps=50,
    lr_scheduler_type="cosine",
    
    # Mixed precision configuration
    bf16=bf16_supported,
    fp16=cuda_available and not bf16_supported,
    
    # 8-bit optimizer configuration
    optim="adamw_8bit",  # 8-bit AdamW for reduced memory
    
    # Alternative 8-bit optimizers:
    # optim="lion_8bit",    # 8-bit Lion optimizer
    # optim="paged_adamw_8bit",  # Paged 8-bit AdamW
    
    # Optimization settings
    max_grad_norm=1.0,
    
    # Performance settings
    dataloader_pin_memory=cuda_available,
    dataloader_num_workers=2 if cuda_available else 0,
    
    # Memory optimization settings
    gradient_checkpointing=False,  # Can enable if memory is tight
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
    callbacks=[monitor],
)

# Print configuration
total_params = sum(p.numel() for p in model.parameters())
print(f"Total parameters: {total_params:,}")
print(f"Batch size: {training_args.per_device_train_batch_size}")
print(f"Model precision: {model_dtype}")
print(f"Optimizer: {training_args.optim}")
print(f"Mixed precision: {'BF16' if bf16_supported else 'FP16' if cuda_available else 'FP32'}")

# Calculate memory savings
optimizer_state_bytes = total_params * 12  # Standard optimizer: 2x momentum + 1x variance
optimizer_8bit_bytes = total_params * 3    # 8-bit optimizer: 3x parameters in 8-bit
memory_saving = 100 * (1 - optimizer_8bit_bytes / optimizer_state_bytes)
print(f"Optimizer memory reduction: ~{memory_saving:.0f}%")
print(f"Standard optimizer: {optimizer_state_bytes/1e9:.1f} GB")
print(f"8-bit optimizer: {optimizer_8bit_bytes/1e9:.1f} GB")

print("Starting training with 8-bit optimizer...")

train_result = trainer.train()

print("Training completed.")

CUDA Available: True
Loading google/gemma-3-270m in torch.bfloat16...

Loading weights:   0%|          | 0/236 [00:00<?, ?it/s]

Total parameters: 268,098,176
Batch size: 8
Model precision: torch.bfloat16
Optimizer: OptimizerNames.ADAMW_8BIT
Mixed precision: BF16
Optimizer memory reduction: ~75%
Standard optimizer: 3.2 GB
8-bit optimizer: 0.8 GB
Starting training with 8-bit optimizer...
Initial Model Memory Footprint:
  Parameters: 268,098,176
  Precision: 2 bytes
  Total Memory: 1.91 GB
    - Parameters: 0.50 GB
    - KV Cache (est): 1.41 GB
  Estimated FLOPs per forward pass (batch=8, seq=512): 2.05 TFLOPS

============================================================
Epoch 0 Summary
============================================================
  Duration (s)         :         29.27
  Tokens Processed     :       684,032
  Throughput (token/s) :         23370
  Training Steps       :           167
  Avg CPU (%)          :          21.0
  Avg Memory (%)       :          10.6
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :         11.70
  FLOPs (per token)    :   0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================
Epoch 1 Summary
============================================================
  Duration (s)         :         29.06
  Tokens Processed     :       684,032
  Throughput (token/s) :         23536
  Training Steps       :           167
  Avg CPU (%)          :          19.5
  Avg Memory (%)       :          10.5
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :         11.78
  FLOPs (per token)    :   0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================
Epoch 2 Summary
============================================================
  Duration (s)         :         29.42
  Tokens Processed     :       684,032
  Throughput (token/s) :         23252
  Training Steps       :           167
  Avg CPU (%)          :          25.4
  Avg Memory (%)       :          10.7
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :         11.64
  FLOPs (per token)    :   0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['lm_head.weight'].

============================================================
TRAINING COMPLETE
============================================================
Total Training Time: 105.76s
Total Epochs: 3
Average Epoch Time: 29.25s
Total Tokens Processed: 2,052,096
Average Throughput: 19403 tokens/second
Total FLOPs: 1027.47 TFLOPS
Average TFLOPS (per second): 9.71
Overall FLOPs (per token): 0.50 GFLOPS

Final Metrics:
Memory Footprint: 1.91 GB
Inference Throughput: 24886 tokens/second
Total Training FLOPs: 342.49 TFLOPS
Training completed.

In [11]:
summarize_training_results(trainer, monitor)

====================================================================================================
TRAINING RESULTS SUMMARY TABLE
====================================================================================================
Epoch Training Loss Validation Loss Time (s) Tokens Processed Throughput (token/s) TFLOPS (per second) Avg CPU (%) Avg Memory (%) Training Steps
    0        2.4887          3.1576    29.27          684,032                23370               11.70        21.0           10.6            167
    1        1.5854          3.5818    29.06          684,032                23535               11.78        19.5           10.5            167
    2        1.3717          3.6781    29.42          684,032                23252               11.64        25.4           10.7            167

----------------------------------------------------------------------------------------------------
TRAINING STATISTICS:
----------------------------------------------------------------------------------------------------
Total Training Time:      87.8 s
Average Epoch Time:       29.3 s
Total Tokens Processed:   2,052,096
Average Throughput:       23386 tokens/second
Average CPU Usage:        22.0%
Average Memory Usage:     10.6%
Total Training FLOPs:     1027.47 TFLOPS
Average TFLOPS (per sec): 11.71
Overall FLOPs (per token): 0.50 GFLOPS

====================================================================================================

**Reference**
- [Arxiv:Effective Quantization of Muon Optimizer States](https://arxiv.org/abs/2509.23106)
- [Huggingface:Efficient Deep Learning: A Comprehensive Overview of Optimization Techniques](https://huggingface.co/blog/Isayoften/optimization-rush)
- [Huggingface:Trainner](https://huggingface.co/docs/transformers/v4.33.0/main_classes/trainer)

### Activation Checkpointing with Precision

Activation Checkpointing with Precision is a dual-memory optimization technique that combines "Gradient Checkpointing" with "Mixed Precision." Standard checkpointing saves memory by discarding most intermediate activations during the forward pass and recalculating them only when needed during the backward pass. The "Precision" aspect adds a second layer: it stores the few remaining "checkpoints" in a low-precision format (like BF16 or FP16) and then upcasts them to a higher precision (like FP32) only during the intense recomputation phase to maintain numerical accuracy.

**How it Works**

In deep learning, the "activations" (outputs of each layer) are typically stored in memory so they can be used later to calculate gradients. For an LLM, these activations are massive. This technique manages them through a trade-off:
- Selective Storage (The Checkpoint): Instead of storing every activation, the model stores activations only at the boundaries of specific "blocks" (e.g., at the start of each Transformer layer).
- Low-Precision Caching: To save even more space, these boundary activations are stored in 16-bit (half the size of standard 32-bit floats).
- Dynamic Recomputation: When the backward pass needs the missing activations between checkpoints, it triggers a "mini-forward pass" for just that block.
- High-Precision Calculation: During this mini-forward pass, the model often upcasts the low-precision checkpoint to 32-bit or uses high-precision math (like BF16 Tensor Cores) to ensure the recomputed activations are identical to the original ones, preventing "drift" in the gradients.

**Implements Activation Checkpointing with Precision**

The provided script activates this via a combination of model-level methods and Trainer arguments.

**1. Enabling the Mechanism**

    model.gradient_checkpointing_enable()
    
This is a manual call to the underlying model architecture (Gemma). it replaces the standard forward pass of the Transformer layers with a "checkpointed" version that knows how to discard intermediate tensors.

**2. Integrating with Mixed Precision**

    training_args = TrainingArguments(
        bf16=bf16_supported,
        fp16=cuda_available and not bf16_supported,
        gradient_checkpointing=True,
        ...
    )
    
By setting both `bf16/fp16` and `gradient_checkpointing` to `True`, the Hugging Face Trainer ensures that:
- The activations saved at checkpoint boundaries are in the lower `model_dtype` (16-bit).
- The recomputation uses the "autocast" context, which performs the math in 16-bit but handles critical additions in 32-bit to preserve precision.

**3. Non-Reentrant Logic**

    gradient_checkpointing_kwargs={"use_reentrant": False}
    
Setting `use_reentrant=False` is the modern approach. It uses PyTorch's newer "saved tensors hooks," which are more compatible with mixed precision and DDP (Distributed Data Parallel) because they handle the synchronization of precision casts more cleanly than the older "reentrant" method.

**When to Use It?**

This is one of the most powerful memory-saving tools available, but it comes with a performance cost:
- Training with Large Batch Sizes: Use it if you want to increase your `per_device_train_batch_size` (e.g., from 4 to 16 as seen in the code). Larger batches provide smoother gradients and faster convergence.
- Long Sequence Lengths: If you are training on 4096 or 8192 tokens, the "activation memory" grows linearly with sequence length. Checkpointing is often the only way to fit these sequences into GPU memory.
- Deep Architectures: For models with many layers (like Gemma-3), the cumulative memory of activations is higher than the weights themselves. Checkpointing reduces this from $O(N)$ (where $N$ is layers) to roughly $O(\sqrt{N})$.
- Trading Time for Space: Use it when you have plenty of compute power but limited VRAM. Expect a 20-30 percent slowdown in training speed because you are essentially doing 33 percent more math (one forward pass, then re-doing the forward pass during the backward pass).

In [ ]:
# Environment Setup
import torch
from datasets import Dataset, DatasetDict
from transformers import (
    AutoTokenizer, 
    AutoModelForCausalLM,
    DataCollatorForLanguageModeling,
    Trainer,
    TrainingArguments,
    TrainerCallback,
)

In [ ]:
# Configuration
MODEL_NAME = "google/gemma-3-270m"   
OUTPUT_DIR = "./gemma-3-270m-finetuned-qa-checkpoint"

# Check GPU capabilities
cuda_available = torch.cuda.is_available()
bf16_supported = torch.cuda.is_bf16_supported() if cuda_available else False

print("Hardware Configuration:")
print(f"CUDA Available: {cuda_available}")
if cuda_available:
    print(f"GPU: {torch.cuda.get_device_name(0)}")

# Load model with precision for checkpointing
model_dtype = torch.bfloat16 if bf16_supported else torch.float16 if cuda_available else torch.float32
print(f"Loading {MODEL_NAME} in {model_dtype}...")
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    device_map="auto" if cuda_available else None,
    torch_dtype=model_dtype,
    low_cpu_mem_usage=True,
)

# Enable gradient checkpointing in model
model.gradient_checkpointing_enable()

# Training setup
monitor = EpochMonitor(model=model)

data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

# Configure training with activation checkpointing
training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=16,  # Larger batch with checkpointing
    per_device_eval_batch_size=16,
    gradient_accumulation_steps=1,
    learning_rate=2e-5,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_strategy="epoch",
    run_name="gemma-3-270m-qa-checkpoint",
    warmup_steps=50,
    lr_scheduler_type="cosine",
    
    # Mixed precision for recomputation
    bf16=bf16_supported,
    fp16=cuda_available and not bf16_supported,
    
    # Activation checkpointing configuration
    gradient_checkpointing=True,
    gradient_checkpointing_kwargs={"use_reentrant": False},
    
    # Optimization settings
    max_grad_norm=1.0,
    optim="adamw_torch",
    
    # Performance settings
    dataloader_pin_memory=cuda_available,
    dataloader_num_workers=2 if cuda_available else 0,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
    callbacks=[monitor],
)

# Print configuration
total_params = sum(p.numel() for p in model.parameters())
print(f"Total parameters: {total_params:,}")
print(f"Batch size: {training_args.per_device_train_batch_size}")
print(f"Model precision: {model_dtype}")
print(f"Activation checkpointing: Enabled")
print(f"Checkpoint precision: {model_dtype}")
print(f"Recomputation precision: {model_dtype}")
print(f"Memory reduction: ~{total_params * 2 / 1e9:.1f} GB activations saved")

print("Starting training with activation checkpointing...")

train_result = trainer.train()

trainer.save_model()
tokenizer.save_pretrained(OUTPUT_DIR)

print("Training completed.")

Hardware Configuration:
CUDA Available: True
GPU: NVIDIA RTX A4000
Loading google/gemma-3-270m in torch.bfloat16...

Loading weights:   0%|          | 0/236 [00:00<?, ?it/s]

Total parameters: 268,098,176
Batch size: 16
Model precision: torch.bfloat16
Activation checkpointing: Enabled
Checkpoint precision: torch.bfloat16
Recomputation precision: torch.bfloat16
Memory reduction: ~0.5 GB activations saved
Starting training with activation checkpointing...
Initial Model Memory Footprint:
  Parameters: 268,098,176
  Precision: 2 bytes
  Total Memory: 1.91 GB
    - Parameters: 0.50 GB
    - KV Cache (est): 1.41 GB
  Estimated FLOPs per forward pass (batch=8, seq=512): 2.05 TFLOPS

============================================================
Epoch 0 Summary
============================================================
  Duration (s)         :         26.17
  Tokens Processed     :       688,128
  Throughput (token/s) :         26296
  Training Steps       :            84
  Avg CPU (%)          :          19.2
  Avg Memory (%)       :          10.3
  Total FLOPs          : 344.54 TFLOPS
  TFLOPS (per second)  :         13.17
  FLOPs (per token)    :   0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================
Epoch 1 Summary
============================================================
  Duration (s)         :         25.88
  Tokens Processed     :       688,128
  Throughput (token/s) :         26586
  Training Steps       :            84
  Avg CPU (%)          :          24.3
  Avg Memory (%)       :          10.5
  Total FLOPs          : 344.54 TFLOPS
  TFLOPS (per second)  :         13.31
  FLOPs (per token)    :   0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================
Epoch 2 Summary
============================================================
  Duration (s)         :         26.30
  Tokens Processed     :       688,128
  Throughput (token/s) :         26164
  Training Steps       :            84
  Avg CPU (%)          :          25.6
  Avg Memory (%)       :          10.6
  Total FLOPs          : 344.54 TFLOPS
  TFLOPS (per second)  :         13.10
  FLOPs (per token)    :   0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['lm_head.weight'].

============================================================
TRAINING COMPLETE
============================================================
Total Training Time: 93.90s
Total Epochs: 3
Average Epoch Time: 26.12s
Total Tokens Processed: 2,064,384
Average Throughput: 21985 tokens/second
Total FLOPs: 1033.63 TFLOPS
Average TFLOPS (per second): 11.01
Overall FLOPs (per token): 0.50 GFLOPS

Final Metrics:
Memory Footprint: 1.91 GB
Inference Throughput: 29458 tokens/second
Total Training FLOPs: 344.54 TFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Training completed.

In [13]:
summarize_training_results(trainer, monitor)

====================================================================================================
TRAINING RESULTS SUMMARY TABLE
====================================================================================================
Epoch Training Loss Validation Loss Time (s) Tokens Processed Throughput (token/s) TFLOPS (per second) Avg CPU (%) Avg Memory (%) Training Steps
    0        2.7633          3.0562    26.17          688,128                26296               13.17        19.2           10.3             84
    1        1.9049          3.2701    25.88          688,128                26586               13.31        24.3           10.5             84
    2        1.6932          3.3235    26.30          688,128                26164               13.10        25.6           10.6             84

----------------------------------------------------------------------------------------------------
TRAINING STATISTICS:
----------------------------------------------------------------------------------------------------
Total Training Time:      78.4 s
Average Epoch Time:       26.1 s
Total Tokens Processed:   2,064,384
Average Throughput:       26348 tokens/second
Average CPU Usage:        23.0%
Average Memory Usage:     10.5%
Total Training FLOPs:     1033.63 TFLOPS
Average TFLOPS (per sec): 13.19
Overall FLOPs (per token): 0.50 GFLOPS

====================================================================================================

**Reference**
- [Arxiv:Efficient LLM Inference with Activation Checkpointing and Hybrid Caching](https://arxiv.org/pdf/2501.01792)
- [Huggingface:Trainner](https://huggingface.co/docs/transformers/v4.33.0/main_classes/trainer)

# Quantization-Aware Fine-Tuning (QAT)

Quantization-Aware Fine-Tuning (QAT) is a specialized technique used to compress Large Language Models (LLMs) by reducing their numerical precision (e.g., from 16-bit to 4-bit) while using a training phase to reclaim the intelligence typically lost during such a reduction.

While standard quantization is often done after a model is finished, QAT integrates the "limitations" of low-precision math directly into the fine-tuning process. This makes the model "aware" of the rounding errors it will face, allowing it to adapt its weights to stay accurate despite the grainier math.

**QAT vs. Post-Training Quantization (PTQ)**

If you are deciding between QAT and the more common Post-Training Quantization (PTQ), the differences are significant:
- Complexity: PTQ is a "one-click" process that takes minutes. QAT is a full fine-tuning run that requires a dataset and significant GPU time.
- Accuracy Recovery: PTQ often causes models to lose nuance or become "repetitive" at very low bit-widths (like 4-bit). QAT can often restore the model's performance to nearly 99% of the original full-precision model.
- Data Requirement: PTQ only needs a tiny "calibration" set (e.g., 100 sentences). QAT requires a representative dataset for the task you want the model to perform well in.

**When to Use It**

QAT is not always necessary, but it is the "gold standard" for specific needs:
- Edge Device Deployment: When you need a model to run on a phone, a smartwatch, or a low-power laptop and cannot afford the memory of a full 16-bit model.
- Extreme Compression: If you are pushing a model down to 3-bit or 2-bit precision, where standard quantization usually causes the model to "break" or become incoherent.
- Small Model Optimization: Small models (like 1B to 3B parameters) have less "room for error" than massive models. They benefit the most from QAT because every bit of precision counts for them.
- Performance-Critical Tasks: In fields like medicine, law, or coding, where a slight drop in logic or factual accuracy is unacceptable, QAT is used to ensure the compressed model remains reliable.

## Quantization Simulation

### Fake Quantization

Fake Quantization is a technique used during the training or fine-tuning of Large Language Models (LLMs) to simulate the errors and "noise" that occur when a model is eventually compressed to lower precision (like 8-bit or 4-bit).

Standard models are trained using high-precision 32-bit floats ($FP32$). If you simply "crush" them to 8-bit after training (Post-Training Quantization), the model often becomes confused by the sudden loss of detail. Fake Quantization solves this by letting the model "practice" being low-precision while it is still learning, so it can adjust its weights to compensate for the rounding errors before they become permanent.

**How it Works**

Fake Quantization inserts a special mathematical operation into the model's computation graph during the Forward Pass. This operation follows a two-step cycle:
- Quantize: The high-precision value (e.g., $0.123456$) is rounded to the nearest value representable in the target low-precision format (e.g., $0.12$).
- Dequantize: That rounded value is immediately converted back into a high-precision float (staying as $0.120000$).

The result is a high-precision number that "pretends" to be a low-precision one. It has the same coarse value that an 8-bit integer would have, but it is stored in a format that the computer can still use for training.

**The Backward Pass Trick**

Because rounding is a "step" function, its mathematical derivative is zero almost everywhere, which normally breaks the training process (gradients cannot flow). To fix this, Fake Quantization uses a Straight-Through Estimator (STE). This essentially tells the model: "Pretend the rounding never happened during the backward pass; just pass the gradients through as if the math were smooth."

**Implements Fake Quantization**

The code uses the Optimum Quanto library to automate the insertion of these "Fake Quant" nodes.

**1. Applying the Simulation**

    quantize(model, weights=qfloat8, activations=qfloat8)
    
This line is the heart of the process. It scans the Gemma-3-270m model and replaces every standard Linear layer with a "Quantized Layer." These new layers contain the "Fake Quantize" logic. By setting both weights and activations to `qfloat8`, the model is forced to simulate 8-bit floating point precision for both its stored knowledge (weights) and its real-time thoughts (activations) during every training step.

**2. Freezing for Training**

    freeze(model)
    
In quanto, "freezing" the model after the quantize call converts the parameters into a format where the quantization scales (the "rules" for how to round the numbers) are fixed. This allows the trainer to focus on adjusting the weight values themselves to find a "sweet spot" that works well under 8-bit constraints.

**3. Disabling Hardware Acceleration**

    fp16=False,
    bf16=False
    
The code explicitly disables standard mixed-precision training. This is because Fake Quantization is doing its own precision management. It needs the underlying calculations to stay in $FP32$ so that it can accurately track the tiny weight updates while simulating the 8-bit "fake" noise.

**When to Use It**

Fake Quantization is more "expensive" than standard quantization because it requires a fine-tuning phase, but it is necessary in several cases:
- Low-Bit Targets (4-bit and below): When you want to shrink a model to 4-bit or even 2-bit, the "shock" to the model is usually too great for Post-Training Quantization. Fake Quantization allows the model to "learn to live" with the low precision.
- Sensitive Reasoning Tasks: If your model is used for math, coding, or complex logic (like Gemma-3), it is highly sensitive to rounding errors. Fake Quantization preserves the model's reasoning capabilities much better than one-shot quantization.
- Quantizing Activations: Weights are easy to quantize because they are static. Activations (the data flowing through the model) change with every input and are much harder to predict. Fake Quantization is the best way to ensure the model can handle 8-bit activations without crashing or hallucinating.
- Preparing for Edge Deployment: If you are deploying to hardware that only supports 8-bit math (like some mobile NPU chips), you use Fake Quantization to ensure the model is "hardened" against the specific errors that hardware will produce.

In [ ]:
%%capture
!pip install optimum-quanto
!pip install --upgrade huggingface_hub diffusers optimum-quanto

# Environment Setup
import torch
from datasets import Dataset, DatasetDict
from transformers import (
    AutoTokenizer, 
    AutoModelForCausalLM,
    DataCollatorForLanguageModeling,
    Trainer,
    TrainingArguments,
    TrainerCallback,
)
from optimum.quanto import quantize, qfloat8, freeze

In [ ]:
# Configuration
MODEL_NAME = "google/gemma-3-270m"   
OUTPUT_DIR = "./gemma-3-270m-finetuned-qa-fakequant"

# Load and quantize model
print(f"Loading {MODEL_NAME} with fake quantization...")
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    torch_dtype=torch.float32,  # Load in half precision
    low_cpu_mem_usage=True
)

# Apply fake quantization to the model
print("Applying fake quantization...")
quantize(model, weights=qfloat8, activations=qfloat8)

# Freeze quantization parameters
freeze(model)

print("Model quantized with fake quantization operations")

# Training setup
data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

monitor = EpochMonitor(model=model)

training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    gradient_accumulation_steps=1,
    learning_rate=2e-5,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_strategy="epoch",
    run_name="gemma-3-270m-qa-fakequant",
    warmup_ratio=0.1,
    lr_scheduler_type="cosine",
    fp16=False,  # Disable mixed precision for quantization compatibility
    bf16=False,  # Disable bfloat16 as well
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
    callbacks=[monitor]
)

total_params = sum(p.numel() for p in model.parameters())
trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f"Total parameters: {total_params:,}")
print(f"Trainable parameters: {trainable_params:,}")
print(f"Batch size: {training_args.per_device_train_batch_size}")
print("Starting training with fake quantization...")

train_result = trainer.train()

# Save the quantized model
trainer.save_model()
tokenizer.save_pretrained(OUTPUT_DIR)

print("Training with fake quantization completed!")

Loading google/gemma-3-270m with fake quantization...

Loading weights:   0%|          | 0/236 [00:00<?, ?it/s]

Applying fake quantization...

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Model quantized with fake quantization operations
Total parameters: 435,870,336
Trainable parameters: 435,870,336
Batch size: 8
Starting training with fake quantization...
Initial Model Memory Footprint:
  Parameters: 435,870,336
  Precision: 4 bytes
  Total Memory: 4.44 GB
    - Parameters: 1.62 GB
    - KV Cache (est): 2.81 GB
  Estimated FLOPs per forward pass (batch=8, seq=512): 2.05 TFLOPS

============================================================
Epoch 0 Summary
============================================================
  Duration (s)         :         72.83
  Tokens Processed     :       684,032
  Throughput (token/s) :          9392
  Training Steps       :           167
  Avg CPU (%)          :          20.1
  Avg Memory (%)       :          12.3
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          4.70
  FLOPs (per token)    :   0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================
Epoch 1 Summary
============================================================
  Duration (s)         :         73.37
  Tokens Processed     :       684,032
  Throughput (token/s) :          9323
  Training Steps       :           167
  Avg CPU (%)          :          18.3
  Avg Memory (%)       :          12.5
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          4.67
  FLOPs (per token)    :   0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================
Epoch 2 Summary
============================================================
  Duration (s)         :         73.48
  Tokens Processed     :       684,032
  Throughput (token/s) :          9309
  Training Steps       :           167
  Avg CPU (%)          :          18.0
  Avg Memory (%)       :          12.4
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          4.66
  FLOPs (per token)    :   0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================
TRAINING COMPLETE
============================================================
Total Training Time: 258.78s
Total Epochs: 3
Average Epoch Time: 73.23s
Total Tokens Processed: 2,052,096
Average Throughput: 7930 tokens/second
Total FLOPs: 1027.47 TFLOPS
Average TFLOPS (per second): 3.97
Overall FLOPs (per token): 0.50 GFLOPS

Final Metrics:
Memory Footprint: 4.44 GB
Inference Throughput: 11230 tokens/second
Total Training FLOPs: 342.49 TFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Training with fake quantization completed!

In [16]:
summarize_training_results(trainer, monitor)

====================================================================================================
TRAINING RESULTS SUMMARY TABLE
====================================================================================================
Epoch Training Loss Validation Loss Time (s) Tokens Processed Throughput (token/s) TFLOPS (per second) Avg CPU (%) Avg Memory (%) Training Steps
    0        3.2249          3.3149    72.83          684,032                 9392                4.70        20.1           12.3            167
    1        3.0178          3.3434    73.37          684,032                 9322                4.67        18.3           12.5            167
    2        2.9422          3.3833    73.48          684,032                 9309                4.66        18.0           12.4            167

----------------------------------------------------------------------------------------------------
TRAINING STATISTICS:
----------------------------------------------------------------------------------------------------
Total Training Time:      219.7 s
Average Epoch Time:       73.2 s
Total Tokens Processed:   2,052,096
Average Throughput:       9341 tokens/second
Average CPU Usage:        18.8%
Average Memory Usage:     12.4%
Total Training FLOPs:     1027.47 TFLOPS
Average TFLOPS (per sec): 4.68
Overall FLOPs (per token): 0.50 GFLOPS

====================================================================================================

**Reference**
- [PyTorch:FakeQuantize](https://docs.pytorch.org/docs/stable/generated/torch.ao.quantization.fake_quantize.FakeQuantize.html)
- [Huggingface:Quantization](https://huggingface.co/docs/transformers/en/main_classes/quantization)
- [Huggingface:LoRA](https://huggingface.co/docs/peft/en/package_reference/lora)
- [Arxiv:Precision Neural Network Quantization via Learnable Adaptive Modules](https://arxiv.org/html/2504.17263v1)
- [Huggingface:Optimum Quanto](https://huggingface.co/docs/transformers/main/quantization/quanto)
- [Huggingface:Quanto](https://huggingface.co/docs/diffusers/en/quantization/quanto)
- [GitHub:Optimum Quanto](https://github.com/huggingface/optimum-quanto)

### Straight-Through Estimator (STE)

Straight-Through Estimator (STE) is a mathematical "workaround" used to train neural networks that contain non-differentiable operations, most notably quantization.

In a standard network, every operation must be differentiable so that gradients (signals telling the model how to improve) can flow backward from the loss function to the weights. However, quantization functions like rounding or thresholding are "step functions"—their slope is zero almost everywhere and infinite at the steps. If you tried to train a model through these, the gradients would become zero, and the model would stop learning.

**How it Works**

The STE allows training to continue by essentially "lying" to the model during the backward pass:
- Forward Pass (The Truth): The model uses the actual, non-differentiable operation. For example, it rounds a weight of $0.76$ to a discrete 8-bit integer of $76$. This ensures the model's output reflects the actual errors caused by quantization.
- Backward Pass (The Lie): When it is time to calculate gradients, the STE "pretends" the quantization function was actually an Identity Function ($y = x$). It ignores the rounding and passes the gradient through unchanged to the underlying high-precision weights.
- The Update: Because the high-precision weights receive a non-zero gradient, they can slowly shift. Even if a weight only moves from $0.76$ to $0.77$ (both of which might round to the same integer), enough of these tiny movements eventually push the weight across a "step" to a new quantized value.

**Implements STE**

The code you provided uses the BitsAndBytes library and LoRA (Low-Rank Adaptation), which utilize STE principles behind the scenes to handle the 8-bit quantized base model.

**1. The Quantized Base (Frozen Truth)**

    bnb_config = BitsAndBytesConfig(load_in_8bit=True)
    model = AutoModelForCausalLM.from_pretrained(..., quantization_config=bnb_config)

The base model weights are loaded in a "frozen" 8-bit state. In a pure QAT scenario, STE would update these weights directly. Here, they are kept static, but they provide the "quantized context" for the training.

**2. The Differentiable Adapter (LoRA)**

    model = get_peft_model(model, lora_config)

Since you cannot easily backpropagate through 8-bit integers without specific STE kernels, the code adds LoRA adapters in high precision (FP16/FP32).
- When the model runs, it combines the Quantized Base (using the "Forward Pass Truth") with the Trainable Adapters.
- The gradients flow through the adapters normally.
- In a more advanced "Quantization-Aware" setup (like QLoRA), the STE logic is used to ensure that the gradients computed against the 4-bit or 8-bit base weights are correctly approximated to update the high-precision adapters.

**When to Use It**

You should use STE (or libraries that implement it) in the following scenarios:
- Quantization-Aware Training (QAT): When you want to train a model from scratch or fine-tune it while specifically simulating 4-bit or 8-bit rounding.
- Binarized Neural Networks (BNN): If you are pushing weights to the absolute limit where they can only be $-1$ or $+1$.
- Sparse Training: When you use "hard masks" to prune neurons (setting them to exactly zero). STE is used to allow "dead" neurons to potentially "wake up" if their underlying high-precision gradient becomes strong enough.
- Discrete Latent Variables: In advanced architectures like VQ-VAEs (Vector Quantized Variational Autoencoders) where the model must choose from a discrete codebook.

In [ ]:
# Environment setup
import torch
from datasets import Dataset, DatasetDict
from transformers import (
    AutoTokenizer, 
    AutoModelForCausalLM,
    DataCollatorForLanguageModeling,
    Trainer,
    TrainingArguments,
    BitsAndBytesConfig
)
from peft import LoraConfig, get_peft_model, TaskType

In [ ]:
# Configuration
MODEL_NAME = "google/gemma-3-270m"   
OUTPUT_DIR = "./gemma-3-270m-finetuned-qa-ste"

# Configure and load model with 8-bit quantization
bnb_config = BitsAndBytesConfig(
    load_in_8bit=True,
    llm_int8_enable_fp32_cpu_offload=False
)

print(f"Loading {MODEL_NAME} with 8-bit quantization...")
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    quantization_config=bnb_config,
    device_map="auto",
    torch_dtype=torch.float16
)

# Configure LoRA for PEFT
lora_config = LoraConfig(
    task_type=TaskType.CAUSAL_LM,
    r=16,
    lora_alpha=32,
    lora_dropout=0.05,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj"],
    bias="none"
)

# Apply PEFT to the quantized model
print("Applying LoRA adapters for PEFT...")
model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

print("Model loaded with 8-bit quantization + LoRA adapters")

# Training setup
monitor = EpochMonitor(model=model)

data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    gradient_accumulation_steps=1,
    learning_rate=2e-4,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_strategy="epoch",
    run_name="gemma-3-270m-qa-ste-lora",
    warmup_ratio=0.1,
    lr_scheduler_type="cosine",
    fp16=True,
    gradient_checkpointing=True
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
    callbacks=[monitor]
)

total_params = sum(p.numel() for p in model.parameters())
trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f"Total parameters: {total_params:,}")
print(f"Trainable parameters: {trainable_params:,}")
print(f"Batch size: {training_args.per_device_train_batch_size}")
print("Starting training with STE quantization + LoRA...")

train_result = trainer.train()

# Save only the adapters
model.save_pretrained(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)

print("Training completed!")

Loading tokenizer: google/gemma-3-270m
Tokenizer loaded. Vocab size: 262145
Tokenizing training data...
Tokenizing validation data...
Train examples: 1,331
Validation examples: 285
Loading google/gemma-3-270m with 8-bit quantization...

Loading weights:   0%|          | 0/236 [00:00<?, ?it/s]

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Applying LoRA adapters for PEFT...
trainable params: 1,474,560 || all params: 269,572,736 || trainable%: 0.5470
Model loaded with 8-bit quantization + LoRA adapters
Total parameters: 269,572,736
Trainable parameters: 1,474,560
Batch size: 8
Starting training with STE quantization + LoRA...
Initial Model Memory Footprint:
  Parameters: 269,572,736
  Precision: 2 bytes
  Total Memory: 1.91 GB
    - Parameters: 0.50 GB
    - KV Cache (est): 1.41 GB
  Estimated FLOPs per forward pass (batch=8, seq=512): 2.05 TFLOPS

============================================================
Epoch 0 Summary
============================================================
  Duration (s)         :         78.13
  Tokens Processed     :       684,032
  Throughput (token/s) :          8756
  Training Steps       :           167
  Avg CPU (%)          :          27.1
  Avg Memory (%)       :          14.9
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          4.38
  FLOPs (per token)    :   0.50 GFLOPS

============================================================
Epoch 1 Summary
============================================================
  Duration (s)         :         77.72
  Tokens Processed     :       684,032
  Throughput (token/s) :          8801
  Training Steps       :           167
  Avg CPU (%)          :          27.3
  Avg Memory (%)       :          14.9
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          4.41
  FLOPs (per token)    :   0.50 GFLOPS

============================================================
Epoch 2 Summary
============================================================
  Duration (s)         :         77.28
  Tokens Processed     :       684,032
  Throughput (token/s) :          8851
  Training Steps       :           167
  Avg CPU (%)          :          24.5
  Avg Memory (%)       :          14.8
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          4.43
  FLOPs (per token)    :   0.50 GFLOPS

============================================================
TRAINING COMPLETE
============================================================
Total Training Time: 251.34s
Total Epochs: 3
Average Epoch Time: 77.71s
Total Tokens Processed: 2,052,096
Average Throughput: 8165 tokens/second
Total FLOPs: 1027.47 TFLOPS
Average TFLOPS (per second): 4.09
Overall FLOPs (per token): 0.50 GFLOPS

Final Metrics:
Memory Footprint: 1.91 GB
Inference Throughput: 9137 tokens/second
Total Training FLOPs: 342.49 TFLOPS
Training completed!

**Reference**
- [Arxiv:Understanding Straight-Through Estimator in Training Activation Quantized Neural Nets](https://arxiv.org/abs/1903.05662)
- [Arxiv:Beyond Discreteness: Finite-Sample Analysis of Straight-Through Estimator for Quantizatize](https://arxiv.org/abs/2505.18113)
- [Huggingface:Quantization](https://huggingface.co/docs/transformers/en/main_classes/quantization)
- [Huggingface:LoRA](https://huggingface.co/docs/peft/en/package_reference/lora)

### Learnable Quantization Parameters

Learnable Quantization Parameters (often referred to as Learned Step Size Quantization or LSQ) is an advanced Quantization-Aware Training (QAT) technique. Instead of calculating fixed scaling factors and zero-points once based on statistics (like Min-Max or MSE), the model treats these values as trainable parameters—just like weights or biases.

In standard quantization, parameters are static "rulers" used to measure and round values. In learnable quantization, the model can "stretch" or "shift" these rulers during training to minimize the actual task loss. This allows the model to protect "salient" values that are critical for reasoning, even if they aren't statistically the largest outliers.

**How it Works**

The core of this method is making the quantization formula differentiable. Typically, quantization follows an affine transformation:$$q = \text{round}\left(\frac{x}{s} + z\right)$$Where $s$ is the scaling factor (step size) and $z$ is the zero-point.
- Gradients for Metadata: During the backward pass, the system calculates gradients for $s$ and $z$ using the Straight-Through Estimator (STE).
- Loss Optimization: If the loss is high because a specific layer's rounding is too aggressive, the optimizer will adjust $s$ to change the "resolution" of that layer.
- Task-Awareness: Unlike Post-Training Quantization (PTQ), which only cares about matching the distribution of the weights, learnable parameters care about the performance of the model. If a small range of weights is vital for the model's logic, the scaling factor will adapt to prioritize precision in that specific range.

**Implements Quantization Parameters**

The provided code uses Optimum Quanto to set up a manual training loop where quantization metadata is specifically unlocked for the optimizer.

**1. Identifying the Parameters**

    for name, param in model.named_parameters():
        if 'scale' in name or 'zeropoint' in name.lower():
            param.requires_grad = True

Standard quantization libraries usually "freeze" the scale and zero-point after an initial calibration pass. This loop overrides that behavior. It searches the model’s internal state for tensors named scale or zeropoint and sets `requires_grad = True`. This signals to PyTorch that these values should be updated during the `trainer.train()` call.

**2. The Optimizer's Role**

    learning_rate=1e-4  # Higher learning rate for quantization parameters

Because the number of quantization parameters is tiny compared to the billions of model weights, they often require a slightly higher learning rate to move effectively. During training, the Trainer will update these scales at every step, gradually "refining" the 8-bit grid to better represent the Gemma-3 model's knowledge.

**3. Finalizing the "Rulers"**
    
    freeze(model)

Once training is complete, `freeze(model)` converts these learnable float parameters back into fixed constants. This "bakes" the optimized scales into the model architecture for efficient deployment.

**When to Use It**

Learnable Quantization Parameters are the "pro" version of quantization and are best used in these scenarios:
- Ultra-Low Bit-Widths (2-bit to 4-bit): At 8-bit, fixed scales are usually enough. However, at 4-bit or lower, the "rounding noise" is so loud that the model needs to surgically adjust its scales to survive.
- Small Models (under 7B parameters): Smaller models like Gemma-3-270m have very little "redundancy." Every bit matters, so learning the optimal parameters often results in significantly higher accuracy than standard PTQ.
- Outlier-Heavy Distributions: LLMs often have "outlier features"—specific dimensions with massive values. Static quantization often clips these or loses resolution trying to fit them. Learnable parameters allow the model to find a balance that accommodates outliers without sacrificing the precision of normal values.
- Strict Accuracy Requirements: If you are deploying a model where you cannot afford any drop in benchmark scores (MMLU, GSM8K), this technique provides the best "accuracy recovery" for a quantized model.

In [ ]:
# Environment Setup
import torch
from datasets import Dataset, DatasetDict
from transformers import (
    AutoTokenizer, 
    AutoModelForCausalLM,
    DataCollatorForLanguageModeling,
    Trainer,
    TrainingArguments
)
from optimum.quanto import quantize, qint8, freeze, calibrate

In [ ]:
# Configuration
MODEL_NAME = "google/gemma-3-270m"   
OUTPUT_DIR = "./gemma-3-270m-finetuned-qa-learnable-quant"

# Load model
print(f"Loading {MODEL_NAME}...")
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    torch_dtype=torch.float32,
    low_cpu_mem_usage=True
)

# Apply quantization with calibration
print("Applying quantization with calibration...")
quantize(model, weights=qint8)

# Enable gradients for quantization parameters
for name, param in model.named_parameters():
    if 'scale' in name or 'zeropoint' in name.lower():
        param.requires_grad = True

# Training setup
data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

monitor = EpochMonitor(model=model)

training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    gradient_accumulation_steps=1,
    learning_rate=1e-4,  # Higher learning rate for quantization parameters
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_strategy="epoch",
    run_name="gemma-3-270m-qa-learnable-quant",
    warmup_ratio=0.1,
    lr_scheduler_type="cosine",
    fp16=False
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    callbacks=[monitor],
    data_collator=data_collator
)

total_params = sum(p.numel() for p in model.parameters())
trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f"Total parameters: {total_params:,}")
print(f"Trainable parameters: {trainable_params:,}")
print(f"Batch size: {training_args.per_device_train_batch_size}")
print("Starting training with learnable quantization...")

train_result = trainer.train()

# Freeze quantization parameters after training
freeze(model)

trainer.save_model()
tokenizer.save_pretrained(OUTPUT_DIR)

print("Training with learnable quantization completed!")

`torch_dtype` is deprecated! Use `dtype` instead!

Loading google/gemma-3-270m...

Loading weights:   0%|          | 0/236 [00:00<?, ?it/s]

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Applying quantization with calibration...
Total parameters: 268,098,176
Trainable parameters: 268,098,176
Batch size: 8
Starting training with learnable quantization...
Initial Model Memory Footprint:
  Parameters: 268,098,176
  Precision: 4 bytes
  Total Memory: 3.81 GB
    - Parameters: 1.00 GB
    - KV Cache (est): 2.81 GB
  Estimated FLOPs per forward pass (batch=8, seq=512): 2.05 TFLOPS

============================================================
Epoch 0 Summary
============================================================
  Duration (s)         :         59.02
  Tokens Processed     :       684,032
  Throughput (token/s) :         11590
  Training Steps       :           167
  Avg CPU (%)          :          16.3
  Avg Memory (%)       :          10.6
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          5.80
  FLOPs (per token)    :   0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================
Epoch 1 Summary
============================================================
  Duration (s)         :         60.51
  Tokens Processed     :       684,032
  Throughput (token/s) :         11305
  Training Steps       :           167
  Avg CPU (%)          :          18.8
  Avg Memory (%)       :          10.6
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          5.66
  FLOPs (per token)    :   0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================
Epoch 2 Summary
============================================================
  Duration (s)         :         60.59
  Tokens Processed     :       684,032
  Throughput (token/s) :         11289
  Training Steps       :           167
  Avg CPU (%)          :          20.1
  Avg Memory (%)       :          10.7
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          5.65
  FLOPs (per token)    :   0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['lm_head.weight._data', 'lm_head.weight._scale'].

============================================================
TRAINING COMPLETE
============================================================
Total Training Time: 210.88s
Total Epochs: 3
Average Epoch Time: 60.04s
Total Tokens Processed: 2,052,096
Average Throughput: 9731 tokens/second
Total FLOPs: 1027.47 TFLOPS
Average TFLOPS (per second): 4.87
Overall FLOPs (per token): 0.50 GFLOPS

Final Metrics:
Memory Footprint: 3.81 GB
Inference Throughput: 12953 tokens/second
Total Training FLOPs: 342.49 TFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Training with learnable quantization completed!

In [13]:
summarize_training_results(trainer, monitor)

====================================================================================================
TRAINING RESULTS SUMMARY TABLE
====================================================================================================
Epoch Training Loss Validation Loss Time (s) Tokens Processed Throughput (token/s) TFLOPS (per second) Avg CPU (%) Avg Memory (%) Training Steps
    0        1.6219          4.9731    59.02          684,032                11590                5.80        16.3           10.6            167
    1        0.6625          6.3602    60.51          684,032                11304                5.66        18.8           10.6            167
    2        0.2824          7.6374    60.59          684,032                11288                5.65        20.1           10.7            167

----------------------------------------------------------------------------------------------------
TRAINING STATISTICS:
----------------------------------------------------------------------------------------------------
Total Training Time:      180.1 s
Average Epoch Time:       60.0 s
Total Tokens Processed:   2,052,096
Average Throughput:       11393 tokens/second
Average CPU Usage:        18.4%
Average Memory Usage:     10.6%
Total Training FLOPs:     1027.47 TFLOPS
Average TFLOPS (per sec): 5.70
Overall FLOPs (per token): 0.50 GFLOPS

====================================================================================================

**Reference**
- [Arxiv:Precision Neural Network Quantization via Learnable Adaptive Modules](https://arxiv.org/html/2504.17263v1)
- [Huggingface:Quantization](https://huggingface.co/docs/optimum/en/concept_guides/quantization)
- [Huggingface:Optimum Quanto](https://huggingface.co/docs/transformers/main/quantization/quanto)
- [Huggingface:Quanto](https://huggingface.co/docs/diffusers/en/quantization/quanto)
- [GitHub:Optimum Quanto](https://github.com/huggingface/optimum-quanto)

## Advanced QAT Methods

### Mixed-Precision QAT

Mixed-Precision QAT (Quantization-Aware Training) is an optimization strategy that assigns different numerical bit-widths to various layers or components of a Large Language Model during the training process. Instead of forcing the entire model into a single format (like 4-bit), it identifies which parts of the model are highly sensitive to noise and keeps them in a higher precision (like 8-bit or 16-bit), while aggressively compressing the "robust" layers that don't impact final performance as much.

**How it Works**

Mixed-Precision QAT treats the model as a collection of diverse components rather than a uniform block.

- Sensitivity Identification: The process starts by determining which layers contribute most to the model's "intelligence." Typically, early layers (embeddings) and late layers (output heads) are more sensitive than the middle layers.
- Strategic Assignment: 
    - Sensitive Tensors: Assigned higher bit-widths (e.g., INT8) or kept in floating-point format to maintain accuracy.
    - Robust Tensors: Assigned lower bit-widths (e.g., INT4 or FP8) to maximize memory savings.
- Simulated Low-Precision Training: Like standard QAT, it uses "fake quantization" to simulate the errors of these different formats during the forward pass. The model then uses the fine-tuning phase to learn how to communicate across layers that are operating at different levels of granularity.

**Implements Mixed-Precision QAT**

The script utilizes the ModelOpt library to define a granular quantization map that can be expanded to target specific tensor types.

**1. Granular Configuration Mapping**

    quant_config = {
        "quant_cfg": {
            "*.weight_quantizer": {"num_bits": 8},
            "*.input_quantizer": {"num_bits": 8},
            "*.output_quantizer": {"num_bits": 8}
        }
    }

In this implementation, the `quant_config` dictionary acts as a blueprint. Using wildcards (`*`), it targets specific sub-components. While the provided example sets all weights, inputs, and outputs to 8-bit, the `ModelOpt` framework allows this to be expanded. For instance, one could specify `"model.layers.0.*": {"num_bits": 16}` to keep the first layer in high precision while the rest of the model is pushed lower.

**2. Injection of Diverse Quantizers**

    quantized_model = quantize(model, quant_config)

The `quantize()` function acts as a compiler. It traverses the Gemma-3 architecture and replaces standard layers with specialized Mixed-Precision modules. Each module is "programmed" with the specific bit-width defined in the config, allowing the model to perform 8-bit math in some sections and higher-precision math in others during the same forward pass.

**3. Training the Inter-Layer Logic**

By running `trainer.train()`, the model learns to handle the "information loss" at layer boundaries. If a 4-bit layer passes data to an 8-bit layer, the model adjusts its weights to ensure the "scaling" between these different precisions remains consistent.

**When to Use It**

Mixed-Precision QAT is the most sophisticated form of model compression and is ideal for:
- Pushing Past the "Accuracy Wall": Use it when a uniform 4-bit quantization causes your model to fail benchmarks. By "buying back" precision for just the most critical 10% of layers, you can often restore 100% of the original model's accuracy.
- Hardware-Specific Constraints: Use it for deployment on NPUs or DSPs that have specific requirements (e.g., a chip that supports 8-bit activations but 4-bit weights).
- Long-Context Window Models: For models like Gemma-3 processing large amounts of text, the Key-Value (KV) cache can be massive. Mixed-Precision QAT can target the Attention mechanism with higher precision while heavily compressing the MLP layers to save VRAM.
- Multi-Modal Models: When training models that handle both images and text, you can use higher precision for the sensitive image-encoding layers and lower precision for the text-processing layers.

In [ ]:
%%capture
!pip install nvidia-modelopt[torch] --extra-index-url https://pypi.nvidia.com
!pip install --upgrade nvidia-modelopt transformers accelerate datasets
# 1. Install the 'real' Transformer Engine with PyTorch extensions
!pip install --no-build-isolation transformer-engine[pytorch]

# 2. Reinstall ModelOpt with the 'hf' (Hugging Face) extra to resolve version conflicts
!pip install --upgrade "nvidia-modelopt[hf]" --extra-index-url https://pypi.nvidia.com

import torch
from datasets import Dataset, DatasetDict
from transformers import (
    AutoTokenizer, 
    AutoModelForCausalLM,
    DataCollatorForLanguageModeling,
    Trainer,
    TrainingArguments
)
from modelopt.torch.quantization import quantize

In [ ]:
# Configuration
MODEL_NAME = "google/gemma-3-270m"   
OUTPUT_DIR = "./gemma-3-270m-finetuned-qa-mixed-precision-qat"

# Load model
print(f"Loading {MODEL_NAME}...")
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    torch_dtype=torch.float32,
    low_cpu_mem_usage=True
)

# Configure mixed-precision quantization for modelopt
print("Configuring mixed-precision quantization...")
quant_config = {
    "quant_cfg": {
        "*.weight_quantizer": {"num_bits": 8},
        "*.input_quantizer": {"num_bits": 8},
        "*.output_quantizer": {"num_bits": 8}
    }
}

# Apply quantization to the model
print("Applying mixed-precision quantization...")
quantized_model = quantize(model, quant_config)
print("Model quantized with mixed-precision strategies")

# Training setup
monitor = EpochMonitor(model=quantized_model)
data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    gradient_accumulation_steps=1,
    learning_rate=2e-5,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_strategy="epoch",
    run_name="gemma-3-270m-qa-mixed-precision-qat",
    warmup_ratio=0.1,
    lr_scheduler_type="cosine",
    fp16=True
)

trainer = Trainer(
    model=quantized_model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
    callbacks=[monitor]
)

total_params = sum(p.numel() for p in quantized_model.parameters())
trainable_params = sum(p.numel() for p in quantized_model.parameters() if p.requires_grad)
print(f"Total parameters: {total_params:,}")
print(f"Trainable parameters: {trainable_params:,}")
print(f"Batch size: {training_args.per_device_train_batch_size}")
print("Starting training with mixed-precision QAT...")

train_result = trainer.train()

trainer.save_model()
tokenizer.save_pretrained(OUTPUT_DIR)

print("Training with mixed-precision QAT completed!")

/usr/local/lib/python3.11/dist-packages/modelopt/torch/utils/logging.py:115: UserWarning: Failed to import transformers plugin due to: ImportError("cannot import name 'find_pruneable_heads_and_indices' from 'transformers.pytorch_utils' (/usr/local/lib/python3.11/dist-packages/transformers/pytorch_utils.py)"). You may ignore this warning if you do not need this plugin.
  warnings.warn(message, *args, **kwargs)
/usr/local/lib/python3.11/dist-packages/modelopt/torch/utils/logging.py:115: UserWarning: Failed to import transformer engine plugin due to: RuntimeError("Found empty `transformer-engine` meta package installed. Install `transformer-engine` with framework extensions via'pip3 install --no-build-isolation transformer-engine[pytorch,jax]==VERSION' or 'pip3 install transformer-engine[core]` for the TE core lib only. The `core_cu12` or `core_cu13` extra deps can be used to specify CUDA version for the TE core lib."). You may ignore this warning if you do not need this plugin.
  warnings.warn(message, *args, **kwargs)
/usr/local/lib/python3.11/dist-packages/modelopt/torch/utils/logging.py:115: UserWarning: Failed to import huggingface plugin due to: ImportError("cannot import name 'find_pruneable_heads_and_indices' from 'transformers.pytorch_utils' (/usr/local/lib/python3.11/dist-packages/transformers/pytorch_utils.py)"). You may ignore this warning if you do not need this plugin.
  warnings.warn(message, *args, **kwargs)
/usr/local/lib/python3.11/dist-packages/modelopt/torch/utils/logging.py:115: UserWarning: Failed to import peft plugin due to: ImportError("cannot import name 'find_pruneable_heads_and_indices' from 'transformers.pytorch_utils' (/usr/local/lib/python3.11/dist-packages/transformers/pytorch_utils.py)"). You may ignore this warning if you do not need this plugin.
  warnings.warn(message, *args, **kwargs)
/usr/local/lib/python3.11/dist-packages/modelopt/torch/utils/logging.py:115: UserWarning: Failed to import transformer_engine plugin due to: RuntimeError("Found empty `transformer-engine` meta package installed. Install `transformer-engine` with framework extensions via'pip3 install --no-build-isolation transformer-engine[pytorch,jax]==VERSION' or 'pip3 install transformer-engine[core]` for the TE core lib only. The `core_cu12` or `core_cu13` extra deps can be used to specify CUDA version for the TE core lib."). You may ignore this warning if you do not need this plugin.
  warnings.warn(message, *args, **kwargs)
/usr/local/lib/python3.11/dist-packages/modelopt/torch/__init__.py:36: UserWarning: transformers version 5.1.0 is not tested with nvidia-modelopt and may cause issues. Please install recommended version with `pip install nvidia-modelopt[hf]` if working with HF models.
  _warnings.warn(

Loading google/gemma-3-270m...

Loading weights:   0%|          | 0/236 [00:00<?, ?it/s]

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Configuring mixed-precision quantization...
Applying mixed-precision quantization...
Inserted 381 quantizers
Model quantized with mixed-precision strategies
Total parameters: 268,098,176
Trainable parameters: 268,098,176
Batch size: 8
Starting training with mixed-precision QAT...
Initial Model Memory Footprint:
  Parameters: 268,098,176
  Precision: 4 bytes
  Total Memory: 3.81 GB
    - Parameters: 1.00 GB
    - KV Cache (est): 2.81 GB
  Estimated FLOPs per forward pass (batch=8, seq=512): 2.05 TFLOPS
Loading extension modelopt_cuda_ext...
Loaded extension modelopt_cuda_ext in 68.3 seconds

============================================================
Epoch 0 Summary
============================================================
  Duration (s)         :        121.10
  Tokens Processed     :       684,032
  Throughput (token/s) :          5648
  Training Steps       :           167
  Avg CPU (%)          :          22.2
  Avg Memory (%)       :          14.0
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          2.83
  FLOPs (per token)    :   0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================
Epoch 1 Summary
============================================================
  Duration (s)         :         51.97
  Tokens Processed     :       684,032
  Throughput (token/s) :         13161
  Training Steps       :           167
  Avg CPU (%)          :          22.4
  Avg Memory (%)       :          12.0
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          6.59
  FLOPs (per token)    :   0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================
Epoch 2 Summary
============================================================
  Duration (s)         :         52.34
  Tokens Processed     :       684,032
  Throughput (token/s) :         13068
  Training Steps       :           167
  Avg CPU (%)          :          23.2
  Avg Memory (%)       :          12.0
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          6.54
  FLOPs (per token)    :   0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['lm_head.weight'].

============================================================
TRAINING COMPLETE
============================================================
Total Training Time: 256.62s
Total Epochs: 3
Average Epoch Time: 75.14s
Total Tokens Processed: 2,052,096
Average Throughput: 7997 tokens/second
Total FLOPs: 1027.47 TFLOPS
Average TFLOPS (per second): 4.00
Overall FLOPs (per token): 0.50 GFLOPS

Final Metrics:
Memory Footprint: 3.81 GB
Inference Throughput: 15223 tokens/second
Total Training FLOPs: 342.49 TFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Training with mixed-precision QAT completed!

In [16]:
summarize_training_results(trainer, monitor)

====================================================================================================
TRAINING RESULTS SUMMARY TABLE
====================================================================================================
Epoch Training Loss Validation Loss Time (s) Tokens Processed Throughput (token/s) TFLOPS (per second) Avg CPU (%) Avg Memory (%) Training Steps
    0        3.4863          4.2512   121.10          684,032                 5648                2.83        22.2           14.0            167
    1        3.8125          5.9095    51.97          684,032                13161                6.59        22.4           12.0            167
    2        3.7231          6.2067    52.34          684,032                13068                6.54        23.2           12.0            167

----------------------------------------------------------------------------------------------------
TRAINING STATISTICS:
----------------------------------------------------------------------------------------------------
Total Training Time:      225.4 s
Average Epoch Time:       75.1 s
Total Tokens Processed:   2,052,096
Average Throughput:       9104 tokens/second
Average CPU Usage:        22.6%
Average Memory Usage:     12.7%
Total Training FLOPs:     1027.47 TFLOPS
Average TFLOPS (per sec): 4.56
Overall FLOPs (per token): 0.50 GFLOPS

====================================================================================================

**Reference**
- [Arxiv:Mixed-Precision Quantization for Language Models: Techniques and Prospects](https://arxiv.org/html/2510.16805v1)
- [Arxiv:Mix-QViT: Mixed-Precision Vision Transformer Quantization Driven by Layer Importance and Quantization Sensitivity](https://arxiv.org/html/2501.06357v1)
- [Huggingface:NVIDIA ModelOpt](https://huggingface.co/docs/diffusers/en/quantization/modelopt)
- [PyTorch:Deploy Quantized Models using Torch-TensorRT](https://docs.pytorch.org/TensorRT/tutorials/_rendered_examples/dynamo/vgg16_ptq.html)

### Differentiable Quantization

Differentiable Quantization is an advanced optimization technique where the quantization process is transformed into a "soft" and continuous operation during training.

In traditional quantization, rounding numbers to discrete levels (like $0$ or $1$) is a "hard" operation with a derivative of zero, which normally breaks backpropagation. Differentiable quantization solves this by using continuous relaxations, such as the Gumbel-Softmax trick. This allows the model to "smoothly" explore different quantization levels during fine-tuning, with gradients flowing naturally through the "soft" decisions before they are hardened into final integers.

**How it Works: Gumbel-Softmax Relaxation**

Gumbel-Softmax is a mathematical bridge between the discrete world (integers) and the continuous world (floats).
- Categorical Probabilities: Each weight or activation is treated as a probability of belonging to a specific quantization level (e.g., is this value more like a $-1$, $0$, or $1$?).
- Gumbel Noise: Random noise from a Gumbel distribution is added to these probabilities. This introduces "stochasticity," allowing the model to occasionally pick less-obvious levels to see if they improve the overall loss.
- Temperature-Scaled Softmax: A Softmax function is applied with a Temperature ($\tau$) parameter.
    - High Temperature: The output is "soft" and blurry, spreading weight across all possible levels. This allows for rich gradient flow early in training.
    - Low Temperature: The output becomes "hard" and peaked, eventually mimicking a true discrete integer (one-hot vector).
    
- Annealing: During fine-tuning, the temperature is gradually lowered (annealed). The model starts by exploring a "cloud" of possible quantization values and slowly "freezes" into the optimal discrete levels.

**Implements Differentiable Quantization**

The code uses TorchAO (Architecture Optimization), which handles the complexity of differentiable math through a specific "prepare" and "convert" workflow.

**1. Inserting the "Soft" Estimator**

    quantize_(
        model,
        QATConfig(
            base_config=Int8DynamicActivationInt4WeightConfig(),
            step="prepare"
        )
    )

In this script, the `step="prepare"` phase replaces static layers with fake quantization nodes. While the code comment notes that Gumbel-Softmax isn't a "built-in" toggle for this specific config, the Straight-Through Estimator (STE) used here is the most common implementation of differentiable quantization. It allows the gradients to pass "straight through" the rounding function as if it were a smooth, differentiable line.

**2. Gradient-Based Scaling**

By setting `bf16=True` in the `TrainingArguments`, the model maintains a high-precision "shadow" of the weights. As the `Trainer` runs, the gradients calculated via the "soft" quantization logic update these high-precision weights. The model learns to shift its weight distribution to fit perfectly into the $INT4$ boxes provided by the configuration.

**3. The Final Hardening**

The commented-out `step="convert"` is the equivalent of "zeroing out" the Gumbel-Softmax temperature. It takes the "soft" learned weights and permanently snaps them to the nearest $INT4$ or $INT8$ values for deployment.

**When to Use It**

Differentiable Quantization is particularly powerful in "fragile" scenarios:

- Extremely Low Precision (2-bit or Ternary): When moving to 2-bit (only 4 possible values), the rounding error is so massive that standard "hard" quantization often causes the model to diverge. Soft relaxations allow the model to find a path to convergence.
- Search for Optimal Bit-Width: It is used in Neural Architecture Search (NAS) to let the model "learn" whether a specific layer should be 4-bit, 8-bit, or 16-bit based on the gradient flow.
- Highly Non-Uniform Data: If a model has extreme "outlier" values (common in Llama or Gemma architectures), differentiable quantization allows the "scaling factors" to be learned alongside the weights, protecting those outliers from being clipped.
- Mobile and IoT Deployment: When every milliwatt of power matters, using differentiable quantization ensures the model is perfectly tailored for the specific integer-math limits of a mobile NPU.

In [ ]:
%%capture
!pip install torchao
!pip install --upgrade torchao

from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    TrainingArguments,
    Trainer,
    DataCollatorForLanguageModeling,
)
from datasets import DatasetDict, Dataset
import torch
import torch
from torchao.quantization.qat import QATConfig
from torchao.quantization import (
    quantize_,
    Int8DynamicActivationInt4WeightConfig,
    # Int8DynamicActivationInt4WeightQATQuantizer,  # alternative if you want 4-bit weights
)

In [ ]:
# Configuration
MODEL_NAME = "meta-llama/Llama-3.2-1B-Instruct"
OUTPUT_DIR = "./llama-3.2-1b-finetuned-qa-qat"

# Load tokenizer
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
tokenizer.pad_token = tokenizer.eos_token

# Tokenization
def tokenize_examples(df, max_length=MAX_LENGTH):
    texts = [
        f"""<bos>Question: {row['question_title']}
{row['question_body']}
Answer: {row['answer']}<eos>"""
        for row in df.iter_rows(named=True)
    ]
    tokenized = tokenizer(
        texts,
        truncation=True,
        max_length=max_length,
        padding="max_length",
        return_tensors="pt"
    )
    tokenized["labels"] = tokenized["input_ids"].clone()
    return tokenized

train_tokenized = tokenize_examples(train_data)
val_tokenized = tokenize_examples(val_data)

dataset_dict = DatasetDict({
    "train": Dataset.from_dict({
        "input_ids": train_tokenized["input_ids"],
        "attention_mask": train_tokenized["attention_mask"],
        "labels": train_tokenized["labels"]
    }),
    "validation": Dataset.from_dict({
        "input_ids": val_tokenized["input_ids"],
        "attention_mask": val_tokenized["attention_mask"],
        "labels": val_tokenized["labels"]
    })
})

In [ ]:
# Load model in full precision
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    device_map="auto",
    torch_dtype=torch.bfloat16,
    low_cpu_mem_usage=True,
)

# Apply TorchAO QAT with supported config (int8 dynamic act + int4 weight)
# -> fake quant inserted -> differentiable via STE during training
# Apply TorchAO QAT (differentiable fake quantization during training)
# This enables soft/differentiable behavior via STE (straight-through estimator)
# Gumbel-Softmax not built-in — use STE-based QAT as closest supported differentiable quantization
quantize_(
    model,
    QATConfig(
        base_config=Int8DynamicActivationInt4WeightConfig(),
        # base_config=Int8DynamicActivationInt4WeightQATQuantizer()  # uncomment for 4w if desired
        step="prepare"   # inserts fake quant -> differentiable during .train()
    )
)

# Training setup
monitor = EpochMonitor(model=model)
data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    gradient_accumulation_steps=2,
    learning_rate=2e-5,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_strategy="epoch",
    run_name="llama-3.2-1b-qa-qat-int8act4w",
    warmup_ratio=0.1,
    lr_scheduler_type="cosine",
    bf16=True,
    gradient_checkpointing=True,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
    callbacks=[monitor],
)

# Optional: after training, convert to real quantized for inference/export
# quantize_(
#     model,
#     QATConfig(
#         base_config=Int8DynamicActivationInt4WeightConfig(),
#         step="convert"
#     )
# )

print("Starting training...")
trainer.train()
trainer.save_model()
tokenizer.save_pretrained(OUTPUT_DIR)
print("Training completed!")

`torch_dtype` is deprecated! Use `dtype` instead!

Loading weights:   0%|          | 0/146 [00:00<?, ?it/s]

/usr/local/lib/python3.11/dist-packages/torchao/prototype/quantization/quant_api.py:92: UserWarning: `Int8DynamicActivationInt4WeightConfig` will be deleted in a future release of torchao. Please see https://github.com/pytorch/ao/issues/2752 for more details.
  warnings.warn(
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Starting training...
Initial Model Memory Footprint:
  Parameters: 1,235,814,400
  Precision: 2 bytes
  Total Memory: 18.30 GB
    - Parameters: 2.30 GB
    - KV Cache (est): 16.00 GB
  Estimated FLOPs per forward pass (batch=8, seq=512): 8.89 TFLOPS

============================================================
Epoch 0 Summary
============================================================
  Duration (s)         :        324.70
  Tokens Processed     :       342,016
  Throughput (token/s) :          1053
  Training Steps       :           167
  Avg CPU (%)          :          22.5
  Avg Memory (%)       :           9.7
  Total FLOPs          : 742.00 TFLOPS
  TFLOPS (per second)  :          2.29
  FLOPs (per token)    :   2.17 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================
Epoch 1 Summary
============================================================
  Duration (s)         :        325.32
  Tokens Processed     :       342,016
  Throughput (token/s) :          1051
  Training Steps       :           167
  Avg CPU (%)          :          21.8
  Avg Memory (%)       :           9.7
  Total FLOPs          : 742.00 TFLOPS
  TFLOPS (per second)  :          2.28
  FLOPs (per token)    :   2.17 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================
Epoch 2 Summary
============================================================
  Duration (s)         :        325.26
  Tokens Processed     :       342,016
  Throughput (token/s) :          1052
  Training Steps       :           167
  Avg CPU (%)          :          23.7
  Avg Memory (%)       :           9.7
  Total FLOPs          : 742.00 TFLOPS
  TFLOPS (per second)  :          2.28
  FLOPs (per token)    :   2.17 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['lm_head.weight'].

============================================================
TRAINING COMPLETE
============================================================
Total Training Time: 1082.71s
Total Epochs: 3
Average Epoch Time: 325.09s
Total Tokens Processed: 1,026,048
Average Throughput: 948 tokens/second
Total FLOPs: 2226.01 TFLOPS
Average TFLOPS (per second): 2.06
Overall FLOPs (per token): 2.17 GFLOPS

Final Metrics:
Memory Footprint: 18.30 GB
Inference Throughput: 1159 tokens/second
Total Training FLOPs: 742.00 TFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Training completed!

In [10]:
summarize_training_results(trainer, monitor)

====================================================================================================
TRAINING RESULTS SUMMARY TABLE
====================================================================================================
Epoch Training Loss Validation Loss Time (s) Tokens Processed Throughput (token/s) TFLOPS (per second) Avg CPU (%) Avg Memory (%) Training Steps
    0        2.1203          3.2376   324.70          342,016                 1053                2.29        22.5            9.7            167
    1        0.9202          3.4500   325.32          342,016                 1051                2.28        21.8            9.7            167
    2        0.8940          3.4018   325.26          342,016                 1051                2.28        23.7            9.7            167

----------------------------------------------------------------------------------------------------
TRAINING STATISTICS:
----------------------------------------------------------------------------------------------------
Total Training Time:      975.3 s
Average Epoch Time:       325.1 s
Total Tokens Processed:   1,026,048
Average Throughput:       1052 tokens/second
Average CPU Usage:        22.7%
Average Memory Usage:     9.7%
Total Training FLOPs:     2226.01 TFLOPS
Average TFLOPS (per sec): 2.28
Overall FLOPs (per token): 2.17 GFLOPS

====================================================================================================

**Reference**
- [Arxiv:TorchAO: PyTorch-Native Training-to-Serving Model Optimization](https://arxiv.org/abs/2507.16099)
- [Arxiv:Differentiable, Bit-shifting, and Scalable Quantization without training neural network from scratch](https://arxiv.org/abs/2510.16088)
- [Arxiv:Differentiable Soft Quantization: Bridging Full-Precision and Low-Bit Neural Networks](https://arxiv.org/abs/1908.05033)
- [PyTorch:Welcome to the torchao Documentation](https://docs.pytorch.org/ao/stable/index.html)

### Vector Quantization Fine-tuning

Vector Quantization (VQ) Fine-tuning is an optimization strategy that treats model weights or hidden states as vectors in a multi-dimensional space. Instead of each parameter being an independent, high-precision number, the model learns to map these vectors to a discrete set of "representative" values stored in a codebook.

During adaptation (fine-tuning), the model optimizes this codebook alongside the task-specific updates. This allows the model to compress its knowledge into discrete "tokens" or "bins," making it significantly more efficient for storage and inference while "learning" the best way to represent the data in a low-bit format.

**How it Works**

Vector quantization operates by dividing a high-dimensional space into regions, each represented by a single "centroid" (codebook entry).
- Clustering: Large groups of weights are clustered together. All weights within a specific cluster are approximated by the same codebook vector.
- Codebook Learning: Unlike static quantization, where the "bins" are fixed, VQ Fine-tuning allows the codebook vectors themselves to shift during training. The model learns the optimal "representative" values for the specific task.
- The Straight-Through Estimator (STE): Since the mapping to a codebook is a discrete (non-differentiable) step, the model uses an STE to allow gradients to flow backward. It "pretends" the rounding didn't happen during the backward pass so the codebook and underlying weights can still be updated.

**Implemented Vector Quantization Fine-tuning**

The provided code actually does not implement true Vector Quantization. It uses LoRA (Low-Rank Adaptation), which is a different form of parameter-efficient fine-tuning (PEFT).

**1. The LoRA Approach**

    peft_config = LoraConfig(
        r=16, 
        target_modules=["q_proj", "k_proj", "v_proj", "o_proj"],
        ...
    )
    model = get_peft_model(model, peft_config)

In this script, the model keeps the base weights frozen and adds small, trainable low-rank matrices (Adapters).
- Base Weights: These remain in high precision (float32 as loaded in the script).
- Adapters: These learn the specific task (Question-Answering).
- VQ Missing Link: To perform VQ Fine-tuning, the code would need a specialized library (like AQLM or TorchAO) that replaces the standard linear layers with VQ-specific layers that maintain a trainable codebook. The current code simply uses standard LoRA on a full-precision model.

**When to Use It**

Vector Quantization Fine-tuning is most valuable in specialized deployment scenarios:
- Extreme Compression (2-bit or 3-bit): When standard rounding (scalar quantization) destroys model performance, VQ's ability to capture relationships between dimensions allows the model to remain accurate at extremely low bit-widths.
- High-Speed Similarity Search: In models used for retrieval (like RAG systems), VQ is used to compress embeddings into discrete codes, allowing for much faster nearest-neighbor searches.
- Hardware with Specialized Bit-width Support: If the target hardware (like certain NPUs) is optimized for codebook lookups rather than standard floating-point math.
- Multimodal Consistency: It is frequently used when aligning different types of data (like vision and language) into a unified discrete space so they can be processed by the same transformer architecture.

In [ ]:
from transformers import AutoTokenizer, AutoModelForCausalLM, TrainingArguments, Trainer, DataCollatorForLanguageModeling
from datasets import DatasetDict, Dataset
from peft import LoraConfig, get_peft_model

In [ ]:
# Configuration
MODEL_NAME = "google/gemma-3-270m"
OUTPUT_DIR = "./gemma-3-270m-finetuned-qa"

# Load base model
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    device_map="auto",
    torch_dtype="float32",
    low_cpu_mem_usage=True,
)

# Apply PEFT LoRA (parameter-efficient adaptation; closest standard PEFT method)
# For true learnable vector quantization / codebook learning during fine-tuning,
# a custom VQ layer wrapping linear layers would be needed (not built-in in PEFT).
peft_config = LoraConfig(
    r=16,                     # low rank
    lora_alpha=32,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj"],  # typical for Gemma-like models
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM"
)

model = get_peft_model(model, peft_config)

# Training setup
monitor = EpochMonitor(model=model)
data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    gradient_accumulation_steps=1,
    learning_rate=2e-5,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_strategy="epoch",
    run_name="gemma-3-270m-qa-lora",
    warmup_ratio=0.1,
    lr_scheduler_type="cosine",
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
    callbacks=[monitor],
)

print("Starting training...")
trainer.train()
trainer.save_model()
tokenizer.save_pretrained(OUTPUT_DIR)
print("Training completed!")

`torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors:   0%|          | 0.00/536M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/236 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/133 [00:00<?, ?B/s]

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Starting training...
Initial Model Memory Footprint:
  Parameters: 269,572,736
  Precision: 4 bytes
  Total Memory: 3.82 GB
    - Parameters: 1.00 GB
    - KV Cache (est): 2.81 GB
  Estimated FLOPs per forward pass (batch=8, seq=512): 2.05 TFLOPS

============================================================
Epoch 0 Summary
============================================================
  Duration (s)         :         35.43
  Tokens Processed     :       684,032
  Throughput (token/s) :         19306
  Training Steps       :           167
  Avg CPU (%)          :          18.4
  Avg Memory (%)       :          10.9
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          9.67
  FLOPs (per token)    :   0.50 GFLOPS

============================================================
Epoch 1 Summary
============================================================
  Duration (s)         :         36.41
  Tokens Processed     :       684,032
  Throughput (token/s) :         18787
  Training Steps       :           167
  Avg CPU (%)          :          23.5
  Avg Memory (%)       :          10.9
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          9.41
  FLOPs (per token)    :   0.50 GFLOPS

============================================================
Epoch 2 Summary
============================================================
  Duration (s)         :         36.77
  Tokens Processed     :       684,032
  Throughput (token/s) :         18604
  Training Steps       :           167
  Avg CPU (%)          :          22.0
  Avg Memory (%)       :          10.9
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          9.32
  FLOPs (per token)    :   0.50 GFLOPS

============================================================
TRAINING COMPLETE
============================================================
Total Training Time: 122.14s
Total Epochs: 3
Average Epoch Time: 36.20s
Total Tokens Processed: 2,052,096
Average Throughput: 16802 tokens/second
Total FLOPs: 1027.47 TFLOPS
Average TFLOPS (per second): 8.41
Overall FLOPs (per token): 0.50 GFLOPS

Final Metrics:
Memory Footprint: 3.82 GB
Inference Throughput: 19261 tokens/second
Total Training FLOPs: 342.49 TFLOPS
Training completed!

In [9]:
summarize_training_results(trainer, monitor)

====================================================================================================
TRAINING RESULTS SUMMARY TABLE
====================================================================================================
Epoch Training Loss Validation Loss Time (s) Tokens Processed Throughput (token/s) TFLOPS (per second) Avg CPU (%) Avg Memory (%) Training Steps
    0        3.0557          3.1405    35.43          684,032                19306                9.67        18.4           10.9            167
    1        2.8074          3.0806    36.41          684,032                18786                9.41        23.5           10.9            167
    2        2.7384          3.0729    36.77          684,032                18604                9.32        22.0           10.9            167

----------------------------------------------------------------------------------------------------
TRAINING STATISTICS:
----------------------------------------------------------------------------------------------------
Total Training Time:      108.6 s
Average Epoch Time:       36.2 s
Total Tokens Processed:   2,052,096
Average Throughput:       18894 tokens/second
Average CPU Usage:        21.3%
Average Memory Usage:     10.9%
Total Training FLOPs:     1027.47 TFLOPS
Average TFLOPS (per sec): 9.46
Overall FLOPs (per token): 0.50 GFLOPS

====================================================================================================

**Reference**
- [Arxiv:QEFT: Quantization for Efficient Fine-Tuning of LLMs](https://arxiv.org/html/2410.08661v1)
- [Huggingface:LoRA](https://huggingface.co/docs/peft/en/package_reference/lora)
- [Huggingface:Quantization](https://huggingface.co/docs/peft/en/developer_guides/quantization)

# PARAMETER-EFFICIENT FINE-TUNING (PEFT) (Fine-tuning)

Parameter-Efficient Fine-Tuning (PEFT) is a set of techniques used to adapt Large Language Models (LLMs) to specific tasks by updating only a tiny fraction (often less than 1%) of the model's total parameters.

In traditional "Full Fine-Tuning," every single weight in a massive model (like Llama or GPT) is adjusted. PEFT instead keeps the original model "frozen" and either adds small, trainable layers or only updates a few specific internal parameters.

**How PEFT Works**

Instead of rewriting the entire "brain" of the model, PEFT typically uses one of three approaches:
- Additive (Adapters): Tiny "expansion packs" are plugged into the existing model layers. Only these new layers are trained.
- Reparameterization (LoRA): Low-Rank Adaptation (LoRA) is the most popular PEFT method. It represents the weight changes as two small matrices that are multiplied together. This reduces the number of values to train from billions to just a few million.
- Selective: The model only trains specific parts of its existing structure, such as the "biases" or only the very last layer, while leaving everything else untouched.

**When to Use PEFT**

PEFT is the industry standard for most practical AI projects. You should choose it when:
- You Have Limited Hardware: If you don't have a massive cluster of high-end GPUs (like H100s), PEFT allows you to fine-tune models on consumer-grade hardware or even a single GPU.
- You Need to Save Money: Full fine-tuning is computationally expensive. PEFT can reduce training costs by 90% or more because it requires far less processing power.
- You Want to Avoid "Catastrophic Forgetting": When you fully retrain a model on a new task, it often "forgets" the general knowledge it learned during its initial training. PEFT keeps the original knowledge safe by freezing the base model.
- You are Deploying Many Models: Since PEFT only saves the "diff" (the small changes), the resulting files are megabytes rather than gigabytes. This makes it easy to store and switch between hundreds of different specialized models (e.g., one for legal, one for medical, one for coding) using the same base engine.
- You have a Small Dataset: If you only have a few hundred or thousand examples, full fine-tuning will almost certainly "overfit" (memorize the data rather than learning it). PEFT is much more robust with limited data.

## Low-Rank Adaptation (LoRA)

Low-Rank Adaptation (LoRA) is a parameter-efficient fine-tuning (PEFT) technique designed to adapt Large Language Models (LLMs) to specific tasks without retraining all of their parameters.

Instead of modifying the billions of weights in a foundation model (like Llama or Gemma), LoRA freezes the original weights and adds two small, trainable matrices—called Adapters—to the model's layers. This allows you to achieve performance comparable to full fine-tuning while only training a tiny fraction (often < 0.1%) of the parameters.

**How LoRA Works**

LoRA is based on the mathematical hypothesis that weight updates in a neural network have a "low intrinsic rank." In simpler terms, you don't need to change every weight to teach a model a new skill; you only need to change a small subset of them.
- Freeze the Base Model: All original weights ($W$) are "locked" and do not change during training.
- Rank Decomposition: For any layer that would normally be updated by a large matrix ($\Delta W$), LoRA breaks that update down into two much smaller matrices, $A$ and $B$.
    - If the original matrix is $1000 \times 1000$ (1,000,000 parameters), and you choose a Rank ($r$) of 8, matrix $A$ is $1000 \times 8$ and matrix $B$ is $8 \times 1000$.
    - Total parameters trained: $8,000 + 8,000 = 16,000$. (A 98.4% reduction in this example).
- The Forward Pass: During training, the model processes input by passing it through the frozen weights and the trainable adapters simultaneously. Their outputs are then added together.

**When to Use LoRA**

LoRA has become the "go-to" method for developers and researchers because it balances efficiency with power. Use it when:
- You Have Limited VRAM: LoRA significantly reduces the GPU memory required for training. You can fine-tune a 7B or 13B parameter model on a single consumer GPU (like an RTX 3090 or 4090) that would otherwise crash during full fine-tuning.
- You Need to Save/Share Many Models: A LoRA "adapter" file is usually only 10MB to 300MB, whereas a full model is 15GB to 100GB+. This makes it easy to store and share hundreds of specialized "mini-brains" for different tasks.
- You Want Zero-Latency Inference: Because of the math ($W + BA$), you can "merge" the LoRA weights back into the original model after training. This means the final model runs at exactly the same speed as the original, with no extra "adapter" overhead.
- You are Combatting "Catastrophic Forgetting": Since the original weights are never touched, the model is less likely to lose its foundational reasoning abilities while learning a new specific task (like medical diagnosis or legal document analysis).
- Rapid Prototyping: LoRA converges (finishes training) much faster than full fine-tuning because the optimizer only has to manage a few million variables instead of billions.

**Reference**
- [Arxiv:LoRA: Low-Rank Adaptation of Large Language Models](https://arxiv.org/abs/2106.09685)
- [Huggingface:LoRA (Low-Rank Adaptation)](https://huggingface.co/learn/llm-course/en/chapter11/4)
- [Huggingface:Low-Rank Adaptation of Large Language Models (LoRA)](https://huggingface.co/docs/diffusers/v0.23.1/training/lora)
- [Huggingface:Quantization](https://huggingface.co/docs/peft/en/developer_guides/quantization)

### QLoRA

QLoRA (Quantized Low-Rank Adaptation) is a highly efficient fine-tuning technique that reduces the memory required to train Large Language Models (LLMs) by up to 90%. It works by keeping the massive pre-trained model frozen in a specialized 4-bit format while training tiny, high-precision adapter layers (LoRA) on top of it.

This breakthrough allows a single consumer-grade GPU (like an RTX 3090 or 4090) to fine-tune models with 70 billion parameters, a task that previously required massive industrial server clusters.

**How it Works**

QLoRA achieves its efficiency through three core technical innovations:
- 4-bit NormalFloat (NF4): This is a specialized data type optimized for neural network weights, which usually follow a normal distribution. Unlike standard 4-bit integers, NF4 preserves more information, ensuring that the "compressed" model loses almost no accuracy compared to a full 16-bit model.
- Double Quantization: QLoRA even quantizes the "scaling factors" used in the first layer of quantization. This saves an additional 0.37 bits per parameter, which adds up to gigabytes of saved VRAM on larger models.
- Paged Optimizers: This feature uses NVIDIA Unified Memory to handle sudden memory spikes. If the GPU runs out of VRAM, the optimizer state is temporarily moved to the CPU RAM and then brought back when needed, preventing "Out of Memory" (OOM) crashes.

**Implements QLoRA**

The script uses the BitsAndBytes and PEFT libraries to orchestrate the transition from a heavy 16-bit model to an agile 4-bit training setup.

**1. The 4-bit Foundation**

    bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_use_double_quant=True,
    )

This block sets up the "NormalFloat" and "Double Quantization" described above. When the model loads with this config, its multi-gigabyte weight matrices are instantly compressed into the 4-bit NF4 format.

**2. Preparing for Low-Bit Training**

    model = prepare_model_for_kbit_training(model)

Standard PyTorch layers aren't built to handle gradients while frozen in 4-bit. This function wraps the model, enabling features like Gradient Checkpointing and ensuring that the inputs to the layers remain in a high-precision format (like Float16) so the math stays accurate.

**3. Injecting the Trainable Adapters**

    model = get_peft_model(model, lora_config)

Even though the base Gemma-3 weights are now frozen in 4-bit, this line injects trainable LoRA matrices into the target modules. During training, only these tiny adapters are updated. The `paged_adamw_8bit` optimizer ensures that the memory used for these updates is managed as efficiently as possible.

**When to Use It**

QLoRA is the gold standard for "Democratic AI"—training powerful models on accessible hardware. Use it when:
- Hardware is the Bottleneck: If you need to train a model that is larger than your GPU's total VRAM (e.g., training a 30B model on a 24GB GPU).
- Speed and Cost are Critical: QLoRA is significantly cheaper to run on cloud providers because you can rent lower-tier GPUs while still achieving state-of-the-art results.
- Accuracy Cannot be Sacrificed: Research has shown that QLoRA matches the performance of 16-bit LoRA and even full fine-tuning in most benchmarks.
- Personal or Private Data: Because it runs on consumer hardware, you can fine-tune your own local model on private data without ever uploading it to the cloud.

In [ ]:
import torch
from datasets import Dataset, DatasetDict
from transformers import (
    AutoTokenizer, 
    AutoModelForCausalLM,
    DataCollatorForLanguageModeling,
    Trainer,
    TrainingArguments,
    BitsAndBytesConfig
)
from peft import LoraConfig, get_peft_model, TaskType, prepare_model_for_kbit_training

In [ ]:
# Configuration
MODEL_NAME = "google/gemma-3-270m"   
OUTPUT_DIR = "./gemma-3-270m-finetuned-qa-qlora"

# Configure 4-bit quantization (QLoRA standard)
print("Configuring QLoRA 4-bit quantization...")
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",  # NormalFloat4
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,  # Double quantization for memory efficiency
)

# Load model with QLoRA quantization
print(f"Loading {MODEL_NAME} with QLoRA quantization...")
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    quantization_config=bnb_config,
    device_map="auto",
    torch_dtype=torch.float16,
    trust_remote_code=True,
    low_cpu_mem_usage=True
)

# Prepare model for k-bit training
model = prepare_model_for_kbit_training(model)

# Configure LoRA adapters
print("Configuring LoRA adapters...")
lora_config = LoraConfig(
    task_type=TaskType.CAUSAL_LM,
    r=64,  # LoRA rank
    lora_alpha=16,  # LoRA alpha
    lora_dropout=0.1,  # Dropout for LoRA layers
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
    bias="none",
    modules_to_save=["lm_head", "embed_tokens"]  # These layers stay trainable
)

# Apply LoRA to the quantized model
model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

# Training setup
monitor = EpochMonitor(model=model)
data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    gradient_accumulation_steps=4,  # Increased for memory efficiency
    learning_rate=1e-4,  # Lower learning rate for 4-bit training
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_strategy="epoch",
    run_name="gemma-3-270m-qa-qlora",
    warmup_ratio=0.1,
    lr_scheduler_type="cosine",
    fp16=True,
    bf16=False,
    gradient_checkpointing=True,
    optim="paged_adamw_8bit"  # Optimizer for 8-bit training
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
    callbacks=[monitor]
)

total_params = sum(p.numel() for p in model.parameters())
trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
non_trainable_params = total_params - trainable_params

print(f"Total parameters: {total_params:,}")
print(f"Trainable parameters: {trainable_params:,}")
print(f"Non-trainable parameters: {non_trainable_params:,}")
print(f"Trainable %: {100 * trainable_params / total_params:.2f}%")
print(f"Batch size: {training_args.per_device_train_batch_size}")
print("Starting QLoRA training...")

train_result = trainer.train()

# Save the adapters (not the full model)
model.save_pretrained(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)

print("QLoRA training completed!")

Configuring QLoRA 4-bit quantization...
Loading google/gemma-3-270m with QLoRA quantization...

Loading weights:   0%|          | 0/236 [00:00<?, ?it/s]

Configuring LoRA adapters...

/usr/local/lib/python3.11/dist-packages/peft/tuners/tuners_utils.py:1225: UserWarning: Model has `tie_word_embeddings=True` and a tied layer is part of the adapter, but `ensure_weight_tying` is not set to True. This can lead to complications, for example when merging the adapter or converting your model to formats other than safetensors. Check the discussion here: https://github.com/huggingface/peft/issues/2777
  warnings.warn(msg)
warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 350,732,288 || all params: 618,830,464 || trainable%: 56.6766
Total parameters: 568,695,424
Trainable parameters: 350,732,288
Non-trainable parameters: 217,963,136
Trainable %: 61.67%
Batch size: 8
Starting QLoRA training...
Initial Model Memory Footprint:
  Parameters: 568,695,424
  Precision: 4 bytes
  Total Memory: 4.93 GB
    - Parameters: 2.12 GB
    - KV Cache (est): 2.81 GB
  Estimated FLOPs per forward pass (batch=8, seq=512): 2.05 TFLOPS

============================================================
Epoch 0 Summary
============================================================
  Duration (s)         :        62.48
  Tokens Processed     :      172,032
  Throughput (token/s) :         2754
  Training Steps       :           42
  Avg CPU (%)          :         23.6
  Avg Memory (%)       :         11.4
  Total FLOPs          : 86.14 TFLOPS
  TFLOPS (per second)  :         1.38
  FLOPs (per token)    :  0.50 GFLOPS

============================================================
Epoch 1 Summary
============================================================
  Duration (s)         :        64.91
  Tokens Processed     :      172,032
  Throughput (token/s) :         2650
  Training Steps       :           42
  Avg CPU (%)          :         23.4
  Avg Memory (%)       :         15.0
  Total FLOPs          : 86.14 TFLOPS
  TFLOPS (per second)  :         1.33
  FLOPs (per token)    :  0.50 GFLOPS

============================================================
Epoch 2 Summary
============================================================
  Duration (s)         :        62.25
  Tokens Processed     :      172,032
  Throughput (token/s) :         2764
  Training Steps       :           42
  Avg CPU (%)          :         22.3
  Avg Memory (%)       :         15.1
  Total FLOPs          : 86.14 TFLOPS
  TFLOPS (per second)  :         1.38
  FLOPs (per token)    :  0.50 GFLOPS

============================================================
TRAINING COMPLETE
============================================================
Total Training Time: 221.46s
Total Epochs: 3
Average Epoch Time: 63.21s
Total Tokens Processed: 516,096
Average Throughput: 2330 tokens/second
Total FLOPs: 258.41 TFLOPS
Average TFLOPS (per second): 1.17
Overall FLOPs (per token): 0.50 GFLOPS

Final Metrics:
Memory Footprint: 4.93 GB
Inference Throughput: 2803 tokens/second
Total Training FLOPs: 86.14 TFLOPS
QLoRA training completed!

In [11]:
summarize_training_results(trainer, monitor)

====================================================================================================
TRAINING RESULTS SUMMARY TABLE
====================================================================================================
Epoch Training Loss Validation Loss Time (s) Tokens Processed Throughput (token/s) TFLOPS (per second) Avg CPU (%) Avg Memory (%) Training Steps
    0        2.8462          3.3099    62.48          172,032                 2753                1.38        23.6           11.4             42
    1        1.7327          3.6533    64.91          172,032                 2650                1.33        23.4           15.0             42
    2        1.3354          3.8558    62.25          172,032                 2763                1.38        22.3           15.1             42

----------------------------------------------------------------------------------------------------
TRAINING STATISTICS:
----------------------------------------------------------------------------------------------------
Total Training Time:      189.6 s
Average Epoch Time:       63.2 s
Total Tokens Processed:   516,096
Average Throughput:       2722 tokens/second
Average CPU Usage:        23.1%
Average Memory Usage:     13.8%
Total Training FLOPs:     258.41 TFLOPS
Average TFLOPS (per sec): 1.36
Overall FLOPs (per token): 0.50 GFLOPS

====================================================================================================

**Reference** 
- [Arxiv:QLoRA: Efficient Finetuning of Quantized LLMs](https://arxiv.org/abs/2305.14314)
- [Arxiv:Profiling LoRA/QLoRA Fine-Tuning Efficiency on Consumer GPUs: An RTX 4060 Case Study](https://arxiv.org/abs/2509.12229)
- [Huggingface:Making LLMs even more accessible with bitsandbytes, 4-bit quantization and QLoRA](https://huggingface.co/blog/4bit-transformers-bitsandbytes)
- [Huggingface:QLoRA: Efficient Finetuning of Quantized LLMs](https://huggingface.co/papers/2305.14314)
- [Huggingface:LoRA](https://huggingface.co/docs/peft/en/package_reference/lora)
- [Huggingface:Quantization](https://huggingface.co/docs/peft/en/developer_guides/quantization)

### Double Quantization

Double Quantization is an advanced memory-saving technique introduced with QLoRA that reduces the memory overhead of the "quantization constants" themselves.

When a model is quantized (e.g., to 4-bit), the weights are divided into small groups called blocks. Each block requires a high-precision "scaling factor" (constant) to map the low-bit integers back to their original value range. While the weights are heavily compressed, storing thousands of these high-precision constants still consumes significant VRAM. Double Quantization treats these constants as data and performs a second round of quantization on them, shrinking their memory footprint even further.

**How it Works**

Double Quantization acts like a "compression of the compressor."
- Primary Quantization (Weight Level): The model weights are grouped into blocks (typically of size 64). Each block is quantized to 4-bit, and a 32-bit floating-point quantization constant is calculated to represent the scale of that block.
- The "Constant Overhead" Problem: If a model has 70 billion parameters and uses a block size of 64, it will have over 1 billion constants. Storing these at 32-bit adds approximately 0.5 bits per parameter to the total memory usage.
- Secondary Quantization (Constant Level): Double Quantization takes these 32-bit constants and groups them into larger blocks (typically of size 256). It then quantizes these constants down to 8-bit.
- Resulting Savings: By quantizing the constants, the overhead drops from 0.5 bits per parameter to roughly 0.127 bits per parameter. This saves hundreds of megabytes or even gigabytes of VRAM on large models without impacting accuracy.

**Implements Double Quantization**

The script uses the bitsandbytes library via the `BitsAndBytesConfig` to automate this nested process.

**1. Activating Nested Quantization**

    bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_quant_type="nf4",      # 4-bit NormalFloat
        bnb_4bit_use_double_quant=True, # <--- ENABLES DOUBLE QUANTIZATION
        bnb_4bit_compute_dtype=torch.float16,
    )

The parameter `bnb_4bit_use_double_quant=True` is the "on switch." When the model is loaded, `bitsandbytes` doesn't just convert the weights to 4-bit; it immediately scans the resulting scaling factors and applies the secondary 8-bit quantization to them.

**2. Memory-Efficient Training**

    model = prepare_model_for_kbit_training(model)

Because the weights and their constants are now deeply compressed, the model cannot be trained directly. This function ensures that during the training steps, the necessary parts of the model are "de-quantized" on-the-fly into float16 for calculation and then discarded. The Double Quantization remains active for the stored version of the model throughout the entire training process, keeping the VRAM usage at its absolute minimum.

**When to Use It**

Double Quantization is a "free" memory optimization that should be used in almost all QLoRA scenarios:
- Tuning 70B+ Models on Consumer GPUs: This is the primary use case. On a 70B model, Double Quantization saves about 3GB of VRAM. This can be the difference between a model fitting on a 48GB GPU (like an A6000) or crashing with an "Out of Memory" error.
- Maximizing Batch Size: Even on smaller models like Gemma-3-270m, saving bits on constants frees up VRAM that can be used to increase the `per_device_train_batch_size`. Larger batches lead to more stable training and faster convergence.
- Long Context Windows: If training involves very long sequences (e.g., 8k or 16k tokens), the KV-cache consumes massive amounts of memory. Double Quantization offsets some of the weight memory to make more room for these long sequences.
- Fine-Tuning in Resource-Constrained Environments: When using free-tier cloud GPUs (like those with 15-16GB VRAM), every megabyte counts. Double Quantization provides that extra breathing room.

In [ ]:
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    TrainingArguments,
    Trainer,
    DataCollatorForLanguageModeling,
    BitsAndBytesConfig,
)
from datasets import Dataset, DatasetDict
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training

In [ ]:
# Configuration
MODEL_NAME = "google/gemma-3-270m"
OUTPUT_DIR = "./gemma-3-270m-finetuned-qa-double-quant"

# Load tokenizer
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
tokenizer.pad_token = tokenizer.eos_token

# Tokenization function
def tokenize_examples(df, max_length=MAX_LENGTH):
    texts = [
        f"""<bos>Question: {row['question_title']}
{row['question_body']}
Answer: {row['answer']}<eos>"""
        for row in df.iter_rows(named=True)
    ]
    tokenized = tokenizer(
        texts,
        truncation=True,
        max_length=max_length,
        padding="max_length",
        return_tensors="pt"
    )
    tokenized["labels"] = tokenized["input_ids"].clone()
    return tokenized

train_tokenized = tokenize_examples(train_data)
val_tokenized = tokenize_examples(val_data)

dataset_dict = DatasetDict({
    "train": Dataset.from_dict({
        "input_ids": train_tokenized["input_ids"],
        "attention_mask": train_tokenized["attention_mask"],
        "labels": train_tokenized["labels"]
    }),
    "validation": Dataset.from_dict({
        "input_ids": val_tokenized["input_ids"],
        "attention_mask": val_tokenized["attention_mask"],
        "labels": val_tokenized["labels"]
    })
})

# 4-bit double quantization config (NF4 + nested quant)
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
)

# Load quantized base model
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    quantization_config=bnb_config,
    device_map="auto",
    torch_dtype=torch.float16,
    low_cpu_mem_usage=True,
)

# Prepare for k-bit training + attach LoRA adapters (QLoRA)
model = prepare_model_for_kbit_training(model)
peft_config = LoraConfig(
    r=16,
    lora_alpha=32,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj"],  # typical for Gemma
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM",
)
model = get_peft_model(model, peft_config)

# Training setup
monitor = EpochMonitor(model=model)
data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    gradient_accumulation_steps=1,
    learning_rate=2e-5,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_strategy="epoch",
    run_name="gemma-3-270m-qa-qlora",
    warmup_ratio=0.1,
    lr_scheduler_type="cosine",
    fp16=True,
    gradient_checkpointing=True,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
    callbacks=[monitor],
)

print("Starting QLoRA training with double quantization...")
trainer.train()
trainer.save_model()
tokenizer.save_pretrained(OUTPUT_DIR)
print("Training completed!")

Loading weights:   0%|          | 0/236 [00:00<?, ?it/s]

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Starting QLoRA training with double quantization...
Initial Model Memory Footprint:
  Parameters: 219,437,696
  Precision: 4 bytes
  Total Memory: 3.63 GB
    - Parameters: 0.82 GB
    - KV Cache (est): 2.81 GB
  Estimated FLOPs per forward pass (batch=8, seq=512): 2.05 TFLOPS

============================================================
Epoch 0 Summary
============================================================
  Duration (s)         :         51.18
  Tokens Processed     :       684,032
  Throughput (token/s) :         13366
  Training Steps       :           167
  Avg CPU (%)          :          23.3
  Avg Memory (%)       :          16.3
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          6.69
  FLOPs (per token)    :   0.50 GFLOPS

============================================================
Epoch 1 Summary
============================================================
  Duration (s)         :         50.82
  Tokens Processed     :       684,032
  Throughput (token/s) :         13459
  Training Steps       :           167
  Avg CPU (%)          :          21.5
  Avg Memory (%)       :          16.3
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          6.74
  FLOPs (per token)    :   0.50 GFLOPS

============================================================
Epoch 2 Summary
============================================================
  Duration (s)         :         51.37
  Tokens Processed     :       684,032
  Throughput (token/s) :         13315
  Training Steps       :           167
  Avg CPU (%)          :          22.3
  Avg Memory (%)       :          16.3
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          6.67
  FLOPs (per token)    :   0.50 GFLOPS

============================================================
TRAINING COMPLETE
============================================================
Total Training Time: 165.69s
Total Epochs: 3
Average Epoch Time: 51.13s
Total Tokens Processed: 2,052,096
Average Throughput: 12385 tokens/second
Total FLOPs: 1027.47 TFLOPS
Average TFLOPS (per second): 6.20
Overall FLOPs (per token): 0.50 GFLOPS

Final Metrics:
Memory Footprint: 3.63 GB
Inference Throughput: 13864 tokens/second
Total Training FLOPs: 342.49 TFLOPS
Training completed!

In [13]:
summarize_training_results(trainer, monitor)

====================================================================================================
TRAINING RESULTS SUMMARY TABLE
====================================================================================================
Epoch Training Loss Validation Loss Time (s) Tokens Processed Throughput (token/s) TFLOPS (per second) Avg CPU (%) Avg Memory (%) Training Steps
    0        3.2209          3.3025    51.18          684,032                13365                6.69        23.3           16.3            167
    1        2.9412          3.2499    50.82          684,032                13458                6.74        21.5           16.3            167
    2        2.8693          3.2437    51.37          684,032                13314                6.67        22.3           16.3            167

----------------------------------------------------------------------------------------------------
TRAINING STATISTICS:
----------------------------------------------------------------------------------------------------
Total Training Time:      153.4 s
Average Epoch Time:       51.1 s
Total Tokens Processed:   2,052,096
Average Throughput:       13379 tokens/second
Average CPU Usage:        22.4%
Average Memory Usage:     16.3%
Total Training FLOPs:     1027.47 TFLOPS
Average TFLOPS (per sec): 6.70
Overall FLOPs (per token): 0.50 GFLOPS

====================================================================================================

**Reference** 
- [Arxiv:Double Quantization](https://arxiv.org/pdf/2112.11401)
- [Huggingface:Quantization](https://huggingface.co/docs/transformers/en/main_classes/quantization)
- [Huggingface:LoRA](https://huggingface.co/docs/peft/en/package_reference/lora)

### Paged QLoRA

Paged QLoRA is an enhancement of the QLoRA framework designed to handle intermittent memory spikes during training. It utilizes NVIDIA Unified Memory to prevent "Out of Memory" (OOM) errors that occur when processing long sequences or large batches.

When the GPU reaches its memory limit, Paged QLoRA automatically offloads parts of the optimizer states to the CPU RAM (acting as a "page file") and brings them back to the GPU only when they are needed for a calculation. This ensures that training can continue uninterrupted, even if the total memory required for a specific step briefly exceeds the physical VRAM available on the GPU.

**How it Works**

Paged QLoRA mimics the "virtual memory" system found in standard operating systems.
- Unified Memory Mapping: The system treats the GPU VRAM and CPU RAM as a single, unified memory pool.
- Optimizer State Management: In LLM training, the optimizer states (like the running averages of gradients in AdamW) often consume more memory than the model weights themselves. Paged QLoRA specifically targets these states for paging.
- Dynamic Eviction: During the forward or backward pass, if a memory spike occurs (common with long text inputs), the system "evicts" inactive pages of optimizer data from the GPU to the CPU.
- On-Demand Retrieval: When it is time to update the weights, the paged data is moved back from the CPU to the GPU. While this transfer introduces a slight speed penalty, it prevents the entire training process from crashing.

**Implements Paged QLoRA**

The script enables this behavior primarily through the selection of a specialized optimizer in the training arguments.

**1. Selecting the Paged Optimizer**

    training_args = TrainingArguments(
        ...
        optim="paged_adamw_8bit",  # Enables Paged Memory + 8-bit Optimizer
    )

The string "`paged_adamw_8bit`" is the key.
- `paged`: This tells the bitsandbytes library to use NVIDIA's Unified Memory for the optimizer states.
- `adamw`: This is the standard optimizer used for LLMs.
- `8bit`: This further compresses the optimizer states from 32-bit to 8-bit, providing a dual layer of memory efficiency before paging even begins.

**2. Support for Memory Spikes**

    gradient_checkpointing=True,

By combining the paged optimizer with `gradient_checkpointing`, the model significantly reduces the memory needed for intermediate "activations." When these two features work together, the model is much more resilient to the high VRAM demands of processing long `MAX_LENGTH` sequences.

**When to Use It**

Paged QLoRA is a "safety net" optimization that is essential in specific hardware-limited scenarios:
- Processing Long Sequences: Use it when your training data includes long documents (e.g., 2048+ tokens). Long sequences cause massive memory spikes that are difficult to predict; paging handles these spikes gracefully.
- Hardware with Low VRAM: If you are trying to squeeze a large model adaptation (like a 30B or 70B parameter model) onto a 24GB or 48GB GPU, paging allows you to cross the finish line where standard training would fail.
- Maximizing Throughput: It allows you to push the per_device_train_batch_size to the absolute limit. Instead of leaving a "buffer" of VRAM to avoid crashes, you can fill the GPU and rely on paging to handle occasional overflows.
- Unstable Training Environments: In multi-tenant environments (like shared cloud instances) where VRAM availability might fluctuate, paging provides an extra layer of stability.

In [ ]:
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    TrainingArguments,
    Trainer,
    DataCollatorForLanguageModeling,
    BitsAndBytesConfig,
)
from datasets import DatasetDict, Dataset
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training

In [ ]:
# Configuration
MODEL_NAME = "google/gemma-3-270m"
OUTPUT_DIR = "./gemma-3-270m-finetuned-qa-paged-qlora"

# 4-bit quantization config (double quant enabled)
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
)

# Load quantized base model
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    quantization_config=bnb_config,
    device_map="auto",
    torch_dtype=torch.float16,
    low_cpu_mem_usage=True,
)

# Prepare for k-bit training + apply LoRA (Paged QLoRA setup)
model = prepare_model_for_kbit_training(model)
peft_config = LoraConfig(
    r=16,
    lora_alpha=32,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj"],
    lora_dropout=0.05,
    bias="none",
    task_type="CAUSAL_LM"
)
model = get_peft_model(model, peft_config)

# Training setup with paged optimizer
monitor = EpochMonitor(model=model)
data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    gradient_accumulation_steps=1,
    learning_rate=2e-5,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_strategy="epoch",
    run_name="gemma-3-270m-qa-paged-qlora",
    warmup_ratio=0.1,
    lr_scheduler_type="cosine",
    fp16=True,
    gradient_checkpointing=True,
    optim="paged_adamw_8bit",           # enables PagedAdamW (8-bit states paged to CPU when needed)
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
    callbacks=[monitor],
)

print("Starting Paged QLoRA training...")
trainer.train()
trainer.save_model()
tokenizer.save_pretrained(OUTPUT_DIR)
print("Training completed!")

Loading weights:   0%|          | 0/236 [00:00<?, ?it/s]

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Starting Paged QLoRA training...
Initial Model Memory Footprint:
  Parameters: 219,437,696
  Precision: 4 bytes
  Total Memory: 3.63 GB
    - Parameters: 0.82 GB
    - KV Cache (est): 2.81 GB
  Estimated FLOPs per forward pass (batch=8, seq=512): 2.05 TFLOPS

============================================================
Epoch 0 Summary
============================================================
  Duration (s)         :         51.24
  Tokens Processed     :       684,032
  Throughput (token/s) :         13349
  Training Steps       :           167
  Avg CPU (%)          :          21.2
  Avg Memory (%)       :          16.5
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          6.68
  FLOPs (per token)    :   0.50 GFLOPS

============================================================
Epoch 1 Summary
============================================================
  Duration (s)         :         52.33
  Tokens Processed     :       684,032
  Throughput (token/s) :         13073
  Training Steps       :           167
  Avg CPU (%)          :          26.7
  Avg Memory (%)       :          16.5
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          6.55
  FLOPs (per token)    :   0.50 GFLOPS

============================================================
Epoch 2 Summary
============================================================
  Duration (s)         :         51.61
  Tokens Processed     :       684,032
  Throughput (token/s) :         13253
  Training Steps       :           167
  Avg CPU (%)          :          20.4
  Avg Memory (%)       :          16.5
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          6.64
  FLOPs (per token)    :   0.50 GFLOPS

============================================================
TRAINING COMPLETE
============================================================
Total Training Time: 167.26s
Total Epochs: 3
Average Epoch Time: 51.73s
Total Tokens Processed: 2,052,096
Average Throughput: 12269 tokens/second
Total FLOPs: 1027.47 TFLOPS
Average TFLOPS (per second): 6.14
Overall FLOPs (per token): 0.50 GFLOPS

Final Metrics:
Memory Footprint: 3.63 GB
Inference Throughput: 13737 tokens/second
Total Training FLOPs: 342.49 TFLOPS
Training completed!

In [15]:
summarize_training_results(trainer, monitor)

====================================================================================================
TRAINING RESULTS SUMMARY TABLE
====================================================================================================
Epoch Training Loss Validation Loss Time (s) Tokens Processed Throughput (token/s) TFLOPS (per second) Avg CPU (%) Avg Memory (%) Training Steps
    0        3.2309          3.3036    51.24          684,032                13349                6.68        21.2           16.5            167
    1        2.9382          3.2469    52.33          684,032                13072                6.55        26.7           16.5            167
    2        2.8587          3.2386    51.61          684,032                13252                6.64        20.4           16.5            167

----------------------------------------------------------------------------------------------------
TRAINING STATISTICS:
----------------------------------------------------------------------------------------------------
Total Training Time:      155.2 s
Average Epoch Time:       51.7 s
Total Tokens Processed:   2,052,096
Average Throughput:       13224 tokens/second
Average CPU Usage:        22.8%
Average Memory Usage:     16.5%
Total Training FLOPs:     1027.47 TFLOPS
Average TFLOPS (per sec): 6.62
Overall FLOPs (per token): 0.50 GFLOPS

====================================================================================================

**Reference** 
- [Arxiv:QLORA: Efficient Finetuning of Quantized LLMs](https://arxiv.org/pdf/2305.14314)
- [Huggingface:QLoRA: Efficient Finetuning of Quantized LLMs](https://huggingface.co/papers/2305.14314)
- [APXML:Paged Optimizers for Memory Efficiency](https://apxml.com/courses/lora-peft-efficient-llm-training/chapter-4-advanced-lora-variants/qlora-paged-optimizers)
- [Huggingface:LoRA](https://huggingface.co/docs/peft/en/package_reference/lora)
- [Huggingface:Quantization](https://huggingface.co/docs/peft/en/developer_guides/quantization)

### DoRA (Weight-Decomposed Low-Rank Adaptation)

DoRA (Weight-Decomposed Low-Rank Adaptation) is a parameter-efficient fine-tuning technique that enhances standard LoRA by mimicking the learning behavior of full fine-tuning more closely. While standard LoRA adds a low-rank update to the weights, DoRA decomposes the weight matrix into two components: magnitude and direction. It then applies LoRA-style updates specifically to the directional component, allowing the model to optimize these two properties independently.

**How it Works**

The fundamental principle of DoRA is based on weight normalization. It separates the weight matrix $W$ into a magnitude vector $m$ and a directional matrix $V$.
- Mathematical Decomposition: A weight matrix is represented as $W = m \frac{V}{||V||_p}$, where $m$ is a learnable magnitude vector and $V$ is the directional matrix.
- Directional Adaptation: DoRA freezes the pre-trained weights as the base for $V$ and adds a trainable LoRA adapter ($BA$) to it. The update formula becomes:$$W' = m \frac{W_0 + BA}{||W_0 + BA||_p}$$
- Learning Stability: In standard LoRA, magnitude and direction are updated together in a coupled way, which often differs from how full fine-tuning behaves. By separating them, DoRA allows the model to adjust how "strong" a feature is (magnitude) without necessarily changing the "logic" of the feature (direction), and vice versa.

**Implements DoRA**

The provided code uses the PEFT library to apply DoRA on top of a 4-bit quantized Gemma-3-270m model.

**Enabling the Decomposition:**

    use_dora=True

Inside the `LoraConfig`, this flag tells the library to move beyond simple additive updates. It initializes a learnable magnitude vector $m$ that matches the dimensions of the target layers.

**Targeting Specific Modules:**

    target_modules=["q_proj", "k_proj", "v_proj", "o_proj"]
    
The code applies the DoRA logic specifically to the attention layers. For each of these layers, the directional component will be adjusted by the low-rank matrices $A$ and $B$, while the magnitude vector $m$ is learned separately.

**Integration with QLoRA:**

The code loads the model in 4-bit (`load_in_4bit=True`). DoRA is highly compatible with quantization; it uses the high-precision LoRA adapters and magnitude vectors to "steer" the frozen, quantized base weights.

**Enhancements**

- Adaptive Magnitude Scaling: The magnitude vector $m$ allows the model to dynamically scale the importance of specific neurons or channels. This is much more flexible than LoRA, which lacks a dedicated scaling component for individual weight directions.
- Direction Orthogonalization: Because the update is normalized ($||V||_p$), the model naturally resists redundant weight updates, encouraging the adapters to learn unique, orthogonal directions for different tasks.
- Layer-Coupled DoRA: While not explicitly coded as a separate toggle here, DoRA inherently couples the adapter's learning to the underlying weight norm, ensuring that the scale of the update is always proportional to the original layer's strength.

**When to Use It**

DoRA is preferred over standard LoRA in scenarios where model quality cannot be compromised for efficiency:
- Closing the Accuracy Gap: If standard LoRA is underperforming compared to full fine-tuning on a specific benchmark, DoRA is the first alternative to try, as it often matches full-precision performance.
- Complex Reasoning and Coding: Tasks that require high precision and structural logic benefit from the more stable directional updates of DoRA.
- Low-Rank Constraints: If forced to use a very low rank (e.g., $r=4$ or $r=8$) to save memory, DoRA remains much more "expressive" and capable than a standard LoRA at that same rank.
- Fine-tuning Quantized Models: As seen in the code, DoRA is excellent for QLoRA setups because it compensates for the "stiffness" of 4-bit weights by providing better directional flexibility.

In [ ]:
import torch
from datasets import Dataset, DatasetDict
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    DataCollatorForLanguageModeling,
    Trainer,
    TrainingArguments,
    BitsAndBytesConfig
)
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training

In [ ]:
# Configuration
MODEL_NAME = "google/gemma-3-270m"
OUTPUT_DIR = "./gemma-3-270m-finetuned-qa-dora"

# Define the Quantization Config
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_use_double_quant=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16
)

# Load the model with the config
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    quantization_config=bnb_config, # Use quantization_config instead of load_in_4bit
    device_map="auto",             # Usually required for 4-bit loading
    low_cpu_mem_usage=True,
    torch_dtype=torch.float16
)

# Prepare for training
model = prepare_model_for_kbit_training(
    model,
    use_gradient_checkpointing=True
)

# Configure & apply DoRA
lora_config = LoraConfig(
    task_type="CAUSAL_LM",
    r=16,
    lora_alpha=32,
    lora_dropout=0.1,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj"],
    bias="none",
    use_dora=True
)

model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

# Training setup
monitor = EpochMonitor(model=model)
data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    gradient_accumulation_steps=1,
    learning_rate=2e-4,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_strategy="epoch",
    run_name="gemma-3-270m-qa-dora",
    warmup_ratio=0.1,
    lr_scheduler_type="cosine",
    fp16=True,
    gradient_checkpointing=True,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
    callbacks=[monitor],
)

print("Starting DoRA training...")
trainer.train()

# Save only adapters
model.save_pretrained(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)
print("DoRA training completed!")

`torch_dtype` is deprecated! Use `dtype` instead!

Loading weights:   0%|          | 0/236 [00:00<?, ?it/s]

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 1,513,728 || all params: 269,611,904 || trainable%: 0.5614
Starting DoRA training...
Initial Model Memory Footprint:
  Parameters: 219,476,864
  Precision: 4 bytes
  Total Memory: 3.63 GB
    - Parameters: 0.82 GB
    - KV Cache (est): 2.81 GB
  Estimated FLOPs per forward pass (batch=8, seq=512): 2.05 TFLOPS

============================================================
Epoch 0 Summary
============================================================
  Duration (s)         :         69.75
  Tokens Processed     :       684,032
  Throughput (token/s) :          9807
  Training Steps       :           167
  Avg CPU (%)          :          20.3
  Avg Memory (%)       :          10.4
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          4.91
  FLOPs (per token)    :   0.50 GFLOPS

============================================================
Epoch 1 Summary
============================================================
  Duration (s)         :         70.17
  Tokens Processed     :       684,032
  Throughput (token/s) :          9748
  Training Steps       :           167
  Avg CPU (%)          :          22.8
  Avg Memory (%)       :          10.5
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          4.88
  FLOPs (per token)    :   0.50 GFLOPS

============================================================
Epoch 2 Summary
============================================================
  Duration (s)         :         69.47
  Tokens Processed     :       684,032
  Throughput (token/s) :          9846
  Training Steps       :           167
  Avg CPU (%)          :          21.9
  Avg Memory (%)       :          10.5
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          4.93
  FLOPs (per token)    :   0.50 GFLOPS

============================================================
TRAINING COMPLETE
============================================================
Total Training Time: 226.36s
Total Epochs: 3
Average Epoch Time: 69.80s
Total Tokens Processed: 2,052,096
Average Throughput: 9066 tokens/second
Total FLOPs: 1027.47 TFLOPS
Average TFLOPS (per second): 4.54
Overall FLOPs (per token): 0.50 GFLOPS

Final Metrics:
Memory Footprint: 3.63 GB
Inference Throughput: 10158 tokens/second
Total Training FLOPs: 342.49 TFLOPS
DoRA training completed!

In [10]:
summarize_training_results(trainer, monitor)

====================================================================================================
TRAINING RESULTS SUMMARY TABLE
====================================================================================================
Epoch Training Loss Validation Loss Time (s) Tokens Processed Throughput (token/s) TFLOPS (per second) Avg CPU (%) Avg Memory (%) Training Steps
    0        2.7826          3.3499    69.75          684,032                 9807                4.91        20.3           10.4            167
    1        2.0238          4.1058    70.17          684,032                 9748                4.88        22.8           10.5            167
    2        1.6867          4.6155    69.47          684,032                 9846                4.93        21.9           10.5            167

----------------------------------------------------------------------------------------------------
TRAINING STATISTICS:
----------------------------------------------------------------------------------------------------
Total Training Time:      209.4 s
Average Epoch Time:       69.8 s
Total Tokens Processed:   2,052,096
Average Throughput:       9800 tokens/second
Average CPU Usage:        21.7%
Average Memory Usage:     10.5%
Total Training FLOPs:     1027.47 TFLOPS
Average TFLOPS (per sec): 4.91
Overall FLOPs (per token): 0.50 GFLOPS

====================================================================================================

**Reference** 
- [Arxiv:DoRA: Weight-Decomposed Low-Rank Adaptation](https://arxiv.org/abs/2402.09353)
- [Huggingface:DoRA: Weight-Decomposed Low-Rank Adaptation](https://huggingface.co/papers/2402.09353)
- [Huggingface:LoRA](https://huggingface.co/docs/peft/en/package_reference/lora)
- [Huggingface:Quantization](https://huggingface.co/docs/peft/en/developer_guides/quantization)

### VeRA (Vector-based Random Matrix Adaptation)

VeRA (Vector-based Random Matrix Adaptation) is a next-generation parameter-efficient fine-tuning (PEFT) technique that pushes the boundaries of LoRA's efficiency. While standard LoRA trains unique low-rank matrices for every layer, VeRA uses a single pair of frozen random matrices shared across the entire model. To adapt these shared matrices to specific layers, it trains only tiny scaling vectors.

This approach allows VeRA to update as few as 0.01% of a model's parameters, making it roughly 10x more parameter-efficient than standard LoRA while maintaining competitive performance.

**How it Works**

VeRA operates on the principle that pre-trained models have a "low intrinsic dimensionality"—meaning you don't need a massive amount of new information to steer them toward a new task.
- Shared Frozen Projections: A single pair of matrices, $A$ and $B$, is initialized randomly (using a fixed seed) and frozen. These matrices are shared across every layer of the LLM.
- Layer-Specific Scaling: Because every layer needs to do something slightly different, VeRA introduces two trainable diagonal matrices (vectors) per layer: $\Lambda_d$ and $\Lambda_b$.
- The Formula: The update to a weight matrix $W$ is calculated as:

$$\Delta W = \Lambda_b \cdot B \cdot A \cdot \Lambda_d$$

In this setup, only the vectors $\Lambda_b$ and $\Lambda_d$ change during training. The heavy lifting of the projection is done by the shared, frozen $A$ and $B$.
- No Storage Bloat: Since $A$ and $B$ are generated from a random seed (PRNG key), you don't even need to save them. You only save the seed and the tiny scaling vectors, resulting in adapter files that are mere kilobytes in size.

**Implements VeRA**

The script utilizes the VeraConfig from the Hugging Face PEFT library to apply this specialized reparameterization.

**1. The Random Seed Guarantee**

    vera_config = VeraConfig(
        r=128,
        projection_prng_key=42,  # Deterministic seed for shared matrices
        ...
    )
    
The `projection_prng_key` is the most critical part of VeRA. It ensures that the shared $A$ and $B$ matrices are initialized identically across all layers and can be perfectly reconstructed during inference without being stored in the checkpoint.

**2. Scaling at High Ranks**

    r=128,  # Higher r for VeRA

Because the scaling vectors are so small, VeRA can afford a much higher Rank (`r`) than LoRA. While a LoRA rank of 128 might be too memory-intensive for some GPUs, a VeRA rank of 128 or 512 is extremely lightweight because the matrices themselves aren't being trained or stored individually per layer.

**3. Training the "Lambdas"**

When `trainer.train()` is called, the gradients only flow to the scaling vectors (internally named `vera_lambda_d` and `vera_lambda_b`). The base model and the shared $A/B$ matrices remain untouched. This is why `model.print_trainable_parameters() `will show an incredibly low number of trainable variables compared to the total model size.

**When to Use It**

VeRA is the ideal choice when storage and multi-tenancy are the primary constraints:
- Massive Model Deployment: If you are managing a platform that serves thousands of custom-tuned models (e.g., one for every customer), VeRA allows you to store those "adapters" with almost zero storage cost.
- Extremely Limited VRAM: In scenarios where even LoRA's optimizer states (which scale with the number of trainable parameters) are too large for your GPU, VeRA's tiny parameter count minimizes the optimizer's memory footprint.
- Edge Devices: For mobile or IoT deployment, where memory and disk space are at a premium, VeRA's "reconstruct from seed" capability is a major advantage.
- Large Ranks for Complex Tasks: When a task requires a very "wide" adaptation (high rank) but you cannot afford the parameter explosion that normally comes with it.

In [7]:
import torch
from datasets import Dataset, DatasetDict
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    DataCollatorForLanguageModeling,
    Trainer,
    TrainingArguments
)
from peft import VeraConfig

In [8]:
# Configuration
MODEL_NAME = "google/gemma-3-270m"
OUTPUT_DIR = "./gemma-3-270m-finetuned-qa-dora"

# Configure VeRA
vera_config = VeraConfig(
    r=128,  # Higher r for VeRA
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
    projection_prng_key=42,  # Random seed for frozen matrices
    vera_dropout=0.1,
    d_initial=512,
)

# Load model and apply VeRA
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    device_map="auto",
    dtype=torch.float32,  # Use dtype instead of torch_dtype
    low_cpu_mem_usage=True,
)

model = get_peft_model(model, vera_config)
model.print_trainable_parameters()

# Training setup
monitor = EpochMonitor(model=model)
data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

training_args = TrainingArguments(
    output_dir="./gemma-3-270m-finetuned-qa-vera",
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    gradient_accumulation_steps=1,
    learning_rate=2e-4,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_strategy="epoch",
    run_name="gemma-3-270m-qa-vera",
    warmup_ratio=0.1,
    lr_scheduler_type="cosine",
    fp16=False,  # Disable mixed precision for stability
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
    callbacks=[monitor],
)

print("Starting VeRA training...")
trainer.train()
model.save_pretrained("./gemma-3-270m-finetuned-qa-vera")
tokenizer.save_pretrained("./gemma-3-270m-finetuned-qa-vera")
print("VeRA training completed!")

model.safetensors:   0%|          | 0.00/536M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/236 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/133 [00:00<?, ?B/s]

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 140,544 || all params: 268,238,720 || trainable%: 0.0524
Starting VeRA training...
Initial Model Memory Footprint:
  Parameters: 268,238,720
  Precision: 4 bytes
  Total Memory: 3.81 GB
    - Parameters: 1.00 GB
    - KV Cache (est): 2.81 GB
  Estimated FLOPs per forward pass (batch=8, seq=512): 2.05 TFLOPS

============================================================
Epoch 0 Summary
============================================================
  Duration (s)         :         41.81
  Tokens Processed     :       684,032
  Throughput (token/s) :         16362
  Training Steps       :           167
  Avg CPU (%)          :          17.9
  Avg Memory (%)       :          12.2
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          8.19
  FLOPs (per token)    :   0.50 GFLOPS

============================================================
Epoch 1 Summary
============================================================
  Duration (s)         :         44.47
  Tokens Processed     :       684,032
  Throughput (token/s) :         15381
  Training Steps       :           167
  Avg CPU (%)          :          21.9
  Avg Memory (%)       :          12.2
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          7.70
  FLOPs (per token)    :   0.50 GFLOPS

============================================================
Epoch 2 Summary
============================================================
  Duration (s)         :         44.54
  Tokens Processed     :       684,032
  Throughput (token/s) :         15358
  Training Steps       :           167
  Avg CPU (%)          :          18.6
  Avg Memory (%)       :          12.2
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          7.69
  FLOPs (per token)    :   0.50 GFLOPS

============================================================
TRAINING COMPLETE
============================================================
Total Training Time: 146.35s
Total Epochs: 3
Average Epoch Time: 43.61s
Total Tokens Processed: 2,052,096
Average Throughput: 14022 tokens/second
Total FLOPs: 1027.47 TFLOPS
Average TFLOPS (per second): 7.02
Overall FLOPs (per token): 0.50 GFLOPS

Final Metrics:
Memory Footprint: 3.81 GB
Inference Throughput: 15712 tokens/second
Total Training FLOPs: 342.49 TFLOPS
VeRA training completed!

In [9]:
summarize_training_results(trainer, monitor)

====================================================================================================
TRAINING RESULTS SUMMARY TABLE
====================================================================================================
Epoch Training Loss Validation Loss Time (s) Tokens Processed Throughput (token/s) TFLOPS (per second) Avg CPU (%) Avg Memory (%) Training Steps
    0        3.8831          4.6894    41.81          684,032                16362                8.19        17.9           12.2            167
    1        3.7558          4.4759    44.47          684,032                15380                7.70        21.9           12.2            167
    2        2.8541          4.4916    44.54          684,032                15357                7.69        18.6           12.2            167

----------------------------------------------------------------------------------------------------
TRAINING STATISTICS:
----------------------------------------------------------------------------------------------------
Total Training Time:      130.8 s
Average Epoch Time:       43.6 s
Total Tokens Processed:   2,052,096
Average Throughput:       15686 tokens/second
Average CPU Usage:        19.4%
Average Memory Usage:     12.2%
Total Training FLOPs:     1027.47 TFLOPS
Average TFLOPS (per sec): 7.85
Overall FLOPs (per token): 0.50 GFLOPS

====================================================================================================

**Reference** 
- [Arxiv:VeRA: Vector-based Random Matrix Adaptation](https://arxiv.org/abs/2310.11454)
- [Huggingface:VeRA: Vector-based Random Matrix Adaptation](https://huggingface.co/docs/peft/en/package_reference/vera)

### AdaLoRA

AdaLoRA (Adaptive Low-Rank Adaptation) is an advanced parameter-efficient fine-tuning technique that dynamically manages the "budget" of trainable parameters across different layers of a model. While standard LoRA assigns a fixed rank (r) to every layer, AdaLoRA recognizes that some layers are more critical for a specific task than others. It identifies high-importance layers and allocates them more rank (more parameters), while pruning the rank of less important layers.

**How it Works: Importance-Aware Pruning**

AdaLoRA treats the low-rank adaptation as a Singular Value Decomposition (SVD) problem. Instead of updating a single weight matrix, it decomposes the update into three parts: P, E, and Q, where E is a diagonal matrix of singular values.
- SVD-Based Parametrization: The weight update is represented as ΔW=PEQ. Here, E contains the "importance scores" for each rank.
- Importance Calculation: During training, AdaLoRA calculates the importance of each singular value based on its magnitude and the gradient of the loss function.
- Global Budgeting: The system maintains a global budget for the total number of ranks. Layers that show high gradients or large singular values retain their rank.
- Rank Pruning: Every few steps, the algorithm "prunes" (sets to zero) the least important singular values across the entire model. This effectively shrinks the rank of unimportant layers while keeping the parameters where they matter most.

**Implements AdaLoRA**

The script uses AdaLoraConfig to control the "life cycle" of the parameter budget.

**Initialization and Target Ranks:**

    init_r=12,
    target_r=8,

The model starts with a slightly higher rank (`init_r`) to allow for exploration. Over the course of training, it will prune down to an average `target_r`.

**The Pruning Schedule:**

    tinit=200,
    tfinal=1000,
    deltaT=10,

AdaLoRA doesn't prune immediately. It waits for tinit steps to gather importance statistics. Then, every `deltaT` (10) steps, it prunes singular values until it reaches tfinal steps. This gradual reduction ensures the model doesn't lose vital information too quickly.

**Beta Parameters:**

    beta1=0.85,
    beta2=0.85,

These are moving average coefficients used to smooth the importance scores over time, preventing the model from pruning a layer based on a single "noisy" training batch.

**When to Use It**

AdaLoRA is particularly powerful when training efficiency must be balanced with high performance on complex tasks:
- Heterogeneous Models: Use it for models where different layers serve vastly different functions (e.g., a transformer where early layers handle syntax and later layers handle semantics). AdaLoRA will find which of these is more relevant to your specific dataset.
- Limited Budget, High Complexity: When there is a strict memory or storage limit but the task (like coding or medical reasoning) is too complex for a very low, uniform rank.
- Deep Architectures: In very deep models (32+ layers), manually deciding which layers to tune is impossible. AdaLoRA automates this by "turning off" adapters in layers that don't contribute to the task.
- Preventing Overfitting: By pruning redundant parameters in layers that don't need them, AdaLoRA acts as a regularizer, often leading to better generalization on validation data compared to standard LoRA.

In [ ]:
from peft import AdaLoraConfig

import torch
from datasets import Dataset, DatasetDict
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    DataCollatorForLanguageModeling,
    Trainer,
    TrainingArguments,
)
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training

In [ ]:
# Configuration
MODEL_NAME = "google/gemma-3-270m"
OUTPUT_DIR = "./gemma-3-270m-finetuned-qa-dora"

# Configure AdaLoRA
adalora_config = AdaLoraConfig(
    init_r=12,
    target_r=8,
    beta1=0.85,
    beta2=0.85,
    tinit=200,
    tfinal=1000,
    deltaT=10,
    total_step=3000,  # ADDED: Total training steps required for AdaLoRA
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
    lora_alpha=32,
    lora_dropout=0.1,
    bias="none",
    task_type="CAUSAL_LM",
)

# Load model and apply AdaLoRA
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    device_map="auto",
    dtype=torch.float32,
    low_cpu_mem_usage=True,
)

model = get_peft_model(model, adalora_config)
model.print_trainable_parameters()

monitor = EpochMonitor(model=model)
data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

# Calculate total steps based on your dataset size
total_samples = len(dataset_dict["train"])
batch_size = 8
gradient_accumulation_steps = 1
epochs = 3

total_steps = (total_samples * epochs) // (batch_size * gradient_accumulation_steps)
print(f"Total training steps: {total_steps}")

training_args = TrainingArguments(
    output_dir="./gemma-3-270m-finetuned-qa-adalora",
    num_train_epochs=epochs,
    per_device_train_batch_size=batch_size,
    per_device_eval_batch_size=8,
    gradient_accumulation_steps=gradient_accumulation_steps,
    learning_rate=1e-4,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_strategy="epoch",
    run_name="gemma-3-270m-qa-adalora",
    warmup_ratio=0.1,
    lr_scheduler_type="cosine",
    fp16=False,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
    callbacks=[monitor],
)

print("Starting AdaLoRA training...")
trainer.train()
model.save_pretrained("./gemma-3-270m-finetuned-qa-adalora")
tokenizer.save_pretrained("./gemma-3-270m-finetuned-qa-adalora")
print("AdaLoRA training completed!")

Loading weights:   0%|          | 0/236 [00:00<?, ?it/s]

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 2,849,256 || all params: 270,947,558 || trainable%: 1.0516
Total training steps: 499
Starting AdaLoRA training...
Initial Model Memory Footprint:
  Parameters: 270,947,558
  Precision: 4 bytes
  Total Memory: 3.82 GB
    - Parameters: 1.01 GB
    - KV Cache (est): 2.81 GB
  Estimated FLOPs per forward pass (batch=8, seq=512): 2.05 TFLOPS

============================================================
Epoch 0 Summary
============================================================
  Duration (s)         :         48.21
  Tokens Processed     :       684,032
  Throughput (token/s) :         14188
  Training Steps       :           167
  Avg CPU (%)          :          27.0
  Avg Memory (%)       :          13.2
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          7.10
  FLOPs (per token)    :   0.50 GFLOPS

============================================================
Epoch 1 Summary
============================================================
  Duration (s)         :         48.70
  Tokens Processed     :       684,032
  Throughput (token/s) :         14047
  Training Steps       :           167
  Avg CPU (%)          :          26.3
  Avg Memory (%)       :          13.2
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          7.03
  FLOPs (per token)    :   0.50 GFLOPS

============================================================
Epoch 2 Summary
============================================================
  Duration (s)         :         48.45
  Tokens Processed     :       684,032
  Throughput (token/s) :         14118
  Training Steps       :           167
  Avg CPU (%)          :          22.3
  Avg Memory (%)       :          13.2
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          7.07
  FLOPs (per token)    :   0.50 GFLOPS

============================================================
TRAINING COMPLETE
============================================================
Total Training Time: 160.43s
Total Epochs: 3
Average Epoch Time: 48.45s
Total Tokens Processed: 2,052,096
Average Throughput: 12791 tokens/second
Total FLOPs: 1027.47 TFLOPS
Average TFLOPS (per second): 6.40
Overall FLOPs (per token): 0.50 GFLOPS

Final Metrics:
Memory Footprint: 3.82 GB
Inference Throughput: 14618 tokens/second
Total Training FLOPs: 342.49 TFLOPS
AdaLoRA training completed!

In [14]:
summarize_training_results(trainer, monitor)

====================================================================================================
TRAINING RESULTS SUMMARY TABLE
====================================================================================================
Epoch Training Loss Validation Loss Time (s) Tokens Processed Throughput (token/s) TFLOPS (per second) Avg CPU (%) Avg Memory (%) Training Steps
    0        3.9653          3.6094    48.21          684,032                14188                7.10        27.0           13.2            167
    1        3.0659          3.2016    48.70          684,032                14047                7.03        26.3           13.2            167
    2        2.8732          3.1864    48.45          684,032                14117                7.07        22.3           13.2            167

----------------------------------------------------------------------------------------------------
TRAINING STATISTICS:
----------------------------------------------------------------------------------------------------
Total Training Time:      145.4 s
Average Epoch Time:       48.5 s
Total Tokens Processed:   2,052,096
Average Throughput:       14117 tokens/second
Average CPU Usage:        25.2%
Average Memory Usage:     13.2%
Total Training FLOPs:     1027.47 TFLOPS
Average TFLOPS (per sec): 7.07
Overall FLOPs (per token): 0.50 GFLOPS

====================================================================================================

**Reference** 
- [Arxiv:AdaLoRA: Adaptive Budget Allocation for Parameter-Efficient Fine-Tuning](https://arxiv.org/abs/2303.10512)
- [Huggingface:AdaLoRA](https://huggingface.co/docs/peft/en/package_reference/adalora)
- [Huggingface:LoRA](https://huggingface.co/docs/peft/en/package_reference/lora)
- [Huggingface:Quantization](https://huggingface.co/docs/peft/en/developer_guides/quantization)

### LoRA+

LoRA+ is a performance-driven improvement to the standard Low-Rank Adaptation (LoRA) technique. It addresses a fundamental inefficiency in how standard LoRA trains: the use of a single learning rate for both matrices in the adapter pair.

Research discovered that the two matrices in a LoRA adapter (Matrix A and Matrix B) play very different roles and evolve at different speeds. Matrix A performs a random projection to reduce dimensionality, while Matrix B maps that representation back to the model's weight space. LoRA+ optimizes this by setting a significantly higher learning rate for Matrix A than for Matrix B, leading to faster convergence and better final accuracy.

**How it Works**

The core principle of LoRA+ is "feature learning" efficiency. In standard LoRA, the learning rate is often too small for Matrix A to learn meaningful features, or too large for Matrix B to stay stable.
- The Ratio ($\lambda$): LoRA+ introduces a ratio between the learning rates of the two adapter matrices. Typically, Matrix A is given a much higher learning rate than Matrix B (often 10x to 100x higher).
- Directional Guidance: By increasing the learning rate for Matrix A, the model can more quickly explore the "direction" of the weight update. Matrix B then acts as a stabilizer, refining the magnitude of that update at a slower, more precise pace.
- Stability: This decoupled approach prevents the gradients from becoming "stuck" in suboptimal local minima, which frequently happens when a single learning rate is applied to the entire low-rank bottleneck.

**Implements LoRA+**

While many PEFT techniques require a specific configuration object, LoRA+ is primarily implemented at the optimizer level.

**1. Differentiating Parameter Groups**

    def get_loraplus_optimizer(model):
        param_groups = []
        lr_A = 1e-3  # Higher LR for A matrices
        lr_B = 1e-5  # Lower LR for B matrices
        
        for name, param in model.named_parameters():
            if param.requires_grad:
                if 'lora_A' in name:
                    param_groups.append({'params': param, 'lr': lr_A})
                elif 'lora_B' in name:
                    param_groups.append({'params': param, 'lr': lr_B})
                    
The custom function `get_loraplus_optimizer` is the heart of the implementation. It iterates through all trainable parameters. When it finds a parameter belonging to a `lora_A` module (the down-projection), it assigns it a high learning rate (`1e-3`). When it finds a `lora_B` module (the up-projection), it assigns it a learning rate that is 100 times smaller (`1e-5`).

**2. Injecting the Optimizer**

    trainer.optimizer = get_loraplus_optimizer(model)

Instead of letting the Hugging Face `Trainer` create a default optimizer, the code manually overrides the trainer.optimizer attribute. This ensures that when training begins, the `AdamW` optimizer uses the specific per-parameter learning rates defined in the groups above.

**When to Use It**

LoRA+ is a highly effective "finisher" for LoRA-based projects and should be used when:
- Training Speed is a Priority: LoRA+ can reach the same level of accuracy as standard LoRA in significantly fewer training steps (often up to 2x faster convergence).
- Accuracy Gap Issues: If standard LoRA is struggling to match the performance of full fine-tuning, the decoupled learning rates of LoRA+ can often help the model find a better weight configuration.
- Large Models with Small Ranks: When using very small ranks (e.g., $r=4$ or $r=8$), the feature learning bottleneck is tighter. LoRA+ helps maximize the utility of these few parameters.
- Complex Data Shifts: If the target task is very different from the original pre-training data, Matrix A needs a higher learning rate to "capture" the new distribution effectively.

In [ ]:
import torch
from datasets import Dataset, DatasetDict
from transformers import (
    AutoTokenizer, 
    AutoModelForCausalLM,
    DataCollatorForLanguageModeling,
    Trainer,
    TrainingArguments
)
from peft import LoraConfig
from torch.optim import AdamW

In [ ]:
# Configure LoRA
lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
    lora_dropout=0.1,
    bias="none",
    task_type="CAUSAL_LM",
)

# Load model and apply LoRA
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    device_map="auto",
    dtype=torch.float32,
    low_cpu_mem_usage=True,
)

model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

# Custom optimizer for LoRA+
def get_loraplus_optimizer(model):
    param_groups = []
    lr_A = 1e-3  # Higher LR for A matrices
    lr_B = 1e-5  # Lower LR for B matrices
    
    for name, param in model.named_parameters():
        if param.requires_grad:
            if 'lora_A' in name:
                param_groups.append({'params': param, 'lr': lr_A})
            elif 'lora_B' in name:
                param_groups.append({'params': param, 'lr': lr_B})
            else:
                param_groups.append({'params': param, 'lr': lr_B})
    
    return AdamW(param_groups, weight_decay=0.01)

monitor = EpochMonitor(model=model)
data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

training_args = TrainingArguments(
    output_dir="./gemma-3-270m-finetuned-qa-loraplus",
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    gradient_accumulation_steps=1,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_strategy="epoch",
    run_name="gemma-3-270m-qa-loraplus",
    warmup_ratio=0.1,
    lr_scheduler_type="cosine",
    fp16=False,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
    callbacks=[monitor],
)

# Set custom optimizer
trainer.optimizer = get_loraplus_optimizer(model)

print("Starting LoRA+ training...")
trainer.train()
model.save_pretrained("./gemma-3-270m-finetuned-qa-loraplus")
tokenizer.save_pretrained("./gemma-3-270m-finetuned-qa-loraplus")
print("LoRA+ training completed!")

Loading weights:   0%|          | 0/236 [00:00<?, ?it/s]

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 3,796,992 || all params: 271,895,168 || trainable%: 1.3965
Starting LoRA+ training...
Initial Model Memory Footprint:
  Parameters: 271,895,168
  Precision: 4 bytes
  Total Memory: 3.83 GB
    - Parameters: 1.01 GB
    - KV Cache (est): 2.81 GB
  Estimated FLOPs per forward pass (batch=8, seq=512): 2.05 TFLOPS

============================================================
Epoch 0 Summary
============================================================
  Duration (s)         :         46.63
  Tokens Processed     :       684,032
  Throughput (token/s) :         14670
  Training Steps       :           167
  Avg CPU (%)          :          20.8
  Avg Memory (%)       :          13.6
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          7.35
  FLOPs (per token)    :   0.50 GFLOPS

============================================================
Epoch 1 Summary
============================================================
  Duration (s)         :         46.91
  Tokens Processed     :       684,032
  Throughput (token/s) :         14581
  Training Steps       :           167
  Avg CPU (%)          :          22.8
  Avg Memory (%)       :          13.6
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          7.30
  FLOPs (per token)    :   0.50 GFLOPS

============================================================
Epoch 2 Summary
============================================================
  Duration (s)         :         46.65
  Tokens Processed     :       684,032
  Throughput (token/s) :         14663
  Training Steps       :           167
  Avg CPU (%)          :          21.5
  Avg Memory (%)       :          13.6
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          7.34
  FLOPs (per token)    :   0.50 GFLOPS

============================================================
TRAINING COMPLETE
============================================================
Total Training Time: 154.14s
Total Epochs: 3
Average Epoch Time: 46.73s
Total Tokens Processed: 2,052,096
Average Throughput: 13313 tokens/second
Total FLOPs: 1027.47 TFLOPS
Average TFLOPS (per second): 6.67
Overall FLOPs (per token): 0.50 GFLOPS

Final Metrics:
Memory Footprint: 3.83 GB
Inference Throughput: 15198 tokens/second
Total Training FLOPs: 342.49 TFLOPS
LoRA+ training completed!

In [16]:
summarize_training_results(trainer, monitor)

====================================================================================================
TRAINING RESULTS SUMMARY TABLE
====================================================================================================
Epoch Training Loss Validation Loss Time (s) Tokens Processed Throughput (token/s) TFLOPS (per second) Avg CPU (%) Avg Memory (%) Training Steps
    0        2.6743          3.1528    46.63          684,032                14670                7.35        20.8           13.6            167
    1        1.8778          3.8435    46.91          684,032                14581                7.30        22.8           13.6            167
    2        1.5184          4.0728    46.65          684,032                14663                7.34        21.5           13.6            167

----------------------------------------------------------------------------------------------------
TRAINING STATISTICS:
----------------------------------------------------------------------------------------------------
Total Training Time:      140.2 s
Average Epoch Time:       46.7 s
Total Tokens Processed:   2,052,096
Average Throughput:       14638 tokens/second
Average CPU Usage:        21.7%
Average Memory Usage:     13.6%
Total Training FLOPs:     1027.47 TFLOPS
Average TFLOPS (per sec): 7.33
Overall FLOPs (per token): 0.50 GFLOPS

====================================================================================================

**Reference** 
- [Arxiv:LoRA+: Efficient Low Rank Adaptation of Large Models](https://arxiv.org/abs/2402.12354)
- [Huggingface:LoRA](https://huggingface.co/docs/peft/en/package_reference/lora)

### LoHa

LoHa (Low-rank Hadamard Product) is a parameter-efficient fine-tuning technique that provides a higher "rank capacity" than standard LoRA without significantly increasing the number of trainable parameters. It was originally popularized in the Stable Diffusion community (Fedora) and has since been adapted for Large Language Models.

Instead of representing weight updates as a simple sum of two matrices (A×B), LoHa represents them as the Hadamard product (element-wise multiplication) of two low-rank decompositions. This structural change allows the model to capture much more complex information and higher-rank updates while maintaining the same small memory footprint as LoRA.

**How it Works**

LoHa re-imagines the weight update $ΔW$ by utilizing four smaller matrices instead of two.

Dual Decomposition: It creates two separate low-rank branches. Branch 1 consists of matrices $A_1$ and $B_1$. Branch 2 consists of matrices $A_2$ and $B_2$.

The Hadamard Operation: The final update is calculated by performing a matrix multiplication for each branch and then multiplying those results together element-wise:

$$\Delta W = (A_1 B_1) \odot (A_2 B_2)$$

Where $⊙$ denotes the Hadamard (element-wise) product.

Rank Boosting: Mathematically, the Hadamard product of two matrices with rank `r` can result in a matrix with a rank up to $r^2$. This means a LoHa adapter with `r=8` can potentially express patterns that would require a standard LoRA rank of 64, giving it a massive "expressive" advantage.

**Implements LoHa**

The script uses the LoHaConfig from the PEFT library to swap standard linear layers with specialized Hadamard-product layers.

**Configuring the Rank:**

    r=8,
    alpha=16,

Even with a low rank of 8, the model achieves high expressiveness due to the $r^2$ rank potential. The alpha parameter acts as a scaling factor, similar to standard LoRA, to balance the magnitude of the adapter's influence on the frozen base weights.

**Applying to Gemma-3:**

    target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"]

The code injects these dual-branch adapters into all major linear layers of the Gemma-3-270m model. This ensures that both the attention mechanism and the feed-forward blocks (MLP) benefit from the higher-rank capacity.

**Regularization via Dropout:**

    rank_dropout=0.1,
    module_dropout=0.1,

Because LoHa is more powerful than LoRA, it can be more prone to overfitting on small datasets. The code includes `rank_dropout` (which randomly zeros out specific rows/columns in the low-rank matrices) and `module_dropout` to ensure the model generalizes well.

**When to Use It**

LoHa is an excellent choice when you need the efficiency of a small model but the learning capacity of a much larger one:
- Complex Visual or Stylistic Tasks: Use it when the fine-tuning task involves learning intricate patterns that simple additive LoRA updates struggle to capture (e.g., specific artistic styles or highly technical jargon).
- Parameter-Constrained High Performance: If you are strictly limited to a small rank (like r=4 or r=8) due to VRAM limits but find that standard LoRA isn't "smart" enough to learn the task, LoHa provides the necessary complexity without the memory cost of a higher LoRA rank.
- Stable Diffusion & Multi-Modal Models: It is exceptionally popular for models that handle both text and spatial data, where the relationship between parameters is non-linear and complex.
- Fine-Tuning Very Small Models: For tiny models like Gemma-3-270m, every parameter update must be highly efficient. LoHa's ability to maximize the utility of every bit makes it ideal for sub-1B parameter models.

In [ ]:
import torch
from datasets import Dataset, DatasetDict
from transformers import (
    AutoTokenizer, 
    AutoModelForCausalLM,
    DataCollatorForLanguageModeling,
    Trainer,
    TrainingArguments
)
from peft import LoHaConfig

In [ ]:
# Configure LoHa
loha_config = LoHaConfig(
    r=8,
    alpha=16,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
    rank_dropout=0.1,
    module_dropout=0.1,
    use_effective_conv2d=False,
    #bias="none",
    task_type="CAUSAL_LM",
)

# Load model and apply LoHa
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    device_map="auto",
    dtype=torch.float32,
    low_cpu_mem_usage=True,
)

model = get_peft_model(model, loha_config)
model.print_trainable_parameters()

monitor = EpochMonitor(model=model)
data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

training_args = TrainingArguments(
    output_dir="./gemma-3-270m-finetuned-qa-loha",
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    gradient_accumulation_steps=1,
    learning_rate=2e-4,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_strategy="epoch",
    run_name="gemma-3-270m-qa-loha",
    warmup_ratio=0.1,
    lr_scheduler_type="cosine",
    fp16=False,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
    callbacks=[monitor],
)

print("Starting LoHa training...")
trainer.train()
model.save_pretrained("./gemma-3-270m-finetuned-qa-loha")
tokenizer.save_pretrained("./gemma-3-270m-finetuned-qa-loha")
print("LoHa training completed!")

Loading weights:   0%|          | 0/236 [00:00<?, ?it/s]

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 3,796,992 || all params: 271,895,168 || trainable%: 1.3965
Starting LoHa training...
Initial Model Memory Footprint:
  Parameters: 271,895,168
  Precision: 4 bytes
  Total Memory: 3.83 GB
    - Parameters: 1.01 GB
    - KV Cache (est): 2.81 GB
  Estimated FLOPs per forward pass (batch=8, seq=512): 2.05 TFLOPS

============================================================
Epoch 0 Summary
============================================================
  Duration (s)         :         57.30
  Tokens Processed     :       684,032
  Throughput (token/s) :         11938
  Training Steps       :           167
  Avg CPU (%)          :          21.8
  Avg Memory (%)       :          13.9
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          5.98
  FLOPs (per token)    :   0.50 GFLOPS

============================================================
Epoch 1 Summary
============================================================
  Duration (s)         :         57.16
  Tokens Processed     :       684,032
  Throughput (token/s) :         11967
  Training Steps       :           167
  Avg CPU (%)          :          22.1
  Avg Memory (%)       :          13.9
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          5.99
  FLOPs (per token)    :   0.50 GFLOPS

============================================================
Epoch 2 Summary
============================================================
  Duration (s)         :         57.32
  Tokens Processed     :       684,032
  Throughput (token/s) :         11934
  Training Steps       :           167
  Avg CPU (%)          :          22.0
  Avg Memory (%)       :          13.9
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          5.98
  FLOPs (per token)    :   0.50 GFLOPS

============================================================
TRAINING COMPLETE
============================================================
Total Training Time: 188.94s
Total Epochs: 3
Average Epoch Time: 57.26s
Total Tokens Processed: 2,052,096
Average Throughput: 10861 tokens/second
Total FLOPs: 1027.47 TFLOPS
Average TFLOPS (per second): 5.44
Overall FLOPs (per token): 0.50 GFLOPS

Final Metrics:
Memory Footprint: 3.83 GB
Inference Throughput: 12279 tokens/second
Total Training FLOPs: 342.49 TFLOPS
LoHa training completed!

In [18]:
summarize_training_results(trainer, monitor)

====================================================================================================
TRAINING RESULTS SUMMARY TABLE
====================================================================================================
Epoch Training Loss Validation Loss Time (s) Tokens Processed Throughput (token/s) TFLOPS (per second) Avg CPU (%) Avg Memory (%) Training Steps
    0        2.9967          3.0113    57.30          684,032                11938                5.98        21.8           13.9            167
    1        2.5497          2.9758    57.16          684,032                11966                5.99        22.1           13.9            167
    2        2.4215          2.9828    57.32          684,032                11933                5.98        22.0           13.9            167

----------------------------------------------------------------------------------------------------
TRAINING STATISTICS:
----------------------------------------------------------------------------------------------------
Total Training Time:      171.8 s
Average Epoch Time:       57.3 s
Total Tokens Processed:   2,052,096
Average Throughput:       11946 tokens/second
Average CPU Usage:        21.9%
Average Memory Usage:     13.9%
Total Training FLOPs:     1027.47 TFLOPS
Average TFLOPS (per sec): 5.98
Overall FLOPs (per token): 0.50 GFLOPS

====================================================================================================

**Reference** 
- [Arxiv:LOHA: Direct Graph Spectral Contrastive Learning Between Low-pass and High-pass Views](https://arxiv.org/abs/2501.02969)
- [Huggingface:LoHa](https://huggingface.co/docs/peft/en/package_reference/loha)

### KronA

KronA (Kronecker Adaptation) is a parameter-efficient fine-tuning technique that utilizes the Kronecker product to represent weight updates. It aims to strike a balance between the extreme efficiency of vector-based methods (like IA3) and the high expressivity of matrix-based methods (like LoRA).

By decomposing a large weight update matrix into a Kronecker product of two much smaller matrices, KronA can represent high-rank updates with a significantly lower parameter count than standard LoRA. It effectively "tiles" the weight update across the original weight matrix, allowing for complex, structured changes with minimal training overhead.

**How it Works**

The core mechanism of KronA involves replacing the standard additive update with a Kronecker-structured transformation.
- Kronecker Decomposition: Instead of a low-rank product $A \times B$, KronA defines the update $\Delta W$ as the Kronecker product of two small matrices, A and B:

$$\Delta W = A \otimes B$$

- Parameter Scaling: If $W$ is a $d \times k$ matrix, standard LoRA with rank $r$ requires $r(d+k)$ parameters. KronA can achieve similar or higher ranks using matrices $A$ (size $n \times n$) and $B$ (size $m \times m$) such that $nm \approx d$.
- The Kronecker Property: The Kronecker product $A \otimes B$ results in a block matrix where each element of $A$ is multiplied by the entire matrix $B$. This allows a very small number of parameters to influence every single element of the original weight matrix in a coordinated way.

**Implements KronA-like Adaptation**

The provided code uses IA3 (Infused Adapter by Inhibiting and Amplifying Inner Activations) as a proxy for KronA-like behavior.

Vector-Based Scaling: IA3 is the most compressed version of Kronecker-style adaptation. It simplifies the Kronecker product down to element-wise multiplication by learned vectors ($l_k$ and $l_v$).

**Targeting the Right Modules:**

    target_modules=["k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"]
    
The configuration targets both the attention mechanism and the feedforward network (FFN). In KronA/IA3, these vectors scale the hidden representations directly, which is mathematically equivalent to a Kronecker product where one of the matrices is a diagonal matrix or a identity matrix.

**FFN-Specific Adaptation:**

    feedforward_modules=["gate_proj", "up_proj", "down_proj"]

IA3 and KronA are particularly effective in the FFN (Gemma's "MLP" layers). They learn to "inhibit" or "amplify" specific features of the weights, allowing the model to adapt its internal logic without needing to learn entirely new weight values.

**When to Use It**

KronA and its relatives like IA3 are ideal for scenarios where efficiency is the primary constraint:
- Massive Model Scale: When working with models significantly larger than Gemma-3-270m, KronA provides a way to tune the model with even fewer parameters than LoRA, saving precious VRAM.
- Few-Shot Learning: KronA is highly effective in low-data regimes. Because it has so few trainable parameters, it is much less likely to "overfit" or memorize the small training set, leading to better generalization on new prompts.
- Low-Latency Inference: Since Kronecker products (and IA3 vectors) can be pre-computed and merged into the base weights, they provide the performance boost of fine-tuning with zero additional latency at inference time.
- Global Weight Adaptation: Use KronA when the task requires a "global" change in how a model processes information (e.g., changing the tone or formatting of all outputs) rather than learning highly specific new facts that might require the direct weight injection of LoRA.

In [ ]:
import torch
from datasets import Dataset, DatasetDict
from transformers import (
    AutoTokenizer, 
    AutoModelForCausalLM,
    DataCollatorForLanguageModeling,
    Trainer,
    TrainingArguments
)
from peft import IA3Config

In [ ]:
# Configure IA3 for KronA-like adaptation
krona_config = IA3Config(
    target_modules=["k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
    feedforward_modules=["gate_proj", "up_proj", "down_proj"],
    task_type="CAUSAL_LM",
)

# Load model and apply IA3
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    device_map="auto",
    dtype=torch.float32,
    low_cpu_mem_usage=True,
)

model = get_peft_model(model, krona_config)
model.print_trainable_parameters()

monitor = EpochMonitor(model=model)
data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

training_args = TrainingArguments(
    output_dir="./gemma-3-270m-finetuned-qa-krona",
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    gradient_accumulation_steps=1,
    learning_rate=3e-4,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_strategy="epoch",
    run_name="gemma-3-270m-qa-krona",
    warmup_ratio=0.1,
    lr_scheduler_type="cosine",
    fp16=False,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
    callbacks=[monitor],
)

print("Starting KronA training...")
trainer.train()
model.save_pretrained("./gemma-3-270m-finetuned-qa-krona")
tokenizer.save_pretrained("./gemma-3-270m-finetuned-qa-krona")
print("KronA training completed!")

Loading weights:   0%|          | 0/236 [00:00<?, ?it/s]

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 80,640 || all params: 268,178,816 || trainable%: 0.0301
Starting KronA training...
Initial Model Memory Footprint:
  Parameters: 268,178,816
  Precision: 4 bytes
  Total Memory: 3.81 GB
    - Parameters: 1.00 GB
    - KV Cache (est): 2.81 GB
  Estimated FLOPs per forward pass (batch=8, seq=512): 2.05 TFLOPS

============================================================
Epoch 0 Summary
============================================================
  Duration (s)         :         36.21
  Tokens Processed     :       684,032
  Throughput (token/s) :         18889
  Training Steps       :           167
  Avg CPU (%)          :          19.1
  Avg Memory (%)       :          14.0
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          9.46
  FLOPs (per token)    :   0.50 GFLOPS

============================================================
Epoch 1 Summary
============================================================
  Duration (s)         :         36.09
  Tokens Processed     :       684,032
  Throughput (token/s) :         18955
  Training Steps       :           167
  Avg CPU (%)          :          21.4
  Avg Memory (%)       :          14.0
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          9.49
  FLOPs (per token)    :   0.50 GFLOPS

============================================================
Epoch 2 Summary
============================================================
  Duration (s)         :         36.23
  Tokens Processed     :       684,032
  Throughput (token/s) :         18878
  Training Steps       :           167
  Avg CPU (%)          :          18.3
  Avg Memory (%)       :          14.0
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          9.45
  FLOPs (per token)    :   0.50 GFLOPS

============================================================
TRAINING COMPLETE
============================================================
Total Training Time: 121.44s
Total Epochs: 3
Average Epoch Time: 36.18s
Total Tokens Processed: 2,052,096
Average Throughput: 16898 tokens/second
Total FLOPs: 1027.47 TFLOPS
Average TFLOPS (per second): 8.46
Overall FLOPs (per token): 0.50 GFLOPS

Final Metrics:
Memory Footprint: 3.81 GB
Inference Throughput: 19848 tokens/second
Total Training FLOPs: 342.49 TFLOPS
KronA training completed!

In [20]:
summarize_training_results(trainer, monitor)

====================================================================================================
TRAINING RESULTS SUMMARY TABLE
====================================================================================================
Epoch Training Loss Validation Loss Time (s) Tokens Processed Throughput (token/s) TFLOPS (per second) Avg CPU (%) Avg Memory (%) Training Steps
    0        3.0833          3.2011    36.21          684,032                18889                9.46        19.1           14.0            167
    1        2.8963          3.1618    36.09          684,032                18954                9.49        21.4           14.0            167
    2        2.8474          3.1579    36.23          684,032                18878                9.45        18.3           14.0            167

----------------------------------------------------------------------------------------------------
TRAINING STATISTICS:
----------------------------------------------------------------------------------------------------
Total Training Time:      108.5 s
Average Epoch Time:       36.2 s
Total Tokens Processed:   2,052,096
Average Throughput:       18907 tokens/second
Average CPU Usage:        19.6%
Average Memory Usage:     14.0%
Total Training FLOPs:     1027.47 TFLOPS
Average TFLOPS (per sec): 9.47
Overall FLOPs (per token): 0.50 GFLOPS

====================================================================================================

**Reference** 
- [Arxiv:KronA: Parameter Efficient Tuning with Kronecker Adapter](https://arxiv.org/abs/2212.10650)
- [Huggingface:IA3](https://huggingface.co/docs/peft/en/conceptual_guides/ia3)

### QLoRA with Gradient Checkpointing

QLoRA with Gradient Checkpointing is a dual-layered memory optimization strategy designed to train large language models on limited hardware. While QLoRA reduces the memory needed to store the model weights by compressing them into a 4-bit format, Gradient Checkpointing reduces the memory consumed by "activations"—the intermediate mathematical results generated during the forward pass.

Together, these techniques tackle the two largest memory "hogs" in deep learning, allowing models that would normally require hundreds of gigabytes of VRAM to be fine-tuned on single consumer-grade GPUs.

**How it Works**

This combination optimizes memory across two different axes: static storage and dynamic computation.
- Static Memory (QLoRA): The model's original 16-bit weights are quantized into 4-bit NormalFloat (NF4). This reduces the model's footprint by approximately 75%. Only the tiny LoRA adapter matrices remain in high precision for training.
- Dynamic Memory (Gradient Checkpointing): Normally, a model saves the output of every single layer during the forward pass so it can use them to calculate gradients later. This "activation storage" grows linearly with sequence length and batch size.
- The Trade-off: Gradient Checkpointing discards most of these intermediate activations during the forward pass. When it comes time to calculate the gradients during the backward pass, the model re-calculates the missing activations on the fly.
- Efficiency: This results in a massive reduction in VRAM usage (often 50-70% for activations) at the cost of roughly 30% slower training speed due to the extra re-computation steps.

**Implements the Combination**

The code orchestrates these two optimizations through the bitsandbytes configuration and the transformers training arguments.

**1. Applying 4-bit Quantization**

    bnb_config = BitsAndBytesConfig(
        load_in_4bit=True,
        bnb_4bit_quant_type="nf4",
        bnb_4bit_use_double_quant=True
    )

This handles the QLoRA portion. By passing this to `AutoModelForCausalLM.from_pretrained`, the Gemma-3-270m weights are loaded directly into 4-bit VRAM.

**2. Preparing the Model Structure**

    model = prepare_model_for_kbit_training(model, use_gradient_checkpointing=False)

This function is a vital QLoRA utility. It enables gradient checkpointing support at the structural level and ensures that the inputs to the quantized layers are cast to the correct precision (float16) to maintain numerical stability during the training process.

**3. Activating the Checkpointing Logic**

    training_args = TrainingArguments(
        ...
        gradient_checkpointing=True,
    )

This flag tells the Trainer to actually use the checkpointing strategy during the training loop. It instructs the model to start dropping and re-computing activations, which is what ultimately prevents "Out of Memory" errors when using larger batch sizes or longer sequence lengths.

**When to Use It**

This combined strategy is the ultimate "survival kit" for LLM fine-tuning:
- Sequence Length Challenges: Use it when training on long documents (e.g., 2048+ tokens). Since activation memory scales with sequence length, checkpointing is often the only way to avoid crashes.
- Large Batch Sizes: If the goal is to use larger batches to stabilize training but the GPU memory is full, enabling checkpointing can free up enough space to double or triple the `per_device_train_batch_size`.
- Hardware Constraints: Essential for fine-tuning models on GPUs with 16GB or 24GB of VRAM (like an RTX 3090/4090 or A10G) when the model itself already occupies most of that space.
- Diminishing Returns on Speed: If the bottleneck is memory rather than time, the 30% speed penalty is a small price to pay for the ability to train a model that would otherwise be impossible to load.

In [ ]:
from transformers import BitsAndBytesConfig
from peft import AdaLoraConfig
import torch
from datasets import Dataset, DatasetDict
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    DataCollatorForLanguageModeling,
    Trainer,
    TrainingArguments,
)
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training

In [ ]:
# Configuration
MODEL_NAME = "google/gemma-3-270m"
OUTPUT_DIR = "./gemma-3-270m-finetuned-qa-dora"

# Configure 4-bit quantization
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True
)

# Configure LoRA
lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
    lora_dropout=0.1,
    bias="none",
    task_type="CAUSAL_LM",
)

# Load model with 4-bit quantization
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    quantization_config=bnb_config,
    device_map="auto",
    torch_dtype=torch.float16,
    low_cpu_mem_usage=True,
)

# Prepare model for k-bit training
model = prepare_model_for_kbit_training(model, use_gradient_checkpointing=False) 

# Apply LoRA
model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

monitor = EpochMonitor(model=model)
data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

training_args = TrainingArguments(
    output_dir="./gemma-3-270m-finetuned-qa-qlora",
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    gradient_accumulation_steps=1,
    learning_rate=2e-4,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_strategy="epoch",
    run_name="gemma-3-270m-qa-qlora",
    warmup_ratio=0.1,
    lr_scheduler_type="cosine",
    fp16=True,
    gradient_checkpointing=True,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
    callbacks=[monitor],
)

print("Starting QLoRA training...")
trainer.train()
model.save_pretrained("./gemma-3-270m-finetuned-qa-qlora")
tokenizer.save_pretrained("./gemma-3-270m-finetuned-qa-qlora")
print("QLoRA training completed!")

Loading weights:   0%|          | 0/236 [00:00<?, ?it/s]

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 3,796,992 || all params: 271,895,168 || trainable%: 1.3965
Starting QLoRA training...
Initial Model Memory Footprint:
  Parameters: 221,760,128
  Precision: 4 bytes
  Total Memory: 3.64 GB
    - Parameters: 0.83 GB
    - KV Cache (est): 2.81 GB
  Estimated FLOPs per forward pass (batch=8, seq=512): 2.05 TFLOPS

============================================================
Epoch 0 Summary
============================================================
  Duration (s)         :         63.16
  Tokens Processed     :       684,032
  Throughput (token/s) :         10830
  Training Steps       :           167
  Avg CPU (%)          :          20.3
  Avg Memory (%)       :          13.9
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          5.42
  FLOPs (per token)    :   0.50 GFLOPS

============================================================
Epoch 1 Summary
============================================================
  Duration (s)         :         63.96
  Tokens Processed     :       684,032
  Throughput (token/s) :         10695
  Training Steps       :           167
  Avg CPU (%)          :          23.6
  Avg Memory (%)       :          13.9
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          5.35
  FLOPs (per token)    :   0.50 GFLOPS

============================================================
Epoch 2 Summary
============================================================
  Duration (s)         :         64.29
  Tokens Processed     :       684,032
  Throughput (token/s) :         10640
  Training Steps       :           167
  Avg CPU (%)          :          25.6
  Avg Memory (%)       :          13.9
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          5.33
  FLOPs (per token)    :   0.50 GFLOPS

============================================================
TRAINING COMPLETE
============================================================
Total Training Time: 205.30s
Total Epochs: 3
Average Epoch Time: 63.80s
Total Tokens Processed: 2,052,096
Average Throughput: 9996 tokens/second
Total FLOPs: 1027.47 TFLOPS
Average TFLOPS (per second): 5.00
Overall FLOPs (per token): 0.50 GFLOPS

Final Metrics:
Memory Footprint: 3.64 GB
Inference Throughput: 11068 tokens/second
Total Training FLOPs: 342.49 TFLOPS
QLoRA training completed!

In [22]:
summarize_training_results(trainer, monitor)

====================================================================================================
TRAINING RESULTS SUMMARY TABLE
====================================================================================================
Epoch Training Loss Validation Loss Time (s) Tokens Processed Throughput (token/s) TFLOPS (per second) Avg CPU (%) Avg Memory (%) Training Steps
    0        2.3842          3.9941    63.16          684,032                10829                5.42        20.3           13.9            167
    1        1.1332          6.3537    63.96          684,032                10694                5.35        23.6           13.9            167
    2        0.8031          6.8533    64.29          684,032                10639                5.33        25.6           13.9            167

----------------------------------------------------------------------------------------------------
TRAINING STATISTICS:
----------------------------------------------------------------------------------------------------
Total Training Time:      191.4 s
Average Epoch Time:       63.8 s
Total Tokens Processed:   2,052,096
Average Throughput:       10721 tokens/second
Average CPU Usage:        23.1%
Average Memory Usage:     13.9%
Total Training FLOPs:     1027.47 TFLOPS
Average TFLOPS (per sec): 5.37
Overall FLOPs (per token): 0.50 GFLOPS

====================================================================================================

**Reference** 
- [Arxiv:QLORA: Efficient Finetuning of Quantized LLMs](https://arxiv.org/pdf/2305.14314)
- [APXML:Quantization and its effect on Fine-Tuning (QLoRA)](https://apxml.com/courses/introduction-to-llm-fine-tuning/chapter-4-parameter-efficient-fine-tuning-peft/quantization-and-qlora)
- [Medium:Interactive Study with Conversation1st.ai — QLoRA: Efficient Finetuning of Quantized LLMs](https://medium.com/@tonytong.ai/interactive-study-with-conversation1st-ai-qlora-efficient-finetuning-of-quantized-llms-7b50cb31ea19)

# Prefix and Prompt-Based Methods

Prefix Tuning and Prompt Tuning are additive Parameter-Efficient Fine-Tuning (PEFT) methods that adapt Large Language Models (LLMs) by prepending learnable "soft" tokens to the input.

Unlike standard fine-tuning, which modifies the model's internal weights, or LoRA, which adds secondary matrices to existing layers, these methods keep the entire pre-trained model frozen. They instead learn a set of continuous, task-specific vectors that act as an optimized "instruction" or "context" that guides the model's behavior.

**1. Prompt Tuning**

Prompt Tuning is the most streamlined version of this approach. It learns a small set of trainable vectors that are added only to the input embedding layer.
- How it works: Imagine a standard prompt like "Summarize this: [Text]". In Prompt Tuning, those words are replaced by a set of "virtual" tokens (vectors). These vectors do not correspond to real human words; instead, they are high-dimensional numbers that the model learns through backpropagation to trigger the desired task.
- The Workflow: During training, only these virtual tokens are updated. At inference, these "soft prompts" are prepended to the user's actual input. 

**Prefix Tuning**

Prefix Tuning is a more "integrated" version of the concept. It applies learnable vectors not just to the input layer, but to the hidden states of every layer in the transformer.
- How it works: For every layer in the model, a prefix of trainable vectors is prepended to the Keys ($K$) and Values ($V$) of the attention mechanism.
- Deep Guidance: Because the "instruction" is present at every level of the model's processing hierarchy (from raw text understanding to high-level reasoning), Prefix Tuning is generally more powerful and expressive than simple Prompt Tuning, especially for complex generation tasks.

**Key Differences**

- Depth: Prompt Tuning is "shallow" (input layer only); Prefix Tuning is "deep" (all layers).
- Parameter Count: Prompt Tuning typically uses the fewest parameters of almost any PEFT method. Prefix Tuning uses slightly more but is still highly efficient (typically < 0.1% of the model).
- Complexity: Prefix Tuning often requires more complex implementation as it involves modifying the internal attention blocks of the transformer.

**When to Use These Methods**

Use Prompt Tuning when:
- You have a massive model (100B+ parameters): Research shows that as models get larger, the performance gap between Prompt Tuning and full fine-tuning disappears.
- You are doing simple classification or sentiment analysis: Tasks that don't require heavy structural changes to the model's output are ideal for shallow prompt tuning.
- Multi-tasking at scale: You can store thousands of 10KB "soft prompts" for different users or tasks and simply swap them out in the same batch without changing the base model.

Use Prefix Tuning when:
- You are focused on Natural Language Generation (NLG): It is highly effective for tasks like summarization, translation, or data-to-text generation where the model needs deeper guidance on the output structure.
- You have limited data: Because it freezes the base model, it is very resistant to overfitting on small datasets.
- You need high performance with low storage: Prefix Tuning often matches the performance of full fine-tuning while requiring only a fraction of the storage for the learned vectors.

### Simple Prompt Tuning

Simple Prompt Tuning is a parameter-efficient fine-tuning (PEFT) strategy that adapts a Large Language Model by learning a set of continuous, "soft" embeddings that are prepended to the user's input.

Unlike standard fine-tuning or LoRA, which modify the model's internal weights or add sub-layers, Prompt Tuning leaves the entire pre-trained transformer frozen. It treats the "instruction" part of the input as a set of learnable vectors rather than fixed text tokens. These "virtual tokens" are optimized through backpropagation to guide the model toward the correct output for a specific task.

**How it Works: The Soft Prompt Mechanism**

Prompt Tuning operates entirely at the input embedding level, making it the least invasive form of adaptation.
- Continuous vs. Discrete: A standard "hard" prompt uses real words (e.g., "Summarize:"). Prompt Tuning replaces these with Virtual Tokens. These are not limited to the existing vocabulary; they are continuous vectors in the model's high-dimensional embedding space.
- Concatenation: Before the input passes into the transformer layers, the learnable soft prompt vectors are prepended to the embedded representation of the user's text.
- Frozen Backbone: During the training process, the model's billions of parameters remain unchanged. Only the small matrix containing the soft prompt vectors receives gradient updates.
- Signal Steering: The soft prompt acts as a learned "prefix" that prepares the internal attention mechanisms of the model to process the following text in a task-specific way.

**Implements Simple Prompt Tuning**

The provided script utilizes the PEFT library to wrap a Gemma-3-270m model with a trainable prompt encoder.

**Defining Virtual Tokens:**

    prompt_config = PromptTuningConfig(
        task_type="CAUSAL_LM",
        num_virtual_tokens=20,
        tokenizer_name_or_path=MODEL_NAME,
    )

The `num_virtual_tokens=20` tells the model to create 20 new trainable vectors. The `tokenizer_name_or_path` is used to initialize these vectors, often by taking the embeddings of random common words to give the model a better starting point than pure noise.

**Parameter Isolation:**

When `get_peft_model(model, prompt_config)` is called, the library sets `requires_grad = False` for all original model weights. It creates a new PromptEmbedding layer that contains only the 20 virtual tokens.

**Training and Efficiency:**

    model.print_trainable_parameters()

This line will reveal that only a few thousand parameters (20 tokens multiplied by the model's hidden dimension) are being trained. For a model like Gemma-3-270m, this represents a tiny fraction of the total size, significantly reducing the memory overhead for optimizer states.

**When to Use It**

Simple Prompt Tuning is a specialized tool best suited for specific high-scale or low-resource scenarios:
- Large Scale Multi-Tasking: If a single server needs to handle hundreds of different tasks (e.g., translation, sentiment, summarization), storing hundreds of LoRA adapters (megabytes each) can be bulky. Soft prompts (kilobytes each) can be swapped in and out almost instantly.
- Massive Foundation Models: Research indicates that the larger the model (e.g., 70B+ parameters), the more effective Prompt Tuning becomes. For very large models, it often matches the performance of full fine-tuning.
- Bypassing Architecture Conflicts: As noted in the code comment, some models (like Gemma-3) may have complex Key-Value (KV) cache behaviors that can cause bugs with Prefix Tuning. Simple Prompt Tuning avoids these issues by staying strictly at the input layer.
- Privacy and Personalization: It is ideal for learning user-specific styles. A unique soft prompt can be trained for each user without ever touching the core model weights, ensuring the foundational knowledge remains consistent for everyone.

In [ ]:
import torch
from datasets import Dataset, DatasetDict
from transformers import (
    AutoTokenizer, 
    AutoModelForCausalLM,
    DataCollatorForLanguageModeling,
    Trainer,
    TrainingArguments
)
from peft import PromptTuningConfig, get_peft_model

In [ ]:
# Configure Prompt Tuning
prompt_config = PromptTuningConfig(
    task_type="CAUSAL_LM",
    num_virtual_tokens=20,              # number of learnable prefix tokens
    tokenizer_name_or_path=MODEL_NAME,  # required for prompt encoder init
)

# Load model
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    device_map="auto",
    torch_dtype=torch.bfloat16,
    low_cpu_mem_usage=True,
)

# Apply prompt tuning
model = get_peft_model(model, prompt_config)
model.print_trainable_parameters()

# Training setup
monitor = EpochMonitor(model=model)
data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

training_args = TrainingArguments(
    output_dir="./gemma-3-270m-finetuned-qa-prompt",
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    gradient_accumulation_steps=1,
    learning_rate=2e-4,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_strategy="epoch",
    run_name="gemma-3-270m-qa-prompt",
    warmup_ratio=0.1,
    lr_scheduler_type="cosine",
    gradient_checkpointing=True,
    bf16=True,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
    callbacks=[monitor],
)

print("Starting Prompt Tuning...")
trainer.train()

model.save_pretrained("./gemma-3-270m-finetuned-qa-prompt")
tokenizer.save_pretrained("./gemma-3-270m-finetuned-qa-prompt")
print("Prompt Tuning completed!")

Loading weights:   0%|          | 0/236 [00:00<?, ?it/s]

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 12,800 || all params: 268,110,976 || trainable%: 0.0048
Starting Prompt Tuning...
Initial Model Memory Footprint:
  Parameters: 268,110,976
  Precision: 2 bytes
  Total Memory: 1.91 GB
    - Parameters: 0.50 GB
    - KV Cache (est): 1.41 GB
  Estimated FLOPs per forward pass (batch=8, seq=512): 2.05 TFLOPS

============================================================
Epoch 0 Summary
============================================================
  Duration (s)         :         29.88
  Tokens Processed     :       684,032
  Throughput (token/s) :         22896
  Training Steps       :           167
  Avg CPU (%)          :          24.2
  Avg Memory (%)       :          13.7
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :         11.46
  FLOPs (per token)    :   0.50 GFLOPS

============================================================
Epoch 1 Summary
============================================================
  Duration (s)         :         29.84
  Tokens Processed     :       684,032
  Throughput (token/s) :         22923
  Training Steps       :           167
  Avg CPU (%)          :          22.8
  Avg Memory (%)       :          13.7
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :         11.48
  FLOPs (per token)    :   0.50 GFLOPS

============================================================
Epoch 2 Summary
============================================================
  Duration (s)         :         29.97
  Tokens Processed     :       684,032
  Throughput (token/s) :         22826
  Training Steps       :           167
  Avg CPU (%)          :          22.2
  Avg Memory (%)       :          13.7
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :         11.43
  FLOPs (per token)    :   0.50 GFLOPS

============================================================
TRAINING COMPLETE
============================================================
Total Training Time: 98.26s
Total Epochs: 3
Average Epoch Time: 29.89s
Total Tokens Processed: 2,052,096
Average Throughput: 20885 tokens/second
Total FLOPs: 1027.47 TFLOPS
Average TFLOPS (per second): 10.46
Overall FLOPs (per token): 0.50 GFLOPS

Final Metrics:
Memory Footprint: 1.91 GB
Inference Throughput: 24377 tokens/second
Total Training FLOPs: 342.49 TFLOPS
Prompt Tuning completed!

In [24]:
summarize_training_results(trainer, monitor)

====================================================================================================
TRAINING RESULTS SUMMARY TABLE
====================================================================================================
Epoch Training Loss Validation Loss Time (s) Tokens Processed Throughput (token/s) TFLOPS (per second) Avg CPU (%) Avg Memory (%) Training Steps
    0        4.2426          3.4109    29.88          684,032                22895               11.46        24.2           13.7            167
    1        3.2858          3.3472    29.84          684,032                22922               11.48        22.8           13.7            167
    2        3.2327          3.3318    29.97          684,032                22825               11.43        22.2           13.7            167

----------------------------------------------------------------------------------------------------
TRAINING STATISTICS:
----------------------------------------------------------------------------------------------------
Total Training Time:      89.7 s
Average Epoch Time:       29.9 s
Total Tokens Processed:   2,052,096
Average Throughput:       22881 tokens/second
Average CPU Usage:        23.1%
Average Memory Usage:     13.7%
Total Training FLOPs:     1027.47 TFLOPS
Average TFLOPS (per sec): 11.46
Overall FLOPs (per token): 0.50 GFLOPS

====================================================================================================

**Reference** 
- [Huggingface:Prompt tuning](https://huggingface.co/docs/peft/en/package_reference/prompt_tuning)
- [Huggingface:Prompt Tuning With PEFT.](https://huggingface.co/learn/cookbook/en/prompt_tuning_peft)
- [APXML:Prompt Tuning and P-Tuning Variations](https://apxml.com/courses/lora-peft-efficient-llm-training/chapter-3-peft-methodologies-survey/prompt-tuning-variations)
- [Medium:Prompt Tuning: A New Approach to Large Language Model Specialization](https://medium.com/@tahirbalarabe2/prompt-tuning-a-new-approach-to-language-model-specialization-6abd12cea528)

## Advanced Prompt Tuning

### Prompt Tuning (Soft Prompts)

Prompt Tuning is a parameter-efficient fine-tuning (PEFT) technique that freezes the entire architecture of a Large Language Model and instead learns a small set of continuous "soft prompt" vectors. These vectors are prepended to the input sequence and optimized during training to guide the model toward a specific task or output style.

Unlike "hard" prompts (actual text written by humans), soft prompts are high-dimensional embeddings that exist in the model's vector space. They do not necessarily correspond to real words in the vocabulary, allowing the model to find the most mathematically efficient "instruction" to solve a problem.

**How it Works**

Prompt Tuning focuses exclusively on the input embedding layer of the transformer.
- Virtual Tokens: A set of new, trainable parameters called "virtual tokens" is created. These are just rows in a small embedding matrix.
- Concatenation: When a user provides an input, the model converts that text into embeddings. The trainable soft prompt vectors are then "glued" to the beginning of these embeddings.
- Frozen Backbone: During backpropagation, gradients flow through the entire model, but only the virtual tokens are updated. The billions of parameters in the transformer layers remain unchanged.
- Task Steering: As training progresses, these soft prompt vectors learn to act as a specialized "key" that triggers the relevant knowledge and patterns inside the frozen model to answer the user's request.

**Implements Prompt Tuning**

The script utilizes the PromptTuningConfig from the PEFT library to modify the input pipeline of Gemma-3-270m.

**Configuring the Virtual Space:**

    prompt_config = PromptTuningConfig(
        task_type="CAUSAL_LM",
        num_virtual_tokens=20,
        prompt_tuning_init=PromptTuningInit.RANDOM,
    )

The `num_virtual_tokens=20` defines the length of the learned instruction. `PromptTuningInit.RANDOM` indicates that the virtual tokens start as random noise rather than being initialized from existing word embeddings.

**Model Transformation:**

By calling `get_peft_model(model, prompt_config)`, the code strips away the gradient requirements for the original Gemma-3 weights. It adds a PromptEncoder layer that manages the 20 new vectors.

**Training Specifics:**

The `model.print_trainable_parameters()` output will show that only a few thousand parameters are being trained. For instance, if the hidden dimension of Gemma-3 is 2048, the model only trains $20 \times 2048 = 40,960$ parameters. This is significantly fewer than LoRA, which often trains millions of parameters.

**When to Use It**

Prompt Tuning is a highly specific optimization tool used in the following scenarios:
- Massive Model Scaling: It is exceptionally effective on models with over 10 billion parameters. At this scale, the performance of Prompt Tuning often reaches parity with full fine-tuning.
- Multi-Task Deployment: If one base model needs to serve 1,000 different tasks simultaneously, storing 1,000 Prompt Tuning adapters is extremely cheap (kilobytes each). You can simply swap the "soft prompt" prefix for each request in a single batch.
- Minimal Storage Capacity: When disk space is a primary constraint, Prompt Tuning offers the smallest possible checkpoint size of any fine-tuning method.
- Domain Adaptation with Low Data: Because the base model is frozen, Prompt Tuning is less prone to "overfitting" on tiny datasets compared to methods that modify deeper weights.

In [ ]:
import torch
from datasets import Dataset, DatasetDict
from transformers import (
    AutoTokenizer, 
    AutoModelForCausalLM,
    DataCollatorForLanguageModeling,
    Trainer,
    TrainingArguments
)
from peft import PromptTuningConfig, PromptTuningInit

In [ ]:
# Configure Prompt Tuning
prompt_config = PromptTuningConfig(
    task_type="CAUSAL_LM",
    num_virtual_tokens=20,
    prompt_tuning_init=PromptTuningInit.RANDOM,
    tokenizer_name_or_path=MODEL_NAME,
)

# Load model and apply Prompt Tuning
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    device_map="auto",
    dtype=torch.float32,
    low_cpu_mem_usage=True,
)

model = get_peft_model(model, prompt_config)
model.print_trainable_parameters()

# Training setup
monitor = EpochMonitor(model=model)
data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

training_args = TrainingArguments(
    output_dir="./gemma-3-270m-finetuned-qa-prompt",
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    gradient_accumulation_steps=1,
    learning_rate=3e-5,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_strategy="epoch",
    run_name="gemma-3-270m-qa-prompt",
    warmup_ratio=0.1,
    lr_scheduler_type="cosine",
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
    callbacks=[monitor],
)

print("Starting Prompt Tuning...")
trainer.train()
model.save_pretrained("./gemma-3-270m-finetuned-qa-prompt")
tokenizer.save_pretrained("./gemma-3-270m-finetuned-qa-prompt")
print("Prompt Tuning completed!")

Loading weights:   0%|          | 0/236 [00:00<?, ?it/s]

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 12,800 || all params: 268,110,976 || trainable%: 0.0048
Starting Prompt Tuning...
Initial Model Memory Footprint:
  Parameters: 268,110,976
  Precision: 4 bytes
  Total Memory: 3.81 GB
    - Parameters: 1.00 GB
    - KV Cache (est): 2.81 GB
  Estimated FLOPs per forward pass (batch=8, seq=512): 2.05 TFLOPS

============================================================
Epoch 0 Summary
============================================================
  Duration (s)         :         40.77
  Tokens Processed     :       684,032
  Throughput (token/s) :         16780
  Training Steps       :           167
  Avg CPU (%)          :          20.9
  Avg Memory (%)       :          13.5
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          8.40
  FLOPs (per token)    :   0.50 GFLOPS

============================================================
Epoch 1 Summary
============================================================
  Duration (s)         :         40.99
  Tokens Processed     :       684,032
  Throughput (token/s) :         16688
  Training Steps       :           167
  Avg CPU (%)          :          19.2
  Avg Memory (%)       :          13.4
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          8.36
  FLOPs (per token)    :   0.50 GFLOPS

============================================================
Epoch 2 Summary
============================================================
  Duration (s)         :         41.26
  Tokens Processed     :       684,032
  Throughput (token/s) :         16577
  Training Steps       :           167
  Avg CPU (%)          :          24.7
  Avg Memory (%)       :          13.5
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          8.30
  FLOPs (per token)    :   0.50 GFLOPS

============================================================
TRAINING COMPLETE
============================================================
Total Training Time: 137.66s
Total Epochs: 3
Average Epoch Time: 41.01s
Total Tokens Processed: 2,052,096
Average Throughput: 14907 tokens/second
Total FLOPs: 1027.47 TFLOPS
Average TFLOPS (per second): 7.46
Overall FLOPs (per token): 0.50 GFLOPS

Final Metrics:
Memory Footprint: 3.81 GB
Inference Throughput: 17399 tokens/second
Total Training FLOPs: 342.49 TFLOPS
Prompt Tuning completed!

In [26]:
summarize_training_results(trainer, monitor)

====================================================================================================
TRAINING RESULTS SUMMARY TABLE
====================================================================================================
Epoch Training Loss Validation Loss Time (s) Tokens Processed Throughput (token/s) TFLOPS (per second) Avg CPU (%) Avg Memory (%) Training Steps
    0        5.4567          4.7092    40.77          684,032                16779                8.40        20.9           13.5            167
    1        4.5212          4.0358    40.99          684,032                16688                8.36        19.2           13.4            167
    2        4.1327          3.9562    41.26          684,032                16577                8.30        24.7           13.5            167

----------------------------------------------------------------------------------------------------
TRAINING STATISTICS:
----------------------------------------------------------------------------------------------------
Total Training Time:      123.0 s
Average Epoch Time:       41.0 s
Total Tokens Processed:   2,052,096
Average Throughput:       16681 tokens/second
Average CPU Usage:        21.6%
Average Memory Usage:     13.5%
Total Training FLOPs:     1027.47 TFLOPS
Average TFLOPS (per sec): 8.35
Overall FLOPs (per token): 0.50 GFLOPS

====================================================================================================

**Reference** 
- [Huggingface:Prompt tuning](https://huggingface.co/docs/peft/en/package_reference/prompt_tuning)
- [Huggingface:Prompt Tuning With PEFT.](https://huggingface.co/learn/cookbook/en/prompt_tuning_peft)
- [Huggingface:Soft prompts](https://huggingface.co/docs/peft/en/conceptual_guides/prompting)

### Multi-task Prompt Sharing (P-Tuning v2)

Multi-task Prompt Sharing/Tuning, often implemented through architectures like P-Tuning v2, is an optimization technique where a shared bank of learnable "virtual tokens" is used to adapt a single frozen model to multiple related tasks simultaneously.

Instead of training a completely independent model or a large adapter for every task, this method learns a compressed, continuous representation (a prompt) that can be shared across a family of tasks (e.g., Q&A, summarization, and sentiment analysis). This approach maximizes the "knowledge transfer" between tasks while keeping the parameter count extremely low.

**How it Works**

The core of this method lies in using a re-parameterization network to generate the virtual tokens, rather than learning the embeddings directly.
- Deep Prompt Injection: Unlike basic prompt tuning that only stays at the input layer, this method (P-Tuning v2) injects learnable prompts into every layer of the transformer. This provides the "depth" needed to handle complex, multi-faceted tasks.
- The Prompt Encoder: A small auxiliary network (usually an MLP or LSTM) acts as an "encoder." This encoder takes a task identifier or a generic index and maps it into a high-dimensional continuous prefix.
- Knowledge Sharing: By training the encoder on a variety of datasets at once, the virtual tokens learn a "shared vocabulary" of instructions. For example, the latent representation for "extracting information" learned in a Q&A task can help the model perform better in a summarization task.
- Frozen Backbone: The massive foundation model remains 100% frozen. Only the small encoder network and the prompt vectors are updated, preventing "catastrophic forgetting" of the model's original capabilities.

**Implements Multi-task Prompt Sharing**

The provided script uses PromptEncoderConfig to set up a P-Tuning v2 architecture on Gemma-3-270m.

Configuring the Encoder:

    p_tuning_config = PromptEncoderConfig(
        task_type="CAUSAL_LM",
        num_virtual_tokens=20,
        encoder_hidden_size=128,
        encoder_num_layers=2,
    )

This defines a small 2-layer MLP (`encoder_num_layers=2`) with a bottleneck width of 128. This MLP is responsible for generating the 20 virtual tokens. Because this MLP is trainable, it can learn to produce different nuances in the prompt based on the input it receives during training.

**Deep Layer Adaptation:**

By using `PromptEncoderConfig`, the PEFT library automatically applies these virtual tokens across the hidden states of the model. This is more robust than simple prompt tuning because the "instruction" is reinforced at every step of the model's internal reasoning.

**Training Dynamics:**

The `learning_rate=2e-4` is relatively high compared to full fine-tuning. This is common in prompt-based methods because the optimizer needs to move the small number of trainable parameters more aggressively to "steer" the massive frozen model.

**When to Use It**

Multi-task Prompt Sharing/Tuning is the ideal choice for "Model-as-a-Service" (MaaS) platforms and complex system architectures:
- Shared Task Domains: When you have 5-10 tasks that are structurally similar (e.g., different types of medical entity extraction). The shared prompt bank allows the model to learn the "language of medicine" once and apply it to all sub-tasks.
- Massive Efficiency Requirements: If you need to serve hundreds of different fine-tuned capabilities from a single inference server. Swapping a P-Tuning v2 prefix is nearly instantaneous and requires negligible memory compared to swapping full models.
- Small Datasets for Specific Tasks: If Task A has 10,000 examples but Task B only has 100, the shared encoder allows Task B to "borrow" the structural understanding learned from Task A.
- Bypassing KV-Cache Limits: P-Tuning v2 is specifically optimized to be more stable than original Prefix Tuning in many implementations, making it a safer choice for newer architectures like Gemma-3.

In [ ]:
import torch
from datasets import Dataset, DatasetDict
from transformers import (
    AutoTokenizer, 
    AutoModelForCausalLM,
    DataCollatorForLanguageModeling,
    Trainer,
    TrainingArguments
)
from peft import PromptEncoderConfig

In [ ]:
# Configure P-Tuning v2
p_tuning_config = PromptEncoderConfig(
    task_type="CAUSAL_LM",
    num_virtual_tokens=20,
    encoder_hidden_size=128,
    encoder_num_layers=2,
    encoder_dropout=0.1,
)

# Load model and apply P-Tuning v2
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    device_map="auto",
    dtype=torch.float32,
    low_cpu_mem_usage=True,
)

model = get_peft_model(model, p_tuning_config)
model.print_trainable_parameters()

# Training setup
monitor = EpochMonitor(model=model)
data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

training_args = TrainingArguments(
    output_dir="./gemma-3-270m-finetuned-qa-p-tuning",
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    gradient_accumulation_steps=1,
    learning_rate=2e-4,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_strategy="epoch",
    run_name="gemma-3-270m-qa-p-tuning",
    warmup_ratio=0.1,
    lr_scheduler_type="cosine",
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
    callbacks=[monitor],
)

print("Starting P-Tuning v2 training...")
trainer.train()
model.save_pretrained("./gemma-3-270m-finetuned-qa-p-tuning")
tokenizer.save_pretrained("./gemma-3-270m-finetuned-qa-p-tuning")
print("P-Tuning v2 training completed!")

Loading weights:   0%|          | 0/236 [00:00<?, ?it/s]

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 193,920 || all params: 268,292,096 || trainable%: 0.0723
Starting P-Tuning v2 training...
Initial Model Memory Footprint:
  Parameters: 268,292,096
  Precision: 4 bytes
  Total Memory: 3.81 GB
    - Parameters: 1.00 GB
    - KV Cache (est): 2.81 GB
  Estimated FLOPs per forward pass (batch=8, seq=512): 2.05 TFLOPS

============================================================
Epoch 0 Summary
============================================================
  Duration (s)         :         41.18
  Tokens Processed     :       684,032
  Throughput (token/s) :         16610
  Training Steps       :           167
  Avg CPU (%)          :          23.9
  Avg Memory (%)       :          13.7
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          8.32
  FLOPs (per token)    :   0.50 GFLOPS

============================================================
Epoch 1 Summary
============================================================
  Duration (s)         :         41.07
  Tokens Processed     :       684,032
  Throughput (token/s) :         16656
  Training Steps       :           167
  Avg CPU (%)          :          20.8
  Avg Memory (%)       :          13.8
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          8.34
  FLOPs (per token)    :   0.50 GFLOPS

============================================================
Epoch 2 Summary
============================================================
  Duration (s)         :         40.89
  Tokens Processed     :       684,032
  Throughput (token/s) :         16729
  Training Steps       :           167
  Avg CPU (%)          :          22.4
  Avg Memory (%)       :          13.7
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          8.38
  FLOPs (per token)    :   0.50 GFLOPS

============================================================
TRAINING COMPLETE
============================================================
Total Training Time: 137.43s
Total Epochs: 3
Average Epoch Time: 41.05s
Total Tokens Processed: 2,052,096
Average Throughput: 14932 tokens/second
Total FLOPs: 1027.47 TFLOPS
Average TFLOPS (per second): 7.48
Overall FLOPs (per token): 0.50 GFLOPS

Final Metrics:
Memory Footprint: 3.81 GB
Inference Throughput: 17370 tokens/second
Total Training FLOPs: 342.49 TFLOPS
P-Tuning v2 training completed!

In [28]:
summarize_training_results(trainer, monitor)

====================================================================================================
TRAINING RESULTS SUMMARY TABLE
====================================================================================================
Epoch Training Loss Validation Loss Time (s) Tokens Processed Throughput (token/s) TFLOPS (per second) Avg CPU (%) Avg Memory (%) Training Steps
    0        3.0523          3.0624    41.18          684,032                16609                8.32        23.9           13.7            167
    1        2.8480          3.0299    41.07          684,032                16655                8.34        20.8           13.8            167
    2        2.8062          3.0161    40.89          684,032                16729                8.38        22.4           13.7            167

----------------------------------------------------------------------------------------------------
TRAINING STATISTICS:
----------------------------------------------------------------------------------------------------
Total Training Time:      123.1 s
Average Epoch Time:       41.0 s
Total Tokens Processed:   2,052,096
Average Throughput:       16665 tokens/second
Average CPU Usage:        22.4%
Average Memory Usage:     13.7%
Total Training FLOPs:     1027.47 TFLOPS
Average TFLOPS (per sec): 8.34
Overall FLOPs (per token): 0.50 GFLOPS

====================================================================================================

**Reference** 
- [Huggingface:Prompt tuning](https://huggingface.co/docs/peft/en/package_reference/prompt_tuning)
- [Huggingface:Prompt Tuning With PEFT.](https://huggingface.co/learn/cookbook/en/prompt_tuning_peft)
- [Arxiv:P-Tuning v2: Prompt Tuning Can Be Comparable to Fine-tuning Universally Across Scales and Tasks](https://arxiv.org/pdf/2110.07602)
- [APXML:Prompt Tuning and P-Tuning Variations](https://apxml.com/courses/lora-peft-efficient-llm-training/chapter-3-peft-methodologies-survey/prompt-tuning-variations)
- [Medium:Prompt Tuning: A New Approach to Large Language Model Specialization](https://medium.com/@tahirbalarabe2/prompt-tuning-a-new-approach-to-language-model-specialization-6abd12cea528)

## Prefix Tuning Improvements

### Depth-Adaptive Prefixes

Depth-Adaptive Prefixes (DAP) is an advanced optimization strategy for Prefix Tuning that breaks the standard "one-size-fits-all" rule for transformer layers. Instead of prepending a prefix of the same length to every layer, DAP assigns variable-length prefixes based on the representational needs of different depths in the model.

In a standard transformer, early layers often focus on shallow syntactic patterns, while deeper layers handle complex semantic reasoning. Depth-Adaptive Prefixes exploit this by using shorter prefixes where less guidance is needed and longer prefixes in critical layers, maximizing performance while minimizing the total number of trainable parameters.

**How it Works**

The core principle of DAP is Resource Allocation across the model's depth.
- Layer Sensitivity: Researchers have found that the middle and late layers of an LLM typically have the most influence on task-specific output. DAP assigns a "budget" of virtual tokens to each layer accordingly.
- The Gating Mechanism: Most DAP implementations use a small gate network or a learned scaling factor for each layer. This gate determines how many prefix tokens are "active" for that specific layer during the forward pass.
- Variable Dimensionality: Mathematically, for a layer $L$, the prefix $P_L$ has a shape of $(n_L \times d)$, where $n_L$ is the layer-specific prefix length and $d$ is the hidden dimension. In standard prefix tuning, $n$ is constant; in DAP, $n$ is a function of the layer index.
- Information Filtering: This allows the model to "filter" the task-specific information. An early layer might only need 2 tokens to identify the language, while a deep layer might need 30 tokens to handle logical reasoning.

**Implements DAP (via Stability Logic)**

The provided code uses a PromptTuningConfig as a "stable alternative" to implement the foundations of depth-aware adaptation on Gemma-3-270m.

**Bypassing KV-Cache Complexity:**

    prompt_config = PromptTuningConfig(
    num_virtual_tokens=20,
    prompt_tuning_init=PromptTuningInit.RANDOM,
    )

While true Depth-Adaptive Prefixes modify the internal attention layers, the code chooses **Input-Level Prompt Tuning**. This is a "Depth-Adaptive" strategy in a different sense: it lets the model decide through its own attention mechanism which layers should pay the most attention to the 20 virtual tokens. 

**Layer-Independent Weights:**

Because the base model is frozen and the virtual tokens are only at the input, the model's internal weights naturally "adapt" the influence of these tokens as they pass through the layers. This avoids the common "KV cache bugs" found in newer models like Gemma-3 when attempting to force different prefix lengths into the deep attention layers.

**Memory and Efficiency:**

By using `torch.bfloat16` and `gradient_checkpointing=True`, the code ensures that even with the overhead of managing these virtual tokens, the training remains stable on consumer hardware.

**When to Use It**

Depth-Adaptive strategies are best when precision and efficiency must be perfectly balanced:
- Low-Resource Finetuning: If you have a very strict parameter budget (e.g., you can only afford 50k trainable parameters), DAP allows you to put those parameters in the layers where they actually matter, rather than wasting them on the first few layers.
- Complex Multi-Step Tasks: For tasks like mathematical reasoning or multi-turn dialogue, where different stages of the transformer handle different parts of the logic, DAP provides the necessary flexibility.
- Inference Latency Sensitivity: In production environments, shorter prefixes in early layers reduce the computation time for the Key-Value (KV) cache, leading to slightly faster "Time to First Token" (TTFT).
- Mitigating Overfitting: By reducing the number of trainable parameters in less sensitive layers, DAP acts as a form of architectural regularization, preventing the model from memorizing noise in the training data.

In [ ]:
import torch
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    Trainer,
    TrainingArguments,
    DataCollatorForLanguageModeling,
)
from datasets import DatasetDict, Dataset
from peft import PromptTuningConfig, PromptTuningInit, get_peft_model

In [29]:
# Configuration
MODEL_NAME = "google/gemma-3-270m"
OUTPUT_DIR = "./gemma-3-270m-finetuned-qa-prompt-tuning"

# Prompt Tuning Config (more stable alternative)
prompt_config = PromptTuningConfig(
    task_type="CAUSAL_LM",
    num_virtual_tokens=20,
    prompt_tuning_init=PromptTuningInit.RANDOM,
    tokenizer_name_or_path=MODEL_NAME,
)

# Load model
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    device_map="auto",
    dtype=torch.bfloat16,  # Use bfloat16 for efficiency
    low_cpu_mem_usage=True,
)

# Apply prompt tuning
model = get_peft_model(model, prompt_config)
model.print_trainable_parameters()

# Training setup
monitor = EpochMonitor(model=model)
data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

# Calculate warmup steps
total_steps = len(dataset_dict["train"]) * 3 // (4 * 2)  # batch_size=4, grad_acc=2
warmup_steps = int(total_steps * 0.1)

training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    gradient_accumulation_steps=2,
    learning_rate=3e-4,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_strategy="epoch",
    run_name="gemma-3-270m-prompt-tuning",
    warmup_steps=warmup_steps,
    lr_scheduler_type="cosine",
    gradient_checkpointing=True,
    bf16=True,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
    callbacks=[monitor],
)

print("Starting Prompt Tuning on Gemma-3-270m...")
trainer.train()

model.save_pretrained(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)
print("Prompt Tuning completed successfully!")

Loading weights:   0%|          | 0/236 [00:00<?, ?it/s]

trainable params: 12,800 || all params: 268,110,976 || trainable%: 0.0048
Starting Prompt Tuning on Gemma-3-270m...
Initial Model Memory Footprint:
  Parameters: 268,110,976
  Precision: 2 bytes
  Total Memory: 1.91 GB
    - Parameters: 0.50 GB
    - KV Cache (est): 1.41 GB
  Estimated FLOPs per forward pass (batch=8, seq=512): 2.05 TFLOPS

============================================================
Epoch 0 Summary
============================================================
  Duration (s)         :         47.81
  Tokens Processed     :       342,016
  Throughput (token/s) :          7153
  Training Steps       :           167
  Avg CPU (%)          :          19.4
  Avg Memory (%)       :          13.6
  Total FLOPs          : 171.25 TFLOPS
  TFLOPS (per second)  :          3.58
  FLOPs (per token)    :   0.50 GFLOPS

============================================================
Epoch 1 Summary
============================================================
  Duration (s)         :         49.05
  Tokens Processed     :       342,016
  Throughput (token/s) :          6973
  Training Steps       :           167
  Avg CPU (%)          :          25.9
  Avg Memory (%)       :          13.6
  Total FLOPs          : 171.25 TFLOPS
  TFLOPS (per second)  :          3.49
  FLOPs (per token)    :   0.50 GFLOPS

============================================================
Epoch 2 Summary
============================================================
  Duration (s)         :         47.74
  Tokens Processed     :       342,016
  Throughput (token/s) :          7165
  Training Steps       :           167
  Avg CPU (%)          :          20.6
  Avg Memory (%)       :          13.6
  Total FLOPs          : 171.25 TFLOPS
  TFLOPS (per second)  :          3.59
  FLOPs (per token)    :   0.50 GFLOPS

============================================================
TRAINING COMPLETE
============================================================
Total Training Time: 155.97s
Total Epochs: 3
Average Epoch Time: 48.20s
Total Tokens Processed: 1,026,048
Average Throughput: 6578 tokens/second
Total FLOPs: 513.74 TFLOPS
Average TFLOPS (per second): 3.29
Overall FLOPs (per token): 0.50 GFLOPS

Final Metrics:
Memory Footprint: 1.91 GB
Inference Throughput: 7503 tokens/second
Total Training FLOPs: 171.25 TFLOPS
Prompt Tuning completed successfully!

In [30]:
summarize_training_results(trainer, monitor)

====================================================================================================
TRAINING RESULTS SUMMARY TABLE
====================================================================================================
Epoch Training Loss Validation Loss Time (s) Tokens Processed Throughput (token/s) TFLOPS (per second) Avg CPU (%) Avg Memory (%) Training Steps
    0        4.0619          3.3960    47.81          342,016                 7152                3.58        19.4           13.6            167
    1        3.2509          3.3222    49.05          342,016                 6972                3.49        25.9           13.6            167
    2        3.2031          3.3134    47.74          342,016                 7164                3.59        20.6           13.6            167

----------------------------------------------------------------------------------------------------
TRAINING STATISTICS:
----------------------------------------------------------------------------------------------------
Total Training Time:      144.6 s
Average Epoch Time:       48.2 s
Total Tokens Processed:   1,026,048
Average Throughput:       7096 tokens/second
Average CPU Usage:        22.0%
Average Memory Usage:     13.6%
Total Training FLOPs:     513.74 TFLOPS
Average TFLOPS (per sec): 3.55
Overall FLOPs (per token): 0.50 GFLOPS

====================================================================================================

**Reference** 
- [Huggingface:Prompt tuning](https://huggingface.co/docs/peft/en/package_reference/prompt_tuning)
- [Huggingface:Prompt Tuning With PEFT.](https://huggingface.co/learn/cookbook/en/prompt_tuning_peft)
- [Arxiv:How Do LLMs Use Their Depth?](https://arxiv.org/html/2510.18871v1)
- [ResearchGate:Towards Adaptive Prefix Tuning for Parameter-Efficient Language Model Fine-tuning](https://www.researchgate.net/publication/371009825_Towards_Adaptive_Prefix_Tuning_for_Parameter-Efficient_Language_Model_Fine-tuning)

### Attention-Guided Prefix Allocation

Attention-Guided Prefix Allocation is an optimization strategy for Prefix Tuning based on the observation that not all layers in a transformer contribute equally to a task. In a standard transformer, specific layers (often middle and late layers) exhibit higher "attention intensity" or sensitivity to task-specific signals.

This method focuses the parameter budget on these high-attention layers. Instead of spreading a small number of parameters thinly across the entire model depth, it concentrates more trainable capacity where the model’s internal attention mechanism is most active, leading to more effective steering of the model's behavior.

**How it Works**

The mechanism relies on identifying and reinforcing the most influential layers of the LLM.
- Attention Analysis: Before or during training, the model's attention maps are analyzed to determine which layers are "bottlenecks" or key decision-makers for the specific dataset.
- Weighted Allocation: Rather than using a fixed length for all prefixes, high-attention layers receive a deeper or more complex prefix representation. This is often achieved through a Prefix Projection (an MLP encoder) that maps the virtual tokens into the specific hidden space of those layers.
- Cross-Layer Influence: By prepending learnable Key (K) and Value (V) vectors to the attention blocks, the prefixes act as a "soft" cache. In layers with high attention scores, these soft caches exert a stronger influence on the final representation of each token, essentially "re-programming" the layer's output.
- Parameter Efficiency: By concentrating parameters in critical layers, the model achieves better performance with fewer total trainable parameters compared to full fine-tuning or even uniform LoRA.

**Implements Attention-Guided Prefix Allocation**

The script utilizes PrefixTuningConfig with a specific focus on structural stability and representational depth.

**Enabling the Prefix Projection:**

    prefix_config = PrefixTuningConfig(
        num_virtual_tokens=30,
        prefix_projection=True, # <- Critical for representational depth
        encoder_hidden_size=model.config.n_embd,
    )
    
Setting `prefix_projection=True` is the engine for guided allocation. It creates a two-layer MLP (bottleneck network) that generates the actual prefixes. This allows the model to learn a complex mapping from the 30 virtual tokens to the specific attention requirements of each layer. Layers that "demand" more steering will naturally cause the optimizer to adjust the weights of this projection to provide more meaningful prefix vectors for those specific depths.

**Fixed Attention Implementation:**

    attn_implementation="eager"

The code forces the "eager" attention implementation. This is necessary because modern optimizations like Flash Attention or SDPA can sometimes obscure the specific attention masks required for prefix tuning. By using "eager" mode, the model ensures that the prefixes are correctly injected into every attention head, allowing the guided allocation logic to function without mask shape errors.

**Stability over Speed:**

Using `fp16=False` (full `float32`) ensures that the gradients for the prefix vectors remain stable. Since prefixes are highly sensitive to small updates, high precision allows the attention-guided steering to converge more reliably.

**When to Use It**

Attention-Guided Prefix Allocation is most effective in the following scenarios:
- Fine-Tuning Small Models: In models like GPT-2, every parameter counts. Guiding the prefix allocation ensures that the limited parameter budget isn't wasted on early layers that only handle basic tokenization.
- Highly Specialized Tasks: For tasks with very rigid formats (like SQL generation or medical coding), specific middle layers often handle the structural "rules." This method reinforces those layers specifically.
- Resource-Constrained Inference: If the total VRAM available for adapters is strictly limited, this method provides the highest "intelligence-per-byte" by only placing parameters where they have the most impact on the attention mechanism.
- Mitigating Catastrophic Forgetting: Because the model weights are 100% frozen and the prefixes only guide the attention, the model is very unlikely to lose its general knowledge, making it ideal for continuous learning applications.

In [ ]:
import torch
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    Trainer,
    TrainingArguments,
    DataCollatorForLanguageModeling,
)
from peft import PrefixTuningConfig, get_peft_model
from datasets import DatasetDict, Dataset
import gc

In [37]:
# Configuration
MODEL_NAME = "openai-community/gpt2"
OUTPUT_DIR = "./openai-community-gpt2-attention-prefix"
MAX_LENGTH = 128
NUM_VIRTUAL_TOKENS = 30

# Tokenizer
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
tokenizer.pad_token = tokenizer.eos_token

def tokenize_examples(data, max_length=MAX_LENGTH):
    texts = [
        f"<bos>Question: {row['question_title']}\n{row['question_body']}\nAnswer: {row['answer']}<eos>"
        for row in data.iter_rows(named=True)
    ]
    tokenized = tokenizer(
        texts,
        truncation=True,
        max_length=max_length,
        padding="max_length",
        return_tensors="pt"
    )
    tokenized["labels"] = tokenized["input_ids"].clone()
    tokenized["labels"][tokenized["labels"] == tokenizer.pad_token_id] = -100
    return tokenized

# ------------------- Data -------------------
train_tokenized = tokenize_examples(train_data)
val_tokenized = tokenize_examples(val_data)

dataset_dict = DatasetDict({
    "train": Dataset.from_dict(train_tokenized),
    "validation": Dataset.from_dict(val_tokenized)
})

print(f"Train examples: {len(dataset_dict['train']):,}")
print(f"Validation examples: {len(dataset_dict['validation']):,}")

Train examples: 1,331
Validation examples: 285

In [38]:
# Load Model & Apply Prefix Tuning 
print(f"Loading model: {MODEL_NAME}")
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    torch_dtype=torch.float32,
    device_map="auto",
    low_cpu_mem_usage=True,
    attn_implementation="eager",   # SDPA mask shape error with prefix tuning
)

prefix_config = PrefixTuningConfig(
    task_type="CAUSAL_LM",
    num_virtual_tokens=NUM_VIRTUAL_TOKENS,
    prefix_projection=True,
    encoder_hidden_size=model.config.n_embd,
)

model = get_peft_model(model, prefix_config)
model.print_trainable_parameters()

monitor = EpochMonitor(model=model)

# Training Arguments
training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    gradient_accumulation_steps=8,
    learning_rate=1e-4,
    weight_decay=0.01,
    max_grad_norm=0.5,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_steps=20,
    warmup_steps=100,
    lr_scheduler_type="cosine",
    fp16=False,                        # full fp32 for maximum stability
    optim="adamw_torch",
    gradient_checkpointing=True,
    gradient_checkpointing_kwargs={"use_reentrant": False},
    dataloader_num_workers=2,
    dataloader_pin_memory=True,
)

# Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=DataCollatorForLanguageModeling(
        tokenizer=tokenizer,
        mlm=False,
        pad_to_multiple_of=8
    ),
    callbacks = [monitor]
)

torch.cuda.empty_cache()

print("Starting Prefix Tuning fine-tuning...")
trainer.train()

print("\nSaving PEFT adapter and tokenizer...")
model.save_pretrained(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)

print("Training completed!")
print(f"Model saved to: {OUTPUT_DIR}")

Loading model: openai-community/gpt2

Loading weights:   0%|          | 0/148 [00:00<?, ?it/s]

GPT2LMHeadModel LOAD REPORT from: openai-community/gpt2
Key                  | Status     |  |
---------------------+------------+--+-
h.{0...11}.attn.bias | UNEXPECTED |  |

Notes:
- UNEXPECTED	:can be ignored when loading from different task/architecture; not ok if you expect identical arch.

trainable params: 14,787,840 || all params: 139,227,648 || trainable%: 10.6213
Starting Prefix Tuning fine-tuning...
Initial Model Memory Footprint:
  Parameters: 139,227,648
  Precision: 4 bytes
  Total Memory: 0.59 GB
    - Parameters: 0.52 GB
    - KV Cache (est): 0.07 GB
  Estimated FLOPs per forward pass (batch=8, seq=512): 1.05 TFLOPS

============================================================
Epoch 0 Summary
============================================================
  Duration (s)         :        23.06
  Tokens Processed     :       86,016
  Throughput (token/s) :         3730
  Training Steps       :           42
  Avg CPU (%)          :         22.8
  Avg Memory (%)       :         12.8
  Total FLOPs          : 22.06 TFLOPS
  TFLOPS (per second)  :         0.96
  FLOPs (per token)    :  0.26 GFLOPS

============================================================
Epoch 1 Summary
============================================================
  Duration (s)         :        23.17
  Tokens Processed     :       86,016
  Throughput (token/s) :         3712
  Training Steps       :           42
  Avg CPU (%)          :         24.3
  Avg Memory (%)       :         12.8
  Total FLOPs          : 22.06 TFLOPS
  TFLOPS (per second)  :         0.95
  FLOPs (per token)    :  0.26 GFLOPS

============================================================
Epoch 2 Summary
============================================================
  Duration (s)         :        23.22
  Tokens Processed     :       86,016
  Throughput (token/s) :         3704
  Training Steps       :           42
  Avg CPU (%)          :         24.8
  Avg Memory (%)       :         12.7
  Total FLOPs          : 22.06 TFLOPS
  TFLOPS (per second)  :         0.95
  FLOPs (per token)    :  0.26 GFLOPS

============================================================
TRAINING COMPLETE
============================================================
Total Training Time: 76.45s
Total Epochs: 3
Average Epoch Time: 23.15s
Total Tokens Processed: 258,048
Average Throughput: 3375 tokens/second
Total FLOPs: 66.19 TFLOPS
Average TFLOPS (per second): 0.87
Overall FLOPs (per token): 0.26 GFLOPS

Final Metrics:
Memory Footprint: 0.59 GB
Inference Throughput: 3874 tokens/second
Total Training FLOPs: 22.06 TFLOPS

Saving PEFT adapter and tokenizer...
Training completed!
Model saved to: ./openai-community-gpt2-attention-prefix

**Reference** 
- [Huggingface:Prefix tuning](https://huggingface.co/docs/peft/en/package_reference/prefix_tuning)
- [Huggingface:Prefix tuning for conditional generation](https://huggingface.co/docs/peft/v0.6.0/en/task_guides/seq2seq-prefix-tuning)
- [Arxiv:PAT: Accelerating LLM Decoding via Prefix-Aware Attention with Resource Efficient Multi-Tile Kernel](https://arxiv.org/html/2511.22333v1)

### Prompt Compression (Quantized Prompts)

Prompt Compression in the context of PEFT refers to the application of compression techniques—specifically pruning and quantization—to the learned "soft" prompt vectors. While standard prompt tuning already reduces the number of trainable parameters, Prompt Compression further shrinks the storage and memory footprint of these remaining parameters.

By converting the high-precision floating-point embeddings of the virtual tokens into lower-precision formats (like 4-bit or 8-bit), the model can store thousands of task-specific adapters with negligible disk space and faster retrieval times during inference.

**How it Works**

Prompt Compression targets the learned embedding matrix that contains the virtual tokens.
- Quantization: The continuous values in the soft prompt are mapped from a wide range (e.g., 32-bit float) to a discrete set of levels (e.g., 4-bit integers). This uses techniques like NormalFloat (NF4) to ensure that the distribution of the learned values is preserved as accurately as possible.
- Pruning (Optional): This involves identifying "dead" or low-impact dimensions within the virtual tokens and setting them to zero. This simplifies the mathematical influence of the prompt on the model's attention mechanism.
- Low-Bit Optimization: During training, the gradients are calculated in higher precision, but the "master" copy of the prompt is stored and updated in its compressed form. This ensures that the learned prompt is inherently robust to the noise introduced by compression.

**Implements Prompt Compression**

The provided script manually injects 4-bit quantization into the Prompt Tuning workflow using the bitsandbytes library.

**Targeted Parameter Injection:**

    for name, param in model.named_parameters():
        if "prompt_embeddings" in name:
            param.data = bnb.nn.Params4bit(param.data, requires_grad=True, compress_statistics=True)

After setting up standard Prompt Tuning, the code iterates through the model's parameters to find the `prompt_embeddings`. It then overwrites the standard tensor with a `Params4bit` object. This effectively "squashes" the 20 virtual tokens into a 4-bit representation before training even begins.

**Double Quantization:**

By setting `compress_statistics=True`, the code enables a second layer of quantization on the scaling constants of the prompt embeddings. This is the same logic used in QLoRA, but applied exclusively to the tiny prompt matrix.

**Stability during Training:**

The use of `dtype=torch.float32` for the base model loading ensures that while the prompt is compressed, the actual computations remain numerically stable. The Trainer will handle the "de-quantization" of the prompt on the fly during each forward pass.

**When to Use It**

Prompt Compression is the most extreme form of optimization for high-density AI environments:
- Ultra-Massive Multi-Tenancy: If a single server needs to store and swap between tens of thousands of fine-tuned prompts (e.g., a personalized chatbot for every customer), Prompt Compression ensures that these "adapter files" are only a few kilobytes each.
- Edge and IoT Deployment: On devices with extremely limited RAM and disk space, every byte saved on the prompt allows for a slightly larger context window or a more complex base model.
- Fast Model Switching: Lower-precision prompts can be loaded from disk to GPU memory faster than full-precision ones, reducing the "cold start" latency when switching tasks.
- Regularization: In some cases, quantizing the prompt acts as a regularizer. Because the model can't rely on hyper-precise floating-point values to memorize the training data, it is forced to learn more robust, generalized features.

In [ ]:
import torch
from datasets import Dataset, DatasetDict
from transformers import (
    AutoTokenizer, 
    AutoModelForCausalLM,
    DataCollatorForLanguageModeling,
    Trainer,
    TrainingArguments
)
from peft import PromptTuningConfig, PromptTuningInit
import bitsandbytes as bnb

In [30]:
# Configure Prompt Tuning with Quantization
prompt_config = PromptTuningConfig(
    task_type="CAUSAL_LM",
    num_virtual_tokens=20,
    prompt_tuning_init=PromptTuningInit.RANDOM,
    tokenizer_name_or_path=MODEL_NAME,
)

# Load model
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    device_map="auto",
    dtype=torch.float32,
    low_cpu_mem_usage=True,
)

# Apply quantization to prompt embeddings only
model = get_peft_model(model, prompt_config)

# Quantize prompt embeddings to 8-bit
for name, param in model.named_parameters():
    if "prompt_embeddings" in name:
        param.data = bnb.nn.Params4bit(param.data, requires_grad=True, compress_statistics=True)

model.print_trainable_parameters()

# Training setup
monitor = EpochMonitor(model=model)
data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

training_args = TrainingArguments(
    output_dir="./gemma-3-270m-finetuned-qa-quantized-prompt",
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    gradient_accumulation_steps=1,
    learning_rate=3e-5,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_strategy="epoch",
    run_name="gemma-3-270m-qa-quantized-prompt",
    warmup_ratio=0.1,
    lr_scheduler_type="cosine",
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
    callbacks=[monitor],
)

print("Starting Quantized Prompt Tuning...")
trainer.train()
model.save_pretrained("./gemma-3-270m-finetuned-qa-quantized-prompt")
tokenizer.save_pretrained("./gemma-3-270m-finetuned-qa-quantized-prompt")
print("Quantized Prompt Tuning completed!")

Loading weights:   0%|          | 0/236 [00:00<?, ?it/s]

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 12,800 || all params: 268,110,976 || trainable%: 0.0048
Starting Quantized Prompt Tuning...
Initial Model Memory Footprint:
  Parameters: 268,110,976
  Precision: 4 bytes
  Total Memory: 3.81 GB
    - Parameters: 1.00 GB
    - KV Cache (est): 2.81 GB
  Estimated FLOPs per forward pass (batch=8, seq=512): 2.05 TFLOPS

============================================================
Epoch 0 Summary
============================================================
  Duration (s)         :         39.05
  Tokens Processed     :       684,032
  Throughput (token/s) :         17517
  Training Steps       :           167
  Avg CPU (%)          :          21.7
  Avg Memory (%)       :          11.5
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          8.77
  FLOPs (per token)    :   0.50 GFLOPS

============================================================
Epoch 1 Summary
============================================================
  Duration (s)         :         40.57
  Tokens Processed     :       684,032
  Throughput (token/s) :         16863
  Training Steps       :           167
  Avg CPU (%)          :          18.9
  Avg Memory (%)       :          11.5
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          8.44
  FLOPs (per token)    :   0.50 GFLOPS

============================================================
Epoch 2 Summary
============================================================
  Duration (s)         :         40.97
  Tokens Processed     :       684,032
  Throughput (token/s) :         16697
  Training Steps       :           167
  Avg CPU (%)          :          22.8
  Avg Memory (%)       :          11.5
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          8.36
  FLOPs (per token)    :   0.50 GFLOPS

============================================================
TRAINING COMPLETE
============================================================
Total Training Time: 134.91s
Total Epochs: 3
Average Epoch Time: 40.19s
Total Tokens Processed: 2,052,096
Average Throughput: 15211 tokens/second
Total FLOPs: 1027.47 TFLOPS
Average TFLOPS (per second): 7.62
Overall FLOPs (per token): 0.50 GFLOPS

Final Metrics:
Memory Footprint: 3.81 GB
Inference Throughput: 17357 tokens/second
Total Training FLOPs: 342.49 TFLOPS
Quantized Prompt Tuning completed!

In [31]:
summarize_training_results(trainer, monitor)

====================================================================================================
TRAINING RESULTS SUMMARY TABLE
====================================================================================================
Epoch Training Loss Validation Loss Time (s) Tokens Processed Throughput (token/s) TFLOPS (per second) Avg CPU (%) Avg Memory (%) Training Steps
    0        5.4567          4.7092    39.05          684,032                17516                8.77        21.7           11.5            167
    1        4.5212          4.0358    40.57          684,032                16862                8.44        18.9           11.5            167
    2        4.1327          3.9562    40.97          684,032                16697                8.36        22.8           11.5            167

----------------------------------------------------------------------------------------------------
TRAINING STATISTICS:
----------------------------------------------------------------------------------------------------
Total Training Time:      120.6 s
Average Epoch Time:       40.2 s
Total Tokens Processed:   2,052,096
Average Throughput:       17018 tokens/second
Average CPU Usage:        21.1%
Average Memory Usage:     11.5%
Total Training FLOPs:     1027.47 TFLOPS
Average TFLOPS (per sec): 8.52
Overall FLOPs (per token): 0.50 GFLOPS

====================================================================================================

**Reference** 
- [Huggingface:Prompt tuning](https://huggingface.co/docs/peft/en/package_reference/prompt_tuning)
- [Huggingface:Prompt Tuning With PEFT.](https://huggingface.co/learn/cookbook/en/prompt_tuning_peft)
- [Arxiv:CompactPrompt: A Unified Pipeline for Prompt and Data Compression in LLM Workflows](https://arxiv.org/html/2510.18043v1)

### Hierarchical Prompt Structures

Hierarchical Prompt Structures is a parameter-efficient fine-tuning (PEFT) strategy that organizes virtual tokens into different functional groups to steer a model more effectively. Instead of treating all soft prompt tokens as a monolithic block, a hierarchical approach distinguishes between global tokens (which capture general task intent, like "Question Answering") and local tokens (which handle specific nuances or instance-level details).

This method mimics the way humans provide instructions: first defining the broad category of the task and then providing specific constraints or context. By structuring the prompt this way, the model can learn broader patterns that generalize across the dataset while maintaining enough flexibility to handle specific variations.

**How it Works**

Hierarchical prompting leverages the transformer's attention mechanism to create a "ladder" of information.
- Functional Division: The virtual token budget is split. The first set of tokens (global) learns high-level semantic signals, while the second set (local) focuses on finer adjustments to the model's internal activations.
- Semantic Initialization: Rather than starting with random noise, these prompts are often initialized with task-relevant text. This anchors the hierarchy in real-world concepts (e.g., initializing with "Question: Answer:" ensures the global tokens start in a region of the embedding space associated with inquiry).
- Layer-Wise Interaction: As these tokens pass through the model's layers, the hierarchy allows the model to "attend" to broad task instructions in early layers and more specific steering signals in later, more sensitive layers.
- Frozen Backbone Stability: By keeping the base LLM frozen, the hierarchical structure ensures that the learned "instruction" doesn't degrade the model's foundational knowledge, only guides how that knowledge is accessed.

**Implements Hierarchical Prompting**

The script utilizes PromptTuningConfig to establish a multi-token steering signal for Gemma-3-270m.

**Expanded Token Budget:**

    num_virtual_tokens=30,  # Total tokens: 10 global + 20 local

By increasing the token count to 30, the configuration provides enough "real estate" for the model to develop a hierarchical representation. The first 10 tokens naturally tend to stabilize as task-level identifiers, while the remaining 20 adapt to the specific dataset patterns.

**Task-Relevant Anchoring:**

    prompt_tuning_init_text="Question: Answer:",

This is a key differentiator. By initializing with these specific strings, the code provides a "semantic backbone." The virtual tokens aren't just arbitrary numbers; they are offsets from the embeddings of "Question:" and "Answer:". This forces the hierarchy to start within a logical context, leading to faster and more stable convergence.

**Precision and Stability:**

Using `dtype=torch.float32` and a `learning_rate=2e-4` allows the hierarchical tokens to be updated with high precision. This is critical because hierarchical structures rely on subtle differences between the global and local token groups.

**When to Use It**

Hierarchical Prompt Structures are particularly beneficial in these scenarios:
- Multi-Faceted Datasets: When the training data contains diverse types of questions (e.g., some requiring short answers, others requiring long explanations), a hierarchical prompt can learn to handle both the "General Q&A" logic and the "Specific Formatting" logic.
- Bridging the Gap to Full Fine-Tuning: If simple prompt tuning feels too "weak" to move the model's performance, adding hierarchy and more tokens provides the extra expressiveness needed to capture complex task behaviors.
- High-Sensitivity Architectures: Smaller models like Gemma-3-270m are more sensitive to input perturbations. A structured, semantically-initialized prompt is less likely to "confuse" the model than a block of 30 random virtual tokens.
- Zero-Shot Generalization: Models trained with hierarchical prompts often generalize better to unseen but related tasks because the "global" portion of the prompt captures the overarching task essence that remains constant.

In [ ]:
from peft import PromptTuningConfig

import torch
from datasets import Dataset, DatasetDict
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    DataCollatorForLanguageModeling,
    Trainer,
    TrainingArguments,
)
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training

In [32]:
# Configuration
MODEL_NAME = "google/gemma-3-270m"
OUTPUT_DIR = "./gemma-3-270m-finetuned-qa-dora"

# Configure Hierarchical Prompt Tuning
hierarchical_config = PromptTuningConfig(
    task_type="CAUSAL_LM",
    num_virtual_tokens=30,  # Total tokens: 10 global + 20 local
    prompt_tuning_init_text="Question: Answer:",  # Initialize with task-relevant text
    tokenizer_name_or_path=MODEL_NAME,
)

# Load model and apply Hierarchical Prompt Tuning
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    device_map="auto",
    dtype=torch.float32,
    low_cpu_mem_usage=True,
)

model = get_peft_model(model, hierarchical_config)
model.print_trainable_parameters()

# Training setup
monitor = EpochMonitor(model=model)
data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

training_args = TrainingArguments(
    output_dir="./gemma-3-270m-finetuned-qa-hierarchical",
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    gradient_accumulation_steps=1,
    learning_rate=2e-4,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_strategy="epoch",
    run_name="gemma-3-270m-qa-hierarchical",
    warmup_ratio=0.1,
    lr_scheduler_type="cosine",
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
    callbacks=[monitor],
)

print("Starting Hierarchical Prompt Tuning...")
trainer.train()
model.save_pretrained("./gemma-3-270m-finetuned-qa-hierarchical")
tokenizer.save_pretrained("./gemma-3-270m-finetuned-qa-hierarchical")
print("Hierarchical Prompt Tuning completed!")

Loading weights:   0%|          | 0/236 [00:00<?, ?it/s]

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 19,200 || all params: 268,117,376 || trainable%: 0.0072
Starting Hierarchical Prompt Tuning...
Initial Model Memory Footprint:
  Parameters: 268,117,376
  Precision: 4 bytes
  Total Memory: 3.81 GB
    - Parameters: 1.00 GB
    - KV Cache (est): 2.81 GB
  Estimated FLOPs per forward pass (batch=8, seq=512): 2.05 TFLOPS

============================================================
Epoch 0 Summary
============================================================
  Duration (s)         :         43.76
  Tokens Processed     :       684,032
  Throughput (token/s) :         15632
  Training Steps       :           167
  Avg CPU (%)          :          23.6
  Avg Memory (%)       :          12.1
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          7.83
  FLOPs (per token)    :   0.50 GFLOPS

============================================================
Epoch 1 Summary
============================================================
  Duration (s)         :         43.44
  Tokens Processed     :       684,032
  Throughput (token/s) :         15747
  Training Steps       :           167
  Avg CPU (%)          :          22.4
  Avg Memory (%)       :          12.1
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          7.88
  FLOPs (per token)    :   0.50 GFLOPS

============================================================
Epoch 2 Summary
============================================================
  Duration (s)         :         43.50
  Tokens Processed     :       684,032
  Throughput (token/s) :         15723
  Training Steps       :           167
  Avg CPU (%)          :          21.0
  Avg Memory (%)       :          12.2
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          7.87
  FLOPs (per token)    :   0.50 GFLOPS

============================================================
TRAINING COMPLETE
============================================================
Total Training Time: 145.98s
Total Epochs: 3
Average Epoch Time: 43.57s
Total Tokens Processed: 2,052,096
Average Throughput: 14057 tokens/second
Total FLOPs: 1027.47 TFLOPS
Average TFLOPS (per second): 7.04
Overall FLOPs (per token): 0.50 GFLOPS

Final Metrics:
Memory Footprint: 3.81 GB
Inference Throughput: 16306 tokens/second
Total Training FLOPs: 342.49 TFLOPS
Hierarchical Prompt Tuning completed!

In [33]:
summarize_training_results(trainer, monitor)

====================================================================================================
TRAINING RESULTS SUMMARY TABLE
====================================================================================================
Epoch Training Loss Validation Loss Time (s) Tokens Processed Throughput (token/s) TFLOPS (per second) Avg CPU (%) Avg Memory (%) Training Steps
    0        4.5665          3.4720    43.76          684,032                15632                7.83        23.6           12.1            167
    1        3.3206          3.3823    43.44          684,032                15747                7.88        22.4           12.1            167
    2        3.2655          3.3712    43.50          684,032                15723                7.87        21.0           12.2            167

----------------------------------------------------------------------------------------------------
TRAINING STATISTICS:
----------------------------------------------------------------------------------------------------
Total Training Time:      130.7 s
Average Epoch Time:       43.6 s
Total Tokens Processed:   2,052,096
Average Throughput:       15701 tokens/second
Average CPU Usage:        22.4%
Average Memory Usage:     12.1%
Total Training FLOPs:     1027.47 TFLOPS
Average TFLOPS (per sec): 7.86
Overall FLOPs (per token): 0.50 GFLOPS

====================================================================================================

**Reference** 
- [Huggingface:Prompt tuning](https://huggingface.co/docs/peft/en/package_reference/prompt_tuning)
- [Huggingface:Prompt Tuning With PEFT.](https://huggingface.co/learn/cookbook/en/prompt_tuning_peft)
- [Arxiv:Learning Hierarchical Prompt with Structured Linguistic Knowledge for Vision-Language Models](https://arxiv.org/abs/2312.06323)

### Sparse Prefix Tuning

Sparse Prefix Tuning is a parameter-efficient fine-tuning (PEFT) strategy that optimizes only a small fraction of the prefix or prompt parameters while keeping the rest frozen. While standard Prefix Tuning already significantly reduces the number of trainable parameters compared to full fine-tuning, Sparse Prefix Tuning goes a step further by identifying and updating only the "most impactful" entries within those task-specific vectors.

Instead of training a dense matrix of virtual tokens, this method applies a sparsity mask to the prefix weights. This results in an extremely lightweight "delta" that can steer the model's behavior with even less computational and storage overhead than traditional prefix methods.

**How it Works**

Sparse Prefix Tuning is based on the "Lottery Ticket Hypothesis," which suggests that within any large set of trainable parameters, there is a small sub-network that does most of the work.
- Prefix Initialization: The model starts with a standard set of virtual tokens (the prefix).
- Sparsity Masking: A mask is applied to the prefix parameters. This mask can be static (randomly chosen at the start) or dynamic (calculated based on gradient magnitude or importance scores).
- Selective Backpropagation: During training, gradients are only calculated and applied for the parameters where the mask is "active" (e.g., the top 10% of values). The other 90% of the prefix parameters remain at their initial values.
- Inference-Time Reconstruction: When the model runs, the full prefix is used (initial values + learned sparse updates), but the update itself is mathematically sparse, making it easier to store and transmit.

**Implements Sparse Prefix Tuning**

The script implements a static random sparse mask on the prompt embeddings of Qwen2-0.5B.

**Prompt Tuning Setup:**

    prompt_config = PromptTuningConfig(
        num_virtual_tokens=20,
        tokenizer_name_or_path=MODEL_NAME,
    )
    model = get_peft_model(model, prompt_config)

Initially, the code sets up 20 virtual tokens. At this stage, all parameters in these 20 vectors are marked as trainable.

**Applying the Sparsity Mask:**

    sparsity = 0.1
    for name, param in model.named_parameters():
        if "prompt_encoder" in name or "embedding" in name.lower():
            if param.requires_grad:
                mask = torch.rand_like(param) > sparsity
                with torch.no_grad():
                    param.mul_(mask.float())

This loop finds the trainable prompt parameters and creates a random boolean mask where only 10% of the values are True. By multiplying the parameters by this mask, it effectively "zeroes out" 90% of the initial prompt values. Because the optimizer only updates parameters with non-zero gradients, and the gradients for the zeroed-out values will not meaningfully contribute to the task direction, the model learns a very sparse signal.

**Parameter Counting:**

The `model.print_trainable_parameters()` call will show that the number of trainable parameters is technically the same, but the "effective" trainable space has been constrained by the zeroing-out operation, forcing the model to find a sparse solution.

**When to Use It**

Sparse Prefix Tuning is ideal for extreme resource constraints and modular systems:
- Extreme Multi-Tasking: When you need to store hundreds of task-specific adapters for a single model in a shared environment. Sparse prefixes take up even less disk space than dense ones.
- Continual Learning: If you are updating a model frequently with new facts or tasks, sparse updates are less likely to interfere with previously learned knowledge (mitigating catastrophic forgetting).
- Low-Bandwidth Deployment: In scenarios where adapters must be sent over a network (e.g., edge computing or federated learning), sparse vectors can be compressed significantly for faster transmission.
- Ablation and Research: It is useful for determining the "intrinsic dimension" of a task—finding out just how few parameters are actually required to teach an LLM a specific new behavior.

In [ ]:
import torch
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    TrainingArguments,
    Trainer,
    DataCollatorForLanguageModeling,
)
from datasets import DatasetDict, Dataset
from peft import PromptTuningConfig, get_peft_model

In [34]:
# Configuration – small model (<1B params)
MODEL_NAME = "Qwen/Qwen2-0.5B-Instruct"
OUTPUT_DIR = "./qwen2-0.5b-finetuned-qa-sparse-prefix"

# Load tokenizer
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
tokenizer.pad_token = tokenizer.eos_token

# Tokenization
def tokenize_examples(df, max_length=MAX_LENGTH):
    texts = [
        f"""<bos>Question: {row['question_title']}
{row['question_body']}
Answer: {row['answer']}<eos>"""
        for row in df.iter_rows(named=True)
    ]
    tokenized = tokenizer(
        texts,
        truncation=True,
        max_length=max_length,
        padding="max_length",
        return_tensors="pt"
    )
    tokenized["labels"] = tokenized["input_ids"].clone()
    return tokenized

train_tokenized = tokenize_examples(train_data)
val_tokenized = tokenize_examples(val_data)

dataset_dict = DatasetDict({
    "train": Dataset.from_dict({
        "input_ids": train_tokenized["input_ids"],
        "attention_mask": train_tokenized["attention_mask"],
        "labels": train_tokenized["labels"]
    }),
    "validation": Dataset.from_dict({
        "input_ids": val_tokenized["input_ids"],
        "attention_mask": val_tokenized["attention_mask"],
        "labels": val_tokenized["labels"]
    })
})

config.json:   0%|          | 0.00/659 [00:00<?, ?B/s]

tokenizer_config.json: 0.00B [00:00, ?B/s]

vocab.json: 0.00B [00:00, ?B/s]

merges.txt: 0.00B [00:00, ?B/s]

tokenizer.json: 0.00B [00:00, ?B/s]

In [35]:
# Load small model
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    device_map="auto",
    torch_dtype=torch.bfloat16,
    low_cpu_mem_usage=True,
)

# Sparse Prompt Tuning (input-level prefix equivalent)
prompt_config = PromptTuningConfig(
    task_type="CAUSAL_LM",
    num_virtual_tokens=20,
    tokenizer_name_or_path=MODEL_NAME,
)

model = get_peft_model(model, prompt_config)

# Apply sparsity mask (only approx. 10% of prompt parameters remain trainable)
sparsity = 0.1
for name, param in model.named_parameters():
    if "prompt_encoder" in name or "embedding" in name.lower():
        if param.requires_grad:
            mask = torch.rand_like(param) > sparsity
            with torch.no_grad():
                param.mul_(mask.float())

model.print_trainable_parameters()

# Training setup
monitor = EpochMonitor(model=model)
data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    gradient_accumulation_steps=1,
    learning_rate=2e-4,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_strategy="epoch",
    run_name="qwen2-0.5b-qa-sparse-prefix",
    warmup_ratio=0.1,
    lr_scheduler_type="cosine",
    gradient_checkpointing=True,
    bf16=True,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
    callbacks=[monitor],
)

print("Starting Sparse Prefix Tuning...")
trainer.train()

model.save_pretrained(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)
print("Sparse Prefix Tuning completed!")

model.safetensors:   0%|          | 0.00/988M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/290 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/242 [00:00<?, ?B/s]

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 17,920 || all params: 494,050,688 || trainable%: 0.0036
Starting Sparse Prefix Tuning...
Initial Model Memory Footprint:
  Parameters: 494,050,688
  Precision: 2 bytes
  Total Memory: 3.55 GB
    - Parameters: 0.92 GB
    - KV Cache (est): 2.62 GB
  Estimated FLOPs per forward pass (batch=8, seq=512): 3.55 TFLOPS

============================================================
Epoch 0 Summary
============================================================
  Duration (s)         :         26.56
  Tokens Processed     :       684,032
  Throughput (token/s) :         25751
  Training Steps       :           167
  Avg CPU (%)          :          22.6
  Avg Memory (%)       :          12.4
  Total FLOPs          : 592.93 TFLOPS
  TFLOPS (per second)  :         22.32
  FLOPs (per token)    :   0.87 GFLOPS

============================================================
Epoch 1 Summary
============================================================
  Duration (s)         :         26.81
  Tokens Processed     :       684,032
  Throughput (token/s) :         25512
  Training Steps       :           167
  Avg CPU (%)          :          19.8
  Avg Memory (%)       :          12.5
  Total FLOPs          : 592.93 TFLOPS
  TFLOPS (per second)  :         22.11
  FLOPs (per token)    :   0.87 GFLOPS

============================================================
Epoch 2 Summary
============================================================
  Duration (s)         :         26.73
  Tokens Processed     :       684,032
  Throughput (token/s) :         25587
  Training Steps       :           167
  Avg CPU (%)          :          17.0
  Avg Memory (%)       :          12.5
  Total FLOPs          : 592.93 TFLOPS
  TFLOPS (per second)  :         22.18
  FLOPs (per token)    :   0.87 GFLOPS

============================================================
TRAINING COMPLETE
============================================================
Total Training Time: 87.26s
Total Epochs: 3
Average Epoch Time: 26.70s
Total Tokens Processed: 2,052,096
Average Throughput: 23516 tokens/second
Total FLOPs: 1778.78 TFLOPS
Average TFLOPS (per second): 20.38
Overall FLOPs (per token): 0.87 GFLOPS

Final Metrics:
Memory Footprint: 3.55 GB
Inference Throughput: 26920 tokens/second
Total Training FLOPs: 592.93 TFLOPS
Sparse Prefix Tuning completed!

In [36]:
summarize_training_results(trainer, monitor)

====================================================================================================
TRAINING RESULTS SUMMARY TABLE
====================================================================================================
Epoch Training Loss Validation Loss Time (s) Tokens Processed Throughput (token/s) TFLOPS (per second) Avg CPU (%) Avg Memory (%) Training Steps
    0        3.2667          3.1937    26.56          684,032                25750               22.32        22.6           12.4            167
    1        3.0555          3.1210    26.81          684,032                25512               22.11        19.8           12.5            167
    2        3.0120          3.1066    26.73          684,032                25587               22.18        17.0           12.5            167

----------------------------------------------------------------------------------------------------
TRAINING STATISTICS:
----------------------------------------------------------------------------------------------------
Total Training Time:      80.1 s
Average Epoch Time:       26.7 s
Total Tokens Processed:   2,052,096
Average Throughput:       25617 tokens/second
Average CPU Usage:        19.8%
Average Memory Usage:     12.5%
Total Training FLOPs:     1778.78 TFLOPS
Average TFLOPS (per sec): 22.20
Overall FLOPs (per token): 0.87 GFLOPS

====================================================================================================

**Reference** 
- [Huggingface:Prompt tuning](https://huggingface.co/docs/peft/en/package_reference/prompt_tuning)
- [Huggingface:Prompt Tuning With PEFT.](https://huggingface.co/learn/cookbook/en/prompt_tuning_peft)
- [Arxiv:Prefix-Tuning+: Modernizing Prefix-Tuning by Decoupling the Prefix from Attention](https://arxiv.org/html/2506.13674v2)
- [Arxiv:Classifier Language Models: Unifying Sparse Finetuning and Adaptive Tokenization for Specialized Classification Tasks](https://arxiv.org/html/2508.08635v1)

### Dynamic Prompt Generation

Dynamic Prompt Generation (DPG) is a parameter-efficient fine-tuning (PEFT) strategy where the soft prompts (virtual tokens) are not fixed vectors learned during training, but are instead generated on-the-fly by a secondary, lightweight network. While standard Prompt Tuning uses the same "cheat sheet" for every input, DPG creates a unique, customized instruction for every single query based on its specific content.

This method transforms the static nature of continuous prompts into an adaptive system, allowing the model to "shift its gears" instantly depending on whether the input is a complex math problem, a casual chat, or a technical document.

**How it Works**

The core of DPG is the Instance-Dependent mechanism, which replaces fixed embeddings with a neural function.
- Context Encoding: The input text is first converted into a dense feature vector (often using mean pooling of the input embeddings). This vector captures the "essence" or "intent" of the user's specific query.
- The Hyper-Network (Generator): A small, trainable multi-layer perceptron (MLP) or encoder takes this query feature as input. Its job is to predict what kind of virtual tokens would best "steer" the frozen LLM for this specific instance.
- Projection and Injection: The generated tokens are then projected into the model's high-dimensional space. In advanced implementations like the one provided, these tokens are transformed directly into Key-Value (KV) pairs for the model's attention cache.
- Virtual Cache Pre-filling: These generated KV states are prepended to the model's internal memory (the KV-cache). When the LLM processes the actual user input, it "sees" these dynamic instructions as if they were part of its own internal reasoning history.

**Implements Dynamic Prompt Generation**

The script builds a sophisticated, custom DPG pipeline for Gemma-3-270m using a generator-projector architecture.

**The Generator (Hyper-network):**

    self.encoder = nn.Sequential(
        nn.Linear(input_dim, 256),
        nn.GELU(),
        nn.Linear(256, prompt_dim * num_virtual_tokens)
    )

The `DynamicPromptGenerator` class defines the MLP that creates the prompts. It maps the input features into a long vector that is reshaped into 20 virtual tokens. This ensures the prompt is a mathematical function of the input, not a static weight.

**KV-State Projection:**

    self.prompt_projection = nn.Linear(
        generator.prompt_dim,
        self.num_kv_heads * self.head_dim * 2
    )

The `DynamicPromptModel` doesn't just put tokens at the beginning of the text; it projects them into the specific dimensions required by Gemma's attention heads. The `* 2` multiplier creates both Key and Value states for every layer.

**DynamicCache Integration:**

    cache = DynamicCache()
    for layer_idx in range(self.num_layers):
        cache.update(key_states, value_states, layer_idx, ...)

This is the most critical optimization. Instead of appending tokens to the input string (which consumes token budget and slows down processing), the code "hacks" the model's memory by pre-filling a DynamicCache. This makes the dynamic prompt virtually invisible to the input length while still guiding every layer of the transformer.

**When to Use It**

Dynamic Prompt Generation is the best choice for high-performance, adaptive AI systems:
- High-Variance Workloads: If a single model instance must handle wildly different tasks (e.g., coding, creative writing, and data extraction), DPG allows the model to adapt its internal "mode" for each request.
- Personalized AI Agents: For systems that need to adapt based on user profile or history. The generator can take user metadata as input to "style" the LLM's response without needing a separate model for every user.
- Scaling Smaller Models: Research shows DPG can help smaller models (like 270M or 2B parameters) punch above their weight class by providing higher-quality, instance-specific guidance that static prompts cannot.
- Latency-Sensitive Applications: Because DPG uses a cache-injection method, it avoids the overhead of re-tokenizing and re-processing long prompt strings, making it faster than many RAG-based prompt builders.

In [ ]:
import torch
import torch.nn as nn
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    Trainer,
    TrainingArguments,
    DataCollatorForLanguageModeling,
    TrainerCallback,
    DynamicCache  # Import DynamicCache instead of HybridCache
)
from datasets import DatasetDict, Dataset
import gc
import os

In [7]:
# Configuration
MODEL_NAME = "google/gemma-3-270m-it"
OUTPUT_DIR = "./gemma-3-270m-dynamic-prompt"
MAX_LENGTH = 128
NUM_VIRTUAL_TOKENS = 20
PROMPT_DIM = 64
LEARNING_RATE = 5e-5

os.makedirs(OUTPUT_DIR, exist_ok=True)

# Tokenizer
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"

def tokenize_examples(df):
    texts = [
        f"Question: {row['question_title']}\n{row['question_body']}\nAnswer: {row['answer']}"
        for row in df.iter_rows(named=True)
    ]
    tokenized = tokenizer(
        texts,
        truncation=True,
        max_length=MAX_LENGTH,
        padding="max_length",
        return_tensors="pt"
    )
    tokenized["labels"] = tokenized["input_ids"].clone()
    tokenized["labels"][tokenized["labels"] == tokenizer.pad_token_id] = -100
    return tokenized

# Dataset Preparation
print("Tokenizing datasets...")
train_tokenized = tokenize_examples(train_data)
val_tokenized = tokenize_examples(val_data)

dataset_dict = DatasetDict({
    "train": Dataset.from_dict(train_tokenized),
    "validation": Dataset.from_dict(val_tokenized)
})

print(f"Train examples: {len(dataset_dict['train']):,}")
print(f"Validation examples: {len(dataset_dict['validation']):,}")

Tokenizing datasets...
Train examples: 1,331
Validation examples: 285

In [8]:
# Dynamic Prompt Generator
class DynamicPromptGenerator(nn.Module):
    def __init__(self, input_dim, prompt_dim, num_virtual_tokens):
        super().__init__()
        self.prompt_dim = prompt_dim
        self.num_virtual_tokens = num_virtual_tokens
        self.encoder = nn.Sequential(
            nn.Linear(input_dim, 256),
            nn.LayerNorm(256),
            nn.GELU(),
            nn.Dropout(0.1),
            nn.Linear(256, prompt_dim * num_virtual_tokens)
        )
        
    def forward(self, input_features):
        batch_size = input_features.size(0)
        generated = self.encoder(input_features)
        return generated.view(batch_size, self.num_virtual_tokens, self.prompt_dim)

# Metrics Callback
class MetricsCallback(TrainerCallback):
    def on_log(self, args, state, control, logs=None, **kwargs):
        model = kwargs.get("model")
        if model and hasattr(model, 'prompt_norm'):
            logs["prompt_norm"] = model.prompt_norm
        return control

# Dynamic Prompt Model with DynamicCache
class DynamicPromptModel(nn.Module):
    def __init__(self, base_model, generator, num_virtual_tokens=20):
        super().__init__()
        self.base_model = base_model
        self.generator = generator
        self.num_virtual_tokens = num_virtual_tokens
        self.prompt_norm = 0.0
        
        # Gemma-3 specific dimensions
        self.num_kv_heads = base_model.config.num_key_value_heads
        self.head_dim = base_model.config.head_dim
        self.num_layers = base_model.config.num_hidden_layers
        
        # Projection for key/value states
        self.prompt_projection = nn.Linear(
            generator.prompt_dim,
            self.num_kv_heads * self.head_dim * 2
        )
        
    def forward(self, input_ids, attention_mask=None, labels=None, **kwargs):
        batch_size = input_ids.shape[0]
        device = input_ids.device
        
        # Get input features via mean pooling (no gradients)
        with torch.no_grad():
            input_embeds = self.base_model.get_input_embeddings()(input_ids)
            input_features = input_embeds.mean(dim=1)
        
        # Generate and project dynamic prompts
        generated_prompts = self.generator(input_features)
        projected = self.prompt_projection(generated_prompts)
        key_states, value_states = projected.chunk(2, dim=-1)
        
        # Reshape to [batch, num_kv_heads, num_vt, head_dim]
        key_states = key_states.view(
            batch_size, self.num_virtual_tokens, self.num_kv_heads, self.head_dim
        ).transpose(1, 2).contiguous()
        
        value_states = value_states.view(
            batch_size, self.num_virtual_tokens, self.num_kv_heads, self.head_dim
        ).transpose(1, 2).contiguous()
        
        # Create DynamicCache and pre-fill with prompt tokens
        cache = DynamicCache()
        cache_position = torch.arange(self.num_virtual_tokens, device=device)
        
        for layer_idx in range(self.num_layers):
            cache.update(
                key_states,
                value_states,
                layer_idx,
                cache_kwargs={"cache_position": cache_position}
            )
        
        # Forward pass with pre-filled cache
        outputs = self.base_model(
            input_ids=input_ids,
            attention_mask=attention_mask,
            labels=labels,
            past_key_values=cache,
            use_cache=True,
            **kwargs
        )
        
        # Update prompt norm for logging
        if self.training:
            with torch.no_grad():
                self.prompt_norm = 0.9 * self.prompt_norm + 0.1 * generated_prompts.norm(dim=-1).mean().item()
        
        return outputs
    
    @property
    def config(self):
        """Expose base model config for saving."""
        return self.base_model.config

In [9]:
# Load Model
print(f"Loading base model: {MODEL_NAME}")
base_model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    dtype=torch.bfloat16,  
    device_map="auto",
    attn_implementation="eager"
)

# Freeze base model
base_model.eval()
for param in base_model.parameters():
    param.requires_grad = False

# Initialize generator
generator = DynamicPromptGenerator(
    input_dim=base_model.config.hidden_size,
    prompt_dim=PROMPT_DIM,
    num_virtual_tokens=NUM_VIRTUAL_TOKENS
)

# Create dynamic prompt model
model = DynamicPromptModel(
    base_model=base_model,
    generator=generator,
    num_virtual_tokens=NUM_VIRTUAL_TOKENS
)

# Move model to same device as base_model
model = model.to(base_model.device)

monitor = EpochMonitor(model=model)

# Count trainable parameters
trainable_params = sum(p.numel() for p in generator.parameters()) + \
                   sum(p.numel() for p in model.prompt_projection.parameters())
total_params = sum(p.numel() for p in model.parameters())

print(f"\n{'='*50}")
print(f"PARAMETER STATISTICS")
print(f"{'='*50}")
print(f"  Total parameters: {total_params:,}")
print(f"  Trainable parameters: {trainable_params:,}")
print(f"  Trainable percentage: {(trainable_params / total_params * 100):.4f}%")
print(f"  Virtual tokens per prompt: {NUM_VIRTUAL_TOKENS}")
print(f"  Prompt dimension: {PROMPT_DIM}")
print(f"{'='*50}\n")

# Training Arguments
total_steps = len(dataset_dict["train"]) * 3 // (2 * 8)  # samples * epochs / (batch_size * grad_accum)
training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=2,
    per_device_eval_batch_size=2,
    gradient_accumulation_steps=8,
    learning_rate=LEARNING_RATE,
    weight_decay=0.01,
    max_grad_norm=1.0,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_steps=20,
    warmup_steps=int(0.1 * total_steps), 
    lr_scheduler_type="cosine",
    bf16=True,
    optim="adamw_torch",
    gradient_checkpointing=False,
    dataloader_num_workers=2,
    ddp_find_unused_parameters=False if torch.cuda.device_count() > 1 else None,
)

# Custom Trainer
class DynamicPromptTrainer(Trainer):
    def _save(self, output_dir, state_dict=None):
        """Save only the trainable components."""
        output_dir = output_dir or self.args.output_dir
        os.makedirs(output_dir, exist_ok=True)
        
        # Save only the trainable components
        if hasattr(self.model, 'generator') and hasattr(self.model, 'prompt_projection'):
            torch.save({
                'generator_state_dict': self.model.generator.state_dict(),
                'projection_state_dict': self.model.prompt_projection.state_dict(),
                'config': {
                    'model_name': MODEL_NAME,
                    'num_virtual_tokens': NUM_VIRTUAL_TOKENS,
                    'prompt_dim': PROMPT_DIM,
                    'num_kv_heads': self.model.num_kv_heads,
                    'head_dim': self.model.head_dim,
                    'num_layers': self.model.num_layers,
                }
            }, os.path.join(output_dir, "dynamic_prompt_model.pt"))
        
        # Save the base model config
        if hasattr(self.model, 'config'):
            self.model.config.save_pretrained(output_dir)
        
        # Save training args
        torch.save(self.args, os.path.join(output_dir, "training_args.bin"))

# Trainer
trainer = DynamicPromptTrainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=DataCollatorForLanguageModeling(
        tokenizer=tokenizer,
        mlm=False,
    ),
    callbacks=[MetricsCallback(), monitor],
)

# Train
print(f"\n{'='*60}")
print(f"STARTING DYNAMIC PROMPT GENERATION TRAINING")
print(f"Output directory: {OUTPUT_DIR}")
print(f"{'='*60}\n")

trainer.train()

# Save
print("\nSaving model components...")

# Save using our custom method
trainer._save(OUTPUT_DIR)

# Save tokenizer
tokenizer.save_pretrained(OUTPUT_DIR)

# Save additional configuration
config = {
    'model_name': MODEL_NAME,
    'num_virtual_tokens': NUM_VIRTUAL_TOKENS,
    'prompt_dim': PROMPT_DIM,
    'learning_rate': LEARNING_RATE,
    'trainable_params': trainable_params,
    'total_params': total_params,
}
torch.save(config, f"{OUTPUT_DIR}/training_config.pt")

print(f"Dynamic prompt model saved")
print(f"Tokenizer saved")
print(f"Config saved")
print(f"\nDynamic Prompt Generation training completed!")

Loading base model: google/gemma-3-270m-it

Loading weights:   0%|          | 0/236 [00:00<?, ?it/s]

==================================================
PARAMETER STATISTICS
==================================================
  Total parameters: 268,625,024
  Trainable parameters: 526,848
  Trainable percentage: 0.1961%
  Virtual tokens per prompt: 20
  Prompt dimension: 64
==================================================


============================================================
STARTING DYNAMIC PROMPT GENERATION TRAINING
Output directory: ./gemma-3-270m-dynamic-prompt
============================================================

Initial Model Memory Footprint:
  Parameters: 268,625,024
  Precision: 4 bytes
  Total Memory: 3.81 GB
    - Parameters: 1.00 GB
    - KV Cache (est): 2.81 GB
  Estimated FLOPs per forward pass (batch=8, seq=512): 2.05 TFLOPS

============================================================
Epoch 0 Summary
============================================================
  Duration (s)         :        57.20
  Tokens Processed     :       86,016
  Throughput (token/s) :         1504
  Training Steps       :           84
  Avg CPU (%)          :         24.3
  Avg Memory (%)       :         12.5
  Total FLOPs          : 43.07 TFLOPS
  TFLOPS (per second)  :         0.75
  FLOPs (per token)    :  0.50 GFLOPS

============================================================
Epoch 1 Summary
============================================================
  Duration (s)         :        56.35
  Tokens Processed     :       86,016
  Throughput (token/s) :         1527
  Training Steps       :           84
  Avg CPU (%)          :         24.6
  Avg Memory (%)       :         12.5
  Total FLOPs          : 43.07 TFLOPS
  TFLOPS (per second)  :         0.76
  FLOPs (per token)    :  0.50 GFLOPS

============================================================
Epoch 2 Summary
============================================================
  Duration (s)         :        56.06
  Tokens Processed     :       86,016
  Throughput (token/s) :         1534
  Training Steps       :           84
  Avg CPU (%)          :         22.6
  Avg Memory (%)       :         12.5
  Total FLOPs          : 43.07 TFLOPS
  TFLOPS (per second)  :         0.77
  FLOPs (per token)    :  0.50 GFLOPS

Could not locate the best model at ./gemma-3-270m-dynamic-prompt/checkpoint-252/pytorch_model.bin, if you are running a distributed training on multiple nodes, you should activate `--save_on_each_node`.

============================================================
TRAINING COMPLETE
============================================================
Total Training Time: 187.91s
Total Epochs: 3
Average Epoch Time: 56.54s
Total Tokens Processed: 258,048
Average Throughput: 1373 tokens/second
Total FLOPs: 129.20 TFLOPS
Average TFLOPS (per second): 0.69
Overall FLOPs (per token): 0.50 GFLOPS

Final Metrics:
Memory Footprint: 3.81 GB
Inference Throughput: 1623 tokens/second
Total Training FLOPs: 43.07 TFLOPS

Saving model components...
Dynamic prompt model saved
Tokenizer saved
Config saved

Dynamic Prompt Generation training completed!

**Reference** 
- [Huggingface:Cache strategies](https://huggingface.co/docs/transformers/en/kv_cache)
- [Arxiv:Dynamic Compressing Prompts for Efficient Inference of Large Language Models](https://arxiv.org/html/2504.11004v1)
- [Arxiv:CacheFocus: Dynamic Cache Re-Positioning for Efficient Retrieval-Augmented Generation](https://arxiv.org/abs/2502.11101)

### Prompt Ensembling

Prompt Ensembling is a strategy that improves the reliability and accuracy of Large Language Models by combining the outputs of multiple different prompts for the same task. Instead of relying on a single "perfect" prompt, ensembling leverages a diverse set of instructions—often called "weak learners"—to reach a consensus or a more comprehensive final answer.

This technique is rooted in the principle of "The Wisdom of the Crowd." By approaching a problem from different linguistic angles (e.g., asking for a "detailed response" vs. an "accurate answer"), the model is less likely to be swayed by the specific wording of any single prompt, effectively smoothing out hallucinations and instabilities.

**How it Works**

Prompt ensembling typically follows a multi-stage pipeline:
- Prompt Diversification: Multiple prompts are generated, either manually by varying the phrasing or automatically through paraphrasing and different few-shot examples.
- Parallel Execution: The LLM processes the input several times, once for each prompt in the ensemble.
- Aggregation: The individual results are combined using a voting or scoring mechanism. Common methods include:
- Majority Voting: Choosing the most frequent answer (best for classification or multiple-choice).
- Weighted Averaging: Assigning higher importance to prompts that performed better during a validation phase.
- Consensus-based Refinement: Using a second LLM pass to synthesize the best parts of each response into one final output.

**Implements Prompt Ensembling**

The script automates the creation and training of distinct soft-prompt adapters for a single base model (Gemma-3-270m-it).

**Independent Expert Training:**

    for i in range(NUM_ENSEMBLES):
        # ...
        prompt_tuning_init_text=base_init_texts[i % len(base_init_texts)],

The code runs a loop to train three separate prompt adapters. Each one starts with a different semantic "`seed`" (e.g., "Answer the following..." or "Provide a detailed..."). This ensures that each of the three ensembles learns to steer the model slightly differently, creating the diversity needed for an effective ensemble.

**Modular Storage:**

    ensemble_dir = f"{OUTPUT_DIR}/ensemble-{i}"
    model.save_pretrained(ensemble_dir)

The code saves each trained prompt as a separate PEFT adapter. This allows the system to load all three "specialists" later and run them in parallel (or sequence) to compare their outputs.

**Configuration Management:**

By saving an `ensemble_config.pt`, the code keeps track of which prompts belong together. This metadata is essential for the inference stage, where the system must know which sub-directories to load to reconstruct the full ensemble.

**When to Use It**

Prompt Ensembling is highly effective in high-stakes or high-uncertainty environments:
- Mitigating Hallucination: In factual Q&A or medical/legal domains, if three different prompts yield the same answer, the confidence in that answer is significantly higher. If they disagree, it signals the model is uncertain.
- Complex Reasoning: For "hard" problems like math (GSM8K) or logic, different prompts can trigger different "reasoning paths" (Chain-of-Thought). Aggregating these paths often leads to the correct solution even if individual prompts fail.
- Handling Prompt Sensitivity: Some models are notoriously finicky about how a question is asked. Ensembling removes the "lottery" aspect of prompt engineering by averaging out the performance across multiple variations.
- Edge-Case Robustness: While a single prompt might perform well on 90% of data, it might fail on specific edge cases. A diverse ensemble is more likely to have at least one member that handles the edge case correctly.

In [ ]:
import torch
import torch.nn as nn
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    Trainer,
    TrainingArguments,
    DataCollatorForLanguageModeling,
    TrainerCallback
)
from peft import PromptTuningConfig, get_peft_model, PromptTuningInit
from datasets import DatasetDict, Dataset
import gc
import os

In [ ]:
# Configuration
MODEL_NAME = "google/gemma-3-270m-it"
OUTPUT_DIR = "./gemma-3-270m-prompt-ensemble"
MAX_LENGTH = 128
NUM_VIRTUAL_TOKENS = 20
NUM_ENSEMBLES = 3
LEARNING_RATE = 3e-5

os.makedirs(OUTPUT_DIR, exist_ok=True)

In [ ]:
# Tokenizer
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"

def tokenize_examples(df, max_length=MAX_LENGTH):
    texts = [
        f"Question: {row['question_title']}\n{row['question_body']}\nAnswer: {row['answer']}"
        for row in df.iter_rows(named=True)
    ]
    tokenized = tokenizer(
        texts,
        truncation=True,
        max_length=max_length,
        padding="max_length",
        return_tensors="pt"
    )
    tokenized["labels"] = tokenized["input_ids"].clone()
    tokenized["labels"][tokenized["labels"] == tokenizer.pad_token_id] = -100
    return tokenized

# Dataset Preparation
print("Tokenizing datasets...")
train_tokenized = tokenize_examples(train_data)
val_tokenized = tokenize_examples(val_data)

dataset_dict = DatasetDict({
    "train": Dataset.from_dict(train_tokenized),
    "validation": Dataset.from_dict(val_tokenized)
})

print(f"Train examples: {len(dataset_dict['train']):,}")
print(f"Validation examples: {len(dataset_dict['validation']):,}")

# Metrics Callback
class MetricsCallback(TrainerCallback):
    def on_log(self, args, state, control, logs=None, **kwargs):
        return control

In [ ]:
# Train Multiple Prompt Ensembles
prompt_dirs = []
base_init_texts = [
    "Answer the following question accurately:",
    "Provide a detailed response to:",
    "Give a comprehensive answer for:"
]

print(f"\n{'='*60}")
print(f"TRAINING {NUM_ENSEMBLES} PROMPT ENSEMBLES")
print(f"{'='*60}\n")

monitor = EpochMonitor(model=model)

for i in range(NUM_ENSEMBLES):
    print(f"\n{'─'*40}")
    print(f"Training Prompt Ensemble {i+1}/{NUM_ENSEMBLES}")
    print(f"{'─'*40}")
    
    # Create ensemble-specific output directory
    ensemble_dir = f"{OUTPUT_DIR}/ensemble-{i}"
    os.makedirs(ensemble_dir, exist_ok=True)
    
    # Configure prompt tuning with different initialization texts
    prompt_config = PromptTuningConfig(
        task_type="CAUSAL_LM",
        num_virtual_tokens=NUM_VIRTUAL_TOKENS,
        prompt_tuning_init=PromptTuningInit.TEXT,
        prompt_tuning_init_text=base_init_texts[i % len(base_init_texts)],
        tokenizer_name_or_path=MODEL_NAME,
    )
    
    # Load base model with correct parameters
    model = AutoModelForCausalLM.from_pretrained(
        MODEL_NAME,
        torch_dtype=torch.bfloat16,  # use torch_dtype, not dtype
        device_map="auto",
        attn_implementation="eager"  # Required for Gemma-3
    )
    
    # Apply prompt tuning
    model = get_peft_model(model, prompt_config)
    
    # Print trainable parameters
    trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
    total_params = sum(p.numel() for p in model.parameters())
    print(f"  Trainable parameters: {trainable_params:,}")
    print(f"  Trainable percentage: {(trainable_params / total_params * 100):.4f}%")
    
    # Training arguments
    training_args = TrainingArguments(
        output_dir=ensemble_dir,
        num_train_epochs=3,
        per_device_train_batch_size=4,  # Reduced for stability
        per_device_eval_batch_size=4,
        gradient_accumulation_steps=2,
        learning_rate=LEARNING_RATE,
        weight_decay=0.01,
        max_grad_norm=1.0,
        eval_strategy="epoch",
        save_strategy="epoch",
        load_best_model_at_end=True,
        metric_for_best_model="eval_loss",
        greater_is_better=False,
        report_to="none",
        save_total_limit=2,
        remove_unused_columns=False,
        logging_steps=50,
        warmup_ratio=0.1,
        lr_scheduler_type="cosine",
        bf16=True,
        optim="adamw_torch",
        gradient_checkpointing=False,
        dataloader_num_workers=2,
        dataloader_pin_memory=True,
        ddp_find_unused_parameters=False if torch.cuda.device_count() > 1 else None,
    )
    
    # Trainer
    trainer = Trainer(
        model=model,
        args=training_args,
        train_dataset=dataset_dict["train"],
        eval_dataset=dataset_dict["validation"],
        data_collator=DataCollatorForLanguageModeling(
            tokenizer=tokenizer,
            mlm=False,
        ),
        callbacks=[MetricsCallback(), monitor],
    )
    
    # Train
    torch.cuda.empty_cache()
    gc.collect()
    
    print(f"\nStarting training...")
    trainer.train()
    
    # Save
    model.save_pretrained(ensemble_dir)
    prompt_dirs.append(ensemble_dir)
    print(f"✓ Prompt Ensemble {i+1} saved to: {ensemble_dir}")
    
    # Cleanup
    del model, trainer
    torch.cuda.empty_cache()
    gc.collect()

# Save Tokenizer and Ensemble Configuration
tokenizer.save_pretrained(f"{OUTPUT_DIR}/tokenizer")

# Save ensemble configuration
ensemble_config = {
    'model_name': MODEL_NAME,
    'num_ensembles': NUM_ENSEMBLES,
    'num_virtual_tokens': NUM_VIRTUAL_TOKENS,
    'learning_rate': LEARNING_RATE,
    'prompt_dirs': prompt_dirs,
    'init_texts': base_init_texts[:NUM_ENSEMBLES]
}

torch.save(ensemble_config, f"{OUTPUT_DIR}/ensemble_config.pt")

print(f"\n{'='*60}")
print(f"PROMPT ENSEMBLING COMPLETED")
print(f"{'='*60}")
print(f"{NUM_ENSEMBLES} prompt ensembles trained and saved")
print(f"Tokenizer saved")
print(f"Config saved")
print(f"\nEnsemble directories:")
for i, dir_path in enumerate(prompt_dirs):
    print(f"  [{i+1}] {dir_path}")

In [ ]:
summarize_training_results(trainer, monitor)

In [ ]:
# Ensemble Inference Example
def ensemble_generate(prompt_dirs, input_text, max_new_tokens=50):
    """Generate using prompt ensemble by averaging logits."""
    device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
    tokenizer = AutoTokenizer.from_pretrained(f"{OUTPUT_DIR}/tokenizer")
    
    # Load all ensemble models
    models = []
    for dir_path in prompt_dirs:
        model = AutoModelForCausalLM.from_pretrained(
            MODEL_NAME,
            torch_dtype=torch.bfloat16,
            device_map="auto",
            attn_implementation="eager"
        )
        model = get_peft_model(model, PromptTuningConfig(
            task_type="CAUSAL_LM",
            num_virtual_tokens=NUM_VIRTUAL_TOKENS,
            tokenizer_name_or_path=MODEL_NAME,
        ))
        model.load_adapter(dir_path)
        model.eval()
        models.append(model)
    
    # Tokenize input
    inputs = tokenizer(input_text, return_tensors="pt").to(device)
    
    # Generate with ensemble
    with torch.no_grad():
        # Get logits from all models
        all_logits = []
        for model in models:
            outputs = model(**inputs)
            all_logits.append(outputs.logits)
        
        # Average logits
        avg_logits = torch.stack(all_logits).mean(dim=0)
        
        # Greedy decoding
        next_token_logits = avg_logits[:, -1, :]
        next_token = torch.argmax(next_token_logits, dim=-1)
    
    # Cleanup
    for model in models:
        del model
    torch.cuda.empty_cache()
    
    return tokenizer.decode(next_token[0])

print(f"\n{'='*60}")
print(f"ENSEMBLE INFERENCE READY")
print(f"{'='*60}")
print(f"Example usage: ensemble_generate(prompt_dirs, 'What is machine learning?')")

**Reference** 
- [Huggingface:Prompt tuning](https://huggingface.co/docs/peft/en/package_reference/prompt_tuning)
- [Huggingface:Prompt Tuning With PEFT.](https://huggingface.co/learn/cookbook/en/prompt_tuning_peft)
- [Arxiv:Boosted Prompt Ensembles for Large Language Models](https://arxiv.org/abs/2304.05970)
- [Arxiv:M-Ped: Multi-Prompt Ensemble Decoding for Large Language Models](https://arxiv.org/abs/2412.18299)

# Adapter and Scaling Methods

In Large Language Model (LLM) optimization, Adapter Methods and Scaling Methods refer to two different philosophies for making models more powerful or specialized. While "Adapters" focus on surgical, parameter-efficient updates, "Scaling" refers to the broader laws governing how a model's size, data, and compute impact its final performance.

**1. Adapter Methods (The "Modular" Approach)**

Adapters are lightweight, plug-and-play neural modules inserted into a frozen LLM. Instead of retraining all billions of parameters, you only train these "mini-networks" (usually less than 1% of the total model size).

**How they work**

- Bottleneck Structure: A typical adapter takes a high-dimensional signal from the model, "squeezes" it down to a small dimension (down-projection), applies a non-linear activation, and then "stretches" it back (up-projection) to fit the model's original layer.
- Weight Freezing: The original weights of the LLM are locked ($\text{requires\_grad = False}$). This prevents "catastrophic forgetting," where a model loses its general knowledge while learning a new task.
- LoRA (Low-Rank Adaptation): A popular modern variant where instead of adding layers, you add two small matrices that represent the change in weights ($\Delta W$). This is mathematically efficient and adds zero latency during inference if the weights are merged. 

**2. Scaling Methods (The "Growth" Approach)**

Scaling refers to the systematic increase of variables to improve model capability. This is guided by Scaling Laws, which predict that a model's performance (loss) follows a predictable power-law relationship with three factors: Compute (C), Dataset Size (D), and Parameter Count (N).

**How they work**

- Model Scaling: Increasing the depth (layers) and width (hidden dimension) of the transformer. Larger models have a higher "inductive bias" for complex reasoning.
- Data Scaling: Increasing the number of tokens during pre-training. Current research suggests that for every doubling of model size, you should also double the training data to remain "Chinchilla-optimal."
- Optimization Scaling: Adjusting hyperparameters like batch size and learning rate schedules as the model grows. Larger models require more stable optimization techniques to avoid training "explosions."

**When to use them?**

Use Adapter Methods when:

- You have a budget: You want to fine-tune a 70B parameter model but only have one or two GPUs.
- You need multi-tenancy: You are serving 100 different customers and want to give each a "custom" model without storing 100 full copies of the LLM. You just swap their tiny adapter files ($\approx 100\text{MB}$ each) on the fly.
- You want to preserve knowledge: You need the model to learn a specific format (like JSON output) without losing its ability to write poetry or speak French.

Use Scaling Methods when:

- You are building a "Base" model: You are a researcher or company creating a new foundation model from scratch to compete with industry leaders.
- You've hit a performance ceiling: Small models often plateau. If an adapter-tuned 7B model can't solve your logic puzzles, you likely need to scale up to a 70B or 400B model.
- You have massive data: If you have trillions of tokens of proprietary data, scaling the model size is the most effective way to "absorb" that information into the model's latent space.

### IA3 (Infused Adapter)

IA3 (Infused Adapter by Inhibiting and Amplifying Inner Activations) is an extremely lightweight parameter-efficient fine-tuning (PEFT) method that adapts an LLM by scaling its internal activations. Rather than adding new layers or low-rank matrices (like LoRA), IA3 learns simple vectors that multiply existing activations to either amplify (increase) or inhibit (suppress) specific signals within the model.

While LoRA often updates around 0.1% to 1% of a model's parameters, IA3 is even more surgical, typically updating as little as 0.01% of the total parameters. It was introduced as part of the "T-Few" recipe to make few-shot learning more robust and computationally cheaper than in-context learning.

**How it Works**

IA3 works by performing element-wise multiplication on three specific types of internal activations in each Transformer block:

- Self-Attention Keys (K): A learned vector rescales the keys, affecting how the model determines which parts of the input are relevant to each other.
- Self-Attention Values (V): A learned vector rescales the values, changing the actual information that gets passed forward after the attention calculation.
- Feed-Forward Network (FFN) Activations: A learned vector rescales the intermediate activations within the position-wise feed-forward layers (usually the output of the first linear layer in the FFN).

By scaling these values, IA3 "nudges" the model's internal representations to align with the new task without changing the fundamental weights of the pre-trained model. Mathematically, for an activation $x$, IA3 computes $x' = l \odot x$, where $l$ is the learned scaling vector and $\odot$ is the element-wise product.

**Implements IA3**

The script uses the `IA3Config` class from the peft library to target the most sensitive parts of the Gemma-3-270m architecture.

**Targeting Specific Projections:**

    ia3_config = IA3Config(
        task_type="CAUSAL_LM",
        target_modules=["k_proj", "v_proj", "down_proj"],
        feedforward_modules=["down_proj"],
    )

The configuration explicitly identifies the Key (`k_proj`) and Value (`v_proj`) matrices for attention scaling. It also identifies the `down_proj` (the second half of the FFN) as the feedforward_module. In IA3, the scaling vector for the FFN is typically applied to the input of the "down" projection, which is equivalent to scaling the intermediate activation.

**Model Infusion:**

    model = get_peft_model(model, ia3_config)

When this line executes, peft injects the learned scaling vectors into the specified layers. If you run `model.print_trainable_parameters()`, you will see a significantly smaller number compared to LoRA, as IA3 only stores one scalar per dimension of the targeted layers rather than two full low-rank matrices.

**Training and Merging:**

The training process remains identical to standard fine-tuning. Because IA3 is just a scaling operation, these learned vectors can eventually be merged into the original weights ($W_{new} = l \odot W_{old}$) for zero-latency inference.

**When to Use It**

IA3 is the preferred choice in scenarios where parameter economy and "few-shot" efficiency are the top priorities:
- Ultra-Low Resource Environments: If you are working with extremely limited GPU memory or storage (e.g., edge devices), IA3’s tiny footprint is unmatched.
- Few-Shot Learning: IA3 was specifically designed to outperform In-Context Learning (ICL) when you only have a few dozen examples (e.g., 20–50 samples). It is more stable than prompt tuning in these "low-data" regimes.
- Massive Multi-Tasking: Because the adapters are so small (often just a few kilobytes per task), you can store and switch between thousands of different task-specific IA3 adapters on a single server without significant overhead.
- Competitive Performance with LoRA: Use it when you want LoRA-like performance but find that LoRA is still using too much memory or converging too slowly for your specific task.

In [ ]:
import torch
import torch.nn as nn
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    Trainer,
    TrainingArguments,
    DataCollatorForLanguageModeling,
    DynamicCache,
)
from datasets import DatasetDict, Dataset
from peft import get_peft_model, IA3Config, TaskType

In [50]:
# Configuration
MODEL_NAME = "google/gemma-3-270m"
OUTPUT_DIR = "./gemma-3-270m-finetuned-qa-dynamic-prompt"

# Configure IA3
ia3_config = IA3Config(
    task_type="CAUSAL_LM",
    target_modules=["k_proj", "v_proj", "down_proj"],
    feedforward_modules=["down_proj"],
)

# Load model and apply IA3
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    device_map="auto",
    dtype=torch.float32,
    low_cpu_mem_usage=True,
)

model = get_peft_model(model, ia3_config)
model.print_trainable_parameters()

monitor = EpochMonitor(model=model)

data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

training_args = TrainingArguments(
    output_dir="./gemma-3-270m-finetuned-qa-ia3",
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    gradient_accumulation_steps=1,
    learning_rate=3e-4,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_strategy="epoch",
    run_name="gemma-3-270m-qa-ia3",
    warmup_ratio=0.1,
    lr_scheduler_type="cosine",
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
    callbacks=[monitor],
)

print("Starting IA3 training...")
trainer.train()
model.save_pretrained("./gemma-3-270m-finetuned-qa-ia3")
tokenizer.save_pretrained("./gemma-3-270m-finetuned-qa-ia3")
print("IA3 training completed!")

Loading weights:   0%|          | 0/236 [00:00<?, ?it/s]

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 46,080 || all params: 268,144,256 || trainable%: 0.0172
Starting IA3 training...
Initial Model Memory Footprint:
  Parameters: 268,144,256
  Precision: 4 bytes
  Total Memory: 3.81 GB
    - Parameters: 1.00 GB
    - KV Cache (est): 2.81 GB
  Estimated FLOPs per forward pass (batch=8, seq=512): 2.05 TFLOPS

============================================================
Epoch 0 Summary
============================================================
  Duration (s)         :         33.61
  Tokens Processed     :       684,032
  Throughput (token/s) :         20349
  Training Steps       :           167
  Avg CPU (%)          :          19.8
  Avg Memory (%)       :          13.8
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :         10.19
  FLOPs (per token)    :   0.50 GFLOPS

============================================================
Epoch 1 Summary
============================================================
  Duration (s)         :         35.11
  Tokens Processed     :       684,032
  Throughput (token/s) :         19483
  Training Steps       :           167
  Avg CPU (%)          :          28.4
  Avg Memory (%)       :          13.8
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          9.76
  FLOPs (per token)    :   0.50 GFLOPS

============================================================
Epoch 2 Summary
============================================================
  Duration (s)         :         35.24
  Tokens Processed     :       684,032
  Throughput (token/s) :         19409
  Training Steps       :           167
  Avg CPU (%)          :          20.5
  Avg Memory (%)       :          13.8
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          9.72
  FLOPs (per token)    :   0.50 GFLOPS

============================================================
TRAINING COMPLETE
============================================================
Total Training Time: 116.55s
Total Epochs: 3
Average Epoch Time: 34.66s
Total Tokens Processed: 2,052,096
Average Throughput: 17607 tokens/second
Total FLOPs: 1027.47 TFLOPS
Average TFLOPS (per second): 8.82
Overall FLOPs (per token): 0.50 GFLOPS

Final Metrics:
Memory Footprint: 3.81 GB
Inference Throughput: 20196 tokens/second
Total Training FLOPs: 342.49 TFLOPS
IA3 training completed!

In [51]:
summarize_training_results(trainer, monitor)

====================================================================================================
TRAINING RESULTS SUMMARY TABLE
====================================================================================================
Epoch Training Loss Validation Loss Time (s) Tokens Processed Throughput (token/s) TFLOPS (per second) Avg CPU (%) Avg Memory (%) Training Steps
    0        3.1455          3.2725    33.61          684,032                20349               10.19        19.8           13.8            167
    1        3.0190          3.2421    35.11          684,032                19483                9.76        28.4           13.8            167
    2        2.9806          3.2378    35.24          684,032                19408                9.72        20.5           13.8            167

----------------------------------------------------------------------------------------------------
TRAINING STATISTICS:
----------------------------------------------------------------------------------------------------
Total Training Time:      104.0 s
Average Epoch Time:       34.7 s
Total Tokens Processed:   2,052,096
Average Throughput:       19738 tokens/second
Average CPU Usage:        22.9%
Average Memory Usage:     13.8%
Total Training FLOPs:     1027.47 TFLOPS
Average TFLOPS (per sec): 9.88
Overall FLOPs (per token): 0.50 GFLOPS

====================================================================================================

**Reference** 
- [Huggingface:Cache strategies](https://huggingface.co/docs/transformers/en/kv_cache)
- [Arxiv:Dynamic Compressing Prompts for Efficient Inference of Large Language Models](https://arxiv.org/html/2504.11004v1)
- [Huggingface:IA3](https://huggingface.co/docs/peft/en/conceptual_guides/ia3)
- [Arxiv:Few-Shot Parameter-Efficient Fine-Tuning is Better and Cheaper than In-Context Learning](https://arxiv.org/abs/2205.05638)

### Bias-Only Fine-tuning (BitFit)

Bias-Only Fine-tuning (BitFit) is a minimalist parameter-efficient fine-tuning (PEFT) strategy that updates only the bias terms (b) of a pre-trained model while keeping all weight matrices (W) frozen. This technique is based on the research finding that the foundational knowledge of an LLM is stored in its weights, while the "task-specific shift" required to adapt to a new domain can often be achieved just by recalibrating the bias offsets.

In a typical Transformer model like BERT or Gemma, bias parameters account for roughly 0.08% to 0.1% of the total parameter count. Despite this tiny footprint, BitFit can often match the performance of full fine-tuning, especially on small-to-medium datasets.

**How it Works**

In a standard linear layer calculation $y = Wx + b$, traditional fine-tuning updates both $W$ and $b$. BitFit modifies the optimization process:

- Frozen Weights: All large weight matrices ($W_{query}$, $W_{key}$, $W_{value}$, $W_{FFN}$) are locked.
- Trainable Biases: Only the additive bias vectors ($b$) are allowed to receive gradients.
- Activation Shifting: By adjusting these biases, the model "nudges" its internal activations. This essentially "re-centers" the pre-trained features to better fit the statistical distribution of the new task.

**Implements BitFit**

The provided script manually implements the BitFit logic by traversing the model's named parameters and selectively unfreezing them based on their names and shapes.

**Global Freeze:**

    for param in model.parameters():
        param.requires_grad = False

This ensures that by default, no part of the 270M parameters in Gemma will be updated, saving significant memory.

**Keyword-Based Selection:**

    if any(keyword in name.lower() for keyword in ['bias', '.bias', '_bias']):
        param.requires_grad = True

The code identifies parameters explicitly named as "bias." These are the primary targets of the BitFit paper.

**Heuristic Fallbacks:**

Modern models like Gemma-3 often use `LayerNorm` or `RMSNorm` which may not have traditional "bias" names. The code smartly handles this by searching for:
- Normalization Parameters: Gamma and beta parameters in `LayerNorm` act similarly to biases by scaling and shifting distributions.
- Small 1D Tensors: If a parameter is a small 1D array (unlike a 2D weight matrix), it is statistically likely to be a bias or offset term, and the code unfreezes it as a fallback.

**When to Use It**

BitFit is a specialized tool that excels in specific constraints:
- Extremely Limited Hardware: Since you are only storing gradients and optimizer states for approx. 0.1% of the model, you can fine-tune much larger models on consumer-grade GPUs that would otherwise crash during full fine-tuning.
- Small Data Regimes: When you only have a few hundred or thousand examples, BitFit acts as a natural regularizer. It prevents "catastrophic forgetting" because it is physically impossible for the model to drastically change its fundamental logic with just bias shifts.
- Multi-Task Serving: You can store 50 different "task-specific" bias sets for the same model on a single disk. Swapping between them is near-instantaneous and requires almost no storage space.
- High-Speed Prototyping: Because the search space is so small, BitFit often converges much faster than LoRA or full fine-tuning.

In [ ]:
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    Trainer,
    TrainingArguments,
    DataCollatorForLanguageModeling,
)
from datasets import DatasetDict, Dataset
import torch

In [9]:
# Configuration
MODEL_NAME = "google/gemma-3-270m"   
OUTPUT_DIR = "./gemma-3-270m-finetuned-qa-bitfit"

model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    device_map="auto",
    torch_dtype=torch.float32,
    low_cpu_mem_usage=True,
)

# BitFit Implementation - Find all bias parameters
print("Applying BitFit: freezing all parameters except biases...")

# First freeze all parameters
for param in model.parameters():
    param.requires_grad = False

# Unfreeze bias parameters
bias_params = []
trainable_count = 0

# Try different naming conventions for biases
for name, param in model.named_parameters():
    # Check for bias parameters in various naming conventions
    if any(keyword in name.lower() for keyword in ['bias', '.bias', '_bias']):
        param.requires_grad = True
        trainable_count += param.numel()
        bias_params.append(name)
        #print(f"  Found bias parameter: {name}")

# If no biases found with standard names, try to find any additive parameters
if len(bias_params) == 0:
    print("No standard bias parameters found. Searching for LayerNorm parameters...")
    
    # Look for LayerNorm gamma/beta parameters (these are like biases in normalization layers)
    for name, param in model.named_parameters():
        if any(keyword in name.lower() for keyword in ['layernorm', 'norm', 'gamma', 'beta']):
            param.requires_grad = True
            trainable_count += param.numel()
            bias_params.append(name)
            #print(f"  Found LayerNorm parameter: {name}")

# If still no trainable parameters, find ANY parameter with small dimensions (likely biases)
if len(bias_params) == 0:
    print("No bias parameters found. Searching for small-dimensional parameters...")
    
    for name, param in model.named_parameters():
        # Biases are usually 1D tensors
        if len(param.shape) == 1 and param.numel() < 10000:  # Small 1D parameters likely biases
            param.requires_grad = True
            trainable_count += param.numel()
            bias_params.append(name)
            #print(f"  Found small 1D parameter (likely bias): {name}")

# If still no trainable parameters, fallback to training final layer biases
if len(bias_params) == 0:
    print("No biases found. Training last layer parameters as fallback...")
    
    # Find the final output layer
    for name, param in model.named_parameters():
        if 'lm_head' in name or 'output' in name or 'proj' in name:
            if len(param.shape) == 1:  # Only unfreeze 1D parameters (biases)
                param.requires_grad = True
                trainable_count += param.numel()
                bias_params.append(name)
                #print(f"  Found output layer bias: {name}")

# Verify we have trainable parameters
total_params = sum(p.numel() for p in model.parameters())
print(f"\nTotal parameters: {total_params:,}")
print(f"Trainable parameters (BitFit): {trainable_count:,}")
print(f"Trainable percentage: {trainable_count/total_params*100:.4f}%")

if trainable_count == 0:
    raise ValueError("No trainable parameters found for BitFit! Check model architecture.")

data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

monitor = EpochMonitor(model=model)

training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    gradient_accumulation_steps=1,
    learning_rate=1e-3,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_strategy="epoch",
    run_name="gemma-3-270m-qa-bitfit",
    warmup_ratio=0.1,
    lr_scheduler_type="cosine",
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
    callbacks=[monitor]
)

print("\nStarting BitFit training...")
trainer.train()
model.save_pretrained(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)
print("BitFit training completed!")

Loading weights:   0%|          | 0/236 [00:00<?, ?it/s]

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Applying BitFit: freezing all parameters except biases...
No standard bias parameters found. Searching for LayerNorm parameters...

Total parameters: 268,098,176
Trainable parameters (BitFit): 55,936
Trainable percentage: 0.0209%

Starting BitFit training...
Initial Model Memory Footprint:
  Parameters: 268,098,176
  Precision: 4 bytes
  Total Memory: 3.81 GB
    - Parameters: 1.00 GB
    - KV Cache (est): 2.81 GB
  Estimated FLOPs per forward pass (batch=8, seq=512): 2.05 TFLOPS

============================================================
Epoch 0 Summary
============================================================
  Duration (s)         :         34.01
  Tokens Processed     :       684,032
  Throughput (token/s) :         20115
  Training Steps       :           167
  Avg CPU (%)          :          25.5
  Avg Memory (%)       :          14.5
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :         10.07
  FLOPs (per token)    :   0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================
Epoch 1 Summary
============================================================
  Duration (s)         :         34.68
  Tokens Processed     :       684,032
  Throughput (token/s) :         19726
  Training Steps       :           167
  Avg CPU (%)          :          28.2
  Avg Memory (%)       :          14.5
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          9.88
  FLOPs (per token)    :   0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================
Epoch 2 Summary
============================================================
  Duration (s)         :         35.08
  Tokens Processed     :       684,032
  Throughput (token/s) :         19497
  Training Steps       :           167
  Avg CPU (%)          :          24.8
  Avg Memory (%)       :          14.6
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          9.76
  FLOPs (per token)    :   0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['lm_head.weight'].

============================================================
TRAINING COMPLETE
============================================================
Total Training Time: 121.87s
Total Epochs: 3
Average Epoch Time: 34.59s
Total Tokens Processed: 2,052,096
Average Throughput: 16839 tokens/second
Total FLOPs: 1027.47 TFLOPS
Average TFLOPS (per second): 8.43
Overall FLOPs (per token): 0.50 GFLOPS

Final Metrics:
Memory Footprint: 3.81 GB
Inference Throughput: 20017 tokens/second
Total Training FLOPs: 342.49 TFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

BitFit training completed!

In [10]:
summarize_training_results(trainer, monitor)

====================================================================================================
TRAINING RESULTS SUMMARY TABLE
====================================================================================================
Epoch Training Loss Validation Loss Time (s) Tokens Processed Throughput (token/s) TFLOPS (per second) Avg CPU (%) Avg Memory (%) Training Steps
    0        3.0634          3.1779    34.01          684,032                20114               10.07        25.5           14.5            167
    1        2.8831          3.1494    34.68          684,032                19726                9.88        28.2           14.5            167
    2        2.8396          3.1473    35.08          684,032                19496                9.76        24.8           14.6            167

----------------------------------------------------------------------------------------------------
TRAINING STATISTICS:
----------------------------------------------------------------------------------------------------
Total Training Time:      103.8 s
Average Epoch Time:       34.6 s
Total Tokens Processed:   2,052,096
Average Throughput:       19776 tokens/second
Average CPU Usage:        26.2%
Average Memory Usage:     14.5%
Total Training FLOPs:     1027.47 TFLOPS
Average TFLOPS (per sec): 9.90
Overall FLOPs (per token): 0.50 GFLOPS

====================================================================================================

**Reference** 
- [Huggingface:BitFit: Simple Parameter-efficient Fine-tuning for Transformer-based Masked Language-model](https://huggingface.co/papers/2106.10199)
- [Arxiv:BitFit: Simple Parameter-efficient Fine-tuning for Transformer-based Masked Language-models](https://arxiv.org/abs/2106.10199)

### Compacter (using adapters library)

Compacter is a highly efficient parameter-efficient fine-tuning (PEFT) method that reduces the number of trainable parameters to extreme levels—often as low as 0.05% of the model—while maintaining the performance of full fine-tuning. It achieves this by replacing standard adapter weight matrices with Parameterized Hypercomplex Multiplication (PHM) layers.

While methods like LoRA use low-rank decomposition, Compacter goes a step further by using Kronecker products to generate large weight matrices from very small, shared "proto-matrices." This allows the model to learn complex task-specific patterns with a tiny memory footprint.

**How it Works**

Compacter works by decomposing an adapter's weight matrix W into a structured mathematical form:

- Parameterized Hypercomplex Multiplication (PHM): Instead of learning a full matrix $W$, Compacter learns a set of small matrices $\{A_i\}$ and $\{B_i\}$. The final weight matrix is reconstructed using the sum of their Kronecker products: $W = \sum_{i=1}^{n} A_i \otimes B_i$.
- Kronecker Product ($\otimes$): This operation creates a large matrix from two smaller ones. If $A$ is $2 \times 2$ and $B$ is $100 \times 100$, their Kronecker product is $200 \times 200$. This "parameter scaling" is the secret to Compacter's efficiency.
- Low-Rank Parameterization: To save even more space, the $B_i$ matrices are further constrained to be low-rank (similar to LoRA), often restricted to rank-1.
- Shared "Slow" Weights: Compacter typically shares the $A_i$ matrices across all layers of the model (called "slow" weights) and only keeps the tiny $B_i$ vectors unique to each layer ("fast" weights).

**IMplement Compacter**

The code provided actually implements LoRA, not Compacter. However, it highlights the architectural "slots" where a Compacter would be inserted.

**The Target Modules:**

    target_modules=["q_proj", "v_proj"]
In the code, LoRA creates A and B matrices for these layers. If this were a Compacter implementation, the library would instead inject PHM layers into these modules.

**The PEFT Wrapper:**

    model = get_peft_model(model, lora_config)
    
Both LoRA and Compacter use the same `get_peft_model` factory pattern. To switch to Compacter in a supported library (like some versions of adapter-transformers), one would replace LoraConfig with a CompacterConfig.

**The Core Difference:**

Where the LoRA code uses a rank `r=8`, Compacter would use a hypercomplex dimension n (usually 4 or 8) and Kronecker products. This would result in the "Trainable parameters" count being roughly 10x smaller than the already small LoRA count.

**When to Use It**

Compacter is the "extreme" choice for parameter efficiency. Use it when:
- Extreme Parameter Constraints: You need to fine-tune a model but have a strict storage budget (e.g., you need the final "delta" file to be under 1MB for a 7B model).
- Massive Multi-Tasking: You are hosting a service where you want to swap between hundreds of different task-specific "experts" (like medical, legal, and coding) instantly. Because Compacter adapters are tiny, switching them is faster than LoRA.
- Low-Resource Data: Compacter has been shown to be particularly robust when you have very little training data, as its highly constrained structure prevents the model from overfitting.
- Efficiency vs. Performance: You want to achieve 99% of the performance of full fine-tuning but are willing to accept a slightly more complex mathematical setup to save the maximum amount of VRAM and disk space.

In [ ]:
%%capture
!pip install -U adapters
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    Trainer,
    TrainingArguments,
    DataCollatorForLanguageModeling,
)
from datasets import DatasetDict, Dataset
import torch
from peft import get_peft_model, LoraConfig, TaskType
from adapters import AutoAdapterModel, CompacterConfig

In [10]:
# Configuration
MODEL_NAME = "google/gemma-3-270m"   
OUTPUT_DIR = "./gemma-3-270m-finetuned-qa-lora"

model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    device_map="auto",
    torch_dtype=torch.float32,
    low_cpu_mem_usage=True,
)

lora_config = LoraConfig(
    task_type=TaskType.CAUSAL_LM,
    inference_mode=False,
    r=8,
    lora_alpha=16,
    lora_dropout=0.1,
    target_modules=["q_proj", "v_proj"],
)

model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

monitor = EpochMonitor(model=model)

training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    gradient_accumulation_steps=1,
    learning_rate=2e-4,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_strategy="epoch",
    run_name="gemma-3-270m-qa-lora",
    warmup_ratio=0.1,
    lr_scheduler_type="cosine",
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
    callbacks=[monitor]
)

trainer.train()
model.save_pretrained(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)

No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.

trainable params: 368,640 || all params: 268,466,816 || trainable%: 0.1373

It is strongly recommended to train Gemma3 models with the `eager` attention implementation instead of `sdpa`. Use `eager` with `AutoModelForCausalLM.from_pretrained('<path-to-checkpoint>', attn_implementation='eager')`.

Initial Model Memory Footprint:
  Parameters: 268,466,816
  Precision: 4 bytes
  Total Memory: 3.81 GB
    - Parameters: 1.00 GB
    - KV Cache (est): 2.81 GB
  Estimated FLOPs per forward pass (batch=8, seq=512): 2.05 TFLOPS

============================================================
Epoch 0 Summary
============================================================
  Duration (s)         :         35.04
  Tokens Processed     :       684,032
  Throughput (token/s) :         19520
  Training Steps       :           167
  Avg CPU (%)          :          20.4
  Avg Memory (%)       :          13.2
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          9.77
  FLOPs (per token)    :   0.50 GFLOPS

============================================================
Epoch 1 Summary
============================================================
  Duration (s)         :         35.80
  Tokens Processed     :       684,032
  Throughput (token/s) :         19107
  Training Steps       :           167
  Avg CPU (%)          :          25.4
  Avg Memory (%)       :          13.6
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          9.57
  FLOPs (per token)    :   0.50 GFLOPS

============================================================
Epoch 2 Summary
============================================================
  Duration (s)         :         36.64
  Tokens Processed     :       684,032
  Throughput (token/s) :         18670
  Training Steps       :           167
  Avg CPU (%)          :          20.0
  Avg Memory (%)       :          13.5
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          9.35
  FLOPs (per token)    :   0.50 GFLOPS

============================================================
TRAINING COMPLETE
============================================================
Total Training Time: 122.75s
Total Epochs: 3
Average Epoch Time: 35.83s
Total Tokens Processed: 2,052,096
Average Throughput: 16717 tokens/second
Total FLOPs: 1027.47 TFLOPS
Average TFLOPS (per second): 8.37
Overall FLOPs (per token): 0.50 GFLOPS

Final Metrics:
Memory Footprint: 3.81 GB
Inference Throughput: 19690 tokens/second
Total Training FLOPs: 342.49 TFLOPS

('./gemma-3-270m-finetuned-qa-lora/tokenizer_config.json',
 './gemma-3-270m-finetuned-qa-lora/special_tokens_map.json',
 './gemma-3-270m-finetuned-qa-lora/tokenizer.model',
 './gemma-3-270m-finetuned-qa-lora/added_tokens.json',
 './gemma-3-270m-finetuned-qa-lora/tokenizer.json')

In [11]:
summarize_training_results(trainer, monitor)

====================================================================================================
TRAINING RESULTS SUMMARY TABLE
====================================================================================================
Epoch Training Loss Validation Loss Time (s) Tokens Processed Throughput (token/s) TFLOPS (per second) Avg CPU (%) Avg Memory (%) Training Steps
    0        2.8760          3.0522    35.04          684,032                19520                9.77        20.4           13.2            167
    1        2.4723          3.1864    35.80          684,032                19107                9.57        25.4           13.6            167
    2        2.3554          3.2177    36.64          684,032                18670                9.35        20.0           13.5            167

----------------------------------------------------------------------------------------------------
TRAINING STATISTICS:
----------------------------------------------------------------------------------------------------
Total Training Time:      107.5 s
Average Epoch Time:       35.8 s
Total Tokens Processed:   2,052,096
Average Throughput:       19093 tokens/second
Average CPU Usage:        21.9%
Average Memory Usage:     13.4%
Total Training FLOPs:     1027.47 TFLOPS
Average TFLOPS (per sec): 9.56
Overall FLOPs (per token): 0.50 GFLOPS

====================================================================================================

**Reference** 
- [Huggingface:Using Adapters at Hugging Face](https://huggingface.co/docs/hub/en/adapters)
- [Arxiv:Compacter: Efficient Low-Rank Hypercomplex Adapter Layers](https://arxiv.org/abs/2106.04647)
- [GitHub: adapters repository](https://github.com/adapter-hub/adapters)

### LayerScale Adaptation

LayerScale Adaptation is a parameter-efficient fine-tuning (PEFT) strategy that optimizes only the normalization and scaling parameters within a Large Language Model. Similar to BitFit (bias-only) or IA3 (activation scaling), it leaves the massive weight matrices ($\text{W}_{Q}, \text{W}_{K}, \text{W}_{V}, \text{W}_{FFN}$) frozen and focuses on the "valves" that control the flow and magnitude of information between transformer layers.

In models like Gemma or Llama, these parameters typically include the gain (scale) and bias (shift) terms of Layer Normalization or RMSNorm. By adjusting only these, the model recalibrates how much each feature dimension contributes to the next layer, allowing it to adapt to new distributions with minimal storage overhead.

**How it Works**

LayerScale Adaptation targets the mathematical transformation that occurs at the start or end of every transformer block. In a standard normalization layer:

$$y = \frac{x - \text{E}[x]}{\sqrt{\text{Var}[x] + \epsilon}} \cdot \gamma + \beta$$

- $\gamma$ (Gamma/Scale): Controls the "amplitude" of each feature channel.
- $\beta$ (Beta/Bias): Shifts the "center" of each feature channel.

By updating only γ and β, LayerScale Adaptation performs a "re-balancing" of the pre-trained features. If the base model is too sensitive to certain noise in your new dataset, the adaptation can shrink the γ for those dimensions. If a specific linguistic pattern is more important for your task, it can amplify the γ for those features.

**Implements LayerScale Adaptation**

The provided script performs a manual "surgery" on the Gemma-3-270m model to isolate the normalization parameters.

**The Global Freeze:**

    for param in model.parameters():
        param.requires_grad = False

This locks all 270 million parameters, ensuring the base knowledge is protected and the training memory remains low.

**Selective Unfreezing:**

    if any(keyword in name.lower() for keyword in ['layernorm', 'norm', 'scale']):
        param.requires_grad = True

The script iterates through every parameter name. In Gemma, normalization layers are typically named `input_layernorm` or `post_attention_layernorm`. By searching for "norm" or "scale," the code catches the γ and β parameters across all layers of the network.

**Targeted Optimization:**

Once unfrozen, the Trainer only calculates gradients for these specific vectors. Because these are 1D vectors (matching the hidden dimension size, e.g., 1024 or 2048) rather than 2D matrices, the number of trainable parameters is minuscule—often less than 0.05% of the model.

**When to Use It**

LayerScale Adaptation is an excellent choice when you need a balance between extreme efficiency and model stability:
- Domain Alignment: Use it when the task remains the same (e.g., general chat) but the vocabulary or style changes slightly (e.g., switching from casual chat to formal legal summaries).
- Preventing Training Instability: When fine-tuning very deep models, full fine-tuning can often lead to "gradient explosions." Scaling only the normalization layers acts as a natural stabilizer, keeping activations within a healthy range.
- Multi-Task "Switching": Because the resulting files are tiny (a few hundred KB), you can load different LayerScale "profiles" for different users or tasks almost instantly, making it ideal for edge computing or high-concurrency APIs.
- Resource-Constrained Devices: It is even more memory-efficient than LoRA because it does not require auxiliary matrices (A and B). If a model barely fits on your GPU, LayerScale is often the only way to squeeze out a fine-tune.

In [ ]:
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    Trainer,
    TrainingArguments,
    DataCollatorForLanguageModeling,
)
from datasets import DatasetDict, Dataset
import torch

In [12]:
# Configuration
MODEL_NAME = "google/gemma-3-270m"   
OUTPUT_DIR = "./gemma-3-270m-finetuned-qa-layerscale"

model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    device_map="auto",
    torch_dtype=torch.float32,
    low_cpu_mem_usage=True,
)

for param in model.parameters():
    param.requires_grad = False

for name, param in model.named_parameters():
    if any(keyword in name.lower() for keyword in ['layernorm', 'norm', 'scale']):
        param.requires_grad = True

data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

monitor = EpochMonitor(model=model)

training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    gradient_accumulation_steps=1,
    learning_rate=5e-4,
    weight_decay=0.0,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_strategy="epoch",
    run_name="gemma-3-270m-qa-layerscale",
    warmup_ratio=0.1,
    lr_scheduler_type="cosine",
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
    callbacks=[monitor]
)

trainer.train()
model.save_pretrained(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)

Initial Model Memory Footprint:
  Parameters: 268,098,176
  Precision: 4 bytes
  Total Memory: 3.81 GB
    - Parameters: 1.00 GB
    - KV Cache (est): 2.81 GB
  Estimated FLOPs per forward pass (batch=8, seq=512): 2.05 TFLOPS

============================================================
Epoch 0 Summary
============================================================
  Duration (s)         :         35.47
  Tokens Processed     :       684,032
  Throughput (token/s) :         19286
  Training Steps       :           167
  Avg CPU (%)          :          26.9
  Avg Memory (%)       :          13.6
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          9.66
  FLOPs (per token)    :   0.50 GFLOPS

============================================================
Epoch 1 Summary
============================================================
  Duration (s)         :         35.37
  Tokens Processed     :       684,032
  Throughput (token/s) :         19340
  Training Steps       :           167
  Avg CPU (%)          :          28.1
  Avg Memory (%)       :          13.9
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          9.68
  FLOPs (per token)    :   0.50 GFLOPS

============================================================
Epoch 2 Summary
============================================================
  Duration (s)         :         35.39
  Tokens Processed     :       684,032
  Throughput (token/s) :         19330
  Training Steps       :           167
  Avg CPU (%)          :          24.9
  Avg Memory (%)       :          13.9
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          9.68
  FLOPs (per token)    :   0.50 GFLOPS

There were missing keys in the checkpoint model loaded: ['lm_head.weight'].

============================================================
TRAINING COMPLETE
============================================================
Total Training Time: 129.54s
Total Epochs: 3
Average Epoch Time: 35.41s
Total Tokens Processed: 2,052,096
Average Throughput: 15841 tokens/second
Total FLOPs: 1027.47 TFLOPS
Average TFLOPS (per second): 7.93
Overall FLOPs (per token): 0.50 GFLOPS

Final Metrics:
Memory Footprint: 3.81 GB
Inference Throughput: 19991 tokens/second
Total Training FLOPs: 342.49 TFLOPS

('./gemma-3-270m-finetuned-qa-layerscale/tokenizer_config.json',
 './gemma-3-270m-finetuned-qa-layerscale/special_tokens_map.json',
 './gemma-3-270m-finetuned-qa-layerscale/tokenizer.model',
 './gemma-3-270m-finetuned-qa-layerscale/added_tokens.json',
 './gemma-3-270m-finetuned-qa-layerscale/tokenizer.json')

In [13]:
summarize_training_results(trainer, monitor)

====================================================================================================
TRAINING RESULTS SUMMARY TABLE
====================================================================================================
Epoch Training Loss Validation Loss Time (s) Tokens Processed Throughput (token/s) TFLOPS (per second) Avg CPU (%) Avg Memory (%) Training Steps
    0        3.1178          3.2430    35.47          684,032                19285                9.66        26.9           13.6            167
    1        2.9773          3.2103    35.37          684,032                19340                9.68        28.1           13.9            167
    2        2.9397          3.2067    35.39          684,032                19330                9.68        24.9           13.9            167

----------------------------------------------------------------------------------------------------
TRAINING STATISTICS:
----------------------------------------------------------------------------------------------------
Total Training Time:      106.2 s
Average Epoch Time:       35.4 s
Total Tokens Processed:   2,052,096
Average Throughput:       19319 tokens/second
Average CPU Usage:        26.6%
Average Memory Usage:     13.8%
Total Training FLOPs:     1027.47 TFLOPS
Average TFLOPS (per sec): 9.67
Overall FLOPs (per token): 0.50 GFLOPS

====================================================================================================

**Reference** 
- [Arxiv:Adaptive Layer Selection for Efficient Vision Transformer Fine-Tuning](https://arxiv.org/abs/2408.08670)
- [Arxiv:Adaptive Layer Selection for Layer-Wise Token Pruning in LLM Inference](https://arxiv.org/abs/2601.07667)

### HyperAdapters / HyperLoRA

HyperAdapters (and their low-rank variant, HyperLoRA) represent a meta-learning approach to LLM optimization. Instead of learning fixed adapter weights for a specific task, this method uses a secondary neural network—called a Hypernetwork—to generate the weights for the adapters on the fly.

Think of it as the difference between buying a custom-made suit (Standard LoRA) and owning a 3D printer that prints a new suit every time you need to go to a different event (HyperLoRA). The hypernetwork takes an "embedding" (representing a task, a language, or even a specific user) and outputs the parameters that should be injected into the main LLM.

**How it Works**

The architecture involves a hierarchy of two models:
- The Target Model (LLM): The large pre-trained transformer remains frozen. It contains "slots" for adapters (like LoRA matrices or bottleneck layers).
- The Hypernetwork: A smaller, separate network (often an MLP or a small Transformer). Its input is a Task Embedding or Conditioning Vector.
- Weight Generation: The hypernetwork's output is not a prediction, but a set of weights. These weights are reshaped and "plugged into" the Target Model's adapter slots.
- Parameter Sharing: Because one hypernetwork can generate weights for many different tasks, the parameters of the hypernetwork are shared across all tasks. This allows the system to learn the "logic" of how to adapt a model, rather than just memorizing a single task.

**Implementation HyperLoRA**

The provided code implements Standard LoRA, but it sets the stage for HyperLoRA by defining the target architecture.

**Comprehensive Target Modules:**

    target_modules=["q_proj", "v_proj", "k_proj", "o_proj", "gate_proj", "up_proj", "down_proj"]

By targeting every major projection in **Gemma-3-270m**, the code creates a high-dimensional "adaptation surface." In a HyperLoRA setup, the hypernetwork would be responsible for generating the rank matrices ($A$ and $B$) for *all* these layers simultaneously based on a single input vector.

**The PEFT Integration**: The `get_peft_model` function used here is the same entry point for HyperLoRA. To transform this into HyperLoRA, the LoraConfig would be replaced by a configuration that defines the hypernetwork's structure and the dimensionality of the task embeddings.

**Frozen Backbone**: 

The core principle shown in the code—tuning a tiny fraction of parameters while keeping the base model static—is exactly how HyperLoRA maintains efficiency. The hypernetwork itself becomes the only "trainable" part of the system.

**When to Use It**

HyperAdapters are most effective in highly dynamic or multi-task environments:
- Massive Multi-Task Learning: If you need a model to handle 1,000 different tasks, storing 1,000 separate LoRA adapters is inefficient. One HyperLoRA model can generate all 1,000 adapters using just 1,000 tiny task-ID vectors.
- Zero-Shot Task Generalization: If trained correctly, a hypernetwork can generate an adapter for a task it has never seen before, provided you give it a description or embedding of that task.
- Dynamic Personalization: In a chatbot environment, the hypernetwork can take "User Context" as input and generate a personalized adapter for every single conversation, adapting the tone and knowledge in real-time.
- Cross-Lingual Transfer: You can use a hypernetwork to learn how to "shift" an English model into dozens of other languages by inputting language embeddings, rather than training separate models for each language.

In [ ]:
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    Trainer,
    TrainingArguments,
    DataCollatorForLanguageModeling,
)
from datasets import DatasetDict, Dataset
import torch
from peft import get_peft_model, LoraConfig, TaskType

In [14]:
# Configuration
MODEL_NAME = "google/gemma-3-270m"   
OUTPUT_DIR = "./gemma-3-270m-finetuned-qa-lora"

model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    device_map="auto",
    torch_dtype=torch.float32,
    low_cpu_mem_usage=True,
)

lora_config = LoraConfig(
    task_type=TaskType.CAUSAL_LM,
    inference_mode=False,
    r=8,
    lora_alpha=16,
    lora_dropout=0.1,
    target_modules=["q_proj", "v_proj", "k_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
)

model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

monitor = EpochMonitor(model=model)

training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    gradient_accumulation_steps=1,
    learning_rate=2e-4,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_strategy="epoch",
    run_name="gemma-3-270m-qa-lora",
    warmup_ratio=0.1,
    lr_scheduler_type="cosine",
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
    callbacks=[monitor]
)

trainer.train()
model.save_pretrained(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)

No label_names provided for model class `PeftModelForCausalLM`. Since `PeftModel` hides base models input arguments, if label_names is not given, label_names can't be set automatically within `Trainer`. Note that empty label_names list will be used instead.

trainable params: 1,898,496 || all params: 269,996,672 || trainable%: 0.7032
Initial Model Memory Footprint:
  Parameters: 269,996,672
  Precision: 4 bytes
  Total Memory: 3.82 GB
    - Parameters: 1.01 GB
    - KV Cache (est): 2.81 GB
  Estimated FLOPs per forward pass (batch=8, seq=512): 2.05 TFLOPS

============================================================
Epoch 0 Summary
============================================================
  Duration (s)         :         41.84
  Tokens Processed     :       684,032
  Throughput (token/s) :         16348
  Training Steps       :           167
  Avg CPU (%)          :          25.1
  Avg Memory (%)       :          13.8
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          8.19
  FLOPs (per token)    :   0.50 GFLOPS

============================================================
Epoch 1 Summary
============================================================
  Duration (s)         :         42.15
  Tokens Processed     :       684,032
  Throughput (token/s) :         16228
  Training Steps       :           167
  Avg CPU (%)          :          23.4
  Avg Memory (%)       :          14.0
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          8.13
  FLOPs (per token)    :   0.50 GFLOPS

============================================================
Epoch 2 Summary
============================================================
  Duration (s)         :         42.11
  Tokens Processed     :       684,032
  Throughput (token/s) :         16243
  Training Steps       :           167
  Avg CPU (%)          :          22.5
  Avg Memory (%)       :          14.0
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          8.13
  FLOPs (per token)    :   0.50 GFLOPS

============================================================
TRAINING COMPLETE
============================================================
Total Training Time: 145.28s
Total Epochs: 3
Average Epoch Time: 42.03s
Total Tokens Processed: 2,052,096
Average Throughput: 14125 tokens/second
Total FLOPs: 1027.47 TFLOPS
Average TFLOPS (per second): 7.07
Overall FLOPs (per token): 0.50 GFLOPS

Final Metrics:
Memory Footprint: 3.82 GB
Inference Throughput: 16788 tokens/second
Total Training FLOPs: 342.49 TFLOPS

('./gemma-3-270m-finetuned-qa-lora/tokenizer_config.json',
 './gemma-3-270m-finetuned-qa-lora/special_tokens_map.json',
 './gemma-3-270m-finetuned-qa-lora/tokenizer.model',
 './gemma-3-270m-finetuned-qa-lora/added_tokens.json',
 './gemma-3-270m-finetuned-qa-lora/tokenizer.json')

In [15]:
summarize_training_results(trainer, monitor)

====================================================================================================
TRAINING RESULTS SUMMARY TABLE
====================================================================================================
Epoch Training Loss Validation Loss Time (s) Tokens Processed Throughput (token/s) TFLOPS (per second) Avg CPU (%) Avg Memory (%) Training Steps
    0        2.4455          3.5807    41.84          684,032                16347                8.19        25.1           13.8            167
    1        1.3686          4.4867    42.15          684,032                16228                8.13        23.4           14.0            167
    2        0.9957          5.1175    42.11          684,032                16243                8.13        22.5           14.0            167

----------------------------------------------------------------------------------------------------
TRAINING STATISTICS:
----------------------------------------------------------------------------------------------------
Total Training Time:      126.1 s
Average Epoch Time:       42.0 s
Total Tokens Processed:   2,052,096
Average Throughput:       16273 tokens/second
Average CPU Usage:        23.7%
Average Memory Usage:     14.0%
Total Training FLOPs:     1027.47 TFLOPS
Average TFLOPS (per sec): 8.15
Overall FLOPs (per token): 0.50 GFLOPS

====================================================================================================

**Reference** 
- [Arxiv:HyperLoRA: Parameter-Efficient Adaptive Generation for Portrait Synthesis](https://arxiv.org/abs/2503.16944)
- [Huggingface:LoRA](https://huggingface.co/docs/peft/en/package_reference/lora)

# Model Compression

Model Compression is a suite of techniques designed to reduce the size, memory footprint, and computational requirements of Large Language Models (LLMs). In the context of fine-tuning and deployment, compression bridges the gap between massive "foundation" models and the practical constraints of hardware, such as GPU VRAM, power consumption, and latency requirements.

While fine-tuning teaches a model what to do, compression optimizes how it exists on hardware.

**Core Techniques in Model Compression**

Compression is typically applied at different stages of the lifecycle, ranging from pre-training to post-inference.

**1. Quantization (The same as in the previous section)**

Quantization reduces the numerical precision of the model's weights and activations. Most LLMs are trained in 16-bit or 32-bit floating point (FP16 or FP32). Quantization "squashes" these values into 8-bit (INT8), 4-bit (INT4), or even 1-bit formats.
- Post-Training Quantization (PTQ): Applied after fine-tuning is complete (e.g., using GPTQ or AWQ).
- Quantization-Aware Training (QAT): The model is trained to handle the loss of precision during the fine-tuning process itself (e.g., QLoRA).

**2. Pruning**

Pruning involves identifying and removing redundant or non-essential parameters (neurons or entire layers) from the network.
- Unstructured Pruning: Individual weights are set to zero based on their magnitude.
- Structured Pruning: Entire blocks, such as attention heads or feed-forward channels, are removed. This is more hardware-friendly and leads to direct speedups.

**3. Knowledge Distillation**
This process involves a large "Teacher" model (e.g., Llama-3-70B) training a smaller "Student" model (e.g., Llama-3-8B). The student learns to mimic the teacher's output distribution, capturing much of the teacher's reasoning capability in a fraction of the size.

**4. Weight Sharing and Low-Rank Approximation**

Techniques like Compacter or LoRA (when used for compression) decompose large weight matrices into smaller, shared components. By representing a large matrix as the product of two smaller ones, the total number of parameters stored on disk is drastically reduced.

**When to Use Model Compression**

Compression is not always necessary, but it is critical in specific deployment and fine-tuning scenarios.
- Use it during Fine-Tuning when: VRAM is Limited: If you want to fine-tune a 70B model on a single 24GB or 48GB GPU, you must use QLoRA (4-bit quantization) to fit the model and its gradients into memory.
- Training Speed is Critical: Compressed models (especially those using 4-bit or 8-bit precision) often allow for larger batch sizes, which can speed up the training throughput.
- Use it during Deployment when: Deploying to the Edge: If the model must run on a smartphone, laptop, or IoT device, compression (specifically 4-bit quantization via llama.cpp/GGUF) is mandatory to fit within the device's RAM.
- Reducing Latency (Time-to-First-Token): Smaller, quantized models can be moved from GPU memory to the processor faster, and the integer math involved is often hardware-accelerated, leading to higher tokens per second.
- Lowering Serving Costs: In a cloud environment, using compressed models allows you to serve more users on a single GPU instance or use cheaper, older GPU hardware (like a T4 instead of an H100).
- Multi-Tenancy: When you need to keep many different fine-tuned "specialists" in memory at once, compressing each one ensures you don't run out of VRAM as you switch between tasks.

## Prunning Strategies

Pruning is the process of removing redundant or less important weights from a neural network to reduce its size and improve inference speed. In LLMs, pruning strategies are categorized by their granularity (how they cut) and their timing (when they cut).

**1. Structural Granularity: How to Prune**

- Unstructured Pruning: Individual weights are removed based on their magnitude (smallest values first). While this achieves high theoretical compression, it creates "sparse" matrices that standard hardware (GPUs) struggle to accelerate, often resulting in no real-world speedup.
- Structured Pruning: Entire components are removed, such as attention heads, feed-forward channels, or even full layers. This creates smaller, dense matrices that lead to immediate improvements in memory usage and latency on any hardware.

**2. Timing Strategies: When to Prune**

- Post-Training Pruning (PTP): Pruning is applied to a fully trained model. It often requires a small "calibration" dataset to determine which weights are least important.
- Pruning During Fine-Tuning: The model is pruned and fine-tuned simultaneously. This allows the remaining weights to compensate for the removed ones, leading to much higher accuracy retention.
- Sparse Fine-Tuning: Only a subset of weights is updated during training, effectively "growing" a sparse structure that is optimized for the specific task.

**3. Decision Metrics: What to Prune**

- Magnitude-based: Removes weights with the smallest absolute values ($|w|$).
- Gradient-based: Removes weights that have the least impact on the loss function (low gradients).
- Taylor Pruning: Uses a mathematical approximation (Taylor expansion) to estimate how much the model's error will increase if a specific parameter is removed.
- Wanda (Weights and Activations): A modern LLM strategy that prunes weights based on the product of their magnitude and the norm of the input activations, specifically designed to work without intensive retraining.

**When to Use Pruning**

- Deployment on Edge Devices: When a model must fit within the strict RAM limits of a smartphone or local PC.Reducing Serving Costs: When you want to decrease the "Time-per-Token" (latency) and increase the number of requests a single GPU can handle.
- Task-Specific Compression: When a model is being fine-tuned for a narrow task (e.g., sentiment analysis), many "general knowledge" circuits become redundant and can be pruned without loss of performance.

## Progressive Pruning Strategies

Progressive Pruning is a sophisticated optimization strategy where an LLM is slimmed down incrementally throughout the fine-tuning process. Rather than removing a large portion of the model in a single "one-shot" operation—which often causes irreversible damage to the model's reasoning capabilities—progressive pruning follows a schedule. It slowly increases the sparsity of the model, allowing the remaining active parameters to "heal" and adapt to the loss of their neighbors.

**Weight Pruning During Fine-Tuning**

This category focuses on trimming the internal parameters of the model to find the most efficient sub-network for a specific task.
- Magnitude Pruning with Regrowth: This approach identifies and removes weights with the smallest absolute values. Crucially, it allows for "regrowth" by periodically re-activating some pruned connections if they show significant gradient importance, ensuring the model doesn't get stuck in a suboptimal sparse pattern early on.
- Gradient-based Pruning: Instead of looking at weight size, this method targets parameters with consistently small gradients. If a weight isn't changing much during training, it is deemed uninformative for the task and removed.
- The Lottery Ticket Hypothesis: This research-driven strategy aims to identify "winning" sparse subnetworks within a large model. Through progressive pruning, the model is winnowed down to these essential connections, which are then fine-tuned to achieve the same performance as the original dense model.
- Structured Pruning: While weight pruning often targets individual parameters (unstructured), structured pruning removes entire hardware-aligned blocks, such as attention heads, feed-forward neurons, or even whole layers. This is the gold standard for deployment because it creates dense, smaller matrices that current GPUs can process significantly faster.

**Token and Sequence Optimization**

Beyond pruning static weights, progressive strategies can also prune the data as it flows through the model, optimizing the "context" the model has to process.
- Dynamic Token Pruning (DTP) and Attention Selection: These methods evaluate the importance of tokens at each layer. As a sequence passes through the transformer, the model "drops" unimportant tokens (like punctuation or filler words) based on low attention scores, reducing the computational load for deeper layers.
- Token Merging (ToMe): Rather than deleting tokens, this strategy identifies highly similar token representations and merges them into a single vector. This effectively reduces the sequence length without losing the semantic information contained in the discarded tokens.
- Sequence Length Curriculum: This is a training-time optimization where the model is initially fine-tuned on very short sequences. The length is progressively increased as training continues, "pruning" the initial computational cost and helping the model learn local patterns before tackling long-range dependencies.
- Sliding Window Attention: Often used in deployment, this restricts each token's attention to a fixed-size local window rather than the entire sequence. This keeps memory usage constant and prevents the quadratic scaling issues usually associated with long-context LLMs.

**When to Use Progressive Pruning**

Progressive pruning should be implemented when accuracy retention is more important than training speed. It is ideal for deploying high-performance models on edge devices (smartphones, laptops) where RAM is strictly limited. It is also the best choice for "Extreme Compression" (removing 80% or more of the model), as one-shot methods typically fail at these levels. Finally, use it when you need a hardware-friendly speedup; structured pruning combined with token merging can often double or triple the inference throughput of an LLM on standard cloud GPUs.

### Token Merging (ToMe)

Token Merging (ToMe) is an optimization technique originally developed by Meta AI for Vision Transformers (ViT) and later adapted for Large Language Models. It reduces the computational cost of the attention mechanism—which scales quadratically with sequence length—by combining redundant or highly similar tokens into a single representative token.

Unlike Pruning, which simply deletes tokens and loses their information, Merging fuses the information from similar tokens using a weighted average or interpolation. This preserves the "signal" of the data while drastically shortening the sequence the model has to process.

**How it Works**

The core principle of ToMe is to identify "redundancy" within a sequence. In natural language, many tokens carry overlapping semantic meaning or are part of a predictable pattern. ToMe operates through three main steps:
- Similarity Scoring: The model calculates the similarity between tokens using a distance metric, typically the cosine similarity of their feature embeddings (the "Keys" in the attention layer).
- Matching: A lightweight bipartite matching algorithm identifies the best pairs of tokens to merge based on their similarity scores.
- Fusion: The identified pairs are merged into a single new token. In many implementations, this is a simple weighted average based on the number of original tokens each merged token represents. This ensures that the importance of a "large" merged block is preserved in future attention calculations.

**Implements Token Mergin (ToMe)**

The provided code implements a Static Input-Level Token Merging strategy using a custom PyTorch hook and a trainer wrapper.

- Fixed Ratio Reduction: The TokenMergingHook uses a `merge_ratio (0.3)` to calculate exactly how many tokens must be eliminated. If the sequence is 128 tokens, it aims to keep only 89 tokens.

- Segmental Truncation & Repacking: 

        new_input_ids = input_ids[:, :keep_tokens].clone()

The hook keeps the first portion of the sequence intact. In this specific implementation, it doesn't perform complex semantic matching; instead, it preserves the most important initial context and then "merges" the remaining tail of the sequence into a single representative **EOS (End of Sentence)** token.
Information Preservation: By preserving the first keep_tokens, the code ensures the prompt and initial instructions are untouched. The "merging" of the rest into an EOS token signals to the model that the sequence has ended, effectively forcing the model to operate on a compressed input space.

- Trainer Integration: The TokenMergingTrainer overrides the collate_fn. This means every time a batch is loaded for training or evaluation, it is passed through the merge_tokens function before reaching the model's layers. This reduces the VRAM used by the attention matrices (Q,K,V) because the sequence length N is physically smaller.

**When to Use It**

ToMe is a "speed-accuracy" trade-off tool. It should be used in the following scenarios:

-  Long-Context Processing: When processing very long documents (e.g., 8k+ tokens) where the $O(N^2)$ cost of attention becomes a bottleneck for speed or memory.
- High-Throughput Inference: In production environments where you need to serve more requests per second and can tolerate a minor (usually <1%) drop in accuracy.
- Multi-Modal Tasks: ToMe is exceptionally effective in Video and Image LLMs, where visual patches are often highly redundant (e.g., many tokens representing a solid blue sky).
- Edge Deployment: When a model is too large for the VRAM of a mobile device or a small GPU; reducing the token count is often more effective than pruning for keeping the model "smart."

In [ ]:
%%capture
!pip install "git+https://github.com/facebookresearch/ToMe.git"
import torch
import torch.nn as nn
import torch.nn.functional as F
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    Trainer,
    TrainingArguments,
    DataCollatorForLanguageModeling,
    BitsAndBytesConfig,
)
from datasets import DatasetDict, Dataset
from peft import get_peft_model, LoraConfig, TaskType
import gc
import tome

In [7]:
# Configuration 
MODEL_NAME = "meta-llama/Llama-2-7b-hf"
OUTPUT_DIR = "./llama-2-7b-finetuned-qa-tome"
MAX_LENGTH = 128
MERGE_RATIO = 0.3
WARMUP_STEPS = 50

# Tokenizer
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"

def tokenize_examples(data, max_length=MAX_LENGTH):
    texts = [
        f"<s>Question: {row['question_title']}\n{row['question_body']}\nAnswer: {row['answer']}</s>"
        for row in data.iter_rows(named=True)
    ]
    tokenized = tokenizer(
        texts,
        truncation=True,
        max_length=max_length,
        padding="max_length",
        return_tensors="pt"
    )
    tokenized["labels"] = tokenized["input_ids"].clone()
    tokenized["labels"][tokenized["labels"] == tokenizer.pad_token_id] = -100
    return tokenized

# Token Merging Hook 
class TokenMergingHook:
    """Merge tokens at input level to reduce sequence length."""
    def __init__(self, merge_ratio=0.3):
        self.merge_ratio = merge_ratio
        self.merge_active = True

    def merge_tokens(self, input_ids, attention_mask, labels):
        if not self.merge_active or self.merge_ratio <= 0.0:
            return input_ids, attention_mask, labels

        batch_size, seq_len = input_ids.shape
        keep_tokens = max(1, int(seq_len * (1 - self.merge_ratio)))

        if keep_tokens >= seq_len:
            return input_ids, attention_mask, labels

        # Keep first keep_tokens
        new_input_ids = input_ids[:, :keep_tokens].clone()
        new_attention_mask = attention_mask[:, :keep_tokens].clone()
        new_labels = labels[:, :keep_tokens].clone()

        # Merge remaining tokens
        if keep_tokens < seq_len:
            remaining_labels = labels[:, keep_tokens:]
            remaining_mask = attention_mask[:, keep_tokens:]
            
            # Find last valid token in remaining segment
            last_valid_idx = (remaining_mask.cumsum(dim=1).argmax(dim=1)).clamp(max=remaining_mask.shape[1]-1)
            
            # Use EOS token as representative
            avg_token_ids = torch.full((batch_size,), tokenizer.eos_token_id, device=input_ids.device)
            
            new_input_ids = torch.cat([new_input_ids, avg_token_ids.unsqueeze(1)], dim=1)
            new_attention_mask = torch.cat([new_attention_mask, torch.ones_like(avg_token_ids).unsqueeze(1)], dim=1)
            new_labels = torch.cat([new_labels, avg_token_ids.unsqueeze(1)], dim=1)

        return new_input_ids, new_attention_mask, new_labels

# Quantization Config
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
)

# Load Base Model 
print("Loading base model with quantization...")
base_model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    quantization_config=bnb_config,
    device_map="auto",
    low_cpu_mem_usage=True,
    torch_dtype=torch.float16,  # use torch_dtype, not dtype
)

# Apply LoRA
lora_config = LoraConfig(
    task_type=TaskType.CAUSAL_LM,
    r=8,
    lora_alpha=16,
    lora_dropout=0.1,
    target_modules=["q_proj", "v_proj", "k_proj", "o_proj"],
    bias="none",
)
model = get_peft_model(base_model, lora_config)
model.print_trainable_parameters()

# Token Merging Hook Instance
tome_hook = TokenMergingHook(merge_ratio=MERGE_RATIO)

# Custom Trainer
class TokenMergingTrainer(Trainer):
    def __init__(self, tome_hook, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.tome_hook = tome_hook

    def get_train_dataloader(self):
        dataloader = super().get_train_dataloader()
        return self._wrap_dataloader(dataloader)

    def get_eval_dataloader(self, eval_dataset=None):
        dataloader = super().get_eval_dataloader(eval_dataset)
        return self._wrap_dataloader(dataloader)

    def _wrap_dataloader(self, dataloader):
        original_collate_fn = dataloader.collate_fn
        
        def tome_collate_fn(batch):
            collated = original_collate_fn(batch)
            if self.tome_hook.merge_active:
                input_ids, attention_mask, labels = self.tome_hook.merge_tokens(
                    collated["input_ids"],
                    collated["attention_mask"],
                    collated["labels"]
                )
                collated["input_ids"] = input_ids
                collated["attention_mask"] = attention_mask
                collated["labels"] = labels
            return collated
        
        dataloader.collate_fn = tome_collate_fn
        return dataloader

    def prediction_step(self, model, inputs, prediction_loss_only, ignore_keys=None):
        with torch.no_grad():
            if self.tome_hook.merge_active:
                inputs["input_ids"], inputs["attention_mask"], inputs["labels"] = self.tome_hook.merge_tokens(
                    inputs["input_ids"],
                    inputs["attention_mask"],
                    inputs["labels"]
                )
            outputs = model(**inputs)
            loss = outputs.loss
            return (loss, None, None)
        
monitor = EpochMonitor(model=model)

# Training Arguments 
training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=2,
    per_device_eval_batch_size=2,
    gradient_accumulation_steps=4,
    gradient_checkpointing=True,
    gradient_checkpointing_kwargs={"use_reentrant": False},
    learning_rate=2e-4,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=1,
    remove_unused_columns=False,
    logging_steps=10,
    warmup_steps=WARMUP_STEPS,
    lr_scheduler_type="cosine",
    fp16=True,
    optim="adamw_torch",
    dataloader_num_workers=2,
    ddp_find_unused_parameters=False,
)

# Data 
print("Tokenizing training data...")
train_tokenized = tokenize_examples(train_data)
print("Tokenizing validation data...")
val_tokenized = tokenize_examples(val_data)

dataset_dict = DatasetDict({
    "train": Dataset.from_dict({
        "input_ids": train_tokenized["input_ids"],
        "attention_mask": train_tokenized["attention_mask"],
        "labels": train_tokenized["labels"]
    }),
    "validation": Dataset.from_dict({
        "input_ids": val_tokenized["input_ids"],
        "attention_mask": val_tokenized["attention_mask"],
        "labels": val_tokenized["labels"]
    })
})

print(f"Train examples: {len(dataset_dict['train']):,}")
print(f"Validation examples: {len(dataset_dict['validation']):,}")

# Trainer 
trainer = TokenMergingTrainer(
    tome_hook=tome_hook,
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=DataCollatorForLanguageModeling(
        tokenizer=tokenizer,
        mlm=False,
        pad_to_multiple_of=8
    ),
    callbacks = [monitor]
)

# Pre-Training Stats

print("\n" + "="*60)
print("Starting Training with Token Merging (ToMe)")
print("="*60)
print(f"Model device: {model.device}")
print(f"Original sequence length: {MAX_LENGTH}")
print(f"Token merging ratio: {MERGE_RATIO}")
print(f"Target sequence length after merge: {int(MAX_LENGTH * (1 - MERGE_RATIO))}")
print(f"GPU memory allocated: {torch.cuda.memory_allocated(0)/1024**3:.2f} GB")
print(f"GPU memory cached: {torch.cuda.memory_reserved(0)/1024**3:.2f} GB\n")

# Train
train_result = trainer.train()

# Final Metrics
print("\n" + "="*60)
print("TRAINING COMPLETE")
print("="*60)
print(f"Training Loss: {train_result.training_loss:.6f}")
print(f"Global Steps: {train_result.global_step}")

print("\nRunning final evaluation...")
eval_results = trainer.evaluate()
print(f"Validation Loss: {eval_results['eval_loss']:.6f}")

# Save 
print("\nSaving model and tokenizer...")
model.save_pretrained(OUTPUT_DIR, safe_serialization=True)
tokenizer.save_pretrained(OUTPUT_DIR)
print(f"Model saved to {OUTPUT_DIR}")

`torch_dtype` is deprecated! Use `dtype` instead!

Loading base model with quantization...

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

trainable params: 8,388,608 || all params: 6,746,804,224 || trainable%: 0.1243
Tokenizing training data...
Tokenizing validation data...
Train examples: 1,331
Validation examples: 285

============================================================
Starting Training with Token Merging (ToMe)
============================================================
Model device: cuda:0
Original sequence length: 128
Token merging ratio: 0.3
Target sequence length after merge: 89
GPU memory allocated: 3.63 GB
GPU memory cached: 12.44 GB

Initial Model Memory Footprint:
  Parameters: 3,508,801,536
  Precision: 2 bytes
  Total Memory: 8.54 GB
    - Parameters: 6.54 GB
    - KV Cache (est): 2.00 GB
  Estimated FLOPs per forward pass (batch=8, seq=512): 42.86 TFLOPS

============================================================
Epoch 0 Summary
============================================================
  Duration (s)         :         343.31
  Tokens Processed     :        171,008
  Throughput (token/s) :            498
  Training Steps       :            167
  Avg CPU (%)          :           23.3
  Avg Memory (%)       :           12.4
  Total FLOPs          : 1789.20 TFLOPS
  TFLOPS (per second)  :           5.21
  FLOPs (per token)    :   10.46 GFLOPS

============================================================
Epoch 1 Summary
============================================================
  Duration (s)         :         336.54
  Tokens Processed     :        171,008
  Throughput (token/s) :            508
  Training Steps       :            167
  Avg CPU (%)          :           22.1
  Avg Memory (%)       :           12.4
  Total FLOPs          : 1789.20 TFLOPS
  TFLOPS (per second)  :           5.32
  FLOPs (per token)    :   10.46 GFLOPS

============================================================
Epoch 2 Summary
============================================================
  Duration (s)         :         329.72
  Tokens Processed     :        171,008
  Throughput (token/s) :            519
  Training Steps       :            167
  Avg CPU (%)          :           22.1
  Avg Memory (%)       :           12.5
  Total FLOPs          : 1789.20 TFLOPS
  TFLOPS (per second)  :           5.43
  FLOPs (per token)    :   10.46 GFLOPS

============================================================
TRAINING COMPLETE
============================================================
Total Training Time: 1074.94s
Total Epochs: 3
Average Epoch Time: 336.53s
Total Tokens Processed: 513,024
Average Throughput: 477 tokens/second
Total FLOPs: 5367.61 TFLOPS
Average TFLOPS (per second): 4.99
Overall FLOPs (per token): 10.46 GFLOPS

Final Metrics:
Memory Footprint: 8.54 GB
Inference Throughput: 523 tokens/second
Total Training FLOPs: 1789.20 TFLOPS

============================================================
TRAINING COMPLETE
============================================================
Training Loss: 0.970877
Global Steps: 501

Running final evaluation...

Validation Loss: 2.774498

Saving model and tokenizer...
Model saved to ./llama-2-7b-finetuned-qa-tome

In [8]:
summarize_training_results(trainer, monitor)

====================================================================================================
TRAINING RESULTS SUMMARY TABLE
====================================================================================================
Epoch Training Loss Validation Loss Time (s) Tokens Processed Throughput (token/s) TFLOPS (per second) Avg CPU (%) Avg Memory (%) Training Steps
    0        2.3845          2.7745   343.31          171,008                  498                5.21        23.3           12.4            167
    1        2.1512          4.4120   336.54          171,008                  508                5.32        22.1           12.4            167
    2        1.9390          4.7741   329.72          171,008                  518                5.43        22.1           12.5            167

----------------------------------------------------------------------------------------------------
TRAINING STATISTICS:
----------------------------------------------------------------------------------------------------
Total Training Time:      1009.6 s
Average Epoch Time:       336.5 s
Total Tokens Processed:   513,024
Average Throughput:       508 tokens/second
Average CPU Usage:        22.5%
Average Memory Usage:     12.4%
Total Training FLOPs:     5367.61 TFLOPS
Average TFLOPS (per sec): 5.32
Overall FLOPs (per token): 10.46 GFLOPS

====================================================================================================

**Reference** 
- [Arxiv:Token Merging: Your ViT But Faster](https://arxiv.org/abs/2210.09461)
- [GutHub: ToMe Repository](https://github.com/facebookresearch/ToMe)
- [Huggingface:Token merging](https://huggingface.co/docs/diffusers/en/optimization/tome)

### Structured Pruning (Head/Layer Removal)

Structured Pruning is a model compression technique that removes entire architectural components—such as attention heads, feed-forward neurons, or whole transformer layers—rather than individual, isolated weights.

Unlike Unstructured Pruning, which creates "holey" matrices that standard hardware (GPUs) cannot process efficiently, Structured Pruning results in smaller, dense matrices. This alignment with hardware allows for direct acceleration of inference speed and a significant reduction in VRAM consumption, as the model is physically smaller in memory.

**How it Works**

Structured Pruning operates by identifying and deleting the "channels" of information flow within the model:
- Attention Head Pruning: In a multi-head attention setup, specific heads may be redundant or specialized for tasks not needed for the target domain. Removing them reduces the width of the attention computation.
- Neuron (MLP) Pruning: Large Language Models spend the majority of their parameters in Feed-Forward Networks (FFN). By removing a percentage of the intermediate neurons, the internal "hidden" layers are narrowed.
- Layer Pruning: This is the most aggressive form, where an entire transformer block is bypassed or deleted. This drastically reduces the depth of the model and improves processing speed linearly with the number of layers removed.
- Hardware Realignment: After weights are zeroed out or removed, the tensors are often "squeezed" to eliminate the zeroed dimensions, resulting in smaller weight matrices that fit more comfortably on consumer hardware.

**Implements Structured Pruning**

The script defines a `StructuredPruner` class that performs manual "surgery" on the Llama-2-7b architecture by manipulating the underlying PyTorch tensors before fine-tuning begins.

**Head Pruning via Reshaping:**

    reshaped_weight = original_weight.view(num_heads, head_dim, -1)
    reshaped_weight[-heads_to_prune_per_layer:] = 0

The code treats the output projection matrix as a collection of heads. It reshapes the 2D matrix into 3D (heads × head dimension × hidden size) and sets the last 25% of these heads to zero. This ensures that the output of those specific heads is effectively silenced.

**Neuron Pruning across Projections:**

    original_gate_weight[-neurons_to_prune_per_layer:] = 0
    original_up_weight[-neurons_to_prune_per_layer:] = 0
    original_down_weight[:, -neurons_to_prune_per_layer:] = 0

In Llama's MLP architecture, neurons are distributed across three projections (gate, up, and down). To remove a neuron, its corresponding row must be zeroed in the input projections and its corresponding column must be zeroed in the output projection.

**Layer Removal:**

    self.model.model.layers = self.model.model.layers[:layers_to_keep]

This physically deletes layers from the `torch.nn.ModuleList`. By shortening the list of layers, the model's forward pass automatically skips the deleted blocks, providing the most significant speedup.

**LoRA Recovery:**

After the pruning "surgery," the code applies a LoRA (Low-Rank Adaptation) adapter. This is a critical step: pruning damages the model's knowledge, and the subsequent fine-tuning with LoRA allows the model to "re-learn" how to use its remaining parameters to achieve the task.

**When to Use It**

Structured Pruning is specifically designed for deployment-heavy scenarios:
- Hardware Speedups: Use it when your primary goal is to increase "Tokens per Second." Because the matrices are smaller, the GPU performs fewer floating-point operations (FLOPs).
- VRAM Constraints: If a model (like 70B) is slightly too large for your GPU memory, structured pruning can narrow the model just enough to fit without requiring complex sharding.
- Latency-Sensitive Apps: For real-time applications like chatbots or coding assistants, removing layers or heads can reduce the "Time to First Token" significantly.
- Mobile and Edge Deployment: When deploying on devices that lack specialized sparse-matrix acceleration, structured pruning is the only way to ensure the model remains fast and responsive.

In [ ]:
%%capture
!pip install torchao

import torch
import torch.nn as nn
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    Trainer,
    TrainingArguments,
    DataCollatorForLanguageModeling,
    BitsAndBytesConfig,
)
from peft import LoraConfig, get_peft_model
from datasets import DatasetDict, Dataset
import gc
import os
import numpy as np

In [7]:
# Configuration
MODEL_NAME = "meta-llama/Llama-2-7b-hf"
OUTPUT_DIR = "./llama-2-7b-finetuned-qa-structured-prune"

# Tokenizer 
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME, token=os.environ.get("HF_TOKEN", None))
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"

def tokenize_examples(data, max_length=MAX_LENGTH):
    texts = [
        f"Question: {row['question_title']}\n{row['question_body']}\nAnswer: {row['answer']}"
        for row in data.iter_rows(named=True)
    ]
    tokenized = tokenizer(
        texts,
        truncation=True,
        max_length=max_length,
        padding="max_length",
        return_tensors="pt"
    )
    tokenized["labels"] = tokenized["input_ids"].clone()
    tokenized["labels"][tokenized["labels"] == tokenizer.pad_token_id] = -100
    return tokenized

# Data 
print("Tokenizing datasets...")
train_tokenized = tokenize_examples(train_data)
val_tokenized = tokenize_examples(val_data)

dataset_dict = DatasetDict({
    "train": Dataset.from_dict(train_tokenized),
    "validation": Dataset.from_dict(val_tokenized)
})

print(f"Train examples: {len(dataset_dict['train']):,}")
print(f"Validation examples: {len(dataset_dict['validation']):,}")

Tokenizing datasets...
Train examples: 1,331
Validation examples: 285

In [8]:
# Pruning configuration
PRUNE_ATTENTION_HEADS = True
PRUNE_NEURONS = True
PRUNE_LAYERS = False

HEAD_PRUNING_PERCENT = 25  # % of attention heads to prune per layer
NEURON_PRUNING_PERCENT = 20  # % of MLP neurons to prune per layer
LAYER_PRUNING_PERCENT = 10  # % of layers to prune (if enabled)

# Quantization Config 
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
)

# Load Model 
print(f"Loading base model: {MODEL_NAME}")
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    quantization_config=bnb_config,
    device_map="auto",
    token=os.environ.get("HF_TOKEN", None),
)

print(f"Model loaded: {type(model).__name__}")
print(f"Number of layers: {model.config.num_hidden_layers}")
print(f"Heads per layer: {model.config.num_attention_heads}")
print(f"Intermediate size: {model.config.intermediate_size}")

Loading base model: meta-llama/Llama-2-7b-hf

Loading weights:   0%|          | 0/291 [00:00<?, ?it/s]

Model loaded: LlamaForCausalLM
Number of layers: 32
Heads per layer: 32
Intermediate size: 11008

In [9]:
monitor = EpochMonitor(model=model)

# Structured Pruning Implementation 
class StructuredPruner:
    def __init__(self, model):
        self.model = model
        self.device = next(model.parameters()).device
        self.pruning_masks = {}
        
    def prune_attention_heads(self, prune_percent=25):
        """Prune attention heads by setting their output projections to zero."""
        print(f"\n{'='*50}")
        print(f"PRUNING ATTENTION HEADS ({prune_percent}%)")
        print(f"{'='*50}")
        
        config = self.model.config
        num_layers = config.num_hidden_layers
        num_heads = config.num_attention_heads
        num_kv_heads = getattr(config, 'num_key_value_heads', num_heads)
        head_dim = config.hidden_size // num_heads
        
        heads_to_prune_per_layer = int(num_heads * prune_percent / 100)
        heads_to_keep_per_layer = num_heads - heads_to_prune_per_layer
        
        for layer_idx in range(num_layers):
            # Access the attention module
            attn_module = self.model.model.layers[layer_idx].self_attn
            
            # Get the output projection weight
            o_proj = attn_module.o_proj
            
            # Create pruning mask for heads (prune last 'heads_to_prune_per_layer' heads)
            # Shape: [num_heads, head_dim] for output projection
            with torch.no_grad():
                original_weight = o_proj.weight.data
                # Reshape to separate heads: [num_heads, head_dim, hidden_size]
                reshaped_weight = original_weight.view(num_heads, head_dim, -1)
                
                # Zero out pruned heads
                if heads_to_prune_per_layer > 0:
                    reshaped_weight[-heads_to_prune_per_layer:] = 0
                
                # Reshape back and assign
                o_proj.weight.data = reshaped_weight.view(original_weight.shape)
                
                # Also zero out biases if they exist
                if o_proj.bias is not None:
                    bias_data = o_proj.bias.data
                    reshaped_bias = bias_data.view(num_heads, head_dim)
                    if heads_to_prune_per_layer > 0:
                        reshaped_bias[-heads_to_prune_per_layer:] = 0
                    o_proj.bias.data = reshaped_bias.view(bias_data.shape)
            
            self.pruning_masks[f"layer_{layer_idx}_heads"] = heads_to_prune_per_layer
        
        print(f"  Pruned {heads_to_prune_per_layer}/{num_heads} heads per layer ({prune_percent}%)")
        print(f"  Remaining heads: {heads_to_keep_per_layer} per layer")
    
    def prune_neurons(self, prune_percent=20):
        """Prune MLP neurons by setting their intermediate activations to zero."""
        print(f"\n{'='*50}")
        print(f"PRUNING MLP NEURONS ({prune_percent}%)")
        print(f"{'='*50}")
        
        config = self.model.config
        num_layers = config.num_hidden_layers
        intermediate_size = config.intermediate_size
        
        neurons_to_prune_per_layer = int(intermediate_size * prune_percent / 100)
        neurons_to_keep_per_layer = intermediate_size - neurons_to_prune_per_layer
        
        for layer_idx in range(num_layers):
            # Access the MLP module
            mlp_module = self.model.model.layers[layer_idx].mlp
            
            # For Llama, MLP has gate_proj, up_proj, down_proj
            # We prune by zeroing rows in gate_proj and up_proj, and columns in down_proj
            with torch.no_grad():
                # Prune gate_proj (rows)
                gate_proj = mlp_module.gate_proj
                original_gate_weight = gate_proj.weight.data
                if neurons_to_prune_per_layer > 0:
                    original_gate_weight[-neurons_to_prune_per_layer:] = 0
                if gate_proj.bias is not None:
                    original_gate_bias = gate_proj.bias.data
                    original_gate_bias[-neurons_to_prune_per_layer:] = 0
                
                # Prune up_proj (rows)
                up_proj = mlp_module.up_proj
                original_up_weight = up_proj.weight.data
                if neurons_to_prune_per_layer > 0:
                    original_up_weight[-neurons_to_prune_per_layer:] = 0
                if up_proj.bias is not None:
                    original_up_bias = up_proj.bias.data
                    original_up_bias[-neurons_to_prune_per_layer:] = 0
                
                # Prune down_proj (columns)
                down_proj = mlp_module.down_proj
                original_down_weight = down_proj.weight.data
                if neurons_to_prune_per_layer > 0:
                    original_down_weight[:, -neurons_to_prune_per_layer:] = 0
                if down_proj.bias is not None:
                    # Bias doesn't correspond to neurons, leave as is
                    pass
            
            self.pruning_masks[f"layer_{layer_idx}_neurons"] = neurons_to_prune_per_layer
        
        print(f"  Pruned {neurons_to_prune_per_layer}/{intermediate_size} neurons per layer ({prune_percent}%)")
        print(f"  Remaining neurons: {neurons_to_keep_per_layer} per layer")
    
    def prune_layers(self, prune_percent=10):
        """Remove entire transformer layers."""
        print(f"\n{'='*50}")
        print(f"PRUNING LAYERS ({prune_percent}%)")
        print(f"{'='*50}")
        
        config = self.model.config
        num_layers = config.num_hidden_layers
        layers_to_prune = int(num_layers * prune_percent / 100)
        layers_to_keep = num_layers - layers_to_prune
        
        if layers_to_prune > 0:
            # Remove last 'layers_to_prune' layers
            self.model.model.layers = self.model.model.layers[:layers_to_keep]
            config.num_hidden_layers = layers_to_keep
            
            print(f"  Removed {layers_to_prune}/{num_layers} layers ({prune_percent}%)")
            print(f"  Remaining layers: {layers_to_keep}")
            self.pruning_masks["pruned_layers"] = layers_to_prune
        else:
            print(f"  No layers pruned")
    
    def apply_pruning(self):
        """Apply all configured pruning strategies."""
        print(f"\n{'='*60}")
        print(f"STRUCTURED PRUNING")
        print(f"{'='*60}")
        
        if PRUNE_ATTENTION_HEADS:
            self.prune_attention_heads(HEAD_PRUNING_PERCENT)
        
        if PRUNE_NEURONS:
            self.prune_neurons(NEURON_PRUNING_PERCENT)
        
        if PRUNE_LAYERS:
            self.prune_layers(LAYER_PRUNING_PERCENT)
        
        print(f"\nStructured pruning completed!")
        return self.model

# Apply Structured Pruning 
pruner = StructuredPruner(model)
model = pruner.apply_pruning()

# Store pruning masks in model for reference
model.pruning_masks = pruner.pruning_masks

# Apply LoRA
lora_config = LoraConfig(
    task_type="CAUSAL_LM",
    r=8,
    lora_alpha=16,
    lora_dropout=0.1,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
    bias="none",
)
model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

# Training Arguments 
total_steps = len(dataset_dict["train"]) * 3 // (2 * 8)  # samples * epochs / (batch_size * grad_accum)
training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=2,
    per_device_eval_batch_size=2,
    gradient_accumulation_steps=8,
    gradient_checkpointing=True,
    learning_rate=1e-4,
    weight_decay=0.01,
    max_grad_norm=0.5,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_steps=20,
    warmup_steps=int(0.1 * total_steps),
    lr_scheduler_type="cosine",
    fp16=True,
    optim="paged_adamw_8bit",
    dataloader_num_workers=2,
    ddp_find_unused_parameters=False if torch.cuda.device_count() > 1 else None,
)

# Trainer 
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=DataCollatorForLanguageModeling(
        tokenizer=tokenizer,
        mlm=False,
    ),
    callbacks = [monitor]
)

print(f"\n{'='*60}")
print(f"STARTING FINE-TUNING WITH STRUCTURED PRUNING")
print(f"{'='*60}")
trainer.train()

============================================================
STRUCTURED PRUNING
============================================================

==================================================
PRUNING ATTENTION HEADS (25%)
==================================================
  Pruned 8/32 heads per layer (25%)
  Remaining heads: 24 per layer

==================================================
PRUNING MLP NEURONS (20%)
==================================================
  Pruned 2201/11008 neurons per layer (20%)
  Remaining neurons: 8807 per layer

Structured pruning completed!
trainable params: 19,988,480 || all params: 6,758,404,096 || trainable%: 0.2958

============================================================
STARTING FINE-TUNING WITH STRUCTURED PRUNING
============================================================
Initial Model Memory Footprint:
  Parameters: 3,520,401,408
  Precision: 2 bytes
  Total Memory: 8.56 GB
    - Parameters: 6.56 GB
    - KV Cache (est): 2.00 GB
  Estimated FLOPs per forward pass (batch=8, seq=512): 42.86 TFLOPS

============================================================
Epoch 0 Summary
============================================================
  Duration (s)         :        392.37
  Tokens Processed     :        86,016
  Throughput (token/s) :           219
  Training Steps       :            84
  Avg CPU (%)          :          22.1
  Avg Memory (%)       :          12.3
  Total FLOPs          : 899.96 TFLOPS
  TFLOPS (per second)  :          2.29
  FLOPs (per token)    :  10.46 GFLOPS

============================================================
Epoch 1 Summary
============================================================
  Duration (s)         :        388.96
  Tokens Processed     :        86,016
  Throughput (token/s) :           221
  Training Steps       :            84
  Avg CPU (%)          :          24.1
  Avg Memory (%)       :          12.3
  Total FLOPs          : 899.96 TFLOPS
  TFLOPS (per second)  :          2.31
  FLOPs (per token)    :  10.46 GFLOPS

============================================================
Epoch 2 Summary
============================================================
  Duration (s)         :        382.95
  Tokens Processed     :        86,016
  Throughput (token/s) :           225
  Training Steps       :            84
  Avg CPU (%)          :          23.1
  Avg Memory (%)       :          12.3
  Total FLOPs          : 899.96 TFLOPS
  TFLOPS (per second)  :          2.35
  FLOPs (per token)    :  10.46 GFLOPS

============================================================
TRAINING COMPLETE
============================================================
Total Training Time: 1244.67s
Total Epochs: 3
Average Epoch Time: 388.09s
Total Tokens Processed: 258,048
Average Throughput: 207 tokens/second
Total FLOPs: 2699.88 TFLOPS
Average TFLOPS (per second): 2.17
Overall FLOPs (per token): 10.46 GFLOPS

Final Metrics:
Memory Footprint: 8.56 GB
Inference Throughput: 232 tokens/second
Total Training FLOPs: 899.96 TFLOPS

TrainOutput(global_step=252, training_loss=10.929329342312283, metrics={'train_runtime': 1242.978, 'train_samples_per_second': 3.212, 'train_steps_per_second': 0.203, 'total_flos': 2.0323535661563904e+16, 'train_loss': 10.929329342312283, 'epoch': 3.0})

**Alternative : using torch prunning**

In [ ]:
# Install torch-pruning for better pruning support
# pip install torch-pruning

import torch_pruning as tp

# After loading the model, use torch_pruning for structured pruning
if num_layers > 0 and num_heads > 0:
    # Example pruning with torch_pruning
    print("Using torch_pruning for structured pruning...")
    
    # Define pruning strategy
    strategy = tp.strategy.L1Strategy()
    
    # Prune attention heads
    for layer_idx in range(num_layers):
        layer = model.model.layers[layer_idx].self_attn
        
        # Prune 25% of heads from each projection
        for proj_name in ['q_proj', 'k_proj', 'v_proj', 'o_proj']:
            if hasattr(layer, proj_name):
                proj = getattr(layer, proj_name)
                # This is simplified - actual implementation needs more details
                print(f"Would prune {proj_name} in layer {layer_idx}")

**Reference** 
- [Arxiv:Structured Pruning of Large Language Models](https://arxiv.org/abs/1910.04732)
- [Arxiv:Structured Pruning for Deep Convolutional Neural Networks: A survey](https://arxiv.org/abs/2303.00566)
- [APXML:Model Pruning Strategies](https://apxml.com/courses/advanced-pytorch/chapter-4-deployment-performance-optimization/pruning-strategies)
- [Arxiv:High-Layer Attention Pruning with Rescaling](https://arxiv.org/html/2507.01900v1)
- [PyTorch:Pruning Tutorial](https://docs.pytorch.org/tutorials/intermediate/pruning_tutorial.html)
- [Huggingface:LoRA](https://huggingface.co/docs/peft/en/package_reference/lora)

### Magnitude Pruning with Regrowth (RigL/Sparse Training)

Magnitude Pruning with Regrowth (often associated with algorithms like RigL or SET) is a dynamic optimization strategy that maintains a constant level of sparsity throughout the training process. Unlike standard pruning, which permanently deletes weights, this method periodically removes the smallest weights (pruning) and "grows back" new connections in locations that show high gradient sensitivity (regrowth). This allows the model to continuously explore different sparse architectures while training, eventually settling on the most efficient "wiring" for the specific task.

**How it Works**

The process typically follows a three-step cycle during the fine-tuning phase:
- Magnitude Pruning: At the start of a cycle, the connections with the smallest absolute values (∣w∣) are zeroed out. The assumption is that small weights contribute the least to the model’s output.
- Gradient-Based Regrowth: The model identifies "dead" connections (currently zero) that have the largest gradients. A large gradient suggests that activating this specific connection would significantly reduce the model's loss.
- Redistribution: The model "reallocates" its parameter budget. It takes the "slots" freed up by the small weights and initializes new weights in the high-gradient locations. This keeps the total number of active parameters constant.

This cycle prevents the model from being "locked in" to a bad pruning decision made early in training.

**Implements Magnitude Pruning**

The provided code uses the `torch.nn.utils.prune` utility to implement the Magnitude Pruning phase of this strategy.

**Global Linear Layer Targeting:**

    if isinstance(module, torch.nn.Linear):
        prune.l1_unstructured(module, name='weight', amount=0.5)

The script iterates through the entire Gemma-3-270m model. Every linear layer (where most parameters live) is subjected to 50% unstructured pruning. The `l1_unstructured` function calculates the L1 norm (absolute value) of the weights and creates a binary mask where the bottom 50% are set to zero.

**Mask Reparameterization:**

Under the hood, PyTorch renames the original weight to `weight_orig` and creates a `weight_mask`. During the forward pass, the model effectively computes `weight = weight_orig * weight_mask`.

**Fixed Mask Fine-Tuning:**

While the code performs the "Pruning" part effectively, it does not explicitly implement the "Regrowth" logic (which usually requires a custom optimizer or training hook to update the mask based on gradients). In this specific snippet, the model is fine-tuning the remaining 50% of weights to recover the accuracy lost during the initial prune.

**Finalization:**

    prune.remove(module, 'weight')

This step is vital for deployment. It "integrates" the mask into the weights, making the zero values permanent and removing the extra overhead of the `weight_orig` and mask tensors before saving the model.

**When to Use It**

Magnitude Pruning with Regrowth is ideal for scenarios where efficiency and performance must be perfectly balanced:
- Extreme Sparsity Requirements: When the goal is to remove 80–95% of the model's parameters. Standard pruning usually fails at these levels, but regrowth allows the model to find a functional "sub-skeleton" that works.
- Hardware with Sparse Acceleration: Use this if the target deployment hardware (like certain NVIDIA Ampere or Hopper GPUs) supports sparse tensor cores, which can skip the zero values to provide 2x speedups.
- Preventing Brain Damage: Because the model can "change its mind" about which weights are important, this method is much more robust than one-shot pruning for complex reasoning tasks.
- Resource-Constrained Training: It is useful when there is a desire to train a "dense" model's capabilities but the memory budget only allows for maintaining a "sparse" set of active gradients.

In [ ]:
import torch
import torch.nn.utils.prune as prune
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    Trainer,
    TrainingArguments,
    DataCollatorForLanguageModeling,
)
from datasets import DatasetDict, Dataset

In [9]:
# Configuration
MODEL_NAME = "google/gemma-3-270m"   
OUTPUT_DIR = "./gemma-3-270m-finetuned-qa-sparse"

model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    device_map="auto",
    torch_dtype=torch.float32,
    low_cpu_mem_usage=True,
)

# Apply magnitude pruning to linear layers
for name, module in model.named_modules():
    if isinstance(module, torch.nn.Linear):
        prune.l1_unstructured(module, name='weight', amount=0.5)

data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

monitor = EpochMonitor(model=model)

training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    gradient_accumulation_steps=1,
    learning_rate=2e-5,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_strategy="epoch",
    run_name="gemma-3-270m-qa-sparse",
    warmup_ratio=0.1,
    lr_scheduler_type="cosine",
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
    callbacks = [monitor]
)

total_params = sum(p.numel() for p in model.parameters())
print(f"Total parameters: {total_params:,}")
print("Starting training with magnitude pruning...")

trainer.train()

# Remove pruning reparameterization before saving
for name, module in model.named_modules():
    if isinstance(module, torch.nn.Linear) and hasattr(module, 'weight_orig'):
        prune.remove(module, 'weight')

model.save_pretrained(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)

`torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors:   0%|          | 0.00/536M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/236 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/133 [00:00<?, ?B/s]

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Total parameters: 268,098,176
Starting training with magnitude pruning...
Initial Model Memory Footprint:
  Parameters: 268,098,176
  Precision: 4 bytes
  Total Memory: 3.81 GB
    - Parameters: 1.00 GB
    - KV Cache (est): 2.81 GB
  Estimated FLOPs per forward pass (batch=8, seq=512): 2.05 TFLOPS

============================================================
Epoch 0 Summary
============================================================
  Duration (s)         :         55.99
  Tokens Processed     :       684,032
  Throughput (token/s) :         12218
  Training Steps       :           167
  Avg CPU (%)          :          23.0
  Avg Memory (%)       :          12.3
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          6.12
  FLOPs (per token)    :   0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================
Epoch 1 Summary
============================================================
  Duration (s)         :         60.89
  Tokens Processed     :       684,032
  Throughput (token/s) :         11233
  Training Steps       :           167
  Avg CPU (%)          :          25.3
  Avg Memory (%)       :          12.4
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          5.62
  FLOPs (per token)    :   0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================
Epoch 2 Summary
============================================================
  Duration (s)         :         60.78
  Tokens Processed     :       684,032
  Throughput (token/s) :         11255
  Training Steps       :           167
  Avg CPU (%)          :          21.2
  Avg Memory (%)       :          12.3
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          5.64
  FLOPs (per token)    :   0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['lm_head.weight_orig'].

============================================================
TRAINING COMPLETE
============================================================
Total Training Time: 211.08s
Total Epochs: 3
Average Epoch Time: 59.22s
Total Tokens Processed: 2,052,096
Average Throughput: 9722 tokens/second
Total FLOPs: 1027.47 TFLOPS
Average TFLOPS (per second): 4.87
Overall FLOPs (per token): 0.50 GFLOPS

Final Metrics:
Memory Footprint: 3.81 GB
Inference Throughput: 13323 tokens/second
Total Training FLOPs: 342.49 TFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

('./gemma-3-270m-finetuned-qa-sparse/tokenizer_config.json',
 './gemma-3-270m-finetuned-qa-sparse/tokenizer.json')

In [10]:
summarize_training_results(trainer, monitor)

====================================================================================================
TRAINING RESULTS SUMMARY TABLE
====================================================================================================
Epoch Training Loss Validation Loss Time (s) Tokens Processed Throughput (token/s) TFLOPS (per second) Avg CPU (%) Avg Memory (%) Training Steps
    0        9.2114          8.6068    55.99          684,032                12217                6.12        23.0           12.3            167
    1        3.8563         11.2606    60.89          684,032                11233                5.62        25.3           12.4            167
    2        2.4467         12.6330    60.78          684,032                11254                5.64        21.2           12.3            167

----------------------------------------------------------------------------------------------------
TRAINING STATISTICS:
----------------------------------------------------------------------------------------------------
Total Training Time:      177.7 s
Average Epoch Time:       59.2 s
Total Tokens Processed:   2,052,096
Average Throughput:       11551 tokens/second
Average CPU Usage:        23.2%
Average Memory Usage:     12.3%
Total Training FLOPs:     1027.47 TFLOPS
Average TFLOPS (per sec): 5.78
Overall FLOPs (per token): 0.50 GFLOPS

====================================================================================================

**Reference** 
- [PyTorch:Pruning Tutorial](https://docs.pytorch.org/tutorials/intermediate/pruning_tutorial.html)
- [Arxiv:Rigging the Lottery: Making All Tickets Winners](https://arxiv.org/pdf/1911.11134)
- [Arxiv:A SIMPLE AND EFFECTIVE PRUNING APPROACH FOR LARGE LANGUAGE MODELS](https://arxiv.org/pdf/2306.11695)
- [APXML:Model Pruning Strategies](https://apxml.com/courses/advanced-pytorch/chapter-4-deployment-performance-optimization/pruning-strategies)
- [Arxiv:Confident magnitude-based neural network pruning](https://arxiv.org/abs/2408.04759)
- [ACM:MaGrIP: Magnitude and Gradient-Informed Pruning for Task-Agnostic Large Language Model](https://dl.acm.org/doi/10.1145/3766068)

### Sequence Length Curriculum

Sequence Length Curriculum is an optimization strategy where a model is trained on progressively longer sequences over time. Instead of starting with the maximum context window (e.g., 2048 or 4096 tokens), the training process begins with very short segments and increases the length in stages. This approach is based on the principle of "curriculum learning," where a model masters simple patterns in short sequences before moving on to the complex long-range dependencies found in longer texts.

**How it Works**

The core mechanism relies on the quadratic complexity of the standard Attention mechanism. In a transformer, the computational cost and memory usage scale with the square of the sequence length ($N^2$).
- Stage 1 (Short): The modelMaster masters local context (syntax, grammar, and short-range semantics). Because sequences are short, the model processes many more examples per second, and GPU memory usage is minimal.
- Transition: As training progresses, the "curriculum" increases the token limit. The model leverages what it learned about local structures to help it understand how those structures relate over longer distances.
- Final Stage (Long): The model is fine-tuned on the full target sequence length. By this point, the "heavy lifting" of language understanding is done, and the final stage focuses on long-range coherence and memory.

**Implements Sequence Length Curriculum**

The provided script implements this strategy using a custom TrainerCallback that modifies the dataset and model behavior at the start of every epoch.

**Defining the Schedule:**

    SEQUENCE_STAGES = [64, 96, 128]

The curriculum is explicitly defined here: Epoch 1 uses 64 tokens, Epoch 2 uses 96, and Epoch 3 uses 128.

**Dynamic Re-tokenization:**

The `SequenceLengthCurriculumCallback` class tracks the epoch count. Inside the `on_epoch_begin` method, it checks if a new stage has been reached. When a stage changes, it calls the `tokenize_function` again with the new `max_length`.

    train_tokenized = tokenize_function(train_data, new_len)
    trainer.train_dataset = Dataset.from_dict(...)

This physically replaces the data sitting in the Trainer with a version that has been truncated or padded to the new length.

**Updating the Data Collator:**

    trainer.data_collator = DataCollatorForLanguageModeling(..., pad_to_multiple_of=8)

Whenever the length changes, the data collator is updated to ensure that batches are correctly padded to the new stage's length, maintaining consistency for the GPU kernels.

**When to Use It**

Sequence Length Curriculum is highly beneficial in scenarios where resource efficiency and training stability are paramount:
- Reducing Training Time: By training the majority of the early steps on short sequences, total FLOPS (floating-point operations) are significantly reduced. This can lead to 20%–50% faster total training times.
- Memory-Constrained Hardware: If a dataset contains some extremely long samples that would cause "Out of Memory" (OOM) errors, a curriculum allows the model to learn from the shorter versions first, potentially allowing for larger batch sizes in the early stages.
- Stabilizing Early Training: Large models can sometimes have unstable gradients when starting with very long, complex sequences. Starting small acts as a form of "warm-up" for the attention mechanism.
- Long-Context Fine-tuning: When adapting a model to handle much larger context windows than it was originally trained for (e.g., extending from 2k to 32k), a curriculum is essential to prevent the model from becoming confused by the sudden influx of data.

In [ ]:
import torch
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    Trainer,
    TrainingArguments,
    DataCollatorForLanguageModeling,
    TrainerCallback,
)
from peft import LoraConfig, get_peft_model
from datasets import DatasetDict, Dataset
import gc
import os

In [7]:
# Configuration
MODEL_NAME = "google/gemma-3-270m-it" 
OUTPUT_DIR = "./gemma-3-270m-finetuned-qa-curriculum"
SEQUENCE_STAGES = [64, 96, 128]  # lengths per epoch
LORA_DROPOUT = 0.05
os.makedirs(OUTPUT_DIR, exist_ok=True)

In [8]:
# Tokenizer
print(f"Loading tokenizer: {MODEL_NAME}")
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"
print(f"Tokenizer loaded. Vocab size: {len(tokenizer)}")

# Tokenization Function 
def tokenize_function(examples, max_length):
    texts = [
        f"Question: {q}\n{b}\nAnswer: {a}"
        for q, b, a in zip(
            examples["question_title"],
            examples["question_body"],
            examples["answer"]
        )
    ]
    tokenized = tokenizer(
        texts,
        truncation=True,
        max_length=max_length,
        padding="max_length",
        return_tensors="pt"
    )
    tokenized["labels"] = tokenized["input_ids"].clone()
    tokenized["labels"][tokenized["labels"] == tokenizer.pad_token_id] = -100
    return tokenized

# Load and Tokenize Initial Dataset
print(f"Tokenizing datasets with initial length: {SEQUENCE_STAGES[0]}")
train_tokenized = tokenize_function(train_data, SEQUENCE_STAGES[0])
val_tokenized = tokenize_function(val_data, SEQUENCE_STAGES[0])

dataset_dict = DatasetDict({
    "train": Dataset.from_dict(train_tokenized),
    "validation": Dataset.from_dict(val_tokenized)
})

print(f"Train examples: {len(dataset_dict['train']):,}")
print(f"Validation examples: {len(dataset_dict['validation']):,}")

Loading tokenizer: google/gemma-3-270m-it
Tokenizer loaded. Vocab size: 262145
Tokenizing datasets with initial length: 64
Train examples: 1,331
Validation examples: 285

In [9]:
# Model
print(f"Loading model: {MODEL_NAME}")
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    torch_dtype=torch.bfloat16,  # use bfloat16 instead of float32
    device_map="auto",
    attn_implementation="eager"  # Required for Gemma-3
)

# Apply LoRA
lora_config = LoraConfig(
    task_type="CAUSAL_LM",
    r=8,
    lora_alpha=16,
    lora_dropout=LORA_DROPOUT,
    target_modules=["q_proj", "v_proj", "k_proj", "o_proj"],
)
model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

# Initialize EpochMonitor
monitor = EpochMonitor(model=model)

# Curriculum Callback 
class SequenceLengthCurriculumCallback(TrainerCallback):
    def __init__(self, lengths, trainer_ref=None):
        self.lengths = lengths
        self.trainer_ref = trainer_ref
        self.current_length = lengths[0]

    def on_epoch_begin(self, args, state, control, **kwargs):
        epoch = int(state.epoch) if state.epoch is not None else 0
        if epoch < len(self.lengths) and self.trainer_ref is not None:
            new_len = self.lengths[epoch]
            if new_len != self.current_length:
                self.current_length = new_len
                print(f"\n{'='*60}")
                print(f"Epoch {epoch+1}: Increasing max_length to {new_len}")
                print(f"{'='*60}")

                # Re-tokenize datasets with new length
                train_tokenized = tokenize_function(train_data, new_len)
                val_tokenized = tokenize_function(val_data, new_len)

                self.trainer_ref.train_dataset = Dataset.from_dict({
                    "input_ids": train_tokenized["input_ids"],
                    "attention_mask": train_tokenized["attention_mask"],
                    "labels": train_tokenized["labels"]
                })
                self.trainer_ref.eval_dataset = Dataset.from_dict({
                    "input_ids": val_tokenized["input_ids"],
                    "attention_mask": val_tokenized["attention_mask"],
                    "labels": val_tokenized["labels"]
                })
                print(f" Datasets re-tokenized with max_length={new_len}")
        return control

# Training Argument
# Calculate total steps for warmup
total_steps = len(dataset_dict["train"]) * len(SEQUENCE_STAGES) // (2 * 8)

training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=len(SEQUENCE_STAGES),
    per_device_train_batch_size=2,
    per_device_eval_batch_size=2,
    gradient_accumulation_steps=8,
    learning_rate=1e-4,
    weight_decay=0.01,
    max_grad_norm=1.0,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_steps=20,
    warmup_steps=int(0.1 * total_steps),  # calculate based on total steps
    lr_scheduler_type="cosine",
    bf16=True,                            # use bf16 instead of fp16 for Gemma-3
    optim="adamw_torch",
    gradient_checkpointing=False,         # disable for stability with Gemma-3
    dataloader_num_workers=2,
    ddp_find_unused_parameters=False if torch.cuda.device_count() > 1 else None,
)

# Initialize Curriculum Callback
curriculum_callback = SequenceLengthCurriculumCallback(
    lengths=SEQUENCE_STAGES
)

# Trainer Setup
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=DataCollatorForLanguageModeling(
        tokenizer=tokenizer,
        mlm=False,
    ),
    callbacks=[monitor],
)

# Set trainer reference in curriculum callback
curriculum_callback.trainer_ref = trainer
trainer.add_callback(curriculum_callback)

# Train 
torch.cuda.empty_cache()
gc.collect()

print(f"\n{'='*60}")
print(f"STARTING CURRICULUM LEARNING FINE-TUNING")
print(f"{'='*60}")
print(f"Sequence stages: {SEQUENCE_STAGES}")
print(f"Total epochs: {len(SEQUENCE_STAGES)}")
print(f"{'='*60}\n")

trainer.train()

print("\nSaving model and tokenizer...")
trainer.save_model(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)

print("Curriculum training completed!")

`torch_dtype` is deprecated! Use `dtype` instead!

Loading model: google/gemma-3-270m-it

Loading weights:   0%|          | 0/236 [00:00<?, ?it/s]

trainable params: 737,280 || all params: 268,835,456 || trainable%: 0.2742

============================================================
STARTING CURRICULUM LEARNING FINE-TUNING
============================================================
Sequence stages: [64, 96, 128]
Total epochs: 3
============================================================

Initial Model Memory Footprint:
  Parameters: 268,835,456
  Precision: 2 bytes
  Total Memory: 1.91 GB
    - Parameters: 0.50 GB
    - KV Cache (est): 1.41 GB
  Estimated FLOPs per forward pass (batch=8, seq=512): 2.05 TFLOPS

============================================================
Epoch 0 Summary
============================================================
  Duration (s)         :        73.77
  Tokens Processed     :       86,016
  Throughput (token/s) :         1166
  Training Steps       :           84
  Avg CPU (%)          :         23.8
  Avg Memory (%)       :         12.4
  Total FLOPs          : 43.07 TFLOPS
  TFLOPS (per second)  :         0.58
  FLOPs (per token)    :  0.50 GFLOPS

============================================================
Epoch 2: Increasing max_length to 96
============================================================
 Datasets re-tokenized with max_length=96

============================================================
Epoch 1 Summary
============================================================
  Duration (s)         :        73.71
  Tokens Processed     :       86,016
  Throughput (token/s) :         1167
  Training Steps       :           84
  Avg CPU (%)          :         21.0
  Avg Memory (%)       :         12.6
  Total FLOPs          : 43.07 TFLOPS
  TFLOPS (per second)  :         0.58
  FLOPs (per token)    :  0.50 GFLOPS

============================================================
Epoch 3: Increasing max_length to 128
============================================================
 Datasets re-tokenized with max_length=128

============================================================
Epoch 2 Summary
============================================================
  Duration (s)         :        74.31
  Tokens Processed     :       86,016
  Throughput (token/s) :         1158
  Training Steps       :           84
  Avg CPU (%)          :         21.5
  Avg Memory (%)       :         12.7
  Total FLOPs          : 43.07 TFLOPS
  TFLOPS (per second)  :         0.58
  FLOPs (per token)    :  0.50 GFLOPS

============================================================
TRAINING COMPLETE
============================================================
Total Training Time: 244.89s
Total Epochs: 3
Average Epoch Time: 73.93s
Total Tokens Processed: 258,048
Average Throughput: 1054 tokens/second
Total FLOPs: 129.20 TFLOPS
Average TFLOPS (per second): 0.53
Overall FLOPs (per token): 0.50 GFLOPS

Final Metrics:
Memory Footprint: 1.91 GB
Inference Throughput: 1237 tokens/second
Total Training FLOPs: 43.07 TFLOPS

Saving model and tokenizer...
Curriculum training completed!

**Reference** 
- [Huggingface:LoRA](https://huggingface.co/docs/peft/en/package_reference/lora)
- [Arxiv:Dataset Decomposition: Faster LLM Training with Variable Sequence Length Curriculum](https://arxiv.org/abs/2405.13226)
- [NeurIPS:Dataset Decomposition: Faster LLM Training with Variable Sequence Length Curriculum](https://neurips.cc/virtual/2024/poster/93454)
- [APXML:Introduction to Curriculum Learning](https://apxml.com/courses/how-to-build-a-large-language-model/chapter-9-data-sampling-strategies-training/introduction-curriculum-learning)

### Dynamic Token Pruning (DTP)

Dynamic Token Pruning (DTP) is an optimization strategy that aims to reduce the computational cost of the Attention mechanism—which grows quadratically with sequence length—by identifying and removing "uninformative" tokens during the model's forward pass.

Unlike static pruning, which removes weights or neurons once, DTP is input-dependent. For example, in a long sentence, the model might decide that filler words like "the" or "um" are not essential for predicting the next token in a specific context and can be safely dropped to speed up processing.

**How it Works**

The core mechanism of DTP involves a decision-making component that evaluates token importance in real-time.
- Importance Scoring: A small, auxiliary neural network (often a lightweight MLP) looks at the hidden representations of the tokens and predicts a "score" for each one.
- Selection: The scores are used to rank tokens. The top-k most important tokens are kept, while the rest are discarded.
- Differentiable Masking: During training, a technique like Gumbel-Softmax is often used. This allows the model to "learn" which tokens to prune by backpropagating through the pruning decision, even though the act of dropping a token is technically a non-differentiable step.
- Annealing: To prevent the model from failing early, the "keep ratio" (the percentage of tokens kept) is usually high at the start of training and gradually decreases (anneals) as the model becomes more confident in its pruning decisions.

**Implements Dynamic Token Pruning**

The provided script implements DTP by wrapping the training process in a custom `DTPTrainer` and an auxiliary `prune_head`.

**The Pruning Head:**

    prune_head = nn.Sequential(
    nn.Linear(hidden_dim, hidden_dim // 4),
    nn.GELU(),
    nn.Linear(hidden_dim // 4, 1)
    )

This small MLP acts as the "judge." It takes the high-dimensional hidden state of each token and compresses it into a single scalar value representing that token's importance.

**The Two-Pass Strategy:**

The `compute_loss` function performs two forward passes. The first pass is a "look-ahead" (with `no_grad`) to get the hidden states so the prune_head can decide what to keep. The second pass is the actual training pass, but it only runs on the `new_input_ids`—the subset of tokens selected by torch.topk.

**Differentiable Learning with Gumbel-Softmax:**

    gumbel_noise = -torch.empty_like(importance_logits).exponential_().log()
    noisy_logits = importance_logits + gumbel_noise * self.temperature
    keep_probs = F.softmax(noisy_logits, dim=-1)

During training, the code adds Gumbel noise. This allows the model to explore different pruning patterns and ensures that the importance-scoring MLP can be trained via gradient descent.

**Keep-Ratio Annealing:**

The `KeepRatioSchedulerCallback` ensures that as the global step increases, the `current_keep_ratio` drops from the `initial_keep_ratio` (0.85) toward the `min_keep_ratio` (0.60). This gradually increases the difficulty of the task as the model learns.

**When to Use It**

Dynamic Token Pruning is most effective in specific production and research environments:
- Extreme Throughput Requirements: Use it when serving models in real-time applications where reducing the token count by 30-40% can lead to nearly a 2x speedup in attention-heavy layers.
- Long-Context Summarization: In tasks where the input is very long but the essential information is sparse (e.g., summarizing a 50-page transcript), DTP can help the model focus only on the salient parts.
- Edge AI: When deploying LLMs on devices with limited compute, DTP allows the model to "think faster" by ignoring irrelevant data.
- Reducing "Attention Noise": In some cases, pruning irrelevant tokens acts as a regularizer, preventing the model from over-attending to noise and improving final accuracy.

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    Trainer,
    TrainingArguments,
    DataCollatorForLanguageModeling,
    TrainerCallback,
)
from peft import LoraConfig, get_peft_model
from datasets import DatasetDict, Dataset
import gc

In [10]:
# Configuration
MODEL_NAME = "google/gemma-3-270m-it"
OUTPUT_DIR = "./gemma-3-270m-finetuned-qa-dtp"
INITIAL_KEEP_RATIO = 0.85
MIN_KEEP_RATIO = 0.60
TEMPERATURE = 0.5           # Gumbel-softmax temperature

In [11]:
# Load & Prepare Model (LoRA)
print("Loading base model...")
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    torch_dtype=torch.float32,
    device_map="auto",
    low_cpu_mem_usage=True,
)

lora_config = LoraConfig(
    task_type="CAUSAL_LM",
    r=8,
    lora_alpha=16,
    lora_dropout=0.05,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj", "gate_proj", "up_proj", "down_proj"],
    bias="none",
)
model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

monitor = EpochMonitor(model=model)

# Pruning Head (small MLP)
hidden_dim = model.config.hidden_size
prune_head = nn.Sequential(
    nn.Linear(hidden_dim, hidden_dim // 4),
    nn.GELU(),
    nn.Linear(hidden_dim // 4, 1)
).to(model.device)

# Custom Trainer with Dynamic Pruning
class DTPTrainer(Trainer):
    def __init__(self, prune_head, initial_keep_ratio=0.85, min_keep_ratio=0.60, temperature=0.5, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.prune_head = prune_head
        self.initial_keep_ratio = initial_keep_ratio
        self.min_keep_ratio = min_keep_ratio
        self.temperature = temperature
        self.current_keep_ratio = initial_keep_ratio

    def update_keep_ratio(self, progress):
        self.current_keep_ratio = (
            self.initial_keep_ratio * (1 - progress) +
            self.min_keep_ratio * progress
        )

    def compute_loss(self, model, inputs, return_outputs=False, num_items_in_batch=None):
        input_ids = inputs["input_ids"]
        attention_mask = inputs.get("attention_mask")
        labels = inputs.get("labels")

        # First pass: full sequence to get hidden states 
        with torch.no_grad():
            outputs = model(
                input_ids=input_ids,
                attention_mask=attention_mask,
                output_hidden_states=True,
                use_cache=False
            )
            hidden_states = outputs.hidden_states[-1]  # last layer [B, L, D]

        # Predict per-token importance
        importance_logits = self.prune_head(hidden_states).squeeze(-1)  # [B, L]

        if self.model.training:
            # Gumbel-softmax relaxation
            gumbel_noise = -torch.empty_like(importance_logits).exponential_().log()
            noisy_logits = importance_logits + gumbel_noise * self.temperature
            keep_probs = F.softmax(noisy_logits, dim=-1)
        else:
            keep_probs = torch.sigmoid(importance_logits)

        # Select top-k tokens
        seq_len = input_ids.size(1)
        num_keep = max(4, int(seq_len * self.current_keep_ratio))

        _, top_indices = torch.topk(keep_probs, num_keep, dim=-1, sorted=False)

        # Gather pruned inputs
        batch_size = input_ids.size(0)
        new_input_ids = torch.gather(input_ids, 1, top_indices)
        new_attention_mask = torch.gather(attention_mask, 1, top_indices) if attention_mask is not None else None
        new_labels = torch.gather(labels, 1, top_indices) if labels is not None else None

        # Second pass: pruned sequence
        pruned_outputs = model(
            input_ids=new_input_ids,
            attention_mask=new_attention_mask,
            labels=new_labels,
            use_cache=False
        )

        loss = pruned_outputs.loss

        return (loss, pruned_outputs) if return_outputs else loss

Loading base model...

Loading weights:   0%|          | 0/236 [00:00<?, ?it/s]

trainable params: 1,898,496 || all params: 269,996,672 || trainable%: 0.7032

In [12]:
# Training Arguments 
training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=2,
    per_device_eval_batch_size=2,
    gradient_accumulation_steps=8,
    learning_rate=8e-5,
    weight_decay=0.01,
    max_grad_norm=0.5,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_steps=20,
    warmup_steps=100,
    lr_scheduler_type="cosine",
    fp16=True,
    optim="adamw_torch",
    gradient_checkpointing=True,
    gradient_checkpointing_kwargs={"use_reentrant": False},
    dataloader_num_workers=2,
    dataloader_pin_memory=True,
)

# Trainer Initialization 
trainer = DTPTrainer(
    prune_head=prune_head,
    initial_keep_ratio=INITIAL_KEEP_RATIO,
    min_keep_ratio=MIN_KEEP_RATIO,
    temperature=TEMPERATURE,
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=DataCollatorForLanguageModeling(
        tokenizer=tokenizer,
        mlm=False,
        pad_to_multiple_of=8
    ),
    callbacks = [monitor]
)

# Keep-ratio annealing 
class KeepRatioSchedulerCallback(TrainerCallback):
    def on_step_begin(self, args, state, control, **kwargs):
        if state.max_steps > 0:
            progress = state.global_step / state.max_steps
            trainer.update_keep_ratio(progress)

trainer.add_callback(KeepRatioSchedulerCallback())

print("Starting Dynamic Token Pruning fine-tuning...")
trainer.train()

print("\nSaving PEFT adapter and tokenizer...")
model.save_pretrained(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)

print("DTP training completed!")

Starting Dynamic Token Pruning fine-tuning...
Initial Model Memory Footprint:
  Parameters: 269,996,672
  Precision: 4 bytes
  Total Memory: 3.82 GB
    - Parameters: 1.01 GB
    - KV Cache (est): 2.81 GB
  Estimated FLOPs per forward pass (batch=8, seq=512): 2.05 TFLOPS

============================================================
Epoch 0 Summary
============================================================
  Duration (s)         :       207.91
  Tokens Processed     :       86,016
  Throughput (token/s) :          414
  Training Steps       :           84
  Avg CPU (%)          :         24.3
  Avg Memory (%)       :         14.2
  Total FLOPs          : 43.07 TFLOPS
  TFLOPS (per second)  :         0.21
  FLOPs (per token)    :  0.50 GFLOPS

============================================================
Epoch 1 Summary
============================================================
  Duration (s)         :       204.35
  Tokens Processed     :       86,016
  Throughput (token/s) :          421
  Training Steps       :           84
  Avg CPU (%)          :         22.0
  Avg Memory (%)       :         14.0
  Total FLOPs          : 43.07 TFLOPS
  TFLOPS (per second)  :         0.21
  FLOPs (per token)    :  0.50 GFLOPS

============================================================
Epoch 2 Summary
============================================================
  Duration (s)         :       202.47
  Tokens Processed     :       86,016
  Throughput (token/s) :          425
  Training Steps       :           84
  Avg CPU (%)          :         21.6
  Avg Memory (%)       :         14.0
  Total FLOPs          : 43.07 TFLOPS
  TFLOPS (per second)  :         0.21
  FLOPs (per token)    :  0.50 GFLOPS

============================================================
TRAINING COMPLETE
============================================================
Total Training Time: 660.70s
Total Epochs: 3
Average Epoch Time: 204.91s
Total Tokens Processed: 258,048
Average Throughput: 391 tokens/second
Total FLOPs: 129.20 TFLOPS
Average TFLOPS (per second): 0.20
Overall FLOPs (per token): 0.50 GFLOPS

Final Metrics:
Memory Footprint: 3.82 GB
Inference Throughput: 441 tokens/second
Total Training FLOPs: 43.07 TFLOPS

Saving PEFT adapter and tokenizer...
DTP training completed!

**Reference** 
- [PyTorch: Pruning Tutorial](https://docs.pytorch.org/docs/stable/nn.functional.html)
- [Huggingface:LoRA](https://huggingface.co/docs/peft/en/package_reference/lora)
- [PyTorch: torch.nn.functional](https://docs.pytorch.org/docs/stable/nn.functional.html)
- [Arxiv:DTP: A Simple yet Effective Distracting Token Pruning Framework for Vision-Language Action Models](https://arxiv.org/abs/2601.16065)
- [Arxiv:MADTP: Multimodal Alignment-Guided Dynamic Token Pruning for Accelerating Vision-Language Transformer](https://arxiv.org/abs/2403.02991)
- [ACM:Dynamic token pruning for LLMs: leveraging task-specific attention and adaptive thresholds](https://dl.acm.org/doi/abs/10.1007/s10115-025-02450-1)
- [GitHub:Task-Specific Dynamic Token Pruning (TS-DTP) for LLMs](https://github.com/ahmadpanah/TS-DTP)

# Knowledge Distillation

Knowledge Distillation is a compression technique where a smaller, more efficient "Student" model is trained to mimic the behavior and performance of a larger, pre-trained "Teacher" model. Instead of the Student learning solely from the raw data (hard labels), it learns from the Teacher's "knowledge," which is encoded in its output probabilities and internal representations.

The goal is to transfer the complex reasoning and linguistic capabilities of a massive model (like Llama-3-70B) into a compact model (like Llama-3-8B) that can be deployed on consumer hardware.

**How it Works**

Distillation shifts the training objective from "predict the next word" to "predict exactly what the Teacher would predict."
- Soft Targets: The Teacher provides a probability distribution over the entire vocabulary (e.g., a 10% chance for "cat," 5% for "kitten," 0.1% for "car"). These "soft labels" reveal the Teacher's internal logic and how it relates different concepts—information that is lost in standard training where only the "correct" word is used.
- Feature-Based Distillation: The Student is sometimes forced to match the Teacher’s internal "hidden states" or "attention maps." This encourages the smaller model to process information using the same structural patterns as the larger one.
- The Loss Function: The training process uses a weighted combination of standard Cross-Entropy loss (against the real data) and Distillation Loss (the difference between the Student's and Teacher's outputs).

**Types of Distillation in LLMs**

- Offline Distillation: The Teacher is fixed. You pre-generate millions of responses from the Teacher and then train the Student on that static dataset.
- Online Distillation: Both models are active. The Student generates a response, and the Teacher provides real-time feedback or corrections on that specific output.
- Black-Box Distillation: You don't have access to the Teacher's internal weights (e.g., GPT-4). You only use its text outputs to fine-tune a smaller, open-source model.

**When to Use It**

Knowledge Distillation is the primary choice for creating "small but mighty" models:
- Model Downsizing for Deployment: Use it when you need a model that fits on a smartphone or a single GPU but requires the logical nuance of a model ten times its size.
- Task-Specific Specialization: If you have a massive general-purpose model, you can distill its expertise in a narrow field (like medical coding or legal analysis) into a tiny student model that outperforms larger general models on that specific task.
- Cost Reduction: In high-volume production environments, running a 7B student model is significantly cheaper and faster than running a 70B teacher model.
- Accuracy Boost for Small Models: If you are already planning to fine-tune a small model, adding a distillation objective usually results in higher accuracy than training on the raw data alone.

**Reference** 
- [PyTorch: Knowledge Distillation Tutorial](https://docs.pytorch.org/tutorials/beginner/knowledge_distillation_tutorial.html)
- [Huggingface:Everything You Need to Know about Knowledge Distillation](https://huggingface.co/blog/Kseniase/kd)
- [Arxiv:A Comprehensive Survey on Knowledge Distillation](https://arxiv.org/abs/2503.12067)
- [Arxiv:Distilling the Knowledge in a Neural Network](https://arxiv.org/abs/1503.02531)
- [Wikipedia:Knowledge distillation](https://en.wikipedia.org/wiki/Knowledge_distillation)

## Distillation Techniques:

### Multi-teacher Distillation

Multi-Teacher Distillation is an advanced optimization strategy where a single, compact "Student" model is trained to simultaneously mimic the expertise of multiple "Teacher" models. In Large Language Models (LLMs), this allows the student to benefit from an ensemble of diverse perspectives—for instance, one teacher might be an expert in mathematical reasoning while another excels at creative writing or code generation.

Instead of relying on the biases and limitations of a single reference model, multi-teacher distillation aggregates knowledge, often leading to a student model that is more robust and generalized than any individual teacher used during its training.

**How it Works**

The core of this strategy is the "Consensus" mechanism. The training process ensures the student captures the collective wisdom of the ensemble:
- Ensemble Averaging: For every input token, all teacher models generate their own probability distributions (logits). These distributions are averaged or weighted to create a "mean teacher" signal.
- Knowledge Aggregation: By averaging, the "noise" or specific errors of a single teacher are filtered out. If Teacher A and Teacher B both agree that the next word is likely "Newton," the signal to the student is amplified. If they disagree, the student learns the uncertainty inherent in the concept.
- Temperature Scaling: Like standard distillation, a "Temperature" parameter (T) is used to smooth the teachers' probability distributions. This makes the "soft labels" more informative, revealing the relationships between incorrect but semantically related words.
- Feature Alignment: In some versions, the student also tries to match the average internal hidden representations (embeddings) of all teachers, forcing the student to organize its "mental map" similarly to the larger models.

**Implements Multi-Teacher Distillation**

The provided script implements this using a custom `MultiTeacherDistillationTrainer` that overrides the default loss calculation to incorporate an ensemble signal.

**The Teacher Ensemble:**

    TEACHER_MODELS = ["google/gemma-3-1b-it", "google/gemma-3-4b-it"]

The code loads two larger models into evaluation mode and disables their gradients. These act as the source of truth.

**Logit Aggregation:**

Inside `compute_loss`, the script iterates through the teachers and collects their outputs for the same input sequence.

    avg_teacher_logits = torch.stack(teacher_logits_list).mean(dim=0)

This line is the "Multi-Teacher" core. It stacks the predictions from the 1B and 4B models and calculates the mean, creating a single target distribution for the Student (270M) to follow.

**KL Divergence Loss:**

    distill_loss = F.kl_div(student_log_probs, teacher_probs, reduction="sum")

The code uses Kullback-Leibler (KL) divergence to measure how much the student's predictions differ from the averaged teacher ensemble. The alpha parameter (0.5) balances this "mimicry" loss with the standard Cross-Entropy loss (learning from the actual data).

**Temperature Smoothing:**

Both the student log-probs and teacher probs are divided by `self.temperature` (2.0) before the loss is calculated, which softens the probability spikes and makes the training signal richer.

**When to Use It**

Multi-teacher distillation is a high-performance choice for specific deployment needs:
- Building a Generalist from Specialists: Use it when you have several models that are great at different things (e.g., a Python expert and a Java expert) and want to create one small model that is good at both.
- Mitigating Hallucinations: Large models often hallucinate in different ways. By distilling from multiple teachers, the student is less likely to pick up the idiosyncratic "lies" of a single model and instead learns the "consensus" truth.
- Maximum Performance in Tiny Models: When training very small models (under 1B parameters), the training signal from a single teacher can sometimes be too "narrow." Multiple teachers provide a more diverse set of "soft labels," helping the small student generalize better.
- Domain Adaptation: If you have a general-purpose model and a domain-specific model (like legal or medical), you can distill from both to ensure the student retains general conversational ability while gaining specialized expertise.

**Multi-teacher Distillation**
- Method 1: Logits Averaging Distillation
- Method 2: Weighted Teacher Distillation
- Method 3: Progressive Distillation with Multiple Teachers

In [ ]:
import torch
import torch.nn.functional as F
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    Trainer,
    TrainingArguments,
    DataCollatorForLanguageModeling,
)
from peft import LoraConfig, get_peft_model
from datasets import DatasetDict, Dataset
import gc

In [7]:
# Configuration 
STUDENT_MODEL = "google/gemma-3-270m-it"
TEACHER_MODELS = [
    "google/gemma-3-1b-it",
    #"google/gemma-3-4b-it"      # Not using due to saving computational cost, uncomment to do full fine tuning
]
OUTPUT_DIR = "./gemma-3-270m-multi-teacher-distill"
TEMPERATURE = 2.0
ALPHA = 0.5          # weight for distillation term

# Tokenizer 
tokenizer = AutoTokenizer.from_pretrained(STUDENT_MODEL)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"

def tokenize_examples(data, max_length=MAX_LENGTH):
    texts = [
        f"Question: {row['question_title']}\n{row['question_body']}\nAnswer: {row['answer']}"
        for row in data.iter_rows(named=True)
    ]
    tokenized = tokenizer(
        texts,
        truncation=True,
        max_length=max_length,
        padding="max_length",
        return_tensors="pt"
    )
    tokenized["labels"] = tokenized["input_ids"].clone()
    tokenized["labels"][tokenized["labels"] == tokenizer.pad_token_id] = -100
    return tokenized

# Load Models in fp32 (AMP handles fp16)
print("Loading teacher models...")
teachers = []
for t_name in TEACHER_MODELS:
    teacher = AutoModelForCausalLM.from_pretrained(
        t_name,
        torch_dtype=torch.float32,
        device_map="auto",
        low_cpu_mem_usage=True,
    )
    teacher.eval()
    for param in teacher.parameters():
        param.requires_grad = False
    teachers.append(teacher)

print("Loading student model...")
student = AutoModelForCausalLM.from_pretrained(
    STUDENT_MODEL,
    torch_dtype=torch.float32,
    device_map="auto",
    low_cpu_mem_usage=True,
)

lora_config = LoraConfig(
    r=8,
    lora_alpha=16,
    target_modules=["q_proj", "v_proj", "k_proj", "o_proj"],
    lora_dropout=0.1,
    bias="none",
    task_type="CAUSAL_LM",
)
student = get_peft_model(student, lora_config)
student.print_trainable_parameters()

# Custom Trainer 
class MultiTeacherDistillationTrainer(Trainer):
    def __init__(self, teachers, temperature=2.0, alpha=0.5, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.teachers = teachers
        self.temperature = temperature
        self.alpha = alpha

    def compute_loss(self, model, inputs, return_outputs=False, num_items_in_batch=None):
        # Student forward
        student_outputs = model(
            input_ids=inputs["input_ids"],
            attention_mask=inputs["attention_mask"],
            labels=inputs["labels"]
        )
        student_ce_loss = student_outputs.loss
        student_logits = student_outputs.logits.float()

        # Teachers forward (no grad)
        teacher_logits_list = []
        with torch.no_grad():
            for teacher in self.teachers:
                teacher_out = teacher(
                    input_ids=inputs["input_ids"],
                    attention_mask=inputs["attention_mask"],
                )
                teacher_logits = teacher_out.logits.float()[:, :student_logits.shape[1], :]
                teacher_logits_list.append(teacher_logits)

        avg_teacher_logits = torch.stack(teacher_logits_list).mean(dim=0)

        # Valid mask (only compute distillation on positions where we have labels)
        valid_mask = (inputs["labels"] != -100)
        valid_count = valid_mask.sum().clamp(min=1.0)

        student_valid = student_logits[valid_mask]
        teacher_valid = avg_teacher_logits[valid_mask]

        student_log_probs = F.log_softmax(student_valid / self.temperature, dim=-1)
        student_log_probs = torch.clamp(student_log_probs, min=-100.0)

        teacher_probs = F.softmax(teacher_valid / self.temperature, dim=-1)
        teacher_probs = torch.clamp(teacher_probs, min=1e-8)

        distill_loss = F.kl_div(
            student_log_probs,
            teacher_probs,
            reduction="sum"
        ) / valid_count * (self.temperature ** 2)

        total_loss = (1 - self.alpha) * student_ce_loss + self.alpha * distill_loss

        return (total_loss, student_outputs) if return_outputs else total_loss
    
monitor = EpochMonitor(model=student)

# Training Arguments
training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=1,
    per_device_eval_batch_size=1,
    gradient_accumulation_steps=8,
    gradient_checkpointing=True,
    gradient_checkpointing_kwargs={"use_reentrant": False},
    learning_rate=1e-4,               # lowered slightly for stability
    max_grad_norm=1.0,                # clip gradients
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=1,
    remove_unused_columns=False,
    logging_steps=10,
    logging_first_step=True,
    warmup_steps=50,                  # explicit instead of ratio
    lr_scheduler_type="cosine",
    fp16=True,
    optim="adamw_torch",
    dataloader_num_workers=2,
    ddp_find_unused_parameters=False,
)

# Data 
print("Tokenizing data...")
train_tokenized = tokenize_examples(train_data)
val_tokenized = tokenize_examples(val_data)

dataset_dict = DatasetDict({
    "train": Dataset.from_dict({
        "input_ids": train_tokenized["input_ids"],
        "attention_mask": train_tokenized["attention_mask"],
        "labels": train_tokenized["labels"]
    }),
    "validation": Dataset.from_dict({
        "input_ids": val_tokenized["input_ids"],
        "attention_mask": val_tokenized["attention_mask"],
        "labels": val_tokenized["labels"]
    })
})

print(f"Train examples: {len(dataset_dict['train']):,}")
print(f"Validation examples: {len(dataset_dict['validation']):,}")

# Trainer 
trainer = MultiTeacherDistillationTrainer(
    teachers=teachers,
    temperature=TEMPERATURE,
    alpha=ALPHA,
    model=student,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=DataCollatorForLanguageModeling(
        tokenizer=tokenizer,
        mlm=False,
        pad_to_multiple_of=8
    ),
    callbacks = [monitor]
)

print("Starting multi-teacher distillation training...")
trainer.train()

print("Saving model and tokenizer...")
student.save_pretrained(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)
print(f"Model saved to {OUTPUT_DIR}")

config.json:   0%|          | 0.00/1.35k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/1.16M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/33.4M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/35.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/662 [00:00<?, ?B/s]

chat_template.jinja:   0%|          | 0.00/1.53k [00:00<?, ?B/s]

Loading teacher models...

config.json:   0%|          | 0.00/899 [00:00<?, ?B/s]

`torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors:   0%|          | 0.00/2.00G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/340 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/215 [00:00<?, ?B/s]

Loading student model...

model.safetensors:   0%|          | 0.00/536M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/236 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/173 [00:00<?, ?B/s]

trainable params: 737,280 || all params: 268,835,456 || trainable%: 0.2742
Tokenizing data...
Train examples: 1,331
Validation examples: 285
Starting multi-teacher distillation training...
Initial Model Memory Footprint:
  Parameters: 268,835,456
  Precision: 4 bytes
  Total Memory: 3.81 GB
    - Parameters: 1.00 GB
    - KV Cache (est): 2.81 GB
  Estimated FLOPs per forward pass (batch=8, seq=512): 2.05 TFLOPS

============================================================
Epoch 0 Summary
============================================================
  Duration (s)         :       357.56
  Tokens Processed     :       85,504
  Throughput (token/s) :          239
  Training Steps       :          167
  Avg CPU (%)          :         22.6
  Avg Memory (%)       :         18.2
  Total FLOPs          : 42.81 TFLOPS
  TFLOPS (per second)  :         0.12
  FLOPs (per token)    :  0.50 GFLOPS

============================================================
Epoch 1 Summary
============================================================
  Duration (s)         :       357.73
  Tokens Processed     :       85,504
  Throughput (token/s) :          239
  Training Steps       :          167
  Avg CPU (%)          :         22.6
  Avg Memory (%)       :         18.0
  Total FLOPs          : 42.81 TFLOPS
  TFLOPS (per second)  :         0.12
  FLOPs (per token)    :  0.50 GFLOPS

============================================================
Epoch 2 Summary
============================================================
  Duration (s)         :       357.81
  Tokens Processed     :       85,504
  Throughput (token/s) :          239
  Training Steps       :          167
  Avg CPU (%)          :         22.3
  Avg Memory (%)       :         18.0
  Total FLOPs          : 42.81 TFLOPS
  TFLOPS (per second)  :         0.12
  FLOPs (per token)    :  0.50 GFLOPS

============================================================
TRAINING COMPLETE
============================================================
Total Training Time: 1167.93s
Total Epochs: 3
Average Epoch Time: 357.70s
Total Tokens Processed: 256,512
Average Throughput: 220 tokens/second
Total FLOPs: 128.43 TFLOPS
Average TFLOPS (per second): 0.11
Overall FLOPs (per token): 0.50 GFLOPS

Final Metrics:
Memory Footprint: 3.81 GB
Inference Throughput: 243 tokens/second
Total Training FLOPs: 42.81 TFLOPS
Saving model and tokenizer...
Model saved to ./gemma-3-270m-multi-teacher-distill

**Reference** 
- [Arxiv:Multi-teacher knowledge distillation as an effective method for compressing ensembles of neural networks](https://arxiv.org/abs/2302.07215)
- [Aclanthology:One Teacher is Enough?
Pre-trained Language Model Distillation from Multiple Teachers](https://aclanthology.org/2021.findings-acl.387.pdf)
- [Arxiv:Adaptive Multi-Teacher Multi-level Knowledge Distillation](https://arxiv.org/abs/2103.04062)
- [NeurIPS:Multi-Teacher Distillation: An Ensemble-Then-Distill Approach](https://neurips.cc/virtual/2024/106613)

### Self-Distillation

Self-Distillation is an optimization technique where a single model acts as both the teacher and the student. Instead of needing a massive external model (like GPT-4) to provide guidance, the model learns from its own internal representations or from its previous snapshots during the training process.

In the context of LLMs, this often involves a "moving" target: as the model improves, it uses its more mature version to regularize and refine its current learning, effectively "polishing" its own outputs and stabilizing the training landscape.

**How it Works**

Self-distillation relies on the idea that a model's own "soft" predictions (probability distributions over tokens) contain more nuance than the raw training data (hard labels).
- Dual Roles: During training, two versions of the same architecture exist: the Student (the version currently being updated) and the Teacher (a frozen or slowly updated snapshot of the same model).
- Snapshotting: The Teacher is typically initialized as an exact copy of the Student. Every X steps, the Teacher is updated to match the Student’s latest weights.
- Knowledge Transfer: Both versions process the same input. The Student attempts to minimize two things:
- Standard Loss: Predicting the correct next token in the text.
- Distillation Loss: Matching the probability distribution (logits) produced by the Teacher snapshot.
- Regularization: Because the Teacher represents a "stable" version of the model, this process prevents the Student from overfitting to noise or making wild updates, leading to a flatter loss landscape and better generalization.

**Implements Self-Distillation**

The provided script uses a custom `SelfDistillationTrainer` to manage the relationship between the active model and its snapshot.

**Teacher Initialization:**

    def _init_teacher(self, model):
        teacher = copy.deepcopy(model)
        teacher.eval()
        for param in teacher.parameters():
            param.requires_grad = False
        return teacher

When training starts, the code creates a deep copy of the model, freezes it, and puts it in evaluation mode. This ensures the Teacher provides a stable reference.

**Logit Matching (KL Divergence):**

Inside `compute_loss`, both the active model and the teacher_model run a forward pass. The `F.kl_div` (Kullback-Leibler divergence) measures the difference between their output distributions.

    total_loss = (1 - self.alpha) * student_loss + self.alpha * distillation_loss
    
The alpha (0.5) ensures the model values its own past "wisdom" just as much as the ground-truth data.

**Periodic Updates:**

    if self.state.global_step % self.teacher_update_steps == 0:
        self.teacher_model = self._init_teacher(model)

This is the "Self" part of the distillation. Every 100 steps, the Teacher "catches up" to the Student, providing a fresh, improved target for the next phase of training.

**When to Use It**

Self-distillation is particularly useful when you do not have access to a larger teacher model or want to maximize the potential of a specific architecture:
- Preventing Catastrophic Forgetting: When fine-tuning a model on a new, narrow dataset, self-distillation helps the model retain its original general-purpose capabilities by using its pre-fine-tuned state as the teacher.
- Improving Model Robustness: It acts as a powerful regularizer. If the training data is slightly noisy, the soft targets from the model itself can help smooth out the learning process.
- Small-Scale Budget: Use it when you want the benefits of distillation (faster convergence and higher accuracy) but don't have the VRAM or API budget to run a massive 70B+ parameter model alongside your training.
- Iterative Refinement: It is excellent for "continual learning" scenarios where the model is updated over time with new data and needs to stay consistent with its previous versions.

In [ ]:
import torch
import torch.nn.functional as F
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    Trainer,
    TrainingArguments,
    DataCollatorForLanguageModeling,
)
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training
from datasets import DatasetDict, Dataset
import pandas as pd
import copy

In [9]:
# Configuration
MODEL_NAME = "google/gemma-3-270m"
OUTPUT_DIR = "./gemma-3-270m-self-distilled"
TEMPERATURE = 3.0
ALPHA = 0.5
TEACHER_UPDATE_STEPS = 100

# Load tokenizer
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"

def tokenize_examples(data, max_length=MAX_LENGTH):
    texts = [f"<bos>Question: {row['question_title']}\n{row['question_body']}\nAnswer: {row['answer']}<eos>" 
             for row in data.iter_rows(named=True)]
    tokenized = tokenizer(texts, truncation=True, max_length=max_length, 
                         padding="max_length", return_tensors="pt")
    tokenized["labels"] = tokenized["input_ids"].clone()
    return tokenized

# Load base model without quantization
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    torch_dtype=torch.float16,
    device_map="auto",
    low_cpu_mem_usage=True,
)

# Prepare model for LoRA training
model = prepare_model_for_kbit_training(model)
lora_config = LoraConfig(
    r=8,
    lora_alpha=16,
    target_modules=["q_proj", "v_proj", "k_proj", "o_proj"],
    lora_dropout=0.1,
    bias="none",
    task_type="CAUSAL_LM",
)
model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

class SelfDistillationTrainer(Trainer):
    def __init__(self, temperature=3.0, alpha=0.5, teacher_update_steps=100, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.temperature = temperature
        self.alpha = alpha
        self.teacher_update_steps = teacher_update_steps
        self.teacher_model = None

    def _init_teacher(self, model):
        """Create a frozen copy of the model as teacher"""
        teacher = copy.deepcopy(model)
        teacher.eval()
        for param in teacher.parameters():
            param.requires_grad = False
        return teacher

    def compute_loss(self, model, inputs, return_outputs=False, num_items_in_batch=None):
        if self.teacher_model is None:
            self.teacher_model = self._init_teacher(model)

        # Student forward pass
        student_outputs = model(**inputs)
        student_logits = student_outputs.logits
        student_loss = student_outputs.loss

        # Teacher forward pass (no gradients)
        with torch.no_grad():
            teacher_outputs = self.teacher_model(**inputs)
            teacher_logits = teacher_outputs.logits

        # Align sequence lengths
        min_seq_len = min(student_logits.shape[1], teacher_logits.shape[1])
        student_logits_trunc = student_logits[:, :min_seq_len, :]
        teacher_logits_trunc = teacher_logits[:, :min_seq_len, :]

        # Align vocabulary sizes (teacher and student have same vocab size in self-distillation)
        student_vocab_size = student_logits_trunc.shape[-1]
        teacher_vocab_size = teacher_logits_trunc.shape[-1]

        if teacher_vocab_size > student_vocab_size:
            teacher_logits_aligned = teacher_logits_trunc[:, :, :student_vocab_size]
        elif teacher_vocab_size < student_vocab_size:
            pad_size = student_vocab_size - teacher_vocab_size
            padding = torch.full((teacher_logits_trunc.shape[0], teacher_logits_trunc.shape[1], pad_size), 
                               float('-inf'), device=teacher_logits_trunc.device, dtype=teacher_logits_trunc.dtype)
            teacher_logits_aligned = torch.cat([teacher_logits_trunc, padding], dim=-1)
        else:
            teacher_logits_aligned = teacher_logits_trunc

        # Distillation loss
        distillation_loss = F.kl_div(
            F.log_softmax(student_logits_trunc / self.temperature, dim=-1),
            F.softmax(teacher_logits_aligned / self.temperature, dim=-1),
            reduction="batchmean"
        ) * (self.temperature ** 2)

        # Combined loss
        total_loss = (1 - self.alpha) * student_loss + self.alpha * distillation_loss

        # Update teacher model periodically with EMA-like approach
        if self.state.global_step > 0 and self.state.global_step % self.teacher_update_steps == 0:
            self.teacher_model = self._init_teacher(model)

        return (total_loss, student_outputs) if return_outputs else total_loss

monitor = EpochMonitor(model=model)

training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=1,
    per_device_eval_batch_size=1,
    gradient_accumulation_steps=8,
    gradient_checkpointing=True,
    gradient_checkpointing_kwargs={"use_reentrant": False},
    learning_rate=2e-4,
    weight_decay=0.01,
    eval_strategy="steps",
    eval_steps=100,
    save_strategy="steps",
    save_steps=100,
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=1,
    remove_unused_columns=False,
    logging_steps=10,
    warmup_ratio=0.1,
    lr_scheduler_type="cosine",
    fp16=True,
    optim="adamw_torch",
    dataloader_num_workers=2,
    ddp_find_unused_parameters=False,
)

# Tokenize data
print("Tokenizing training data...")
train_tokenized = tokenize_examples(train_data)
print("Tokenizing validation data...")
val_tokenized = tokenize_examples(val_data)

# Create dataset dictionary
dataset_dict = DatasetDict({
    "train": Dataset.from_dict({k: v for k, v in train_tokenized.items()}),
    "validation": Dataset.from_dict({k: v for k, v in val_tokenized.items()})
})

print(f"Train examples: {len(dataset_dict['train']):,}")
print(f"Validation examples: {len(dataset_dict['validation']):,}")

data_collator = DataCollatorForLanguageModeling(
    tokenizer=tokenizer, 
    mlm=False,
    pad_to_multiple_of=8
)

trainer = SelfDistillationTrainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
    temperature=TEMPERATURE,
    alpha=ALPHA,
    teacher_update_steps=TEACHER_UPDATE_STEPS,
    callbacks = [monitor]
)

torch.cuda.empty_cache()
print("Starting self-distillation training...")
trainer.train()

print("Saving model and tokenizer...")
model.save_pretrained(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)
print(f"Model saved to {OUTPUT_DIR}")

`torch_dtype` is deprecated! Use `dtype` instead!

Loading weights:   0%|          | 0/236 [00:00<?, ?it/s]

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

trainable params: 737,280 || all params: 268,835,456 || trainable%: 0.2742
Tokenizing training data...
Tokenizing validation data...
Train examples: 1,331
Validation examples: 285
Starting self-distillation training...
Initial Model Memory Footprint:
  Parameters: 268,835,456
  Precision: 4 bytes
  Total Memory: 3.81 GB
    - Parameters: 1.00 GB
    - KV Cache (est): 2.81 GB
  Estimated FLOPs per forward pass (batch=8, seq=512): 2.05 TFLOPS

============================================================
Epoch 0 Summary
============================================================
  Duration (s)         :       384.53
  Tokens Processed     :       85,504
  Throughput (token/s) :          222
  Training Steps       :          167
  Avg CPU (%)          :         21.8
  Avg Memory (%)       :         11.4
  Total FLOPs          : 42.81 TFLOPS
  TFLOPS (per second)  :         0.11
  FLOPs (per token)    :  0.50 GFLOPS

============================================================
Epoch 1 Summary
============================================================
  Duration (s)         :       443.72
  Tokens Processed     :       85,504
  Throughput (token/s) :          193
  Training Steps       :          167
  Avg CPU (%)          :         21.7
  Avg Memory (%)       :         11.6
  Total FLOPs          : 42.81 TFLOPS
  TFLOPS (per second)  :         0.10
  FLOPs (per token)    :  0.50 GFLOPS

============================================================
Epoch 2 Summary
============================================================
  Duration (s)         :       442.47
  Tokens Processed     :       85,504
  Throughput (token/s) :          193
  Training Steps       :          167
  Avg CPU (%)          :         21.4
  Avg Memory (%)       :         11.6
  Total FLOPs          : 42.81 TFLOPS
  TFLOPS (per second)  :         0.10
  FLOPs (per token)    :  0.50 GFLOPS

============================================================
TRAINING COMPLETE
============================================================
Total Training Time: 1272.87s
Total Epochs: 3
Average Epoch Time: 423.58s
Total Tokens Processed: 256,512
Average Throughput: 202 tokens/second
Total FLOPs: 128.43 TFLOPS
Average TFLOPS (per second): 0.10
Overall FLOPs (per token): 0.50 GFLOPS

Final Metrics:
Memory Footprint: 3.81 GB
Inference Throughput: 267 tokens/second
Total Training FLOPs: 42.81 TFLOPS
Saving model and tokenizer...
Model saved to ./gemma-3-270m-self-distilled

**Alternative using built-in training without custom trainer**

How the Implementation below Does Self-Distillation

The code provided is a standard fine-tuning script, but it is currently missing the "Distillation" logic. To turn the provided code into a Self-Distillation script, one would need to replace the standard Trainer with a custom class.

Based on the logic of self-distillation, the code should be modified as follows:
- Initialize a Shadow Model: A copy of the model would be created (e.g., `eacher_model = copy.deepcopy(model)`) and set to `.eval()` mode so its weights don't change during a training step.
- Modify the Loss Function: Inside a custom `compute_loss` method, the trainer would run the input through both the student and the teacher.
- Calculate KL-Divergence: Instead of just calculating outputs.loss (Cross-Entropy), the code would calculate the Kullback-Leibler (KL) Divergence between the student's logits and the teacher's logits.
- Combine Losses: The final loss would be something like:$$Loss = (1 - \alpha) \times \text{Cross-Entropy} + \alpha \times \text{KL-Divergence}$$Where $\alpha$ is a value like 0.5 to balance learning from data vs. learning from itself.

In [ ]:
import torch
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    Trainer,
    TrainingArguments,
    DataCollatorForLanguageModeling,
    BitsAndBytesConfig,
)
from peft import LoraConfig, get_peft_model
from datasets import DatasetDict, Dataset

In [ ]:
# Configuration
MODEL_NAME = "google/gemma-3-270m"
OUTPUT_DIR = "./gemma-3-270m-finetuned"

# Load tokenizer
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
tokenizer.pad_token = tokenizer.eos_token

# Tokenization
def tokenize_examples(df, max_length=MAX_LENGTH):
    texts = [
        f"<bos>Question: {row['question_title']}\n{row['question_body']}\nAnswer: {row['answer']}<eos>"
        for row in df.iter_rows(named=True)
    ]
    tokenized = tokenizer(
        texts,
        truncation=True,
        max_length=max_length,
        padding="max_length",
        return_tensors="pt"
    )
    tokenized["labels"] = tokenized["input_ids"].clone()
    return tokenized

train_tokenized = tokenize_examples(train_data)
val_tokenized = tokenize_examples(val_data)

dataset_dict = DatasetDict({
    "train": Dataset.from_dict({
        "input_ids": train_tokenized["input_ids"],
        "attention_mask": train_tokenized["attention_mask"],
        "labels": train_tokenized["labels"]
    }),
    "validation": Dataset.from_dict({
        "input_ids": val_tokenized["input_ids"],
        "attention_mask": val_tokenized["attention_mask"],
        "labels": val_tokenized["labels"]
    })
})

# Quantization config
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float32,
    bnb_4bit_use_double_quant=True,
)

# LoRA config
lora_config = LoraConfig(
    r=8,
    lora_alpha=16,
    target_modules=["q_proj", "v_proj"],
    lora_dropout=0.1,
    bias="none",
    task_type="CAUSAL_LM",
)

# Load and prepare model
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    quantization_config=bnb_config,
    device_map="auto",
    torch_dtype=torch.float32,
)

model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

monitor = EpochMonitor(model=model)

training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=2,
    per_device_eval_batch_size=2,
    gradient_accumulation_steps=4,
    gradient_checkpointing=True,
    learning_rate=1e-4,
    weight_decay=0.01,
    eval_strategy="steps",
    eval_steps=50,
    save_strategy="steps",
    save_steps=100,
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=1,
    remove_unused_columns=False,
    logging_steps=10,
    run_name="gemma-3-270m-finetuned",
    warmup_steps=50,
    lr_scheduler_type="cosine",
    fp16=True,
    optim="paged_adamw_8bit",
    dataloader_pin_memory=False,
    dataloader_num_workers=0,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
    callbacks = [monitor]
)

trainer.train()

model.save_pretrained(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)

**Reference** 
- [Arxiv:Self-Distillation Enables Continual Learning](https://arxiv.org/abs/2601.19897)
- [Arxiv:Revisiting Self-Distillation](https://arxiv.org/abs/2206.08491)
- [Arxiv:Reinforcement Learning via Self-Distillation](https://arxiv.org/abs/2601.20802)
- [Aclanthology:Self-Distillation Bridges Distribution Gap in Language Model Fine-Tuning](https://aclanthology.org/2024.acl-long.58/)
- [PyTorch:torch.nn.functional](https://docs.pytorch.org/docs/stable/nn.functional.html)

### Adaptive Temperature Distillation

Adaptive Temperature is a refinement strategy used in knowledge distillation where the "softness" of the probability distributions is adjusted as training progresses. In standard distillation, a fixed temperature (T) is used to smooth out logits, making it easier for the student to learn from the teacher’s secondary predictions. Adaptive temperature acknowledges that a student needs a broad, soft signal at the beginning of training (high T) to understand general patterns, but a sharper, more precise signal (low T) as it nears convergence to master specific details.

**How it Works**

The temperature parameter controls how much "probability mass" is shared between the correct token and incorrect tokens.
- Early Training (High Temperature): By using a high temperature (e.g., `T=4.0`), the teacher’s output distribution becomes very flat. This reveals the "dark knowledge"—the relationships between incorrect tokens (e.g., why "cat" is more similar to "dog" than to "car"). This helps the student learn the underlying structure of language.
- The Decay Phase: As training continues, the temperature is gradually decreased (often linearly or via a cosine schedule).
- Late Training (Low Temperature): As the temperature approaches 1.0, the distribution becomes sharper. This forces the student to focus on the exact high-confidence predictions of the teacher, refining its accuracy for the final deployment.

**Implements Adaptive Temperature**

The provided script implements this dynamic adjustment within a custom AdaptiveTemperatureDistillationTrainer.

**Linear Decay Logic:**

Inside the `compute_loss` method, the code calculates the training progress and updates the temperature in real-time:

    progress = min(1.0, self.state.global_step / self.state.max_steps)
    self.current_temperature = (
        self.base_temperature * (1 - progress) + self.min_temperature * progress
    )

This ensures that at step 0, the temperature is at `BASE_TEMPERATURE` (4.0), and at the final step, it has reached `MIN_TEMPERATURE` (1.0).

**Softened KL Divergence:**

The calculated `current_temperature` is then applied to both the student and teacher logits before calculating the Kullback-Leibler (KL) divergence:

    student_log_probs = F.log_softmax(student_valid / self.current_temperature, dim=-1)
    teacher_log_probs = F.log_softmax(teacher_valid / self.current_temperature, dim=-1)
The result is multiplied by $T^2$ (a standard mathematical correction in distillation) to ensure the gradient scale remains consistent even as the temperature changes.

**When to Use It**

Adaptive Temperature is highly effective in complex fine-tuning scenarios:
- Bridging Large Gaps: When the teacher is significantly larger than the student (e.g., distilling a 70B model into a 270M model), the student often struggles with the teacher's complexity. A high initial temperature "simplifies" the teacher's knowledge for the student.
- Long Fine-Tuning Runs: For training runs lasting many epochs, a fixed temperature can become a bottleneck. Decaying the temperature allows the model to shift from "exploration" to "exploitation."
- Improving Accuracy on Hard Samples: If the dataset contains many difficult or ambiguous examples, adaptive temperature helps the model learn generalities before being forced to make hard decisions on the ambiguous cases.
- Preventing Gradient Vanishing: High temperatures early on provide smoother gradients, which can lead to more stable training for very small models that might otherwise fall into local minima.

In [ ]:
import torch
import torch.nn.functional as F
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    Trainer,
    TrainingArguments,
    DataCollatorForLanguageModeling,
    TrainerCallback,
)
from peft import LoraConfig, get_peft_model
from datasets import DatasetDict, Dataset
import gc
import os

In [ ]:
# Configuration
STUDENT_MODEL = "google/gemma-3-270m-it"
TEACHER_MODEL = "google/gemma-3-1b-it"
OUTPUT_DIR = "./gemma-3-270m-adaptive-temp-distilled"
BASE_TEMPERATURE = 4.0
MIN_TEMPERATURE = 1.0
ALPHA = 0.7  # weight for distillation term

os.makedirs(OUTPUT_DIR, exist_ok=True)

# Tokenizer 
tokenizer = AutoTokenizer.from_pretrained(STUDENT_MODEL)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"

def tokenize_examples(data, max_length=MAX_LENGTH):
    texts = [
        f"Question: {row['question_title']}\n{row['question_body']}\nAnswer: {row['answer']}"
        for row in data.iter_rows(named=True)
    ]
    tokenized = tokenizer(
        texts,
        truncation=True,
        max_length=max_length,
        padding="max_length",
        return_tensors="pt"
    )
    tokenized["labels"] = tokenized["input_ids"].clone()
    tokenized["labels"][tokenized["labels"] == tokenizer.pad_token_id] = -100
    return tokenized

# Data 
print("Tokenizing data...")
train_tokenized = tokenize_examples(train_data)
val_tokenized = tokenize_examples(val_data)

dataset_dict = DatasetDict({
    "train": Dataset.from_dict(train_tokenized),
    "validation": Dataset.from_dict(val_tokenized)
})

print(f"Train examples: {len(dataset_dict['train']):,}")
print(f"Validation examples: {len(dataset_dict['validation']):,}")

# Load Teacher Model 
print("Loading teacher model...")
teacher = AutoModelForCausalLM.from_pretrained(
    TEACHER_MODEL,
    dtype=torch.bfloat16,  # Use bfloat16 for efficiency
    device_map="auto",
    attn_implementation="eager"
)
teacher.eval()
for param in teacher.parameters():
    param.requires_grad = False

# Load Student Model
print("Loading student model...")
student = AutoModelForCausalLM.from_pretrained(
    STUDENT_MODEL,
    dtype=torch.bfloat16,
    device_map="auto",
    attn_implementation="eager"
)

# Apply LoRA
lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    target_modules=["q_proj", "v_proj", "k_proj", "o_proj"],
    lora_dropout=0.1,
    task_type="CAUSAL_LM"
)
student = get_peft_model(student, lora_config)
student.print_trainable_parameters()

# Adaptive Temperature Trainer 
class AdaptiveTemperatureDistillationTrainer(Trainer):
    def __init__(self, teacher_model, base_temperature=4.0, min_temperature=1.0, alpha=0.7, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.teacher = teacher_model
        self.base_temperature = base_temperature
        self.min_temperature = min_temperature
        self.alpha = alpha
        self.current_temperature = base_temperature

    def compute_loss(self, model, inputs, return_outputs=False, num_items_in_batch=None):
        device = next(model.parameters()).device
        
        # Move inputs to device
        input_ids = inputs["input_ids"].to(device)
        attention_mask = inputs["attention_mask"].to(device)
        labels = inputs["labels"].to(device)

        # Adaptive temperature: linear decay over total training progress
        if self.state.max_steps > 0:
            progress = min(1.0, self.state.global_step / self.state.max_steps)
            self.current_temperature = (
                self.base_temperature * (1 - progress) + self.min_temperature * progress
            )
        elif self.args.num_train_epochs > 0:
            progress = min(1.0, (self.state.epoch or 0) / self.args.num_train_epochs)
            self.current_temperature = (
                self.base_temperature * (1 - progress) + self.min_temperature * progress
            )

        # Student forward pass
        student_outputs = model(
            input_ids=input_ids,
            attention_mask=attention_mask,
            labels=labels,
            use_cache=False
        )
        student_ce_loss = student_outputs.loss
        student_logits = student_outputs.logits.float()

        # Teacher forward pass (no grad)
        with torch.no_grad():
            teacher_device = next(self.teacher.parameters()).device
            teacher_outputs = self.teacher(
                input_ids=input_ids.to(teacher_device),
                attention_mask=attention_mask.to(teacher_device),
                use_cache=False
            )
            teacher_logits = teacher_outputs.logits.float().to(device)

        # Align sequence lengths
        min_seq_len = min(student_logits.shape[1], teacher_logits.shape[1])
        student_logits = student_logits[:, :min_seq_len, :]
        teacher_logits = teacher_logits[:, :min_seq_len, :]
        labels = labels[:, :min_seq_len]

        # Align vocabulary sizes
        min_vocab = min(student_logits.shape[-1], teacher_logits.shape[-1])
        student_logits = student_logits[:, :, :min_vocab]
        teacher_logits = teacher_logits[:, :, :min_vocab]

        # Mask only valid label positions for distillation
        valid_mask = labels != -100
        valid_count = valid_mask.sum().clamp(min=1.0).float()

        student_valid = student_logits[valid_mask]
        teacher_valid = teacher_logits[valid_mask]

        # Adaptive temperature softening - using log_target for numerical stability
        student_log_probs = F.log_softmax(student_valid / self.current_temperature, dim=-1)
        teacher_log_probs = F.log_softmax(teacher_valid / self.current_temperature, dim=-1)

        distill_loss = F.kl_div(
            student_log_probs,
            teacher_log_probs,
            reduction="sum",
            log_target=True
        ) / valid_count * (self.current_temperature ** 2)

        # Combined loss
        total_loss = (1 - self.alpha) * student_ce_loss + self.alpha * distill_loss

        return (total_loss, student_outputs) if return_outputs else total_loss

# Training Arguments
# Calculate total steps for accurate temperature scheduling
total_steps = len(dataset_dict["train"]) * 3 // (1 * 2)  # samples * epochs / (batch_size * grad_accum)

training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=1,
    per_device_eval_batch_size=1,
    gradient_accumulation_steps=2,
    learning_rate=1e-4,
    max_grad_norm=1.0,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_steps=50,
    warmup_steps=int(0.1 * total_steps),
    lr_scheduler_type="cosine",
    bf16=True,  # Use bf16 instead of fp16 for Gemma-3
    optim="adamw_torch",
    gradient_checkpointing=False,  # DISABLED - causes issues with teacher model
    dataloader_num_workers=2,
    ddp_find_unused_parameters=False if torch.cuda.device_count() > 1 else None,
)

# Trainer 
trainer = AdaptiveTemperatureDistillationTrainer(
    teacher_model=teacher,
    base_temperature=BASE_TEMPERATURE,
    min_temperature=MIN_TEMPERATURE,
    alpha=ALPHA,
    model=student,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=DataCollatorForLanguageModeling(
        tokenizer=tokenizer,
        mlm=False
    )
)

# Train
torch.cuda.empty_cache()
gc.collect()

print(f"\n{'='*60}")
print(f"STARTING ADAPTIVE TEMPERATURE DISTILLATION")
print(f"{'='*60}")
print(f"Base temperature: {BASE_TEMPERATURE}")
print(f"Min temperature: {MIN_TEMPERATURE}")
print(f"Alpha (distill weight): {ALPHA}")
print(f"{'='*60}\n")

trainer.train()

print("\nSaving model and tokenizer...")
trainer.save_model(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)

print(f"\n{'='*60}")
print(f"ADAPTIVE TEMPERATURE DISTILLATION COMPLETED!")
print(f"{'='*60}")
print(f"Model saved to: {OUTPUT_DIR}")
print(f"Final temperature: {trainer.current_temperature:.2f}")
print(f"{'='*60}")

# Cleanup
del teacher, student, trainer
torch.cuda.empty_cache()
gc.collect()

config.json:   0%|          | 0.00/1.35k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/1.16M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/33.4M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/35.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/662 [00:00<?, ?B/s]

chat_template.jinja:   0%|          | 0.00/1.53k [00:00<?, ?B/s]

Tokenizing data...
Train examples: 1,331
Validation examples: 285
Loading teacher model...

config.json:   0%|          | 0.00/899 [00:00<?, ?B/s]

model.safetensors:   0%|          | 0.00/2.00G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/340 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/215 [00:00<?, ?B/s]

Loading student model...

model.safetensors:   0%|          | 0.00/536M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/236 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/173 [00:00<?, ?B/s]

trainable params: 1,474,560 || all params: 269,572,736 || trainable%: 0.5470

============================================================
STARTING ADAPTIVE TEMPERATURE DISTILLATION
============================================================
Base temperature: 4.0
Min temperature: 1.0
Alpha (distill weight): 0.7
============================================================

Saving model and tokenizer...

============================================================
ADAPTIVE TEMPERATURE DISTILLATION COMPLETED!
============================================================
Model saved to: ./gemma-3-270m-adaptive-temp-distilled
Final temperature: 1.00
============================================================

15866

**Reference** 
- [Arxiv:Adaptive Temperature Based on Logits Correlation in Knowledge Distillation](https://arxiv.org/abs/2503.09030)
- [Sciencedirect:Adaptive Temperature Distillation method for mining hard samples’ knowledge](https://www.sciencedirect.com/science/article/abs/pii/S0925231225004175)
- [ACM:Adaptive Temperature Distillation method for mining hard samples’ knowledge](https://dl.acm.org/doi/10.1016/j.neucom.2025.129745)
- [ACM:ATMKD: adaptive temperature guided multi-teacher knowledge distillation](https://dl.acm.org/doi/abs/10.1007/s00530-024-01483-w)

## Feature Alignment

### Attention Map Transfer (Intermediate Distillation)

Attention Map Transfer (or Distillation) is an optimization technique where a student model is forced to mimic the internal "focus" or relational patterns of a teacher model. While standard distillation focuses on matching the final output (logits), attention distillation looks inside the "brain" of the teacher to see which tokens it prioritizes when processing a sentence.

By aligning these attention maps, the student learns not just what the right answer is, but why specific words are important in reaching that conclusion. This helps small models inherit the sophisticated structural reasoning of larger models.

**How it Works**

In a Transformer, the attention mechanism calculates a matrix (an "attention map") where each value represents how much one token "attends" to another.
- Extraction: During a training forward pass, you extract the attention matrices from both the teacher and student models.
- Mapping: Since students usually have fewer layers and heads than teachers, you select specific layers to align (e.g., the last 4 layers of the student might mimic the last 4 of the teacher).
- Pattern Matching: You calculate a distance metric—typically Mean Squared Error (MSE)—between the teacher’s attention map and the student’s.
- Structural Guidance: The student is penalized if its attention weights differ significantly from the teacher’s. This forces the student to "look" at the same context clues that the larger model used.

**Implements Attention Distillation**

The provided `AttentionDistillationTrainer` script operationalizes this through three key steps:

**Extraction (`output_attentions=True`):**

The trainer explicitly requests the internal attention matrices by setting this flag in the forward pass for both models.

    s_out = model(..., output_attentions=True)
    t_out = self.teacher(..., output_attentions=True)

**Aggregation and Alignment:**

Because teacher models often have more heads, the code averages the attention maps across all heads to create a unified "importance" map for each layer. It then selects the last `min_layers` to compare.

    s_attn = s_attn_stack.mean(dim=0).mean(dim=1) # Average across heads
    t_attn = t_attn_stack.mean(dim=0).mean(dim=1)

**The Attention Loss (MSE):**

The code uses `F.mse_loss` to calculate the difference between these averaged maps. Crucially, it uses an attn_mask to ensure the model isn't penalized for how it handles padding tokens.

    a_mse = F.mse_loss(s_attn[attn_mask], t_attn[attn_mask])

This `a_mse` (weighted by BETA) is added to the total loss, directing the student's internal focus.

**When to Use It**

Attention Map Transfer is highly beneficial in the following scenarios:
- Complex Reasoning Tasks: Use it for tasks like coding, math, or logical deduction where the "relationship" between distant words is more important than just identifying the next word.
- Massive Model Compression: When distilling a very large teacher (e.g., 70B) into a tiny student (e.g., 270M), the student needs more than just logits; it needs structural hints to bridge the massive capacity gap.
- Low-Data Regimes: If you have a small dataset, attention maps act as a powerful "inductive bias," helping the student converge faster by showing it the "correct" way to process language.
- Interpretability Requirements: If you want your small model to be as interpretable as your large model (e.g., highlighting relevant keywords in a legal or medical context), forcing it to share the teacher's attention patterns is essential.

In [ ]:
import torch
import torch.nn.functional as F
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    Trainer,
    TrainingArguments,
    DataCollatorForLanguageModeling,
)
from peft import LoraConfig, get_peft_model
from datasets import DatasetDict, Dataset
import gc

In [10]:
# Configuration 
STUDENT_MODEL = "google/gemma-3-270m-it"
TEACHER_MODEL = "google/gemma-3-1b-it"
OUTPUT_DIR = "./gemma-3-270m-attention-distilled"
ALPHA = 0.5
BETA = 0.3
LOGIT_TEMP = 2.0
WARMUP_STEPS = 50

# Tokenizer
tokenizer = AutoTokenizer.from_pretrained(STUDENT_MODEL)
tokenizer.pad_token = tokenizer.eos_token

def tokenize_examples(data):
    texts = [
        f"Question: {row['question_title']}\nAnswer: {row['answer']}"
        for row in data.iter_rows(named=True)
    ]
    tokenized = tokenizer(
        texts,
        truncation=True,
        max_length=MAX_LENGTH,
        padding="max_length",
        return_tensors="pt"
    )
    tokenized["labels"] = tokenized["input_ids"].clone()
    tokenized["labels"][tokenized["labels"] == tokenizer.pad_token_id] = -100
    return tokenized

# Load Models
print("Loading teacher model...")
teacher = AutoModelForCausalLM.from_pretrained(
    TEACHER_MODEL,
    torch_dtype=torch.float32,
    device_map="auto",
    attn_implementation="eager",
    low_cpu_mem_usage=True,
)
teacher.eval()
for param in teacher.parameters():
    param.requires_grad = False

print("Loading student model...")
student = AutoModelForCausalLM.from_pretrained(
    STUDENT_MODEL,
    torch_dtype=torch.float32,
    device_map="auto",
    attn_implementation="eager",
    low_cpu_mem_usage=True,
)

lora_config = LoraConfig(
    r=8,
    lora_alpha=16,
    target_modules=["q_proj", "v_proj"],
    task_type="CAUSAL_LM",
)
student = get_peft_model(student, lora_config)
student.print_trainable_parameters()

monitor = EpochMonitor(model=student)

# Custom Trainer
class AttentionDistillationTrainer(Trainer):
    def __init__(self, teacher_model, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.teacher = teacher_model

    def compute_loss(self, model, inputs, return_outputs=False, num_items_in_batch=None):
        # Student forward
        s_out = model(
            input_ids=inputs["input_ids"],
            attention_mask=inputs["attention_mask"],
            labels=inputs["labels"],
            output_attentions=True
        )
        s_loss = s_out.loss
        s_logits = s_out.logits
        s_attentions = s_out.attentions

        # Teacher forward
        with torch.no_grad():
            t_out = self.teacher(
                input_ids=inputs["input_ids"],
                attention_mask=inputs["attention_mask"],
                output_attentions=True
            )
            t_logits = t_out.logits[:, :s_logits.shape[1], :]
            t_attentions = t_out.attentions

        # Logit KL (only on valid tokens)
        valid_mask = inputs["labels"] != -100
        valid_count = valid_mask.sum().clamp(min=1)
        s_valid = s_logits.view(-1, s_logits.shape[-1])[valid_mask.view(-1)]
        t_valid = t_logits.view(-1, t_logits.shape[-1])[valid_mask.view(-1)]
        l_kl = F.kl_div(
            F.log_softmax(s_valid / LOGIT_TEMP, dim=-1),
            F.softmax(t_valid / LOGIT_TEMP, dim=-1),
            reduction="sum"
        ) / valid_count * (LOGIT_TEMP ** 2)

        # Attention MSE (head-averaged, last min_layers)
        min_layers = min(len(s_attentions), len(t_attentions))
        s_attn_stack = torch.stack(s_attentions[-min_layers:])
        t_attn_stack = torch.stack(t_attentions[-min_layers:])
        s_attn = s_attn_stack.mean(dim=0).mean(dim=1)  # [batch, seq, seq]
        t_attn = t_attn_stack.mean(dim=0).mean(dim=1)

        # Mask padded positions
        attn_mask = (
            inputs["attention_mask"].unsqueeze(1) *
            inputs["attention_mask"].unsqueeze(2)
        ).bool()
        if attn_mask.sum() > 0:
            a_mse = F.mse_loss(s_attn[attn_mask], t_attn[attn_mask])
        else:
            a_mse = torch.tensor(0.0, device=s_attn.device)

        # Combined loss
        total_loss = (1 - ALPHA - BETA) * s_loss + ALPHA * l_kl + BETA * a_mse

        return (total_loss, s_out) if return_outputs else total_loss

# Data 
print("Tokenizing data...")
train_tokenized = tokenize_examples(train_data)
val_tokenized = tokenize_examples(val_data)

dataset_dict = DatasetDict({
    "train": Dataset.from_dict(train_tokenized),
    "validation": Dataset.from_dict(val_tokenized)
})

print(f"Train examples: {len(dataset_dict['train']):,}")
print(f"Validation examples: {len(dataset_dict['validation']):,}")

# Training Arguments
training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=2,
    per_device_eval_batch_size=2,
    gradient_accumulation_steps=4,
    gradient_checkpointing=True,
    gradient_checkpointing_kwargs={"use_reentrant": False},
    learning_rate=1e-4,
    max_grad_norm=1.0,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=1,
    remove_unused_columns=False,
    logging_steps=10,
    warmup_steps=WARMUP_STEPS,
    lr_scheduler_type="cosine",
    fp16=True,
    optim="adamw_torch",
    dataloader_num_workers=2,
    ddp_find_unused_parameters=False,
)

# Trainer
trainer = AttentionDistillationTrainer(
    teacher_model=teacher,
    model=student,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=DataCollatorForLanguageModeling(
        tokenizer=tokenizer,
        mlm=False,
        pad_to_multiple_of=8
    ),
    callbacks = [monitor]
)

torch.cuda.empty_cache()
gc.collect()

print("Starting Attention Map Distillation...")
trainer.train()

print("Saving model...")
trainer.save_model(OUTPUT_DIR)

print("Training completed.")

Loading teacher model...

Loading weights:   0%|          | 0/340 [00:00<?, ?it/s]

Loading student model...

Loading weights:   0%|          | 0/236 [00:00<?, ?it/s]

trainable params: 368,640 || all params: 268,466,816 || trainable%: 0.1373
Tokenizing data...
Train examples: 1,331
Validation examples: 285
Starting Attention Map Distillation...
Initial Model Memory Footprint:
  Parameters: 268,466,816
  Precision: 4 bytes
  Total Memory: 3.81 GB
    - Parameters: 1.00 GB
    - KV Cache (est): 2.81 GB
  Estimated FLOPs per forward pass (batch=8, seq=512): 2.05 TFLOPS

============================================================
Epoch 0 Summary
============================================================
  Duration (s)         :       192.99
  Tokens Processed     :      171,008
  Throughput (token/s) :          886
  Training Steps       :          167
  Avg CPU (%)          :         23.1
  Avg Memory (%)       :         18.2
  Total FLOPs          : 85.62 TFLOPS
  TFLOPS (per second)  :         0.44
  FLOPs (per token)    :  0.50 GFLOPS

============================================================
Epoch 1 Summary
============================================================
  Duration (s)         :       192.41
  Tokens Processed     :      171,008
  Throughput (token/s) :          889
  Training Steps       :          167
  Avg CPU (%)          :         21.6
  Avg Memory (%)       :         18.1
  Total FLOPs          : 85.62 TFLOPS
  TFLOPS (per second)  :         0.44
  FLOPs (per token)    :  0.50 GFLOPS

============================================================
Epoch 2 Summary
============================================================
  Duration (s)         :       192.28
  Tokens Processed     :      171,008
  Throughput (token/s) :          889
  Training Steps       :          167
  Avg CPU (%)          :         22.4
  Avg Memory (%)       :         18.1
  Total FLOPs          : 85.62 TFLOPS
  TFLOPS (per second)  :         0.45
  FLOPs (per token)    :  0.50 GFLOPS

============================================================
TRAINING COMPLETE
============================================================
Total Training Time: 642.00s
Total Epochs: 3
Average Epoch Time: 192.56s
Total Tokens Processed: 513,024
Average Throughput: 799 tokens/second
Total FLOPs: 256.87 TFLOPS
Average TFLOPS (per second): 0.40
Overall FLOPs (per token): 0.50 GFLOPS

Final Metrics:
Memory Footprint: 3.81 GB
Inference Throughput: 905 tokens/second
Total Training FLOPs: 85.62 TFLOPS
Saving model...
Training completed.

**Reference** 
- [Arxiv:Class Attention Transfer Based Knowledge Distillation](https://arxiv.org/abs/2304.12777)
- [Aclanthology:Align-to-Distill: Trainable Attention Alignment for
Knowledge Distillation in Neural Machine Translation](https://aclanthology.org/2024.lrec-main.64.pdf)
- [ACM:Hierarchical Multi-Attention Transfer for Knowledge Distillation](https://dl.acm.org/doi/10.1145/3568679)

### Hidden State Projection

Hidden State Projection (also known as Feature Alignment) is an optimization technique where a student model is trained to match the internal representations (hidden states) of a larger teacher model. While standard distillation focuses on the final output probabilities, this method forces the student to learn the intermediate "concepts" and feature structures that the teacher uses at various layers of its architecture.

Because student models usually have smaller internal dimensions than their teachers (e.g., a 270M student might have a hidden size of 1024, while a 1B teacher has 2048), a Projection Layer is used to bridge the gap, mathematically translating the student's space into the teacher's space.

**How it Works**

Hidden State Projection ensures the student model processes information using a similar internal logic to the teacher.
- Intermediate Capture: During a forward pass, the hidden states (vectors) are captured from specific layers of both the teacher and student.
- Dimensional Alignment: Since the student’s vectors are "narrower" than the teacher’s, a trainable linear transformation (the projection) is applied to the student's output. This essentially "stretches" the student's representation to match the teacher's width.
- Feature Matching: A distance metric, typically Mean Squared Error (MSE), is calculated between the projected student states and the actual teacher states.
- Deep Supervision: By backpropagating this loss, the student is forced to organize its internal features in a way that mimics the teacher, providing a much richer training signal than just looking at the final word prediction.

**Implements Hidden State Projection**

The script uses a custom `FeatureAlignmentDistillationTrainer` to manage the dimensionality mismatch and the alignment loss.

**The Projection Layer (`nn.Linear`):**

The trainer dynamically creates a linear layer that transforms the student's hidden dimension to match the teacher's.

    self.projection = nn.Linear(student_dim, teacher_dim, bias=False)

This layer is a trainable "bridge." It allows the student to keep its small size while still being compared directly to the larger teacher.

**Capturing Hidden States:**

The trainer sets `output_hidden_states=True` during the forward pass of both models. It then slices the last few layers to align.

    s_layers = student_hidden_states[-NUM_LAYERS_TO_ALIGN:]
    t_layers = teacher_hidden_states[-NUM_LAYERS_TO_ALIGN:]

**The MSE Alignment Loss:**

Inside the layer loop, the student's features are projected and compared to the teacher's.

    projected = proj(s_hidden)
    diff = (projected - t_hidden) ** 2 # Mean Squared Error

The `valid_mask` ensures the model doesn't waste effort trying to align padding tokens, focusing only on the actual text content.

**Alpha Weighting:**

The final loss combines the standard Cross-Entropy (CE) with the feature-matching loss.

    total_loss = (1 - self.alpha) * student_ce_loss + self.alpha * feature_loss

**When to Use It**

Hidden State Projection is a powerful tool for deep model compression:
- Extreme Compression Ratios: When the student is significantly smaller (e.g., 10x smaller) than the teacher, it needs deep guidance. Aligning hidden states provides a roadmap for how the small model should structure its "thoughts."
- Transferring "Reasoning" Styles: If a teacher model is particularly good at a specific style of logic (like step-by-step math), projecting its hidden states helps the student adopt the same internal processing flow.
- Faster Convergence: Because the student is being supervised at every layer (rather than just the output), it often learns much faster and reaches a higher accuracy plateau than with standard fine-tuning.
- Domain Specialization: When teaching a general model to handle specialized data (like medical or legal text), feature alignment helps the student learn the specific "vocabulary of features" the teacher has developed for that domain.

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    Trainer,
    TrainingArguments,
    DataCollatorForLanguageModeling,
)
from peft import LoraConfig, get_peft_model
from datasets import DatasetDict, Dataset
import gc

In [5]:
# Configuration 
STUDENT_MODEL = "google/gemma-3-270m-it"
TEACHER_MODEL = "google/gemma-3-1b-it"
OUTPUT_DIR = "./gemma-3-270m-feature-aligned-distilled"
ALPHA = 0.5                # weight for feature alignment loss
FEATURE_ALPHA = 1.0        # weight for MSE inside feature loss
NUM_LAYERS_TO_ALIGN = 4    # how many layers to align (last N)

# Tokenizer 
tokenizer = AutoTokenizer.from_pretrained(STUDENT_MODEL)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"

def tokenize_examples(data, max_length=MAX_LENGTH):
    texts = [
        f"Question: {row['question_title']}\n{row['question_body']}\nAnswer: {row['answer']}"
        for row in data.iter_rows(named=True)
    ]
    tokenized = tokenizer(
        texts,
        truncation=True,
        max_length=max_length,
        padding="max_length",
        return_tensors="pt"
    )
    tokenized["labels"] = tokenized["input_ids"].clone()
    tokenized["labels"][tokenized["labels"] == tokenizer.pad_token_id] = -100
    return tokenized

# Load Models in fp32
print("Loading teacher model...")
teacher = AutoModelForCausalLM.from_pretrained(
    TEACHER_MODEL,
    torch_dtype=torch.float32,
    device_map="auto",
    low_cpu_mem_usage=True,
)
teacher.eval()
for param in teacher.parameters():
    param.requires_grad = False

print("Loading student model...")
student = AutoModelForCausalLM.from_pretrained(
    STUDENT_MODEL,
    torch_dtype=torch.float32,
    device_map="auto",
    low_cpu_mem_usage=True,
)

lora_config = LoraConfig(
    r=8,
    lora_alpha=16,
    target_modules=["q_proj", "v_proj"],
    lora_dropout=0.1,
    bias="none",
    task_type="CAUSAL_LM"
)
student = get_peft_model(student, lora_config)
student.print_trainable_parameters()

# Trainer with Hidden State Projection
class FeatureAlignmentDistillationTrainer(Trainer):
    def __init__(self, teacher_model, alpha=0.5, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.teacher = teacher_model
        self.alpha = alpha
        self.projection = None

    def _get_projection(self, student_dim, teacher_dim, device, dtype):
        if self.projection is None or self.projection.in_features != student_dim:
            self.projection = nn.Linear(student_dim, teacher_dim, bias=False)
            self.projection.to(device=device, dtype=dtype)
            print(f"Projection layer created: {student_dim} -> {teacher_dim}")
        return self.projection

    def compute_loss(self, model, inputs, return_outputs=False, num_items_in_batch=None):
        device = inputs["input_ids"].device

        # Student forward with hidden states
        student_outputs = model(
            input_ids=inputs["input_ids"],
            attention_mask=inputs["attention_mask"],
            labels=inputs["labels"],
            output_hidden_states=True
        )
        student_ce_loss = student_outputs.loss
        student_hidden_states = student_outputs.hidden_states  # tuple

        # Teacher forward (no grad)
        with torch.no_grad():
            teacher_outputs = self.teacher(
                input_ids=inputs["input_ids"],
                attention_mask=inputs["attention_mask"],
                output_hidden_states=True
            )
            teacher_hidden_states = teacher_outputs.hidden_states

        # Feature alignment loss
        feature_loss = torch.tensor(0.0, device=device, dtype=torch.float32)
        num_aligned = 0

        # Align last N layers
        s_layers = student_hidden_states[-NUM_LAYERS_TO_ALIGN:]
        t_layers = teacher_hidden_states[-NUM_LAYERS_TO_ALIGN:]

        for s_hidden, t_hidden in zip(s_layers, t_layers):
            # Get dimensions
            s_dim = s_hidden.shape[-1]
            t_dim = t_hidden.shape[-1]

            # Initialize projection if needed
            proj = self._get_projection(s_dim, t_dim, device, s_hidden.dtype)

            # Truncate sequence length to min
            seq_len = min(s_hidden.shape[1], t_hidden.shape[1])
            s_hidden = s_hidden[:, :seq_len, :]
            t_hidden = t_hidden[:, :seq_len, :]

            # Mask for valid positions (non-padding)
            valid_mask = inputs["attention_mask"][:, :seq_len].bool()
            valid_mask = valid_mask.unsqueeze(-1).expand(-1, -1, t_dim)

            # Project student hidden states
            projected = proj(s_hidden)

            # Compute MSE only on valid positions
            diff = (projected - t_hidden) ** 2
            masked_diff = diff * valid_mask.float()
            layer_loss = masked_diff.sum() / valid_mask.sum().clamp(min=1.0)
            feature_loss += layer_loss
            num_aligned += 1

        if num_aligned > 0:
            feature_loss = feature_loss / num_aligned

        # Combined loss
        total_loss = (1 - self.alpha) * student_ce_loss + self.alpha * feature_loss

        return (total_loss, student_outputs) if return_outputs else total_loss

# Training Arguments 
training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=2,
    per_device_eval_batch_size=2,
    gradient_accumulation_steps=4,
    gradient_checkpointing=True,
    gradient_checkpointing_kwargs={"use_reentrant": False},
    learning_rate=1e-4,
    max_grad_norm=1.0,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_steps=50,
    warmup_steps=100,
    lr_scheduler_type="cosine",
    fp16=False,  # Disabled to avoid dtype issues with projection
    optim="adamw_torch",
    dataloader_num_workers=2,
    dataloader_pin_memory=False,
)

# Data 
print("Tokenizing data...")
train_tokenized = tokenize_examples(train_data)
val_tokenized = tokenize_examples(val_data)

dataset_dict = DatasetDict({
    "train": Dataset.from_dict({
        "input_ids": train_tokenized["input_ids"],
        "attention_mask": train_tokenized["attention_mask"],
        "labels": train_tokenized["labels"]
    }),
    "validation": Dataset.from_dict({
        "input_ids": val_tokenized["input_ids"],
        "attention_mask": val_tokenized["attention_mask"],
        "labels": val_tokenized["labels"]
    })
})

print(f"Train examples: {len(dataset_dict['train']):,}")
print(f"Validation examples: {len(dataset_dict['validation']):,}")

# Trainer 
trainer = FeatureAlignmentDistillationTrainer(
    teacher_model=teacher,
    alpha=ALPHA,
    model=student,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=DataCollatorForLanguageModeling(
        tokenizer=tokenizer,
        mlm=False
    ),
)

print("Starting Feature Alignment Distillation...")
trainer.train()

# Save everything
print("Saving model, tokenizer and projection layer...")
trainer.save_model(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)

# Save projection layer
if hasattr(trainer, 'projection') and trainer.projection is not None:
    torch.save(trainer.projection.state_dict(), f"{OUTPUT_DIR}/projection_layer.pt")
    print("Projection layer saved.")

print("Feature Alignment Distillation completed!")
print(f"Models and projection saved to: {OUTPUT_DIR}")

`torch_dtype` is deprecated! Use `dtype` instead!

Loading teacher model...

Loading weights:   0%|          | 0/340 [00:00<?, ?it/s]

Loading student model...

Loading weights:   0%|          | 0/236 [00:00<?, ?it/s]

trainable params: 368,640 || all params: 268,466,816 || trainable%: 0.1373
Tokenizing data...
Train examples: 1,331
Validation examples: 285
Starting Feature Alignment Distillation...
Projection layer created: 640 -> 1152

Saving model, tokenizer and projection layer...
Projection layer saved.
Feature Alignment Distillation completed!
Models and projection saved to: ./gemma-3-270m-feature-aligned-distilled

**Reference** 
- [Arxiv:Reliable Unlearning Harmful Information in LLMs with Metamorphosis Representation Projection](https://arxiv.org/html/2508.15449v1)
- [Aaclanthology:Are the Hidden States Hiding Something? Testing the Limits of
Factuality-Encoding Capabilities in LLMs](https://aclanthology.org/2025.acl-long.304.pdf)
- [OpenReview:Leveraging LLM Hidden-State Trajectories for Label-Free Sampler Adaptation](https://openreview.net/forum?id=kJiB24fTmw)
- [OpenReview:The Hidden Dimensions of LLM Alignment: A Multi-Dimensional Analysis of Orthogonal Safety Directions](https://openreview.net/forum?id=wGFEzfhFae)
- [Medrxiv:Probing Hidden States for Calibrated, Alignment-Resistant Predictions in LLMs](https://www.medrxiv.org/content/10.1101/2025.09.17.25336018v2.full)

# ARCHITECTURAL OPTIMIZATIONS

## Efficient Attention Mechanisms

Efficient Attention Mechanisms are architectural and hardware-level optimizations designed to overcome the "Quadratic Bottleneck" of standard Transformers. In traditional models, every token must look at every other token, meaning that doubling the input length quadruples the memory and compute requirements—a complexity of $O(L^2)$.

Efficient attention reduces this cost to $O(L)$ or $O(L \log L)$, enabling models to process massive documents, maintain long conversation histories, and run faster on limited hardware. Efficient attention generally falls into three primary categories:

**1. Sparse Attention**

Instead of a "dense" matrix where every token attends to everything, the model uses a "sparse" pattern to limit connections.
- Sliding Window: Tokens only attend to a local neighborhood of nearby tokens.
- Global Tokens: A few specific tokens (like the "CLS" or "BOS" token) are allowed to look at the entire sequence to act as information anchors.
- Dilated/Strided Attention: Tokens attend to others at fixed intervals (e.g., every 2nd or 4th token), increasing the receptive field without increasing the number of calculations.

**2. Low-Rank and Linear Attention**

These methods use mathematical approximations to avoid calculating the $L \times L$ attention matrix entirely. By changing the order of operations—calculating the relationship between Keys and Values before multiplying by the Queries—the complexity drops from quadratic to linear. This effectively treats the attention mechanism as a fixed-size memory buffer that doesn't grow with sequence length.

**3. Hardware-Aware Optimizations (FlashAttention)**

`FlashAttention` is currently the most popular optimization for deployment. It does not change the underlying math of attention; instead, it changes how the GPU handles the data. It uses "tiling" to calculate attention in small blocks that fit into the GPU's fastest memory (SRAM), drastically reducing the time spent moving data to and from the slower main VRAM.

**When to Use It**

- Massive Context Windows: If a task requires reading entire books, multi-hour meeting transcripts, or large codebases (context over 8,000 tokens), efficient attention is mandatory to avoid "Out of Memory" errors.
- High-Throughput Production: For deployment, optimizations like FlashAttention-2 allow a single GPU to serve significantly more users per second by reducing the time spent on the attention bottleneck.
- On-Device AI: When running models on laptops or mobile phones, linear or sparse attention reduces the memory footprint, making it possible to run larger models than the hardware would normally allow.
- Long-Term Memory: In agentic workflows where a model needs to remember a long history of past actions, efficient attention keeps the "memory" fast and manageable.

**Reference** 
- [Arxiv:Efficient Attention Mechanisms for Large Language Models: A Survey](https://arxiv.org/abs/2507.19595)
- [Arxiv: AttentionEngine: A Versatile Framework for Efficient Attention Mechanisms on Diverse Hardware Platforms](https://arxiv.org/abs/2502.15349)

### Multi-Query Attention (MQA)

Hidden State Projection is an optimization technique used primarily in Knowledge Distillation to align the internal representations of a student model with those of a teacher model. Since LLMs of different sizes have different internal "widths" (hidden dimensions), they cannot be compared directly. Hidden state projection uses a trainable mathematical bridge—a linear transformation—to map the student's smaller vector space into the teacher's larger vector space.

This allows the student to learn not just the final answer, but the internal "reasoning" and feature structures the teacher uses at every layer.

**How it Works**

The core goal is to minimize the distance between what the student is "thinking" and what the teacher is "thinking" at intermediate stages.
- Intermediate Extraction: During training, the hidden states (vectors) are pulled from a specific layer of the student and the corresponding layer of the teacher.
- Projection: Because the student’s hidden dimension (e.g., 1024) is smaller than the teacher’s (e.g., 4096), a linear layer is applied to the student's vector. This "projects" the 1024-dimensional vector into a 4096-dimensional space.
- Loss Calculation: A distance metric, usually Mean Squared Error (MSE), measures how far the student's projected "thought" is from the teacher's actual "thought."
- Optimization: The student model and the projection layer are trained simultaneously. The student learns to create representations that, when transformed, perfectly match the teacher's sophisticated internal features.

**Hidden State Projection**

The code provided is actually a script for Multi-Query Attention (MQA) Conversion, not Hidden State Projection. It focuses on modifying the attention mechanism to save memory during inference. However, if Hidden State Projection were implemented in a similar script, it would look like this:
- The Projection Layer: A module like `nn.Linear(student_hidden_size, teacher_hidden_size)` would be initialized.
- The Forward Pass: Both the student and teacher would run the same text through their layers. The trainer would collect the hidden_states from both.
- The Weight Transfer Logic: Much like how the provided code transfers weights from `original_attn.q_proj` to `mqa_attn.q_proj`, a projection script would pass student hidden states through the new linear layer before comparing them to the teacher's pre-trained weights.
- The Loss function: Instead of using the standard Cross-Entropy loss shown in the Trainer setup, it would add a term like `MSELoss(projected_student_states, teacher_states)`.

**When to Use It**

Hidden State Projection is a specialized tool used for deep model refinement:
- Structural Compression: When compressing a large model (like Llama-3 70B) into a much smaller one (like Llama-3 8B), standard distillation is often insufficient. Hidden state projection provides the "blueprint" of the teacher's internal logic.
- Feature Alignment: Use it when the student needs to learn a specific way of organizing information, such as maintaining a certain "style" or "logic" found in the teacher's intermediate layers.
- Cross-Architecture Distillation: If the student and teacher have entirely different architectures (e.g., distilling a Transformer into a Recurrent model or a Mamba model), projection layers are the only way to compare their internal states.
- Accelerating Convergence: By providing supervision at every layer rather than just the output, the student often reaches high performance levels much faster than through standard fine-tuning.

In [ ]:
import torch
from torch import nn
from transformers import (
    AutoTokenizer, 
    AutoModelForCausalLM,
    DataCollatorForLanguageModeling,
    TrainingArguments,
    Trainer,
    TrainerCallback
)
from datasets import DatasetDict, Dataset
import gc
import os

In [9]:
# Configuration
MODEL_NAME = "meta-llama/Llama-3.2-1B-Instruct"   
OUTPUT_DIR = "./llama-3.2-1b-mqa-finetuned"

os.makedirs(OUTPUT_DIR, exist_ok=True)

# Load tokenizer
print(f"Loading tokenizer: {MODEL_NAME}")
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"
print(f"Tokenizer loaded. Vocab size: {len(tokenizer)}")

# Tokenization
def tokenize_examples(df, max_length=MAX_LENGTH):
    texts = []
    for row in df.iter_rows(named=True):
        text = f"Question: {row['question_title']}\n{row['question_body']}\nAnswer: {row['answer']}"
        texts.append(text)

    tokenized = tokenizer(
        texts,
        truncation=True,
        max_length=max_length,
        padding="max_length",
        return_tensors="pt"
    )
    tokenized["labels"] = tokenized["input_ids"].clone()
    tokenized["labels"][tokenized["labels"] == tokenizer.pad_token_id] = -100
    return tokenized

print("Tokenizing training data...")
train_tokenized = tokenize_examples(train_data)
print("Tokenizing validation data...")
val_tokenized = tokenize_examples(val_data)

dataset_dict = DatasetDict({
    "train": Dataset.from_dict(train_tokenized),
    "validation": Dataset.from_dict(val_tokenized)
})

print(f"Train examples: {len(dataset_dict['train']):,}")
print(f"Validation examples: {len(dataset_dict['validation']):,}")

# Efficient MQA Implementation for Llama-3.2
class LlamaMultiQueryAttention(nn.Module):
    def __init__(self, config):
        super().__init__()
        self.config = config
        self.num_heads = config.num_attention_heads
        self.head_dim = config.hidden_size // config.num_attention_heads
        self.hidden_size = config.hidden_size
        
        # Query projection for all heads
        self.q_proj = nn.Linear(config.hidden_size, self.num_heads * self.head_dim, bias=config.attention_bias)
        
        # Single key and value projections for MQA
        self.k_proj = nn.Linear(config.hidden_size, self.head_dim, bias=config.attention_bias)
        self.v_proj = nn.Linear(config.hidden_size, self.head_dim, bias=config.attention_bias)
        
        # Output projection
        self.o_proj = nn.Linear(self.num_heads * self.head_dim, config.hidden_size, bias=config.attention_bias)
        
        self.dropout = nn.Dropout(config.attention_dropout)
        self.scale = self.head_dim ** -0.5
        
    def forward(
        self,
        hidden_states,
        attention_mask=None,
        position_ids=None,
        past_key_value=None,
        output_attentions=False,
        use_cache=False,
        cache_position=None,
        position_embeddings=None,
        **kwargs,
    ):
        batch_size, seq_len, _ = hidden_states.shape
        
        # Project queries for all heads
        q = self.q_proj(hidden_states)
        q = q.view(batch_size, seq_len, self.num_heads, self.head_dim).transpose(1, 2)
        
        # Project keys and values (single head)
        k = self.k_proj(hidden_states)
        v = self.v_proj(hidden_states)
        
        # Reshape for attention computation
        k = k.view(batch_size, seq_len, 1, self.head_dim).transpose(1, 2)
        v = v.view(batch_size, seq_len, 1, self.head_dim).transpose(1, 2)
        
        # Expand single KV head to match query heads
        k = k.expand(-1, self.num_heads, -1, -1)
        v = v.expand(-1, self.num_heads, -1, -1)
        
        # Apply rotary embeddings if provided
        if position_embeddings is not None:
            cos, sin = position_embeddings
            q = self.apply_rotary_pos_emb(q, cos, sin)
            k = self.apply_rotary_pos_emb(k, cos, sin)
        
        # Handle past key values for caching
        if past_key_value is not None:
            k = torch.cat([past_key_value[0], k], dim=2)
            v = torch.cat([past_key_value[1], v], dim=2)
        
        # Update cache
        present_key_value = (k, v) if use_cache else None
        
        # Compute attention scores
        attn_weights = torch.matmul(q, k.transpose(-2, -1)) * self.scale
        
        if attention_mask is not None:
            attn_weights = attn_weights + attention_mask
            
        attn_weights = nn.functional.softmax(attn_weights, dim=-1, dtype=torch.float32).to(q.dtype)
        attn_weights = self.dropout(attn_weights)
        
        # Apply attention
        attn_output = torch.matmul(attn_weights, v)
        attn_output = attn_output.transpose(1, 2).contiguous()
        attn_output = attn_output.view(batch_size, seq_len, -1)
        
        # Final projection
        attn_output = self.o_proj(attn_output)
        
        return attn_output, present_key_value

    def apply_rotary_pos_emb(self, x, cos, sin):
        # x shape: [batch_size, num_heads, seq_len, head_dim]
        cos = cos.unsqueeze(0).unsqueeze(1)  # [1, 1, seq_len, head_dim]
        sin = sin.unsqueeze(0).unsqueeze(1)  # [1, 1, seq_len, head_dim]
        
        x_embed = (x * cos) + (self.rotate_half(x) * sin)
        return x_embed

    def rotate_half(self, x):
        x1, x2 = x.chunk(2, dim=-1)
        return torch.cat([-x2, x1], dim=-1)

def convert_llama_to_mqa(model):
    config = model.config
    
    for i, layer in enumerate(model.model.layers):
        original_attn = layer.self_attn
        
        # Create MQA attention module
        mqa_attn = LlamaMultiQueryAttention(config)
        
        # Transfer query weights
        mqa_attn.q_proj.weight.data = original_attn.q_proj.weight.data.clone()
        if hasattr(original_attn.q_proj, 'bias') and original_attn.q_proj.bias is not None:
            mqa_attn.q_proj.bias.data = original_attn.q_proj.bias.data.clone()
        
        # Average key/value weights across KV heads for MQA
        if hasattr(config, 'num_key_value_heads'):
            k_weight = original_attn.k_proj.weight.data
            v_weight = original_attn.v_proj.weight.data
            
            hidden_size = config.hidden_size
            head_dim = config.head_dim if hasattr(config, 'head_dim') else hidden_size // config.num_attention_heads
            num_kv_heads = config.num_key_value_heads
            
            # Reshape to [num_kv_heads, head_dim, hidden_size]
            k_weight_reshaped = k_weight.view(num_kv_heads, head_dim, hidden_size)
            v_weight_reshaped = v_weight.view(num_kv_heads, head_dim, hidden_size)
            
            # Average across KV heads
            k_weight_avg = k_weight_reshaped.mean(dim=0)
            v_weight_avg = v_weight_reshaped.mean(dim=0)
            
            # Assign averaged weights
            mqa_attn.k_proj.weight.data = k_weight_avg.clone()
            mqa_attn.v_proj.weight.data = v_weight_avg.clone()
            
            # Handle biases if present
            if hasattr(original_attn.k_proj, 'bias') and original_attn.k_proj.bias is not None:
                k_bias = original_attn.k_proj.bias.data
                v_bias = original_attn.v_proj.bias.data
                
                k_bias_reshaped = k_bias.view(num_kv_heads, head_dim)
                v_bias_reshaped = v_bias.view(num_kv_heads, head_dim)
                
                mqa_attn.k_proj.bias.data = k_bias_reshaped.mean(dim=0).clone()
                mqa_attn.v_proj.bias.data = v_bias_reshaped.mean(dim=0).clone()
        
        # Transfer output weights
        mqa_attn.o_proj.weight.data = original_attn.o_proj.weight.data.clone()
        if hasattr(original_attn.o_proj, 'bias') and original_attn.o_proj.bias is not None:
            mqa_attn.o_proj.bias.data = original_attn.o_proj.bias.data.clone()
        
        # Replace attention module
        layer.self_attn = mqa_attn
        
        print(f"Converted layer {i+1}/{len(model.model.layers)} to MQA")
    
    return model

# Load model
print(f"Loading {MODEL_NAME}...")
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    device_map="auto",
    dtype=torch.bfloat16,  
    attn_implementation="eager"  # Use eager attention for compatibility
)

print("Analyzing model architecture...")
print(f"Model type: {type(model).__name__}")
print(f"Hidden size: {model.config.hidden_size}")
print(f"Number of attention heads: {model.config.num_attention_heads}")
print(f"Head dimension: {model.config.hidden_size // model.config.num_attention_heads}")

if hasattr(model.config, 'num_key_value_heads'):
    print(f"Number of KV heads (GQA): {model.config.num_key_value_heads}")
    kv_groups = model.config.num_attention_heads // model.config.num_key_value_heads
    print(f"KV groups: {kv_groups}")

print("\nConverting model to Multi-Query Attention...")
model = convert_llama_to_mqa(model)

# Calculate parameter reduction
total_params = sum(p.numel() for p in model.parameters())
layers = len(model.model.layers)
head_dim = model.config.hidden_size // model.config.num_attention_heads

original_kv_params_per_layer = 2 * model.config.hidden_size * model.config.hidden_size
mqa_kv_params_per_layer = 2 * model.config.hidden_size * head_dim
kv_reduction_per_layer = original_kv_params_per_layer - mqa_kv_params_per_layer
total_kv_reduction = kv_reduction_per_layer * layers

print(f"\nParameter savings from MQA conversion:")
print(f"Original KV parameters per layer: {original_kv_params_per_layer:,}")
print(f"MQA KV parameters per layer: {mqa_kv_params_per_layer:,}")
print(f"Reduction per layer: {kv_reduction_per_layer:,}")
print(f"Total reduction across {layers} layers: {total_kv_reduction:,}")
print(f"Total model parameters: {total_params:,}")

# Training setup
data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

# Calculate total steps for warmup
total_steps = len(dataset_dict["train"]) * 3 // (8 * 1)  # samples * epochs / (batch_size * grad_accum)

monitor = EpochMonitor(model=model)

training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=8,         
    per_device_eval_batch_size=8,
    gradient_accumulation_steps=1,
    learning_rate=2e-5,
    weight_decay=0.01,
    max_grad_norm=1.0,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_steps=50,
    warmup_steps=int(0.1 * total_steps),
    lr_scheduler_type="cosine",
    bf16=True,  # Use bf16 for better stability
    optim="adamw_torch",
    gradient_checkpointing=False,  # Disable for stability with custom attention
    dataloader_num_workers=2,
    ddp_find_unused_parameters=False if torch.cuda.device_count() > 1 else None,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
    callbacks=[monitor], 
)

trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)
print(f"\nTrainable parameters: {trainable_params:,}")
print(f"Batch size: {training_args.per_device_train_batch_size}")

print("\n" + "="*60)
print("STARTING TRAINING WITH MULTI-QUERY ATTENTION")
print("="*60)
print(f"Model: {MODEL_NAME}")
print(f"Output dir: {OUTPUT_DIR}")
print(f"KV reduction: {total_kv_reduction:,} parameters")
print("="*60 + "\n")

train_result = trainer.train()

print("\nSaving model and tokenizer...")
model.save_pretrained(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)

print("\n" + "="*60)
print("TRAINING COMPLETED WITH MULTI-QUERY ATTENTION!")
print("="*60)
print(f"Model saved to: {OUTPUT_DIR}")
print(f"Final loss: {train_result.training_loss:.4f}")
print("="*60)

Loading tokenizer: meta-llama/Llama-3.2-1B-Instruct
Tokenizer loaded. Vocab size: 128256
Tokenizing training data...
Tokenizing validation data...
Train examples: 1,331
Validation examples: 285
Loading meta-llama/Llama-3.2-1B-Instruct...

Loading weights:   0%|          | 0/146 [00:00<?, ?it/s]

Analyzing model architecture...
Model type: LlamaForCausalLM
Hidden size: 2048
Number of attention heads: 32
Head dimension: 64
Number of KV heads (GQA): 8
KV groups: 4

Converting model to Multi-Query Attention...
Converted layer 1/16 to MQA
Converted layer 2/16 to MQA
Converted layer 3/16 to MQA
Converted layer 4/16 to MQA
Converted layer 5/16 to MQA
Converted layer 6/16 to MQA
Converted layer 7/16 to MQA
Converted layer 8/16 to MQA
Converted layer 9/16 to MQA
Converted layer 10/16 to MQA
Converted layer 11/16 to MQA
Converted layer 12/16 to MQA
Converted layer 13/16 to MQA
Converted layer 14/16 to MQA
Converted layer 15/16 to MQA
Converted layer 16/16 to MQA

Parameter savings from MQA conversion:
Original KV parameters per layer: 8,388,608
MQA KV parameters per layer: 262,144
Reduction per layer: 8,126,464
Total reduction across 16 layers: 130,023,424
Total model parameters: 1,206,454,272

Trainable parameters: 1,206,454,272
Batch size: 8

============================================================
STARTING TRAINING WITH MULTI-QUERY ATTENTION
============================================================
Model: meta-llama/Llama-3.2-1B-Instruct
Output dir: ./llama-3.2-1b-mqa-finetuned
KV reduction: 130,023,424 parameters
============================================================

Initial Model Memory Footprint:
  Parameters: 1,206,454,272
  Precision: 2 bytes
  Total Memory: 18.25 GB
    - Parameters: 2.25 GB
    - KV Cache (est): 16.00 GB
  Estimated FLOPs per forward pass (batch=8, seq=512): 8.89 TFLOPS

============================================================
Epoch 0 Summary
============================================================
  Duration (s)         :          65.39
  Tokens Processed     :        684,032
  Throughput (token/s) :          10460
  Training Steps       :            167
  Avg CPU (%)          :           17.5
  Avg Memory (%)       :            9.7
  Total FLOPs          : 1484.01 TFLOPS
  TFLOPS (per second)  :          22.69
  FLOPs (per token)    :    2.17 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================
Epoch 1 Summary
============================================================
  Duration (s)         :          65.60
  Tokens Processed     :        684,032
  Throughput (token/s) :          10427
  Training Steps       :            167
  Avg CPU (%)          :           17.8
  Avg Memory (%)       :            9.7
  Total FLOPs          : 1484.01 TFLOPS
  TFLOPS (per second)  :          22.62
  FLOPs (per token)    :    2.17 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================
Epoch 2 Summary
============================================================
  Duration (s)         :          65.75
  Tokens Processed     :        684,032
  Throughput (token/s) :          10403
  Training Steps       :            167
  Avg CPU (%)          :           19.5
  Avg Memory (%)       :            9.7
  Total FLOPs          : 1484.01 TFLOPS
  TFLOPS (per second)  :          22.57
  FLOPs (per token)    :    2.17 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['lm_head.weight'].

============================================================
TRAINING COMPLETE
============================================================
Total Training Time: 241.03s
Total Epochs: 3
Average Epoch Time: 65.58s
Total Tokens Processed: 2,052,096
Average Throughput: 8514 tokens/second
Total FLOPs: 4452.03 TFLOPS
Average TFLOPS (per second): 18.47
Overall FLOPs (per token): 2.17 GFLOPS

Final Metrics:
Memory Footprint: 18.25 GB
Inference Throughput: 16370 tokens/second
Total Training FLOPs: 1484.01 TFLOPS

Saving model and tokenizer...

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================
TRAINING COMPLETED WITH MULTI-QUERY ATTENTION!
============================================================
Model saved to: ./llama-3.2-1b-mqa-finetuned
Final loss: 4.0657
============================================================

In [10]:
summarize_training_results(trainer, monitor)

====================================================================================================
TRAINING RESULTS SUMMARY TABLE
====================================================================================================
Epoch Training Loss Validation Loss Time (s) Tokens Processed Throughput (token/s) TFLOPS (per second) Avg CPU (%) Avg Memory (%) Training Steps
    0        6.4720          5.5317    65.39          684,032                10460               22.69        17.5            9.7            167
    1        4.3429          5.6775    65.60          684,032                10426               22.62        17.8            9.7            167
    2        3.9056          5.7912    65.75          684,032                10402               22.57        19.5            9.7            167

----------------------------------------------------------------------------------------------------
TRAINING STATISTICS:
----------------------------------------------------------------------------------------------------
Total Training Time:      196.8 s
Average Epoch Time:       65.6 s
Total Tokens Processed:   2,052,096
Average Throughput:       10430 tokens/second
Average CPU Usage:        18.3%
Average Memory Usage:     9.7%
Total Training FLOPs:     4452.03 TFLOPS
Average TFLOPS (per sec): 22.63
Overall FLOPs (per token): 2.17 GFLOPS

====================================================================================================

**Reference** 
- [Arxiv:Fast Transformer Decoding: One Write-Head is All You Need](https://arxiv.org/abs/1911.02150)
- [Arxiv:GQA: Training Generalized Multi-Query Transformer Models from
Multi-Head Checkpoints](https://arxiv.org/pdf/2305.13245)
- [Aaclanthology:GQA: Training Generalized Multi-Query Transformer Models from Multi-Head Checkpoints](https://aclanthology.org/2023.emnlp-main.298/)

### !Grouped-Query Attention (GQA)

Grouped-Query Attention (GQA) is an optimization technique for the attention mechanism in Large Language Models. It serves as a middle ground between Multi-Head Attention (MHA), which is memory-intensive, and Multi-Query Attention (MQA), which can suffer from quality degradation. GQA organizes query heads into groups, where each group shares a single Key-Value (KV) head. This drastically reduces the size of the KV cache during inference while maintaining high model performance.

**How it Works**

Standard attention mechanisms face a bottleneck during token generation because the KV cache must be stored in memory for every token in the sequence.
- Multi-Head Attention (MHA): Every Query head has its own corresponding Key and Value head. This provides maximum expressiveness but consumes massive VRAM as sequences grow.
- Multi-Query Attention (MQA): All Query heads share a single Key and Value head. This is incredibly fast and memory-efficient but can lead to a drop in the model's ability to handle complex relationships.
- Grouped-Query Attention (GQA): Query heads are divided into "groups." For example, if a model has 32 query heads and 8 KV heads, each KV head is shared by 4 query heads. This provides a balance, keeping the memory footprint low while allowing the model to attend to different types of information through its multiple KV groups.

**Implements Grouped-Query Attention**

The provided code does not manually construct the GQA architecture; instead, it leverages native GQA support built into modern models like Gemma-3.

**Architecture Selection:**

By loading `google/gemma-3-1b-it`, the script initializes a model that already contains GQA in its weights and configuration.

**Configuration Verification:**

The code explicitly checks the `num_key_value_heads` parameter. In the output, if `num_attention_heads` (e.g., 16) is greater than `num_key_value_heads` (e.g., 8), the model is functioning in GQA mode.

if hasattr(config, 'num_key_value_heads'):
    print(f"Model uses GQA: {config.num_attention_heads} query heads, {config.num_key_value_heads} key-value heads")

**Efficiency Gains:**

During the `trainer.train()` call, the GQA architecture allows the model to handle the `per_device_train_batch_size` more efficiently. Since the KV cache produced during evaluation and internal processing is compressed (e.g., by 2x or 4x), more memory is available for weights and gradients, reducing the likelihood of "Out of Memory" (OOM) errors compared to an MHA model of the same size.

**When to Use It**

Grouped-Query Attention is the modern standard for high-performance LLMs and should be used in these contexts:
- Inference at Scale: When deploying a model to serve thousands of users, GQA allows for significantly larger batch sizes and higher throughput because the KV cache takes up much less space per user.
- Long-Context Window Tasks: If the application requires processing documents with thousands of tokens, GQA is essential. Without it, the VRAM required just to store the "memory" of the conversation (the KV cache) would exceed the capacity of most GPUs.
- Edge Device Deployment: For running models on local hardware with limited VRAM (like laptops or mobile phones), GQA makes it possible to run larger, more capable models that would otherwise be too memory-heavy.
- Training Large Models: Most state-of-the-art models (Llama 3, Gemma 2/3, Mistral) are pre-trained with GQA. When fine-tuning, maintaining this architecture is necessary to keep the weights compatible and the performance optimized.

In [6]:
import torch
from transformers import (
    AutoTokenizer, 
    AutoModelForCausalLM, 
    TrainingArguments, 
    Trainer,
    DataCollatorForLanguageModeling
)
from datasets import Dataset, DatasetDict
import os
import numpy as np

In [7]:
# Configuration
MODEL_NAME = "google/gemma-3-1b-it"  # Gemma model with GQA
OUTPUT_DIR = "./gqa-model-finetuned"
MAX_LENGTH = 128
BATCH_SIZE = 4
EPOCHS = 3

os.makedirs(OUTPUT_DIR, exist_ok=True)

# Load tokenizer
print(f"Loading tokenizer: {MODEL_NAME}")
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"

# Tokenization
def tokenize_examples(df, max_length=MAX_LENGTH):
    texts = [
        f"Question: {row['question_title']}\n{row['question_body']}\nAnswer: {row['answer']}"
        for row in df.iter_rows(named=True)
    ]
    tokenized = tokenizer(
        texts,
        truncation=True,
        max_length=max_length,
        padding="max_length",
        return_tensors="pt"
    )
    labels = tokenized["input_ids"].clone()
    labels[labels == tokenizer.pad_token_id] = -100
    tokenized["labels"] = labels
    return tokenized

# Tokenize datasets
print("Tokenizing training data...")
train_tokenized = tokenize_examples(train_data)

print("Tokenizing validation data...")
val_tokenized = tokenize_examples(val_data)

dataset_dict = DatasetDict({
    "train": Dataset.from_dict({
        "input_ids": train_tokenized["input_ids"].tolist(),
        "attention_mask": train_tokenized["attention_mask"].tolist(),
        "labels": train_tokenized["labels"].tolist()
    }),
    "validation": Dataset.from_dict({
        "input_ids": val_tokenized["input_ids"].tolist(),
        "attention_mask": val_tokenized["attention_mask"].tolist(),
        "labels": val_tokenized["labels"].tolist()
    })
})

print(f"Train examples: {len(dataset_dict['train']):,}")
print(f"Validation examples: {len(dataset_dict['validation']):,}")

# Load GQA model
print(f"Loading {MODEL_NAME} with GQA...")
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    device_map="auto",
    torch_dtype=torch.bfloat16,  # Changed from float16 to bfloat16
    low_cpu_mem_usage=True,
)

# Check GQA configuration
config = model.config
if hasattr(config, 'num_key_value_heads'):
    num_query_heads = config.num_attention_heads
    num_kv_heads = config.num_key_value_heads
    compression_ratio = num_query_heads / num_kv_heads if num_kv_heads > 0 else 0
    
    print(f"\nModel uses GQA: {num_query_heads} query heads, {num_kv_heads} key-value heads")
    print(f"KV cache compression: {compression_ratio:.1f}x")
    print(f"Each KV head serves {compression_ratio:.0f} query heads")

# Memory and compute estimation
def estimate_memory_footprint(model, batch_size=BATCH_SIZE, seq_length=MAX_LENGTH):
    num_params = sum(p.numel() for p in model.parameters())
    param_memory = num_params * 2 / (1024**3)  # bfloat16 = 2 bytes
    
    # Estimate KV cache size for GQA
    config = model.config
    num_kv_heads = getattr(config, 'num_key_value_heads', config.num_attention_heads)
    hidden_size = config.hidden_size
    head_dim = hidden_size // config.num_attention_heads
    
    # KV cache memory for one batch (bfloat16)
    kv_cache_memory = 2 * batch_size * seq_length * num_kv_heads * head_dim * 2 / (1024**3)  # *2 for key and value
    
    total_memory = param_memory + kv_cache_memory
    
    print(f"\nInitial Model Memory Footprint:")
    print(f"  Parameters: {num_params:,}")
    print(f"  Precision: 2 bytes (bfloat16)")
    print(f"  Total Memory: {total_memory:.2f} GB")
    print(f"    - Parameters: {param_memory:.2f} GB")
    print(f"    - KV Cache (est): {kv_cache_memory:.2f} GB")
    
    return total_memory

def estimate_flops(model, batch_size=BATCH_SIZE, seq_length=MAX_LENGTH):
    config = model.config
    hidden_size = config.hidden_size
    num_layers = config.num_hidden_layers
    vocab_size = config.vocab_size
    
    # Rough FLOPs estimation
    # Attention: 2 * batch * seq_len^2 * hidden_size
    attention_flops = 2 * batch_size * (seq_length ** 2) * hidden_size * num_layers
    
    # FFN: 2 * batch * seq_len * hidden_size * (4 * hidden_size) * num_layers
    ffn_flops = 8 * batch_size * seq_length * (hidden_size ** 2) * num_layers
    
    # Logits: batch * seq_len * hidden_size * vocab_size
    logits_flops = batch_size * seq_length * hidden_size * vocab_size
    
    total_flops = (attention_flops + ffn_flops + logits_flops) / 1e12  # Convert to TFLOPS
    
    print(f"  Estimated FLOPs per forward pass (batch={batch_size}, seq={seq_length}): {total_flops:.2f} TFLOPS")
    
    return total_flops

# Calculate and display metrics
total_params = sum(p.numel() for p in model.parameters())
print(f"\nTotal parameters: {total_params:,}")

estimate_memory_footprint(model)
estimate_flops(model)

# Training setup
data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

monitor = EpochMonitor(model=model)

training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=EPOCHS,
    per_device_train_batch_size=BATCH_SIZE,
    per_device_eval_batch_size=BATCH_SIZE,
    gradient_accumulation_steps=1,
    learning_rate=2e-5,
    weight_decay=0.01,
    max_grad_norm=1.0,  # Added gradient clipping
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=True,
    logging_steps=50,
    warmup_steps=100,
    lr_scheduler_type="cosine",
    bf16=True,  # Changed from fp16 to bf16
    dataloader_num_workers=2,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
    callbacks = [monitor]
)

print("\nStarting training with GQA...")
train_result = trainer.train()

# Save model
trainer.save_model()
tokenizer.save_pretrained(OUTPUT_DIR)

print(f"\nTraining completed! Model saved to {OUTPUT_DIR}")

# Final statistics
print("\nFinal Training Statistics:")
print(f"  Total parameters: {total_params:,}")
print(f"  GQA configuration: {num_query_heads} query heads, {num_kv_heads} KV heads")
print(f"  KV cache compression: {compression_ratio:.1f}x")
print(f"  Memory saved with GQA: {(1 - 1/compression_ratio) * 100:.1f}% less KV cache")

Loading tokenizer: google/gemma-3-1b-it

config.json:   0%|          | 0.00/899 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/1.16M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/33.4M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/35.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/662 [00:00<?, ?B/s]

Tokenizing training data...
Tokenizing validation data...

`torch_dtype` is deprecated! Use `dtype` instead!

Train examples: 1,331
Validation examples: 285
Loading google/gemma-3-1b-it with GQA...

model.safetensors:   0%|          | 0.00/2.00G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/340 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/215 [00:00<?, ?B/s]

Model uses GQA: 4 query heads, 1 key-value heads
KV cache compression: 4.0x
Each KV head serves 4 query heads

Total parameters: 999,885,952

Initial Model Memory Footprint:
  Parameters: 999,885,952
  Precision: 2 bytes (bfloat16)
  Total Memory: 1.86 GB
    - Parameters: 1.86 GB
    - KV Cache (est): 0.00 GB
  Estimated FLOPs per forward pass (batch=4, seq=128): 0.30 TFLOPS

Starting training with GQA...
Initial Model Memory Footprint:
  Parameters: 999,885,952
  Precision: 2 bytes
  Total Memory: 5.52 GB
    - Parameters: 1.86 GB
    - KV Cache (est): 3.66 GB
  Estimated FLOPs per forward pass (batch=8, seq=512): 7.12 TFLOPS

============================================================
Epoch 0 Summary
============================================================
  Duration (s)         :          99.98
  Tokens Processed     :        681,984
  Throughput (token/s) :           6821
  Training Steps       :            333
  Avg CPU (%)          :           22.3
  Avg Memory (%)       :           14.2
  Total FLOPs          : 1185.83 TFLOPS
  TFLOPS (per second)  :          11.86
  FLOPs (per token)    :    1.74 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================
Epoch 1 Summary
============================================================
  Duration (s)         :         101.77
  Tokens Processed     :        681,984
  Throughput (token/s) :           6701
  Training Steps       :            333
  Avg CPU (%)          :           23.1
  Avg Memory (%)       :           14.0
  Total FLOPs          : 1185.83 TFLOPS
  TFLOPS (per second)  :          11.65
  FLOPs (per token)    :    1.74 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================
Epoch 2 Summary
============================================================
  Duration (s)         :         102.37
  Tokens Processed     :        681,984
  Throughput (token/s) :           6662
  Training Steps       :            333
  Avg CPU (%)          :           26.1
  Avg Memory (%)       :           14.0
  Total FLOPs          : 1185.83 TFLOPS
  TFLOPS (per second)  :          11.58
  FLOPs (per token)    :    1.74 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['lm_head.weight'].

============================================================
TRAINING COMPLETE
============================================================
Total Training Time: 343.26s
Total Epochs: 3
Average Epoch Time: 101.37s
Total Tokens Processed: 2,045,952
Average Throughput: 5960 tokens/second
Total FLOPs: 3557.50 TFLOPS
Average TFLOPS (per second): 10.36
Overall FLOPs (per token): 1.74 GFLOPS

Final Metrics:
Memory Footprint: 5.52 GB
Inference Throughput: 12602 tokens/second
Total Training FLOPs: 1185.83 TFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Training completed! Model saved to ./gqa-model-finetuned

Final Training Statistics:
  Total parameters: 999,885,952
  GQA configuration: 4 query heads, 1 KV heads
  KV cache compression: 4.0x
  Memory saved with GQA: 75.0% less KV cache

In [8]:
summarize_training_results(trainer, monitor)

====================================================================================================
TRAINING RESULTS SUMMARY TABLE
====================================================================================================
Epoch Training Loss Validation Loss Time (s) Tokens Processed Throughput (token/s) TFLOPS (per second) Avg CPU (%) Avg Memory (%) Training Steps
    0        3.1339          4.8366    99.98          681,984                 6821               11.86        22.3           14.2            333
    1        1.6762          5.4858   101.77          681,984                 6701               11.65        23.1           14.0            333
    2        0.9963          5.8412   102.37          681,984                 6662               11.58        26.1           14.0            333

----------------------------------------------------------------------------------------------------
TRAINING STATISTICS:
----------------------------------------------------------------------------------------------------
Total Training Time:      304.1 s
Average Epoch Time:       101.4 s
Total Tokens Processed:   2,045,952
Average Throughput:       6728 tokens/second
Average CPU Usage:        23.8%
Average Memory Usage:     14.1%
Total Training FLOPs:     3557.50 TFLOPS
Average TFLOPS (per sec): 11.70
Overall FLOPs (per token): 1.74 GFLOPS

====================================================================================================

**Reference** 
- [Arxiv:GQA: Training Generalized Multi-Query Transformer Models from Multi-Head Checkpoints](https://arxiv.org/abs/2305.13245)

### Linear Attention Variants

Linear Attention Adaptation is a structural optimization that replaces the standard "Softmax Attention" in a Transformer with a mathematically equivalent or approximate form that scales linearly with sequence length.

In standard models, the attention mechanism calculates an $L \times L$ matrix (where $L$ is sequence length), resulting in $O(L^2)$ complexity. Linear attention uses the associative property of matrix multiplication to change the order of operations, reducing complexity to $O(L \cdot d^2)$, where $d$ is the much smaller head dimension.

**How it Works**

The key to linear attention is removing the softmax function that sits between the Query ($Q$) and Key ($K$) matrices.
- Feature Mapping: Standard attention calculates $\text{Softmax}(QK^T)V$. Because of the softmax, $Q$ and $K$ must be multiplied first. Linear attention replaces softmax with a feature map $\phi(x)$.
- Changing the Order: The equation becomes $(\phi(Q)\phi(K)^T)V$. Because matrix multiplication is associative, this can be rewritten as:$$\phi(Q) \times (\phi(K)^T \times V)$$
- The KV Buffer: By calculating $\phi(K)^T \times V$ first, the model creates a fixed-size "summary" matrix of size $d \times d$. The queries then interact with this summary instead of every individual previous token.

**Implementation Linear Attention Adaptation**

The code snippet provided defines a LinearAttentionLayer that implements a popular variant often seen in Linear Transformers.
- Positive Feature Map: The code uses `torch.nn.functional.elu(q) + 1.0`. This is a common feature map ϕ(x) that ensures all values are positive (required for stability when removing softmax) while maintaining a gradient for small values.
- The "KV" Summary: The line `kv = torch.einsum('bhnd,bhne->bhde', k, v)` calculates the relationship between Keys and Values across the entire sequence before involving the Queries. This results in a d×d representation.
- Normalization (`Z`): Since softmax normally ensures that attention weights sum to 1, linear attention needs a manual "denominator." The code calculates z by summing the Key features, ensuring the output remains at the correct scale.
- Linear Projection: Finally, `attn_output = torch.einsum('bhnd,bhde,bhn->bhne', q, kv, z)` applies the Queries to the pre-calculated KV summary.

**When to Use It**

Linear Attention Adaptation is a powerful tool, but it involves trade-offs in accuracy:
- Processing Millions of Tokens: When the context length L is so large (e.g., 100k+ tokens) that even FlashAttention cannot prevent a GPU out-of-memory error.
- Real-time Streaming: In applications like live audio processing or continuous sensor monitoring where the model must "remember" an indefinite history without the processing time increasing over time.
- Fast Autoregressive Decoding: Linear attention can be formulated as a Recurrent Neural Network (RNN). This allows for constant-time (O(1)) generation per token, making it much faster for chatbots than standard Transformers which get slower as the conversation gets longer.
- In-Context Learning Bottlenecks: Use it when the "KV Cache" size is the primary limiting factor for scaling your system's throughput.

In [ ]:
import torch
import torch.nn as nn
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    Trainer,
    TrainingArguments,
    DataCollatorForLanguageModeling
)
from datasets import DatasetDict, Dataset

In [13]:
# Configuration
MODEL_NAME = "meta-llama/Llama-3.2-1B-Instruct"
OUTPUT_DIR = "./linear-attention-variant"
MAX_LENGTH = 128

# Load tokenizer
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
tokenizer.pad_token = tokenizer.eos_token

# Tokenization
def tokenize_examples(df, max_length=MAX_LENGTH):
    texts = [
        f"Question: {row['question_title']}\n{row['question_body']}\nAnswer: {row['answer']}"
        for row in df.iter_rows(named=True)
    ]
    tokenized = tokenizer(
        texts,
        truncation=True,
        max_length=max_length,
        padding="max_length",
        return_tensors="pt"
    )
    tokenized["labels"] = tokenized["input_ids"].clone()
    return tokenized

# Tokenize datasets
train_tokenized = tokenize_examples(train_data)
val_tokenized = tokenize_examples(val_data)

dataset_dict = DatasetDict({
    "train": Dataset.from_dict({
        "input_ids": train_tokenized["input_ids"],
        "attention_mask": train_tokenized["attention_mask"],
        "labels": train_tokenized["labels"]
    }),
    "validation": Dataset.from_dict({
        "input_ids": val_tokenized["input_ids"],
        "attention_mask": val_tokenized["attention_mask"],
        "labels": val_tokenized["labels"]
    })
})

# Load standard model
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    device_map="auto",
    torch_dtype=torch.float16,
    low_cpu_mem_usage=True,
)

# Custom linear attention layer 
class LinearAttentionLayer(nn.Module):
    def __init__(self, dim, heads=8):
        super().__init__()
        self.dim = dim
        self.heads = heads
        self.head_dim = dim // heads
        
        self.q_proj = nn.Linear(dim, dim)
        self.k_proj = nn.Linear(dim, dim)
        self.v_proj = nn.Linear(dim, dim)
        self.out_proj = nn.Linear(dim, dim)
        
    def forward(self, x):
        batch, seq, _ = x.shape
        
        q = self.q_proj(x).view(batch, seq, self.heads, self.head_dim).transpose(1, 2)
        k = self.k_proj(x).view(batch, seq, self.heads, self.head_dim).transpose(1, 2)
        v = self.v_proj(x).view(batch, seq, self.heads, self.head_dim).transpose(1, 2)
        
        # Linear attention approximation
        q = torch.nn.functional.elu(q) + 1.0
        k = torch.nn.functional.elu(k) + 1.0
        
        # Linear complexity attention
        kv = torch.einsum('bhnd,bhne->bhde', k, v)
        z = 1.0 / (torch.einsum('bhnd,bhd->bhn', q, k.sum(dim=2)) + 1e-6)
        attn_output = torch.einsum('bhnd,bhde,bhn->bhne', q, kv, z)
        
        attn_output = attn_output.transpose(1, 2).contiguous().view(batch, seq, -1)
        return self.out_proj(attn_output)

# Training setup
data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

monitor = EpochMonitor(model=model)

training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    gradient_accumulation_steps=1,
    learning_rate=2e-5,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=True,
    logging_strategy="epoch",
    warmup_steps=100,
    lr_scheduler_type="cosine",
    fp16=False,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
    callbacks = [monitor]
)

total_params = sum(p.numel() for p in model.parameters())
print(f"Total parameters: {total_params:,}")
print("Starting training with standard attention...")

trainer.train()
trainer.save_model()
tokenizer.save_pretrained(OUTPUT_DIR)
print("Training completed!")

Loading weights:   0%|          | 0/146 [00:00<?, ?it/s]

Total parameters: 1,235,814,400
Starting training with standard attention...
Initial Model Memory Footprint:
  Parameters: 1,235,814,400
  Precision: 2 bytes
  Total Memory: 18.30 GB
    - Parameters: 2.30 GB
    - KV Cache (est): 16.00 GB
  Estimated FLOPs per forward pass (batch=8, seq=512): 8.89 TFLOPS

============================================================
Epoch 0 Summary
============================================================
  Duration (s)         :          71.19
  Tokens Processed     :        684,032
  Throughput (token/s) :           9609
  Training Steps       :            167
  Avg CPU (%)          :           18.5
  Avg Memory (%)       :           12.7
  Total FLOPs          : 1484.01 TFLOPS
  TFLOPS (per second)  :          20.85
  FLOPs (per token)    :    2.17 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================
Epoch 1 Summary
============================================================
  Duration (s)         :          71.47
  Tokens Processed     :        684,032
  Throughput (token/s) :           9570
  Training Steps       :            167
  Avg CPU (%)          :           16.6
  Avg Memory (%)       :           12.7
  Total FLOPs          : 1484.01 TFLOPS
  TFLOPS (per second)  :          20.76
  FLOPs (per token)    :    2.17 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================
Epoch 2 Summary
============================================================
  Duration (s)         :          70.58
  Tokens Processed     :        684,032
  Throughput (token/s) :           9692
  Training Steps       :            167
  Avg CPU (%)          :           21.2
  Avg Memory (%)       :           12.8
  Total FLOPs          : 1484.01 TFLOPS
  TFLOPS (per second)  :          21.03
  FLOPs (per token)    :    2.17 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['lm_head.weight'].

============================================================
TRAINING COMPLETE
============================================================
Total Training Time: 251.53s
Total Epochs: 3
Average Epoch Time: 71.08s
Total Tokens Processed: 2,052,096
Average Throughput: 8158 tokens/second
Total FLOPs: 4452.03 TFLOPS
Average TFLOPS (per second): 17.70
Overall FLOPs (per token): 2.17 GFLOPS

Final Metrics:
Memory Footprint: 18.30 GB
Inference Throughput: 18008 tokens/second
Total Training FLOPs: 1484.01 TFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Training completed!

In [14]:
summarize_training_results(trainer, monitor)

====================================================================================================
TRAINING RESULTS SUMMARY TABLE
====================================================================================================
Epoch Training Loss Validation Loss Time (s) Tokens Processed Throughput (token/s) TFLOPS (per second) Avg CPU (%) Avg Memory (%) Training Steps
    0      120.2749        278.6335    71.19          684,032                 9609               20.85        18.5           12.7            167
    1      763.2401       4239.8730    71.47          684,032                 9570               20.76        16.6           12.7            167
    2      542.8405        304.6598    70.58          684,032                 9691               21.03        21.2           12.8            167

----------------------------------------------------------------------------------------------------
TRAINING STATISTICS:
----------------------------------------------------------------------------------------------------
Total Training Time:      213.2 s
Average Epoch Time:       71.1 s
Total Tokens Processed:   2,052,096
Average Throughput:       9623 tokens/second
Average CPU Usage:        18.8%
Average Memory Usage:     12.7%
Total Training FLOPs:     4452.03 TFLOPS
Average TFLOPS (per sec): 20.88
Overall FLOPs (per token): 2.17 GFLOPS

====================================================================================================

**Reference** 
- [Arxiv:On-the-Fly Adaptive Distillation of Transformer to Dual-State Linear Attention for Long-Context LLM Serving](https://arxiv.org/html/2506.09316v1)
- [Arxiv:Neural Attention Search Linear: Towards Adaptive Token-Level Hybrid Attention Models](https://arxiv.org/abs/2602.03681)
- [Aaclanthology:Span-Selective Linear Attention Transformers for Effective and Robust Schema-Guided Dialogue State Tracking](https://aclanthology.org/2023.acl-long.6/)
- [OpenReview:Enhancing linear attention with residual learning](https://openreview.net/forum?id=dy6tnQMeyI)

### Memory Compressed Attention

Memory Compressed Attention is a structural optimization technique designed to reduce the memory footprint of the Key-Value (KV) cache, specifically by shrinking the sequence dimension of Keys and Values.

Standard attention mechanisms maintain a 1:1 ratio between queries and the stored key-value pairs. As the input sequence grows, the KV cache grows linearly, which often becomes the primary memory bottleneck during long-context training and inference. Memory Compressed Attention breaks this 1:1 ratio by using pooling or convolutions to "summarize" multiple tokens into a single compressed representation, allowing the model to attend to the same context using significantly less memory.

**How it Works**

The core idea is to apply a compression function to the Key (K) and Value (V) tensors before the attention calculation begins.
- Selection of Ratio: A compression ratio is defined (e.g., 4:1). This means for every 4 input tokens, only 1 compressed "summary" token is stored in the cache.
- Downsampling: The sequence of Keys and Values is downsampled along the time (sequence length) dimension. This can be done via strided convolutions, linear projections, or adaptive pooling.
- Cross-Attention: The Queries (Q) remain at their original length to ensure the model produces one output for every input token. The Queries then perform a cross-attention operation against the shortened K and V tensors.
- Memory Savings: The resulting attention matrix is reduced from L×L to L×(L/r), where r is the compression ratio.

**Memory Compressed Attention Implementation**

The provided code implements a wrapper that modifies the internal attention forward pass using Adaptive Average Pooling.

**The Compression Function (`compress_kv`):**

This function takes the original K and V tensors and uses `F.`. It treats the head dimension as a channel and pools across the sequence dimension.

    k_compressed = F.adaptive_avg_pool1d(k.transpose(2, 3), compressed_len).transpose(2, 3)
    
This effectively "averages" every few tokens into one, reducing the total number of keys and values the model has to look at.

**Thresholding:** 

The code includes a check (if `seq_len <= 128`) to skip compression for short sequences, as the overhead of pooling isn't worth it when memory isn't yet a bottleneck.

**The Attention Calculation:**

    attn_weights = torch.matmul(q, k_compressed.transpose(-2, -1))

Here, the Queries (q) are at full sequence length, but they are being multiplied by a much smaller K matrix. This results in a smaller attention weight matrix, saving VRAM during the backward pass (gradients).

**When to Use It**

Memory Compressed Attention is particularly useful in specific high-resource scenarios:
- Long-Document Summarization: When training or fine-tuning models to handle documents exceeding 16k or 32k tokens, where standard attention would cause immediate "Out of Memory" (OOM) errors.
- High-Throughput Batching: When you need to increase the batch size during training to improve GPU utilization but are limited by the memory required for the attention activations.
- Hierarchical Information Processing: For tasks where the model needs to understand the "gist" of a long history rather than every exact word, as pooling naturally acts as a semantic summarizer.
- Constraint-Based Deployment: When deploying a model on hardware with very limited VRAM but where long-context capability is still a requirement.

In [ ]:
import torch
import torch.nn as nn
import torch.nn.functional as F
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    Trainer,
    TrainingArguments,
    DataCollatorForLanguageModeling
)
from datasets import DatasetDict, Dataset

In [15]:
# Configuration
MODEL_NAME = "meta-llama/Llama-3.2-1B-Instruct"
OUTPUT_DIR = "./memory-compressed-attention"
MAX_LENGTH = 128

# Load tokenizer
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
tokenizer.pad_token = tokenizer.eos_token

# Tokenization
def tokenize_examples(df, max_length=MAX_LENGTH):
    texts = [
        f"Question: {row['question_title']}\n{row['question_body']}\nAnswer: {row['answer']}"
        for row in df.iter_rows(named=True)
    ]
    tokenized = tokenizer(
        texts,
        truncation=True,
        max_length=max_length,
        padding="max_length",
        return_tensors="pt"
    )
    tokenized["labels"] = tokenized["input_ids"].clone()
    return tokenized

# Tokenize datasets
train_tokenized = tokenize_examples(train_data)
val_tokenized = tokenize_examples(val_data)

dataset_dict = DatasetDict({
    "train": Dataset.from_dict({
        "input_ids": train_tokenized["input_ids"],
        "attention_mask": train_tokenized["attention_mask"],
        "labels": train_tokenized["labels"]
    }),
    "validation": Dataset.from_dict({
        "input_ids": val_tokenized["input_ids"],
        "attention_mask": val_tokenized["attention_mask"],
        "labels": val_tokenized["labels"]
    })
})

# Load model
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    device_map="auto",
    torch_dtype=torch.float16,
    low_cpu_mem_usage=True,
)

# Memory compressed attention wrapper
class MemoryCompressedAttention(nn.Module):
    def __init__(self, original_attn, compression_ratio=4):
        super().__init__()
        self.original_attn = original_attn
        self.compression_ratio = compression_ratio
        
    def compress_kv(self, k, v):
        batch, heads, seq_len, dim = k.shape
        
        if seq_len <= 128:  # Don't compress short sequences
            return k, v
        
        compressed_len = max(seq_len // self.compression_ratio, 32)
        
        # Use adaptive pooling to compress
        k_compressed = F.adaptive_avg_pool1d(
            k.transpose(2, 3), compressed_len
        ).transpose(2, 3)
        
        v_compressed = F.adaptive_avg_pool1d(
            v.transpose(2, 3), compressed_len
        ).transpose(2, 3)
        
        return k_compressed, v_compressed
    
    def forward(self, hidden_states, attention_mask=None, **kwargs):
        # Get original attention weights
        q_proj = self.original_attn.q_proj
        k_proj = self.original_attn.k_proj
        v_proj = self.original_attn.v_proj
        out_proj = self.original_attn.o_proj
        
        batch, seq_len, hidden_dim = hidden_states.shape
        
        # Project queries, keys, values
        q = q_proj(hidden_states)
        k = k_proj(hidden_states)
        v = v_proj(hidden_states)
        
        # Reshape for multi-head attention
        heads = self.original_attn.num_heads
        head_dim = hidden_dim // heads
        
        q = q.view(batch, seq_len, heads, head_dim).transpose(1, 2)
        k = k.view(batch, seq_len, heads, head_dim).transpose(1, 2)
        v = v.view(batch, seq_len, heads, head_dim).transpose(1, 2)
        
        # Compress keys and values
        k_compressed, v_compressed = self.compress_kv(k, v)
        
        # Compute attention with compressed KV
        attn_weights = torch.matmul(q, k_compressed.transpose(-2, -1))
        
        if attention_mask is not None:
            attn_weights = attn_weights + attention_mask
            
        attn_weights = F.softmax(attn_weights, dim=-1)
        attn_output = torch.matmul(attn_weights, v_compressed)
        
        # Reshape and project
        attn_output = attn_output.transpose(1, 2).contiguous().view(batch, seq_len, hidden_dim)
        return out_proj(attn_output)

# Training setup
data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

monitor = EpochMonitor(model=model)

training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    gradient_accumulation_steps=1,
    learning_rate=2e-5,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=True,
    logging_strategy="epoch",
    warmup_steps=100,
    lr_scheduler_type="cosine",
    fp16=False,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
    callbacks = [monitor]
)

total_params = sum(p.numel() for p in model.parameters())
print(f"Total parameters: {total_params:,}")
print("Starting training...")
print("Note: For production memory compressed attention, use xformers library")

trainer.train()
trainer.save_model()
tokenizer.save_pretrained(OUTPUT_DIR)
print("Training completed!")

Loading weights:   0%|          | 0/146 [00:00<?, ?it/s]

Total parameters: 1,235,814,400
Starting training...
Note: For production memory compressed attention, use xformers library
Initial Model Memory Footprint:
  Parameters: 1,235,814,400
  Precision: 2 bytes
  Total Memory: 18.30 GB
    - Parameters: 2.30 GB
    - KV Cache (est): 16.00 GB
  Estimated FLOPs per forward pass (batch=8, seq=512): 8.89 TFLOPS

============================================================
Epoch 0 Summary
============================================================
  Duration (s)         :          71.40
  Tokens Processed     :        684,032
  Throughput (token/s) :           9581
  Training Steps       :            167
  Avg CPU (%)          :           18.5
  Avg Memory (%)       :           12.5
  Total FLOPs          : 1484.01 TFLOPS
  TFLOPS (per second)  :          20.79
  FLOPs (per token)    :    2.17 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================
Epoch 1 Summary
============================================================
  Duration (s)         :          71.59
  Tokens Processed     :        684,032
  Throughput (token/s) :           9555
  Training Steps       :            167
  Avg CPU (%)          :           19.3
  Avg Memory (%)       :           12.5
  Total FLOPs          : 1484.01 TFLOPS
  TFLOPS (per second)  :          20.73
  FLOPs (per token)    :    2.17 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================
Epoch 2 Summary
============================================================
  Duration (s)         :          71.59
  Tokens Processed     :        684,032
  Throughput (token/s) :           9555
  Training Steps       :            167
  Avg CPU (%)          :           15.7
  Avg Memory (%)       :           12.5
  Total FLOPs          : 1484.01 TFLOPS
  TFLOPS (per second)  :          20.73
  FLOPs (per token)    :    2.17 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['lm_head.weight'].

============================================================
TRAINING COMPLETE
============================================================
Total Training Time: 258.91s
Total Epochs: 3
Average Epoch Time: 71.52s
Total Tokens Processed: 2,052,096
Average Throughput: 7926 tokens/second
Total FLOPs: 4452.03 TFLOPS
Average TFLOPS (per second): 17.19
Overall FLOPs (per token): 2.17 GFLOPS

Final Metrics:
Memory Footprint: 18.30 GB
Inference Throughput: 17875 tokens/second
Total Training FLOPs: 1484.01 TFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Training completed!

In [16]:
summarize_training_results(trainer, monitor)

====================================================================================================
TRAINING RESULTS SUMMARY TABLE
====================================================================================================
Epoch Training Loss Validation Loss Time (s) Tokens Processed Throughput (token/s) TFLOPS (per second) Avg CPU (%) Avg Memory (%) Training Steps
    0      120.2749        278.6335    71.40          684,032                 9580               20.79        18.5           12.5            167
    1      763.2401       4239.8730    71.59          684,032                 9555               20.73        19.3           12.5            167
    2      542.8405        304.6598    71.59          684,032                 9555               20.73        15.7           12.5            167

----------------------------------------------------------------------------------------------------
TRAINING STATISTICS:
----------------------------------------------------------------------------------------------------
Total Training Time:      214.6 s
Average Epoch Time:       71.5 s
Total Tokens Processed:   2,052,096
Average Throughput:       9564 tokens/second
Average CPU Usage:        17.8%
Average Memory Usage:     12.5%
Total Training FLOPs:     4452.03 TFLOPS
Average TFLOPS (per sec): 20.75
Overall FLOPs (per token): 2.17 GFLOPS

====================================================================================================

**Reference** 
- [Arxiv:LoMA: Lossless Compressed Memory Attention](https://arxiv.org/abs/2401.09486)
- [Aaclanthology:ClusterAttn: KV Cache Compression under Intrinsic Attention Clustering](https://aclanthology.org/2025.acl-long.703/)
- [OpenReview:Attention and Compression is all you need for Controllably Efficient Language Models](https://openreview.net/forum?id=6rYa2BUnTt)

## Mixture of Experts Optimization

Mixture of Experts (MoE) Optimization focuses on managing the sparsity of the model to maximize intelligence while minimizing the actual hardware work required for each token. Unlike dense models where every parameter is used for every word, MoE uses a Router (or Gating Network) to select a tiny subset of "experts" for each task.

Optimization during fine-tuning and deployment ensures that this selection process is fast, balanced, and computationally efficient.

**MoE Fine-tuning Strategies**

Fine-tuning an MoE model requires a careful balance to prevent the model from "collapsing" into using only a few favorite experts, which would waste the capacity of the rest of the model.
- Expert Specialization: During fine-tuning on specialized datasets (like medical or coding data), specific experts are encouraged to learn the nuances of that domain. This allows the model to act as a collection of specialists rather than one generalist.
- Routing Optimization: A common efficiency trick is to "freeze" the expert weights and only fine-tune the routing logic. This trains the model to better identify which existing expert is best suited for a new task without the high cost of updating billions of parameters.
- Sparse/Partial Expert Updates: To save VRAM and compute during training, developers may only backpropagate gradients through the experts that were actually activated for a given batch.
- Expert Load Balancing: Optimization includes monitoring "expert popularity." If one expert is overloaded, the system applies a penalty, forcing the router to distribute the workload to underutilized experts.

**Efficient MoE Training and Deployment**

Deploying and training these massive sparse models requires specific architectural guardrails to maintain speed.
- Top-k Gating with Capacity Factor: The router usually picks the "Top-1" or "Top-2" best experts. A Capacity Factor is a hard limit on how many tokens a single expert can handle in one pass. If an expert is "full," tokens are either dropped or sent to a second-choice expert to prevent computational bottlenecks.
- Auxiliary Losses: To ensure the model remains efficient, developers add extra "penalties" to the loss function. These losses specifically target load balancing (making sure all experts are used) and importance (making sure each expert contributes meaningful information).
- Expert Dropout: Similar to standard dropout, this technique randomly disables certain experts during training. This forces the model to be robust, ensuring that the knowledge is distributed and the model doesn't become overly dependent on a single "master" expert.
- Gradient Accumulation for MoE: Because different experts might receive different amounts of data in a single step, computational requirements vary. Gradient accumulation helps smooth out these spikes, allowing the model to train on hardware that might otherwise struggle with the uneven memory demands of sparse layers.

In [ ]:
%%capture
!pip install packaging
!pip install psutil
!pip install ninja
!pip install --upgrade ninja
!MAX_JOBS=4 pip install flash-attn --no-build-isolation

import torch
import transformers
from transformers import (
    AutoTokenizer, 
    AutoModelForCausalLM,
    DataCollatorForLanguageModeling,
    TrainingArguments,
    Trainer,
)
from datasets import DatasetDict, Dataset
from peft import LoraConfig, get_peft_model, TaskType

In [7]:
# Configuration
MODEL_NAME = "microsoft/Phi-tiny-MoE-instruct"
OUTPUT_DIR = "./phi-tiny-moe-finetuned"
MAX_LENGTH = 128

print(f"Loading tokenizer: {MODEL_NAME}")
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
tokenizer.pad_token = tokenizer.eos_token
print(f"Tokenizer loaded. Vocab size: {len(tokenizer)}")

def tokenize_examples(df, max_length=MAX_LENGTH):
    texts = []
    for row in df.iter_rows(named=True):
        text = f"Question: {row['question_title']}\n{row['question_body']}\nAnswer: {row['answer']}"
        texts.append(text)

    tokenized = tokenizer(
        texts,
        truncation=True,
        max_length=max_length,
        padding="max_length",
        return_tensors="pt"
    )
    tokenized["labels"] = tokenized["input_ids"].clone()
    return tokenized

print("Tokenizing training data...")
train_tokenized = tokenize_examples(train_data)

print("Tokenizing validation data...")
val_tokenized = tokenize_examples(val_data)

dataset_dict = DatasetDict({
    "train": Dataset.from_dict({
        "input_ids": train_tokenized["input_ids"],
        "attention_mask": train_tokenized["attention_mask"],
        "labels": train_tokenized["labels"]
    }),
    "validation": Dataset.from_dict({
        "input_ids": val_tokenized["input_ids"],
        "attention_mask": val_tokenized["attention_mask"],
        "labels": val_tokenized["labels"]
    })
})

print(f"Train examples: {len(dataset_dict['train']):,}")
print(f"Validation examples: {len(dataset_dict['validation']):,}")

Loading tokenizer: microsoft/Phi-tiny-MoE-instruct
Tokenizer loaded. Vocab size: 32011
Tokenizing training data...
Tokenizing validation data...
Train examples: 1,331
Validation examples: 285

**Reference** 
- [Arxiv:A Comprehensive Survey of Mixture-of-Experts: Algorithms, Theory, and Applications](https://arxiv.org/abs/2503.07137)
- [Arxiv:A Survey on Inference Optimization Techniques for Mixture of Experts Models](https://arxiv.org/abs/2412.14219)
- [Arxiv:Mixture of Experts for Network Optimization: A Large Language Model-enabled Approach](https://arxiv.org/abs/2402.09756)
- [Wikipedia:Mixture of experts](https://en.wikipedia.org/wiki/Mixture_of_experts)
- [Huggingface:Mixture of Experts Explained](https://huggingface.co/blog/moe)

### Top-k Gating with Capacity Factor + bitsandbytes + LoRA

Top-k Gating with Capacity Factor is an optimization technique for Mixture-of-Experts (MoE) models that prevents "expert overflow." In an MoE model, if a specific expert becomes too "popular" and receives too many tokens from a batch, it creates a computational bottleneck. The Capacity Factor acts as a hard limit on how many tokens any single expert is allowed to process, ensuring that the workload is distributed and the training/inference speed remains predictable.

**How it Works**

Standard Top-k gating simply picks the best k experts for each token. However, in large-scale systems, this can lead to Expert Hotspots where one GPU is overwhelmed while others are idle.

- Expert Capacity Calculation: The system calculates a maximum capacity for each expert using the formula:$$Capacity = \left( \frac{\text{Tokens per Batch}}{\text{Number of Experts}} \right) \times \text{Capacity Factor}$$
- Routing with Limits: Tokens are routed to their preferred experts. If an expert reaches its $Capacity$, any additional tokens assigned to it are "dropped."
- Handling Dropped Tokens: Dropped tokens typically bypass the expert layers entirely via a residual connection (acting as if that layer was an identity function) to ensure the model doesn't crash, though this may slightly reduce accuracy for those specific tokens.
- Capacity Factor (CF): * CF = 1.0: Perfect mathematical balance. If routing is uneven, many tokens will be dropped.
    - CF > 1.0 (e.g., 1.25): Provides "slack." Experts can handle 25% more than their "fair share," reducing the number of dropped tokens at the cost of some wasted memory/compute padding.

**Top-k Gating with Capacity Factor Implementation**

The code uses `microsoft/Phi-tiny-MoE-instruct`, which is a sparse MoE model. It does not manually define the gating logic because it is baked into the model's architecture.
- Native Configuration: The script `prints model.config.num_experts_per_tok`. This value is the k in Top-k. For Phi-tiny-MoE, this is typically 2, meaning each token is sent to the top 2 experts.
- Automatic Enforcement: When `trainer.train()` is called, the model's internal Forward pass executes a routing function. If the model was trained with a capacity factor (common in the Phi and Switch Transformer families), it automatically counts the tokens assigned to each expert.
- Buffer Management: In a distributed training setup (which the `TrainingArguments` are prepared for via `bf16` and `gradient_checkpointing`), the capacity factor ensures that the "all-to-all" communication buffers between GPUs have a fixed size. Without a capacity factor, the code would need dynamic memory allocation, which is much slower and prone to crashing.

**When to Use It**

Top-k Gating with a Capacity Factor is essential in specific high-performance environments:
- Expert Parallelism: When experts are spread across multiple GPUs. You use a capacity factor to prevent one GPU from waiting indefinitely for another GPU that received too many tokens (the "straggler" problem).
- Predictable Latency: In production deployment, you use a low capacity factor to guarantee that the model always responds within a certain timeframe, even if it means occasionally dropping a token's expert processing.
- Large Batch Training: During pre-training or fine-tuning with large `gradient_accumulation_steps`, a capacity factor prevents memory spikes that would otherwise occur if a batch happened to contain many tokens that all wanted the same expert.
- Hardware with Fixed Buffers: On specialized hardware (like TPUs or certain high-speed interconnects) where memory must be pre-allocated before the computation begins.

In [7]:
import torch
import transformers
from transformers import (
    AutoTokenizer, 
    AutoModelForCausalLM,
    DataCollatorForLanguageModeling,
    TrainingArguments,
    Trainer,
)
from datasets import DatasetDict, Dataset
from peft import LoraConfig, get_peft_model, TaskType

In [ ]:
# Configuration
MODEL_NAME = "microsoft/Phi-tiny-MoE-instruct"
OUTPUT_DIR = "./phi-tiny-moe-topk-finetuned"

print(f"Loading {MODEL_NAME} with flash-attn support...")
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")

model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    torch_dtype=torch.float16,
    low_cpu_mem_usage=True,
    #use_flash_attention_2=True,
)

model.to(device)

print("\nMoE Configuration:")
print(f"Model type: {type(model).__name__}")
print(f"Number of experts: {model.config.num_local_experts}")
print(f"Experts per token: {model.config.num_experts_per_tok}")
print(f"Hidden size: {model.config.hidden_size}")
print(f"Using flash-attention: {model.config._attn_implementation == 'flash_attention_2'}")

total_params = sum(p.numel() for p in model.parameters())
print(f"Total parameters: {total_params:,}")

# LoRA configuration
lora_config = LoraConfig(
    task_type=TaskType.CAUSAL_LM,
    r=8,
    lora_alpha=16,
    lora_dropout=0.1,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj"],
    bias="none",
)

model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

monitor = EpochMonitor(model=model)

data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=1,
    per_device_eval_batch_size=1,
    gradient_accumulation_steps=4,
    learning_rate=1e-4,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_strategy="epoch",
    run_name="phi-tiny-moe-topk",
    warmup_ratio=0.1,
    lr_scheduler_type="cosine",
    gradient_checkpointing=True,
    bf16=True,
    optim="paged_adamw_8bit",
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
    callbacks=[monitor],
)

print("\nTraining with Top-k Gating (built-in)...")
print(f"Using {model.config.num_experts_per_tok} experts per token")

train_result = trainer.train()

model.save_pretrained(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)

print("\nTraining completed!")

**Reference** 
- [Arxiv:Switch Transformers: Scaling to Trillion Parameter Models with Simple and Efficient Sparsity](https://arxiv.org/abs/2101.03961)
- [Arxiv:Statistical Perspective of Top-K Sparse Softmax Gating Mixture of Experts](https://arxiv.org/abs/2309.13850)
- [Arxiv:Mixture-of-Experts with Expert Choice Routing](https://arxiv.org/pdf/2202.09368)
- [Huggingface:A Review on the Evolvement of Load Balancing Strategy in MoE LLMs: Pitfalls and Lessons](https://huggingface.co/blog/NormalUhr/moe-balance)

### Sparse/Partial Expert Updates

Sparse/Partial Expert Updates is an optimization technique where only a specific subset of the "experts" in a Mixture-of-Experts (MoE) model are unfrozen and updated during training or fine-tuning.

In a standard MoE model, there might be dozens or hundreds of experts. Updating every single one is computationally expensive and memory-intensive. Sparse updates allow you to pick the most relevant experts for a task (e.g., experts that already specialize in coding) and only train them, keeping the rest of the model's trillions of parameters frozen.

**How it Works**

The technique leverages the modular nature of MoE architectures to isolate gradients.
- Freezing the Backbone: All parameters in the model—including the attention layers and the gating networks—are initially set to be non-trainable.
- Expert Selection: You identify which experts should learn the new information. This can be done by selecting specific expert indices (e.g., Expert 0, 1, and 2) or by using a heuristic that identifies which experts are most frequently activated by the training data.
- Local Unfreezing: Only the weights inside these selected expert blocks are set to requires_grad = True.
- Sparse Gradient Flow: During the backward pass, gradients are only calculated and stored for the unfrozen experts. This significantly reduces VRAM usage because you don't need to store the "optimizer states" (like momentum) for the thousands of frozen experts.

**Implements Sparse Expert Updates**

The provided code demonstrates a surgical approach to unfreezing parameters in the Phi-tiny-MoE model.
- **Global Freeze:** It starts by disabling gradients for every parameter in the model:

    for param in model.parameters():
        param.requires_grad = False

- **Targeted Unfreezing:**

It then iterates through the model's named parameters. It specifically looks for strings containing `mlp.experts` and checks if the expert index matches the `experts_to_train` list:

    if "mlp.experts" in name:
        for expert_num in experts_to_train:
            if f"experts.{expert_num}" in name:
                param.requires_grad = True

**Combining with PEFT:**

The code also unfreezes the LoRA (Low-Rank Adaptation) parameters. This creates a "Hybrid Sparse Update" where the model gains new knowledge through the LoRA layers and fine-tunes the specific expertise of the chosen experts.

**Memory Efficiency:**

By training only 3 out of the total experts, the `trainable_params` count drops to a tiny fraction (shown as 0.XXX% in the logs), allowing the model to be fine-tuned on much smaller GPUs than a full-parameter update would require.

**When to Use It**

Sparse/Partial Expert Updates are the ideal choice in the following scenarios:
- Domain-Specific Adaptation: When you have a general-purpose MoE (like Mixtral or Phi-MoE) and want to make it an expert in a niche field like "Legal Document Analysis" without ruining its general intelligence.
- VRAM Constraints: When the total model size (e.g., 47B parameters) is too large for your hardware, but you can afford to train 2-3 experts (effectively training a much smaller dense model).
- Preventing Catastrophic Forgetting: By leaving most experts frozen, you preserve the model's original pre-trained knowledge. Only the selected experts change, ensuring the model doesn't "forget" how to perform basic tasks while learning new ones.
- Rapid Prototyping: Since fewer parameters are being updated, the optimizer has less work to do, often resulting in slightly faster training iterations and lower storage requirements for checkpoints.

In [ ]:
import torch
import transformers
from transformers import (
    AutoTokenizer, 
    AutoModelForCausalLM,
    DataCollatorForLanguageModeling,
    TrainingArguments,
    Trainer,
)
from datasets import DatasetDict, Dataset
from peft import LoraConfig, get_peft_model, TaskType

In [ ]:
# Configuration
MODEL_NAME = "microsoft/Phi-tiny-MoE-instruct"
OUTPUT_DIR = "./phi-tiny-moe-sparse-finetuned"

print(f"Loading {MODEL_NAME} without quantization...")
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")

model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    torch_dtype=torch.float32,
    low_cpu_mem_usage=True,
)

model.to(device)

print(f"\nMoE Configuration:")
print(f"Model type: {type(model).__name__}")
print(f"Hidden size: {model.config.hidden_size}")
print(f"Number of experts: {model.config.num_local_experts}")
print(f"Experts per token: {model.config.num_experts_per_tok}")
print(f"Model dtype: {model.dtype}")

total_params = sum(p.numel() for p in model.parameters())
print(f"Total parameters: {total_params:,}")

# LoRA configuration
lora_config = LoraConfig(
    task_type=TaskType.CAUSAL_LM,
    r=4,
    lora_alpha=8,
    lora_dropout=0.05,
    target_modules=["q_proj", "v_proj"],
    bias="none",
)

model = get_peft_model(model, lora_config)

# Freeze all parameters first
for param in model.parameters():
    param.requires_grad = False

# Unfreeze only specific experts for sparse updates
print("\nApplying Sparse Expert Updates...")
total_experts = model.config.num_local_experts
experts_to_train = [0, 1, 2]  # Train only first 3 experts
print(f"Training experts: {experts_to_train} out of {total_experts} total experts")

# Track which parameters we're unfreezing
expert_params_unfrozen = 0
lora_params_unfrozen = 0

for name, param in model.named_parameters():
    # Unfreeze selected experts
    if "mlp.experts" in name:
        for expert_num in experts_to_train:
            if f"experts.{expert_num}" in name:
                param.requires_grad = True
                expert_params_unfrozen += param.numel()
                break
    
    # Unfreeze LoRA parameters
    if "lora" in name:
        param.requires_grad = True
        lora_params_unfrozen += param.numel()

# Calculate statistics
total_params = sum(p.numel() for p in model.parameters())
trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)

print(f"\nParameter Statistics:")
print(f"Total parameters: {total_params:,}")
print(f"Trainable parameters: {trainable_params:,}")
print(f"Trainable percentage: {trainable_params/total_params*100:.3f}%")
print(f"Expert parameters unfrozen: {expert_params_unfrozen:,}")
print(f"LoRA parameters unfrozen: {lora_params_unfrozen:,}")

data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

monitor = EpochMonitor(model=model)

training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=2,
    per_device_train_batch_size=1,
    per_device_eval_batch_size=1,
    gradient_accumulation_steps=8,
    learning_rate=1e-4,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_strategy="epoch",
    run_name="phi-moe-sparse",
    warmup_steps=20,
    lr_scheduler_type="cosine",
    fp16=False,  # Disable mixed precision for stability
    gradient_checkpointing=True,
    optim="adamw_torch",
    dataloader_pin_memory=False,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
    callbacks=[monitor],
)

print(f"\nTraining Configuration:")
print(f"Device: {device}")
print(f"Batch size: {training_args.per_device_train_batch_size}")
print(f"Gradient accumulation: {training_args.gradient_accumulation_steps}")
print(f"Effective batch size: {training_args.per_device_train_batch_size * training_args.gradient_accumulation_steps}")
print(f"Memory savings: Only {len(experts_to_train)}/{total_experts} experts are trainable")

train_result = trainer.train()

model.save_pretrained(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)

print("\nTraining completed with Sparse Expert Updates!")

In [ ]:
summarize_training_results(trainer, monitor)

**Alternative Options Setup**

In [ ]:
# Option 1: Train "specialist" experts (odd-numbered)
experts_to_train = [1, 3, 5, 7, 9, 11, 13, 15]  # Odd experts as specialists

# Option 2: Train "generalist" experts (even-numbered)  
experts_to_train = [0, 2, 4, 6, 8, 10, 12, 14]  # Even experts as generalists

# Option 3: Random selection
import random
total_experts = model.config.num_local_experts
num_to_train = total_experts // 4  # Train 25% of experts
experts_to_train = random.sample(range(total_experts), num_to_train)
print(f"Randomly selected experts to train: {sorted(experts_to_train)}")

**Reference** 
- [Arxiv:Sparse maximal update parameterization: A holistic approach to sparse training dynamics](https://arxiv.org/html/2405.15743v3)
- [Arxiv:Partial Experts Checkpoint: Efficient Fault Tolerance for Sparse Mixture-of-Experts Model Training](https://arxiv.org/html/2408.04307v1)
- [Openreview:Drop-Upcycling: Training Sparse Mixture of Experts with Partial Re-initialization](https://openreview.net/forum?id=gx1wHnf5Vp)
- [Huggingface:Drop-Upcycling: Training Sparse Mixture of Experts with Partial Re-initialization](https://huggingface.co/papers/2502.19261)

### Expert Load Balancing (via Auxiliary Losses)

Expert Load Balancing is an optimization technique used in Mixture-of-Experts (MoE) models to ensure that the "router" distributes tokens evenly across all available experts. Without balancing, an MoE model often suffers from "expert collapse," where the routing algorithm learns to send almost all tokens to only one or two "favorite" experts. This makes the other experts redundant, effectively wasting the model's capacity and causing computational bottlenecks on the specific hardware hosting the overloaded experts.

**How it Works**

Expert Load Balancing works by introducing a specific mathematical penalty during training that discourages the router from being biased.
- Utilization Tracking: During the forward pass, the model tracks how many tokens are assigned to each expert and the routing probabilities (gating scores) assigned to them.
- Auxiliary Loss Calculation: An additional loss term, called the Auxiliary Loss (or Balancing Loss), is calculated. This loss is minimized when the distribution of tokens across experts is uniform.
- The Switch Divergence: It often measures the correlation between the probability of picking an expert and the actual frequency of picking that expert. High correlation with a uniform distribution results in a lower penalty.
- Joint Optimization: The model tries to minimize both the standard language modeling loss (predicting the next word) and this auxiliary loss. If the router starts favoring one expert too much, the rising auxiliary loss forces it to reconsider underutilized experts.

**Expert Load Balancing Implementation**

The provided script implements load balancing by explicitly activating and configuring the auxiliary loss mechanism within the Phi-tiny-MoE architecture.

**Configuring the Coefficient:**

The line `model.config.aux_loss_coef = 0.01` is the critical trigger. It tells the model's internal loss function to weigh the balancing penalty. A coefficient of 0.01 means 1% of the total gradient signal will be dedicated to ensuring experts are used evenly.

    model.config.aux_loss_coef = 0.01

**Router Supervision:**

During `trainer.train()`, the model's forward pass returns not just the language modeling loss, but also the load-balancing loss. The Trainer automatically sums these.

**Gradient Flow:**

Because the routing weights (the "gate") are part of the differentiable graph, the auxiliary loss provides gradients that specifically update the gating network's parameters, teaching it to "spread the wealth" of tokens across all `num_local_experts`.

**When to Use It**

Expert Load Balancing should be prioritized in the following circumstances:
- Fine-tuning on New Domains: When moving a general MoE model to a specific domain (like legal or medical text), the router might over-rely on a few experts that happen to have relevant initial weights. Balancing prevents the other experts from being ignored and forgotten.
- Distributed Training: In setups where experts are split across different GPUs (Expert Parallelism), load balancing is essential for performance. If one GPU (expert) gets 90% of the tokens, the other GPUs will sit idle, leading to massive hardware inefficiency.
- Pre-training from Scratch: It is nearly impossible to train a functional MoE model without load balancing; the model will almost always collapse into a dense model during the first few thousand steps without it.
- Maximizing Model Capacity: If the goal is to ensure the "intelligence" of a 47B parameter model is actually being used, load balancing ensures that every parameter contributes to the final output rather than just a small fraction of the model doing all the work.

In [ ]:
import torch
import transformers
from transformers import (
    AutoTokenizer, 
    AutoModelForCausalLM,
    DataCollatorForLanguageModeling,
    TrainingArguments,
    Trainer,
)
from datasets import DatasetDict, Dataset
from peft import LoraConfig, get_peft_model, TaskType

In [ ]:
# Configuration
MODEL_NAME = "microsoft/Phi-tiny-MoE-instruct"
OUTPUT_DIR = "./phi-tiny-moe-balanced-finetuned"

print(f"Loading {MODEL_NAME}...")
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")

model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    torch_dtype=torch.float32,
    low_cpu_mem_usage=True,
)

model.to(device)

print("\nMoE Configuration:")
print(f"Model type: {type(model).__name__}")
print(f"Number of experts: {model.config.num_local_experts}")
print(f"Experts per token: {model.config.num_experts_per_tok}")
print(f"Hidden size: {model.config.hidden_size}")

# Enable auxiliary loss for expert load balancing
model.config.aux_loss_coef = 0.01
print(f"Auxiliary loss coefficient set to: {model.config.aux_loss_coef}")

# LoRA configuration
lora_config = LoraConfig(
    task_type=TaskType.CAUSAL_LM,
    r=8,
    lora_alpha=16,
    lora_dropout=0.1,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj"],
    bias="none",
)

model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

class EpochMonitor(transformers.TrainerCallback):
    def on_epoch_end(self, args, state, control, **kwargs):
        print(f"Epoch {state.epoch} completed. Loss: {state.log_history[-1].get('loss', 'N/A')}")

monitor = EpochMonitor(model=model)

data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=1,
    per_device_eval_batch_size=1,
    gradient_accumulation_steps=16,
    learning_rate=1e-4,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_strategy="epoch",
    run_name="phi-tiny-moe-balanced",
    warmup_ratio=0.1,
    lr_scheduler_type="cosine",
    gradient_checkpointing=True,
    bf16=True,
    optim="paged_adamw_8bit",
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
    callbacks=[monitor],
)

print("\nTraining with Expert Load Balancing...")
print(f"Using auxiliary loss (coefficient: {model.config.aux_loss_coef}) to ensure balanced expert utilization")
print(f"Training on {model.config.num_local_experts} experts with {model.config.num_experts_per_tok} experts per token")

train_result = trainer.train()

model.save_pretrained(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)

print("\nTraining completed!")
print(f"Final loss: {train_result.training_loss:.4f}")
print(f"Model saved to: {OUTPUT_DIR}")

Loading microsoft/Phi-tiny-MoE-instruct...
Using device: cuda

Loading weights:   0%|          | 0/485 [00:00<?, ?it/s]

In [ ]:
summarize_training_results(trainer, monitor)

**Reference** 
- [Arxiv:Auxiliary-Loss-Free Load Balancing Strategy for Mixture-of-Experts](https://arxiv.org/abs/2408.15664)
- [Arxiv:A Theoretical Framework for Auxiliary-Loss-Free Load Balancing of Sparse Mixture-of-Experts in Large-Scale AI Models](https://arxiv.org/abs/2512.03915)
- [Arxiv:Load Balancing Mixture of Experts with Similarity Preserving Routers](https://arxiv.org/abs/2506.14038)
- [Arxiv:Least-Loaded Expert Parallelism: Load Balancing An Imbalanced Mixture-of-Experts](https://arxiv.org/abs/2601.17111)
- [Huggingface:A Review on the Evolvement of Load Balancing Strategy in MoE LLMs: Pitfalls and Lessons](https://huggingface.co/blog/NormalUhr/moe-balance)

### Routing Optimization (Router-only Tuning)

Routing Optimization is a specialized fine-tuning strategy for Mixture-of-Experts (MoE) models that focuses exclusively on the "Gating Network" (the router). Instead of retraining the billions of parameters contained within the experts—which already possess vast knowledge—this technique trains the model to better "navigate" its existing knowledge. By adjusting only the router, the model learns to send specific types of inputs to the most appropriate pre-trained experts for a given new task or domain.

**How it Works**

The fundamental idea is to treat the pre-trained experts as a static library of specialized skills and the router as a librarian whose job is to direct traffic more effectively.
- Freezing Experts: All the weights inside the Feed-Forward Networks (the experts) are frozen. This prevents "catastrophic forgetting," ensuring the experts do not lose their general-purpose reasoning capabilities.
- Gating Supervision: During backpropagation, gradients are only used to update the router's weights. The router learns the relationship between the input hidden states and the expert indices that yield the lowest loss for the specific dataset.
- Representational Alignment: The router learns to identify subtle cues in the input text—such as specific terminology, tone, or structural patterns—to select the "Top-k" experts that have already seen similar patterns during their initial pre-training.

**Routing Optimization Implementation**

The provided script uses a targeted approach to isolate the training signals to the attention and routing mechanisms using Parameter-Efficient Fine-Tuning (PEFT).

**Identification of Router Layers:**

The code programmatically searches for layers containing the string "router." These are the linear layers that output the logits used to select which experts are activated.

    if 'router' in name.lower():
        # logic to identify and track router modules

**LoRA Integration:**

The script applies LoRA to the attention layers (`q_proj, v_proj, etc.`). This allows the model to adapt its "reading comprehension" while the router learns to adapt its "expert selection."

**Strict Freezing:**

The critical optimization step occurs when the script iterates through all parameters and sets `requires_grad = False` for anything that is not a LoRA weight. Since the expert weights are not part of the LoRA target modules, they are completely frozen.

    for name, param in model.named_parameters():
        if 'lora' not in name:
            param.requires_grad = False

**Efficiency:**

Because the heavy expert weights (which make up the vast majority of an MoE model's size) are frozen, the optimizer only needs to track a tiny fraction of the parameters. This drastically reduces the VRAM required for the optimizer's memory states.

**When to Use It**

Routing Optimization is the preferred method in specific scenarios where maintaining the original model's integrity is as important as learning the new task:
- Domain Transfer with Limited Data: If a small dataset is available for a new field (e.g., legal or technical writing), retraining experts might cause them to "overfit" and lose general logic. Routing optimization simply teaches the model which existing experts are best at "speaking" that specific language.
- Low-Resource Hardware: When a model like Mixtral 8x7B (approx. 47B parameters) needs to be tuned on a single consumer GPU. Freezing the experts allows the user to train the model because only the router and LoRA weights require gradient memory.
- Multi-Task Learning: When adding a new capability to a model that must remain a "jack of all trades." Only the router changes its "opinion" on which experts to use for the new task, leaving the experts' core knowledge untouched for other tasks.
- Rapid Adaptation: Because so few parameters are being updated, the model often converges (reaches its best performance) much faster than full-parameter fine-tuning.

In [ ]:
import torch
import transformers
from transformers import (
    AutoTokenizer, 
    AutoModelForCausalLM,
    DataCollatorForLanguageModeling,
    TrainingArguments,
    Trainer,
)
from datasets import DatasetDict, Dataset
from peft import LoraConfig, get_peft_model, TaskType

In [ ]:
# Configuration
MODEL_NAME = "microsoft/Phi-tiny-MoE-instruct"
OUTPUT_DIR = "./phi-tiny-moe-router-finetuned"

print(f"Loading {MODEL_NAME}...")
device = "cuda" if torch.cuda.is_available() else "cpu"
print(f"Using device: {device}")

model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    dtype=torch.float32,
    low_cpu_mem_usage=True,
)

model.to(device)

print("\nMoE Configuration:")
print(f"Model type: {type(model).__name__}")
print(f"Number of experts: {model.config.num_local_experts}")
print(f"Experts per token: {model.config.num_experts_per_tok}")
print(f"Hidden size: {model.config.hidden_size}")

# Identify all linear layers in router modules
router_module_names = []
linear_layers_in_router = []

for name, module in model.named_modules():
    if 'router' in name.lower():
        router_module_names.append(name)
        # Get the parent module to find linear layers within it
        parent_name = name[:name.rfind('.')]
        parent_module = model.get_submodule(parent_name)
        
        # Look for linear layers in the router module
        for sub_name, sub_module in parent_module.named_modules():
            full_name = f"{parent_name}.{sub_name}" if sub_name else parent_name
            if isinstance(sub_module, torch.nn.Linear):
                linear_layers_in_router.append(full_name)
                print(f"Found Linear layer in router: {full_name}")

print(f"\nFound {len(router_module_names)} router modules")
print(f"Found {len(linear_layers_in_router)} Linear layers in router modules")

# Use a simpler approach - target all linear layers in the model
# This will include router linear layers but also others
lora_config = LoraConfig(
    task_type=TaskType.CAUSAL_LM,
    r=2,
    lora_alpha=4,
    lora_dropout=0.05,
    target_modules=["q_proj", "k_proj", "v_proj", "o_proj"],  # Standard attention layers
    bias="none",
)

# Apply LoRA
model = get_peft_model(model, lora_config)

# Freeze all non-LoRA parameters
print("\nApplying Router Optimization Tuning...")
print("Freezing all expert weights, training only attention and routing layers with LoRA")

for name, param in model.named_parameters():
    if 'lora' not in name:
        param.requires_grad = False

model.print_trainable_parameters()

class EpochMonitor(transformers.TrainerCallback):
    def on_epoch_end(self, args, state, control, **kwargs):
        if state.log_history:
            latest_log = state.log_history[-1]
            loss = latest_log.get('loss', latest_log.get('eval_loss', 'N/A'))
            print(f"Epoch {state.epoch} completed. Loss: {loss}")

monitor = EpochMonitor(model=model)

data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=1,
    per_device_eval_batch_size=1,
    gradient_accumulation_steps=16,
    learning_rate=1e-4,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_strategy="epoch",
    run_name="phi-tiny-moe-balanced",
    warmup_ratio=0.1,
    lr_scheduler_type="cosine",
    gradient_checkpointing=True,
    bf16=True,
    optim="paged_adamw_8bit",
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
    callbacks=[monitor],
)

print("\nTraining with Routing Optimization...")
print("Optimizing routing mechanisms without modifying expert weights")

train_result = trainer.train()

model.save_pretrained(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)

print("\nTraining completed!")
print(f"Final loss: {train_result.training_loss:.4f}")
print(f"Model saved to: {OUTPUT_DIR}")

In [ ]:
summarize_training_results(trainer, monitor)

**Reference** 
- [Arxiv:Router-Tuning: A Simple and Effective Approach for Dynamic Depth](https://arxiv.org/html/2410.13184v2)
- [APXML:Router Optimization Strategies](https://apxml.com/courses/mixture-of-experts/chapter-3-moe-training-dynamics-optimization/router-optimization-strategies)

# MEMORY & COMPUTE OPTIMIZATION

Memory and Compute Optimization involves systems-level strategies to manage GPU physical resources during the training and fine-tuning of Large Language Models. These techniques address the "Memory Wall," where the VRAM required to store model weights, gradients, optimizer states, and activations exceeds the capacity of available hardware. By strategically trading compute time for memory space or offloading data, these optimizations enable the training of massive models on limited hardware.

**How it Works: Gradient and Activation Management**

The most effective optimizations focus on the two largest consumers of VRAM during training: gradients and intermediate activations.

**Gradient Checkpointing**

In a standard training pass, every layer's output (activation) is saved in memory to calculate gradients later. Gradient checkpointing deletes most of these activations after the forward pass. During the backward pass, the model re-runs the forward calculation for a specific segment to recreate the missing data.
- Selective Checkpointing: Only the most memory-intensive or "heavy" activations are saved, while lightweight ones are recomputed.
- Layer-wise Checkpointing: Different strategies are applied depending on the layer; for instance, saving activations for attention layers but recomputing for MLP layers.
- Dynamic Checkpointing: The system monitors real-time VRAM usage and adjusts how many activations to store or discard on the fly.

**Gradient Accumulation**

Since large batch sizes are required for stable training but often cause "Out of Memory" errors, gradient accumulation breaks a large batch into smaller "micro-batches."
- Mechanism: The model processes a micro-batch, calculates gradients, but does not update the weights. It simply adds (accumulates) these gradients in a buffer. After several steps, the accumulated gradient is used to update the weights once.
- Variable Accumulation: The number of steps adjusts based on the sequence length to keep memory usage constant.
- CPU Offloading: Gradients are moved to system RAM (CPU) to free up high-speed GPU VRAM for the actual math operations.

**Activation Management**

This focuses on the "live" data generated during a forward pass.
- Partial Recomputation: Only the most complex parts of the transformer block (like the attention matrix) are recomputed, while simpler linear layers are stored.
- Activation Compression: Activations are temporarily quantized (e.g., from 16-bit to 4-bit) or pruned before being stored, then decompressed when needed for the backward pass.

**When to Use It**

- Limited Hardware Access: These optimizations are mandatory when fine-tuning a model (like Llama-3 70B) on a single GPU or a small cluster where the total weight and activation size exceed VRAM.
- Long-Context Fine-tuning: As sequence length increases, activation memory grows quadratically. Optimization is required to handle documents or conversations exceeding 4,000–8,000 tokens.
- Simulating Large Batch Sizes: When a project requires the stable convergence of a large batch (e.g., 128 or 256 samples) but the hardware can only fit 1 or 2 samples at a time.
- Edge Device Training: In scenarios involving on-device learning or "Edge AI," where memory is extremely constrained and power efficiency is balanced with compute cycles.
- Maximizing Throughput: When training on expensive cloud instances, using these techniques allows for higher utilization of the GPU’s compute cores by packing more data or larger models into the same memory space.

**Reference** 
- [Arxiv:Practical tradeoffs between memory, compute, and performance in learned optimizers](https://arxiv.org/abs/2203.11860)
- [Medium:Efficient LLM Training: Memory & Compute Optimization](http://medium.com/@ak16425/efficient-llm-training-memory-compute-optimization-f1aae81c83f4)
- [ACM:MemoriaNova: Optimizing Memory-Aware Model Inference for Edge Computing](https://dl.acm.org/doi/10.1145/3701997)
- [Nvidia:Mastering LLM Techniques: Inference Optimization](https://developer.nvidia.com/blog/mastering-llm-techniques-inference-optimization/)

## Gradient and Activation Management

### Gradient Checkpointing: Selective Checkpointing

Selective Gradient Checkpointing is a memory optimization strategy that intelligently chooses which intermediate activations to save and which to discard during the forward pass. While standard gradient checkpointing usually discards all activations between "checkpoints" (typically the start of a transformer layer), selective checkpointing targets only the most memory-intensive activations—such as those from the attention mechanism—while retaining smaller ones to minimize the computational penalty of re-running calculations.

**How it Works**

During training, the "backward pass" needs the data generated during the "forward pass" to calculate gradients.
- Memory Bottleneck Identification: In LLMs, the Attention layers (specifically the $QK^T$ matrix) consume memory quadratically relative to sequence length. 
- The Feed-Forward (MLP) layers consume memory linearly.The Selective Choice: Instead of an "all or nothing" approach, selective checkpointing keeps the outputs of the MLP layers (which are cheap to store) but discards the massive attention activation matrices.
- On-Demand Recomputation: When the backward pass reaches an attention layer, the model re-runs only that specific attention calculation to get the necessary data.
- Result: This significantly reduces VRAM usage (often by 5x or more for long sequences) while being faster than "full" checkpointing because fewer layers need to be recomputed.

**Gradient Checkpointing Implementation**

The provided code enables the standard version of this feature within the Hugging Face Trainer ecosystem.
- Enabling the Feature: The line `gradient_checkpointing=True` in the TrainingArguments is the primary switch. It tells the Gemma model to trigger its internal `gradient_checkpointing_enable()` method.

    gradient_checkpointing=True,

- Layer-wise Implementation: Once enabled, the model stops storing activations for every single internal operation. For Gemma and similar architectures, the Trainer will treat the boundaries of each `GemmaDecoderLayer` as the checkpoints.
- Memory vs. Speed Trade-off: By enabling this, the script allows for the `per_device_train_batch_size=8` and `gradient_accumulation_steps=4`. Without this setting, the activations from 32 total samples (8 * 4) at a length of 128 tokens would likely exceed the VRAM of a standard consumer GPU.
- Note on Routing Optimization: The code does not perform Routing Optimization. It is a standard dense model script (Gemma 3). To perform Routing Optimization, the model would need to be a Mixture-of-Experts (MoE) model, and the code would need to freeze expert weights while unfreezing the router layers.

**When to Use It**

Selective Gradient Checkpointing is the preferred choice when:
- Sequence Length is High: When training on sequences longer than 2,048 tokens, where attention matrices become the dominant memory cost.
- VRAM is Extremely Limited: When attempting to fine-tune a model on a GPU with 8GB–16GB of memory where the model weights themselves already take up most of the space.
- Batch Size Needs to be Increased: If a project requires a larger micro-batch size to stabilize training or utilize more of the GPU's compute cores.
- Full Checkpointing is Too Slow: If standard gradient checkpointing is making training 30–50% slower, switching to a selective strategy (often provided by libraries like `FlashAttention or DeepSpeed`) can recover some of that speed by recomputing only the most "expensive" parts of the model.

In [ ]:
import torch
import transformers
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    DataCollatorForLanguageModeling,
    TrainingArguments,
    Trainer,
)
from datasets import DatasetDict, Dataset

In [10]:
MODEL_NAME = "google/gemma-3-270m"
OUTPUT_DIR = "./gemma-3-270m-finetuned-qa"

model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    torch_dtype=torch.float32,
)

data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

monitor = EpochMonitor(model=model)

import os
os.environ["ACCELERATE_USE_DEEPSPEED"] = "false"

training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    gradient_accumulation_steps=4,
    learning_rate=2e-5,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_strategy="epoch",
    run_name="gemma-3-270m-qa",
    warmup_steps=100,
    lr_scheduler_type="cosine",
    fp16=True,
    optim="paged_adamw_8bit",
    gradient_checkpointing=True,
    deepspeed=None,  # Explicitly disable DeepSpeed
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
    callbacks = [monitor]
)

train_result = trainer.train()
trainer.save_model()
tokenizer.save_pretrained(OUTPUT_DIR)

Loading weights:   0%|          | 0/236 [00:00<?, ?it/s]

Initial Model Memory Footprint:
  Parameters: 268,098,176
  Precision: 4 bytes
  Total Memory: 3.81 GB
    - Parameters: 1.00 GB
    - KV Cache (est): 2.81 GB
  Estimated FLOPs per forward pass (batch=8, seq=512): 2.05 TFLOPS

============================================================
Epoch 0 Summary
============================================================
  Duration (s)         :        34.41
  Tokens Processed     :      172,032
  Throughput (token/s) :         4999
  Training Steps       :           42
  Avg CPU (%)          :         17.6
  Avg Memory (%)       :         10.0
  Total FLOPs          : 86.14 TFLOPS
  TFLOPS (per second)  :         2.50
  FLOPs (per token)    :  0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================
Epoch 1 Summary
============================================================
  Duration (s)         :        35.04
  Tokens Processed     :      172,032
  Throughput (token/s) :         4910
  Training Steps       :           42
  Avg CPU (%)          :         19.2
  Avg Memory (%)       :         13.4
  Total FLOPs          : 86.14 TFLOPS
  TFLOPS (per second)  :         2.46
  FLOPs (per token)    :  0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================
Epoch 2 Summary
============================================================
  Duration (s)         :        35.19
  Tokens Processed     :      172,032
  Throughput (token/s) :         4889
  Training Steps       :           42
  Avg CPU (%)          :         18.3
  Avg Memory (%)       :         13.4
  Total FLOPs          : 86.14 TFLOPS
  TFLOPS (per second)  :         2.45
  FLOPs (per token)    :  0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['lm_head.weight'].

============================================================
TRAINING COMPLETE
============================================================
Total Training Time: 124.28s
Total Epochs: 3
Average Epoch Time: 34.88s
Total Tokens Processed: 516,096
Average Throughput: 4153 tokens/second
Total FLOPs: 258.41 TFLOPS
Average TFLOPS (per second): 2.08
Overall FLOPs (per token): 0.50 GFLOPS

Final Metrics:
Memory Footprint: 3.81 GB
Inference Throughput: 4984 tokens/second
Total Training FLOPs: 86.14 TFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

('./gemma-3-270m-finetuned-qa/tokenizer_config.json',
 './gemma-3-270m-finetuned-qa/tokenizer.json')

In [11]:
summarize_training_results(trainer, monitor)

====================================================================================================
TRAINING RESULTS SUMMARY TABLE
====================================================================================================
Epoch Training Loss Validation Loss Time (s) Tokens Processed Throughput (token/s) TFLOPS (per second) Avg CPU (%) Avg Memory (%) Training Steps
    0        2.9314          3.0835    34.41          172,032                 4999                2.50        17.6           10.0             42
    1        1.7751          3.9342    35.04          172,032                 4910                2.46        19.2           13.4             42
    2        0.8155          5.0601    35.19          172,032                 4888                2.45        18.3           13.4             42

----------------------------------------------------------------------------------------------------
TRAINING STATISTICS:
----------------------------------------------------------------------------------------------------
Total Training Time:      104.6 s
Average Epoch Time:       34.9 s
Total Tokens Processed:   516,096
Average Throughput:       4932 tokens/second
Average CPU Usage:        18.4%
Average Memory Usage:     12.3%
Total Training FLOPs:     258.41 TFLOPS
Average TFLOPS (per sec): 2.47
Overall FLOPs (per token): 0.50 GFLOPS

====================================================================================================

**Reference** 
- [Arxiv:Optimal Gradient Checkpoint Search for Arbitrary Computation Graphs](https://arxiv.org/abs/1808.00079)
- [Huggingface:Performance and Scalability](https://huggingface.co/docs/transformers/v4.23.1/en/performance)
- [APXML:Practice: Implementing Gradient Checkpointing](https://apxml.com/courses/advanced-jax/chapter-6-large-scale-model-training-jax/practice-gradient-checkpointing)
- [PyTorch:torch.utils.checkpoint](https://docs.pytorch.org/docs/stable/checkpoint.html)

### Gradient Accumulation: Variable Accumulation Steps

Variable Gradient Accumulation is an advanced optimization strategy that dynamically adjusts the number of micro-batches processed before updating model weights. While standard gradient accumulation uses a fixed number of steps to simulate a larger batch size, the variable approach monitors system resource constraints (like VRAM) in real-time. This allows the training process to remain stable and avoid "Out of Memory" (OOM) errors even when encountering data samples of varying lengths or complexity.

**How it Works**

Standard Gradient Accumulation calculates gradients for multiple small micro-batches and sums them up. Only after a predefined number of steps does the optimizer update the weights. Variable Accumulation adds a logic layer to this:
- Resource Monitoring: The system continuously tracks GPU memory allocation or sequence length for the current batch.
- Threshold Logic: If memory usage crosses a safe threshold (e.g., 85% of VRAM), the system increases the accumulation steps and reduces the micro-batch size (if possible) to prevent a crash.
- Dynamic Throughput: When memory is plentiful, it reduces accumulation steps to speed up the weight update frequency, maximizing hardware utilization.
- Mathematical Consistency: To maintain the "Effective Batch Size," the system tries to balance the relationship:

        EffectiveBatchSize=BatchSize×AccumulationSteps


**Variable Gradient Accumulation Implementation**

The provided code implements this logic via a custom `TrainerCallback`. It injects monitoring code into the training loop of the Hugging Face Trainer.
- The Monitoring Class (`VariableGradientAccumulationCallback`): This class is initialized with a `memory_threshold` (0.8 or 80%).
- Real-time Memory Check: `Inside on_step_begin`, the code calculates the ratio of currently used memory to the maximum memory ever allocated:

        memory_used = torch.cuda.memory_allocated() / torch.cuda.max_memory_allocated()

- Adaptive Step Adjustment: The logic checks if the usage exceeds the threshold. If the GPU is nearing its limit, it doubles the `gradient_accumulation_steps` (capping it at 16) to process smaller chunks of data more carefully. If memory is safe, it reverts to the `base_steps`.
- State Injection: Because args (`TrainingArguments`) are passed by reference, modifying `args.gradient_accumulation_steps` directly inside the callback changes how the Trainer behaves for the very next step without needing to restart the training.

**When to Use It**

Variable Gradient Accumulation is highly effective in the following scenarios:
- Variable Sequence Lengths: When training on datasets where some examples are very short (e.g., 128 tokens) and others are very long (e.g., 4096 tokens). The system can use fewer accumulation steps for short text and increase them automatically for long text.
- Shared Infrastructure: If training on a GPU that is occasionally used by other processes, the variable steps can help the training "shrink" its memory footprint when VRAM becomes tight.
- Preventing OOM at Peak Usage: Some layers (like Softmax or specific MoE routers) cause sudden spikes in memory. This optimization acts as a safety net that catches these spikes before they cause a crash.
- Optimizing for Time-to-Convergence: By using the smallest stable number of accumulation steps whenever possible, the model updates its weights more frequently, which can sometimes lead to faster convergence in the early stages of training.

In [ ]:
import torch
import transformers
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    DataCollatorForLanguageModeling,
    TrainingArguments,
    Trainer,
)
from datasets import DatasetDict, Dataset
from transformers.trainer_callback import TrainerCallback

In [12]:
class VariableGradientAccumulationCallback(TrainerCallback):
    def __init__(self, base_steps=1, memory_threshold=0.85):
        self.base_steps = base_steps
        self.memory_threshold = memory_threshold
    
    def on_step_begin(self, args, state, control, **kwargs):
        if torch.cuda.is_available():
            memory_used = torch.cuda.memory_allocated() / torch.cuda.max_memory_allocated()
            
            if memory_used > self.memory_threshold:
                args.gradient_accumulation_steps = min(self.base_steps * 2, 16)
            else:
                args.gradient_accumulation_steps = self.base_steps
            
            if state.global_step % 50 == 0:
                print(f"Step {state.global_step}: Memory used {memory_used:.2%}, "
                      f"Accumulation steps: {args.gradient_accumulation_steps}")

MODEL_NAME = "google/gemma-3-270m"
OUTPUT_DIR = "./gemma-3-270m-finetuned-qa"
MAX_LENGTH = 128

model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    device_map="auto",
    torch_dtype=torch.float32,
    low_cpu_mem_usage=True,
)

data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

monitor = EpochMonitor(model=model)

variable_accum_callback = VariableGradientAccumulationCallback(base_steps=2, memory_threshold=0.8)

training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=4,
    per_device_eval_batch_size=4,
    gradient_accumulation_steps=2,
    learning_rate=2e-5,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_strategy="epoch",
    run_name="gemma-3-270m-qa",
    warmup_ratio=0.1,
    lr_scheduler_type="cosine",
    fp16=True,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
    callbacks=[variable_accum_callback, monitor],
)

total_params = sum(p.numel() for p in model.parameters())
trainable_params = total_params

train_result = trainer.train()

trainer.save_model()
tokenizer.save_pretrained(OUTPUT_DIR)

Loading weights:   0%|          | 0/236 [00:00<?, ?it/s]

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Initial Model Memory Footprint:
  Parameters: 268,098,176
  Precision: 4 bytes
  Total Memory: 3.81 GB
    - Parameters: 1.00 GB
    - KV Cache (est): 2.81 GB
  Estimated FLOPs per forward pass (batch=8, seq=512): 2.05 TFLOPS
Step 0: Memory used 30.42%, Accumulation steps: 2

Step 50: Memory used 50.72%, Accumulation steps: 2
Step 100: Memory used 50.72%, Accumulation steps: 2
Step 150: Memory used 50.72%, Accumulation steps: 2

============================================================
Epoch 0 Summary
============================================================
  Duration (s)         :         44.44
  Tokens Processed     :       342,016
  Throughput (token/s) :          7696
  Training Steps       :           167
  Avg CPU (%)          :          16.0
  Avg Memory (%)       :          14.1
  Total FLOPs          : 171.25 TFLOPS
  TFLOPS (per second)  :          3.85
  FLOPs (per token)    :   0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Step 200: Memory used 50.72%, Accumulation steps: 2
Step 250: Memory used 50.72%, Accumulation steps: 2
Step 300: Memory used 50.72%, Accumulation steps: 2

============================================================
Epoch 1 Summary
============================================================
  Duration (s)         :         44.83
  Tokens Processed     :       342,016
  Throughput (token/s) :          7629
  Training Steps       :           167
  Avg CPU (%)          :          17.3
  Avg Memory (%)       :          14.1
  Total FLOPs          : 171.25 TFLOPS
  TFLOPS (per second)  :          3.82
  FLOPs (per token)    :   0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Step 350: Memory used 50.72%, Accumulation steps: 2
Step 400: Memory used 50.72%, Accumulation steps: 2
Step 450: Memory used 50.72%, Accumulation steps: 2
Step 500: Memory used 50.72%, Accumulation steps: 2

============================================================
Epoch 2 Summary
============================================================
  Duration (s)         :         44.88
  Tokens Processed     :       342,016
  Throughput (token/s) :          7620
  Training Steps       :           167
  Avg CPU (%)          :          17.2
  Avg Memory (%)       :          14.1
  Total FLOPs          : 171.25 TFLOPS
  TFLOPS (per second)  :          3.82
  FLOPs (per token)    :   0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['lm_head.weight'].

============================================================
TRAINING COMPLETE
============================================================
Total Training Time: 159.53s
Total Epochs: 3
Average Epoch Time: 44.72s
Total Tokens Processed: 1,026,048
Average Throughput: 6432 tokens/second
Total FLOPs: 513.74 TFLOPS
Average TFLOPS (per second): 3.22
Overall FLOPs (per token): 0.50 GFLOPS

Final Metrics:
Memory Footprint: 3.81 GB
Inference Throughput: 9435 tokens/second
Total Training FLOPs: 171.25 TFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

('./gemma-3-270m-finetuned-qa/tokenizer_config.json',
 './gemma-3-270m-finetuned-qa/tokenizer.json')

In [13]:
summarize_training_results(trainer, monitor)

====================================================================================================
TRAINING RESULTS SUMMARY TABLE
====================================================================================================
Epoch Training Loss Validation Loss Time (s) Tokens Processed Throughput (token/s) TFLOPS (per second) Avg CPU (%) Avg Memory (%) Training Steps
    0        1.8033          4.3089    44.44          342,016                 7696                3.85        16.0           14.1            167
    1        0.6773          5.6210    44.83          342,016                 7629                3.82        17.3           14.1            167
    2        0.4541          6.0853    44.88          342,016                 7620                3.82        17.2           14.1            167

----------------------------------------------------------------------------------------------------
TRAINING STATISTICS:
----------------------------------------------------------------------------------------------------
Total Training Time:      134.2 s
Average Epoch Time:       44.7 s
Total Tokens Processed:   1,026,048
Average Throughput:       7648 tokens/second
Average CPU Usage:        16.8%
Average Memory Usage:     14.1%
Total Training FLOPs:     513.74 TFLOPS
Average TFLOPS (per sec): 3.83
Overall FLOPs (per token): 0.50 GFLOPS

====================================================================================================

**Reference** 
- [Arxiv:Layered gradient accumulation and modular pipeline parallelism: fast and efficient training of large language models](https://arxiv.org/abs/2106.02679)
- [Arxiv:Small Batch Size Training for Language Models: When Vanilla SGD Works, and Why Gradient Accumulation Is Wasteful](https://arxiv.org/abs/2507.07101)
- [Huggingface:Performing gradient accumulation with Accelerate](https://huggingface.co/docs/accelerate/en/usage_guides/gradient_accumulation)
- [APXML:Gradient Clipping and Accumulation](https://apxml.com/courses/advanced-pytorch/chapter-3-optimization-training-strategies/gradient-clipping-accumulation)

### Activation Management: Activation Compression (Quantization)

Activation Management with Compression is a resource-level optimization that reduces the memory footprint of the intermediate data generated during a model's forward pass. While weight quantization (like 4-bit) shrinks the model itself, activation compression targets the "hidden states" that must be stored in VRAM to calculate gradients during the backward pass. By quantizing, pruning, or offloading these transient tensors, the system can handle much larger batch sizes or longer sequences than the physical GPU memory would normally allow.

**How it Works**

Activation management intervenes at the moment a layer finishes its calculation and prepares to save its output for the training step's backward phase.
- Quantization: High-precision activation tensors (typically 16-bit) are converted to lower precision (8-bit integers). This immediately cuts the storage requirement for those activations in half.
- Pruning: Many values in activation tensors are near zero and contribute very little to the final gradient. Pruning identifies these values based on a threshold and converts the tensor into a "sparse" format, storing only the most important data points.
- Offloading: Instead of keeping every intermediate result in expensive GPU VRAM, the system "packs" the compressed data and moves it to system RAM (CPU). When the backward pass begins, the data is "unpacked" and moved back to the GPU just in time for the specific layer calculation.

**Activation Compression Implementation**

The provided script uses advanced PyTorch Autograd Hooks to intercept how tensors are saved and retrieved.

**The Hook Mechanism (`saved_tensors_hooks`):**

The ActivationCompressionTrainer wraps the loss calculation inside a context manager. This ensures that every time the model tries to "save" a tensor for later, it must pass through the pack_hook.

    with torch.autograd.graph.saved_tensors_hooks(self.compression_hook.pack_hook, ...):
        outputs = model(**inputs)

8-bit Quantization (`quantize_tensor`): The code calculates a scale and zero-point for each activation tensor, converts it to torch.uint8, and stores it as a compact tuple.

**Threshold-based Pruning (prune_tensor):**

If a tensor has many values below 1e-4, the code uses `torch.nonzero` to find important indices and only saves those values, discarding the "noise."

**CPU Offloading:**

The `pack_hook` explicitly calls `.cpu()` on the compressed tensors. This moves the bulk of the training memory burden from the GPU to the (usually larger) system RAM.

**Symmetry:**

When the backward pass needs the data, the `unpack_hook` reverses these steps—moving the data back to the GPU, dequantizing it to the original dtype, and expanding pruned values back into a full-sized tensor.

**When to Use It**

- Massive Batch Sizes on Small GPUs: When a task requires a large batch size (e.g., for contrastive learning) that would normally lead to an "Out of Memory" error even with 4-bit weights.
- Extreme Context Lengths: When processing very long documents where the activation memory grows significantly along the sequence dimension.
- Limited VRAM / High CPU RAM: In systems where the GPU is small (e.g., 12GB or 16GB) but the host machine has a large amount of system memory (e.g., 64GB or 128GB).
- Researching Activation Sparsity: When trying to understand which parts of a model's activations are most critical for learning, as pruning provides a direct look at the importance of different features.
- Alternative to Gradient Checkpointing: Use this when you have enough CPU RAM to store activations but want to avoid the extra compute time required to re-run layers (which standard checkpointing would require).

In [ ]:
import torch
import torch.nn as nn
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    DataCollatorForLanguageModeling,
    TrainingArguments,
    Trainer,
    BitsAndBytesConfig,
    TrainerCallback
)
from peft import LoraConfig, get_peft_model, TaskType  # <-- IMPORTANT: Import PEFT
from datasets import DatasetDict, Dataset
import gc
import os

In [11]:
# Configuration
MODEL_NAME = "google/gemma-3-270m-it"
OUTPUT_DIR = "./gemma-3-270m-finetuned-qa-activation-compressed"
MAX_LENGTH = 128
os.makedirs(OUTPUT_DIR, exist_ok=True)

# Tokenizer
print(f"Loading tokenizer: {MODEL_NAME}")
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"
print(f"Tokenizer loaded. Vocab size: {len(tokenizer)}")

# Tokenization Function
def tokenize_examples(df, max_length=MAX_LENGTH):
    texts = [
        f"Question: {row['question_title']}\n{row['question_body']}\nAnswer: {row['answer']}"
        for row in df.iter_rows(named=True)
    ]
    tokenized = tokenizer(
        texts,
        truncation=True,
        max_length=max_length,
        padding="max_length",
        return_tensors="pt"
    )
    tokenized["labels"] = tokenized["input_ids"].clone()
    tokenized["labels"][tokenized["labels"] == tokenizer.pad_token_id] = -100
    return tokenized

# Load and Tokenize Dataset 
print("Tokenizing datasets...")
train_tokenized = tokenize_examples(train_data)
val_tokenized = tokenize_examples(val_data)

dataset_dict = DatasetDict({
    "train": Dataset.from_dict(train_tokenized),
    "validation": Dataset.from_dict(val_tokenized)
})

print(f"Train examples: {len(dataset_dict['train']):,}")
print(f"Validation examples: {len(dataset_dict['validation']):,}")

# OPTIMIZATION 1: 4-bit Quantization
print("\nConfiguring 4-bit quantization...")
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.bfloat16,
    bnb_4bit_use_double_quant=True,
)

print(f"Loading {MODEL_NAME} with 4-bit quantization...")
base_model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    quantization_config=bnb_config,
    device_map="auto",
    torch_dtype=torch.bfloat16,
    attn_implementation="eager",
)

# OPTIMIZATION 2: Attach LoRA Adapters 
# This is the crucial fix: adding trainable adapters on top of the quantized model.
print("\nAttaching LoRA adapters for fine-tuning...")
lora_config = LoraConfig(
    task_type=TaskType.CAUSAL_LM,
    r=8,
    lora_alpha=16,
    lora_dropout=0.05,
    target_modules=["q_proj", "v_proj", "k_proj", "o_proj"],
)
model = get_peft_model(base_model, lora_config)
model.print_trainable_parameters()

# OPTIMIZATION 3: Activation Compression
class ActivationCompressionHook:
    """
    Hook for compressing activations during training using saved_tensors_hooks.
    """
    def __init__(self, offload_to_cpu=True, quantize_activations=True, prune_threshold=1e-4):
        self.offload_to_cpu = offload_to_cpu
        self.quantize_activations = quantize_activations
        self.prune_threshold = prune_threshold

    def pack_hook(self, tensor):
        """Compress activations before saving for backward pass."""
        if not tensor.requires_grad:
            return tensor

        compressed = tensor

        if self.offload_to_cpu:
            compressed = compressed.cpu()

        if self.quantize_activations and tensor.numel() > 1000:
            compressed = self.quantize_tensor(compressed)

        if self.prune_threshold > 0 and isinstance(compressed, torch.Tensor) and tensor.numel() > 1000:
            compressed = self.prune_tensor(compressed)

        return compressed

    def unpack_hook(self, packed):
        """Restore compressed activations for backward pass."""
        if isinstance(packed, torch.Tensor):
            tensor = packed
        else:
            if isinstance(packed, tuple) and len(packed) == 5:
                quantized, scale, zero_point, shape, dtype = packed
                tensor = self.dequantize_tensor(quantized, scale, zero_point, shape, dtype)
            elif isinstance(packed, tuple) and len(packed) == 4:
                indices, values, shape, dtype = packed
                tensor = self.deprune_tensor(indices, values, shape, dtype)
            else:
                tensor = packed

        if self.offload_to_cpu and isinstance(tensor, torch.Tensor):
            device = torch.cuda.current_device() if torch.cuda.is_available() else 'cpu'
            tensor = tensor.to(device)

        return tensor

    def quantize_tensor(self, tensor):
        """Quantize tensor to 8-bit with scaling factors."""
        if tensor.dtype == torch.bfloat16 or tensor.dtype == torch.float32:
            tensor_min = tensor.min()
            tensor_max = tensor.max()

            if tensor_max - tensor_min > 1e-8:
                scale = 255.0 / (tensor_max - tensor_min)
                zero_point = -tensor_min * scale
                quantized = torch.round(scale * tensor + zero_point).to(torch.uint8)
                return (quantized.cpu(), scale, zero_point, tensor.shape, tensor.dtype)
        return tensor

    def dequantize_tensor(self, quantized, scale, zero_point, shape, dtype):
        """Dequantize tensor from 8-bit representation."""
        dequantized = (quantized.float() - zero_point) / scale
        return dequantized.reshape(shape).to(dtype)

    def prune_tensor(self, tensor):
        """Prune near-zero values to reduce memory."""
        if tensor.numel() > 1000:
            mask = torch.abs(tensor) > self.prune_threshold
            if mask.sum() < tensor.numel() * 0.3:
                indices = torch.nonzero(mask, as_tuple=True)
                values = tensor[mask].cpu()
                return (indices, values, tensor.shape, tensor.dtype)
        return tensor

    def deprune_tensor(self, indices, values, shape, dtype):
        """Restore pruned tensor from sparse representation."""
        tensor = torch.zeros(shape, dtype=dtype)
        tensor[indices] = values
        return tensor

compression_hook = ActivationCompressionHook(
    offload_to_cpu=True,
    quantize_activations=True,
    prune_threshold=1e-4
)

print("\nApplying activation compression:")
print("  - Activation offloading to CPU")
print("  - 8-bit activation quantization")
print("  - Activation pruning (threshold: 1e-4)")

# OPTIMIZATION 4: 8-bit Optimizer
print("\nUsing 8-bit AdamW optimizer (via 'adamw_8bit' in TrainingArguments).")

# Training Arguments
total_steps = len(dataset_dict["train"]) * 3 // (8 * 1)
warmup_steps = int(0.1 * total_steps)

monitor = EpochMonitor(model=model)

training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    gradient_accumulation_steps=1,
    learning_rate=2e-5,
    weight_decay=0.01,
    max_grad_norm=1.0,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_steps=50,
    warmup_steps=warmup_steps,
    lr_scheduler_type="cosine",
    bf16=True,
    optim="adamw_8bit",  # Enables 8-bit optimizer
    gradient_checkpointing=False,
    dataloader_num_workers=2,
    ddp_find_unused_parameters=False if torch.cuda.device_count() > 1 else None,
)

# Custom Trainer with Compression 
class ActivationCompressionTrainer(Trainer):
    def __init__(self, compression_hook, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.compression_hook = compression_hook

    def compute_loss(self, model, inputs, return_outputs=False, num_items_in_batch=None):
        with torch.autograd.graph.saved_tensors_hooks(
            self.compression_hook.pack_hook,
            self.compression_hook.unpack_hook
        ):
            outputs = model(**inputs)
            loss = outputs.loss
        return (loss, outputs) if return_outputs else loss

# Trainer 
trainer = ActivationCompressionTrainer(
    compression_hook=compression_hook,
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False),
    callbacks=[monitor],
)

# Model Statistics
total_params = sum(p.numel() for p in model.parameters())
trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)

print(f"\nModel Statistics:")
print(f"  Total parameters: {total_params:,}")
print(f"  Trainable parameters: {trainable_params:,}")
print(f"  Trainable percentage: {(trainable_params / total_params * 100):.2f}%")

# Train 

print(f"\n{'='*60}")
print("STARTING TRAINING WITH ACTIVATION COMPRESSION")
print(f"{'='*60}")
print(f"Weight Quantization: 4-bit (NF4)")
print(f"Trainable Adapters: LoRA attached")
print(f"Activation Offloading: Enabled")
print(f"Activation Quantization: 8-bit")
print(f"Activation Pruning: Enabled (threshold: 1e-4)")
print(f"Optimizer: 8-bit AdamW")
print(f"{'='*60}\n")

train_result = trainer.train()

# Save
print("\nSaving model and tokenizer...")
model.save_pretrained(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)

print(f"\n{'='*60}")
print("TRAINING COMPLETED SUCCESSFULLY!")
print(f"{'='*60}")
print(f"Model saved to: {OUTPUT_DIR}")
print(f"Final train loss: {train_result.training_loss:.4f}")

Loading tokenizer: google/gemma-3-270m-it
Tokenizer loaded. Vocab size: 262145
Tokenizing datasets...

`torch_dtype` is deprecated! Use `dtype` instead!

Train examples: 1,331
Validation examples: 285

Configuring 4-bit quantization...
Loading google/gemma-3-270m-it with 4-bit quantization...

Loading weights:   0%|          | 0/236 [00:00<?, ?it/s]

Attaching LoRA adapters for fine-tuning...
trainable params: 737,280 || all params: 268,835,456 || trainable%: 0.2742

Applying activation compression:
  - Activation offloading to CPU
  - 8-bit activation quantization
  - Activation pruning (threshold: 1e-4)

Using 8-bit AdamW optimizer (via 'adamw_8bit' in TrainingArguments).

Model Statistics:
  Total parameters: 218,700,416
  Trainable parameters: 737,280
  Trainable percentage: 0.34%

============================================================
STARTING TRAINING WITH ACTIVATION COMPRESSION
============================================================
Weight Quantization: 4-bit (NF4)
Trainable Adapters: LoRA attached
Activation Offloading: Enabled
Activation Quantization: 8-bit
Activation Pruning: Enabled (threshold: 1e-4)
Optimizer: 8-bit AdamW
============================================================

Initial Model Memory Footprint:
  Parameters: 218,700,416
  Precision: 2 bytes
  Total Memory: 1.81 GB
    - Parameters: 0.41 GB
    - KV Cache (est): 1.41 GB
  Estimated FLOPs per forward pass (batch=8, seq=512): 2.05 TFLOPS

============================================================
Epoch 0 Summary
============================================================
  Duration (s)         :       1316.73
  Tokens Processed     :       684,032
  Throughput (token/s) :           519
  Training Steps       :           167
  Avg CPU (%)          :          35.9
  Avg Memory (%)       :          14.0
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          0.26
  FLOPs (per token)    :   0.50 GFLOPS

============================================================
Epoch 1 Summary
============================================================
  Duration (s)         :       1299.05
  Tokens Processed     :       684,032
  Throughput (token/s) :           527
  Training Steps       :           167
  Avg CPU (%)          :          36.2
  Avg Memory (%)       :          15.8
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          0.26
  FLOPs (per token)    :   0.50 GFLOPS

============================================================
Epoch 2 Summary
============================================================
  Duration (s)         :       1399.72
  Tokens Processed     :       684,032
  Throughput (token/s) :           489
  Training Steps       :           167
  Avg CPU (%)          :          39.3
  Avg Memory (%)       :          15.7
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          0.24
  FLOPs (per token)    :   0.50 GFLOPS

============================================================
TRAINING COMPLETE
============================================================
Total Training Time: 4028.33s
Total Epochs: 3
Average Epoch Time: 1338.50s
Total Tokens Processed: 2,052,096
Average Throughput: 509 tokens/second
Total FLOPs: 1027.47 TFLOPS
Average TFLOPS (per second): 0.26
Overall FLOPs (per token): 0.50 GFLOPS

Final Metrics:
Memory Footprint: 1.81 GB
Inference Throughput: 510 tokens/second
Total Training FLOPs: 342.49 TFLOPS

Saving model and tokenizer...

============================================================
TRAINING COMPLETED SUCCESSFULLY!
============================================================
Model saved to: ./gemma-3-270m-finetuned-qa-activation-compressed
Final train loss: 3.4802

In [12]:
summarize_training_results(trainer, monitor)

====================================================================================================
TRAINING RESULTS SUMMARY TABLE
====================================================================================================
Epoch Training Loss Validation Loss Time (s) Tokens Processed Throughput (token/s) TFLOPS (per second) Avg CPU (%) Avg Memory (%) Training Steps
    0        3.9873          3.5948  1316.73          684,032                  519                0.26        35.9           14.0            167
    1        3.5155          3.5423  1299.05          684,032                  526                0.26        36.2           15.8            167
    2        3.4500          3.5345  1399.72          684,032                  488                0.24        39.3           15.7            167

----------------------------------------------------------------------------------------------------
TRAINING STATISTICS:
----------------------------------------------------------------------------------------------------
Total Training Time:      4015.5 s
Average Epoch Time:       1338.5 s
Total Tokens Processed:   2,052,096
Average Throughput:       511 tokens/second
Average CPU Usage:        37.1%
Average Memory Usage:     15.1%
Total Training FLOPs:     1027.47 TFLOPS
Average TFLOPS (per sec): 0.26
Overall FLOPs (per token): 0.50 GFLOPS

====================================================================================================

**Reference** 
- [Arxiv:TAH-QUANT: Effective Activation Quantization in Pipeline Parallelism over Slow Network](https://arxiv.org/abs/2506.01352)
- [Arxiv:AWQ: Activation-aware Weight Quantization for LLM Compression and Acceleration](https://arxiv.org/abs/2306.00978)
- [Huggingface:Quantization](https://huggingface.co/docs/transformers/en/main_classes/quantization)
- [Aclanthology:ATQ: Activation Transformation for Weight-Activation Quantization of Large Language Models](https://aclanthology.org/2024.findings-emnlp.1001.pdf)

## Optimizer State Optimization

Optimizer State Optimization is a memory management strategy that targets the largest (and often overlooked) consumer of VRAM during the training process: the optimizer's internal variables.

When using a standard optimizer like Adam, the hardware must store two "moments" (moving averages of gradients) for every single trainable parameter. In a 16-bit model, the optimizer states can consume up to four times more memory than the model weights themselves. Optimization reduces this burden by compressing these states or moving them out of the GPU's high-speed memory.

**8-bit Optimizers**

Standard optimizers store states in 32-bit precision to maintain numerical stability. 8-bit optimizers compress these values, drastically reducing the memory footprint.
- AdamW8bit / Lion8bit: These are drop-in replacements for standard optimizers. They use block-wise quantization to maintain accuracy while using only 25% of the memory typically required for optimizer states.
- Dynamic Quantization: This approach adjusts the precision of the optimizer states on the fly. If the gradients for a specific layer are very stable, the precision is lowered; if they are volatile, the precision is increased.
- Per-parameter Precision: Not all layers are equally sensitive. This strategy applies 8-bit precision to large, stable matrices (like MLP layers) while keeping critical layers (like embedding or head layers) in 32-bit.

**Optimizer State Partitioning and Offloading**

These techniques focus on where the memory is stored rather than just how it is compressed.
- ZeRO-Offload: Part of the Zero Redundancy Optimizer (ZeRO) family, this moves the optimizer states and the gradient updates from the GPU to the CPU RAM. Since CPU RAM is usually much larger and cheaper, this allows for training massive models on a single GPU.
- Optimizer State Sharding (ZeRO-1/2): In multi-GPU setups, instead of every GPU keeping a full copy of the optimizer states, the states are "sharded" across the cluster. Each GPU only tracks and updates its own assigned portion of the parameters.
- Delayed Optimizer Updates: By accumulating gradients over many steps and updating the weights less frequently, the model can reduce the computational overhead associated with managing complex optimizer states, though this is primarily a compute-saving tactic.

**When to Use It**

Optimizer State Optimization is a "must-use" in the following scenarios:
- Fine-tuning Large Models on Consumer GPUs: If the goal is to fine-tune a 7B or 13B parameter model on a single 24GB GPU (like an RTX 4090), the optimizer states alone would usually cause a crash. Using AdamW8bit is often the difference between a successful run and an "Out of Memory" error.
- Training with "Full" Parameters: If LoRA or other PEFT techniques are not an option and every parameter must be updated, these optimizations are the only way to fit the training overhead into VRAM.
- Maximizing Batch Size: Even if a model fits in memory, optimizer state optimization frees up enough VRAM to significantly increase the batch size, which can lead to more stable training and better hardware utilization.
- Limited Multi-GPU Interconnect: If the connection between GPUs is slow, ZeRO-Offload can be more efficient than complex sharding because it relies on the faster PCIe connection to the CPU rather than the network connection between cards.

**Reference** 
- [Medium:Study of Optimizations for Fine-tuning LLMs](https://medium.com/@techsachin/study-of-optimizations-for-fine-tuning-llms-2ccba350c511)
- [Medium:Optimization Fundamentals for Training Large Language Models](https://pub.towardsai.net/optimization-fundamentals-for-training-large-language-models-c1eb2a61a88a)
- [ACM:A survey of optimization modeling meets LLMs: progress and future directions](https://dl.acm.org/doi/10.24963/ijcai.2025/1192)
- [APXML:Saving Model State (Weights, Optimizer States)](https://apxml.com/courses/how-to-build-a-large-language-model/chapter-19-checkpointing-fault-tolerance/saving-model-state)
- [Efficient Deep Learning: A Comprehensive Overview of Optimization Techniques](https://huggingface.co/blog/Isayoften/optimization-rush)
- [PyTorch:torch.optim](https://docs.pytorch.org/docs/stable/optim.html)
- [Medium:Optimizers in Deep Learning](https://musstafa0804.medium.com/optimizers-in-deep-learning-7bf81fed78a0)

### 8-bit Optimizers

8-bit Optimizers are memory-efficient versions of standard optimization algorithms (like AdamW or Lion) that reduce the storage requirements for "optimizer states." In standard training, the optimizer must track two 32-bit floating-point values—the first moment (mean) and the second moment (variance) of the gradients—for every single trainable parameter. For large models, these states often consume significantly more VRAM than the model weights themselves. 8-bit optimizers compress these states into 8-bit integers, reducing the memory footprint by approximately 75% compared to standard 32-bit implementations.

**How it Works**

Standard AdamW stores moments in FP32 (32-bit) to preserve precision during small weight updates. 8-bit optimizers maintain high performance through Block-wise Quantization.
- Block-wise Division: The optimizer states (the moments) are divided into small blocks (e.g., 2048 elements).
- Dynamic Scaling: For each block, the system calculates a maximum absolute value (a scaling factor).
- Quantization: Every 32-bit value in the block is mapped to an 8-bit integer relative to that block's scale.
- Dequantization on the Fly: During the weight update step, the 8-bit values are temporarily converted back to higher precision, the update is calculated, and the updated moments are re-quantized back to 8-bit.
- Paged Memory (for "Paged" variants): Advanced versions like `paged_adamw_8bit` can offload these 8-bit states to CPU RAM if the GPU reaches capacity, acting as an extra safety net against "Out of Memory" errors.

**8-bit Optimizers Implementation**

The script utilizes the integration between the `bitsandbytes` library and the Hugging Face Trainer to activate these savings with a single configuration flag.

**Optimizer Selection:**

The line `optim="paged_adamw_8bit"` in the `TrainingArguments` is the core optimization.

                optim="paged_adamw_8bit",

This instructs the Trainer to swap the standard PyTorch `AdamW` (which uses FP32 states) for the `bitsandbytes` 8-bit implementation.

**Environment Configuration:** 

The script sets `os.environ["ACCELERATE_USE_DEEPSPEED"] = "false"`. This is done to ensure the Trainer uses the native `bitsandbytes` integration rather than attempting to pass optimizer control to `DeepSpeed`, which handles 8-bit states differently.

**Memory Coordination:**

By combining the 8-bit optimizer with `gradient_checkpointing=True`, the code effectively minimizes two of the three largest memory consumers: optimizer states and activations.

**Compatibility:**

Using `fp16=True` ensures the compute-heavy parts of the training happen in 16-bit, while the 8-bit optimizer manages the long-term storage of the moments.

**When to Use It**

8-bit Optimizers are a standard requirement in the following scenarios:
- Fine-tuning on Consumer GPUs: When training models with 7B parameters or more on GPUs with 24GB of VRAM or less. Without 8-bit optimization, the optimizer states alone can take up 14GB–28GB of VRAM for a 7B model.
- Full-Parameter Fine-tuning: If not using PEFT (LoRA), every parameter in the model is trainable. In this case, 8-bit optimizers are often the only way to fit the training state into memory.
- Maximizing Batch Size and Sequence Length: If the model fits in memory but the user wants to increase the batch size or double the sequence length, 8-bit optimizers free up the necessary VRAM to do so.
- Training Large MoE Models: Mixture-of-Experts models have a massive total parameter count. Even if only a few experts are active, the optimizer often still needs to track states for the entire model; 8-bit compression makes this manageable.

**AdamW-8bit (Implementation)**

In [ ]:
import torch
import transformers
import os
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    DataCollatorForLanguageModeling,
    TrainingArguments,
    Trainer,
)
from datasets import DatasetDict, Dataset

In [14]:
# Disable DeepSpeed to use paged_adamw_8bit optimizer
os.environ["ACCELERATE_USE_DEEPSPEED"] = "false"

MODEL_NAME = "google/gemma-3-270m"
OUTPUT_DIR = "./gemma-3-270m-finetuned-qa"

device = "cuda" if torch.cuda.is_available() else "cpu"

model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    torch_dtype=torch.float32,
    low_cpu_mem_usage=True,
)

model.to(device)

data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

monitor = EpochMonitor(model=model)

training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=2,
    per_device_eval_batch_size=2,
    gradient_accumulation_steps=1,
    learning_rate=2e-5,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_strategy="epoch",
    run_name="gemma-3-270m-qa",
    warmup_steps=100,
    lr_scheduler_type="cosine",
    fp16=True,
    optim="paged_adamw_8bit",
    gradient_checkpointing=True,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
    callbacks = [monitor]
)

train_result = trainer.train()
trainer.save_model()
tokenizer.save_pretrained(OUTPUT_DIR)

Loading weights:   0%|          | 0/236 [00:00<?, ?it/s]

Initial Model Memory Footprint:
  Parameters: 268,098,176
  Precision: 4 bytes
  Total Memory: 3.81 GB
    - Parameters: 1.00 GB
    - KV Cache (est): 2.81 GB
  Estimated FLOPs per forward pass (batch=8, seq=512): 2.05 TFLOPS

============================================================
Epoch 0 Summary
============================================================
  Duration (s)         :        142.65
  Tokens Processed     :       681,984
  Throughput (token/s) :          4781
  Training Steps       :           666
  Avg CPU (%)          :          21.1
  Avg Memory (%)       :          16.0
  Total FLOPs          : 341.47 TFLOPS
  TFLOPS (per second)  :          2.39
  FLOPs (per token)    :   0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================
Epoch 1 Summary
============================================================
  Duration (s)         :        143.39
  Tokens Processed     :       681,984
  Throughput (token/s) :          4756
  Training Steps       :           666
  Avg CPU (%)          :          22.9
  Avg Memory (%)       :          19.3
  Total FLOPs          : 341.47 TFLOPS
  TFLOPS (per second)  :          2.38
  FLOPs (per token)    :   0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================
Epoch 2 Summary
============================================================
  Duration (s)         :        144.35
  Tokens Processed     :       681,984
  Throughput (token/s) :          4724
  Training Steps       :           666
  Avg CPU (%)          :          24.0
  Avg Memory (%)       :          19.4
  Total FLOPs          : 341.47 TFLOPS
  TFLOPS (per second)  :          2.37
  FLOPs (per token)    :   0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['lm_head.weight'].

============================================================
TRAINING COMPLETE
============================================================
Total Training Time: 456.96s
Total Epochs: 3
Average Epoch Time: 143.47s
Total Tokens Processed: 2,045,952
Average Throughput: 4477 tokens/second
Total FLOPs: 1024.40 TFLOPS
Average TFLOPS (per second): 2.24
Overall FLOPs (per token): 0.50 GFLOPS

Final Metrics:
Memory Footprint: 3.81 GB
Inference Throughput: 4900 tokens/second
Total Training FLOPs: 341.47 TFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

('./gemma-3-270m-finetuned-qa/tokenizer_config.json',
 './gemma-3-270m-finetuned-qa/tokenizer.json')

In [15]:
summarize_training_results(trainer, monitor)

====================================================================================================
TRAINING RESULTS SUMMARY TABLE
====================================================================================================
Epoch Training Loss Validation Loss Time (s) Tokens Processed Throughput (token/s) TFLOPS (per second) Avg CPU (%) Avg Memory (%) Training Steps
    0        1.5640          4.9634   142.65          681,984                 4780                2.39        21.1           16.0            666
    1        0.6252          6.3169   143.39          681,984                 4756                2.38        22.9           19.3            666
    2        0.3454          7.0199   144.35          681,984                 4724                2.37        24.0           19.4            666

----------------------------------------------------------------------------------------------------
TRAINING STATISTICS:
----------------------------------------------------------------------------------------------------
Total Training Time:      430.4 s
Average Epoch Time:       143.5 s
Total Tokens Processed:   2,045,952
Average Throughput:       4754 tokens/second
Average CPU Usage:        22.7%
Average Memory Usage:     18.3%
Total Training FLOPs:     1024.40 TFLOPS
Average TFLOPS (per sec): 2.38
Overall FLOPs (per token): 0.50 GFLOPS

====================================================================================================

**Reference** 
- [Arxiv:8-bit Optimizers via Block-wise Quantization](https://arxiv.org/abs/2110.02861)
- [Huggingface:8-bit optimizers](https://huggingface.co/docs/bitsandbytes/en/optimizers)
- [Huggingface:Introduction: 8-bit optimizers](https://huggingface.co/docs/bitsandbytes/v0.43.0/optimizers)
- [OpenReview:Q-Adam-mini: Memory-Efficient 8-bit Quantized Optimizer for Large Language Model Training](https://openreview.net/forum?id=sa3uVJLEsR)

### Dynamic Quantization with Paged Optimizer

Dynamic Quantization in the context of optimizer states is an optimization technique that adjusts the numerical precision of the optimizer's memory (the moments) based on the statistical distribution of the gradients. Unlike static quantization, which forces all values into a fixed 8-bit or 4-bit range regardless of their importance, dynamic quantization recalculates scaling factors for every "block" of parameters at every training step. This ensures that the most critical updates retain high fidelity while less active parameters are compressed aggressively to save VRAM.

**How it Works**

The primary goal is to maintain the accuracy of 32-bit optimization while using the memory footprint of an 8-bit system.
- Block-wise Analysis: The optimizer divides the massive tensor of gradients and moments into small, manageable chunks (blocks of 2048 elements).
- Range Detection: For each individual block, the algorithm identifies the maximum absolute value (the outlier).
- Dynamic Scaling: A unique scale factor is generated for that specific block. This transforms the high-precision values into an 8-bit integer range (0-255) that best represents that specific block's data.
- Temporal Adaptation: Because gradients change as the model learns, these scales are recalculated at every step. If a layer suddenly becomes "noisier" during training, the dynamic scaling adjusts to prevent the information from being lost in the quantization noise.
- Dequantization for Updates: When it is time to apply the update to the model weights, the 8-bit values are temporarily expanded back to 16-bit or 32-bit, added to the weights, and then the updated moments are re-quantized for storage.

**Dynamic Quantization Implementation**

The provided code implements dynamic quantization through its use of the `bitsandbytes` optimizer integration.

**The Optimizer Flag:**

By setting `optim="paged_adamw_8bit"`, the code triggers the use of the `bitsandbytes AdamW` implementation. This specific optimizer is built entirely on the concept of dynamic block-wise quantization.

**Paged Memory Management:**

The "paged" part of the optimizer name indicates that if the dynamic scaling and 8-bit storage still result in VRAM pressure, the quantized states are "paged" (offloaded) to the CPU.

**Coordination with FP16:**

The code uses fp16=True. This means the model weights and the actual math of the forward/backward pass happen in 16-bit, while the "long-term memory" of the optimizer is managed by the 8-bit dynamic quantization logic.

**Model Agnostic:**

The code applies this to the `google/gemma-3-270m`. Because the optimizer wraps the model's parameters regardless of their internal architecture, the dynamic quantization automatically scales to handle Gemma’s specific attention and MLP layers.

**When to Use It**

Dynamic Quantization is best utilized in the following training scenarios:
- Training with High Gradient Variance: If the dataset is diverse (e.g., a mix of code, math, and creative writing), the gradients will have vastly different scales. Dynamic quantization ensures the "math" experts don't get drowned out by the "writing" experts.
- Preventing Training Divergence: In early stages of training (the warmup phase), gradients are often very large. Static quantization might clip these values and cause the model to crash. Dynamic quantization adapts to these spikes.
- Maximizing Memory Efficiency: When every megabyte of VRAM counts. It allows for the training of larger models on GPUs like the RTX 3060 (12GB) or 4060 Ti (16GB) where standard AdamW would be impossible.
- Fine-tuning Sensitive Models: Some models are highly sensitive to "optimizer noise." Dynamic quantization provides a safer middle ground between 32-bit (perfect but heavy) and static 8-bit (fast but potentially unstable).

In [ ]:
import torch
import transformers
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    DataCollatorForLanguageModeling,
    TrainingArguments,
    Trainer,
    BitsAndBytesConfig
)
from datasets import DatasetDict, Dataset

In [16]:
MODEL_NAME = "google/gemma-3-270m"
OUTPUT_DIR = "./gemma-3-270m-finetuned-qa"

model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    device_map="auto",
    torch_dtype=torch.float32,
    low_cpu_mem_usage=True,
)

data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

monitor = EpochMonitor(model=model)

training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=2,
    per_device_eval_batch_size=2,
    gradient_accumulation_steps=4,
    learning_rate=2e-5,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_strategy="epoch",
    run_name="gemma-3-270m-qa",
    warmup_ratio=0.1,
    lr_scheduler_type="cosine",
    fp16=True,
    optim="paged_adamw_8bit",
    gradient_checkpointing=True,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
    callbacks = [monitor]
)

train_result = trainer.train()
trainer.save_model()
tokenizer.save_pretrained(OUTPUT_DIR)

Loading weights:   0%|          | 0/236 [00:00<?, ?it/s]

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Initial Model Memory Footprint:
  Parameters: 268,098,176
  Precision: 4 bytes
  Total Memory: 3.81 GB
    - Parameters: 1.00 GB
    - KV Cache (est): 2.81 GB
  Estimated FLOPs per forward pass (batch=8, seq=512): 2.05 TFLOPS

============================================================
Epoch 0 Summary
============================================================
  Duration (s)         :       118.27
  Tokens Processed     :      171,008
  Throughput (token/s) :         1446
  Training Steps       :          167
  Avg CPU (%)          :         22.3
  Avg Memory (%)       :         19.9
  Total FLOPs          : 85.62 TFLOPS
  TFLOPS (per second)  :         0.72
  FLOPs (per token)    :  0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================
Epoch 1 Summary
============================================================
  Duration (s)         :       117.76
  Tokens Processed     :      171,008
  Throughput (token/s) :         1452
  Training Steps       :          167
  Avg CPU (%)          :         21.6
  Avg Memory (%)       :         23.2
  Total FLOPs          : 85.62 TFLOPS
  TFLOPS (per second)  :         0.73
  FLOPs (per token)    :  0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================
Epoch 2 Summary
============================================================
  Duration (s)         :       120.46
  Tokens Processed     :      171,008
  Throughput (token/s) :         1420
  Training Steps       :          167
  Avg CPU (%)          :         24.0
  Avg Memory (%)       :         23.2
  Total FLOPs          : 85.62 TFLOPS
  TFLOPS (per second)  :         0.71
  FLOPs (per token)    :  0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['lm_head.weight'].

============================================================
TRAINING COMPLETE
============================================================
Total Training Time: 381.87s
Total Epochs: 3
Average Epoch Time: 118.83s
Total Tokens Processed: 513,024
Average Throughput: 1343 tokens/second
Total FLOPs: 256.87 TFLOPS
Average TFLOPS (per second): 0.67
Overall FLOPs (per token): 0.50 GFLOPS

Final Metrics:
Memory Footprint: 3.81 GB
Inference Throughput: 1457 tokens/second
Total Training FLOPs: 85.62 TFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

('./gemma-3-270m-finetuned-qa/tokenizer_config.json',
 './gemma-3-270m-finetuned-qa/tokenizer.json')

In [17]:
summarize_training_results(trainer, monitor)

====================================================================================================
TRAINING RESULTS SUMMARY TABLE
====================================================================================================
Epoch Training Loss Validation Loss Time (s) Tokens Processed Throughput (token/s) TFLOPS (per second) Avg CPU (%) Avg Memory (%) Training Steps
    0        1.8628          4.2612   118.27          171,008                 1445                0.72        22.3           19.9            167
    1        0.6857          5.6685   117.76          171,008                 1452                0.73        21.6           23.2            167
    2        0.4548          6.0900   120.46          171,008                 1419                0.71        24.0           23.2            167

----------------------------------------------------------------------------------------------------
TRAINING STATISTICS:
----------------------------------------------------------------------------------------------------
Total Training Time:      356.5 s
Average Epoch Time:       118.8 s
Total Tokens Processed:   513,024
Average Throughput:       1439 tokens/second
Average CPU Usage:        22.6%
Average Memory Usage:     22.1%
Total Training FLOPs:     256.87 TFLOPS
Average TFLOPS (per sec): 0.72
Overall FLOPs (per token): 0.50 GFLOPS

====================================================================================================

**Reference** 
- [APXML:Paged Optimizers for Memory Efficiency](https://apxml.com/courses/lora-peft-efficient-llm-training/chapter-4-advanced-lora-variants/qlora-paged-optimizers)
- [ACM:Exploring Quantization Techniques for Large-Scale Language Models: Methods, Challenges and Future Directions](https://dl.acm.org/doi/full/10.1145/3689236.3695383)
- [Huggingface:8-bit optimizers](https://huggingface.co/docs/bitsandbytes/en/optimizers)
- [Huggingface:Introduction: 8-bit optimizers](https://huggingface.co/docs/bitsandbytes/v0.43.0/optimizers)
- [Arxiv:8-bit Optimizers via Block-wise Quantization](https://arxiv.org/abs/2110.02861)
- [Medium:[vLLM — Quantization] bitsandbytes: 8-bit Optimizers, LLM.int8(), QLoRA, and k-bit Inference Scaling Laws](https://medium.com/byte-sized-ai/vllm-quantization-bitsandbytes-efaec31f00df)

### Per-parameter Optimizer Precision

Per-parameter Optimizer Precision is a memory optimization strategy that assigns different numerical precisions to the optimizer states (moments) based on the specific role of the parameters in the model. In standard training, a single precision (like 32-bit) is applied to every weight in the network. However, certain parts of a Large Language Model—such as the input embeddings and the output head—are highly sensitive to rounding errors. This technique keeps these critical parameters in high precision (32-bit) while aggressively compressing the bulk of the model (like the hidden layers) into 8-bit precision to save VRAM.

**How it Works**

The technique leverages the fact that LLM layers are not equally important for numerical stability.
- Parameter Categorization: The model is scanned to identify different types of layers: Embeddings, Transformer Blocks (Attention/MLP), and the Language Modeling Head.
- Sensitivity Mapping: Small, high-impact layers (Embeddings and Head) are flagged for high precision. These layers often represent the "vocabulary" of the model; small errors here can lead to complete gibberish or incoherent text.
- Selective Compression: The Transformer blocks, which contain the vast majority of the parameters, are assigned a lower precision (8-bit). This is where the bulk of the memory savings occurs.
- Mixed-Precision Optimization: The optimizer maintains a "Mixed-State" buffer. During the update step, it handles the 32-bit updates for the head/embeddings and the quantized 8-bit updates for the core blocks simultaneously, ensuring the model's "brain" is compressed while its "senses" remain sharp.

**Per-parameter Optimizer Precision Implementation**

The provided code uses the bitsandbytes library to manually create "Optimizer Groups" with varying configurations.
- Group Sorting: The code iterates through `model.named_parameters()` and uses string matching to sort them into three specific lists: `embedding_params, head_params, and other_params`.
- Precision Targeting: In the `optimizer_groups` definition, the `other_params` (the bulk of the model) are explicitly assigned `"optim_bits": 8`. The embeddings and head groups do not have this flag, causing them to default to standard 32-bit precision.

        optimizer_groups = [
            {"params": embedding_params, ...}, # Defaults to 32-bit
            {"params": head_params, ...},      # Defaults to 32-bit
            {"params": other_params, ..., "optim_bits": 8}, # Forced to 8-bit
        ]

- Optimizer Injection: The code initializes a `bnb.optim.AdamW` with these groups. When the Trainer is created, the custom optimizer is passed into the optimizers argument as a tuple (optimizer, None). This tells the Hugging Face Trainer to bypass its default optimizer logic and use the manually configured per-parameter precision settings.
- Balanced Efficiency: By keeping the lm_head and embed in 32-bit, the script avoids the common "quantization collapse" seen in small models like Gemma-270m, where the vocabulary layers are too small to be compressed safely.

**When to Use It**

Per-parameter Optimizer Precision should be utilized in the following contexts:
- Fine-tuning Small Models: Smaller models (under 1B parameters) are statistically more sensitive to quantization noise. Keeping the input and output layers in high precision prevents the loss of fine-grained vocabulary knowledge.
- Vocab-Heavy Tasks: If the task involves very specific tokens (like medical codes or rare programming languages), the embedding layer must be precise. Selective precision ensures those tokens aren't "smudged" by 8-bit quantization.
- Stability in Deep Networks: In very deep models, gradient errors can accumulate across layers. Keeping the "entry" and "exit" points of the gradient flow in 32-bit acts as an anchor for numerical stability.
- Maximizing VRAM without Sacrifice: Use this when a standard 8-bit optimizer causes a drop in evaluation metrics. It provides the memory savings of an 8-bit optimizer for 95% of the model while maintaining the accuracy of 32-bit for the critical 5%.

In [ ]:
import torch
import transformers
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    DataCollatorForLanguageModeling,
    TrainingArguments,
    Trainer,
)
from datasets import DatasetDict, Dataset
import bitsandbytes as bnb

In [ ]:
MODEL_NAME = "google/gemma-3-270m"
OUTPUT_DIR = "./gemma-3-270m-finetuned-qa"

model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    device_map="auto",
    torch_dtype=torch.float32,
    low_cpu_mem_usage=True,
)

embedding_params = []
head_params = []
other_params = []

for name, param in model.named_parameters():
    if param.requires_grad:
        if "embed" in name:
            embedding_params.append(param)
        elif "lm_head" in name:
            head_params.append(param)
        else:
            other_params.append(param)

optimizer_groups = [
    {"params": embedding_params, "lr": 2e-5, "weight_decay": 0.01},
    {"params": head_params, "lr": 2e-5, "weight_decay": 0.01},
    {"params": other_params, "lr": 2e-5, "weight_decay": 0.01, "optim_bits": 8},
]

optimizer = bnb.optim.AdamW(
    optimizer_groups,
    lr=2e-5,
    betas=(0.9, 0.999),
    eps=1e-8,
    weight_decay=0.01,
    is_paged=True,
)

data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

monitor = EpochMonitor(model=model)

training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=2,
    per_device_eval_batch_size=2,
    gradient_accumulation_steps=4,
    learning_rate=2e-5,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_strategy="epoch",
    run_name="gemma-3-270m-qa",
    warmup_ratio=0.1,
    lr_scheduler_type="cosine",
    fp16=True,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
    optimizers=(optimizer, None),
    callbacks = [monitor]
)

train_result = trainer.train()
trainer.save_model()
tokenizer.save_pretrained(OUTPUT_DIR)

Loading weights:   0%|          | 0/236 [00:00<?, ?it/s]

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Initial Model Memory Footprint:
  Parameters: 268,098,176
  Precision: 4 bytes
  Total Memory: 3.81 GB
    - Parameters: 1.00 GB
    - KV Cache (est): 2.81 GB
  Estimated FLOPs per forward pass (batch=8, seq=512): 2.05 TFLOPS

============================================================
Epoch 0 Summary
============================================================
  Duration (s)         :        74.05
  Tokens Processed     :      171,008
  Throughput (token/s) :         2310
  Training Steps       :          167
  Avg CPU (%)          :         23.4
  Avg Memory (%)       :         22.8
  Total FLOPs          : 85.62 TFLOPS
  TFLOPS (per second)  :         1.16
  FLOPs (per token)    :  0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================
Epoch 1 Summary
============================================================
  Duration (s)         :        74.42
  Tokens Processed     :      171,008
  Throughput (token/s) :         2298
  Training Steps       :          167
  Avg CPU (%)          :         22.7
  Avg Memory (%)       :         27.3
  Total FLOPs          : 85.62 TFLOPS
  TFLOPS (per second)  :         1.15
  FLOPs (per token)    :  0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================
Epoch 2 Summary
============================================================
  Duration (s)         :        76.53
  Tokens Processed     :      171,008
  Throughput (token/s) :         2234
  Training Steps       :          167
  Avg CPU (%)          :         25.9
  Avg Memory (%)       :         27.3
  Total FLOPs          : 85.62 TFLOPS
  TFLOPS (per second)  :         1.12
  FLOPs (per token)    :  0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['lm_head.weight'].

============================================================
TRAINING COMPLETE
============================================================
Total Training Time: 255.02s
Total Epochs: 3
Average Epoch Time: 75.00s
Total Tokens Processed: 513,024
Average Throughput: 2012 tokens/second
Total FLOPs: 256.87 TFLOPS
Average TFLOPS (per second): 1.01
Overall FLOPs (per token): 0.50 GFLOPS

Final Metrics:
Memory Footprint: 3.81 GB
Inference Throughput: 2303 tokens/second
Total Training FLOPs: 85.62 TFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

('./gemma-3-270m-finetuned-qa/tokenizer_config.json',
 './gemma-3-270m-finetuned-qa/tokenizer.json')

In [19]:
summarize_training_results(trainer, monitor)

====================================================================================================
TRAINING RESULTS SUMMARY TABLE
====================================================================================================
Epoch Training Loss Validation Loss Time (s) Tokens Processed Throughput (token/s) TFLOPS (per second) Avg CPU (%) Avg Memory (%) Training Steps
    0        1.8636          4.2803    74.05          171,008                 2309                1.16        23.4           22.8            167
    1        0.6864          5.6642    74.42          171,008                 2297                1.15        22.7           27.3            167
    2        0.4571          6.0995    76.53          171,008                 2234                1.12        25.9           27.3            167

----------------------------------------------------------------------------------------------------
TRAINING STATISTICS:
----------------------------------------------------------------------------------------------------
Total Training Time:      225.0 s
Average Epoch Time:       75.0 s
Total Tokens Processed:   513,024
Average Throughput:       2280 tokens/second
Average CPU Usage:        24.0%
Average Memory Usage:     25.8%
Total Training FLOPs:     256.87 TFLOPS
Average TFLOPS (per sec): 1.14
Overall FLOPs (per token): 0.50 GFLOPS

====================================================================================================

**Reference** 
- [APXML:Choosing Optimizer Hyperparameters (lr, betas, eps, weight_decay)](https://apxml.com/courses/how-to-build-a-large-language-model/chapter-17-optimization-algorithms-llms/choosing-optimizer-hyperparameters)
- [Huggingface:bitsandbytes](https://huggingface.co/docs/bitsandbytes/en/index)
- [Huggingface:8-bit optimizers](https://huggingface.co/docs/bitsandbytes/en/optimizers)
- [Huggingface:Introduction: 8-bit optimizers](https://huggingface.co/docs/bitsandbytes/v0.43.0/optimizers)
- [Huggingface:Efficient Deep Learning: A Comprehensive Overview of Optimization Techniques](https://huggingface.co/blog/Isayoften/optimization-rush)
- [Arxiv:Memory Efficient Mixed-Precision Optimizers](https://arxiv.org/abs/2309.12381)
- [PyTorch:Automatic Mixed Precision examples](https://docs.pytorch.org/docs/stable/notes/amp_examples.html)

## Optimizer State Partitioning

### ZeRO-Offload (Stage 2)

ZeRO-Offload (Stage 2) is a specialized memory optimization within the DeepSpeed framework that offloads optimizer states and the gradient update process from the GPU to the host CPU. While ZeRO-2 normally shards (partitions) gradients and optimizer states across multiple GPUs to save VRAM, ZeRO-Offload goes a step further by moving those sharded pieces out of the GPU entirely. This effectively "loans" the CPU's memory to the training process, allowing for the fine-tuning of models that are significantly larger than the available GPU memory.

**How it Works**

ZeRO-Offload treats the GPU and CPU as a heterogeneous system, placing data where it is most efficient for the specific training phase.
- Optimizer State Offloading: Optimizer states (like the momentum and variance in Adam) often consume 2-4x more memory than the model weights. These are stored in CPU RAM for the duration of the training.
- Gradient Offloading: As gradients are computed on the GPU during the backward pass, they are immediately moved (offloaded) to the CPU.
- CPU Computation: Instead of the GPU performing the weight update, the CPU calculates the new parameter values using its own cores. To prevent this from becoming a slow bottleneck, DeepSpeed uses DeepSpeedCPUAdam, a highly optimized C++/CUDA version of Adam that is significantly faster than standard PyTorch CPU implementations.
- Communication Overlap: To maintain speed, the system overlaps the GPU's backward pass (calculating gradients) with the CPU's optimizer update. By the time the next forward pass starts, the updated weights are moved back to the GPU.

**ZeRO-Offload Implementation**

The provided code uses a DeepSpeed Configuration Dictionary to enable this behavior without requiring manual changes to the model's architecture.
**Stage 2 Definition:**

The "stage": 2 setting enables sharding of gradients and optimizer states.

**The Offload Command:**

The key optimization happens in the offload_optimizer block:

    "offload_optimizer": {
        "device": "cpu", 
        "pin_memory": True
    }
    
This tells DeepSpeed to store the Adam moments in CPU RAM. `pin_memory: True` is crucial because it enables "Fast Page-Locked" memory transfers, allowing the GPU to copy data to/from the CPU at maximum PCIe bandwidth.

**Parameter Offload:**

The line `"offload_param": {"device": "cpu"}` is technically a Stage 3 feature but is often included in hybrid configurations. In Stage 2 context, it ensures the CPU manages the master weights efficiently.

**Integration:**

By passing this dictionary into `TrainingArguments(deepspeed=deepspeed_config)`, the Hugging Face Trainer hands over the entire optimization loop to the DeepSpeed engine, which then manages the CPU-GPU communication automatically during `trainer.train()`.

**When to Use It**

ZeRO-Offload Stage 2 is ideal in these specific scenarios:
- Massive Models on Single GPUs: If you need to train a 10B+ parameter model on a single 24GB or 32GB GPU where it would normally be impossible.
- High CPU RAM availability: When your server has a massive amount of system RAM (e.g., 128GB or 256GB) but limited VRAM. You are effectively converting your cheap system RAM into "virtual VRAM."
- Full-Parameter Fine-Tuning: Use this when you cannot use LoRA/PEFT and must update every weight in a model that is too large for your GPU cluster.
- Large Batch Sizes: Even if the model fits, offloading optimizer states frees up enough VRAM to significantly increase your `per_device_train_batch_size`, leading to better training stability and potentially faster convergence.

In [7]:
%%capture
# 1. Install the system-level MPI library
!sudo apt-get update
!sudo apt-get install libopenmpi-dev

# 2. Install the Python library
!pip install mpi4py

import torch
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    DataCollatorForLanguageModeling,
    TrainingArguments,
    Trainer,
)
import deepspeed
from datasets import DatasetDict, Dataset
import os

In [ ]:
MODEL_NAME = "meta-llama/Llama-3.2-1B"
OUTPUT_DIR = "./llama-3.2-1B-finetuned-qa"
BATCH_SIZE = 2
GRADIENT_ACCUMULATION_STEPS = 4
LEARNING_RATE = 2e-5
WEIGHT_DECAY = 0.01
EPOCHS = 3

os.makedirs(OUTPUT_DIR, exist_ok=True)

# DeepSpeed ZeRO-Offload configuration
deepspeed_config = {
    "train_batch_size": BATCH_SIZE * GRADIENT_ACCUMULATION_STEPS,
    "train_micro_batch_size_per_gpu": BATCH_SIZE,
    "gradient_accumulation_steps": GRADIENT_ACCUMULATION_STEPS,
    "zero_optimization": {
        "stage": 2,
        "offload_optimizer": {"device": "cpu", "pin_memory": True},
        "offload_param": {"device": "cpu", "pin_memory": True},
        "allgather_partitions": True,
        "allgather_bucket_size": 2e8,
        "overlap_comm": True,
        "reduce_scatter": True,
        "reduce_bucket_size": 2e8,
        "contiguous_gradients": True
    },
    "optimizer": {
        "type": "AdamW",
        "params": {
            "lr": LEARNING_RATE,
            "betas": [0.9, 0.999],
            "eps": 1e-8,
            "weight_decay": WEIGHT_DECAY
        }
    },
    "scheduler": {
        "type": "WarmupLR",
        "params": {
            "warmup_min_lr": 0,
            "warmup_max_lr": LEARNING_RATE,
            "warmup_num_steps": 100
        }
    },
    "fp16": {"enabled": True},
    "gradient_clipping": 1.0,
    "steps_per_print": 100,
}

# Initialize distributed environment
if torch.cuda.device_count() > 1:
    deepspeed.init_distributed()

# Load tokenizer
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"

# Tokenize data
def tokenize_examples(texts):
    tokenized = tokenizer(
        texts,
        truncation=True,
        max_length=MAX_LENGTH,
        padding="max_length",
        return_tensors="pt"
    )
    tokenized["labels"] = tokenized["input_ids"].clone()
    tokenized["labels"][tokenized["labels"] == tokenizer.pad_token_id] = -100
    return tokenized

# Assuming train_data and val_data are Polars DataFrames
train_texts = [f"<bos>Question: {row['question_title']}\n{row['question_body']}\nAnswer: {row['answer']}<eos>" 
               for row in train_data.rows(named=True)]
val_texts = [f"<bos>Question: {row['question_title']}\n{row['question_body']}\nAnswer: {row['answer']}<eos>" 
             for row in val_data.rows(named=True)]

train_tokenized = tokenize_examples(train_texts)
val_tokenized = tokenize_examples(val_texts)

dataset_dict = DatasetDict({
    "train": Dataset.from_dict({
        "input_ids": train_tokenized["input_ids"],
        "attention_mask": train_tokenized["attention_mask"],
        "labels": train_tokenized["labels"]
    }),
    "validation": Dataset.from_dict({
        "input_ids": val_tokenized["input_ids"],
        "attention_mask": val_tokenized["attention_mask"],
        "labels": val_tokenized["labels"]
    })
})

# Load model
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    torch_dtype=torch.float16,
    low_cpu_mem_usage=True,
    use_cache=False
)

# Move model to GPU if single GPU
if torch.cuda.device_count() == 1:
    model = model.cuda()

data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=EPOCHS,
    per_device_train_batch_size=BATCH_SIZE,
    per_device_eval_batch_size=BATCH_SIZE,
    gradient_accumulation_steps=GRADIENT_ACCUMULATION_STEPS,
    learning_rate=LEARNING_RATE,
    weight_decay=WEIGHT_DECAY,
    max_grad_norm=1.0,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_steps=100,
    warmup_steps=100,
    lr_scheduler_type="cosine",
    fp16=True,
    deepspeed=deepspeed_config,
    ddp_find_unused_parameters=False,
    local_rank=int(os.environ.get("LOCAL_RANK", -1)),
    dataloader_drop_last=True,
    optim="adamw_torch",
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
)

print("\n" + "="*60)
print("DEEPSPEED ZERO-OFFLOAD STAGE 2 CONFIGURATION")
print("="*60)
print(f"Number of GPUs: {torch.cuda.device_count()}")
print(f"ZeRO Stage: 2")
print(f"Optimizer offload to CPU: Enabled")
print(f"Parameter offload to CPU: Enabled")
print(f"Batch size per GPU: {BATCH_SIZE}")
print(f"Gradient accumulation steps: {GRADIENT_ACCUMULATION_STEPS}")
print(f"Effective batch size: {BATCH_SIZE * GRADIENT_ACCUMULATION_STEPS}")
print(f"FP16: Enabled")
print("="*60)

train_result = trainer.train()

trainer.save_model(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)

print(f"\nTraining completed! Model saved to {OUTPUT_DIR}")

[W215 21:36:57.575189496 socket.cpp:200] [c10d] The hostname of the client socket cannot be retrieved. err=-3
[W215 21:36:57.576299008 socket.cpp:200] [c10d] The hostname of the client socket cannot be retrieved. err=-3

Loading weights:   0%|          | 0/146 [00:00<?, ?it/s]

============================================================
DEEPSPEED ZERO-OFFLOAD STAGE 2 CONFIGURATION
============================================================
Number of GPUs: 2
ZeRO Stage: 2
Optimizer offload to CPU: Enabled
Parameter offload to CPU: Enabled
Batch size per GPU: 2
Gradient accumulation steps: 4
Effective batch size: 8
FP16: Enabled
============================================================

Gradient accumulation steps mismatch: GradientAccumulationPlugin has 1, DeepSpeed config has 4. Using DeepSpeed's value.
[rank0]:W0215 21:37:08.757000 1487 torch/utils/cpp_extension.py:2425] TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation.
[rank0]:W0215 21:37:08.757000 1487 torch/utils/cpp_extension.py:2425] If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'] to specific architectures.

Installed CUDA version 12.5 does not match the version torch was compiled with 12.6 but since the APIs are compatible, accepting this combination
Before initializing optimizer states
MA 2.79 GB         Max_MA 4.61 GB         CA 4.61 GB         Max_CA 5 GB
CPU Virtual Memory:  used = 22.19 GB, percent = 70.8%

**Reference** 
- [DeepSpeed:DeepSpeed ZeRO-3 Offload](https://www.deepspeed.ai/2021/03/07/zero3-offload.html)
- [Huggingface:DeepSpeed](https://huggingface.co/docs/accelerate/en/usage_guides/deepspeed)
- [GitHub:DeepSpeed](https://github.com/deepspeedai/DeepSpeed)
- [DeepSpeed:ZeRO](https://deepspeed.readthedocs.io/en/latest/zero3.html)
- [Arxiv:ZeRO: Memory Optimizations Toward Training Trillion Parameter Models](https://arxiv.org/abs/1910.02054)
- [Arxiv:DeepZero: Scaling up Zeroth-Order Optimization for Deep Model Training](https://arxiv.org/abs/2310.02025)
- [DeepSpeed:Zero Redundancy Optimizer](https://www.deepspeed.ai/tutorials/zero/)
- [Huggingface:ZeRO Optimization Strategies for Large-Scale Model Training - A brief Performance Analysis](https://huggingface.co/blog/josh-a/zero-optimization-strategies)
- [APXML:Using DeepSpeed ZeRO Optimizations](https://apxml.com/courses/how-to-build-a-large-language-model/chapter-16-implementing-distributed-training-frameworks/using-deepspeed-zero-optimizations)
- [Medium;Zero Redundancy Optimizer (ZeRO): Scaling LLM Training Without Breaking the Bank](https://medium.com/@adilmaqsood501/zero-redundancy-optimizer-zero-scaling-llm-training-without-breaking-the-bank-ba045b6a805e)
- [PyTorch:Shard Optimizer States with ZeroRedundancyOptimizer](https://docs.pytorch.org/tutorials/recipes/zero_redundancy_optimizer.html)
- [ZeRO: Optimizer state and gradient sharding](https://vissl.readthedocs.io/en/v0.1.5/large_scale/zero.html)

### Optimizer State Sharding (ZeRO-1)

Optimizer State Sharding (ZeRO-1) is the first level of the Zero Redundancy Optimizer framework. It eliminates memory redundancy by partitioning (sharding) the optimizer states across multiple GPUs in a distributed training setup.

In standard Data Parallelism (DDP), every GPU maintains a full copy of the model weights, the gradients, and the optimizer states. For an optimizer like Adam, which stores two "moments" (moving averages) for every parameter in 32-bit precision, these states consume roughly 12 bytes per parameter. In a cluster of 8 GPUs, you are storing the same 12 bytes eight times. ZeRO-1 ensures that each GPU only stores 1/N of those states (where N is the number of GPUs), drastically reducing the VRAM required per device.

**How it Works**

ZeRO-1 focuses specifically on the "Optimizer States" while leaving weights and gradients replicated for maximum speed.
- Partitioning: The model's parameters are logically divided into equal shards. If you have 4 GPUs, GPU 0 is "responsible" for the first 25% of the parameters, GPU 1 for the next 25%, and so on.
- Local Updates: During the training step, each GPU calculates the gradients for the entire model based on its local batch of data.
- Gradient Reduction: GPUs synchronize their gradients (usually via an All-Reduce or Reduce-Scatter operation).
- Sharded Optimization: Instead of every GPU updating the entire model, each GPU only uses its assigned gradients to update its assigned shard of the optimizer states and master weights.
- Synchronization: After the local update, an All-Gather operation is performed so that every GPU receives the updated weights from its peers, ensuring all model replicas stay in sync for the next forward pass.

**ZeRO-1 Implementation**

The provided script uses the deepspeed_config dictionary to instruct the DeepSpeed engine to apply Stage 1 partitioning.

**The Stage Flag:**

The core command is "stage": 1. This tells DeepSpeed to shard only the optimizer states.

    "zero_optimization": {
        "stage": 1,
        "reduce_bucket_size": 5e8,
        "allgather_bucket_size": 5e8,
    }

**Bucket Tuning:**

The `reduce_bucket_size` and `allgather_bucket_size` parameters (set to 5e8 or 500M elements) control how much data is grouped together before being sent across the network. Larger buckets improve communication efficiency on fast interconnects (like NVLink) but use more temporary "buffer" memory.

**Data Parallel Coordination:**

By calling `deepspeed.init_distributed()`, the code sets up the communication group. When the Trainer starts, it sees the deepspeed argument in TrainingArguments and wraps the model.

**Weight Master Copy:**

Since `fp16=True` is enabled, the optimizer states being sharded are the 32-bit "master weights" and Adam moments. This allows the model to train in 16-bit while the optimizer maintains 32-bit precision for stability without a massive memory penalty.

**When to Use It**

ZeRO-1 is the "sweet spot" for many distributed training scenarios:
- Multi-GPU Setups with High Interconnect Speed: Because ZeRO-1 requires an All-Gather step to sync weights after every update, it is most effective when your GPUs are connected via NVLink or high-speed InfiniBand.
- Models Between 1B and 7B Parameters: For models of this size, the optimizer states are the primary bottleneck. Sharding them across 4–8 GPUs often provides enough memory headroom to avoid moving to the more complex Stage 2 or 3.
- Maximizing Throughput: ZeRO-1 generally has higher throughput (faster steps) than Stage 2 or 3 because it involves less communication overhead. If your model fits with just Stage 1, it will usually train faster than with Stage 2.
- When using specific Optimizers: Some advanced optimizers or custom training loops are more compatible with Stage 1 because the model weights themselves remain replicated and easily accessible on every GPU.

In [ ]:
import torch
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    DataCollatorForLanguageModeling,
    TrainingArguments,
    Trainer,
)
import deepspeed
from datasets import DatasetDict, Dataset
import os

In [ ]:
MODEL_NAME = "meta-llama/Llama-3.2-1B"
OUTPUT_DIR = "./llama-3.2-1B-finetuned-qa"

# DeepSpeed ZeRO-1 configuration
deepspeed_config = {
    "train_batch_size": "auto",
    "train_micro_batch_size_per_gpu": "auto",
    "gradient_accumulation_steps": "auto",
    "zero_optimization": {
        "stage": 1,
        "reduce_bucket_size": 5000,
        "allgather_bucket_size": 5000,
    },
    "optimizer": {
        "type": "AdamW",
        "params": {
            "lr": "auto",
            "weight_decay": "auto"
        }
    },
    "scheduler": {
        "type": "WarmupCosineLR",
        "params": {
            "total_num_steps": "auto", # Trainer can auto-fill this
            "warmup_num_steps": "auto", # Trainer can auto-fill this (from warmup_steps)
            "warmup_min_ratio": 0.0,    
            "cos_min_ratio": 0.0001     
        }
    },
    "fp16": {
        "enabled": "auto"
    },
    "gradient_clipping": "auto",
}

In [ ]:
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
tokenizer.pad_token = tokenizer.eos_token

train_texts = [f"<bos>Question: {row['question_title']}\n{row['question_body']}\nAnswer: {row['answer']}<eos>" 
               for row in train_data.iter_rows(named=True)]
val_texts = [f"<bos>Question: {row['question_title']}\n{row['question_body']}\nAnswer: {row['answer']}<eos>" 
             for row in val_data.iter_rows(named=True)]

train_tokenized = tokenizer(
    train_texts,
    truncation=True,
    max_length=MAX_LENGTH,
    padding="max_length",
    return_tensors="pt"
)
train_tokenized["labels"] = train_tokenized["input_ids"].clone()

val_tokenized = tokenizer(
    val_texts,
    truncation=True,
    max_length=MAX_LENGTH,
    padding="max_length",
    return_tensors="pt"
)
val_tokenized["labels"] = val_tokenized["input_ids"].clone()

dataset_dict = DatasetDict({
    "train": Dataset.from_dict({
        "input_ids": train_tokenized["input_ids"],
        "attention_mask": train_tokenized["attention_mask"],
        "labels": train_tokenized["labels"]
    }),
    "validation": Dataset.from_dict({
        "input_ids": val_tokenized["input_ids"],
        "attention_mask": val_tokenized["attention_mask"],
        "labels": val_tokenized["labels"]
    })
})

In [ ]:
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    torch_dtype=torch.float16,
)

data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

monitor = EpochMonitor(model=model)

training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=1,
    per_device_eval_batch_size=1,
    gradient_accumulation_steps=4,
    learning_rate=2e-5,
    weight_decay=0.01,
    max_grad_norm=1.0,           # Maps to DeepSpeed gradient_clipping
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_steps=100,
    warmup_steps=100,
    lr_scheduler_type="cosine",
    fp16=True,
    deepspeed=deepspeed_config,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
    callbacks = [monitor]
)

train_result = trainer.train()

trainer.save_model(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)

**Reference**
- [Huggingface:DeepSpeed](https://huggingface.co/docs/accelerate/en/usage_guides/deepspeed)
- [GitHub:DeepSpeed](https://github.com/deepspeedai/DeepSpeed)
- [DeepSpeed:ZeRO](https://deepspeed.readthedocs.io/en/latest/zero3.html)
- [Arxiv:ZeRO: Memory Optimizations Toward Training Trillion Parameter Models](https://arxiv.org/abs/1910.02054)
- [Arxiv:DeepZero: Scaling up Zeroth-Order Optimization for Deep Model Training](https://arxiv.org/abs/2310.02025)
- [DeepSpeed:Zero Redundancy Optimizer](https://www.deepspeed.ai/tutorials/zero/)
- [Huggingface:ZeRO Optimization Strategies for Large-Scale Model Training - A brief Performance Analysis](https://huggingface.co/blog/josh-a/zero-optimization-strategies)
- [APXML:Using DeepSpeed ZeRO Optimizations](https://apxml.com/courses/how-to-build-a-large-language-model/chapter-16-implementing-distributed-training-frameworks/using-deepspeed-zero-optimizations)
- [Medium;Zero Redundancy Optimizer (ZeRO): Scaling LLM Training Without Breaking the Bank](https://medium.com/@adilmaqsood501/zero-redundancy-optimizer-zero-scaling-llm-training-without-breaking-the-bank-ba045b6a805e)
- [PyTorch:Shard Optimizer States with ZeroRedundancyOptimizer](https://docs.pytorch.org/tutorials/recipes/zero_redundancy_optimizer.html)
- [ZeRO: Optimizer state and gradient sharding](https://vissl.readthedocs.io/en/v0.1.5/large_scale/zero.html)

### Delayed Optimizer Updates

Delayed Optimizer Updates (also widely known as Gradient Accumulation) is a technique used to simulate a larger training batch size than what the physical GPU memory can actually hold. In standard training, the model weights are updated after every single batch (forward and backward pass). With delayed updates, the optimizer "waits" for multiple batches to finish, summing their gradients together before finally performing a single weight update. This effectively decouples the batch size needed for stable learning from the batch size dictated by VRAM limits.

**How it Works**

The process essentially breaks one large "global" batch into several smaller "micro-batches."
- Iterative Passes: The model performs a forward pass and a backward pass on a micro-batch. It calculates the gradients (the direction the weights should move).
- Gradient Storage: Instead of using these gradients to update the weights immediately, the system stores them in a buffer and adds them to the gradients of the next micro-batch.
- The Delay: The optimizer and weight-update logic are skipped during these intermediate steps. No optimizer states (like Adam moments) are updated yet.
- The Step: Once a pre-defined number of micro-batches (the accumulation steps) is reached, the optimizer takes the total accumulated gradient and performs a single update to the model's parameters.
- Reset: The gradient buffer is cleared, and the cycle repeats.

**Delayed Optimizer Updates Implementation**

The script leverages the Hugging Face `TrainingArguments` and `DeepSpeed` integration to handle the mathematical synchronization of these delayed updates.

**The Accumulation Setting:**

The parameter `gradient_accumulation_steps=4` is the core of this optimization.

    per_device_train_batch_size=1,
    gradient_accumulation_steps=4,

This configuration tells the trainer to process 4 micro-batches of 1 sample each. The actual weight update only happens every 4 steps, resulting in an "Effective Batch Size" of 4.

**DeepSpeed Coordination:**

In the `deepspeed_config`, the setting `"gradient_accumulation_steps": "auto"` allows DeepSpeed to automatically pull the value from the `TrainingArguments`. This ensures that DeepSpeed's internal mechanisms (like ZeRO-1 sharding) remain synchronized with the delay in weight updates.

**Mathematical Normalization:**

The Trainer automatically divides the loss of each micro-batch by the number of accumulation steps. This ensures that the final accumulated gradient has the correct scale and doesn't "explode" during the update.

**Resource Efficiency:** 

Because the weights only move every 4 steps, the computational overhead of the optimizer (which can be significant for 1B+ parameter models) is reduced by 75% per processed sample.

**When to Use It**

Delayed Optimizer Updates should be used in the following conditions:
- Hardware Memory Constraints: This is the primary use case. If a model requires a batch size of 32 to learn effectively, but the GPU can only fit a batch size of 2, setting accumulation steps to 16 solves the problem.
- Stabilizing Training: Large language models often require large batch sizes to provide a "smooth" gradient signal. Small batches can be noisy and cause the model to fail to converge; delaying the update provides a cleaner, averaged gradient.
- Reducing Communication Overhead: In distributed (multi-GPU) training, the GPUs must talk to each other to sync gradients. By delaying updates, you reduce the frequency of this communication, which can significantly speed up training on networks with high latency.
- Context Length Extension: As you increase the `MAX_LENGTH` of your input, the VRAM usage per sample grows. If you increase the length to the point where only one sample fits, you use delayed updates to regain the benefits of a larger batch.

In [ ]:
import torch
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    DataCollatorForLanguageModeling,
    TrainingArguments,
    Trainer,
)
from datasets import DatasetDict, Dataset

In [7]:
MODEL_NAME = "meta-llama/Llama-3.2-1B"
OUTPUT_DIR = "./llama-3.2-1B-finetuned-qa"

# DeepSpeed configuration for delayed updates
deepspeed_config = {
    "train_batch_size": "auto",
    "train_micro_batch_size_per_gpu": "auto",
    "gradient_accumulation_steps": "auto",
    "zero_optimization": {
        "stage": 1,
        "reduce_bucket_size": 5000,
        "allgather_bucket_size": 5000,
    },
    "optimizer": {
        "type": "AdamW",
        "params": {
            "lr": "auto",
            "weight_decay": "auto"
        }
    },
    # The "scheduler" block is removed. 
    # Trainer handles this via lr_scheduler_type and warmup_steps.
    "fp16": {
        "enabled": "auto"
    },
    "gradient_clipping": "auto",
}

In [8]:
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
tokenizer.pad_token = tokenizer.eos_token

train_texts = [f"<bos>Question: {row['question_title']}\n{row['question_body']}\nAnswer: {row['answer']}<eos>" 
               for row in train_data.iter_rows(named=True)]
val_texts = [f"<bos>Question: {row['question_title']}\n{row['question_body']}\nAnswer: {row['answer']}<eos>" 
             for row in val_data.iter_rows(named=True)]

train_tokenized = tokenizer(
    train_texts,
    truncation=True,
    max_length=MAX_LENGTH,
    padding="max_length",
    return_tensors="pt"
)
train_tokenized["labels"] = train_tokenized["input_ids"].clone()

val_tokenized = tokenizer(
    val_texts,
    truncation=True,
    max_length=MAX_LENGTH,
    padding="max_length",
    return_tensors="pt"
)
val_tokenized["labels"] = val_tokenized["input_ids"].clone()

dataset_dict = DatasetDict({
    "train": Dataset.from_dict({
        "input_ids": train_tokenized["input_ids"],
        "attention_mask": train_tokenized["attention_mask"],
        "labels": train_tokenized["labels"]
    }),
    "validation": Dataset.from_dict({
        "input_ids": val_tokenized["input_ids"],
        "attention_mask": val_tokenized["attention_mask"],
        "labels": val_tokenized["labels"]
    })
})

In [ ]:
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    torch_dtype=torch.float16,
)

data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

monitor = EpochMonitor(model=model)

training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=1,
    per_device_eval_batch_size=1,
    gradient_accumulation_steps=4,
    learning_rate=2e-5,
    weight_decay=0.01,
    max_grad_norm=1.0,           # This maps to DeepSpeed's gradient_clipping
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_steps=10,
    warmup_steps=100,
    lr_scheduler_type="cosine",
    fp16=True,
    deepspeed=deepspeed_config,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
    callbacks = [monitor]
)

train_result = trainer.train()

trainer.save_model(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)

**Upgrading to Stage 2 or 3 and offloading work to the CPU will drastically reduce the GPU memory pressure.**

In [ ]:
import torch
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    DataCollatorForLanguageModeling,
    TrainingArguments,
    Trainer,
)
from datasets import DatasetDict, Dataset
import gc
import os

In [ ]:
# Configuration 
MODEL_NAME = "meta-llama/Llama-3.2-1B"
OUTPUT_DIR = "./llama-3.2-1B-finetuned-qa-delayed-updates"

# DeepSpeed configuration for delayed optimizer updates
# This configures optimizer to update less frequently by accumulating gradients
deepspeed_config = {
    "train_batch_size": "auto",
    "train_micro_batch_size_per_gpu": "auto",
    "gradient_accumulation_steps": 16,  # Accumulate gradients over 16 steps
    "zero_optimization": {
        "stage": 2,
        "offload_optimizer": {
            "device": "cpu",
            "pin_memory": True
        },
        "allgather_bucket_size": 2e8,
        "reduce_bucket_size": 2e8,
        "overlap_comm": True,
        "contiguous_gradients": True
    },
    "optimizer": {
        "type": "AdamW",
        "params": {
            "lr": 2e-5,
            "betas": [0.9, 0.999],
            "eps": 1e-8,
            "weight_decay": 0.01
        }
    },
    "scheduler": {
        "type": "WarmupCosine",
        "params": {
            "warmup_min_lr": 0,
            "warmup_max_lr": 2e-5,
            "warmup_num_steps": 100,
            "total_num_steps": 1000  # Will be adjusted automatically
        }
    },
    "fp16": {
        "enabled": "auto"
    },
    "gradient_clipping": "auto",
    "steps_per_print": 100,
    "wall_clock_breakdown": False
}

# Tokenizer 
print(f"Loading tokenizer: {MODEL_NAME}")
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"

def tokenize_examples(df, max_length=MAX_LENGTH):
    texts = [
        f"Question: {row['question_title']}\n{row['question_body']}\nAnswer: {row['answer']}"
        for row in df.iter_rows(named=True)
    ]
    tokenized = tokenizer(
        texts,
        truncation=True,
        max_length=max_length,
        padding="max_length",
        return_tensors="pt"
    )
    tokenized["labels"] = tokenized["input_ids"].clone()
    tokenized["labels"][tokenized["labels"] == tokenizer.pad_token_id] = -100
    return tokenized

# Data
print("Tokenizing datasets...")
train_tokenized = tokenize_examples(train_data)
val_tokenized = tokenize_examples(val_data)

dataset_dict = DatasetDict({
    "train": Dataset.from_dict(train_tokenized),
    "validation": Dataset.from_dict(val_tokenized)
})

print(f"Train examples: {len(dataset_dict['train']):,}")
print(f"Validation examples: {len(dataset_dict['validation']):,}")

# Load Model 
print(f"Loading base model: {MODEL_NAME}")
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    dtype=torch.float16,  
    device_map="auto",
    token=os.environ.get("HF_TOKEN", None),  # Required for gated models
)

monitor = EpochMonitor(model=model)

# Training Arguments
# Calculate total steps for warmup
total_steps = len(dataset_dict["train"]) * 3 // 1  # samples * epochs / batch_size
gradient_accumulation_steps = 16  # Update optimizer every 16 steps (delayed updates)

training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=1,  # Small batch size
    per_device_eval_batch_size=1,
    gradient_accumulation_steps=gradient_accumulation_steps,  # Delayed updates
    learning_rate=2e-5,
    weight_decay=0.01,
    max_grad_norm=1.0,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_steps=10,
    warmup_steps=int(0.1 * total_steps // gradient_accumulation_steps),  # Adjust for delayed updates
    lr_scheduler_type="cosine",
    fp16=True,
    gradient_checkpointing=True,  # Memory saving
    optim="adamw_torch",  
    deepspeed=deepspeed_config,  # Enable DeepSpeed with delayed updates
    dataloader_num_workers=2,
    ddp_find_unused_parameters=False if torch.cuda.device_count() > 1 else None,
)

# Data Collator 
data_collator = DataCollatorForLanguageModeling(
    tokenizer=tokenizer,
    mlm=False,
)

# Trainer 
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
    callbacks = [monitor]
)

# Train 

print(f"\n{'='*60}")
print(f"STARTING TRAINING WITH DELAYED OPTIMIZER UPDATES")
print(f"{'='*60}")
print(f"Gradient accumulation steps: {gradient_accumulation_steps}")
print(f"Optimizer updates per epoch: ~{len(dataset_dict['train']) // gradient_accumulation_steps}")
print(f"{'='*60}\n")

train_result = trainer.train()

# Save 
print("\nSaving model and tokenizer...")
trainer.save_model(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)

# Save training stats
with open(f"{OUTPUT_DIR}/training_stats.txt", "w") as f:
    f.write(f"Model: {MODEL_NAME}\n")
    f.write(f"Gradient accumulation steps: {gradient_accumulation_steps}\n")
    f.write(f"Final loss: {train_result.training_loss:.4f}\n")
    f.write(f"Global steps: {train_result.global_step}\n")

print(f"Model saved to: {OUTPUT_DIR}")
print(f"Tokenizer saved to: {OUTPUT_DIR}")
print(f"Training stats saved to: {OUTPUT_DIR}/training_stats.txt")
print(f"\nDelayed Optimizer Updates training completed!")

**Reference**
- [Arxiv:Stochastic Approximation with Delayed Updates: Finite-Time Rates under Markovian Sampling](https://proceedings.mlr.press/v238/adibi24a/adibi24a.pdf)
- [Arxiv:Distributed Delayed Stochastic Optimization](https://arxiv.org/abs/1104.5525)
- [Huggingface:DeepSpeed](https://huggingface.co/docs/accelerate/en/usage_guides/deepspeed)
- [GitHub:DeepSpeed](https://github.com/deepspeedai/DeepSpeed)
- [DeepSpeed:ZeRO](https://deepspeed.readthedocs.io/en/latest/zero3.html)
- [DeepSpeed:Zero Redundancy Optimizer](https://www.deepspeed.ai/tutorials/zero/)
- [Arxiv:DeepCompile: A Compiler-Driven Approach to Optimizing Distributed Deep Learning Training](https://arxiv.org/html/2504.09983v1)
- [Arxiv:ZeRO: Memory Optimizations Toward Training Trillion Parameter Models](https://arxiv.org/abs/1910.02054)
- [Arxiv:DeepZero: Scaling up Zeroth-Order Optimization for Deep Model Training](https://arxiv.org/abs/2310.02025)
- [DeepSpeed:Zero Redundancy Optimizer](https://www.deepspeed.ai/tutorials/zero/)
- [Huggingface:ZeRO Optimization Strategies for Large-Scale Model Training - A brief Performance Analysis](https://huggingface.co/blog/josh-a/zero-optimization-strategies)
- [APXML:Using DeepSpeed ZeRO Optimizations](https://apxml.com/courses/how-to-build-a-large-language-model/chapter-16-implementing-distributed-training-frameworks/using-deepspeed-zero-optimizations)
- [DeepSpeed:Training API](https://deepspeed.readthedocs.io/en/latest/training.html)

# DISTRIBUTED TRAINING OPTIMIZATIONS (Fine-tuning)

## Advanced Parallelism Strategies

Advanced Parallelism Strategies are a suite of techniques designed to train models that are physically too large to fit into a single GPU's memory. While the standard optimizations (like 8-bit Adam) target the optimizer, 3D Parallelism and ZeRO target the entire model architecture and distributed data flow.

**3D Parallelism**

3D Parallelism is the simultaneous combination of three different scaling dimensions. It organizes GPUs into a 3D grid, where each "cell" handles a specific part of the workload.
- Data Parallelism (DP): The grid's first dimension. It splits the dataset. Different GPUs get different sentences but hold the same "part" of the model.
- Pipeline Parallelism (PP): The second dimension. It splits the model vertically (by layer). GPU A might handle layers 1–10, while GPU B handles layers 11–20. Data flows through them like an assembly line.
- Tensor Parallelism (TP): The third dimension. It splits the model horizontally (inside a single layer). A massive matrix multiplication is chopped into pieces, and each GPU calculates a fragment of the math.

**ZeRO (Zero Redundancy Optimizer)**

ZeRO is often described as "Data Parallelism on steroids." In standard training, every GPU in a data-parallel group keeps a full copy of the model. ZeRO removes this redundancy by sharding the state across all available GPUs.
- ZeRO-1: Shards only the Optimizer States (Adam moments).
- ZeRO-2: Shards Optimizer States + Gradients.
- ZeRO-3: Shards Optimizer States + Gradients + Model Parameters. In Stage 3, a GPU only holds a fraction of the model; it "fetches" the other pieces from its neighbors right before it needs them for a calculation and then deletes them immediately after.

**When to Use It**

These strategies are high-octane tools and should be used based on your specific scale:
- Trillion-Parameter Ambitions: If you are training or full-finetuning models like Llama-3-70B or larger across dozens of GPUs, 3D Parallelism is mandatory to prevent "Out of Memory" errors.
- Hardware with High-Speed Interconnects: Tensor Parallelism (TP) requires GPUs to talk constantly. You should only use TP if your GPUs are in the same box connected via NVLink. If you are training across different servers (over a standard network), stick to ZeRO-2 or Pipeline Parallelism.
- Maximizing Throughput: Use ZeRO-2 as your default for multi-GPU training. It provides a massive memory saving with almost zero performance penalty.
- Extreme Memory Pressure: Use ZeRO-3 when your model is so big that even the weights themselves won't fit on the GPU. It is slower than ZeRO-2 due to constant network "fetching," but it allows for near-infinite scaling—the more GPUs you add, the more memory you "create."
- Long Sequence Lengths: When training on very long documents (e.g., 32k or 128k tokens), the Activations become the bottleneck. 3D Parallelism (specifically Tensor Parallelism) helps distribute these activations so they don't crash a single card.

**Reference**
- [Arxiv:PAFT: A Parallel Training Paradigm for Effective LLM Fine-Tuning](https://arxiv.org/abs/2406.17923)
- [ACM:Parallelization Techniques for Large Language Models: A Review from Training to Inference](https://dl.acm.org/doi/10.1007/978-981-96-8725-1_25)
- [Huggingface:Parallelism methods](https://huggingface.co/docs/transformers/en/perf_train_gpu_many)
- [Medium:Scaling Large Language Models: A Guide to Parallelism Techniques](https://medium.com/@siddharthtiwari01/scaling-large-language-models-a-guide-to-parallelism-techniques-c4f7dd6c9f1f)
- [AWS:Parallelism Techniques for LLM Inference](https://awsdocs-neuron.readthedocs-hosted.com/en/latest/libraries/nxd-inference/app-notes/parallelism.html)
- [Arxiv:ZeRO: Memory Optimizations Toward Training Trillion Parameter Models](https://arxiv.org/abs/1910.02054)
- [Arxiv:DeepZero: Scaling up Zeroth-Order Optimization for Deep Model Training](https://arxiv.org/abs/2310.02025)
- [Arxiv:Distributed Delayed Stochastic Optimization](https://arxiv.org/abs/1104.5525)
- [Huggingface:DeepSpeed](https://huggingface.co/docs/accelerate/en/usage_guides/deepspeed)
- [GitHub:DeepSpeed](https://github.com/deepspeedai/DeepSpeed)
- [DeepSpeed:ZeRO](https://deepspeed.readthedocs.io/en/latest/zero3.html)
- [DeepSpeed:Zero Redundancy Optimizer](https://www.deepspeed.ai/tutorials/zero/)
- [Arxiv:DeepCompile: A Compiler-Driven Approach to Optimizing Distributed Deep Learning Training](https://arxiv.org/html/2504.09983v1)
- [DeepSpeed:Zero Redundancy Optimizer](https://www.deepspeed.ai/tutorials/zero/)
- [Huggingface:ZeRO Optimization Strategies for Large-Scale Model Training - A brief Performance Analysis](https://huggingface.co/blog/josh-a/zero-optimization-strategies)
- [APXML:Using DeepSpeed ZeRO Optimizations](https://apxml.com/courses/how-to-build-a-large-language-model/chapter-16-implementing-distributed-training-frameworks/using-deepspeed-zero-optimizations)
- [DeepSpeed:Training API](https://deepspeed.readthedocs.io/en/latest/training.html)
- [Huggingface:PEFT](https://huggingface.co/docs/peft/en/index)
- [Huggingface:Quantization](https://huggingface.co/docs/peft/en/developer_guides/quantization)

### ZeRO Optimization Levels

#### ZeRO-1 (Optimizer State Sharding)

ZeRO-1 (Zero Redundancy Optimizer Stage 1) is a memory-saving technique designed for distributed training. It works by sharding (partitioning) the optimizer states across all available GPUs in a cluster.

In standard Data Parallel training, every GPU stores a complete copy of the model parameters, gradients, and optimizer states. For an optimizer like Adam, the states (momentum and variance) consume significantly more memory than the model weights themselves. ZeRO-1 ensures that each GPU only holds and updates a fraction of these states, reducing the per-GPU memory footprint by roughly 4x for the optimizer portion.

**How it Works**

ZeRO-1 focuses on eliminating redundancy in the optimizer memory while keeping parameters and gradients replicated for speed.
- Partitioning: If you have N GPUs, the optimizer states are split into N equal shards. GPU 1 manages the first 1/N of the parameters' states, GPU 2 the next 1/N, and so on.
- Full Forward/Backward Pass: Every GPU still processes its own batch of data using a full copy of the model weights.
- Gradient Average: After the backward pass, gradients are averaged across all GPUs (typically via an "All-Reduce" operation).
- Sharded Update: Each GPU performs the optimizer update (math) only for its assigned shard of the parameters.
- Re-synchronization: After the update, GPUs perform an "All-Gather" to share their updated parameter shards with everyone else, ensuring all GPUs have the identical, fully updated model for the next step.

**ZeRO-1 Implementation**

The provided code uses the DeepSpeed integration in the Hugging Face Trainer to activate Stage 1 partitioning.

**DeepSpeed Config:**

The dictionary key "stage": 1 inside `zero_optimization` tells the engine to shard only the optimizer states.

    "zero_optimization": {
        "stage": 1,
        "allgather_bucket_size": 2e8,
        "reduce_bucket_size": 2e8
    }

**Automatic Handshake:**

The use of "auto" for parameters like `train_batch_size` and fp16 allows DeepSpeed to inherit settings directly from the `TrainingArguments`. This ensures that the sharding logic respects the batch size and precision (FP16) defined in the script.

**Communication Buckets:**

The `allgather_bucket_size` and `reduce_bucket_size` values control the size of data chunks transferred between GPUs. Setting these to 2e8 helps balance communication speed with memory usage by grouping small parameter updates together.

**Integration with QLoRA:**

The script combines ZeRO-1 with 4-bit quantization (`BitsAndBytesConfig`). While QLoRA reduces the memory of the model weights, ZeRO-1 ensures that the optimizer states for the trainable LoRA adapters are distributed across GPUs, preventing any single GPU from hitting a memory bottleneck.

**When to Use It**

ZeRO-1 is a "low-hanging fruit" optimization that is ideal for:
- Multi-GPU Environments: It is strictly for distributed training (2 or more GPUs). It does nothing for single-GPU setups.
- Training Models with Adam/AdamW: Since Adam keeps two 32-bit "moments" for every parameter, the states are massive. ZeRO-1 is the most efficient way to reduce this overhead without the higher communication costs of ZeRO-2 or ZeRO-3.
- Maximizing Training Speed: ZeRO-1 is generally faster than Stage 2 or 3 because it involves less communication. If your model fits in memory with just Stage 1, it is usually the best choice for throughput.
- Large Batch Training: Use it when you want to increase your `per_device_batch_size beyond` what standard data parallelism allows, but don't need the extreme memory savings of full parameter sharding.

In [ ]:
%%capture
# Install the system-level MPI dependency
!sudo apt-get update
!sudo apt-get install -y libopenmpi-dev

# Install the mpi4py Python package
!pip install mpi4py
!pip install tiktoken

import torch
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    DataCollatorForLanguageModeling,
    TrainingArguments,
    Trainer,
    BitsAndBytesConfig,
)
from datasets import DatasetDict, Dataset
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training, TaskType
import os

In [7]:
MODEL_NAME = "meta-llama/Llama-3.2-1B"
OUTPUT_DIR = "./llama-3.2-1B-finetuned-qa"
MAX_LENGTH = 128

# BitsAndBytes for 4-bit quantization (QLoRA)
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
)

# DeepSpeed config for ZeRO Stage 1 (Optimizer State Sharding)
# Using 'auto' for values that should be calculated automatically
deepspeed_config = {
    "train_batch_size": "auto",
    "train_micro_batch_size_per_gpu": "auto",
    "gradient_accumulation_steps": "auto",
    "zero_optimization": {
        "stage": 1,
        "allgather_bucket_size": 2e8,
        "reduce_bucket_size": 2e8
    },
    "optimizer": {
        "type": "AdamW",
        "params": {
            "lr": "auto",
            "weight_decay": "auto"
        }
    },
    "scheduler": {
        "type": "WarmupCosineLR",
        "params": {
            "total_num_steps": "auto", # Trainer can auto-fill this
            "warmup_num_steps": "auto", # Trainer can auto-fill this (from warmup_steps)
            "warmup_min_ratio": 0.0,    
            "cos_min_ratio": 0.0001 
        }
    },
    "fp16": {
        "enabled": "auto"
    }
}

In [8]:
# Load tokenizer
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
tokenizer.pad_token = tokenizer.eos_token

# Check if special tokens exist in vocabulary
if not tokenizer.bos_token:
    tokenizer.bos_token = "<s>"
if not tokenizer.eos_token:
    tokenizer.eos_token = "</s>"

# Use the tokenizer's special tokens instead of hardcoded ones
train_texts = [
    f"{tokenizer.bos_token}Question: {row['question_title']}\n{row['question_body']}\nAnswer: {row['answer']}{tokenizer.eos_token}"
    for row in train_data.iter_rows(named=True)
]

val_texts = [
    f"{tokenizer.bos_token}Question: {row['question_title']}\n{row['question_body']}\nAnswer: {row['answer']}{tokenizer.eos_token}"
    for row in val_data.iter_rows(named=True)
]

# Tokenize without returning tensors immediately to avoid issues
def tokenize_function(examples):
    return tokenizer(
        examples["text"],
        truncation=True,
        max_length=MAX_LENGTH,
        padding="max_length",
    )

# Create datasets
train_dataset = Dataset.from_dict({"text": train_texts})
val_dataset = Dataset.from_dict({"text": val_texts})

# Tokenize datasets
train_tokenized = train_dataset.map(
    tokenize_function,
    batched=True,
    remove_columns=["text"]
)
val_tokenized = val_dataset.map(
    tokenize_function,
    batched=True,
    remove_columns=["text"]
)

# Add labels (for causal language modeling)
train_tokenized = train_tokenized.map(
    lambda examples: {"labels": examples["input_ids"].copy()}
)
val_tokenized = val_tokenized.map(
    lambda examples: {"labels": examples["input_ids"].copy()}
)

dataset_dict = DatasetDict({
    "train": train_tokenized,
    "validation": val_tokenized
})

# Calculate steps for debugging
num_train_samples = len(dataset_dict["train"])
batch_size = 1  # per_device_train_batch_size
grad_accum_steps = 4
epochs = 3

steps_per_epoch = num_train_samples // (batch_size * grad_accum_steps)
if num_train_samples % (batch_size * grad_accum_steps) > 0:
    steps_per_epoch += 1
total_steps = steps_per_epoch * epochs

print(f"Training samples: {num_train_samples}")
print(f"Batch size: {batch_size}")
print(f"Gradient accumulation steps: {grad_accum_steps}")
print(f"Steps per epoch: {steps_per_epoch}")
print(f"Total training steps: {total_steps}")

Map:   0%|          | 0/1331 [00:00<?, ? examples/s]

Map:   0%|          | 0/285 [00:00<?, ? examples/s]

Map:   0%|          | 0/1331 [00:00<?, ? examples/s]

Map:   0%|          | 0/285 [00:00<?, ? examples/s]

Training samples: 1331
Batch size: 1
Gradient accumulation steps: 4
Steps per epoch: 333
Total training steps: 999

In [9]:
# Load quantized model
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    quantization_config=bnb_config,
    low_cpu_mem_usage=True,
    device_map="auto",
    torch_dtype=torch.float16,
)

# Prepare for QLoRA training
model = prepare_model_for_kbit_training(model)
model.gradient_checkpointing_enable()

# PEFT LoRA config
lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    lora_dropout=0.05,
    bias="none",
    task_type=TaskType.CAUSAL_LM,
    target_modules=["q_proj", "v_proj", "k_proj", "o_proj"],
)

model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

# Data collator
data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

monitor = EpochMonitor(model=model)

# Training arguments
training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=1,
    gradient_accumulation_steps=4,
    learning_rate=2e-5,
    weight_decay=0.01,
    warmup_steps=100,
    fp16=True,
    lr_scheduler_type="cosine", 
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    deepspeed=deepspeed_config,
)

# Initialize Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
)

# Check if DeepSpeed is properly initialized
print(f"DeepSpeed enabled: {training_args.deepspeed is not None}")

# Start training
train_result = trainer.train()

# Save the model
trainer.save_model(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)

# Also save the LoRA adapter separately
model.save_pretrained(OUTPUT_DIR)

`torch_dtype` is deprecated! Use `dtype` instead!

Loading weights:   0%|          | 0/146 [00:00<?, ?it/s]

trainable params: 3,407,872 || all params: 1,239,222,272 || trainable%: 0.2750

Gradient accumulation steps mismatch: GradientAccumulationPlugin has 1, DeepSpeed config has 4. Using DeepSpeed's value.

DeepSpeed enabled: True
Before initializing optimizer states
MA 0.98 GB         Max_MA 0.98 GB         CA 1.29 GB         Max_CA 1 GB
CPU Virtual Memory:  used = 3.65 GB, percent = 8.3%
After initializing optimizer states
MA 0.98 GB         Max_MA 0.99 GB         CA 1.29 GB         Max_CA 1 GB
CPU Virtual Memory:  used = 3.65 GB, percent = 8.3%
After initializing ZeRO optimizer
MA 0.98 GB         Max_MA 0.98 GB         CA 1.29 GB         Max_CA 1 GB
CPU Virtual Memory:  used = 3.65 GB, percent = 8.3%
[2026-02-14 03:36:12,210] [WARNING] [lr_schedules.py:862:get_lr] Attempting to get learning rate from scheduler before it has started
Initial Model Memory Footprint:
  Parameters: 752,683,008
  Precision: 2 bytes
  Total Memory: 17.40 GB
    - Parameters: 1.40 GB
    - KV Cache (est): 16.00 GB
  Estimated FLOPs per forward pass (batch=8, seq=512): 8.89 TFLOPS

============================================================
Epoch 0 Summary
============================================================
  Duration (s)         :        342.44
  Tokens Processed     :       170,496
  Throughput (token/s) :           498
  Training Steps       :           333
  Avg CPU (%)          :          19.0
  Avg Memory (%)       :           9.4
  Total FLOPs          : 369.89 TFLOPS
  TFLOPS (per second)  :          1.08
  FLOPs (per token)    :   2.17 GFLOPS

============================================================
Epoch 1 Summary
============================================================
  Duration (s)         :        342.13
  Tokens Processed     :       170,496
  Throughput (token/s) :           498
  Training Steps       :           333
  Avg CPU (%)          :          18.6
  Avg Memory (%)       :          10.5
  Total FLOPs          : 369.89 TFLOPS
  TFLOPS (per second)  :          1.08
  FLOPs (per token)    :   2.17 GFLOPS

============================================================
Epoch 2 Summary
============================================================
  Duration (s)         :        340.95
  Tokens Processed     :       170,496
  Throughput (token/s) :           500
  Training Steps       :           333
  Avg CPU (%)          :          17.2
  Avg Memory (%)       :          10.6
  Total FLOPs          : 369.89 TFLOPS
  TFLOPS (per second)  :          1.08
  FLOPs (per token)    :   2.17 GFLOPS

============================================================
TRAINING COMPLETE
============================================================
Total Training Time: 1047.96s
Total Epochs: 3
Average Epoch Time: 341.84s
Total Tokens Processed: 511,488
Average Throughput: 488 tokens/second
Total FLOPs: 1109.68 TFLOPS
Average TFLOPS (per second): 1.06
Overall FLOPs (per token): 2.17 GFLOPS

Final Metrics:
Memory Footprint: 17.40 GB
Inference Throughput: 505 tokens/second
Total Training FLOPs: 369.89 TFLOPS

**Reference**
- [Arxiv:ZeRO: Memory Optimizations Toward Training Trillion Parameter Models](https://arxiv.org/abs/1910.02054)
- [Arxiv:DeepZero: Scaling up Zeroth-Order Optimization for Deep Model Training](https://arxiv.org/abs/2310.02025)
- [Arxiv:Distributed Delayed Stochastic Optimization](https://arxiv.org/abs/1104.5525)
- [Huggingface:DeepSpeed](https://huggingface.co/docs/accelerate/en/usage_guides/deepspeed)
- [GitHub:DeepSpeed](https://github.com/deepspeedai/DeepSpeed)
- [DeepSpeed:ZeRO](https://deepspeed.readthedocs.io/en/latest/zero3.html)
- [DeepSpeed:Zero Redundancy Optimizer](https://www.deepspeed.ai/tutorials/zero/)
- [Arxiv:DeepCompile: A Compiler-Driven Approach to Optimizing Distributed Deep Learning Training](https://arxiv.org/html/2504.09983v1)
- [DeepSpeed:Zero Redundancy Optimizer](https://www.deepspeed.ai/tutorials/zero/)
- [Huggingface:ZeRO Optimization Strategies for Large-Scale Model Training - A brief Performance Analysis](https://huggingface.co/blog/josh-a/zero-optimization-strategies)
- [APXML:Using DeepSpeed ZeRO Optimizations](https://apxml.com/courses/how-to-build-a-large-language-model/chapter-16-implementing-distributed-training-frameworks/using-deepspeed-zero-optimizations)
- [DeepSpeed:Training API](https://deepspeed.readthedocs.io/en/latest/training.html)
- [Huggingface:PEFT](https://huggingface.co/docs/peft/en/index)
- [Huggingface:Quantization](https://huggingface.co/docs/peft/en/developer_guides/quantization)

#### ZeRO-2 (Gradient + Optimizer Sharding)

ZeRO-2 (Zero Redundancy Optimizer Stage 2) is a sophisticated distributed training optimization that builds upon ZeRO-1. While Stage 1 only shards the optimizer states, ZeRO-2 shards both the optimizer states and the gradients across all participating GPUs. This eliminates the memory redundancy of keeping a full set of gradients on every GPU, providing roughly an 8× reduction in memory related to training states. It allows for significantly larger batch sizes and more complex models without the heavy communication overhead found in Stage 3.

**How it Works**

ZeRO-2 transforms how a cluster of GPUs manages the temporary data generated during training.
- Gradient Sharding: In standard training, every GPU stores all gradients for the entire model. In ZeRO-2, each GPU is assigned ownership of a specific "shard" of the model. When gradients are calculated, they are immediately reduced (averaged) across GPUs, but each GPU only retains the averaged gradients for its assigned shard.
- Reduced-Scatter Operation: Instead of a full "All-Reduce" (where everyone gets everything), ZeRO-2 uses a "Reduce-Scatter." This ensures that once gradients are averaged, the "scattered" results stay only with the assigned owner GPU.
- Optimizer Update: Because a GPU only holds the gradients for its specific shard, it only needs the optimizer states (momentum, variance) for that same shard. It performs the math to update its portion of the weights.
- Weight Broadcast: After the update, the new weights are shared back to all GPUs so they can begin the next forward pass with a complete, synchronized model.

**ZeRO-2 Implementation**

The script activates Stage 2 by passing a specialized DeepSpeed JSON-like dictionary into the Hugging Face Trainer.

**The Stage Definition:**

The core instruction is `"stage": 2`. This tells DeepSpeed to enable both optimizer state and gradient sharding.

    "zero_optimization": {
        "stage": 2, 
        "overlap_comm": True,
        "reduce_scatter": True
    }

**Communication Overlap:**

The setting `"overlap_comm": True` allows the system to start transferring gradients across the network while the GPU is still busy calculating gradients for other layers. This hides the network latency behind the computation.

**Reduce-Scatter:** 

Enabling `"reduce_scatter": True `is the technical implementation of gradient sharding. It ensures that averaged gradients are distributed to their respective owners rather than being copied everywhere.

**Quantization Synergy:**

The code loads the model with `load_in_4bit=True`. By combining QLoRA (which shrinks weights) with ZeRO-2 (which shards gradients and optimizer states), the VRAM footprint is minimized across every major category: weights, gradients, and optimizer states.

**When to Use It**

ZeRO-2 is considered the "industry standard" default for multi-GPU training because it offers the best balance of memory savings and speed.
- Multi-GPU Fine-tuning: It is strictly for clusters of 2 or more GPUs. It provides no benefit for single-GPU setups.
- Memory-Hungry Optimizers: Use it whenever using Adam or AdamW. Since these optimizers store multiple values per parameter, sharding them along with gradients provides the "8x" memory relief.
- High-Speed Interconnects: While it works on standard ethernet, it thrives on NVLink or InfiniBand. The frequent movement of gradient shards and weight updates requires high bandwidth to keep the GPUs from idling.
- Balanced Scaling: Use ZeRO-2 when ZeRO-1 isn't saving enough memory to prevent "Out of Memory" errors, but you want to avoid the significant slowdown that comes with ZeRO-3 (which shards the actual model parameters).

In [ ]:
import torch
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    DataCollatorForLanguageModeling,
    TrainingArguments,
    Trainer,
    BitsAndBytesConfig,
)
from datasets import DatasetDict, Dataset
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training, TaskType
import os

In [7]:
MODEL_NAME = "meta-llama/Llama-3.2-1B"
OUTPUT_DIR = "./llama-3.2-1B-finetuned-qa"
MAX_LENGTH = 128

# DeepSpeed config for ZeRO Stage 2 (Gradient + Optimizer Sharding)
deepspeed_config = {
    "train_batch_size": "auto",
    "train_micro_batch_size_per_gpu": "auto",
    "gradient_accumulation_steps": "auto",
    "zero_optimization": {
        "stage": 2,  # Changed from 1 to 2 for Gradient + Optimizer sharding
        "allgather_bucket_size": 2e8,
        "reduce_bucket_size": 2e8,
        "overlap_comm": True,
        "reduce_scatter": True
    },
    "optimizer": {
        "type": "AdamW",
        "params": {
            "lr": "auto",
            "weight_decay": "auto"
        }
    },
    "scheduler": {
        "type": "WarmupCosineLR",
        "params": {
            "total_num_steps": "auto", 
            "warmup_num_steps": "auto", 
            "warmup_min_ratio": 0.0,    
            "cos_min_ratio": 0.0001     
        }
    },
    "fp16": {
        "enabled": "auto"
    }
}

In [8]:
# Load tokenizer
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
tokenizer.pad_token = tokenizer.eos_token

if not tokenizer.bos_token:
    tokenizer.bos_token = "<s>"
if not tokenizer.eos_token:
    tokenizer.eos_token = "</s>"

# Dataset Preparation (Assuming train_data/val_data are available in context)
train_texts = [
    f"{tokenizer.bos_token}Question: {row['question_title']}\n{row['question_body']}\nAnswer: {row['answer']}{tokenizer.eos_token}"
    for row in train_data.iter_rows(named=True)
]

val_texts = [
    f"{tokenizer.bos_token}Question: {row['question_title']}\n{row['question_body']}\nAnswer: {row['answer']}{tokenizer.eos_token}"
    for row in val_data.iter_rows(named=True)
]

def tokenize_function(examples):
    return tokenizer(
        examples["text"],
        truncation=True,
        max_length=MAX_LENGTH,
        padding="max_length",
    )

train_dataset = Dataset.from_dict({"text": train_texts})
val_dataset = Dataset.from_dict({"text": val_texts})

train_tokenized = train_dataset.map(tokenize_function, batched=True, remove_columns=["text"])
val_tokenized = val_dataset.map(tokenize_function, batched=True, remove_columns=["text"])

# Add labels
train_tokenized = train_tokenized.map(lambda examples: {"labels": examples["input_ids"].copy()})
val_tokenized = val_tokenized.map(lambda examples: {"labels": examples["input_ids"].copy()})

dataset_dict = DatasetDict({"train": train_tokenized, "validation": val_tokenized})

Map:   0%|          | 0/1331 [00:00<?, ? examples/s]

Map:   0%|          | 0/285 [00:00<?, ? examples/s]

Map:   0%|          | 0/1331 [00:00<?, ? examples/s]

Map:   0%|          | 0/285 [00:00<?, ? examples/s]

In [9]:
# BitsAndBytes for 4-bit quantization (QLoRA)
bnb_config = BitsAndBytesConfig(
    load_in_4bit=True,
    bnb_4bit_quant_type="nf4",
    bnb_4bit_compute_dtype=torch.float16,
    bnb_4bit_use_double_quant=True,
)

# Load model (Quantized for QLoRA)
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    quantization_config=bnb_config,
    low_cpu_mem_usage=True,
    device_map="auto", # Trainer + DeepSpeed handles distribution
    torch_dtype=torch.float16,
)

model = prepare_model_for_kbit_training(model)
model.gradient_checkpointing_enable()

# PEFT LoRA setup
lora_config = LoraConfig(
    r=16,
    lora_alpha=32,
    lora_dropout=0.05,
    bias="none",
    task_type=TaskType.CAUSAL_LM,
    target_modules=["q_proj", "v_proj", "k_proj", "o_proj"],
)

model = get_peft_model(model, lora_config)
model.print_trainable_parameters()

data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

monitor = EpochMonitor(model=model)

# Training Arguments
training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=1,
    gradient_accumulation_steps=4,
    learning_rate=2e-5,
    weight_decay=0.01,
    warmup_steps=100,
    fp16=True,
    lr_scheduler_type="cosine", # String required for HF validation
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    deepspeed=deepspeed_config, # ZeRO-2 config
)

# Initialize and Run Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
)

print(f"DeepSpeed enabled: {training_args.deepspeed is not None}")
train_result = trainer.train()

# Save final artifacts
trainer.save_model(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)
model.save_pretrained(OUTPUT_DIR)

`torch_dtype` is deprecated! Use `dtype` instead!

Loading weights:   0%|          | 0/146 [00:00<?, ?it/s]

trainable params: 3,407,872 || all params: 1,239,222,272 || trainable%: 0.2750

Gradient accumulation steps mismatch: GradientAccumulationPlugin has 1, DeepSpeed config has 4. Using DeepSpeed's value.

DeepSpeed enabled: True
Before initializing optimizer states
MA 0.98 GB         Max_MA 0.98 GB         CA 1.23 GB         Max_CA 1 GB
CPU Virtual Memory:  used = 3.65 GB, percent = 8.3%
After initializing optimizer states
MA 0.98 GB         Max_MA 0.99 GB         CA 1.23 GB         Max_CA 1 GB
CPU Virtual Memory:  used = 3.65 GB, percent = 8.3%
After initializing ZeRO optimizer
MA 0.98 GB         Max_MA 0.98 GB         CA 1.23 GB         Max_CA 1 GB
CPU Virtual Memory:  used = 3.65 GB, percent = 8.3%
[2026-02-14 03:13:02,533] [WARNING] [lr_schedules.py:862:get_lr] Attempting to get learning rate from scheduler before it has started
Initial Model Memory Footprint:
  Parameters: 752,683,008
  Precision: 2 bytes
  Total Memory: 17.40 GB
    - Parameters: 1.40 GB
    - KV Cache (est): 16.00 GB
  Estimated FLOPs per forward pass (batch=8, seq=512): 8.89 TFLOPS

============================================================
Epoch 0 Summary
============================================================
  Duration (s)         :        354.02
  Tokens Processed     :       170,496
  Throughput (token/s) :           482
  Training Steps       :           333
  Avg CPU (%)          :          18.6
  Avg Memory (%)       :           9.4
  Total FLOPs          : 369.89 TFLOPS
  TFLOPS (per second)  :          1.04
  FLOPs (per token)    :   2.17 GFLOPS

============================================================
Epoch 1 Summary
============================================================
  Duration (s)         :        356.03
  Tokens Processed     :       170,496
  Throughput (token/s) :           479
  Training Steps       :           333
  Avg CPU (%)          :          18.8
  Avg Memory (%)       :          10.6
  Total FLOPs          : 369.89 TFLOPS
  TFLOPS (per second)  :          1.04
  FLOPs (per token)    :   2.17 GFLOPS

============================================================
Epoch 2 Summary
============================================================
  Duration (s)         :        356.71
  Tokens Processed     :       170,496
  Throughput (token/s) :           478
  Training Steps       :           333
  Avg CPU (%)          :          18.8
  Avg Memory (%)       :          10.6
  Total FLOPs          : 369.89 TFLOPS
  TFLOPS (per second)  :          1.04
  FLOPs (per token)    :   2.17 GFLOPS

============================================================
TRAINING COMPLETE
============================================================
Total Training Time: 1085.73s
Total Epochs: 3
Average Epoch Time: 355.59s
Total Tokens Processed: 511,488
Average Throughput: 471 tokens/second
Total FLOPs: 1109.68 TFLOPS
Average TFLOPS (per second): 1.02
Overall FLOPs (per token): 2.17 GFLOPS

Final Metrics:
Memory Footprint: 17.40 GB
Inference Throughput: 482 tokens/second
Total Training FLOPs: 369.89 TFLOPS

**Reference**
- [Arxiv:ZeRO: Memory Optimizations Toward Training Trillion Parameter Models](https://arxiv.org/abs/1910.02054)
- [Arxiv:DeepZero: Scaling up Zeroth-Order Optimization for Deep Model Training](https://arxiv.org/abs/2310.02025)
- [Arxiv:Distributed Delayed Stochastic Optimization](https://arxiv.org/abs/1104.5525)
- [Huggingface:DeepSpeed](https://huggingface.co/docs/accelerate/en/usage_guides/deepspeed)
- [GitHub:DeepSpeed](https://github.com/deepspeedai/DeepSpeed)
- [DeepSpeed:ZeRO](https://deepspeed.readthedocs.io/en/latest/zero3.html)
- [DeepSpeed:Zero Redundancy Optimizer](https://www.deepspeed.ai/tutorials/zero/)
- [Arxiv:DeepCompile: A Compiler-Driven Approach to Optimizing Distributed Deep Learning Training](https://arxiv.org/html/2504.09983v1)
- [DeepSpeed:Zero Redundancy Optimizer](https://www.deepspeed.ai/tutorials/zero/)
- [Huggingface:ZeRO Optimization Strategies for Large-Scale Model Training - A brief Performance Analysis](https://huggingface.co/blog/josh-a/zero-optimization-strategies)
- [APXML:Using DeepSpeed ZeRO Optimizations](https://apxml.com/courses/how-to-build-a-large-language-model/chapter-16-implementing-distributed-training-frameworks/using-deepspeed-zero-optimizations)
- [DeepSpeed:Training API](https://deepspeed.readthedocs.io/en/latest/training.html)
- [Huggingface:PEFT](https://huggingface.co/docs/peft/en/index)
- [Huggingface:Quantization](https://huggingface.co/docs/peft/en/developer_guides/quantization)

#### ZeRO-3 (Full Parameter Partitioning)

ZeRO-3 (Zero Redundancy Optimizer Stage 3) is the most advanced memory optimization stage in the DeepSpeed suite. While earlier stages shard only optimizer states (ZeRO-1) or gradients (ZeRO-2), ZeRO-3 shards the model parameters themselves across all available GPUs.

This creates a pooled memory environment where the total memory of the entire GPU cluster is used as a single large buffer. In this stage, no single GPU holds a full copy of the model. This allows for a memory reduction of N× (where N is the number of GPUs), theoretically enabling the training of models with trillions of parameters that would be physically impossible to fit on a single device.

**How it Works**

ZeRO-3 operates on a "just-in-time" parameter fetching logic.
- Full Partitioning: At the start, model weights, gradients, and optimizer states are split into N equal parts across N GPUs.
- Live Parameter Fetching: During the forward pass, when a GPU reaches a specific layer (e.g., Layer 5), it sends a broadcast request to all other GPUs to "fetch" the missing pieces of that layer.
- Calculation and Discard: Once the GPU has the full layer parameters, it performs the computation. Immediately after the calculation is done, it discards the fetched parameters, keeping only its original 1/N shard.
- Backward Pass: The same "fetch-calculate-discard" cycle repeats during the backward pass to compute gradients.
- CPU Offloading: ZeRO-3 often incorporates ZeRO-Infinity technology, which allows moving the sharded parameters and optimizer states from GPU VRAM to the host CPU RAM (or even NVMe storage). This makes the effective memory limit the size of your system's RAM rather than your GPU's VRAM.

**ZeRO-3 Implementation**

The script activates the full suite of ZeRO-3 features through the deepspeed_config and TrainingArguments.

**Stage 3 Activation:**

The setting "stage": 3 triggers the parameter sharding logic.

**Infinite Offloading:**

The configuration below moves both the optimizer states and the parameters to the CPU when they are not actively being used in a calculation:

    "offload_optimizer": {"device": "cpu", "pin_memory": True},
    "offload_param": {"device": "cpu", "pin_memory": True},

This is what allows a Llama-3 model to be fine-tuned even on GPUs with very low VRAM, as the "working memory" is shifted to the CPU.

**Prefetching and Overlap:**

To mitigate the speed penalty of fetching parameters over the network, settings like `overlap_comm: True` and `stage3_prefetch_bucket_size` allow the system to start fetching the next layer's weights while the current layer is still calculating.

**Model Initialization:**

Unlike Stage 1 or 2, the model is loaded in `torch.float16` without a `device_map`. This is because DeepSpeed Stage 3 must take control of the model's memory allocation from the moment it is loaded to ensure parameters are sharded correctly across the distributed group.

**When to Use It**

ZeRO-3 is a specialized tool that should be used when memory is the absolute bottleneck:
- Massive Models (70B+ Parameters): When the model weights alone exceed the VRAM of a single GPU. For example, a 70B model in FP16 takes ~140GB; if your GPUs only have 80GB each, ZeRO-3 is required to "spread" the model.
- Extremely Limited GPU VRAM: If you are trying to fine-tune a 7B or 13B model on consumer GPUs (like 12GB or 24GB cards), ZeRO-3 with CPU Offloading is often the only way to avoid "Out of Memory" (OOM) errors.
- Large Batch Sizes or Long Context: If you need to use a very long context window (e.g., 32k tokens), the "Activation Memory" grows significantly. ZeRO-3 frees up the VRAM usually taken by weights to make room for these activations.
- When QLoRA is not enough: While QLoRA (4-bit) saves space, it still replicates the model weights. ZeRO-3 is an alternative (or sometimes a partner) when you need to scale beyond what a single-device view of the model allows.

In [ ]:
%%capture
!pip install mpi4py
import torch
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    DataCollatorForLanguageModeling,
    TrainingArguments,
    Trainer,
)
from datasets import DatasetDict, Dataset

In [7]:
MODEL_NAME = "meta-llama/Llama-3.2-1B"
OUTPUT_DIR = "./llama-3.2-1B-finetuned-qa"
MAX_LENGTH = 128

# DeepSpeed config for ZeRO Stage 3 with explicit values
deepspeed_config = {
    "train_batch_size": 4,
    "train_micro_batch_size_per_gpu": 1,
    "gradient_accumulation_steps": 4,
    
    "zero_optimization": {
        "stage": 3,
        "offload_optimizer": {
            "device": "cpu",
            "pin_memory": True
        },
        "offload_param": {
            "device": "cpu",
            "pin_memory": True
        },
        "overlap_comm": True,
        "contiguous_gradients": True,
        "reduce_bucket_size": 500000000,
        "stage3_prefetch_bucket_size": 50000000,
        "stage3_param_persistence_threshold": 10000000,
        "stage3_max_live_parameters": 1000000000,
        "stage3_max_reuse_distance": 1000000000,
        "stage3_gather_16bit_weights_on_model_save": True
    },
    
    "optimizer": {
        "type": "AdamW",
        "params": {
            "lr": 2e-5,
            "weight_decay": 0.01,
        }
    },
    "scheduler": {
        "type": "WarmupCosineLR",
        "params": {
            "total_num_steps": "auto", 
            "warmup_num_steps": "auto", 
            "warmup_min_ratio": 0.0,    
            "cos_min_ratio": 0.0001     
        }
    },
    
    "fp16": {
        "enabled": True,
    },
    
    "gradient_clipping": 1.0,
    "steps_per_print": 50,
}

In [8]:
# Load tokenizer
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
tokenizer.pad_token = tokenizer.eos_token

# Prepare training data
train_texts = [
    f"<bos>Question: {row['question_title']}\n{row['question_body']}\nAnswer: {row['answer']}<eos>"
    for row in train_data.iter_rows(named=True)
]
val_texts = [
    f"<bos>Question: {row['question_title']}\n{row['question_body']}\nAnswer: {row['answer']}<eos>"
    for row in val_data.iter_rows(named=True)
]

# Tokenize data
train_tokenized = tokenizer(
    train_texts,
    truncation=True,
    max_length=MAX_LENGTH,
    padding="max_length",
    return_tensors="pt"
)
train_tokenized["labels"] = train_tokenized["input_ids"].clone()

val_tokenized = tokenizer(
    val_texts,
    truncation=True,
    max_length=MAX_LENGTH,
    padding="max_length",
    return_tensors="pt"
)
val_tokenized["labels"] = val_tokenized["input_ids"].clone()

# Create datasets
dataset_dict = DatasetDict({
    "train": Dataset.from_dict({
        "input_ids": train_tokenized["input_ids"],
        "attention_mask": train_tokenized["attention_mask"],
        "labels": train_tokenized["labels"]
    }),
    "validation": Dataset.from_dict({
        "input_ids": val_tokenized["input_ids"],
        "attention_mask": val_tokenized["attention_mask"],
        "labels": val_tokenized["labels"]
    })
})

config.json:   0%|          | 0.00/843 [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/50.5k [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/9.09M [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/301 [00:00<?, ?B/s]

In [ ]:
# Load model for ZeRO-3 (no device_map, no quantization)
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    torch_dtype=torch.float16,
)

# Data collator
data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

monitor = EpochMonitor(model=model)

# Training arguments
training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=1,
    per_device_eval_batch_size=1,
    gradient_accumulation_steps=4,
    learning_rate=2e-5,
    weight_decay=0.01,
    warmup_steps=100,
    fp16=True,
    lr_scheduler_type="cosine",
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    deepspeed=deepspeed_config,
    gradient_checkpointing=True,
    ddp_find_unused_parameters=False,
)

# Initialize trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
)

# Train with DeepSpeed ZeRO-3
train_result = trainer.train()

# Save model and tokenizer
trainer.save_model(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)

`torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors:   0%|          | 0.00/2.47G [00:00<?, ?B/s]

Loading weights:   0%|          | 0/146 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/185 [00:00<?, ?B/s]

Gradient accumulation steps mismatch: GradientAccumulationPlugin has 1, DeepSpeed config has 4. Using DeepSpeed's value.

Installed CUDA version 12.0 does not match the version torch was compiled with 12.8 but since the APIs are compatible, accepting this combination
Stage 3 initialize beginning
MA 2.3 GB         Max_MA 2.3 GB         CA 2.3 GB         Max_CA 2 GB
CPU Virtual Memory:  used = 4.84 GB, percent = 11.0%
DeepSpeedZeRoOffload initialize [begin]
MA 2.3 GB         Max_MA 2.3 GB         CA 2.3 GB         Max_CA 2 GB
CPU Virtual Memory:  used = 4.98 GB, percent = 11.3%
Parameter Offload - Persistent parameters statistics: param_count = 97, numel = 167839744
DeepSpeedZeRoOffload initialize [end]
MA 0.0 GB         Max_MA 2.3 GB         CA 2.3 GB         Max_CA 2 GB
CPU Virtual Memory:  used = 7.36 GB, percent = 16.7%
Before creating fp16 partitions
MA 0.0 GB         Max_MA 0.0 GB         CA 2.3 GB         Max_CA 2 GB
CPU Virtual Memory:  used = 7.36 GB, percent = 16.7%
After creating fp16 partitions: 2
MA 0.0 GB         Max_MA 0.0 GB         CA 2.3 GB         Max_CA 2 GB
CPU Virtual Memory:  used = 11.43 GB, percent = 25.9%
Before creating fp32 partitions
MA 0.0 GB         Max_MA 0.0 GB         CA 2.3 GB         Max_CA 2 GB
CPU Virtual Memory:  used = 11.43 GB, percent = 25.9%
After creating fp32 partitions
MA 0.0 GB         Max_MA 0.0 GB         CA 2.3 GB         Max_CA 2 GB
CPU Virtual Memory:  used = 16.02 GB, percent = 36.3%
Before initializing optimizer states
MA 0.0 GB         Max_MA 0.0 GB         CA 2.3 GB         Max_CA 2 GB
CPU Virtual Memory:  used = 16.02 GB, percent = 36.3%
After initializing optimizer states
MA 0.0 GB         Max_MA 0.0 GB         CA 2.3 GB         Max_CA 2 GB
CPU Virtual Memory:  used = 21.16 GB, percent = 48.0%
After initializing ZeRO optimizer
MA 0.93 GB         Max_MA 1.91 GB         CA 3.73 GB         Max_CA 4 GB
CPU Virtual Memory:  used = 25.25 GB, percent = 57.3%
[2026-02-14 04:31:37,091] [WARNING] [lr_schedules.py:862:get_lr] Attempting to get learning rate from scheduler before it has started

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

**Reference**
- [Arxiv:ZeRO: Memory Optimizations Toward Training Trillion Parameter Models](https://arxiv.org/abs/1910.02054)
- [Arxiv:DeepZero: Scaling up Zeroth-Order Optimization for Deep Model Training](https://arxiv.org/abs/2310.02025)
- [Arxiv:Distributed Delayed Stochastic Optimization](https://arxiv.org/abs/1104.5525)
- [Huggingface:DeepSpeed](https://huggingface.co/docs/accelerate/en/usage_guides/deepspeed)
- [GitHub:DeepSpeed](https://github.com/deepspeedai/DeepSpeed)
- [DeepSpeed:ZeRO](https://deepspeed.readthedocs.io/en/latest/zero3.html)
- [DeepSpeed:Zero Redundancy Optimizer](https://www.deepspeed.ai/tutorials/zero/)
- [Arxiv:DeepCompile: A Compiler-Driven Approach to Optimizing Distributed Deep Learning Training](https://arxiv.org/html/2504.09983v1)
- [DeepSpeed:Zero Redundancy Optimizer](https://www.deepspeed.ai/tutorials/zero/)
- [Huggingface:ZeRO Optimization Strategies for Large-Scale Model Training - A brief Performance Analysis](https://huggingface.co/blog/josh-a/zero-optimization-strategies)
- [APXML:Using DeepSpeed ZeRO Optimizations](https://apxml.com/courses/how-to-build-a-large-language-model/chapter-16-implementing-distributed-training-frameworks/using-deepspeed-zero-optimizations)
- [DeepSpeed:Training API](https://deepspeed.readthedocs.io/en/latest/training.html)
- [Huggingface:PEFT](https://huggingface.co/docs/peft/en/index)
- [Huggingface:Quantization](https://huggingface.co/docs/peft/en/developer_guides/quantization)

#### ZeRO-Offload (CPU Offloading)

ZeRO-Offload and ZeRO-Infinity are heterogeneous memory technologies that allow for training models far larger than what can fit in a single GPU's VRAM. By leveraging the host's CPU RAM and NVMe SSDs as an extension of GPU memory, these strategies "break the memory wall."

**What are ZeRO-Offload and ZeRO-Infinity?**

- ZeRO-Offload: Specifically designed for ZeRO Stage 2. It offloads the optimizer states and gradients to the CPU. Since the Adam optimizer requires 32-bit buffers for every parameter, moving these to the CPU frees up nearly 80% of the VRAM typically used by the optimizer, allowing a single GPU to train models with up to 13 billion parameters.
- ZeRO-Infinity: An evolution designed for ZeRO Stage 3. It can offload everything—optimizer states, gradients, and the model parameters themselves—to both CPU RAM and NVMe SSDs. It uses "memory-centric tiling" to process massive layers in small chunks, theoretically enabling a single node to fine-tune models with 1 trillion+ parameters.

**How it Works**

These systems treat the computer's memory as a hierarchy (GPU VRAM → CPU RAM → NVMe).
- Computation Placement: The "heavy lifting" (forward and backward passes) stays on the GPU. The optimizer update (the math that changes the weights) is moved to the CPU.
- Optimizer Offloading: During the backward pass, gradients are computed on the GPU and then "pushed" to the CPU. The CPU updates the weights and then "pushes" the new weights back to the GPU for the next round.
- NVMe Integration (Infinity): If even CPU RAM is full, ZeRO-Infinity streams data directly from the NVMe SSD to the GPU. It uses high-speed asynchronous I/O to "prefetch" the next layer's weights while the current one is still calculating, hiding the slowness of the disk.

**ZeRO-Offload Implementation**

The provided script uses ZeRO-Offload within a Stage 2 setup.

The Offload Trigger: The `offload_optimizer` and `offload_param` blocks in the `zero_optimization` config are the key.

    "offload_optimizer": {"device": "cpu", "pin_memory": True},
    "offload_param": {"device": "cpu", "pin_memory": True}

- `device: "cpu"`: Instructs DeepSpeed to move these components to the host RAM.
- `pin_memory: True`: Tells the system to use "locked" CPU memory, which allows for significantly faster data transfers (PCIe DMA) between the CPU and GPU.

**Contiguous Gradients:**

The setting `"contiguous_gradients": True` groups gradients into a single large buffer before offloading. This makes the transfer to the CPU much more efficient than sending thousands of tiny individual tensors.

**Standard Model Loading:**

Because this script uses Stage 2, the model is loaded normally on the GPU. DeepSpeed then intervenes to move the optimizer states to the CPU as soon as the training starts.

**Note:** For true ZeRO-Infinity (NVMe), the device would be set to `"nvme"` and a `nvme_path` would be provided.

**When to Use It**

- Offloading is a trade-off: you gain massive memory but lose some speed due to the time it takes to move data across the PCIe bus.
- Hardware Bottlenecks: Use it when you are training on consumer GPUs (like an RTX 3090/4090) or mid-tier enterprise cards (A10) and keep hitting "Out of Memory" errors even with Stage 2 or 3 enabled.
- Single-GPU Power: Use ZeRO-Offload if you only have one GPU but want to train a model larger than 2B parameters. It is the only way to train a 13B model on a single 80GB A100.
- Huge Parameter Counts: Use ZeRO-Infinity (NVMe) when your model is so massive (e.g., 70B+ or 175B+) that it exceeds the combined VRAM of your entire cluster and your available CPU RAM.
- Fine-tuning Focus: Offloading is excellent for fine-tuning because the slightly slower speed is often acceptable given that fine-tuning usually requires fewer total steps than pre-training.

In [ ]:
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, DataCollatorForLanguageModeling, TrainingArguments, Trainer
from datasets import DatasetDict, Dataset

In [11]:
MODEL_NAME = "meta-llama/Llama-3.2-1B"
OUTPUT_DIR = "./llama-3.2-1B-finetuned-qa"
MAX_LENGTH = 128

deepspeed_config = {
    "train_batch_size": "auto",
    "train_micro_batch_size_per_gpu": "auto",
    "gradient_accumulation_steps": "auto",
    "zero_optimization": {
        "stage": 2,
        "offload_optimizer": {"device": "cpu", "pin_memory": True},
        "offload_param": {"device": "cpu", "pin_memory": True},
        "overlap_comm": True,
        "contiguous_gradients": True,
        "reduce_bucket_size": 2e8,
        "allgather_bucket_size": 2e8,
    },
    "optimizer": {"type": "AdamW", "params": {"lr": "auto", "weight_decay": "auto"}},
    "scheduler": {
    "type": "WarmupCosineLR",
    "params": {
        "total_num_steps": "auto", 
        "warmup_num_steps": "auto", 
        "warmup_min_ratio": 0.0,    
        "cos_min_ratio": 0.0001     
        }
    },
    "fp16": {"enabled": "auto"},
    "gradient_clipping": "auto",
}

In [12]:
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
tokenizer.pad_token = tokenizer.eos_token

train_texts = [f"<bos>Question: {row['question_title']}\n{row['question_body']}\nAnswer: {row['answer']}<eos>" for row in train_data.iter_rows(named=True)]
val_texts = [f"<bos>Question: {row['question_title']}\n{row['question_body']}\nAnswer: {row['answer']}<eos>" for row in val_data.iter_rows(named=True)]

train_tokenized = tokenizer(train_texts, truncation=True, max_length=MAX_LENGTH, padding="max_length", return_tensors="pt")
train_tokenized["labels"] = train_tokenized["input_ids"].clone()

val_tokenized = tokenizer(val_texts, truncation=True, max_length=MAX_LENGTH, padding="max_length", return_tensors="pt")
val_tokenized["labels"] = val_tokenized["input_ids"].clone()

dataset_dict = DatasetDict({
    "train": Dataset.from_dict({"input_ids": train_tokenized["input_ids"], "attention_mask": train_tokenized["attention_mask"], "labels": train_tokenized["labels"]}),
    "validation": Dataset.from_dict({"input_ids": val_tokenized["input_ids"], "attention_mask": val_tokenized["attention_mask"], "labels": val_tokenized["labels"]})
})

In [ ]:
model = AutoModelForCausalLM.from_pretrained(MODEL_NAME, torch_dtype=torch.float16)

data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

monitor = EpochMonitor(model=model)

training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=1,
    per_device_eval_batch_size=1,
    gradient_accumulation_steps=4,
    learning_rate=2e-5,
    weight_decay=0.01,
    warmup_steps=100,
    fp16=True,
    lr_scheduler_type="cosine",
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    deepspeed=deepspeed_config,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
    callbacks = [monitor]
)

train_result = trainer.train()
trainer.save_model(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)

**Reference**
- [DeepSpeed:DeepSpeed ZeRO-3 Offload](https://www.deepspeed.ai/2021/03/07/zero3-offload.html)
- [Arxiv:ZeRO: Memory Optimizations Toward Training Trillion Parameter Models](https://arxiv.org/abs/1910.02054)
- [Arxiv:DeepZero: Scaling up Zeroth-Order Optimization for Deep Model Training](https://arxiv.org/abs/2310.02025)
- [Arxiv:Distributed Delayed Stochastic Optimization](https://arxiv.org/abs/1104.5525)
- [Huggingface:DeepSpeed](https://huggingface.co/docs/accelerate/en/usage_guides/deepspeed)
- [GitHub:DeepSpeed](https://github.com/deepspeedai/DeepSpeed)
- [DeepSpeed:ZeRO](https://deepspeed.readthedocs.io/en/latest/zero3.html)
- [DeepSpeed:Zero Redundancy Optimizer](https://www.deepspeed.ai/tutorials/zero/)
- [Arxiv:DeepCompile: A Compiler-Driven Approach to Optimizing Distributed Deep Learning Training](https://arxiv.org/html/2504.09983v1)
- [DeepSpeed:Zero Redundancy Optimizer](https://www.deepspeed.ai/tutorials/zero/)
- [Huggingface:ZeRO Optimization Strategies for Large-Scale Model Training - A brief Performance Analysis](https://huggingface.co/blog/josh-a/zero-optimization-strategies)
- [APXML:Using DeepSpeed ZeRO Optimizations](https://apxml.com/courses/how-to-build-a-large-language-model/chapter-16-implementing-distributed-training-frameworks/using-deepspeed-zero-optimizations)
- [DeepSpeed:Training API](https://deepspeed.readthedocs.io/en/latest/training.html)
- [Huggingface:PEFT](https://huggingface.co/docs/peft/en/index)
- [Huggingface:Quantization](https://huggingface.co/docs/peft/en/developer_guides/quantization)

#### ZeRO-3 and CPU Offload Combination

ZeRO-3 (Zero Redundancy Optimizer Stage 3) is a memory-saving technology developed by Microsoft DeepSpeed that enables the training of models far larger than the memory capacity of a single GPU. While standard data parallelism replicates the entire model on every GPU, ZeRO-3 shards (partitions) all three main memory consumers—optimizer states, gradients, and model parameters—across the entire distributed system.

CPU Offloading acts as an auxiliary extension to ZeRO. It moves the storage and computation of optimizer updates and parameters from the high-cost VRAM of the GPU to the high-capacity system memory (RAM) of the CPU. This combination allows for training models with billions of parameters on hardware that would otherwise experience "Out of Memory" (OOM) errors.

**How the Optimization Works**

ZeRO-3 operates on a "need-to-know" basis during the training process:
- Parameter Sharding: The model weights are divided among all available GPUs. No single GPU holds a complete copy of the model.
- On-the-Fly Reconstruction: During the forward and backward passes, the specific weights needed for a layer are temporarily gathered (broadcasted) from other GPUs. Once the computation for that layer is finished, the GPU immediately discards the full weights and reverts to holding only its assigned shard.
- CPU Offloading:
    - Offload Optimizer: The AdamW optimizer states (momentum and variance) stay in the CPU RAM. The CPU performs the weight update calculation, saving significant VRAM.
    - Offload Param: Model parameters can also be stored in CPU RAM when not actively being used for a layer calculation.
- Overlap Communication: DeepSpeed overlaps the gathering of weights for the next layer with the computation of the current layer to hide the latency caused by moving data across the PCIe bus or network.

**ZeRO-3 and CPU Offload Implementation**

The script leverages the Hugging Face Trainer integrated with a DeepSpeed configuration file to implement these optimizations:

- `"stage": 3`: This directive activates ZeRO-3, ensuring that the model parameters, gradients, and optimizer states are sharded across all detected GPUs.
- `"offload_optimizer": {"device": "cpu"}`: This configuration moves the heaviest memory consumer (optimizer states) to the system RAM. For a typical AdamW optimizer, this saves 12 bytes of memory per parameter on the GPU.
- `"offload_param": {"device": "cpu"}`: This offloads the model parameters themselves to the CPU, only bringing them to the GPU during the actual mathematical execution of a layer.
- `"pin_memory": True`: This optimizes the data transfer between CPU and GPU by using "page-locked" memory, which allows for significantly faster PCIe transfers.
- `model.gradient_checkpointing_enable()`: Combined with ZeRO-3, this further reduces VRAM usage by not storing intermediate activations during the forward pass, re-calculating them instead during the backward pass.

**When to Use It**

Use ZeRO-3 + CPU Offload when:
- Massive Model Sizes: The model is too large to fit into a single GPU's VRAM even at Stage 1 or 2 (e.g., trying to fine-tune a 7B+ parameter model on consumer-grade 24GB GPUs).
- Limited GPU Memory: When working with entry-level GPUs or cloud instances with small VRAM allocations but large system RAM.
- Large Batch Sizes: When there is a need to increase the batch size to stabilize training but no VRAM is left to accommodate the extra data.

Avoid ZeRO-3 + CPU Offload when:
- The Model Fits in VRAM: ZeRO-3 introduces communication overhead. If a model fits comfortably on the GPU using ZeRO-1 or ZeRO-2, Stage 3 will likely be slower.
- Slow Interconnects: If the connection between the CPU and GPU (PCIe) or between GPUs is slow, the time spent moving shards will drastically increase training time.
- Small Models: For models under 1 billion parameters, the administrative overhead of sharding parameters may outweigh the memory benefits.

In [ ]:
%%capture
!pip install mpi4py
import torch
import os
from transformers import (
    AutoTokenizer, 
    AutoModelForCausalLM, 
    DataCollatorForLanguageModeling,
    TrainingArguments, 
    Trainer,
)
from datasets import Dataset, DatasetDict
import deepspeed

In [ ]:
# Set environment variables for distributed training
os.environ["MASTER_ADDR"] = "localhost"
os.environ["MASTER_PORT"] = "9994"
os.environ["RANK"] = "0"
os.environ["WORLD_SIZE"] = str(torch.cuda.device_count())
os.environ["LOCAL_RANK"] = "0"

# Check CUDA availability and GPU count
print(f"CUDA available: {torch.cuda.is_available()}")
gpu_count = torch.cuda.device_count()
print(f"Number of GPUs detected: {gpu_count}")

if gpu_count == 0:
    raise RuntimeError(
        "No GPUs detected. DeepSpeed ZeRO-3 requires at least one CUDA-enabled GPU. "
        "Please check your CUDA installation and GPU availability."
    )

print(f"GPU(s) detected: {[torch.cuda.get_device_name(i) for i in range(gpu_count)]}")

# Configuration
MODEL_NAME = "google/gemma-3-270m"
OUTPUT_DIR = "./gemma-3-270m-finetuned-deepspeed"
MAX_LENGTH = 128

# Tokenization
print(f"\nLoading tokenizer: {MODEL_NAME}")
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
tokenizer.pad_token = tokenizer.eos_token
print(f"Tokenizer loaded. Vocab size: {len(tokenizer)}")

def tokenize_examples(df, max_length=MAX_LENGTH):
    texts = [f"<bos>Question: {row['question_title']}\n{row['question_body']}\nAnswer: {row['answer']}<eos>" 
             for row in df.iter_rows(named=True)]
    tokenized = tokenizer(
        texts,
        truncation=True,
        max_length=max_length,
        padding="max_length",
        return_tensors="pt"
    )
    tokenized["labels"] = tokenized["input_ids"].clone()
    return tokenized

print("Tokenizing training data...")
train_tokenized = tokenize_examples(train_data)
print("Tokenizing validation data...")
val_tokenized = tokenize_examples(val_data)

# Create datasets - keep as tensors
dataset_dict = DatasetDict({
    "train": Dataset.from_dict({
        "input_ids": train_tokenized["input_ids"],
        "attention_mask": train_tokenized["attention_mask"],
        "labels": train_tokenized["labels"]
    }),
    "validation": Dataset.from_dict({
        "input_ids": val_tokenized["input_ids"],
        "attention_mask": val_tokenized["attention_mask"],
        "labels": val_tokenized["labels"]
    })
})
print(f"Train examples: {len(dataset_dict['train']):,}")
print(f"Validation examples: {len(dataset_dict['validation']):,}")

# DeepSpeed Configuration
per_device_batch_size = 1
gradient_accumulation_steps = 4

deepspeed_config = {
    "train_batch_size": per_device_batch_size * gradient_accumulation_steps * gpu_count,
    "train_micro_batch_size_per_gpu": per_device_batch_size,
    "gradient_accumulation_steps": gradient_accumulation_steps,
    
    "zero_optimization": {
        "stage": 3,
        "offload_optimizer": {
            "device": "cpu",
            "pin_memory": True
        },
        "offload_param": {
            "device": "cpu",
            "pin_memory": True
        },
        "overlap_comm": True,
        "contiguous_gradients": True,
        "reduce_bucket_size": 5e8,
        "stage3_prefetch_bucket_size": 5e8,
        "stage3_param_persistence_threshold": 1e6,
        "gather_16bit_weights_on_model_save": True
    },
    
    "fp16": {
        "enabled": True,
        "auto_cast": True,
        "loss_scale": 0,
        "initial_scale_power": 16
    },
    
    "gradient_clipping": 1.0,
    "steps_per_print": 50,
    
    # Don't include optimizer/scheduler here - let HF handle them
    "wall_clock_breakdown": False
}

# Save config to file (more reliable than passing dict)
with open("ds_config.json", "w") as f:
    json.dump(deepspeed_config, f)

print("DeepSpeed configuration created")

# Load Model
print(f"\nLoading {MODEL_NAME}...")

# Initialize DeepSpeed engine first
deepspeed.init_distributed()

# Load model - use from_pretrained with specific settings for ZeRO-3
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    torch_dtype=torch.float16,
    low_cpu_mem_usage=True,
    use_cache=False
)

print(f"Model loaded successfully")

# Enable gradient checkpointing
model.gradient_checkpointing_enable()

# Training Setup with DeepSpeed
data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

# Training arguments
training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=per_device_batch_size,
    per_device_eval_batch_size=1,
    gradient_accumulation_steps=gradient_accumulation_steps,
    learning_rate=2e-5,
    weight_decay=0.01,
    warmup_steps=100,
    lr_scheduler_type="cosine",
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_strategy="steps",
    logging_steps=10,
    fp16=True,
    deepspeed="ds_config.json",  # Use file path instead of dict
    gradient_checkpointing=True,
    ddp_find_unused_parameters=False,
    optim="adamw_torch",
    dataloader_num_workers=0,
    local_rank=int(os.environ["LOCAL_RANK"]),
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
    tokenizer=tokenizer
)

# Training with DeepSpeed
print(f"\nDeepSpeed ZeRO-3 Stage: Enabled")
print(f"CPU Offload: Enabled")
print(f"Activation Checkpointing: Enabled")
print(f"Mixed Precision: FP16")
print(f"Number of GPUs: {gpu_count}")
print("Starting training with DeepSpeed optimizations...")

train_result = trainer.train()

# Save Model
trainer.save_model()
tokenizer.save_pretrained(OUTPUT_DIR)
print(f"\nTraining completed. Model saved to {OUTPUT_DIR}")

print("\n" + "="*60)
print("DEEPSPEED OPTIMIZATION BENEFITS")
print("="*60)
print("ZeRO-3 Stage:")
print("  - Partitions optimizer states, gradients, and parameters")
print("  - Reduces per-GPU memory footprint")
print("CPU Offload Engine:")
print("  - Offloads optimizer states and parameters to CPU")
print("Activation Checkpointing:")
print("  - Reduces memory from activations")
print(f"GPUs used: {gpu_count}")
print("="*60)

CUDA available: True
Number of GPUs detected: 2
GPU(s) detected: ['Tesla T4', 'Tesla T4']

Loading tokenizer: google/gemma-3-270m
Tokenizer loaded. Vocab size: 262145
Tokenizing training data...
Tokenizing validation data...
Train examples: 133
Validation examples: 28
DeepSpeed configuration created

Loading google/gemma-3-270m...

**Reference**
- [DeepSpeed:DeepSpeed ZeRO-3 Offload](https://www.deepspeed.ai/2021/03/07/zero3-offload.html)
- [Arxiv:ZeRO: Memory Optimizations Toward Training Trillion Parameter Models](https://arxiv.org/abs/1910.02054)
- [Arxiv:DeepZero: Scaling up Zeroth-Order Optimization for Deep Model Training](https://arxiv.org/abs/2310.02025)
- [Arxiv:Distributed Delayed Stochastic Optimization](https://arxiv.org/abs/1104.5525)
- [Huggingface:DeepSpeed](https://huggingface.co/docs/accelerate/en/usage_guides/deepspeed)
- [GitHub:DeepSpeed](https://github.com/deepspeedai/DeepSpeed)
- [DeepSpeed:ZeRO](https://deepspeed.readthedocs.io/en/latest/zero3.html)
- [DeepSpeed:Zero Redundancy Optimizer](https://www.deepspeed.ai/tutorials/zero/)
- [Arxiv:DeepCompile: A Compiler-Driven Approach to Optimizing Distributed Deep Learning Training](https://arxiv.org/html/2504.09983v1)
- [DeepSpeed:Zero Redundancy Optimizer](https://www.deepspeed.ai/tutorials/zero/)
- [Huggingface:ZeRO Optimization Strategies for Large-Scale Model Training - A brief Performance Analysis](https://huggingface.co/blog/josh-a/zero-optimization-strategies)
- [APXML:Using DeepSpeed ZeRO Optimizations](https://apxml.com/courses/how-to-build-a-large-language-model/chapter-16-implementing-distributed-training-frameworks/using-deepspeed-zero-optimizations)
- [DeepSpeed:Training API](https://deepspeed.readthedocs.io/en/latest/training.html)
- [Huggingface:PEFT](https://huggingface.co/docs/peft/en/index)
- [Huggingface:Quantization](https://huggingface.co/docs/peft/en/developer_guides/quantization)

### Hybrid Parallelism

Hybrid Parallelism is the strategic combination of multiple distributed training techniques to overcome the limitations of any single method. While ZeRO-3 or 3D Parallelism are powerful, modern "Frontier" models are now so complex that they require a mix-and-match approach to balance memory, compute speed, and network latency.

**1. 3D Parallelism: The "Foundation"**

This is the simultaneous use of Data (DP), Tensor (TP), and Pipeline (PP) parallelism. It is typically visualized as a 3D grid where each axis handles a different scaling problem.

**2. Sequence Parallelism (SP)**

Sequence Parallelism is a specialized "4th dimension" added to 3D parallelism. In traditional TP, while weights are sharded, certain "activations" (like LayerNorm and Dropout) are still replicated, which creates a memory bottleneck as sequence lengths grow (e.g., from 4k to 128k tokens).

**3. Selective Replication**

Not every part of an LLM is the same size. Selective Replication moves away from the "one-size-fits-all" sharding of ZeRO-3.

**4. Adaptive Strategy Selection**

This is the "AI for AI" approach. Instead of a human developer manually setting sharding rules, a software framework (like ParaDySe or Ray) chooses the strategy for you.

**Reference**
- [Arxiv:PAFT: A Parallel Training Paradigm for Effective LLM Fine-Tuning](https://arxiv.org/abs/2406.17923)
- [ACM:Parallelization Techniques for Large Language Models: A Review from Training to Inference](https://dl.acm.org/doi/10.1007/978-981-96-8725-1_25)
- [Huggingface:Parallelism methods](https://huggingface.co/docs/transformers/en/perf_train_gpu_many)
- [Arxiv:Distributed Hybrid Parallelism for Large Language Models: Comparative Study and System Design Guide](https://arxiv.org/html/2602.09109v1)
- [Nvidia:Optimizing Communication for Mixture-of-Experts Training with Hybrid Expert Parallel](https://developer.nvidia.com/blog/optimizing-communication-for-mixture-of-experts-training-with-hybrid-expert-parallel/)
- [Arxiv:Distributed Hybrid Parallelism for Large Language Models: Comparative Study and System Design Guide](https://www.arxiv.org/abs/2602.09109)
- [ACM:Chimera: Communication Fusion for Hybrid Parallelism in Large Language Models](https://dl.acm.org/doi/10.1145/3695053.3731025)

#### 3D Parallelism (Data, Tensor, Pipeline)

3D Parallelism is a highly advanced distributed training strategy that integrates three orthogonal methods of parallelism: Data Parallelism (DP), Tensor Parallelism (TP), and Pipeline Parallelism (PP). This approach is designed to overcome the physical memory and bandwidth limitations of individual GPUs when training Large Language Models (LLMs) with billions or trillions of parameters.

**How 3D Parallelism Works**

The "3D" naming convention refers to the logical organization of GPUs into a three-dimensional grid, where each axis addresses a specific scaling bottleneck.
- Tensor Parallelism (Horizontal Scaling): Within a single model layer, large matrices (like those in self-attention or feed-forward blocks) are split across multiple GPUs. This allows a single mathematical operation to be performed in parallel, effectively sharding the "width" of the model.
- Pipeline Parallelism (Vertical Scaling): The model is split by layers into different "stages." For example, the first 10 layers stay on GPU group A, while the next 10 move to GPU group B. Data flows through these stages like an assembly line, sharding the "depth" of the model.
- Data Parallelism (Batch Scaling): The entire "sharded" model setup described above is replicated. Each replica processes a different subset of the training data simultaneously, which increases the overall training throughput.

**3D Parallelism Implementation**

The provided script utilizes the DeepSpeed library to orchestrate these dimensions. It transitions from standard sequential PyTorch logic to a distributed engine that manages sharding and inter-GPU communication.
- Topology Definition: The `ds_config` dictionary sets the grid dimensions. By setting `"tp_size": 2` and defining `"pipeline": {"stages": "auto"}`, the script instructs DeepSpeed to divide the 8 available GPUs into a 2x2x2 grid (TP=2×PP=2×DP=2=8 GPUs).
- Memory-Efficient Initialization: The use of with `deepspeed.zero.Init():` is crucial. It ensures that the model parameters are never fully loaded into a single GPU's memory at once. Instead, they are initialized in a sharded state across the cluster, preventing "Out of Memory" (OOM) errors before training even begins.
- Pipeline Micro-Batching: The script defines `train_micro_batch_size_per_gpu: 1` and `gradient_accumulation_steps: 4`. This creates the "pipeline" flow where small chunks of data are passed between stages, ensuring that GPUs in later stages aren't sitting idle while waiting for earlier stages to finish.
- Unified Training Step: The command `model_engine.train_batch(batch)` replaces the traditional manual backward pass and optimizer step. This single call handles the complex synchronization required to communicate sharded tensors (TP), hidden states between stages (PP), and gradients across replicas (DP/ZeRO-1).

**When to Use It**

3D Parallelism should be used in specific high-scale scenarios:
- Extreme Model Scale: When a model exceeds 20B–70B parameters. At this size, even advanced techniques like ZeRO-3 may not provide enough memory savings on a single node, requiring Pipeline Parallelism to stretch the model across multiple nodes.
- Massive Compute Clusters: When training on 64 or more GPUs. Standard Data Parallelism suffers from diminishing returns due to the massive communication overhead of synchronizing gradients; 3D Parallelism keeps communication localized and efficient.
- Wide Architectures: When a model has extremely large hidden dimensions (e.g., 8192 or higher). Tensor Parallelism becomes necessary to shard the activations of these massive layers so they fit into VRAM.
- Efficiency Requirements: When you need to maximize the "Model Flops Utilization" (MFU) of high-end hardware like NVIDIA H100s, where keeping the silicon busy requires overlapping data transfers with computation.

In [ ]:
import os
import json
import torch
import deepspeed
import polars as pl
from tqdm import tqdm
from torch.utils.data import Dataset
from sklearn.model_selection import train_test_split
from transformers import (
    AutoTokenizer, 
    AutoConfig,
    AutoModelForCausalLM, 
    DataCollatorForLanguageModeling
)

In [ ]:
# Data Preparation (Polars) 
unique_questions = qa_selected["question_title"].unique().to_list()
train_questions, temp_questions = train_test_split(unique_questions, test_size=0.2, random_state=42)
test_questions, val_questions = train_test_split(temp_questions, test_size=0.3, random_state=42)

train_data = qa_selected.filter(pl.col("question_title").is_in(train_questions))
val_data = qa_selected.filter(pl.col("question_title").is_in(val_questions))

# Configuration
MODEL_NAME = "meta-llama/Llama-3.2-1B"
OUTPUT_DIR = "./llama-3.2-1B-3D"
MAX_LENGTH = 128

# 3D Parallelism Configuration (for 8 GPUs)
# TP_SIZE * PP_SIZE * DP_SIZE = Total GPUs
# 2 * 2 * 2 = 8
ds_config = {
    "train_batch_size": 16,
    "train_micro_batch_size_per_gpu": 1,
    "gradient_accumulation_steps": 4,
    "bf16": {"enabled": True},
    "zero_optimization": {
        "stage": 1  # ZeRO-1 is most stable with Pipeline Parallelism
    },
    "pipeline": {
        "stages": "auto",
        "partition_strategy": "balanced",
        "seed_layers": True,
        "activation_checkpointing": {
            "partition_activations": True,
            "cpu_checkpointing": True
        }
    },
    "tensor_parallel": {
        "tp_size": 2
    },
    "optimizer": {
        "type": "AdamW",
        "params": {
            "lr": 2e-5,
            "betas": [0.9, 0.95],
            "eps": 1e-8,
            "weight_decay": 0.01
        }
    }
}

# Distributed Initialization 
deepspeed.init_distributed()

# Tokenizer & Dataset 
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
tokenizer.pad_token = tokenizer.eos_token

class QADataset(Dataset):
    def __init__(self, df):
        self.rows = df.to_dicts()
    def __len__(self):
        return len(self.rows)
    def __getitem__(self, idx):
        row = self.rows[idx]
        text = f"Question: {row['question_title']}\n{row['question_body']}\nAnswer: {row['answer']}"
        tokenized = tokenizer(text, truncation=True, max_length=MAX_LENGTH, padding="max_length", return_tensors="pt")
        # Flatten the tensors for the DataLoader
        return {k: v.squeeze(0) for k, v in tokenized.items()}

train_dataset = QADataset(train_data)
val_dataset = QADataset(val_data)

# 3D Parallel Model Loading 
# We use AutoConfig to initialize the model layers across the 3D grid
config = AutoConfig.from_pretrained(MODEL_NAME)

# In DeepSpeed 3D, the model is initialized directly sharded
# This prevents OOM during the loading phase
with deepspeed.zero.Init():
    model = AutoModelForCausalLM.from_config(config)

# Initialize DeepSpeed Engine
model_engine, optimizer, _, _ = deepspeed.initialize(
    model=model,
    model_parameters=model.parameters(),
    config=ds_config
)

# Training Loop 
model_engine.train()
data_loader = model_engine.dist_dataloader(train_dataset)

for epoch in range(3):
    pbar = tqdm(data_loader) if model_engine.local_rank == 0 else data_loader
    for step, batch in enumerate(pbar):
        # Move batch to current GPU
        batch = {k: v.to(model_engine.device) for k, v in batch.items()}
        batch["labels"] = batch["input_ids"].clone()

        # train_batch() handles the 3D communication (TP, PP, and DP)
        loss = model_engine.train_batch(batch)

        if model_engine.local_rank == 0:
            pbar.set_description(f"Epoch {epoch+1} Loss: {loss.item():.4f}")

    # Save 3D sharded checkpoint
    model_engine.save_checkpoint(os.path.join(OUTPUT_DIR, f"checkpoint-ep{epoch}"))

if model_engine.local_rank == 0:
    print("Training Completed and Model Saved.")

**Reference**
- [Arxiv:Diving into 3D Parallelism with Heterogeneous Spot Instance GPUs: Design and Implications](https://arxiv.org/html/2512.20953v1)
- [ResearchGate:Pipeline and Tensor Parallelism Strategies for Training LLMs on Limited VRAM](https://www.researchgate.net/publication/398601065_Pipeline_and_Tensor_Parallelism_Strategies_for_Training_LLMs_on_Limited_VRAM)
- [Huggingface:Parallelism methods](https://huggingface.co/docs/transformers/en/perf_train_gpu_many)
- [Uvadlc:Part 5: Language Modeling with 3D Parallelism](https://uvadlc-notebooks.readthedocs.io/en/latest/tutorial_notebooks/scaling/JAX/3d_parallelism.html#3D-Parallelism)
- [Nvidia:Parallelisms Guide](https://docs.nvidia.com/nemo/megatron-bridge/0.2.0/parallelisms.html)
- [Arxiv:Accelerating Large Language Model Training with Hybrid GPU-based Compression](https://arxiv.org/abs/2409.02423)
- [PyTorch:Pipeline Parallelism](https://docs.pytorch.org/docs/stable/distributed.pipelining.html)
- [PyTorch:Introduction to Distributed Pipeline Parallelism](https://docs.pytorch.org/tutorials/intermediate/pipelining_tutorial.html)

#### Sequence Parallelism with DeepSpeed Ulysses

Sequence Parallelism is a distributed training technique designed to shard the sequence dimension of a single data sample across multiple GPUs. While Data Parallelism replicates the model and Tensor Parallelism shards model weights, Sequence Parallelism specifically addresses the memory bottleneck caused by long input sequences, where a single sequence (e.g., 32k or 128k tokens) produces activations too large for a single GPU's memory.

**How it Works**

In standard training, a GPU holds the entire sequence of tokens for its assigned batch. Sequence Parallelism breaks this sequence into chunks. For example, if the sequence length is 4,000 tokens and the sequence parallel size is 2, GPU 0 processes tokens 1–2,000, and GPU 1 processes tokens 2,001–4,000.

The primary mechanism involves sharding the activations and intermediate computations that are usually replicated in Tensor Parallelism, such as:
- Layer Normalization: Instead of every GPU in a tensor-parallel group calculating LayerNorm for the whole sequence, they only calculate it for their specific tokens.
- Dropout: Operations are sharded to save memory.
- Activation Sharding: By splitting the sequence, the memory required to store "activations" (the data passed between layers) is divided by the number of GPUs in the sequence parallel group.

During the Attention mechanism, the GPUs use specialized communication (all-to-all) to ensure each GPU can still attend to all tokens in the full sequence, even if it only "owns" a fragment of it.

**Sequence Parallelism Implementation**

The code enables Sequence Parallelism through the DeepSpeed configuration and the Megatron integration.

**Configuration Trigger:**

The variable `SEQUENCE_PARALLEL_SIZE = 2` acts as a flag. In the configuration dictionary, it specifically enables the Megatron-style sequence parallelism:

    deepspeed_config["megatron"] = {
        "sequence_parallelism": True
    }

**Memory Efficiency:**

By setting `zero_optimization: stage 3`, the code already shards parameters and gradients. Adding sequence parallelism ensures that even the activations—which scale linearly with sequence length—are sharded.

**Sparse Attention Integration:**

The code also configures `sparse_attention`. In long-sequence training, sequence parallelism is often paired with sparse attention to reduce the quadratic computational cost ($O(n^2)$) of the attention matrix to something more manageable ($O(n)$).

**Initialization Context:** 

The line `transformers.modeling_utils._is_ds_init_called = True` is used to signal to the Transformers library that DeepSpeed will handle the memory orchestration, which is vital when sharding sequences across devices.

**When to Use It**

Sequence Parallelism is not necessary for standard short-text tasks but is critical in the following scenarios:
- Long-Context Window Training: When training models to handle 32k, 64k, or 128k tokens. At these lengths, the activation memory (the memory needed for the forward pass) exceeds the GPU's VRAM long before the model weights do.
- Activation Bottlenecks: When using Tensor Parallelism (TP) and still hitting "Out of Memory" (OOM) errors. TP shards weights, but standard TP replicates activations; Sequence Parallelism shards those activations to bridge the gap.
- High-Resolution Multimodal Training: When training on images or videos where the "sequence" of visual patches is extremely long.
- Training with Small Batch Sizes: If memory constraints force a micro-batch size of 1, but the sequence length is still causing OOM, Sequence Parallelism is the only way to process that single sample.

In [ ]:
%%capture
!pip install mpi4py

import torch
from transformers import (
    AutoTokenizer, AutoModelForCausalLM, TrainingArguments, Trainer,
    DataCollatorForLanguageModeling
)
from datasets import Dataset, DatasetDict
import deepspeed
import json
import os
import torch.distributed as dist

In [ ]:
MODEL_NAME = "meta-llama/Llama-3.2-1B"
OUTPUT_DIR = "./llama-3.2-1B-finetuned-qa-sequence"
MAX_LENGTH = 128
MICRO_BATCH_SIZE = 1
GRADIENT_ACCUMULATION_STEPS = 4

os.makedirs(OUTPUT_DIR, exist_ok=True)

# Initialize distributed environment first
deepspeed.init_distributed()

world_size = dist.get_world_size()
local_rank = int(os.environ.get("LOCAL_RANK", 0))
rank = dist.get_rank()

if rank == 0:
    print(f"World size: {world_size}, Local rank: {local_rank}, Rank: {rank}")
    print(f"Loading tokenizer: {MODEL_NAME}")

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"

def tokenize_examples(examples, max_length=MAX_LENGTH):
    texts = [
        f"Question: {q_title}\n{q_body}\nAnswer: {answer}"
        for q_title, q_body, answer in zip(
            examples["question_title"],
            examples["question_body"],
            examples["answer"]
        )
    ]
    
    tokenized = tokenizer(
        texts,
        truncation=True,
        max_length=max_length,
        padding="max_length",
        return_tensors="pt"
    )
    
    labels = tokenized["input_ids"].clone()
    labels[labels == tokenizer.pad_token_id] = -100
    
    return {
        "input_ids": tokenized["input_ids"],
        "attention_mask": tokenized["attention_mask"],
        "labels": labels
    }

if rank == 0:
    print("Tokenizing training data...")
train_tokenized = tokenize_examples(train_data)

if rank == 0:
    print("Tokenizing validation data...")
val_tokenized = tokenize_examples(val_data)

dataset_dict = DatasetDict({
    "train": Dataset.from_dict(train_tokenized),
    "validation": Dataset.from_dict(val_tokenized)
})

if rank == 0:
    print(f"Train examples: {len(dataset_dict['train']):,}")
    print(f"Validation examples: {len(dataset_dict['validation']):,}")

train_batch_size = MICRO_BATCH_SIZE * GRADIENT_ACCUMULATION_STEPS * world_size

# DeepSpeed configuration with sequence parallelism
deepspeed_config = {
    "train_batch_size": "auto",
    "train_micro_batch_size_per_gpu": "auto",
    "gradient_accumulation_steps": "auto",
    "optimizer": {
        "type": "AdamW",
        "params": {
            "lr": 2e-5,
            "betas": [0.9, 0.999],
            "eps": 1e-8,
            "weight_decay": 0.01
        }
    },
    "scheduler": {
        "type": "WarmupLR",
        "params": {
            "warmup_min_lr": 0,
            "warmup_max_lr": 2e-5,
            "warmup_num_steps": 100
        }
    },
    "zero_optimization": {
        "stage": 3,
        "contiguous_gradients": True,
        "stage3_max_live_parameters": 1e9,
        "stage3_max_reuse_distance": 1e9,
        "stage3_prefetch_bucket_size": 1e7,
        "stage3_param_persistence_threshold": 1e5,
        "reduce_bucket_size": 5e8,
        "allgather_bucket_size": 5e8
    },
    "bf16": {"enabled": True},
    "gradient_clipping": 1.0,
    "steps_per_print": 100,
    "wall_clock_breakdown": False,
    "activation_checkpointing": {
        "partition_activations": True,
        "contiguous_memory_optimization": True,
        "number_checkpoints": None,
        "synchronize_checkpoint_boundary": False,
        "profile": False
    }
}

# Enable sequence parallelism through Megatron config
if world_size > 1:
    deepspeed_config["megatron"] = {
        "sequence_parallelism": True,
        "tp_size": world_size
    }

config_path = os.path.join(OUTPUT_DIR, "ds_config.json")
if rank == 0:
    with open(config_path, "w") as f:
        json.dump(deepspeed_config, f, indent=2)
    print(f"DeepSpeed config saved to {config_path}")

if rank == 0:
    print(f"Loading {MODEL_NAME}...")

# Disable DeepSpeed auto-initialization
import transformers
transformers.modeling_utils._is_ds_init_called = True

model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    torch_dtype=torch.bfloat16,
    low_cpu_mem_usage=True,
    attn_implementation="eager",
    use_cache=False
)

# Move model to correct device
device = torch.device(f"cuda:{local_rank}" if torch.cuda.is_available() else "cpu")
model = model.to(device)

model.gradient_checkpointing_enable()

data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=MICRO_BATCH_SIZE,
    per_device_eval_batch_size=1,
    gradient_accumulation_steps=GRADIENT_ACCUMULATION_STEPS,
    learning_rate=2e-5,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_steps=50,
    warmup_steps=100,
    lr_scheduler_type="cosine",
    bf16=True,
    deepspeed=config_path,
    dataloader_num_workers=2,
    ddp_find_unused_parameters=False,
    local_rank=local_rank,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
)

if rank == 0:
    total_params = sum(p.numel() for p in model.parameters())
    print(f"\n{'='*60}")
    print(f"Total parameters: {total_params:,}")
    print(f"World size: {world_size}")
    print(f"Sequence parallel size: {world_size}")
    print(f"Micro batch size per GPU: {MICRO_BATCH_SIZE}")
    print(f"Gradient accumulation steps: {GRADIENT_ACCUMULATION_STEPS}")
    print(f"Effective batch size: {train_batch_size}")
    print(f"{'='*60}\n")
    print("Starting training with sequence parallelism...")

train_result = trainer.train()

if rank == 0:
    trainer.save_model()
    tokenizer.save_pretrained(OUTPUT_DIR)
    print(f"Training completed! Model saved to {OUTPUT_DIR}")

World size: 1, Local rank: 0, Rank: 0
Loading tokenizer: meta-llama/Llama-3.2-1B
Tokenizing training data...
Tokenizing validation data...
Train examples: 1,331
Validation examples: 285
DeepSpeed config saved to ./llama-3.2-1B-finetuned-qa-sequence/ds_config.json
Loading meta-llama/Llama-3.2-1B...

**Reference**
- [Arxiv:DeepSpeed Ulysses: System Optimizations for Enabling Training of Extreme Long Sequence Transformer Models](https://arxiv.org/abs/2309.14509)
- [DeepSpeed:Getting Started with DeepSpeed-Ulysses for Training Transformer Models with Extreme Long Sequences](https://www.deepspeed.ai/tutorials/ds-sequence/)
- [Huggingface:Parallelism methods](https://huggingface.co/docs/transformers/en/perf_train_gpu_many)
- [Huggingface:Ultra-Long Sequence Parallelism: Ulysses + Ring-Attention Technical Principles and Implementation](https://huggingface.co/blog/exploding-gradients/ulysses-ring-attention)

#### Selective Replication

Selective Replication is a hybrid optimization strategy used within distributed training frameworks like DeepSpeed ZeRO-3. In a standard ZeRO-3 setup, all model parameters are sharded (split) across all available GPUs to minimize memory usage. Selective Replication allows a developer to pick specific layers or parameters to be "replicated" (copied in full) on every GPU instead of being sharded.

**How it Works**

When training an LLM across multiple GPUs, there is a constant trade-off between memory savings and communication speed.
- Sharding (The Default): In ZeRO-3, parameters are partitioned. Before a GPU can perform a forward or backward pass on a specific layer, it must "collect" the missing pieces of that layer from other GPUs via an all-gather communication operation. After the math is done, it discards the pieces to save memory.
- Replication (The Override): Some layers are small in terms of parameters but are used very frequently or are located at the very beginning and end of the model. By replicating these, the GPU always has the full layer locally. This eliminates the need for the all-gather communication step for those specific layers.

By selectively replicating small but "communication-heavy" layers, the total time spent waiting for the network (inter-GPU communication) decreases, often leading to a significant boost in training speed with only a minor increase in memory consumption.

**Selective Replication Implementation**

The provided code implements this by manually iterating through the model's parameters and setting a DeepSpeed-specific override flag before the trainer starts.

**Parameter Identification:**

The script loops through `model.named_parameters()` and checks the names of the layers.

**The Flag:**

It targets the `embed_tokens` (the input embedding layer) and the lm_head (the final output layer). These layers are often small compared to the transformer blocks but are high-traffic areas.

**The Override:** 


        if "embed_tokens" in name or "lm_head" in name:
        param.ds_override_replication = True

By setting `ds_override_replication = True`, the code tells the DeepSpeed ZeRO-3 engine: "Do not shard these specific tensors. Keep a full copy on every GPU."

**Tracking:**

The script calculates and prints the percentage of replicated vs. sharded parameters, allowing the user to see exactly how much extra memory is being traded for speed. In the Llama-3.2-1B model, the embeddings and head make up a notable portion of the parameter count, so replicating them significantly reduces the communication overhead for the first and last steps of every forward and backward pass.

**When to Use It**

Selective Replication is most effective in the following scenarios:
- Communication Bottlenecks: When training on a cluster where the interconnect (the "cables" between GPUs/nodes) is slow compared to the GPU's compute power. Reducing the number of all-gather operations helps hide this latency.
- Small, Frequent Layers: When the model has specific layers that are relatively small (like embeddings or normalization layers) but are bottlenecks for communication.
- Unbalanced Architectures: In models where the embedding layer is very large but the hidden layers are small; sharding a small hidden layer might take more time in communication overhead than it's worth in memory savings.
- Plenty of Headroom: When there is a small amount of "leftover" VRAM on the GPUs. Instead of letting that memory sit empty, it can be used to store replicated copies of frequent layers to speed up the training loop.

In [ ]:
import torch
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    TrainingArguments,
    Trainer,
    DataCollatorForLanguageModeling
)
from datasets import Dataset, DatasetDict
import deepspeed
import json
import os

In [ ]:
# Configuration 
MODEL_NAME = "meta-llama/Llama-3.2-1B"
OUTPUT_DIR = "./llama-3.2-1B-finetuned-qa-selective"
MAX_LENGTH = 128
MICRO_BATCH_SIZE = 1
GRADIENT_ACCUMULATION_STEPS = 4
NUM_EPOCHS = 3

os.makedirs(OUTPUT_DIR, exist_ok=True)

world_size = int(os.environ.get("WORLD_SIZE", 1))
local_rank = int(os.environ.get("LOCAL_RANK", 0))

print(f"World size: {world_size}, Local rank: {local_rank}")

# Tokenizer 
print(f"Loading tokenizer: {MODEL_NAME}")
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"

def tokenize_examples(examples, max_length=MAX_LENGTH):
    texts = [
        f"Question: {q_title}\n{q_body}\nAnswer: {answer}"
        for q_title, q_body, answer in zip(
            examples["question_title"],
            examples["question_body"],
            examples["answer"]
        )
    ]
    
    tokenized = tokenizer(
        texts,
        truncation=True,
        max_length=max_length,
        padding="max_length",
        return_tensors="pt"
    )
    
    labels = tokenized["input_ids"].clone()
    labels[labels == tokenizer.pad_token_id] = -100
    
    return {
        "input_ids": tokenized["input_ids"],
        "attention_mask": tokenized["attention_mask"],
        "labels": labels
    }

# Data
print("Tokenizing training data...")
train_tokenized = tokenize_examples(train_data)
print("Tokenizing validation data...")
val_tokenized = tokenize_examples(val_data)

dataset_dict = DatasetDict({
    "train": Dataset.from_dict(train_tokenized),
    "validation": Dataset.from_dict(val_tokenized)
})

print(f"Train examples: {len(dataset_dict['train']):,}")
print(f"Validation examples: {len(dataset_dict['validation']):,}")

# Calculate total training steps for information only
steps_per_epoch = len(dataset_dict["train"]) // (MICRO_BATCH_SIZE * GRADIENT_ACCUMULATION_STEPS * world_size)
total_steps = steps_per_epoch * NUM_EPOCHS
print(f"Calculated total steps: {total_steps}")

# DeepSpeed Configuration
train_batch_size = MICRO_BATCH_SIZE * GRADIENT_ACCUMULATION_STEPS * world_size

deepspeed_config = {
    "train_batch_size": train_batch_size,
    "train_micro_batch_size_per_gpu": MICRO_BATCH_SIZE,
    "gradient_accumulation_steps": GRADIENT_ACCUMULATION_STEPS,
    "optimizer": {
        "type": "AdamW",
        "params": {
            "lr": "auto",
            "betas": "auto",
            "eps": "auto",
            "weight_decay": "auto"
        }
    },
    "scheduler": {
        "type": "WarmupCosineLR",
        "params": {
            "total_num_steps": "auto",
            "warmup_num_steps": "auto",
            "warmup_min_lr": "auto"
        }
    },
    "zero_optimization": {
        "stage": 3,
        "contiguous_gradients": True,
        "overlap_comm": True,
        "reduce_scatter": True,
        "reduce_bucket_size": 5e8,
        "allgather_bucket_size": 5e8,
        "stage3_param_persistence_threshold": 1e5,
        "stage3_max_live_parameters": 1e9,
        "stage3_prefetch_bucket_size": 1e7,
        "stage3_gather_16bit_weights_on_model_save": True
    },
    "bf16": {"enabled": True},
    "gradient_clipping": "auto",
    "steps_per_print": 100,
    "wall_clock_breakdown": False
}

config_path = os.path.join(OUTPUT_DIR, "ds_config.json")
with open(config_path, "w") as f:
    json.dump(deepspeed_config, f, indent=2)

print(f"DeepSpeed config saved to {config_path}")

# Load Model
print(f"Loading {MODEL_NAME}...")

# Disable DeepSpeed auto-initialization during model loading
import transformers
transformers.modeling_utils._is_ds_init_called = True

model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    torch_dtype=torch.bfloat16,
    attn_implementation="eager",
    low_cpu_mem_usage=True,
    use_cache=False
)

# Selective Replication
print("Applying selective replication configuration...")

replicated_params = 0
sharded_params = 0

for name, param in model.named_parameters():
    if "embed_tokens" in name or "lm_head" in name:
        param.ds_override_replication = True
        replicated_params += param.numel()
    else:
        param.ds_override_replication = False
        sharded_params += param.numel()

total_params = replicated_params + sharded_params
print(f"Replicated parameters: {replicated_params:,} ({replicated_params/total_params*100:.1f}%)")
print(f"Sharded parameters: {sharded_params:,} ({sharded_params/total_params*100:.1f}%)")

# Training Arguments
training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=NUM_EPOCHS,
    per_device_train_batch_size=MICRO_BATCH_SIZE,
    per_device_eval_batch_size=1,
    gradient_accumulation_steps=GRADIENT_ACCUMULATION_STEPS,
    learning_rate=2e-5,
    weight_decay=0.01,
    max_grad_norm=1.0,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_steps=20,
    warmup_steps=100,
    lr_scheduler_type="cosine",
    bf16=True,
    deepspeed=config_path,
    gradient_checkpointing=True,
    gradient_checkpointing_kwargs={"use_reentrant": False},
    dataloader_num_workers=2,
    ddp_find_unused_parameters=False,
    dataloader_drop_last=True,
    local_rank=local_rank,
)

# Data Collator 
data_collator = DataCollatorForLanguageModeling(
    tokenizer=tokenizer,
    mlm=False,
)

# Trainer 
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
)

# Train 
print(f"\n{'='*60}")
print("STARTING TRAINING WITH SELECTIVE REPLICATION")
print(f"{'='*60}")
print(f"World size: {world_size}")
print(f"Micro batch size per GPU: {MICRO_BATCH_SIZE}")
print(f"Gradient accumulation steps: {GRADIENT_ACCUMULATION_STEPS}")
print(f"Effective batch size: {train_batch_size}")
print(f"Number of epochs: {NUM_EPOCHS}")
print(f"Calculated total steps: {total_steps}")
print(f"{'='*60}\n")

trainer.train()

# Save 
print("\nSaving model...")
trainer.save_model(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)

print(f"\n{'='*60}")
print("TRAINING COMPLETED SUCCESSFULLY!")
print(f"{'='*60}")
print(f"Model saved to: {OUTPUT_DIR}")
print(f"Tokenizer saved to: {OUTPUT_DIR}")
print(f"{'='*60}")

**Reference**
- [ACM:Selective replication: A lightweight technique for soft errors](https://dl.acm.org/doi/abs/10.1145/1658357.1658359)
- [ACM:DeepSpeed: System Optimizations Enable Training Deep Learning Models with Over 100 Billion Parameters](https://dl.acm.org/doi/10.1145/3394486.3406703#:~:text=It%20also%20presents%20a%20clear,and%20scale%20of%20your%20training.)
- [Arxiv:DeepCompile: A Compiler-Driven Approach to Optimizing Distributed Deep Learning Training](https://arxiv.org/html/2504.09983v1)
- [DeepSpeed:Training API](https://deepspeed.readthedocs.io/en/latest/training.html)
- [Huggingface:DeepSpeed](https://huggingface.co/docs/transformers/en/deepspeed)

#### Adaptive Strategy Selection

Adaptive Strategy Selection is a dynamic optimization approach that adjusts parallelization techniques and training configurations based on the specific requirements of different model layers or training stages. Instead of applying a uniform "one-size-fits-all" strategy to the entire network, it adapts the compute and memory orchestration to maximize efficiency, often switching between different parallelization modes to balance throughput and VRAM usage.

**How it Works**

Adaptive strategies work by profiling the resource demands—such as peak memory usage, compute intensity, and communication overhead—of different parts of the Large Language Model.
- Layer-Specific Optimization: Transformer layers near the input might have different memory footprints compared to the final output head. An adaptive system can choose to shard parameters more aggressively (ZeRO-3) for larger layers while using simpler data parallelism for smaller ones.
- Resource Offloading: If the GPU memory is nearly full, the system adaptively offloads optimizer states or parameters to the CPU or NVMe storage. It "pre-fetches" these back to the GPU only when they are needed for computation.
- Curriculum Adaptation: The strategy can also adapt based on the data itself. For example, starting with shorter sequences to speed up early training and gradually increasing sequence length (Curriculum Learning) as the model stabilizes, adjusting the parallel strategy to handle the increased memory load of longer sequences.

**Adaptive Strategy Selection Implementation**

The provided script uses a combination of DeepSpeed ZeRO-3, CPU Offloading, and Curriculum Learning to create an adaptive environment.
**Dynamic Resource Sharding:**

By using `zero_optimization: stage 3`, the code shards all parameters. However, the `sub_group_size` and `prefetch_bucket_size` (set to "auto") allow DeepSpeed to adaptively decide how many parameters to gather at once based on current performance and memory headroom.

**Adaptive CPU Offloading:**

The configuration enables `offload_optimizer` and `offload_param` to CPU. This means the system adaptively manages the movement of data between host memory and device memory, allowing the 1B parameter model to train even if the GPU has limited VRAM.

**Difficulty-Based Adaptation (Curriculum Learning):** 

The `curriculum_learning` block is a key adaptive feature:

    "curriculum_type": "seqlen",
    "min_difficulty": 1,
    "max_difficulty": 128

This instructs the trainer to adaptively change the sequence length during training. It starts with easier (shorter) sequences and increases difficulty over time, which optimizes throughput by not wasting compute on maximum sequence lengths in the early stages of training.

**Memory Checkpointing:**

The script enables `partition_activations` and `cpu_checkpointing` within `activation_checkpointing`. This adaptively trades compute for memory by discarding activations and re-calculating them during the backward pass only when memory limits are reached.

**When to Use It**

Adaptive Strategy Selection is most beneficial in the following cases:
- Heterogeneous Hardware: When training on a cluster where nodes have varying amounts of VRAM or different interconnect speeds.
- Memory-Constrained Environments: When attempting to fine-tune a model that is technically too large for the available GPU memory (e.g., training a 7B model on a single 16GB GPU) by utilizing CPU offloading and activation partitioning.
- Fine-Tuning on Variable Sequence Lengths: When the dataset has a wide range of sequence lengths; curriculum learning prevents the "idle time" associated with padding short sequences to a large fixed length.
- Production Training Pipelines: When the goal is to maximize "Model FLOPs Utilization" (MFU) automatically without requiring manual, layer-by-layer tuning of parallel strategies.

In [ ]:
import torch
from transformers import (
    AutoTokenizer, AutoModelForCausalLM, TrainingArguments, Trainer,
    DataCollatorForLanguageModeling
)
from datasets import Dataset, DatasetDict
import deepspeed
import json
import os
import torch.distributed as dist

In [ ]:
MODEL_NAME = "meta-llama/Llama-3.2-1B"
OUTPUT_DIR = "./llama-3.2-1B-finetuned-qa-adaptive"
MAX_LENGTH = 128
MICRO_BATCH_SIZE = 1
GRADIENT_ACCUMULATION_STEPS = 4

os.makedirs(OUTPUT_DIR, exist_ok=True)

# Initialize distributed environment first
deepspeed.init_distributed()

world_size = dist.get_world_size()
local_rank = int(os.environ.get("LOCAL_RANK", 0))
rank = dist.get_rank()

if rank == 0:
    print(f"World size: {world_size}, Local rank: {local_rank}, Rank: {rank}")
    print(f"Loading tokenizer: {MODEL_NAME}")

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"

def tokenize_examples(examples, max_length=MAX_LENGTH):
    texts = [
        f"Question: {q_title}\n{q_body}\nAnswer: {answer}"
        for q_title, q_body, answer in zip(
            examples["question_title"],
            examples["question_body"],
            examples["answer"]
        )
    ]
    
    tokenized = tokenizer(
        texts,
        truncation=True,
        max_length=max_length,
        padding="max_length",
        return_tensors="pt"
    )
    
    labels = tokenized["input_ids"].clone()
    labels[labels == tokenizer.pad_token_id] = -100
    
    return {
        "input_ids": tokenized["input_ids"],
        "attention_mask": tokenized["attention_mask"],
        "labels": labels
    }

if rank == 0:
    print("Tokenizing training data...")
train_tokenized = tokenize_examples(train_data)

if rank == 0:
    print("Tokenizing validation data...")
val_tokenized = tokenize_examples(val_data)

dataset_dict = DatasetDict({
    "train": Dataset.from_dict(train_tokenized),
    "validation": Dataset.from_dict(val_tokenized)
})

if rank == 0:
    print(f"Train examples: {len(dataset_dict['train']):,}")
    print(f"Validation examples: {len(dataset_dict['validation']):,}")

train_batch_size = MICRO_BATCH_SIZE * GRADIENT_ACCUMULATION_STEPS * world_size

# DeepSpeed configuration with adaptive strategy 
deepspeed_config = {
    "train_batch_size": "auto",
    "train_micro_batch_size_per_gpu": "auto",
    "gradient_accumulation_steps": "auto",
    "optimizer": {
        "type": "AdamW",
        "params": {
            "lr": 2e-5,
            "betas": [0.9, 0.999],
            "eps": 1e-8,
            "weight_decay": 0.01
        }
    },
    "scheduler": {
        "type": "WarmupCosineLR",
        "params": {
            "total_num_steps": "auto",
            "warmup_num_steps": "auto",
            "warmup_min_ratio": 0.0,
            "cos_min_ratio": 0.001
        }
    },
    "zero_optimization": {
        "stage": 3,
        "offload_optimizer": {
            "device": "cpu",
            "pin_memory": True
        },
        "offload_param": {
            "device": "cpu",
            "pin_memory": True
        },
        "overlap_comm": True,
        "contiguous_gradients": True,
        "sub_group_size": 1e9,
        "reduce_bucket_size": "auto",
        "stage3_prefetch_bucket_size": "auto",
        "stage3_param_persistence_threshold": "auto",
        "stage3_max_live_parameters": 1e9,
        "stage3_max_reuse_distance": 1e9,
        "stage3_gather_16bit_weights_on_model_save": True
    },
    "activation_checkpointing": {
        "partition_activations": True,
        "cpu_checkpointing": True,
        "contiguous_memory_optimization": True,
        "number_checkpoints": None,
        "synchronize_checkpoint_boundary": False,
        "profile": False
    },
    "bf16": {"enabled": True},
    "gradient_clipping": 1.0,
    "steps_per_print": 10,
    "wall_clock_breakdown": False,
    "data_efficiency": {
        "enabled": True,
        "seed": 42
    },
    "curriculum_learning": {
        "enabled": True,
        "curriculum_type": "seqlen",
        "min_difficulty": 1,
        "max_difficulty": 128,
        "schedule_type": "fixed_linear",
        "schedule_config": {
            "total_curriculum_step": 1000,
            "difficulty_step": 8
        }
    }
}

# Comment out hybrid_engine for now due to compatibility issues
# deepspeed_config["hybrid_engine"] = {
#     "enabled": True,
#     "max_out_tokens": 2048,
#     "inference_tp_size": 1,
#     "release_inference_cache": False,
#     "pin_parameters": True,
#     "tp_gather_partition_size": 8
# }

config_path = os.path.join(OUTPUT_DIR, "ds_config.json")
if rank == 0:
    with open(config_path, "w") as f:
        json.dump(deepspeed_config, f, indent=2)
    print(f"DeepSpeed config saved to {config_path}")

if rank == 0:
    print(f"Loading {MODEL_NAME}...")

# Disable DeepSpeed auto-initialization
import transformers
transformers.modeling_utils._is_ds_init_called = True

model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    torch_dtype=torch.bfloat16,
    low_cpu_mem_usage=True,
    attn_implementation="eager",
    use_cache=False
)

# Move model to correct device
device = torch.device(f"cuda:{local_rank}" if torch.cuda.is_available() else "cpu")
model = model.to(device)

# Enable gradient checkpointing
model.gradient_checkpointing_enable()

data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=MICRO_BATCH_SIZE,
    per_device_eval_batch_size=1,
    gradient_accumulation_steps=GRADIENT_ACCUMULATION_STEPS,
    learning_rate=2e-5,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_steps=50,
    warmup_steps=100,
    lr_scheduler_type="cosine",
    bf16=True,
    deepspeed=config_path,
    dataloader_num_workers=2,
    ddp_find_unused_parameters=False,
    local_rank=local_rank,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
)

if rank == 0:
    total_params = sum(p.numel() for p in model.parameters())
    print(f"\n{'='*60}")
    print(f"Total parameters: {total_params:,}")
    print(f"World size: {world_size}")
    print(f"Micro batch size per GPU: {MICRO_BATCH_SIZE}")
    print(f"Gradient accumulation steps: {GRADIENT_ACCUMULATION_STEPS}")
    print(f"Effective batch size: {train_batch_size}")
    print(f"Adaptive strategy: Enabled (ZeRO-3 + Offload + Curriculum)")
    print(f"Curriculum learning: Enabled")
    print(f"CPU offloading: Enabled")
    print(f"{'='*60}\n")
    print("Starting training with adaptive strategy selection...")

train_result = trainer.train()

if rank == 0:
    trainer.save_model()
    tokenizer.save_pretrained(OUTPUT_DIR)
    print(f"Training completed! Model saved to {OUTPUT_DIR}")

[W215 11:38:01.716778528 socket.cpp:200] [c10d] The hostname of the client socket cannot be retrieved. err=-3
[W215 11:38:01.717807589 socket.cpp:200] [c10d] The hostname of the client socket cannot be retrieved. err=-3

World size: 1, Local rank: 0, Rank: 0
Loading tokenizer: meta-llama/Llama-3.2-1B
Tokenizing training data...
Tokenizing validation data...

`torch_dtype` is deprecated! Use `dtype` instead!

Train examples: 1,331
Validation examples: 285
DeepSpeed config saved to ./llama-3.2-1B-finetuned-qa-adaptive/ds_config.json
Loading meta-llama/Llama-3.2-1B...

Loading weights:   0%|          | 0/146 [00:00<?, ?it/s]

Gradient accumulation steps mismatch: GradientAccumulationPlugin has 1, DeepSpeed config has 4. Using DeepSpeed's value.

============================================================
Total parameters: 1,235,814,400
World size: 1
Micro batch size per GPU: 1
Gradient accumulation steps: 4
Effective batch size: 4
Adaptive strategy: Enabled (ZeRO-3 + Offload + Curriculum)
Curriculum learning: Enabled
CPU offloading: Enabled
============================================================

Starting training with adaptive strategy selection...

[rank0]:W0215 11:38:12.156000 3066 torch/utils/cpp_extension.py:2425] TORCH_CUDA_ARCH_LIST is not set, all archs for visible cards are included for compilation.
[rank0]:W0215 11:38:12.156000 3066 torch/utils/cpp_extension.py:2425] If this is not desired, please set os.environ['TORCH_CUDA_ARCH_LIST'] to specific architectures.

Installed CUDA version 12.5 does not match the version torch was compiled with 12.6 but since the APIs are compatible, accepting this combination
Stage 3 initialize beginning
MA 2.3 GB         Max_MA 2.3 GB         CA 2.3 GB         Max_CA 2 GB
CPU Virtual Memory:  used = 2.87 GB, percent = 9.2%
DeepSpeedZeRoOffload initialize [begin]
MA 2.3 GB         Max_MA 2.3 GB         CA 2.3 GB         Max_CA 2 GB
CPU Virtual Memory:  used = 2.94 GB, percent = 9.4%
Parameter Offload - Persistent parameters statistics: param_count = 33, numel = 67584
DeepSpeedZeRoOffload initialize [end]
MA 0.0 GB         Max_MA 2.3 GB         CA 2.3 GB         Max_CA 2 GB
CPU Virtual Memory:  used = 5.3 GB, percent = 16.9%
Before creating fp16 partitions
MA 0.0 GB         Max_MA 0.0 GB         CA 2.3 GB         Max_CA 2 GB
CPU Virtual Memory:  used = 5.3 GB, percent = 16.9%
After creating fp16 partitions: 2
MA 0.0 GB         Max_MA 0.0 GB         CA 2.3 GB         Max_CA 2 GB
CPU Virtual Memory:  used = 9.36 GB, percent = 29.9%
Before creating fp32 partitions
MA 0.0 GB         Max_MA 0.0 GB         CA 2.3 GB         Max_CA 2 GB
CPU Virtual Memory:  used = 9.36 GB, percent = 29.9%
After creating fp32 partitions
MA 0.0 GB         Max_MA 0.0 GB         CA 2.3 GB         Max_CA 2 GB
CPU Virtual Memory:  used = 13.98 GB, percent = 44.6%
Before initializing optimizer states
MA 0.0 GB         Max_MA 0.0 GB         CA 2.3 GB         Max_CA 2 GB
CPU Virtual Memory:  used = 13.98 GB, percent = 44.6%
After initializing optimizer states
MA 0.0 GB         Max_MA 0.0 GB         CA 2.3 GB         Max_CA 2 GB
CPU Virtual Memory:  used = 19.29 GB, percent = 61.5%
After initializing ZeRO optimizer
MA 0.01 GB         Max_MA 0.99 GB         CA 2.79 GB         Max_CA 3 GB
CPU Virtual Memory:  used = 23.34 GB, percent = 74.4%
[2026-02-15 11:38:34,564] [WARNING] [lr_schedules.py:862:get_lr] Attempting to get learning rate from scheduler before it has started

**Reference**
- [ACM:Adaptive strategy selection in differential evolution](https://dl.acm.org/doi/10.1145/1830483.1830559)
- [Arxiv:Adaptive-Solver Framework for Dynamic Strategy Selection in Large Language Model Reasoning](https://arxiv.org/abs/2310.01446)
- [Arxiv:Route to Reason: Adaptive Routing for LLM and Reasoning Strategy Selection](https://arxiv.org/abs/2505.19435)
- [DeepSpeed:Training API](https://deepspeed.readthedocs.io/en/latest/training.html)
- [Huggingface:DeepSpeed](https://huggingface.co/docs/transformers/en/deepspeed)
- [PyTorch:PyTorch Distributed Overview](https://docs.pytorch.org/tutorials/beginner/dist_overview.html)

## Communication Optimization

Communication Optimization in LLM training is a suite of techniques designed to reduce the "communication overhead"—the time GPUs spend talking to each other rather than performing actual mathematical computations. In large-scale distributed training, the network (the physical wires connecting GPUs) is often much slower than the GPUs themselves, creating a bottleneck where expensive hardware sits idle waiting for data.

**Core Techniques**
Communication optimization generally focuses on two main strategies: reducing the size of the data sent and changing the timing of the data transfer.

**1. Gradient Compression**

Instead of sending full, high-precision floating-point numbers for every gradient during synchronization, the data is "squashed."
- FP16/BF16/Int8 Quantization: Gradients are converted to lower precision before transmission, reducing the required bandwidth by 50% or more.
- Sparse Updates: Only the most significant gradients (those above a certain threshold) are sent, while near-zero gradients are ignored.

**2. Asynchronous Updates**

In standard "Synchronous" training, every GPU must finish its math and share its results before anyone can start the next step.
- Overlapping Computation and Communication: Using a "Lookahead" or "Bucket" approach, a GPU begins sending the gradients for the final layer of the model while it is still calculating the gradients for the middle layers.
- Asynchronous SGD: Some GPUs are allowed to push ahead and update the model weights even if other GPUs are still working on the previous batch.

**3. Topology-Aware Communication**

Algorithms like All-Reduce are optimized to understand the physical layout of the cluster. They ensure that data takes the shortest path between GPUs (e.g., staying within a high-speed NVLink server rather than going out over a slower Ethernet cable to another rack).

**How it Works**

When a training step reaches the backward pass, the system generates gradients. Communication optimization triggers a "bucketize" process:
- Bucketing: Small gradients are grouped into a larger "bucket" to minimize the number of individual network "handshakes."
- Compression: The bucket is compressed (e.g., via 1-bit Adam or PowerSGD).
- Hiding Latency: The system initiates the network transfer of Bucket A while the GPU simultaneously starts the math for Bucket B.

**When to Use It**

Communication optimization is not always necessary for single-server setups, but it is critical in the following environments:
- Slow Interconnects: Use it if you are training on a "low-bandwidth" network (e.g., standard 10Gbps or 100Gbps Ethernet) rather than specialized high-speed interconnects like NVIDIA InfiniBand or RoCE.
- Multi-Node Clusters: As soon as training scales beyond one machine (e.g., 2 nodes or 16+ GPUs), the time spent sending data over the network grows exponentially; optimization is required to keep scaling efficiency high.
- High-Throughput Requirements: If your GPUs are very fast (like H100s) but your data storage or network cannot keep up, compression is the only way to prevent the GPUs from "starving" for data.
- Federated or Edge Learning: If you are training across geographically distant locations where latency is extremely high, asynchronous updates are mandatory to prevent the entire training run from stalling.

### Gradient Compression (1-bit Adam)

Gradient Compression is a communication optimization technique that reduces the volume of data transferred between GPUs during the synchronization of gradients. In distributed Large Language Model (LLM) training, the standard process requires every GPU to share its calculated gradients with all other GPUs (an "All-Reduce" operation). Gradient compression uses quantization to convert high-precision gradient values into a highly compressed format, such as 1-bit representations, significantly lowering the bandwidth required for these network transfers.

**How it Works**

Gradient compression functions by drastically reducing the precision of the numbers sent over the network while maintaining the mathematical direction of the model update.
- Warm-up Phase: The model begins training using standard high-precision gradients (like FP32 or BF16). This allows the optimizer to establish a stable "momentum" or direction for the model's weights.
- Quantization (The Compression): After a set number of steps, the system begins compressing the gradients. In a 1-bit scheme, the system doesn't send the exact value of the gradient. Instead, it only sends the sign (positive or negative) of the gradient.
- Error Compensation: Because sending only 1 bit per value is a "lossy" process, the system tracks the difference between the actual gradient and the compressed version. This "error" is added back to the next batch's gradients to ensure that the model doesn't drift away from the correct learning path over time.

**Gradient Compression Implementation**

The provided script implements gradient compression through the DeepSpeed OneBitAdam optimizer. This specialized optimizer is designed to handle the transition from high-precision to compressed communication.

**Optimizer Selection:** 

The configuration specifies `"type": "OneBitAdam"`. This replaces the standard AdamW optimizer with a version capable of 1-bit quantization for the communication phase.

**The Freeze Step:**

The parameter `"freeze_step": 23000` is the most critical part of the adaptive compression logic. It tells the optimizer to train normally for the first 23,000 steps to build up reliable variance and momentum estimates. Only after this "freeze" period does the 1-bit compression of gradients trigger.

**Communication Backend:**

By setting `"comm_backend_name": "nccl"` and `"cuda_aware": True`, the code ensures that the compressed gradients are moved efficiently using NVIDIA's collective communications library directly between GPU memories.

**Precision and Strategy Compatibility:**

The script enables bf16 for computation but explicitly sets `zero_optimization` to `stage: 0`. This is because 1-bit Adam's internal logic for tracking momentum and compressed states is mathematically complex and, in certain DeepSpeed versions, is used as an alternative to the parameter sharding found in ZeRO-3 to avoid communication bottlenecks.

**When to Use It**

Gradient Compression should be utilized in the following specific scenarios:
- Low-Bandwidth Interconnects: This is the primary use case. If GPUs are connected via standard 1Gbps or 10Gbps Ethernet instead of high-speed NVLink or InfiniBand, the network will be the primary bottleneck. Compression can speed up training by up to 5x in these environments.
- Scaling to Many Nodes: As the number of nodes in a cluster increases, the time spent on "All-Reduce" communication grows. Gradient compression helps maintain high scaling efficiency even on massive clusters.
- Cloud Training: When training on public cloud instances where inter-node bandwidth is limited or expensive, 1-bit Adam allows for faster training completion without requiring specialized, high-cost networking tiers.
- Communication-Bound Models: Some models have a very high ratio of parameters to computation. These models spend a disproportionate amount of time sharing gradients; compressing those gradients ensures the GPUs spend more time calculating and less time waiting.

In [ ]:
%%capture
!pip install mpi4py
!git clone https://github.com/deepspeedai/DeepSpeed
!pip install deepspeed[1bit_adam]
import torch
from transformers import (
    AutoTokenizer, AutoModelForCausalLM,
    TrainingArguments, Trainer, DataCollatorForLanguageModeling
)
from datasets import DatasetDict, Dataset

In [ ]:
# Configuration
MODEL_NAME = "google/gemma-3-1b-pt"  #"google/gemma-2-2b"          # smallest realistic for 1-bit Adam
OUTPUT_DIR = "./gemma-2-2b-finetuned-qa"
MAX_LENGTH = 128

# Load tokenizer
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
tokenizer.pad_token = tokenizer.eos_token

# Tokenization function
def tokenize_examples(df, max_length=MAX_LENGTH):
    texts = [
        f"<bos>Question: {row['question_title']}\n{row['question_body']}\nAnswer: {row['answer']}<eos>"
        for row in df.iter_rows(named=True)
    ]
    tokenized = tokenizer(
        texts,
        truncation=True,
        max_length=max_length,
        padding="max_length",
        return_tensors="pt"
    )
    tokenized["labels"] = tokenized["input_ids"].clone()
    return tokenized

train_tokenized = tokenize_examples(train_data)
val_tokenized   = tokenize_examples(val_data)

dataset_dict = DatasetDict({
    "train": Dataset.from_dict({
        "input_ids": train_tokenized["input_ids"],
        "attention_mask": train_tokenized["attention_mask"],
        "labels": train_tokenized["labels"]
    }),
    "validation": Dataset.from_dict({
        "input_ids": val_tokenized["input_ids"],
        "attention_mask": val_tokenized["attention_mask"],
        "labels": val_tokenized["labels"]
    })
})

# Model
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    torch_dtype=torch.bfloat16,
    low_cpu_mem_usage=True,
    device_map="auto"
)

# DeepSpeed config – 1-bit Adam only (NO ZeRO as per documentation)
deepspeed_config = {
    "train_batch_size": "auto",
    "train_micro_batch_size_per_gpu": 1,  
    "gradient_accumulation_steps": 4,     
    "steps_per_print": 64,
    "wall_clock_breakdown": False,
    
    # 1-bit Adam optimizer configuration
    "optimizer": {
        "type": "OneBitAdam",
        "params": {
            "lr": 4e-4,
            "weight_decay": 0.01,
            "bias_correction": False,  # Typically set to False for 1-bit Adam
            "freeze_step": 23000,      # Warmup steps before compression starts
            "comm_backend_name": "nccl",  # Use NCCL backend as recommended
            "cuda_aware": True,
            "eps": 1e-8,                # Added for stability
            "betas": [0.9, 0.999]       # Added for stability
        }
    },
    
    # Scheduler configuration
    "scheduler": {
        "type": "WarmupDecayLR",
        "params": {
            "warmup_min_lr": 0,
            "warmup_max_lr": 4e-4,     # Should match learning rate
            "warmup_num_steps": 100,
            "total_num_steps": "auto"   # Will be computed based on dataset
        }
    },
    
    # Mixed precision configuration
    "bf16": {
        "enabled": True
    },
    
    # Gradient clipping
    "gradient_clipping": 1.0,
    
    # IMPORTANT: NO ZeRO optimization when using 1-bit Adam
    "zero_optimization": {
        "stage": 0,  # Stage 0 means NO ZeRO optimization
        "offload_optimizer": {
            "device": "none"  # No offloading
        }
    },
    
    # FP16 disabled since we're using BF16
    "fp16": {
        "enabled": False
    }
}

training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=1,
    per_device_eval_batch_size=1,
    gradient_accumulation_steps=4,
    learning_rate=4e-4,
    weight_decay=0.01,
    warmup_steps=100,
    # Use bf16 instead of fp16 for better stability with Gemma
    bf16=True,
    fp16=False,
    lr_scheduler_type="linear",  # Changed to linear to match WarmupDecayLR
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    deepspeed=deepspeed_config,
    ddp_find_unused_parameters=False,
    # These are important for DeepSpeed
    gradient_checkpointing=True,  # Save memory
    dataloader_pin_memory=False,
    dataloader_num_workers=0,
)

# Trainer
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False),
)

print(f"Total parameters: {model.num_parameters():,}")
print("Starting training with 1-bit Adam compression...")

# Initialize DeepSpeed
trainer.train()
trainer.save_model()
tokenizer.save_pretrained(OUTPUT_DIR)
print("Training completed!")

**Reference**
- [Arxiv:1-bit Adam: Communication Efficient Large-Scale Training with Adam's Convergence Speed](https://arxiv.org/abs/2102.02888)
- [Arxiv:Deep Gradient Compression: Reducing the Communication Bandwidth for Distributed Training](https://arxiv.org/abs/1712.01887)
- [DeepSpeed:1-bit Adam: Up to 5x less communication volume and up to 3.4x faster training](https://www.deepspeed.ai/tutorials/onebit-adam/](https://www.deepspeed.ai/tutorials/onebit-adam/)
- [ICM:1-bit Adam: Communication Efficient Large-Scale Training with Adam's Convergence Speed](https://icml.cc/media/icml-2021/Slides/9809.pdf)
- [DeepSpeed:Training API](https://deepspeed.readthedocs.io/en/latest/training.html)
- [Huggingface:DeepSpeed](https://huggingface.co/docs/transformers/en/deepspeed)

### Asynchronous Gradient Updates

Asynchronous Updates in the context of Large Language Model (LLM) training refer to the ability of a distributed system to perform gradient synchronization without forcing every GPU to stop and wait for the network. In a standard synchronous setup, computation and communication happen in serial: the GPU calculates gradients, then pauses all work to send/receive data (All-Reduce), and only then proceeds to the next step. Asynchronous updates and their related "non-blocking" techniques allow these two phases to overlap, so the GPU can begin calculating gradients for the next layer while the network is still busy transmitting the previous ones.

**How it Works**

The core logic of non-blocking updates is to hide the "latency" of the network behind the "compute" of the GPU.
- Bucketing: Gradients are not sent one by one. They are grouped into "buckets."
- Look-ahead Execution: As soon as a bucket of gradients is ready (usually starting from the final layer and moving backward), the system triggers a background network request to synchronize that bucket.
- Non-blocking Communication: Instead of waiting for the "OK" from other GPUs, the system immediately continues the backward pass for the next set of layers.
- Stale Gradients (Pure Async): In extreme asynchronous versions (like Parameter Servers), a GPU might even start a whole new forward pass using slightly "stale" weights while the background update is still finishing. However, in modern LLM training, "Asynchronous" usually refers to overlapping the communication of current gradients with ongoing computation to ensure the hardware never sits idle.

**Asynchronous Updates Implementation**

The provided code achieves non-blocking, asynchronous-like behavior through specific DeepSpeed ZeRO-3 communication overlap settings.

**`overlap_comm: True`:** 

This is the primary trigger. It instructs DeepSpeed to initiate the "All-Gather" (to get parameters) or "Reduce-Scatter" (to send gradients) in a separate background stream. This allows the GPU to perform matrix multiplications for layer N−1 while the network is still synchronizing layer N.

**`stage3_prefetch_bucket_size: "auto"`:** 

This enables "parameter prefetching." The system adaptively looks ahead at the model's execution graph and starts fetching the parameters for the next layers before the current layer's computation is finished.

**`contiguous_gradients: True`**:

By organizing gradients into a single contiguous buffer, the system can launch larger, more efficient asynchronous memory copies, reducing the number of individual "handshakes" required by the network.

**`communication_data_type: "bf16"`**: 

By synchronizing gradients in `BFloat16` rather than `FP32`, the total data volume is cut in half. This ensures that the background communication finishes faster, making it more likely that the data is ready by the time the next layer needs it, maintaining the non-blocking flow.

**When to Use It**

Asynchronous updates and communication overlap are essential in the following conditions:
- High Communication-to-Compute Ratio: If the model is small enough that the GPU finishes calculations very quickly, the network overhead becomes the dominant factor. Overlapping is required to maintain speed.
- Scaling Beyond a Single Node: When data must travel over Ethernet or InfiniBand between different physical servers, the delay is much higher than inside a single machine. Non-blocking updates are the only way to hide this inter-node latency.
- Large-Scale Training Clusters: On clusters with 128+ GPUs, the "sync" time can become enormous. Overlapping communication ensures the cluster doesn't spend 50% of its time doing nothing.
- Resource-Constrained Interconnects: When training on clouds where the network bandwidth is shared or limited, asynchronous updates prevent the training process from "stuttering" during periods of network congestion.

In [ ]:
import torch
from transformers import (
    AutoTokenizer, AutoModelForCausalLM,
    TrainingArguments, Trainer, DataCollatorForLanguageModeling
)
from datasets import DatasetDict, Dataset

In [ ]:
# Configuration
MODEL_NAME = "google/gemma-3-1b-pt"#"google/gemma-2-2b"
OUTPUT_DIR = "./gemma-2-2b-finetuned-qa-async-like"
MAX_LENGTH = 128

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
tokenizer.pad_token = tokenizer.eos_token

# Same tokenization as above
def tokenize_examples(df, max_length=MAX_LENGTH):
    texts = [
        f"<bos>Question: {row['question_title']}\n{row['question_body']}\nAnswer: {row['answer']}<eos>"
        for row in df.iter_rows(named=True)
    ]
    tokenized = tokenizer(
        texts, truncation=True, max_length=max_length,
        padding="max_length", return_tensors="pt"
    )
    tokenized["labels"] = tokenized["input_ids"].clone()
    return tokenized

train_tokenized = tokenize_examples(train_data)
val_tokenized   = tokenize_examples(val_data)

dataset_dict = DatasetDict({
    "train": Dataset.from_dict(train_tokenized),
    "validation": Dataset.from_dict(val_tokenized),
})

model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    torch_dtype=torch.bfloat16,
    low_cpu_mem_usage=True,
    #device_map="auto"
)

# ZeRO-3 with maximum communication overlap
ds_config = {
    "train_batch_size": "auto",
    "train_micro_batch_size_per_gpu": "auto",
    "gradient_accumulation_steps": "auto",
    "optimizer": {
        "type": "AdamW",
        "params": {
            "lr": 2e-5,
            "weight_decay": 0.01,
            "betas": [0.9, 0.999],
            "eps": 1e-8
        }
    },
    "scheduler": {
        "type": "WarmupDecayLR",
        "params": {
            "warmup_max_lr": 2e-5,
            "warmup_min_lr": 0,
            "warmup_num_steps": 100,  
            "total_num_steps": 999    
        }
    },
    "zero_optimization": {
        "stage": 3,
        "offload_optimizer": {
            "device": "none",
            "pin_memory": False
        },
        "offload_param": {
            "device": "none",
            "pin_memory": False
        },
        "overlap_comm": True,
        "contiguous_gradients": True,
        "reduce_bucket_size": "auto",
        "stage3_prefetch_bucket_size": "auto",
        "stage3_param_persistence_threshold": "auto",
        "gather_16bit_weights_on_model_save": True
    },
    "gradient_clipping": 1.0,
    "bf16": {"enabled": True},
    "communication_data_type": "bf16",      # helps reduce comm volume
    "steps_per_print": 64,
    "wall_clock_breakdown": False
}

training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=1,           # usually smaller micro-batch in ZeRO-3
    per_device_eval_batch_size=1,
    gradient_accumulation_steps=4,
    learning_rate=2e-5,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    logging_strategy="epoch",
    warmup_ratio=0.1,
    lr_scheduler_type="cosine",
    deepspeed=ds_config,
    bf16=True,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False),
)

print(f"Total parameters: {model.num_parameters():,}")
print("Starting training with ZeRO-3 + strong comm overlap...")
trainer.train()
trainer.save_model()
tokenizer.save_pretrained(OUTPUT_DIR)
print("Training completed!")

**Reference**
- [Arxiv:Asynchronous Federated Reinforcement Learning with Policy Gradient Updates: Algorithm Design and Convergence Analysis](https://arxiv.org/abs/2404.08003)
- [Arxiv:Asynchronous Stochastic Gradient Descent with Decoupled Backpropagation and Layer-Wise Updates](https://arxiv.org/abs/2410.05985)
- [Aclanthology:Making Asynchronous Stochastic Gradient Descent Work for Transformers](https://aclanthology.org/anthology-files/pdf/D/D19/D19-5608.pdf)
- [APXML:Synchronous vs. Asynchronous Updates](https://apxml.com/courses/optimization-techniques-ml/chapter-5-distributed-ml-optimization/synchronous-vs-asynchronous-updates)

## Federated Fine-tuning

Federated Fine-tuning (FedFT) is a decentralized training strategy that allows a Large Language Model to be optimized across multiple remote devices or servers (clients) without ever centralizing the raw data. Instead of moving data to the model, the model "travels" to the data.

**H**ow it Works**

- Local Training: A central server sends the current global model to several clients (e.g., hospitals, mobile phones, or regional offices).
- Private Optimization: Each client fine-tunes the model on its own local, private dataset for a few iterations.
- Update Upload: Clients send only the resulting model weights or gradients (often compressed or encrypted) back to the central server, never the actual data.
- Aggregation: The server uses an algorithm like FedAvg (Federated Averaging) to combine these individual updates into a new, improved global model.

**Summary of Benefits**

- Data Privacy: Raw data stays behind local firewalls, reducing the risk of data breaches.
- Compliance: Helps organizations meet strict data residency and protection laws (like GDPR or HIPAA).
- Efficiency: Distributes the computational load across many devices rather than requiring one massive supercomputer.

**When to Use It**

Federated Fine-tuning is the optimal choice in specific scenarios where data movement is restricted:
- Privacy-Sensitive Sectors: When training LLMs for healthcare (patient records) or finance (banking transactions) where legal regulations prohibit sharing raw data with third-party AI providers.
- Edge Device Personalization: When improving the LLM on a user's smartphone (e.g., keyboard auto-correct or personal assistants) while ensuring user text remains private on the device.
- Cross-Institutional Collaboration: When multiple competing companies want to build a shared industry-specific model but refuse to share their proprietary datasets with one another.
- Massive Data Volumes: When the local data is so large that moving it to a central cloud server would be too slow or expensive in terms of network bandwidth.

**Reference**
- [Arxiv:Federated Fine-tuning of Large Language Models under Heterogeneous Tasks and Client Resources](https://arxiv.org/abs/2402.11505)
- [Medium:Implementing Federated Learning for LLM Fine-tuning: A Practical Guide](https://medium.com/@akashpaul2030/implementing-federated-learning-for-llm-fine-tuning-a-practical-guide-53c476fc6f50)
- [NeurIPS:FLoRA: Federated Fine-Tuning Large Language Models with Heterogeneous Low-Rank Adaptations](https://neurips.cc/virtual/2024/poster/95025)

### Federated Averaging

Federated Averaging (FedAvg) is the foundational algorithm used in Federated Learning to combine model updates from multiple decentralized participants. Instead of sharing private data, participants perform local training and only share their updated model parameters. The central server then averages these parameters to create a refined global model that reflects the patterns found in all participants' data.

**How it Works**

The Federated Averaging process operates in a cyclical pattern known as "rounds."
- Selection and Distribution: The central server selects a group of available clients and sends them the current "global" model weights.
- Local Training: Each client trains the model on its own local data for a few iterations (epochs). This creates a "local" version of the model that is slightly different for every client.
- Weight Upload: Clients send their new local weights back to the server. Importantly, the raw data never leaves the client's device.
- Averaging: The server takes a weighted average of all client parameters. Clients with more training data typically have a larger influence on the average.
- Iteration: The newly averaged "global" model is sent back out to clients for the next round, repeating the process until the model converges.

**Federated Averaging Implementation**

The script utilizes the Flower (`flwr`) framework to orchestrate the communication and the averaging logic.

**Strategy Definition:**

The `server_fn` explicitly selects the averaging algorithm:

    strategy = fl.server.strategy.FedAvg(
        fraction_fit=1.0,
        min_fit_clients=NUM_CLIENTS,
        # ... other config
    )

This tells the server to wait for all clients (`NUM_CLIENTS`) to finish their local work before calculating the average of their weights.

**Weight Extraction:**

Inside the `FederatedClient` class, the `get_parameters` method converts complex PyTorch tensors into simple NumPy arrays. This is necessary because the FedAvg algorithm needs to perform basic math (averaging) on the numbers regardless of the deep learning framework being used.

**Local Optimization:**

The fit method handles the actual fine-tuning on the client's private partition of the data. It uses a standard AdamW optimizer locally. Once training is complete, it returns the updated weights to the server.

**Simulation Orchestration:** 

The `run_simulation` function acts as the conductor, managing the virtual "nodes" (clients), triggering the local fit methods, and passing the results to the FedAvg strategy for aggregation.

**When to Use It**

Federated Averaging is most effective in scenarios involving data sensitivity or massive distribution:
- Data Silos: When data exists in different "islands" that cannot be merged due to legal, privacy, or competitive reasons (e.g., different banks or different hospitals).
- Mobile and IoT Applications: When training a model based on user behavior on smartphones or smart home devices where uploading raw user data to a cloud server would violate privacy or consume too much battery/bandwidth.
- Bandwidth Constraints: When the local datasets are so large that it is faster to transmit model weights (which are a fixed size) than to move terabytes of raw data across the network.
- Regulatory Requirements: When a project must strictly comply with "Privacy by Design" principles, ensuring that no single entity ever has access to the full dataset.

In [8]:
%%capture
!pip install flwr
!pip install GPUtil
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, DataCollatorForLanguageModeling
from datasets import Dataset
from flwr.client import ClientApp, NumPyClient
from flwr.server import ServerApp, ServerConfig, ServerAppComponents
from flwr.common import Context
from flwr.simulation import run_simulation
import flwr as fl
import numpy as np
import os
import polars as pl
import time
import psutil
import GPUtil

In [ ]:
# Configuration
MODEL_NAME = "google/gemma-3-270m"
OUTPUT_DIR = "./gemma-3-270m-finetuned-qa"

# Suppress TensorFlow/JAX warnings if any
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'

# Resource monitoring functions
def get_gpu_metrics():
    metrics = {}
    try:
        gpus = GPUtil.getGPUs()
        for i, gpu in enumerate(gpus):
            metrics[f"gpu_{i}_util"] = gpu.load * 100
            metrics[f"gpu_{i}_memory_used"] = gpu.memoryUsed
            metrics[f"gpu_{i}_memory_total"] = gpu.memoryTotal
            metrics[f"gpu_{i}_temperature"] = gpu.temperature
    except:
        metrics["gpu_available"] = False
    return metrics

def get_system_metrics():
    process = psutil.Process()
    metrics = {
        "cpu_percent": psutil.cpu_percent(interval=0.1),
        "memory_percent": psutil.virtual_memory().percent,
        "memory_used_gb": psutil.virtual_memory().used / (1024**3),
        "memory_total_gb": psutil.virtual_memory().total / (1024**3),
        "process_cpu_percent": process.cpu_percent(interval=0.1),
        "process_memory_gb": process.memory_info().rss / (1024**3),
    }
    return metrics

def get_flops_metrics(model, batch_size, seq_length):
    """Estimate FLOPS for a forward pass"""
    hidden_size = model.config.hidden_size
    num_layers = model.config.num_hidden_layers
    
    # Rough estimation based on model architecture
    attention_flops = 2 * batch_size * seq_length * hidden_size * (2 * hidden_size)
    ffn_flops = 2 * batch_size * seq_length * hidden_size * (4 * hidden_size)
    total_flops_per_layer = attention_flops + ffn_flops
    total_flops = num_layers * total_flops_per_layer
    
    return total_flops / 1e9  # Convert to GFLOPS

class ResourceMonitor:
    def __init__(self):
        self.start_time = None
        self.step_count = 0
        self.total_flops = 0
    
    def start_monitoring(self):
        self.start_time = time.time()
        self.start_gpu_metrics = get_gpu_metrics()
        self.start_system_metrics = get_system_metrics()
    
    def stop_monitoring(self, num_batches, batch_size, seq_length, model):
        end_time = time.time()
        end_gpu_metrics = get_gpu_metrics()
        end_system_metrics = get_system_metrics()
        
        duration = end_time - self.start_time
        
        metrics = {
            "training_duration_seconds": duration,
            "batches_processed": num_batches,
            "samples_per_second": (num_batches * batch_size) / duration if duration > 0 else 0,
        }
        
        # Add GPU metrics
        for key, value in end_gpu_metrics.items():
            if isinstance(value, (int, float)):
                metrics[key] = value
        
        # Add system metrics
        metrics.update(end_system_metrics)
        
        # Add FLOPS estimation
        flops_per_batch = get_flops_metrics(model, batch_size, seq_length)
        total_flops = flops_per_batch * num_batches
        metrics["estimated_flops_gflops"] = total_flops
        metrics["flops_per_second_gflops"] = total_flops / duration if duration > 0 else 0
        
        return metrics

class FederatedClient(NumPyClient):
    def __init__(self, client_id, train_dataset, val_dataset, tokenizer):
        self.client_id = client_id
        self.train_dataset = train_dataset
        self.val_dataset = val_dataset
        self.tokenizer = tokenizer
        self.resource_monitor = ResourceMonitor()
        
        self.model = AutoModelForCausalLM.from_pretrained(
            MODEL_NAME,
            torch_dtype=torch.float32,
            low_cpu_mem_usage=True,
        )
        
        self.data_collator = DataCollatorForLanguageModeling(tokenizer=self.tokenizer, mlm=False)
        
    def get_parameters(self, config):
        # FIXED: detach tensors before converting to numpy
        return [val.detach().cpu().numpy() for val in self.model.parameters()]
    
    def set_parameters(self, parameters):
        params_dict = zip(self.model.state_dict().keys(), parameters)
        state_dict = {k: torch.tensor(v) for k, v in params_dict}
        self.model.load_state_dict(state_dict, strict=False)
    
    def fit(self, parameters, config):
        self.set_parameters(parameters)
        
        epochs = config.get("epochs", 1)
        batch_size = config.get("batch_size", 2)
        learning_rate = config.get("learning_rate", 2e-5)
        seq_length = MAX_LENGTH
        
        optimizer = torch.optim.AdamW(self.model.parameters(), lr=learning_rate)
        
        train_loader = torch.utils.data.DataLoader(
            self.train_dataset,
            batch_size=batch_size,
            shuffle=True,
            collate_fn=self.data_collator
        )
        
        self.model.train()
        total_loss = 0
        num_batches = 0
        
        # Start resource monitoring
        self.resource_monitor.start_monitoring()
        
        for _ in range(epochs):
            for batch in train_loader:
                batch = {k: v.to(self.model.device) for k, v in batch.items()}
                
                optimizer.zero_grad()
                outputs = self.model(**batch)
                loss = outputs.loss
                loss.backward()
                optimizer.step()
                
                total_loss += loss.item()
                num_batches += 1
        
        # Stop monitoring and get metrics
        resource_metrics = self.resource_monitor.stop_monitoring(
            num_batches, batch_size, seq_length, self.model
        )
        
        avg_loss = total_loss / num_batches if num_batches > 0 else 0
        
        # Combine loss with resource metrics
        metrics = {"loss": avg_loss}
        metrics.update(resource_metrics)
        
        return self.get_parameters({}), len(self.train_dataset), metrics
    
    def evaluate(self, parameters, config):
        self.set_parameters(parameters)
        
        batch_size = config.get("batch_size", 2)
        seq_length = MAX_LENGTH
        
        eval_loader = torch.utils.data.DataLoader(
            self.val_dataset,
            batch_size=batch_size,
            collate_fn=self.data_collator
        )
        
        self.model.eval()
        total_loss = 0
        num_batches = 0
        
        # Start resource monitoring for evaluation
        self.resource_monitor.start_monitoring()
        
        with torch.no_grad():
            for batch in eval_loader:
                batch = {k: v.to(self.model.device) for k, v in batch.items()}
                outputs = self.model(**batch)
                total_loss += outputs.loss.item()
                num_batches += 1
        
        # Stop monitoring and get metrics
        resource_metrics = self.resource_monitor.stop_monitoring(
            num_batches, batch_size, seq_length, self.model
        )
        
        avg_loss = total_loss / num_batches if num_batches > 0 else float("inf")
        
        # Combine loss with resource metrics
        metrics = {"loss": avg_loss}
        metrics.update(resource_metrics)
        
        return avg_loss, len(self.val_dataset), metrics

# Tokenizer initialization (shared across clients)
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"

def tokenize_examples(df):
    # Convert Polars DataFrame rows to list of dictionaries
    rows = df.to_dicts()
    
    texts = [
        f"<bos>Question: {row['question_title']}\n{row['question_body']}\nAnswer: {row['answer']}<eos>"
        for row in rows
    ]
    
    tokenized = tokenizer(
        texts,
        truncation=True,
        max_length=MAX_LENGTH,
        padding="max_length",
        return_tensors="pt"
    )
    
    labels = tokenized["input_ids"].clone()
    labels[labels == tokenizer.pad_token_id] = -100
    
    return {
        "input_ids": tokenized["input_ids"],
        "attention_mask": tokenized["attention_mask"],
        "labels": labels
    }

# Prepare client datasets
print("Preparing client datasets...")

# Function to split Polars DataFrame into multiple DataFrames
def split_polars_data(data, num_clients=2):
    data_size = data.height
    indices = list(range(data_size))
    np.random.shuffle(indices)
    
    splits = []
    for i in range(num_clients):
        start_idx = i * (data_size // num_clients)
        end_idx = (i + 1) * (data_size // num_clients) if i < num_clients - 1 else data_size
        client_indices = indices[start_idx:end_idx]
        splits.append(data[client_indices])
    return splits

# This assumes train_data and val_data are Polars DataFrames
print(f"Train data type: {type(train_data)}")
print(f"Train data shape: {train_data.shape if hasattr(train_data, 'shape') else 'unknown'}")

train_splits = split_polars_data(train_data)
val_splits = split_polars_data(val_data)

client_datasets = []
for i in range(2):
    print(f"Processing client {i}...")
    
    train_tokenized = tokenize_examples(train_splits[i])
    val_tokenized = tokenize_examples(val_splits[i])
    
    train_dataset = Dataset.from_dict({
        "input_ids": train_tokenized["input_ids"].tolist(),
        "attention_mask": train_tokenized["attention_mask"].tolist(),
        "labels": train_tokenized["labels"].tolist()
    })
    
    val_dataset = Dataset.from_dict({
        "input_ids": val_tokenized["input_ids"].tolist(),
        "attention_mask": val_tokenized["attention_mask"].tolist(),
        "labels": val_tokenized["labels"].tolist()
    })
    
    client_datasets.append((train_dataset, val_dataset))

print(f"Created {len(client_datasets)} client datasets")

# Client function
def client_fn(context: Context):
    # Get client ID from context
    client_id = context.node_config.get("partition-id", 0)
    
    train_dataset, val_dataset = client_datasets[client_id]
    
    return FederatedClient(client_id, train_dataset, val_dataset, tokenizer).to_client()

# Server configuration
def server_fn(context: Context):
    server_config = ServerConfig(num_rounds=3)
    strategy = fl.server.strategy.FedAvg(
        fraction_fit=1.0,
        fraction_evaluate=1.0,
        min_fit_clients=2,
        min_evaluate_clients=2,
        min_available_clients=2,
    )
    return ServerAppComponents(
        strategy=strategy,
        config=server_config
    )

# Create ClientApp and ServerApp
client_app = ClientApp(client_fn)
server_app = ServerApp(server_fn=server_fn)

# Run Federated Learning
print("Starting Federated Averaging training with resource monitoring...")
print(f"Number of clients: 2")
print(f"Number of rounds: 3")

# Run simulation
run_simulation(
    server_app=server_app,
    client_app=client_app,
    num_supernodes=2,
)

print("Federated training completed!")

INFO :      Starting Flower ServerApp, config: num_rounds=3, no round_timeout
INFO :
INFO :      [INIT]
INFO :      Requesting initial parameters from one random client

Preparing client datasets...
Train data type: <class 'polars.dataframe.frame.DataFrame'>
Train data shape: (133, 3)
Processing client 0...
Processing client 1...
Created 2 client datasets
Starting Federated Averaging training with resource monitoring...
Number of clients: 2
Number of rounds: 3

/usr/local/lib/python3.12/dist-packages/jupyter_client/session.py:203: DeprecationWarning: datetime.datetime.utcnow() is deprecated and scheduled for removal in a future version. Use timezone-aware objects to represent datetimes in UTC: datetime.datetime.now(datetime.UTC).
  return datetime.utcnow().replace(tzinfo=utc)
(pid=4941) WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
(pid=4941) E0000 00:00:1771156939.281624    4941 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
(pid=4941) E0000 00:00:1771156939.288742    4941 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
(pid=4941) W0000 00:00:1771156939.307693    4941 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
(pid=4941) W0000 00:00:1771156939.307733    4941 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
(pid=4941) W0000 00:00:1771156939.307737    4941 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
(pid=4941) W0000 00:00:1771156939.307741    4941 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once.
(pid=4941) AttributeError: 'MessageFactory' object has no attribute 'GetPrototype'
(pid=4941) AttributeError: 'MessageFactory' object has no attribute 'GetPrototype'
(ClientAppActor pid=4942) <frozen importlib._bootstrap>:488: DeprecationWarning: builtin type SwigPyPacked has no __module__ attribute
(ClientAppActor pid=4942) <frozen importlib._bootstrap>:488: DeprecationWarning: builtin type SwigPyObject has no __module__ attribute
(pid=4942) WARNING: All log messages before absl::InitializeLog() is called are written to STDERR
(pid=4942) E0000 00:00:1771156939.452870    4942 cuda_dnn.cc:8579] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
(pid=4942) E0000 00:00:1771156939.459985    4942 cuda_blas.cc:1407] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
(pid=4942) W0000 00:00:1771156939.477931    4942 computation_placer.cc:177] computation placer already registered. Please check linkage and avoid linking the same target more than once. [repeated 4x across cluster]
(pid=4942) AttributeError: 'MessageFactory' object has no attribute 'GetPrototype' [repeated 8x across cluster]
(ClientAppActor pid=4942) `torch_dtype` is deprecated! Use `dtype` instead!
Loading weights:   0%|          | 1/236 [00:00<00:00, 4782.56it/s, Materializing param=model.embed_tokens.weight]
Loading weights: 100%|██████████| 236/236 [00:00<00:00, 661.56it/s, Materializing param=model.norm.weight]
(pid=gcs_server) [2026-02-15 12:02:36,541 E 4650 4650] (gcs_server) gcs_server.cc:303: Failed to establish connection to the event+metrics exporter agent. Events and metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
INFO :      Received initial parameters from one random client
INFO :      Starting evaluation of initial global parameters
INFO :      Evaluation returned no results (`None`)
INFO :
INFO :      [ROUND 1]
INFO :      configure_fit: strategy sampled 2 clients (out of 2)
(raylet) [2026-02-15 12:02:39,173 E 4714 4714] (raylet) main.cc:1032: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
[2026-02-15 12:02:44,563 E 3424 4750] core_worker_process.cc:842: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
Loading weights:   0%|          | 1/236 [00:00<00:00, 4946.11it/s, Materializing param=model.embed_tokens.weight]
Loading weights: 100%|██████████| 236/236 [00:00<00:00, 661.01it/s, Materializing param=model.norm.weight]
(ClientAppActor pid=4941) [2026-02-15 12:02:48,134 E 4941 4975] core_worker_process.cc:842: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
(ClientAppActor pid=4941) <frozen importlib._bootstrap>:488: DeprecationWarning: builtin type SwigPyPacked has no __module__ attribute
(ClientAppActor pid=4941) <frozen importlib._bootstrap>:488: DeprecationWarning: builtin type SwigPyObject has no __module__ attribute
(ClientAppActor pid=4941) `torch_dtype` is deprecated! Use `dtype` instead!
(ClientAppActor pid=4942) [2026-02-15 12:02:48,344 E 4942 5004] core_worker_process.cc:842: Failed to establish connection to the metrics exporter agent. Metrics will not be exported. Exporter agent status: RpcError: Running out of retries to initialize the metrics agent. rpc_code: 14
Loading weights:   0%|          | 1/236 [00:00<00:00, 2713.00it/s, Materializing param=model.embed_tokens.weight]
Loading weights:   9%|▉         | 21/236 [00:00<00:29,  7.21it/s, Materializing param=model.layers.1.pre_feedforward_layernorm.weight]
Loading weights:  12%|█▏        | 29/236 [00:00<00:28,  7.21it/s, Materializing param=model.layers.2.mlp.down_proj.weight]
Loading weights:  14%|█▍        | 34/236 [00:00<00:28,  7.21it/s, Materializing param=model.layers.2.pre_feedforward_layernorm.weight]
Loading weights:  17%|█▋        | 39/236 [00:00<00:27,  7.21it/s, Materializing param=model.layers.2.self_attn.q_proj.weight]
Loading weights:  19%|█▉        | 45/236 [00:00<00:26,  7.21it/s, Materializing param=model.layers.3.post_attention_layernorm.weight]
Loading weights:  19%|█▉        | 46/236 [00:00<00:26,  7.21it/s, Materializing param=model.layers.3.post_feedforward_layernorm.weight]
Loading weights:  21%|██        | 50/236 [00:00<00:25,  7.21it/s, Materializing param=model.layers.3.self_attn.o_proj.weight]
Loading weights:  23%|██▎       | 55/236 [00:00<00:25,  7.21it/s, Materializing param=model.layers.4.mlp.down_proj.weight]
Loading weights:  25%|██▌       | 59/236 [00:00<00:24,  7.21it/s, Materializing param=model.layers.4.post_feedforward_layernorm.weight]
Loading weights:  28%|██▊       | 66/236 [00:00<00:23,  7.21it/s, Materializing param=model.layers.4.self_attn.v_proj.weight]
Loading weights:  31%|███       | 73/236 [00:00<00:22,  7.21it/s, Materializing param=model.layers.5.pre_feedforward_layernorm.weight]
Loading weights:  34%|███▍      | 80/236 [00:00<00:21,  7.21it/s, Materializing param=model.layers.6.input_layernorm.weight]
Loading weights:  36%|███▌      | 84/236 [00:00<00:21,  7.21it/s, Materializing param=model.layers.6.post_attention_layernorm.weight]
Loading weights:  39%|███▉      | 92/236 [00:00<00:19,  7.21it/s, Materializing param=model.layers.6.self_attn.v_proj.weight]
Loading weights:  42%|████▏     | 99/236 [00:00<00:19,  7.21it/s, Materializing param=model.layers.7.pre_feedforward_layernorm.weight]
Loading weights:  45%|████▍     | 106/236 [00:00<00:18,  7.21it/s, Materializing param=model.layers.8.input_layernorm.weight]
Loading weights:  47%|████▋     | 110/236 [00:00<00:17,  7.21it/s, Materializing param=model.layers.8.post_attention_layernorm.weight]
Loading weights:  48%|████▊     | 114/236 [00:00<00:16,  7.21it/s, Materializing param=model.layers.8.self_attn.k_proj.weight]
Loading weights:  50%|█████     | 118/236 [00:00<00:16,  7.21it/s, Materializing param=model.layers.8.self_attn.v_proj.weight]
Loading weights:  52%|█████▏    | 122/236 [00:00<00:15,  7.21it/s, Materializing param=model.layers.9.mlp.up_proj.weight]
Loading weights:  54%|█████▍    | 127/236 [00:00<00:15,  7.21it/s, Materializing param=model.layers.9.self_attn.k_proj.weight]
Loading weights:  55%|█████▌    | 130/236 [00:00<00:14,  7.21it/s, Materializing param=model.layers.9.self_attn.q_proj.weight]
Loading weights:  56%|█████▋    | 133/236 [00:00<00:14,  7.21it/s, Materializing param=model.layers.10.mlp.down_proj.weight]
Loading weights:  58%|█████▊    | 136/236 [00:00<00:13,  7.21it/s, Materializing param=model.layers.10.post_attention_layernorm.weight]
Loading weights:  59%|█████▉    | 139/236 [00:00<00:13,  7.21it/s, Materializing param=model.layers.10.self_attn.k_norm.weight]
Loading weights:  59%|█████▉    | 140/236 [00:00<00:13,  7.21it/s, Materializing param=model.layers.10.self_attn.k_proj.weight]
Loading weights:  60%|██████    | 142/236 [00:00<00:13,  7.21it/s, Materializing param=model.layers.10.self_attn.q_norm.weight]
Loading weights:  61%|██████▏   | 145/236 [00:00<00:12,  7.21it/s, Materializing param=model.layers.11.input_layernorm.weight]
Loading weights:  62%|██████▏   | 146/236 [00:00<00:12,  7.21it/s, Materializing param=model.layers.11.mlp.down_proj.weight]
Loading weights:  63%|██████▎   | 149/236 [00:00<00:12,  7.21it/s, Materializing param=model.layers.11.post_attention_layernorm.weight]
Loading weights:  64%|██████▍   | 152/236 [00:00<00:11,  7.21it/s, Materializing param=model.layers.11.self_attn.k_norm.weight]
Loading weights:  66%|██████▌   | 155/236 [00:00<00:11,  7.21it/s, Materializing param=model.layers.11.self_attn.q_norm.weight]
Loading weights:  67%|██████▋   | 158/236 [00:00<00:10,  7.21it/s, Materializing param=model.layers.12.input_layernorm.weight]
Loading weights:  68%|██████▊   | 161/236 [00:00<00:10,  7.21it/s, Materializing param=model.layers.12.mlp.up_proj.weight]
Loading weights:  69%|██████▉   | 164/236 [00:00<00:09,  7.21it/s, Materializing param=model.layers.12.pre_feedforward_layernorm.weight]
Loading weights:  71%|███████   | 167/236 [00:00<00:09,  7.21it/s, Materializing param=model.layers.12.self_attn.o_proj.weight]
Loading weights:  72%|███████▏  | 171/236 [00:00<00:09,  7.21it/s, Materializing param=model.layers.13.input_layernorm.weight]
Loading weights:  74%|███████▎  | 174/236 [00:00<00:08,  7.21it/s, Materializing param=model.layers.13.mlp.up_proj.weight]
Loading weights:  75%|███████▍  | 176/236 [00:00<00:08,  7.21it/s, Materializing param=model.layers.13.post_feedforward_layernorm.weight]
Loading weights:  76%|███████▌  | 179/236 [00:00<00:07,  7.21it/s, Materializing param=model.layers.13.self_attn.k_proj.weight]
Loading weights:  77%|███████▋  | 182/236 [00:00<00:07,  7.21it/s, Materializing param=model.layers.13.self_attn.q_proj.weight]
Loading weights:  78%|███████▊  | 185/236 [00:00<00:07,  7.21it/s, Materializing param=model.layers.14.mlp.down_proj.weight]
Loading weights:  80%|███████▉  | 188/236 [00:00<00:06,  7.21it/s, Materializing param=model.layers.14.post_attention_layernorm.weight]
Loading weights:  80%|███████▉  | 188/236 [00:00<00:06,  7.21it/s, Materializing param=model.layers.14.post_attention_layernorm.weight]
Loading weights:  81%|████████  | 190/236 [00:00<00:06,  7.21it/s, Materializing param=model.layers.14.pre_feedforward_layernorm.weight]
Loading weights:  82%|████████▏ | 193/236 [00:00<00:05,  7.21it/s, Materializing param=model.layers.14.self_attn.o_proj.weight]
Loading weights:  83%|████████▎ | 196/236 [00:00<00:05,  7.21it/s, Materializing param=model.layers.14.self_attn.v_proj.weight]
Loading weights:  84%|████████▍ | 199/236 [00:00<00:05,  7.21it/s, Materializing param=model.layers.15.mlp.gate_proj.weight]
Loading weights:  86%|████████▌ | 203/236 [00:00<00:04,  7.21it/s, Materializing param=model.layers.15.pre_feedforward_layernorm.weight]
Loading weights:  87%|████████▋ | 206/236 [00:00<00:04,  7.21it/s, Materializing param=model.layers.15.self_attn.o_proj.weight]
Loading weights:  89%|████████▉ | 210/236 [00:00<00:03,  7.21it/s, Materializing param=model.layers.16.input_layernorm.weight]
Loading weights:  91%|█████████ | 215/236 [00:00<00:02,  7.21it/s, Materializing param=model.layers.16.post_feedforward_layernorm.weight]
Loading weights:  93%|█████████▎| 219/236 [00:00<00:02,  7.21it/s, Materializing param=model.layers.16.self_attn.o_proj.weight]
Loading weights:  94%|█████████▍| 223/236 [00:00<00:01,  7.21it/s, Materializing param=model.layers.17.input_layernorm.weight]
Loading weights:  96%|█████████▌| 226/236 [00:00<00:01,  7.21it/s, Materializing param=model.layers.17.mlp.up_proj.weight]
Loading weights:  97%|█████████▋| 230/236 [00:00<00:00,  7.21it/s, Materializing param=model.layers.17.self_attn.k_norm.weight]
Loading weights:  99%|█████████▉| 234/236 [00:00<00:00,  7.21it/s, Materializing param=model.layers.17.self_attn.q_proj.weight]
Loading weights: 100%|██████████| 236/236 [00:00<00:00, 626.32it/s, Materializing param=model.norm.weight]

**Reference**
- [Arxiv:Federated Fine-tuning of Large Language Models under Heterogeneous Tasks and Client Resources](https://arxiv.org/abs/2402.11505)
- [Arxiv:Serverless Federated Learning with flwr-serverless](https://arxiv.org/abs/2310.15329)
- [Arxiv:Decentralized Federated Averaging](https://arxiv.org/abs/2104.11375)
- [Arxiv:Communication-Efficient Learning of Deep Networks from Decentralized Data](https://arxiv.org/abs/1602.05629)
- [PyPi:Flower: A Friendly Federated AI Framework](https://pypi.org/project/flwr/)

### Personalized Federated Learning

Personalized Federated Learning (PFL) is an advanced optimization strategy that balances the need for a strong global model with the specific requirements of individual clients. While standard Federated Learning aims to create a single model that works well "on average" for everyone, personalization recognizes that different clients (e.g., users, hospitals, or local branches) have unique data distributions, dialects, or preferences. It creates a "hybrid" model that combines universal knowledge from the group with specialized local adaptations.

**How it Works**

Personalization typically splits a model into two distinct parts:
- The Global Base (Shared): Most of the model (usually the heavy transformer blocks) is treated as a "feature extractor." These layers are updated through standard Federated Averaging across all clients to learn general language patterns.
- The Personalized Head (Local): A small set of layers—often a custom adapter or a final linear layer—is kept exclusively on the client's device. These layers are trained only on the local data to fine-tune the model's output to the specific user's style.

During training, the server orchestrates the synchronization of the base model, but the local "personalization layer" never leaves the client. This allows the model to benefit from the massive scale of the federated network while still being highly customized for the local task.

**Personalized Federated Learning Implementation**

The provided script implements a specific PFL architecture known as "Head-based Personalization" using the PersonalizedModel class and the Flower framework.

**Model Architecture Splitting:**

In the PersonalizedModel class, the base model is frozen, and a new layer is introduced:

    for param in self.base_model.parameters():
        param.requires_grad = False  # Freeze general knowledge
    self.personalization_layer = nn.Linear(...) # Add local adaptation

**Selective Parameter Sharing:**

In the `get_parameters` and `set_parameters` methods of the `PersonalizedFederatedClient`, the client only shares the `base_model` parameters with the server. The weights of the `personalization_layer` remain on the device and are never averaged, preserving the "personal" part of the model.

**Targeted Optimization:**

Inside the fit method, the optimizer is strictly limited to the personalization layer:

    optimizer = torch.optim.AdamW(
        self.model.personalization_layer.parameters(), 
        lr=personal_lr
    )

This ensures that local training time is spent exclusively on tailoring the model to the local data partition rather than overwriting the general knowledge in the base model.

**Resource Tracking:**

The `ResourceMonitor` tracks the efficiency of this split, calculating FLOPS and memory usage specifically for the client's local training steps, which helps in understanding the cost of personalization on edge hardware.

**When to Use It**

Personalized Federated Learning should be used in the following scenarios:
- Non-IID Data (Data Heterogeneity): When data is "Not Identically and Independently Distributed." For example, if one client is a medical clinic and another is a law firm, a single global model will struggle to serve both perfectly.
- User Personalization: For LLM applications like smartphone virtual assistants or predictive keyboards, where the model needs to understand specific slang, names, or contact lists unique to one person.
- Domain Adaptation: When you want a "foundation" LLM that understands general English but needs to be specialized for different regional dialects or industry-specific jargon across different geographic nodes.
- Efficiency on Edge Devices: Because personalization often involves training only a tiny fraction of the model (the "head"), it is much less computationally expensive for a smartphone or IoT device than fine-tuning the entire transformer.

In [ ]:
%%capture
!pip install flwr
!pip install GPUtil
import os
import torch
import torch.nn as nn
from transformers import AutoTokenizer, AutoModelForCausalLM, DataCollatorForLanguageModeling
from datasets import Dataset
from flwr.client import ClientApp, NumPyClient
from flwr.server import ServerApp, ServerConfig, ServerAppComponents
from flwr.common import Context, ndarrays_to_parameters
import flwr as fl
import numpy as np
from typing import Dict, List, Tuple, Optional
import GPUtil
import psutil
import time
import json
from datetime import datetime

In [11]:
# Configuration
MODEL_NAME = "google/gemma-3-270m"
OUTPUT_DIR = "./gemma-3-270m-finetuned-qa"
NUM_CLIENTS = 2
NUM_ROUNDS = 3

os.makedirs(OUTPUT_DIR, exist_ok=True)

# Load tokenizer
print(f"Loading tokenizer: {MODEL_NAME}")
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"
print(f"Tokenizer loaded. Vocab size: {len(tokenizer)}")

# Tokenization
def tokenize_examples(df, max_length=MAX_LENGTH):
    texts = []
    for row in df.iter_rows(named=True):
        text = f"""<bos>Question: {row['question_title']}
{row['question_body']}
Answer: {row['answer']}<eos>"""
        texts.append(text)

    tokenized = tokenizer(
        texts,
        truncation=True,
        max_length=max_length,
        padding="max_length",
        return_tensors="pt"
    )
    labels = tokenized["input_ids"].clone()
    labels[labels == tokenizer.pad_token_id] = -100
    tokenized["labels"] = labels
    return tokenized

print("Tokenizing training data...")
train_tokenized = tokenize_examples(train_data)

print("Tokenizing validation data...")
val_tokenized = tokenize_examples(val_data)

dataset_dict = DatasetDict({
    "train": Dataset.from_dict({
        "input_ids": train_tokenized["input_ids"].tolist(),
        "attention_mask": train_tokenized["attention_mask"].tolist(),
        "labels": train_tokenized["labels"].tolist()
    }),
    "validation": Dataset.from_dict({
        "input_ids": val_tokenized["input_ids"].tolist(),
        "attention_mask": val_tokenized["attention_mask"].tolist(),
        "labels": val_tokenized["labels"].tolist()
    })
})

print(f"Train examples: {len(dataset_dict['train']):,}")
print(f"Validation examples: {len(dataset_dict['validation']):,}")

# Split data for federated learning
def split_data_for_clients(dataset, num_clients=NUM_CLIENTS):
    """Split dataset into num_clients subsets"""
    indices = list(range(len(dataset)))
    np.random.shuffle(indices)
    
    client_datasets = []
    for i in range(num_clients):
        start_idx = i * (len(dataset) // num_clients)
        end_idx = (i + 1) * (len(dataset) // num_clients) if i < num_clients - 1 else len(dataset)
        client_indices = indices[start_idx:end_idx]
        client_datasets.append(dataset.select(client_indices))
    
    return client_datasets

# Split training and validation data for clients
client_train_datasets = split_data_for_clients(dataset_dict["train"], NUM_CLIENTS)
client_val_datasets = split_data_for_clients(dataset_dict["validation"], NUM_CLIENTS)

print(f"\nData split for {NUM_CLIENTS} clients:")
for i in range(NUM_CLIENTS):
    print(f"  Client {i}: {len(client_train_datasets[i])} train, {len(client_val_datasets[i])} val examples")
    
# Resource monitoring functions
def get_gpu_metrics():
    metrics = {}
    try:
        gpus = GPUtil.getGPUs()
        for i, gpu in enumerate(gpus):
            metrics[f"gpu_{i}_util"] = gpu.load * 100
            metrics[f"gpu_{i}_memory_used"] = gpu.memoryUsed
            metrics[f"gpu_{i}_memory_total"] = gpu.memoryTotal
            metrics[f"gpu_{i}_temperature"] = gpu.temperature
        metrics["gpu_available"] = True
        metrics["gpu_count"] = len(gpus)
    except:
        metrics["gpu_available"] = False
        metrics["gpu_count"] = 0
    return metrics

def get_system_metrics():
    process = psutil.Process()
    metrics = {
        "cpu_percent": psutil.cpu_percent(interval=0.1),
        "memory_percent": psutil.virtual_memory().percent,
        "memory_used_gb": psutil.virtual_memory().used / (1024**3),
        "memory_total_gb": psutil.virtual_memory().total / (1024**3),
        "process_cpu_percent": process.cpu_percent(interval=0.1),
        "process_memory_gb": process.memory_info().rss / (1024**3),
    }
    return metrics

def get_flops_metrics(model, batch_size, seq_length):
    """Estimate FLOPS for a forward pass"""
    hidden_size = model.config.hidden_size
    num_layers = model.config.num_hidden_layers
    
    attention_flops = 2 * batch_size * seq_length * hidden_size * (2 * hidden_size)
    ffn_flops = 2 * batch_size * seq_length * hidden_size * (4 * hidden_size)
    total_flops_per_layer = attention_flops + ffn_flops
    total_flops = num_layers * total_flops_per_layer
    
    return total_flops / 1e9

class ResourceMonitor:
    def __init__(self, client_id=None):
        self.client_id = client_id
        self.start_time = None
        self.step_count = 0
        self.total_flops = 0
        self.metrics_history = []
    
    def start_monitoring(self):
        self.start_time = time.time()
        self.start_gpu_metrics = get_gpu_metrics()
        self.start_system_metrics = get_system_metrics()
        print(f"[Client {self.client_id}] Resource monitoring started at {datetime.now()}")
    
    def stop_monitoring(self, num_batches, batch_size, seq_length, model, phase="training"):
        end_time = time.time()
        end_gpu_metrics = get_gpu_metrics()
        end_system_metrics = get_system_metrics()
        
        duration = end_time - self.start_time
        
        metrics = {
            "timestamp": datetime.now().isoformat(),
            "client_id": self.client_id,
            "phase": phase,
            "training_duration_seconds": duration,
            "batches_processed": num_batches,
            "samples_per_second": (num_batches * batch_size) / duration if duration > 0 else 0,
        }
        
        for key, value in end_gpu_metrics.items():
            if isinstance(value, (int, float)):
                metrics[key] = value
        
        metrics.update(end_system_metrics)
        
        flops_per_batch = get_flops_metrics(model, batch_size, seq_length)
        total_flops = flops_per_batch * num_batches
        metrics["estimated_flops_gflops"] = total_flops
        metrics["flops_per_second_gflops"] = total_flops / duration if duration > 0 else 0
        
        if "gpu_0_util" in end_gpu_metrics:
            metrics["avg_gpu_util"] = np.mean([end_gpu_metrics.get(f"gpu_{i}_util", 0) 
                                               for i in range(end_gpu_metrics.get("gpu_count", 0))])
        
        self.metrics_history.append(metrics)
        
        print(f"\n[Client {self.client_id}] {phase.capitalize()} Resource Summary:")
        print(f"  Duration: {duration:.2f}s")
        print(f"  Samples/sec: {metrics['samples_per_second']:.2f}")
        print(f"  GPU Memory Used: {metrics.get('gpu_0_memory_used', 0):.0f}MB")
        print(f"  CPU Usage: {metrics['cpu_percent']:.1f}%")
        print(f"  Process Memory: {metrics['process_memory_gb']:.2f}GB")
        print(f"  FLOPS: {metrics['flops_per_second_gflops']:.2f} GFLOPS\n")
        
        return metrics
    
    def log_step(self, step_type, details=None):
        step_metrics = {
            "timestamp": datetime.now().isoformat(),
            "client_id": self.client_id,
            "step_type": step_type,
            "step_count": self.step_count,
        }
        
        if details:
            step_metrics.update(details)
        
        step_metrics.update(get_system_metrics())
        step_metrics.update(get_gpu_metrics())
        
        self.metrics_history.append(step_metrics)
        self.step_count += 1
        
        return step_metrics
    
    def save_metrics(self, filepath):
        with open(filepath, 'w') as f:
            json.dump({
                "client_id": self.client_id,
                "metrics": self.metrics_history
            }, f, indent=2)
        print(f"[Client {self.client_id}] Metrics saved to {filepath}")

class PersonalizedModel(nn.Module):
    def __init__(self, base_model):
        super().__init__()
        self.base_model = base_model
        for param in self.base_model.parameters():
            param.requires_grad = False
            
        self.personalization_layer = nn.Linear(
            base_model.config.hidden_size, 
            base_model.config.hidden_size
        )
        self.lm_head = base_model.lm_head
        
    def forward(self, input_ids, attention_mask=None, labels=None):
        base_outputs = self.base_model(
            input_ids=input_ids, 
            attention_mask=attention_mask,
            output_hidden_states=True
        )
        
        if hasattr(base_outputs, 'hidden_states'):
            last_hidden_state = base_outputs.hidden_states[-1]
            personalized_hidden = self.personalization_layer(last_hidden_state)
            logits = self.lm_head(personalized_hidden)
            
            loss = None
            if labels is not None:
                shift_logits = logits[..., :-1, :].contiguous()
                shift_labels = labels[..., 1:].contiguous()
                loss_fct = nn.CrossEntropyLoss()
                loss = loss_fct(
                    shift_logits.view(-1, shift_logits.size(-1)),
                    shift_labels.view(-1)
                )
            
            return type('Output', (), {
                'loss': loss,
                'logits': logits,
                'hidden_states': personalized_hidden
            })()
        
        return base_outputs

class PersonalizedFederatedClient(NumPyClient):
    def __init__(self, client_id: int, train_dataset: Dataset, val_dataset: Dataset, tokenizer):
        self.client_id = client_id
        self.train_dataset = train_dataset
        self.val_dataset = val_dataset
        self.tokenizer = tokenizer
        self.resource_monitor = ResourceMonitor(client_id)
        
        base_model = AutoModelForCausalLM.from_pretrained(
            MODEL_NAME,
            torch_dtype=torch.float32,
            low_cpu_mem_usage=True,
        )
        
        self.model = PersonalizedModel(base_model)
        self.device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
        self.model.to(self.device)
        
        self.data_collator = DataCollatorForLanguageModeling(tokenizer=self.tokenizer, mlm=False)
        
        self.resource_monitor.log_step("initialization", {
            "model_name": MODEL_NAME,
            "device": str(self.device),
            "train_size": len(train_dataset),
            "val_size": len(val_dataset)
        })
        
    def get_parameters(self, config):
        return [val.cpu().detach().numpy() for val in self.model.base_model.parameters()]
    
    def set_parameters(self, parameters):
        params_dict = zip(self.model.base_model.state_dict().keys(), parameters)
        state_dict = {k: torch.tensor(v) for k, v in params_dict}
        self.model.base_model.load_state_dict(state_dict, strict=False)
        self.resource_monitor.log_step("parameter_update")
    
    def fit(self, parameters, config):
        self.resource_monitor.log_step("fit_start", {"config": config})
        self.set_parameters(parameters)
        
        epochs = config.get("epochs", 1)
        batch_size = config.get("batch_size", 2)
        personal_lr = config.get("personal_learning_rate", 2e-5)
        
        optimizer = torch.optim.AdamW(
            self.model.personalization_layer.parameters(), 
            lr=personal_lr
        )
        
        train_loader = torch.utils.data.DataLoader(
            self.train_dataset,
            batch_size=batch_size,
            shuffle=True,
            collate_fn=self.data_collator
        )
        
        self.resource_monitor.start_monitoring()
        
        self.model.train()
        total_loss = 0
        num_batches = 0
        
        for epoch in range(epochs):
            epoch_loss = 0
            epoch_batches = 0
            
            for batch_idx, batch in enumerate(train_loader):
                batch = {k: v.to(self.device) for k, v in batch.items() 
                        if k in ['input_ids', 'attention_mask', 'labels']}
                
                optimizer.zero_grad()
                outputs = self.model(**batch)
                loss = outputs.loss
                loss.backward()
                optimizer.step()
                
                total_loss += loss.item()
                num_batches += 1
                epoch_loss += loss.item()
                epoch_batches += 1
                
                if batch_idx % 10 == 0:
                    self.resource_monitor.log_step("batch_completed", {
                        "epoch": epoch,
                        "batch": batch_idx,
                        "loss": loss.item()
                    })
            
            self.resource_monitor.log_step("epoch_completed", {
                "epoch": epoch,
                "avg_loss": epoch_loss / epoch_batches if epoch_batches > 0 else 0,
                "num_batches": epoch_batches
            })
        
        train_metrics = self.resource_monitor.stop_monitoring(
            num_batches, batch_size, MAX_LENGTH, self.model, phase="training"
        )
        
        avg_loss = total_loss / num_batches if num_batches > 0 else 0
        metrics_dict = {"loss": avg_loss, "epochs_completed": epochs, "total_batches": num_batches}
        metrics_dict.update(train_metrics)
        
        return self.get_parameters(config), len(self.train_dataset), metrics_dict
    
    def evaluate(self, parameters, config):
        self.resource_monitor.log_step("evaluation_start", {"config": config})
        self.set_parameters(parameters)
        
        batch_size = config.get("batch_size", 2)
        
        eval_loader = torch.utils.data.DataLoader(
            self.val_dataset,
            batch_size=batch_size,
            collate_fn=self.data_collator
        )
        
        self.resource_monitor.start_monitoring()
        
        self.model.eval()
        total_loss = 0
        num_batches = 0
        
        with torch.no_grad():
            for batch_idx, batch in enumerate(eval_loader):
                batch = {k: v.to(self.device) for k, v in batch.items() 
                        if k in ['input_ids', 'attention_mask', 'labels']}
                outputs = self.model(**batch)
                total_loss += outputs.loss.item()
                num_batches += 1
                
                if batch_idx % 5 == 0:
                    self.resource_monitor.log_step("eval_batch_completed", {
                        "batch": batch_idx,
                        "loss": outputs.loss.item()
                    })
        
        eval_metrics = self.resource_monitor.stop_monitoring(
            num_batches, batch_size, MAX_LENGTH, self.model, phase="evaluation"
        )
        
        avg_loss = total_loss / num_batches if num_batches > 0 else float("inf")
        metrics_dict = {"loss": avg_loss}
        metrics_dict.update(eval_metrics)
        
        return float(avg_loss), len(self.val_dataset), metrics_dict

def server_fn(context: Context):
    config = ServerConfig(num_rounds=NUM_ROUNDS)
    
    tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
    tokenizer.pad_token = tokenizer.eos_token
    
    base_model = AutoModelForCausalLM.from_pretrained(MODEL_NAME)
    model = PersonalizedModel(base_model)
    
    initial_parameters = [val.cpu().detach().numpy() for val in model.base_model.parameters()]
    
    strategy = fl.server.strategy.FedAvg(
        fraction_fit=1.0,
        fraction_evaluate=1.0,
        min_fit_clients=NUM_CLIENTS,
        min_evaluate_clients=NUM_CLIENTS,
        min_available_clients=NUM_CLIENTS,
        initial_parameters=ndarrays_to_parameters(initial_parameters),
        on_fit_config_fn=lambda rnd: {
            "epochs": 1,
            "batch_size": 2,
            "personal_learning_rate": 2e-5,
        },
        on_evaluate_config_fn=lambda rnd: {
            "batch_size": 2,
        }
    )
    
    return ServerAppComponents(strategy=strategy, server_config=config)

def client_fn(context: Context) -> ClientApp:
    client_id = int(context.node_config["partition-id"])
    
    train_dataset = client_train_datasets[client_id]
    val_dataset = client_val_datasets[client_id]
    
    tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
    tokenizer.pad_token = tokenizer.eos_token
    
    client = PersonalizedFederatedClient(client_id, train_dataset, val_dataset, tokenizer)
    return client.to_client()

print("Setting up Personalized Federated Learning with Resource Monitoring...")
print("\nInitial System Metrics:")
initial_system = get_system_metrics()
initial_gpu = get_gpu_metrics()
print(f"CPU Usage: {initial_system['cpu_percent']}%")
print(f"Memory: {initial_system['memory_used_gb']:.2f}GB / {initial_system['memory_total_gb']:.2f}GB")
if initial_gpu['gpu_available']:
    print(f"GPU Count: {initial_gpu['gpu_count']}")
    for i in range(initial_gpu['gpu_count']):
        print(f"GPU {i}: {initial_gpu.get(f'gpu_{i}_util', 0):.1f}% util, "
              f"{initial_gpu.get(f'gpu_{i}_memory_used', 0):.0f}MB / "
              f"{initial_gpu.get(f'gpu_{i}_memory_total', 0):.0f}MB")
else:
    print("No GPU available")

# Create server and client apps
server_app = ServerApp(server_fn=server_fn)
client_app = ClientApp(client_fn)

print(f"\nFederated learning setup complete!")
print(f"Number of clients: {NUM_CLIENTS}")
print(f"Training rounds: {NUM_ROUNDS}")

Loading tokenizer: google/gemma-3-270m
Tokenizer loaded. Vocab size: 262145
Tokenizing training data...
Tokenizing validation data...
Train examples: 133
Validation examples: 28

Data split for 2 clients:
  Client 0: 66 train, 14 val examples
  Client 1: 67 train, 14 val examples
Setting up Personalized Federated Learning with Resource Monitoring...

Initial System Metrics:
CPU Usage: 15.4%
Memory: 2.29GB / 31.35GB
GPU Count: 2
GPU 0: 0.0% util, 3MB / 15360MB
GPU 1: 0.0% util, 3MB / 15360MB

Federated learning setup complete!
Number of clients: 2
Training rounds: 3
Server and client apps are ready for deployment

Resource monitoring will track:
- GPU utilization and memory per client
- CPU and system memory usage
- Training throughput (samples/second)
- Estimated FLOPS performance
- Per-batch and per-epoch metrics

**Reference**
- [Arxiv:Personalized Federated Learning: A Meta-Learning Approach](https://arxiv.org/abs/2002.07948)
- [Arxiv:Learn What You Need in Personalized Federated Learning](https://arxiv.org/abs/2401.08327)
- [Arxiv:Serverless Federated Learning with flwr-serverless](https://arxiv.org/abs/2310.15329)
- [PyPi:Flower: A Friendly Federated AI Framework](https://pypi.org/project/flwr/)

# REGULARIZATION and STABILIZATION (Fine-tuning)

## Advanced Regularization Methods

Regularization Methods in LLM optimization are techniques used to prevent overfitting, a scenario where a model memorizes the training data too well but fails to generalize to new, unseen information. In the context of LLMs, which have billions of parameters, regularization acts as a "constraint" that keeps the model weights from becoming too complex or specialized to the specific noise in the training set.

**Core Techniques**

**1. Weight Decay ($L_2$ Regularization)**

Weight decay adds a penalty to the loss function proportional to the square of the magnitude of the weights. It effectively "decays" large weights, forcing the model to rely on a broader set of features rather than a few overly dominant ones.

**2. Dropout**

During training, dropout randomly "shuts off" a percentage of neurons in each layer. This forces the network to learn redundant representations of data, ensuring that it doesn't become overly dependent on specific paths or individual neurons.

**3. Label Smoothing**

Instead of training the model to be 100% confident in a single "correct" token, label smoothing distributes a small amount of probability to all other incorrect tokens. This prevents the model from becoming too overconfident and improves its ability to handle ambiguous language.

**4. Early Stopping**

The training process is monitored using a separate validation dataset. If the performance on the validation set stops improving (or starts getting worse) while the training loss continues to drop, training is halted to preserve the model's ability to generalize.

**How it Works**

Regularization introduces a trade-off between bias and variance.
- Modification of Loss: The standard loss function (how wrong the model is) is modified to include a "complexity penalty."
- Noise Injection: Techniques like Dropout or Gaussian noise injection during training act as a form of "data augmentation," making the environment harder for the model so it learns more robust features.
- Constraint of Search Space: By penalizing large weights, the optimizer is restricted from exploring parts of the mathematical space that represent highly erratic or "jagged" functions.

**When to Use It**

Regularization should be a primary consideration in the following situations:
- Small Datasets: If fine-tuning an LLM on a very small, niche dataset (e.g., a few hundred medical records), the model is highly likely to memorize the samples. Strong regularization (high weight decay or dropout) is mandatory.
- Gap Between Training and Validation Loss: If the training loss is decreasing but the validation loss is increasing or flatlining, the model is overfitting and needs more regularization.
- High-Capacity Models: Large models (70B+ parameters) have a much higher "memorization capacity" than smaller models. They often require more aggressive regularization to ensure they remain useful for general tasks.
- Long Training Runs: When training for many epochs, the model eventually starts picking up on the specific noise of the dataset. Regularization helps extend the "useful" training window.

**Reference**
- [Arxiv:Selective LLM-Guided Regularization for Enhancing Recommendation Models](https://arxiv.org/html/2512.21526v1)
- [APXML:Regularization Techniques to Prevent Overfitting](https://apxml.com/courses/fine-tuning-adapting-large-language-models/chapter-3-full-parameter-fine-tuning/regularization-fine-tuning)

### Dropout

#### Layer Dropout

LayerDrop is a structural regularization technique specifically designed for deep transformer architectures like LLMs. While standard Dropout randomly deactivates individual neurons or connections, LayerDrop randomly skips entire transformer layers during each training forward pass. This creates a model that is robust to structural variations and allows for "structured pruning," where layers can be removed after training to create smaller, faster models without a significant loss in accuracy.

**How it Works**

LayerDrop treats the entire model as an ensemble of sub-networks with varying depths.
- Stochastic Skipping: For every batch of data, each layer is assigned a probability p of being "dropped." If the drop condition is met, the input to that layer is passed directly to the next layer, completely bypassing the attention and feed-forward calculations.
- Identity Mapping: Because LLMs utilize residual connections (Skip-connections), a dropped layer simply acts as an identity function: $x_{l+1} = x_l$.
- Inference Consistency: During inference (evaluation), LayerDrop is turned off. The model uses all its layers, but because it was trained to handle missing layers, it is much more resilient to the "noise" of deep stacks and less prone to vanishing gradients.
- Pruning Readiness: A unique side effect of LayerDrop is that it makes layers "expendable." After training, one can delete every other layer to reduce the model size by 50%, and the model will typically perform better than one trained from scratch at that smaller size.

**LayerDrop Implementation**

The script implements LayerDrop by dynamically overwriting the forward pass of the model's transformer layers.

**`LayerDropContext` Manager:**

This class acts as a temporary "patch." When it enters (`__enter__`), it scans the `model.model.layers` list and replaces the standard forward method of each layer with a custom wrapper.

**The Conditional Skip:**

Inside `forward_with_drop`, a random number is generated. If this number is lower than `LAYER_DROP_PROB`, the code returns `args[0]` (the input hidden states) directly, effectively skipping all the math inside that layer.

**`LayerDropTrainer` Integration:**

The custom trainer ensures that this skipping only happens during training. By wrapping `super().training_step` in the context manager, it applies the drop during the forward/backward pass and then immediately restores the original model architecture during the `__exit__` phase to ensure evaluation remains stable.

**State Restoration:**

The script saves `self.original_forwards` to ensure that after the training step is done, the model is returned to its full structural integrity, preventing permanent damage to the model's logic.

**When to Use It**

LayerDrop is particularly useful in specific LLM development lifecycles:
- Training Very Deep Models: In models with 80+ layers, LayerDrop helps stabilize training and prevents the "vanishing gradient" problem where early layers stop learning.
- Post-Training Compression: If the goal is to train a large "teacher" model and then prune it down to a smaller "student" model for mobile or edge deployment, LayerDrop is the best way to prepare the model for layer removal.
- Preventing Overfitting on Long Sequences: When fine-tuning on long-form data where the model might over-rely on deep hierarchical patterns that don't generalize, LayerDrop forces the model to learn more robust, shallow representations.
- Improving Generalization: It acts as a powerful regularizer, similar to Dropout but at a macro scale, preventing any single layer from becoming a "bottleneck" or memorizing specific training samples.

In [ ]:
import torch
import torch.nn as nn
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    DataCollatorForLanguageModeling,
    Trainer,
    TrainingArguments,
)
from datasets import DatasetDict, Dataset

In [8]:
# Configuration
MODEL_NAME = "google/gemma-3-270m"  # or gemma-2-2b if you want faster experiments
OUTPUT_DIR = "./gemma-3-270m-finetuned-qa"
LAYER_DROP_PROB = 0.1

# Simple & safe LayerDrop context manager
class LayerDropContext:
    def __init__(self, model: AutoModelForCausalLM, drop_prob: float = 0.1):
        self.model = model
        self.drop_prob = drop_prob
        self.original_forwards = []

    def __enter__(self):
        if not self.model.training or self.drop_prob <= 0:
            return

        layers = self.model.model.layers
        self.original_forwards = [layer.forward for layer in layers]

        for layer in layers:
            original_forward = layer.forward

            def forward_with_drop(*args, **kwargs):
                if torch.rand(1, device=args[0].device).item() < self.drop_prob:
                    # Skip layer → pass hidden states unchanged
                    return args[0]
                return original_forward(*args, **kwargs)

            layer.forward = forward_with_drop

    def __exit__(self, exc_type, exc_val, exc_tb):
        if not self.model.training or self.drop_prob <= 0:
            return
        layers = self.model.model.layers
        for layer, orig_forward in zip(layers, self.original_forwards):
            layer.forward = orig_forward

# Custom Trainer that applies LayerDrop only in training steps
class LayerDropTrainer(Trainer):
    def __init__(self, layer_drop_prob: float = 0.1, **kwargs):
        super().__init__(**kwargs)
        self.layer_drop_prob = layer_drop_prob

    def training_step(self, model, inputs, num_items_in_batch=None):
        with LayerDropContext(model, self.layer_drop_prob):
            return super().training_step(model, inputs, num_items_in_batch)

# Load model
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    torch_dtype=torch.float32,          # or torch.bfloat16 if GPU supports it
    device_map="auto",
    low_cpu_mem_usage=True,
)

# Data collator & training arguments
data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

monitor = EpochMonitor(model=model)

training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=2,
    per_device_eval_batch_size=2,
    gradient_accumulation_steps=4,
    learning_rate=2e-5,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_strategy="epoch",
    run_name="gemma-3-270m-qa-layerdrop",
    warmup_steps=100,
    lr_scheduler_type="cosine",
)

# Trainer with LayerDrop
trainer = LayerDropTrainer(
    layer_drop_prob=LAYER_DROP_PROB,
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
    callbacks = [monitor]
)


total_params = sum(p.numel() for p in model.parameters())
print(f"Total parameters: {total_params:,}")
print(f"Effective batch size: {training_args.per_device_train_batch_size * training_args.gradient_accumulation_steps}")
print(f"Layer drop probability: {LAYER_DROP_PROB}")
print("Starting training with LayerDrop...")
trainer.train()

trainer.save_model()
tokenizer.save_pretrained(OUTPUT_DIR)
print("Training completed!")

`torch_dtype` is deprecated! Use `dtype` instead!

model.safetensors:   0%|          | 0.00/536M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/236 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/133 [00:00<?, ?B/s]

Total parameters: 268,098,176
Effective batch size: 8
Layer drop probability: 0.1
Starting training with LayerDrop...
Initial Model Memory Footprint:
  Parameters: 268,098,176
  Precision: 4 bytes
  Total Memory: 3.81 GB
    - Parameters: 1.00 GB
    - KV Cache (est): 2.81 GB
  Estimated FLOPs per forward pass (batch=8, seq=512): 2.05 TFLOPS

============================================================
Epoch 0 Summary
============================================================
  Duration (s)         :        69.94
  Tokens Processed     :      171,008
  Throughput (token/s) :         2445
  Training Steps       :          167
  Avg CPU (%)          :         22.7
  Avg Memory (%)       :         11.3
  Total FLOPs          : 85.62 TFLOPS
  TFLOPS (per second)  :         1.22
  FLOPs (per token)    :  0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================
Epoch 1 Summary
============================================================
  Duration (s)         :        71.25
  Tokens Processed     :      171,008
  Throughput (token/s) :         2400
  Training Steps       :          167
  Avg CPU (%)          :         23.8
  Avg Memory (%)       :         11.4
  Total FLOPs          : 85.62 TFLOPS
  TFLOPS (per second)  :         1.20
  FLOPs (per token)    :  0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================
Epoch 2 Summary
============================================================
  Duration (s)         :        71.18
  Tokens Processed     :      171,008
  Throughput (token/s) :         2403
  Training Steps       :          167
  Avg CPU (%)          :         20.8
  Avg Memory (%)       :         11.4
  Total FLOPs          : 85.62 TFLOPS
  TFLOPS (per second)  :         1.20
  FLOPs (per token)    :  0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['lm_head.weight'].

============================================================
TRAINING COMPLETE
============================================================
Total Training Time: 241.75s
Total Epochs: 3
Average Epoch Time: 70.79s
Total Tokens Processed: 513,024
Average Throughput: 2122 tokens/second
Total FLOPs: 256.87 TFLOPS
Average TFLOPS (per second): 1.06
Overall FLOPs (per token): 0.50 GFLOPS

Final Metrics:
Memory Footprint: 3.81 GB
Inference Throughput: 2622 tokens/second
Total Training FLOPs: 85.62 TFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Training completed!

In [9]:
summarize_training_results(trainer, monitor)

====================================================================================================
TRAINING RESULTS SUMMARY TABLE
====================================================================================================
Epoch Training Loss Validation Loss Time (s) Tokens Processed Throughput (token/s) TFLOPS (per second) Avg CPU (%) Avg Memory (%) Training Steps
    0       12.9005          3.3766    69.94          171,008                 2445                1.22        22.7           11.3            167
    1        5.6405          3.3203    71.25          171,008                 2400                1.20        23.8           11.4            167
    2        4.9603          3.2927    71.18          171,008                 2402                1.20        20.8           11.4            167

----------------------------------------------------------------------------------------------------
TRAINING STATISTICS:
----------------------------------------------------------------------------------------------------
Total Training Time:      212.4 s
Average Epoch Time:       70.8 s
Total Tokens Processed:   513,024
Average Throughput:       2416 tokens/second
Average CPU Usage:        22.4%
Average Memory Usage:     11.4%
Total Training FLOPs:     256.87 TFLOPS
Average TFLOPS (per sec): 1.21
Overall FLOPs (per token): 0.50 GFLOPS

====================================================================================================

**Reference**
- [Arxiv:Layer-wise Regularized Dropout for Neural Language Models](https://arxiv.org/abs/2402.16361)
- [JMLR:Dropout: A Simple Way to Prevent Neural Networks from Overfitting](https://www.jmlr.org/papers/volume15/srivastava14a/srivastava14a.pdf?utm_content=buffer79b4)
- [PyTorch:Dropout](https://docs.pytorch.org/docs/stable/generated/torch.nn.Dropout.html)
- [Medium:Dropping the Knowledge Bomb: Understanding Dropout Layers in Deep Learning](https://medium.com/@utsavraj.ptn04/dropping-the-knowledge-bomb-understanding-dropout-layers-in-deep-learning-0612f517269d)

#### Attention Dropout

Attention Dropout is a specialized regularization technique that targets the attention mechanism of a Large Language Model. While standard dropout usually zeros out activations in the feed-forward layers, Attention Dropout specifically targets the attention weight matrix (the Softmax output). By randomly "dropping" specific attention connections during training, the model is forced to distribute its focus across multiple parts of the input sequence rather than over-relying on a few dominant tokens.

**How it Works**

The technique intervenes in the Scaled Dot-Product Attention calculation:
- Score Calculation: The model calculates the similarity between Queries (Q) and Keys (K).
- Softmax Normalization: These scores are converted into probabilities (attention weights) that sum to 1.
- Dropout Application: A random binary mask is applied to these probabilities. If a 20% dropout is set, 20% of the attention connections are zeroed out.
- Rescaling: The remaining weights are scaled by $\frac{1}{1-p}$ (where $p$ is the dropout probability) to ensure the total energy of the attention remains consistent.

By preventing the model from attending to the most "obvious" tokens in every training step, it discovers more subtle relationships between words, leading to a more robust understanding of context.

**Attention Dropout Implementation**

The provided code demonstrates two distinct ways to apply this regularization:

**Config-Based Approach:**

The script first modifies the AutoConfig before loading the model:

  config.attention_dropout = 0.2

This is the "native" way. Most modern LLM architectures (like Gemma) have built-in dropout layers within their attention implementation. Setting this variable ensures the model initializes with these layers active.

**Custom Trainer (Monkey-Patching):**

The `AttentionDropoutTrainer` provides a more manual, "forceful" implementation by wrapping the attention modules:
- Layer Targeting: It iterates through model.model.layers to find the self_attn modules.
- Forward Hook: It replaces the original forward method with attention_forward_with_dropout.
- Manual Masking: It checks for attention_probs, generates a torch.rand_like mask, and performs manual rescaling:

    attention_probs = attention_probs * dropout_mask.float()
    attention_probs = attention_probs / (1 - dropout_prob)

**Restoration:**

It uses a `try...finally` block to ensure the model structure is restored to normal after each loss computation, preventing the monkey-patch from leaking into evaluation steps.

**When to Use It**

Attention Dropout is particularly effective in these scenarios:
- Repetitive Training Data: If the fine-tuning dataset has very similar sentence structures, the model might "cheat" by only looking at specific positions. Dropout breaks this habit.
- Preventing "Attention Collapse": In very deep models, attention sometimes collapses, where all heads focus on the same tokens (like the `[SEP]` token or periods). Dropout forces heads to diversify.
- Small-Scale Fine-tuning: When adapting a pre-trained model to a small Q&A dataset, the model is prone to overfitting on specific keywords. Attention dropout prevents this by making the "path" from question to answer less predictable.
- Long-Context Tasks: When the model needs to pick up information from a large window, attention dropout ensures it doesn't ignore the middle of the text in favor of the beginning and end.

In [ ]:
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, DataCollatorForLanguageModeling, Trainer, TrainingArguments
from datasets import DatasetDict, Dataset

In [10]:
# Configuration
MODEL_NAME = "google/gemma-3-270m"
OUTPUT_DIR = "./gemma-3-270m-finetuned-qa"

# First load the config to modify dropout settings
from transformers import AutoConfig

config = AutoConfig.from_pretrained(MODEL_NAME)

# For Gemma models, adjust attention dropout through config
# Note: Gemma models use specific dropout parameters
config.attention_dropout = 0.2  # Increase attention dropout
config.hidden_dropout = 0.1     # Regular hidden dropout
config.resid_pdrop = 0.1        # Residual dropout

# Load model with modified config
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    config=config,  # Use modified config
    device_map="auto",
    dtype=torch.float32,
    low_cpu_mem_usage=True,
)

# Alternative approach: Custom attention dropout implementation
import torch.nn as nn
import torch.nn.functional as F

class AttentionDropoutTrainer(Trainer):
    def __init__(self, attention_dropout_prob=0.2, **kwargs):
        super().__init__(**kwargs)
        self.attention_dropout_prob = attention_dropout_prob
    
    def compute_loss(self, model, inputs, return_outputs=False, num_items_in_batch=None):
        # Apply attention dropout during training
        if model.training:
            # Monkey-patch attention forward methods
            original_attention_forwards = []
            layers = model.model.layers
            
            for layer in layers:
                # Get the attention module
                if hasattr(layer, 'self_attn'):
                    attention_module = layer.self_attn
                elif hasattr(layer, 'attention'):
                    attention_module = layer.attention
                else:
                    continue
                
                # Store original forward
                original_forward = attention_module.forward
                original_attention_forwards.append((attention_module, original_forward))
                
                # Create new forward with attention dropout
                def create_attention_forward(original_fn, dropout_prob):
                    def attention_forward_with_dropout(*args, **kwargs):
                        # Call original attention forward
                        outputs = original_fn(*args, **kwargs)
                        
                        # Apply dropout to attention weights if they exist
                        if hasattr(outputs, 'attention_probs'):
                            attention_probs = outputs.attention_probs
                            # Apply additional dropout
                            dropout_mask = torch.rand_like(attention_probs) > dropout_prob
                            attention_probs = attention_probs * dropout_mask.float()
                            attention_probs = attention_probs / (1 - dropout_prob)  # Scale to maintain expected value
                            outputs.attention_probs = attention_probs
                        
                        return outputs
                    return attention_forward_with_dropout
                
                attention_module.forward = create_attention_forward(original_forward, self.attention_dropout_prob)
        
        try:
            # Compute loss with modified attention
            loss = super().compute_loss(model, inputs, return_outputs, num_items_in_batch)
            return loss
        finally:
            # Restore original attention forward methods
            if model.training:
                for attention_module, original_forward in original_attention_forwards:
                    attention_module.forward = original_forward

data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

monitor = EpochMonitor(model=model)

training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=2,
    per_device_eval_batch_size=2,
    gradient_accumulation_steps=4,  # Increased for memory efficiency
    learning_rate=2e-5,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_strategy="epoch",
    run_name="gemma-3-270m-qa-attention-dropout",
    warmup_steps=100,
    lr_scheduler_type="cosine",
    max_grad_norm=1.0,
    gradient_checkpointing=True,  # Enable for memory efficiency
)

trainer = AttentionDropoutTrainer(
    attention_dropout_prob=0.2,
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
    callbacks = [monitor]
)

total_params = sum(p.numel() for p in model.parameters())
print(f"Total parameters: {total_params:,}")
print(f"Batch size: {training_args.per_device_train_batch_size}")
print(f"Gradient accumulation steps: {training_args.gradient_accumulation_steps}")
print(f"Attention dropout probability: {trainer.attention_dropout_prob}")
print("Starting training with Attention Dropout...")

train_result = trainer.train()

trainer.save_model()
tokenizer.save_pretrained(OUTPUT_DIR)

print("Training completed!")

Loading weights:   0%|          | 0/236 [00:00<?, ?it/s]

Total parameters: 268,098,176
Batch size: 2
Gradient accumulation steps: 4
Attention dropout probability: 0.2
Starting training with Attention Dropout...
Initial Model Memory Footprint:
  Parameters: 268,098,176
  Precision: 4 bytes
  Total Memory: 3.81 GB
    - Parameters: 1.00 GB
    - KV Cache (est): 2.81 GB
  Estimated FLOPs per forward pass (batch=8, seq=512): 2.05 TFLOPS

============================================================
Epoch 0 Summary
============================================================
  Duration (s)         :       110.21
  Tokens Processed     :      171,008
  Throughput (token/s) :         1552
  Training Steps       :          167
  Avg CPU (%)          :         19.2
  Avg Memory (%)       :         11.9
  Total FLOPs          : 85.62 TFLOPS
  TFLOPS (per second)  :         0.78
  FLOPs (per token)    :  0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================
Epoch 1 Summary
============================================================
  Duration (s)         :       110.74
  Tokens Processed     :      171,008
  Throughput (token/s) :         1544
  Training Steps       :          167
  Avg CPU (%)          :         23.7
  Avg Memory (%)       :         11.9
  Total FLOPs          : 85.62 TFLOPS
  TFLOPS (per second)  :         0.77
  FLOPs (per token)    :  0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================
Epoch 2 Summary
============================================================
  Duration (s)         :       110.97
  Tokens Processed     :      171,008
  Throughput (token/s) :         1541
  Training Steps       :          167
  Avg CPU (%)          :         22.7
  Avg Memory (%)       :         11.9
  Total FLOPs          : 85.62 TFLOPS
  TFLOPS (per second)  :         0.77
  FLOPs (per token)    :  0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['lm_head.weight'].

============================================================
TRAINING COMPLETE
============================================================
Total Training Time: 364.68s
Total Epochs: 3
Average Epoch Time: 110.64s
Total Tokens Processed: 513,024
Average Throughput: 1407 tokens/second
Total FLOPs: 256.87 TFLOPS
Average TFLOPS (per second): 0.70
Overall FLOPs (per token): 0.50 GFLOPS

Final Metrics:
Memory Footprint: 3.81 GB
Inference Throughput: 1670 tokens/second
Total Training FLOPs: 85.62 TFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Training completed!

In [11]:
summarize_training_results(trainer, monitor)

====================================================================================================
TRAINING RESULTS SUMMARY TABLE
====================================================================================================
Epoch Training Loss Validation Loss Time (s) Tokens Processed Throughput (token/s) TFLOPS (per second) Avg CPU (%) Avg Memory (%) Training Steps
    0        2.4410          4.0339   110.21          171,008                 1551                0.78        19.2           11.9            167
    1        1.0611          5.1864   110.74          171,008                 1544                0.77        23.7           11.9            167
    2        0.7410          5.4665   110.97          171,008                 1541                0.77        22.7           11.9            167

----------------------------------------------------------------------------------------------------
TRAINING STATISTICS:
----------------------------------------------------------------------------------------------------
Total Training Time:      331.9 s
Average Epoch Time:       110.6 s
Total Tokens Processed:   513,024
Average Throughput:       1546 tokens/second
Average CPU Usage:        21.9%
Average Memory Usage:     11.9%
Total Training FLOPs:     256.87 TFLOPS
Average TFLOPS (per sec): 0.77
Overall FLOPs (per token): 0.50 GFLOPS

====================================================================================================

**Reference**
- [Arxiv:Not All Attention Is All You Need](https://arxiv.org/abs/2104.04692)
- [Arxiv:DropAttention: A Regularization Method for Fully-Connected Self-Attention Networks](https://arxiv.org/abs/1907.11065)
- [PyTorch:Dropout](https://docs.pytorch.org/docs/stable/generated/torch.nn.Dropout.html)
- [Arxiv:Attention-Driven Reasoning: Unlocking the Potential of Large Language Models](https://arxiv.org/html/2403.14932v1)
- [APXML:Top 6 Regularization Techniques for Transformer Models](https://apxml.com/posts/transformer-model-regularization-techniques)

### Weight Regularization

#### Selective Weight Decay

Selective Weight Decay is a refined regularization strategy that applies different levels of "penalty" to different types of neural network parameters. In standard $L_2$ regularization, every weight in the model is slightly reduced during each update to prevent any single value from becoming too large. However, in LLMs, certain parameters—specifically biases and normalization layers—serve as critical offsets or stability anchors. Applying weight decay to these specific parameters can destabilize training or lead to "underfitting" by forcing them toward zero when they need to remain at a specific non-zero value to function correctly.

**How it Works**

The optimization process separates the model parameters into distinct "groups" before training begins.
- Grouping by Name: The system scans the model's internal naming structure (e.g., self_attn.q_proj.weight vs. self_attn.q_proj.bias).
- Identifying "No-Decay" Tensors: Parameters like biases (which provide the intercept for linear equations) and LayerNorm weights/biases (which control the scaling of activations) are identified. These are typically one-dimensional vectors.
- Identifying "Decay" Tensors: The heavy-lifting weight matrices (2D tensors used in attention and feed-forward layers) are grouped separately.
- Differential Penalty: During the backpropagation step, the optimizer applies the weight decay coefficient (e.g., 0.01) to the weight matrices but sets the coefficient to 0.0 for the biases and normalization layers.

**Selective Weight Decay Implementation**

The script implements this logic through a custom optimizer initialization function that overrides the default behavior of the Trainer.

**Parameter Filtering:**

The `get_optimizer` function iterates through `model.named_parameters()`. It uses a list of strings—`["bias", "layer_norm", "layernorm"]`—to detect parameters that should be excluded from regularization.

**Group Creation:** 

It builds a list called `optimizer_grouped_parameters`. This list contains two dictionaries:
- The first dictionary contains the heavy matrix weights with `"weight_decay": 0.01`.
- The second dictionary contains the offsets and norms with `"weight_decay": 0.0`.

**Optimizer Hand-off:**

These groups are passed to `bnb.optim.AdamW8bit`. The optimizer is smart enough to apply the specific decay rate assigned to each group individually during the update step.

**Trainer Integration:**

By passing `optimizers=(get_optimizer(model), None)` to the Trainer class, the script ensures that the Hugging Face library uses this custom grouped setup instead of its standard internal optimizer.

**When to Use It**

Selective weight decay is considered a "best practice" in modern deep learning and should be used in almost all LLM fine-tuning scenarios:
- Fine-tuning Small/Medium LLMs: For models like Gemma-3-270m, stability is key. Over-regularizing the normalization layers can cause the model's internal activations to drift, leading to nonsensical text generation.
- Training with AdamW: Since the AdamW optimizer decouples weight decay from the gradient update, selective decay ensures that the "normalization" logic of the model remains intact while the "pattern matching" logic of the matrices is regularized.
- Low-Resource Data: When the dataset is small, the model is prone to over-relying on biases to "memorize" the limited samples. Setting bias decay to zero while keeping matrix decay high helps the model generalize without breaking its internal math.
- High-Precision Tasks: In tasks like mathematical reasoning or code generation, where specific numerical thresholds in the hidden states are important, avoiding decay on LayerNorm parameters preserves the necessary numerical precision.

In [ ]:
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, DataCollatorForLanguageModeling, Trainer, TrainingArguments
from datasets import DatasetDict, Dataset
import bitsandbytes as bnb

In [12]:
# Configuration
MODEL_NAME = "google/gemma-3-270m"
OUTPUT_DIR = "./gemma-3-270m-finetuned-qa"

# Load model
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    device_map="auto",
    torch_dtype=torch.float32,
    low_cpu_mem_usage=True,
)

# Optimizer with selective weight decay
def get_optimizer(model):
    decay_params = []
    no_decay_params = []
    
    for name, param in model.named_parameters():
        if param.requires_grad:
            if any(nd in name for nd in ["bias", "layer_norm", "layernorm"]):
                no_decay_params.append(param)
            else:
                decay_params.append(param)
    
    optimizer_grouped_parameters = [
        {"params": decay_params, "weight_decay": 0.01},
        {"params": no_decay_params, "weight_decay": 0.0},
    ]
    
    optimizer = bnb.optim.AdamW8bit(
        optimizer_grouped_parameters,
        lr=2e-5,
        betas=(0.9, 0.999),
        eps=1e-8,
    )
    
    return optimizer

data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

monitor = EpochMonitor(model=model)

training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=2,
    per_device_eval_batch_size=2,
    gradient_accumulation_steps=1,
    learning_rate=2e-5,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_strategy="epoch",
    run_name="gemma-3-270m-qa-selective-weight-decay",
    warmup_ratio=0.1,
    lr_scheduler_type="cosine",
    optim="adamw_bnb_8bit",
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
    optimizers=(get_optimizer(model), None),
    callbacks = [monitor]
)

total_params = sum(p.numel() for p in model.parameters())
print(f"Total parameters: {total_params:,}")
print(f"Batch size: {training_args.per_device_train_batch_size}")
print("Starting training with Selective Weight Decay...")

train_result = trainer.train()

trainer.save_model()
tokenizer.save_pretrained(OUTPUT_DIR)

print("Training completed!")

Loading weights:   0%|          | 0/236 [00:00<?, ?it/s]

warmup_ratio is deprecated and will be removed in v5.2. Use `warmup_steps` instead.

Total parameters: 268,098,176
Batch size: 2
Starting training with Selective Weight Decay...
Initial Model Memory Footprint:
  Parameters: 268,098,176
  Precision: 4 bytes
  Total Memory: 3.81 GB
    - Parameters: 1.00 GB
    - KV Cache (est): 2.81 GB
  Estimated FLOPs per forward pass (batch=8, seq=512): 2.05 TFLOPS

============================================================
Epoch 0 Summary
============================================================
  Duration (s)         :         94.70
  Tokens Processed     :       681,984
  Throughput (token/s) :          7201
  Training Steps       :           666
  Avg CPU (%)          :          22.1
  Avg Memory (%)       :          12.3
  Total FLOPs          : 341.47 TFLOPS
  TFLOPS (per second)  :          3.61
  FLOPs (per token)    :   0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================
Epoch 1 Summary
============================================================
  Duration (s)         :         95.30
  Tokens Processed     :       681,984
  Throughput (token/s) :          7156
  Training Steps       :           666
  Avg CPU (%)          :          17.7
  Avg Memory (%)       :          12.3
  Total FLOPs          : 341.47 TFLOPS
  TFLOPS (per second)  :          3.58
  FLOPs (per token)    :   0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================
Epoch 2 Summary
============================================================
  Duration (s)         :         95.03
  Tokens Processed     :       681,984
  Throughput (token/s) :          7176
  Training Steps       :           666
  Avg CPU (%)          :          20.2
  Avg Memory (%)       :          12.3
  Total FLOPs          : 341.47 TFLOPS
  TFLOPS (per second)  :          3.59
  FLOPs (per token)    :   0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['lm_head.weight'].

============================================================
TRAINING COMPLETE
============================================================
Total Training Time: 308.17s
Total Epochs: 3
Average Epoch Time: 95.01s
Total Tokens Processed: 2,045,952
Average Throughput: 6639 tokens/second
Total FLOPs: 1024.40 TFLOPS
Average TFLOPS (per second): 3.32
Overall FLOPs (per token): 0.50 GFLOPS

Final Metrics:
Memory Footprint: 3.81 GB
Inference Throughput: 7343 tokens/second
Total Training FLOPs: 341.47 TFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Training completed!

In [13]:
summarize_training_results(trainer, monitor)

====================================================================================================
TRAINING RESULTS SUMMARY TABLE
====================================================================================================
Epoch Training Loss Validation Loss Time (s) Tokens Processed Throughput (token/s) TFLOPS (per second) Avg CPU (%) Avg Memory (%) Training Steps
    0        1.6280          4.8104    94.70          681,984                 7201                3.61        22.1           12.3            666
    1        0.6489          6.1725    95.30          681,984                 7155                3.58        17.7           12.3            666
    2        0.3569          6.9199    95.03          681,984                 7176                3.59        20.2           12.3            666

----------------------------------------------------------------------------------------------------
TRAINING STATISTICS:
----------------------------------------------------------------------------------------------------
Total Training Time:      285.0 s
Average Epoch Time:       95.0 s
Total Tokens Processed:   2,045,952
Average Throughput:       7178 tokens/second
Average CPU Usage:        20.0%
Average Memory Usage:     12.3%
Total Training FLOPs:     1024.40 TFLOPS
Average TFLOPS (per sec): 3.59
Overall FLOPs (per token): 0.50 GFLOPS

====================================================================================================

**Reference**
- [Arxiv:Why Do We Need Weight Decay in Modern Deep Learning?](https://arxiv.org/abs/2310.04415)
- [Arxiv:Rethinking Weight Decay for Robust Fine-Tuning of Foundation Models](https://arxiv.org/abs/2411.01713)
- [Arxiv:Rethinking Weight Decay For Efficient Neural Network Pruning](https://arxiv.org/abs/2011.10520)
- [PyTorch:torch.optim](https://docs.pytorch.org/docs/stable/optim.html)
- [Medium:Deep Learning Basics — Practical Guide to Weight Decay in PyTorch](https://medium.com/we-talk-data/deep-learning-basics-practical-guide-to-weight-decay-in-pytorch-d9e26fc669db)

#### Orthogonal Regularization

Orthogonal Regularization is an optimization technique that forces the weight matrices of a neural network to stay "orthogonal." In a perfectly orthogonal matrix, every column (or row) is a vector that is perpendicular (at a 90-degree angle) to every other column and has a length of one. In Large Language Models, this prevents different neurons in the same layer from learning the exact same features. By keeping the weights orthogonal, the model is forced to find a diverse set of independent patterns, which maximizes the "expressive power" of each layer.

**How it Works**

The mathematical goal of this regularization is to ensure that for a weight matrix $W$, the product of the matrix and its transpose is equal to the identity matrix $I$.$$W W^T = I$$

- Similarity Check: The system calculates the dot product of the weights. If the weights are orthogonal, the dot product of any two different rows will be zero, and the dot product of a row with itself will be one.
- Penalty Calculation: The algorithm measures how much the current matrix $W W^T$ deviates from the identity matrix $I$. This deviation is usually measured using the Frobenius Norm.
- Constraint: This deviation is added to the training loss as a penalty. To minimize the total loss, the optimizer must change the weights so that the matrix becomes more orthogonal.
- Signal Preservation: Because orthogonal matrices preserve the length of vectors during transformation, this technique helps prevent gradients from "exploding" or "vanishing" as they pass through many layers.

**Orthogonal Regularization Implementation**

The provided script uses a custom TrainerCallback to apply this constraint periodically during the training process without modifying the core model architecture.

**Layer Filtering:**

The on_step_end method iterates through all parameters but specifically targets those with two dimensions `(len(param.shape) == 2)`. This ensures the logic applies to weight matrices (like those in attention or feed-forward layers) but ignores 1D vectors like biases or layer norms.

**Matrix Multiplication:**

It performs the operation `torch.mm(param, param.transpose(0, 1))`. This calculates the correlation between the various "features" learned by that layer.

**Frobenius Norm Penalty:**

The code creates an identity matrix (`torch.eye`) of the same size and calculates the difference:

    orth_loss += torch.norm(prod - identity, p='fro')

The "fro" (Frobenius) norm acts as a measure of the total error between the current weights and a perfectly orthogonal state.

**Optimization Step:**

Every 100 steps, if an orth_loss exists, the callback performs an extra "mini-update." It calculates the gradient of this specific loss (`orth_loss.backward()`) and tells the optimizer to adjust the weights to satisfy the orthogonality constraint.

**When to Use It**

Orthogonal Regularization is highly effective in specific LLM training scenarios:
- Training Very Deep Transformers: It acts as a structural stabilizer, ensuring that gradients flow smoothly through deep stacks (e.g., 40+ layers) without losing information.
- High-Dimensional Latent Spaces: When using large hidden sizes (e.g., 4096 or higher), neurons often become redundant. Orthogonality forces the model to use the entire available "mathematical space" rather than collapsing into a few active dimensions.
- Low-Rank Adaptation (LoRA) or Fine-tuning: If the model is being fine-tuned on a narrow task, it might lose its general knowledge. Orthogonal regularization keeps the internal representations "spread out," preserving more of the pre-trained knowledge.
- Preventing Feature Redundancy: Use it when the model keeps outputting repetitive phrases or exhibits "mode collapse," where many different inputs lead to very similar hidden states.

In [ ]:
import torch
import torch.nn as nn
from transformers import AutoTokenizer, AutoModelForCausalLM, DataCollatorForLanguageModeling, Trainer, TrainingArguments
from datasets import DatasetDict, Dataset

In [ ]:
# Configuration
MODEL_NAME = "google/gemma-3-270m"
OUTPUT_DIR = "./gemma-3-270m-finetuned-qa"

class OrthogonalRegularizationCallback(TrainerCallback):
    def __init__(self, reg_lambda=1e-4):
        self.reg_lambda = reg_lambda
    
    def on_step_end(self, args, state, control, model, **kwargs):
        if state.global_step % 100 == 0:
            orth_loss = 0.0
            for name, param in model.named_parameters():
                if param.requires_grad and len(param.shape) == 2:
                    if param.shape[0] > 1 and param.shape[1] > 1:
                        prod = torch.mm(param, param.transpose(0, 1))
                        identity = torch.eye(prod.shape[0], device=prod.device)
                        orth_loss += torch.norm(prod - identity, p='fro')
            
            if orth_loss > 0:
                orth_loss = self.reg_lambda * orth_loss
                if kwargs.get("optimizer") is not None:
                    kwargs["optimizer"].zero_grad()
                    orth_loss.backward()
                    kwargs["optimizer"].step()

# Load model
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    device_map="auto",
    torch_dtype=torch.float32,
    low_cpu_mem_usage=True,
)

data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

monitor = EpochMonitor(model=model)

training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=2,
    per_device_eval_batch_size=2,
    gradient_accumulation_steps=1,
    learning_rate=2e-5,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_strategy="epoch",
    run_name="gemma-3-270m-qa-orthogonal-reg",
    warmup_ratio=0.1,
    lr_scheduler_type="cosine",
)

orth_callback = OrthogonalRegularizationCallback(reg_lambda=1e-4)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
    callbacks=[orth_callback, monitor],
)

total_params = sum(p.numel() for p in model.parameters())
print(f"Total parameters: {total_params:,}")
print(f"Batch size: {training_args.per_device_train_batch_size}")
print("Starting training with Orthogonal Regularization...")

train_result = trainer.train()

trainer.save_model()
tokenizer.save_pretrained(OUTPUT_DIR)

print("Training completed!")

In [ ]:
summarize_training_results(trainer, monitor)

**Reference**
- [Arxiv:Towards Better Orthogonality Regularization with Disentangled Norm in Training Deep CNNs](https://arxiv.org/abs/2306.09939)
- [NeurIPS:Orthogonality Regularization for Compatible Representation Learning](https://neurips.cc/virtual/2025/loc/san-diego/poster/119181)
- [PyTorch:torch.nn](https://docs.pytorch.org/docs/stable/nn.html)

## Optimization Stability

Optimization Stability refers to the set of techniques used to keep the training process of a Large Language Model within a "safe" mathematical range. LLMs are highly sensitive to the magnitude of their weight updates; if updates are too large, the model’s internal logic can shatter (model collapse), and if they are too erratic, the model may overwrite useful old knowledge with new, noisy data (catastrophic forgetting).

Stability methods ensure that the path the optimizer takes toward the "minimum error" is smooth and controlled, rather than chaotic and explosive.

**How it Works**

Optimization stability relies on two primary "safety valves" that control the energy of the learning process:

**1. Learning Rate Warmup**

At the very start of training, the model's gradients are often chaotic and unreliable because the weights (or the new task's gradients) haven't "settled" yet.
- The Mechanism: Instead of starting at the target learning rate (e.g., $2 \times 10^{-5}$), the model starts at nearly zero. It gradually ramps up to the target rate over the first few hundred or thousand steps.
- The Benefit: This allows the model to "warm up" its internal moments (in optimizers like AdamW) without taking a massive, destructive leap in the wrong direction during the first few batches.

**2. Gradient Clipping**

Sometimes, during backpropagation, the gradients can "explode," reaching mathematically massive values that would flip weights to extreme numbers (or even NaN).
- The Mechanism: Before applying the update, the total "norm" (length) of the gradient vector is calculated. If it exceeds a predefined threshold (usually 1.0), the entire vector is scaled down so its length equals that threshold.
- The Benefit: It preserves the direction of the update (the model still learns what it needs to) but caps the intensity, preventing a single "bad batch" of data from ruining the entire model.

**When to Use It**

Stability techniques are non-negotiable in the following LLM scenarios:
- Instruction Fine-Tuning: When adapting a base model to follow instructions, the gradients can be very sharp. Without warmup and clipping, the model may quickly lose its "pre-trained common sense."
- Large Batch Training: When using high gradient_accumulation_steps or large distributed batches, the "force" of each update is much higher. Stability controls are required to prevent these massive updates from over-correcting the weights.
- Mixed-Precision Training (FP16/BF16): Lower precision math is more susceptible to numerical instability. Gradient clipping is the primary defense against "loss spikes" that occur when numbers become too large for the 16-bit format to handle.
- Continual Learning: If you are adding new knowledge to a model over a long period, using a "cool" learning rate with a long warmup helps the new information integrate into the existing neural structure without "exploding" the old connections.

**Stability in Practice**

In the Hugging Face `TrainingArguments`, these are typically defined as:

- `warmup_steps=500 (or warmup_ratio=0.1)`
- `max_grad_norm=1.0`

**Reference**
- [Arxiv:LLM Stability: A detailed analysis with some surprises](https://arxiv.org/html/2408.04667v2)
- [Aclanthology:A Joint Optimization Framework for Enhancing Efficiency of Tool Utilization in LLM Agents](https://aclanthology.org/2025.findings-acl.1149.pdf)
- [Arxiv:A Closer Look at Learned Optimization: Stability, Robustness, and Inductive Biases](https://arxiv.org/abs/2209.11208)
- [Huggingface:Trainer](https://huggingface.co/docs/transformers/en/main_classes/trainer)

### Enhanced Gradient Clipping

Gradient Clipping is a critical stability technique used during the backpropagation phase of training Large Language Models. It identifies and scales down mathematical gradients that have become too large ("exploding gradients"). In deep networks like transformers, a single batch containing an outlier or a complex linguistic pattern can generate a gradient so massive that it pushes the model's weights into extreme values, causing the training loss to become NaN (Not a Number) and effectively destroying the model's intelligence.

**How it Works**

Gradient clipping typically comes in two flavors, with the "Norm-based" approach being the standard for LLMs:
- Norm-based Clipping (Global Norm): The total magnitude (length) of the gradient vector for the entire model is calculated. If this total length exceeds a threshold ($L$), the entire gradient vector is rescaled.
    - Formula: $g = g \times \min(1, \frac{L}{\|g\|})$
    - Result: The direction of the update remains exactly the same, but the intensity is capped. This is generally preferred for transformers because it preserves the relationship between different layers.
- Value-based Clipping: Every individual element in the gradient matrix is checked. If any value is greater than 0.5 or less than −0.5, it is forced (clamped) to those specific limits.
    - Result: This can change the direction of the gradient vector, which occasionally makes training less stable than norm-based clipping.

**Gradient Clipping Implementation**

The script utilizes the built-in stability controls of the Hugging Face TrainingArguments to handle the heavy lifting:

- Setting the Threshold: The parameter `max_grad_norm=1.0` defines the maximum allowable $L_2$ norm for the gradients. A value of $1.0$ is the industry standard for models like Gemma or Llama.
- The Internal Logic: During the `trainer.train()` loop, the following sequence occurs automatically after the backward pass but before the weights are updated:
    - The gradients for all trainable parameters are collected.
    - The global norm is calculated across all parameters.
    - If the norm > $1.0$, the gradients are multiplied by $\frac{1.0}{\text{current\_norm}}$.
- Interaction with Checkpointing: Because `gradient_checkpointing=True` is enabled in the code, the model saves memory by recomputing activations. Gradient clipping is even more important here, as any numerical instability in the recomputed pass could lead to "spikes" that clipping successfully neutralizes.

**When to Use It**

Gradient clipping should be enabled in nearly every LLM fine-tuning configuration:
- Deep Architectures: Any model with more than 12–24 layers (Gemma-3-270m has many) is at high risk of gradient explosion due to the chain rule of calculus.
- Mixed Precision (FP16/BF16): When training in 16-bit precision (common for speed), the range of numbers the computer can handle is limited. Clipping prevents "Overflow" errors where numbers become too large for the memory format.
- Variable Sequence Lengths: If some training examples are very short and others are very long (up to the MAX_LENGTH of 128), the long sequences often generate much larger gradients. Clipping ensures the long sequences don't dominate the learning process.
- High Learning Rates: If attempting to train with a more aggressive learning rate to speed up convergence, clipping acts as a "guardrail" to keep the model from flying off the mathematical tracks.

In [ ]:
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, DataCollatorForLanguageModeling, Trainer, TrainingArguments
from datasets import DatasetDict, Dataset

In [14]:
# Configuration
MODEL_NAME = "google/gemma-3-270m"
OUTPUT_DIR = "./gemma-3-270m-finetuned-qa"

# Load model
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    device_map="auto",
    torch_dtype=torch.float32,
    low_cpu_mem_usage=True,
)

data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

monitor = EpochMonitor(model=model)

training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=2,
    per_device_eval_batch_size=2,
    gradient_accumulation_steps=1,
    learning_rate=2e-5,
    weight_decay=0.01,
    max_grad_norm=1.0,  # Gradient clipping norm
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_strategy="epoch",
    run_name="gemma-3-270m-qa-grad-clip",
    warmup_steps=100,
    lr_scheduler_type="cosine",
    gradient_checkpointing=True,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
    callbacks = [monitor]
)

total_params = sum(p.numel() for p in model.parameters())
print(f"Total parameters: {total_params:,}")
print(f"Batch size: {training_args.per_device_train_batch_size}")
print("Starting training with Gradient Clipping...")

train_result = trainer.train()

trainer.save_model()
tokenizer.save_pretrained(OUTPUT_DIR)

print("Training completed!")

Loading weights:   0%|          | 0/236 [00:00<?, ?it/s]

Total parameters: 268,098,176
Batch size: 2
Starting training with Gradient Clipping...
Initial Model Memory Footprint:
  Parameters: 268,098,176
  Precision: 4 bytes
  Total Memory: 3.81 GB
    - Parameters: 1.00 GB
    - KV Cache (est): 2.81 GB
  Estimated FLOPs per forward pass (batch=8, seq=512): 2.05 TFLOPS

============================================================
Epoch 0 Summary
============================================================
  Duration (s)         :        127.36
  Tokens Processed     :       681,984
  Throughput (token/s) :          5355
  Training Steps       :           666
  Avg CPU (%)          :          22.2
  Avg Memory (%)       :          12.7
  Total FLOPs          : 341.47 TFLOPS
  TFLOPS (per second)  :          2.68
  FLOPs (per token)    :   0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================
Epoch 1 Summary
============================================================
  Duration (s)         :        127.08
  Tokens Processed     :       681,984
  Throughput (token/s) :          5366
  Training Steps       :           666
  Avg CPU (%)          :          19.5
  Avg Memory (%)       :          12.7
  Total FLOPs          : 341.47 TFLOPS
  TFLOPS (per second)  :          2.69
  FLOPs (per token)    :   0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================
Epoch 2 Summary
============================================================
  Duration (s)         :        127.81
  Tokens Processed     :       681,984
  Throughput (token/s) :          5336
  Training Steps       :           666
  Avg CPU (%)          :          21.4
  Avg Memory (%)       :          12.7
  Total FLOPs          : 341.47 TFLOPS
  TFLOPS (per second)  :          2.67
  FLOPs (per token)    :   0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['lm_head.weight'].

============================================================
TRAINING COMPLETE
============================================================
Total Training Time: 411.80s
Total Epochs: 3
Average Epoch Time: 127.42s
Total Tokens Processed: 2,045,952
Average Throughput: 4968 tokens/second
Total FLOPs: 1024.40 TFLOPS
Average TFLOPS (per second): 2.49
Overall FLOPs (per token): 0.50 GFLOPS

Final Metrics:
Memory Footprint: 3.81 GB
Inference Throughput: 7012 tokens/second
Total Training FLOPs: 341.47 TFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Training completed!

In [15]:
summarize_training_results(trainer, monitor)

====================================================================================================
TRAINING RESULTS SUMMARY TABLE
====================================================================================================
Epoch Training Loss Validation Loss Time (s) Tokens Processed Throughput (token/s) TFLOPS (per second) Avg CPU (%) Avg Memory (%) Training Steps
    0        1.5358          5.1689   127.36          681,984                 5354                2.68        22.2           12.7            666
    1        0.6226          6.4211   127.08          681,984                 5366                2.69        19.5           12.7            666
    2        0.3453          6.9527   127.81          681,984                 5336                2.67        21.4           12.7            666

----------------------------------------------------------------------------------------------------
TRAINING STATISTICS:
----------------------------------------------------------------------------------------------------
Total Training Time:      382.3 s
Average Epoch Time:       127.4 s
Total Tokens Processed:   2,045,952
Average Throughput:       5352 tokens/second
Average CPU Usage:        21.0%
Average Memory Usage:     12.7%
Total Training FLOPs:     1024.40 TFLOPS
Average TFLOPS (per sec): 2.68
Overall FLOPs (per token): 0.50 GFLOPS

====================================================================================================

**Reference**
- [Arxiv:AGGC: Adaptive Group Gradient Clipping for Stabilizing Large Language Model Training](https://arxiv.org/abs/2601.11864)
- [Arxiv:AdaGC: Improving Training Stability for Large Language Model Pretraining](https://arxiv.org/html/2502.11034v1)
- [APXML:Gradient Clipping Techniques](https://apxml.com/courses/how-to-build-a-large-language-model/chapter-17-optimization-algorithms-llms/gradient-clipping-techniques)
- [Medium:Gradient Clipping, Accumulation, and More: Essential Techniques for Effective Training](https://medium.com/@_prinsh_u/gradient-clipping-accumulation-and-more-essential-techniques-for-effective-training-c08f59c8b15d)
- [Medium:The 4 Gradient Clipping Methods: How to Prevent Training from Exploding](https://pub.towardsai.net/the-4-gradient-clipping-methods-how-to-prevent-training-from-exploding-aa83050b356f)
- [Huggingface:Trainer](https://huggingface.co/docs/transformers/en/main_classes/trainer)

### Lookahead Optimization

Lookahead Optimization is a hierarchical optimization strategy that improves the stability and convergence of Large Language Models. Instead of relying solely on a single optimizer to update weights, Lookahead maintains two sets of weights: "Fast Weights" and "Slow Weights." The fast weights explore the loss landscape aggressively, while the slow weights follow behind at a more stable pace, acting as a long-term moving average that prevents the model from getting stuck in sharp, noisy local minima.

**How it Works**

The algorithm operates in a "lead and follow" pattern:
- Fast Update: A standard "inner" optimizer (like AdamW) updates the fast weights for k successive steps. These weights move quickly to respond to the current batch of data.
- Slow Update: Every k steps (the synchronization period), the slow weights are updated by moving them toward the current position of the fast weights.
- Interpolation: The new position is determined by a step size $\alpha$ (the lookahead learning rate). The formula is:$$\theta_{slow} = \theta_{slow} + \alpha (\theta_{fast} - \theta_{slow})$$
- Reset: After the slow update, the fast weights are typically synchronized back to the new slow weight position to start the next cycle from a stable foundation.

This dual-speed mechanism allows the optimizer to "look ahead" at the direction the fast weights are taking and only commit to that direction if it proves consistent over several steps.

**Lookahead Optimization Implementation**

The provided script implements this as a wrapper around a base optimizer:
- Weight Storage: In the `__init__` method, the code creates a `slow_weights` copy for every trainable parameter using `p.data.clone().detach()`.
- The Inner Loop: The step method first calls `self.base_optimizer.step()`. This performs the standard `AdamW` update on the active model parameters (the "fast" weights).
- Periodic Synchronization: The `self.counter % self.k == 0` check ensures that the slow update only happens every k steps (set to 5 in the configuration).
- Linear Interpolation: The code uses `slow_weights.data.add_(p.data - slow_weights, alpha=self.alpha)` to move the slow weights toward the fast weights by the fraction defined by `α` (0.5).
- Trainer Integration: The `LookaheadTrainer` class is customized to ensure that the learning rate scheduler correctly targets the `base_optimizer` (AdamW) while the LookaheadOptimizer manages the high-level weight averaging.

**When to Use It**

Lookahead Optimization is highly effective in the following scenarios:
- Noisy Loss Landscapes: LLM fine-tuning can often encounter "sharp" minima where the loss fluctuates wildly. Lookahead smooths these fluctuations, leading to better final performance.
- Sensitivity to Learning Rates: If finding the "perfect" learning rate for a specific dataset is difficult, Lookahead provides a safety net that makes the model more robust to sub-optimal hyperparameter choices.
- Preventing Catastrophic Forgetting: By maintaining the "slow" weights, the model retains a more stable memory of the pre-trained weights, making it less likely that a few noisy fine-tuning batches will overwrite critical general knowledge.
- Faster Convergence: While it requires slightly more memory to store the slow weight copies, Lookahead often reaches lower loss values in fewer total iterations than standard AdamW alone.

In [ ]:
import torch
from torch.optim import AdamW
from transformers import AutoTokenizer, AutoModelForCausalLM, DataCollatorForLanguageModeling, Trainer, TrainingArguments
from datasets import DatasetDict, Dataset

In [9]:
# Configuration
MODEL_NAME = "google/gemma-3-270m"
OUTPUT_DIR = "./gemma-3-270m-finetuned-qa"

# Proper Lookahead Optimizer implementation
class LookaheadOptimizer(torch.optim.Optimizer):
    def __init__(self, base_optimizer, k=5, alpha=0.5):
        if not isinstance(base_optimizer, torch.optim.Optimizer):
            raise TypeError(f'{type(base_optimizer).__name__} is not an Optimizer')
        
        # Initialize as proper Optimizer
        defaults = dict(k=k, alpha=alpha)
        super().__init__(base_optimizer.param_groups, defaults)
        
        self.base_optimizer = base_optimizer
        self.k = k
        self.alpha = alpha
        self.counter = 0
        
        # Initialize slow weights
        for group in self.param_groups:
            for p in group['params']:
                param_state = self.state[p]
                param_state['slow_weights'] = p.data.clone().detach()
    
    def __getstate__(self):
        return {
            'defaults': self.defaults,
            'state': self.state,
            'param_groups': self.param_groups,
            'base_optimizer': self.base_optimizer,
            'k': self.k,
            'alpha': self.alpha,
            'counter': self.counter,
        }
    
    def __setstate__(self, state):
        self.__dict__.update(state)
    
    def state_dict(self):
        # Include base optimizer state
        base_state = self.base_optimizer.state_dict()
        lookahead_state = {
            'counter': self.counter,
            'slow_weights': {},
        }
        
        # Save slow weights
        for group_idx, group in enumerate(self.param_groups):
            for param_idx, p in enumerate(group['params']):
                if p in self.state:
                    lookahead_state['slow_weights'][f'group{group_idx}_param{param_idx}'] = \
                        self.state[p]['slow_weights'].clone()
        
        return {
            'base_optimizer': base_state,
            'lookahead': lookahead_state,
        }
    
    def load_state_dict(self, state_dict):
        # Load base optimizer state
        self.base_optimizer.load_state_dict(state_dict['base_optimizer'])
        
        # Load slow weights
        lookahead_state = state_dict['lookahead']
        self.counter = lookahead_state.get('counter', 0)
        
        for group_idx, group in enumerate(self.param_groups):
            for param_idx, p in enumerate(group['params']):
                key = f'group{group_idx}_param{param_idx}'
                if key in lookahead_state['slow_weights']:
                    if p in self.state:
                        self.state[p]['slow_weights'] = lookahead_state['slow_weights'][key].clone()
    
    def zero_grad(self, set_to_none=True):
        self.base_optimizer.zero_grad(set_to_none=set_to_none)
    
    def step(self, closure=None):
        loss = None
        if closure is not None:
            loss = closure()
        
        # Base optimizer step
        self.base_optimizer.step()
        self.counter += 1
        
        # Update slow weights every k steps
        if self.counter % self.k == 0:
            for group in self.param_groups:
                for p in group['params']:
                    if p.grad is None:
                        continue
                    
                    param_state = self.state[p]
                    slow_weights = param_state['slow_weights']
                    
                    # Update slow weights: slow = slow + alpha * (fast - slow)
                    # Equivalent to: slow = alpha * fast + (1 - alpha) * slow
                    slow_weights.data.add_(p.data - slow_weights, alpha=self.alpha)
                    
                    # Update fast weights: fast = slow (or keep fast weights as is)
                    # In standard Lookahead, fast weights are not updated here
                    # They continue with their own optimization
        
        return loss
    
# Load model
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    device_map="auto",
    dtype=torch.float32,
    low_cpu_mem_usage=True,
)

# Create Lookahead optimizer
base_optimizer = AdamW(
    model.parameters(), 
    lr=2e-5, 
    weight_decay=0.01,
    eps=1e-8,
    betas=(0.9, 0.999)
)
optimizer = LookaheadOptimizer(base_optimizer, k=5, alpha=0.5)

Loading weights:   0%|          | 0/236 [00:00<?, ?it/s]

In [10]:
# Custom trainer to handle Lookahead properly
class LookaheadTrainer(Trainer):
    def __init__(self, **kwargs):
        super().__init__(**kwargs)
    
    def create_optimizer(self):
        # Skip creating default optimizer since we provide our own
        # But we need to ensure self.optimizer is set
        if self.optimizer is None:
            # If optimizer wasn't provided via optimizers parameter
            # We should create it here, but in our case it's provided
            pass
    
    def create_scheduler(self, num_training_steps, optimizer=None):
        # If no optimizer provided, use self.optimizer
        if optimizer is None:
            optimizer = self.optimizer
        
        # Check if we have a LookaheadOptimizer
        if hasattr(optimizer, 'base_optimizer'):
            # Create scheduler for the base optimizer
            return super().create_scheduler(num_training_steps, optimizer.base_optimizer)
        else:
            # Fall back to regular scheduler creation
            return super().create_scheduler(num_training_steps, optimizer)

data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

monitor = EpochMonitor(model=model)

# Calculate approximate total training steps
num_train_examples = len(dataset_dict["train"])
batch_size = 2
grad_accum = 4
epochs = 3
total_steps = (num_train_examples // (batch_size * grad_accum)) * epochs

training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=epochs,
    per_device_train_batch_size=batch_size,
    per_device_eval_batch_size=2,
    gradient_accumulation_steps=grad_accum,  # Increased for memory efficiency
    learning_rate=2e-5,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_strategy="epoch",
    run_name="gemma-3-270m-qa-lookahead",
    warmup_steps=int(total_steps * 0.1),  # 10% warmup
    lr_scheduler_type="cosine",
    max_grad_norm=1.0,
    gradient_checkpointing=True,  # Enable for memory efficiency
    optim="adamw_torch",  # Use default optimizer (will be overridden)
    dataloader_num_workers=0,
    dataloader_pin_memory=False,
)

trainer = LookaheadTrainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
    optimizers=(optimizer, None),  # Provide custom optimizer
    callbacks = [monitor]
)

total_params = sum(p.numel() for p in model.parameters())
print(f"Total parameters: {total_params:,}")
print(f"Batch size: {training_args.per_device_train_batch_size}")
print(f"Gradient accumulation steps: {training_args.gradient_accumulation_steps}")
print(f"Effective batch size: {training_args.per_device_train_batch_size * training_args.gradient_accumulation_steps}")
print(f"Total training steps: approx. {total_steps}")
print(f"Warmup steps: {training_args.warmup_steps}")
print(f"Lookahead parameters: k={optimizer.k}, alpha={optimizer.alpha}")
print("Starting training with Lookahead Optimization...")

train_result = trainer.train()

trainer.save_model()
tokenizer.save_pretrained(OUTPUT_DIR)

print("Training completed!")

Total parameters: 268,098,176
Batch size: 2
Gradient accumulation steps: 4
Effective batch size: 8
Total training steps: approx. 498
Warmup steps: 49
Lookahead parameters: k=5, alpha=0.5
Starting training with Lookahead Optimization...
Initial Model Memory Footprint:
  Parameters: 268,098,176
  Precision: 4 bytes
  Total Memory: 3.81 GB
    - Parameters: 1.00 GB
    - KV Cache (est): 2.81 GB
  Estimated FLOPs per forward pass (batch=8, seq=512): 2.05 TFLOPS

============================================================
Epoch 0 Summary
============================================================
  Duration (s)         :       111.39
  Tokens Processed     :      171,008
  Throughput (token/s) :         1535
  Training Steps       :          167
  Avg CPU (%)          :         20.2
  Avg Memory (%)       :         11.6
  Total FLOPs          : 85.62 TFLOPS
  TFLOPS (per second)  :         0.77
  FLOPs (per token)    :  0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================
Epoch 1 Summary
============================================================
  Duration (s)         :       111.03
  Tokens Processed     :      171,008
  Throughput (token/s) :         1540
  Training Steps       :          167
  Avg CPU (%)          :         20.1
  Avg Memory (%)       :         11.6
  Total FLOPs          : 85.62 TFLOPS
  TFLOPS (per second)  :         0.77
  FLOPs (per token)    :  0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================
Epoch 2 Summary
============================================================
  Duration (s)         :       111.07
  Tokens Processed     :      171,008
  Throughput (token/s) :         1540
  Training Steps       :          167
  Avg CPU (%)          :         20.5
  Avg Memory (%)       :         11.6
  Total FLOPs          : 85.62 TFLOPS
  TFLOPS (per second)  :         0.77
  FLOPs (per token)    :  0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['lm_head.weight'].

============================================================
TRAINING COMPLETE
============================================================
Total Training Time: 368.12s
Total Epochs: 3
Average Epoch Time: 111.16s
Total Tokens Processed: 513,024
Average Throughput: 1394 tokens/second
Total FLOPs: 256.87 TFLOPS
Average TFLOPS (per second): 0.70
Overall FLOPs (per token): 0.50 GFLOPS

Final Metrics:
Memory Footprint: 3.81 GB
Inference Throughput: 1728 tokens/second
Total Training FLOPs: 85.62 TFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Training completed!

In [11]:
summarize_training_results(trainer, monitor)

====================================================================================================
TRAINING RESULTS SUMMARY TABLE
====================================================================================================
Epoch Training Loss Validation Loss Time (s) Tokens Processed Throughput (token/s) TFLOPS (per second) Avg CPU (%) Avg Memory (%) Training Steps
    0        1.5542          4.5724   111.39          171,008                 1535                0.77        20.2           11.6            167
    1        0.6628          5.5838   111.03          171,008                 1540                0.77        20.1           11.6            167
    2        0.4430          6.1891   111.07          171,008                 1539                0.77        20.5           11.6            167

----------------------------------------------------------------------------------------------------
TRAINING STATISTICS:
----------------------------------------------------------------------------------------------------
Total Training Time:      333.5 s
Average Epoch Time:       111.2 s
Total Tokens Processed:   513,024
Average Throughput:       1538 tokens/second
Average CPU Usage:        20.3%
Average Memory Usage:     11.6%
Total Training FLOPs:     256.87 TFLOPS
Average TFLOPS (per sec): 0.77
Overall FLOPs (per token): 0.50 GFLOPS

====================================================================================================

**Reference**
- [Arxiv:Lookahead Optimizer: k steps forward, 1 step back](https://arxiv.org/abs/1907.08610)
- [Arxiv:Lookahead Path Likelihood Optimization for Diffusion LLMs](https://arxiv.org/abs/2602.03496)
- [APXML:Sophisticated Optimizers Overview](https://apxml.com/courses/advanced-pytorch/chapter-3-optimization-training-strategies/sophisticated-optimizers)
- [OpenReview:Lookahead Routing for Large Language Models](https://openreview.net/forum?id=DRIRD9ELMb)
- [Huggingface:Trainer](https://huggingface.co/docs/transformers/en/main_classes/trainer)
- [APXML:Optimizers (torch.optim)](https://apxml.com/courses/getting-started-with-pytorch/chapter-4-building-models-torch-nn/optimizers-torch-optim)
- [PyTorch:Ltorch.optim](https://docs.pytorch.org/docs/stable/optim.html)

### Enhanced Warmup Strategy

Warmup Strategies are a foundational optimization technique used to stabilize the initial phase of LLM training. Instead of starting training at the full learning rate, a warmup period gradually increases the learning rate from near zero to the target value over a specified number of steps. This prevents the model's weights from being destroyed by the massive, erratic gradients typically seen in the first few iterations when the optimizer's internal "moving averages" (moments) have not yet been established.

**How it Works**

Warmup acts as a "gentle start" for the optimizer. Without it, the large initial updates in a high-capacity model like Gemma can lead to divergence, where the loss becomes infinite or the model's pre-trained knowledge is instantly wiped out.
- Linear Warmup: The most common approach. The learning rate increases at a constant rate (a straight line) from 0 to the maximum value.
- Cosine Warmup: Often paired with a cosine decay, this uses a curved path to reach the peak.
- The "Post-Warmup" Phase: Once the peak is reached, the strategy switches to a decay phase (like Cosine or Linear decay) to slowly lower the learning rate as the model approaches the end of training.

By the time the warmup period ends, the optimizer (like AdamW) has collected enough statistics about the data to make more informed, stable updates.

**Warmup Strategies Implementation**

The script provides a flexible framework to apply several advanced warmup and decay combinations through the EnhancedWarmupTrainer.
- Scheduler Factory: The `EnhancedWarmupScheduler` class acts as a central hub. It maps string names (like `"cosine_with_restarts" or "polynomial"`) to specific mathematical functions provided by the Transformers library.
- Steps Calculation: The code calculates `train_steps` dynamically based on the dataset size, batch size, and epochs. It then sets warmup_steps to 10% of that total (`train_steps * 0.1`).
- Custom Trainer Logic: The `EnhancedWarmupTrainer` overrides the default `create_scheduler` method. It intercepts the `lr_scheduler_type` from the training arguments and passes it to the factory to build the specific curve.
- Hard Restarts: By setting `lr_scheduler_type="cosine_with_restarts"`, the script implements a specialized strategy where the learning rate peaks, decays, and then "jumps" back up to simulate new warmup periods, helping the model escape local minima.

**When to Use It**

Warmup is mandatory for almost all LLM optimization tasks, but specific strategies fit different needs:
- Instruction Fine-Tuning (Linear/Cosine): Standard fine-tuning on a new task should always use a 5% to 10% linear warmup. This protects the pre-trained weights during the initial "shock" of the new data.
- Training from Scratch (Long Warmup): When training a model from random initialization, a very long warmup (up to 10,000 steps) is often used to stabilize the high-variance gradients.
- Complex or Noisy Datasets (Cosine with Restarts): If the dataset contains very diverse information that might lead the model into "traps," using restarts provides multiple mini-warmup phases to help the model find a more global optimum.
- Low Batch Sizes: Smaller batches produce noisier gradients. If the `per_device_train_batch_size` is very low (like 2 in this script), a longer warmup period is essential to prevent the noise from derailing the training early on.

In [ ]:
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, DataCollatorForLanguageModeling, Trainer, TrainingArguments
from datasets import DatasetDict, Dataset

In [12]:
# Configuration
MODEL_NAME = "google/gemma-3-270m"
OUTPUT_DIR = "./gemma-3-270m-finetuned-qa"

# Load model
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    device_map="auto",
    dtype=torch.float32,
    low_cpu_mem_usage=True,
)

# Custom scheduler factory for enhanced warmup strategies
class EnhancedWarmupScheduler:
    @staticmethod
    def get_scheduler(name, optimizer, num_warmup_steps, num_training_steps, **kwargs):
        from transformers.optimization import (
            get_constant_schedule_with_warmup,
            get_cosine_schedule_with_warmup,
            get_cosine_with_hard_restarts_schedule_with_warmup,
            get_linear_schedule_with_warmup,
            get_polynomial_decay_schedule_with_warmup,
        )
        
        schedulers = {
            "constant": get_constant_schedule_with_warmup,
            "cosine": get_cosine_schedule_with_warmup,
            "cosine_with_restarts": get_cosine_with_hard_restarts_schedule_with_warmup,
            "linear": get_linear_schedule_with_warmup,
            "polynomial": get_polynomial_decay_schedule_with_warmup,
        }
        
        if name not in schedulers:
            raise ValueError(f"Unknown scheduler type: {name}")
        
        if name == "cosine_with_restarts":
            return schedulers[name](
                optimizer,
                num_warmup_steps=num_warmup_steps,
                num_training_steps=num_training_steps,
                num_cycles=kwargs.get("num_cycles", 3),
            )
        elif name == "polynomial":
            return schedulers[name](
                optimizer,
                num_warmup_steps=num_warmup_steps,
                num_training_steps=num_training_steps,
                lr_end=kwargs.get("lr_end", 1e-7),
                power=kwargs.get("power", 1.0),
            )
        else:
            return schedulers[name](
                optimizer,
                num_warmup_steps=num_warmup_steps,
                num_training_steps=num_training_steps,
            )

# Custom trainer with enhanced warmup strategies
class EnhancedWarmupTrainer(Trainer):
    def create_scheduler(self, num_training_steps, optimizer=None):
        if optimizer is None:
            optimizer = self.optimizer
        
        # Calculate warmup steps
        warmup_steps = self.args.get_warmup_steps(num_training_steps)
        
        # Use enhanced scheduler factory
        self.lr_scheduler = EnhancedWarmupScheduler.get_scheduler(
            name=self.args.lr_scheduler_type,
            optimizer=optimizer,
            num_warmup_steps=warmup_steps,
            num_training_steps=num_training_steps,
            num_cycles=3,  # For cosine_with_restarts
            lr_end=1e-7,   # For polynomial decay
        )
        
        self._created_lr_scheduler = True
        return self.lr_scheduler

data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

monitor = EpochMonitor(model=model)

# Calculate total training steps for better warmup configuration
train_steps = len(dataset_dict["train"]) // (2 * 4) * 3  # batch_size * grad_accum * epochs

training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=2,
    per_device_eval_batch_size=2,
    gradient_accumulation_steps=4,  # Increased for memory efficiency
    learning_rate=2e-5,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_strategy="epoch",
    run_name="gemma-3-270m-qa-enhanced-warmup",
    warmup_steps=int(train_steps * 0.1),  # 10% warmup
    lr_scheduler_type="cosine_with_restarts",  # Enhanced warmup strategy
    max_grad_norm=1.0,
    gradient_checkpointing=True,  # Memory efficiency
    fp16=False,  # Using float32
    bf16=False,
    dataloader_num_workers=0,
    dataloader_pin_memory=True,
)

trainer = EnhancedWarmupTrainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
    callbacks = [monitor]
)

total_params = sum(p.numel() for p in model.parameters())
trainable_params = total_params
print(f"Total parameters: {total_params:,}")
print(f"Trainable parameters: {trainable_params:,}")
print(f"Batch size: {training_args.per_device_train_batch_size}")
print(f"Effective batch size: {training_args.per_device_train_batch_size * training_args.gradient_accumulation_steps}")
print(f"Total training steps: ~{train_steps}")
print(f"Warmup steps: {training_args.warmup_steps}")
print(f"Warmup percentage: {training_args.warmup_steps/train_steps*100:.1f}%")
print(f"Learning rate scheduler: {training_args.lr_scheduler_type}")
print("Starting training with Enhanced Warmup Strategy...")

train_result = trainer.train()

trainer.save_model()
tokenizer.save_pretrained(OUTPUT_DIR)

print("Training completed!")

Loading weights:   0%|          | 0/236 [00:00<?, ?it/s]

Total parameters: 268,098,176
Trainable parameters: 268,098,176
Batch size: 2
Effective batch size: 8
Total training steps: ~498
Warmup steps: 49
Warmup percentage: 9.8%
Learning rate scheduler: SchedulerType.COSINE_WITH_RESTARTS
Starting training with Enhanced Warmup Strategy...
Initial Model Memory Footprint:
  Parameters: 268,098,176
  Precision: 4 bytes
  Total Memory: 3.81 GB
    - Parameters: 1.00 GB
    - KV Cache (est): 2.81 GB
  Estimated FLOPs per forward pass (batch=8, seq=512): 2.05 TFLOPS

============================================================
Epoch 0 Summary
============================================================
  Duration (s)         :       106.69
  Tokens Processed     :      171,008
  Throughput (token/s) :         1603
  Training Steps       :          167
  Avg CPU (%)          :         18.3
  Avg Memory (%)       :         12.2
  Total FLOPs          : 85.62 TFLOPS
  TFLOPS (per second)  :         0.80
  FLOPs (per token)    :  0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================
Epoch 1 Summary
============================================================
  Duration (s)         :       107.19
  Tokens Processed     :      171,008
  Throughput (token/s) :         1595
  Training Steps       :          167
  Avg CPU (%)          :         20.6
  Avg Memory (%)       :         12.4
  Total FLOPs          : 85.62 TFLOPS
  TFLOPS (per second)  :         0.80
  FLOPs (per token)    :  0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================
Epoch 2 Summary
============================================================
  Duration (s)         :       107.83
  Tokens Processed     :      171,008
  Throughput (token/s) :         1586
  Training Steps       :          167
  Avg CPU (%)          :         21.9
  Avg Memory (%)       :         12.4
  Total FLOPs          : 85.62 TFLOPS
  TFLOPS (per second)  :         0.79
  FLOPs (per token)    :  0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['lm_head.weight'].

============================================================
TRAINING COMPLETE
============================================================
Total Training Time: 352.47s
Total Epochs: 3
Average Epoch Time: 107.24s
Total Tokens Processed: 513,024
Average Throughput: 1456 tokens/second
Total FLOPs: 256.87 TFLOPS
Average TFLOPS (per second): 0.73
Overall FLOPs (per token): 0.50 GFLOPS

Final Metrics:
Memory Footprint: 3.81 GB
Inference Throughput: 1724 tokens/second
Total Training FLOPs: 85.62 TFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Training completed!

In [13]:
summarize_training_results(trainer, monitor)

====================================================================================================
TRAINING RESULTS SUMMARY TABLE
====================================================================================================
Epoch Training Loss Validation Loss Time (s) Tokens Processed Throughput (token/s) TFLOPS (per second) Avg CPU (%) Avg Memory (%) Training Steps
    0        1.7751          4.2707   106.69          171,008                 1602                0.80        18.3           12.2            167
    1        0.7506          5.1268   107.19          171,008                 1595                0.80        20.6           12.4            167
    2        0.5808          5.5118   107.83          171,008                 1585                0.79        21.9           12.4            167

----------------------------------------------------------------------------------------------------
TRAINING STATISTICS:
----------------------------------------------------------------------------------------------------
Total Training Time:      321.7 s
Average Epoch Time:       107.2 s
Total Tokens Processed:   513,024
Average Throughput:       1595 tokens/second
Average CPU Usage:        20.3%
Average Memory Usage:     12.3%
Total Training FLOPs:     256.87 TFLOPS
Average TFLOPS (per sec): 0.80
Overall FLOPs (per token): 0.50 GFLOPS

====================================================================================================

**Reference**
- [ACM:Analyzing & reducing the need for learning rate warmup in GPT training](https://dl.acm.org/doi/10.5555/3737916.3738012)
- [Aclantholog: Warm Up Before You Train: Unlocking General Reasoning in Resource-Constrained Settings](https://aclanthology.org/2025.emnlp-main.727.pdf)
- [Arxiv:Test-Time Warmup for Multimodal Large Language Models](https://arxiv.org/abs/2509.106416)
- [APXML:Learning Rate Scheduling Strategies](https://apxml.com/courses/how-to-build-a-large-language-model/chapter-17-optimization-algorithms-llms/learning-rate-scheduling-strategies)
- [Medium:How to Train Massive Language Models Without Losing Your Mind](https://medium.com/@pacosun/how-to-train-massive-language-models-without-losing-your-mind-333840824114)
- [Machinelearningmastery:How to Speed Up Training Convergence of Language Models](https://machinelearningmastery.com/how-to-speed-up-training-of-language-models/)

### Cosine Annealing with Restarts

Cosine Annealing with Restarts is a sophisticated learning rate scheduling technique that periodically resets the learning rate to a high value after it has decayed following a cosine curve. In LLM optimization, this is often referred to as "Stochastic Gradient Descent with Warm Restarts" (SGDR). The primary goal is to help the model escape "sharp" local minima or saddle points—mathematical traps where the model stops learning but hasn't reached the best possible performance—by injecting a burst of "kinetic energy" via a sudden increase in the learning rate.

**How it Works**

The technique operates in rhythmic cycles:
- The Decay: The learning rate starts at a maximum value and decreases following the half-cycle of a cosine function. This allows the model to settle into a promising area of the loss landscape.
- The Floor: The rate approaches a minimum value ($\eta_{min}$), allowing the model to perform very fine-tuned, precise updates.
- The Restart: Instead of staying low or ending the training, the learning rate "jumps" back up to a high value.
- T_mult (Expansion): Often, each subsequent cycle is made longer than the previous one (controlled by a multiplier). This allows the model to explore broadly early in training and then spend more time converging deeply in the later stages.

By resetting the rate, the model is essentially "kicked" out of its current local minimum. If that minimum was poor, the high learning rate helps the model find a better one. If the minimum was already good, the model will likely gravitate back toward it and settle even more precisely.

**Cosine Annealing with Restarts Implementation**

The script leverages the Hugging Face Trainer's integration with specialized schedulers:

- The Scheduler Type: By setting `lr_scheduler_type="cosine_with_restarts"`, the Trainer initializes a version of the `CosineAnnealingWarmRestarts` logic.
- Cycle Configuration: The `lr_scheduler_kwargs={"num_cycles": 3}` tells the trainer to complete three full "descents" and "restarts" over the course of the total training steps.
- Manual Scheduler Option: The provided `get_cosine_annealing_scheduler` function shows the underlying PyTorch parameters:
    - `T_0`: This defines the number of steps in the very first cycle (set to 10% of total training).
    - `T_mult=2`: This ensures that every new cycle is twice as long as the one before it, giving the model progressively more time to settle.
    - `eta_min=1e-7`: This is the "floor" mentioned earlier, ensuring the learning rate never hits absolute zero, so learning never fully stops.
- Automatic Handling: Because the Trainer manages the step counter, it automatically calculates when to trigger the "restart" based on the global step count.

**When to Use It**

Cosine Annealing with Restarts is particularly useful in these scenarios:
- Non-Convex Loss Landscapes: If the training loss is "bumpy" or plateaus quickly, restarts can force the model to explore alternative mathematical paths that might lead to higher accuracy.
- Long-Duration Training: When training for many epochs, a standard decay might reach zero too early. Restarts keep the model "active" for longer periods.
- Multimodal or Diverse Data: When fine-tuning on a dataset that covers many different topics (e.g., a mix of coding, poetry, and math), the model may get stuck optimizing for one topic. A restart helps it re-adjust to the breadth of the entire dataset.
- Small Batch Training: Smaller batches create "noisy" gradients. Restarts act as a stabilizer, ensuring that even if a few noisy batches lead the model astray, the next high-LR cycle can correct the course.

In [ ]:
import torch
from transformers import AutoTokenizer, AutoModelForCausalLM, DataCollatorForLanguageModeling, Trainer, TrainingArguments
from datasets import DatasetDict, Dataset
from torch.optim.lr_scheduler import CosineAnnealingWarmRestarts

In [16]:
# Configuration
MODEL_NAME = "google/gemma-3-270m"
OUTPUT_DIR = "./gemma-3-270m-finetuned-qa"

# Load model
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    device_map="auto",
    torch_dtype=torch.float32,
    low_cpu_mem_usage=True,
)

# Create custom scheduler
def get_cosine_annealing_scheduler(optimizer, num_training_steps):
    scheduler = CosineAnnealingWarmRestarts(
        optimizer,
        T_0=num_training_steps // 10,
        T_mult=2,
        eta_min=1e-7,
    )
    return scheduler

data_collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

monitor = EpochMonitor(model=model)

training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=2,
    per_device_eval_batch_size=2,
    gradient_accumulation_steps=1,
    learning_rate=2e-5,
    weight_decay=0.01,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_strategy="epoch",
    run_name="gemma-3-270m-qa-cosine-restarts",
    warmup_steps=100,
    lr_scheduler_type="cosine_with_restarts",
    lr_scheduler_kwargs={
        "num_cycles": 3,
    },
    max_grad_norm=1.0,
    gradient_checkpointing=True,
)

trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=data_collator,
    callbacks = [monitor]
)

total_params = sum(p.numel() for p in model.parameters())
print(f"Total parameters: {total_params:,}")
print(f"Batch size: {training_args.per_device_train_batch_size}")
print("Starting training with Cosine Annealing with Restarts...")

train_result = trainer.train()

trainer.save_model()
tokenizer.save_pretrained(OUTPUT_DIR)

print("Training completed!")

Loading weights:   0%|          | 0/236 [00:00<?, ?it/s]

Total parameters: 268,098,176
Batch size: 2
Starting training with Cosine Annealing with Restarts...
Initial Model Memory Footprint:
  Parameters: 268,098,176
  Precision: 4 bytes
  Total Memory: 3.81 GB
    - Parameters: 1.00 GB
    - KV Cache (est): 2.81 GB
  Estimated FLOPs per forward pass (batch=8, seq=512): 2.05 TFLOPS

============================================================
Epoch 0 Summary
============================================================
  Duration (s)         :        126.98
  Tokens Processed     :       681,984
  Throughput (token/s) :          5371
  Training Steps       :           666
  Avg CPU (%)          :          20.2
  Avg Memory (%)       :          12.9
  Total FLOPs          : 341.47 TFLOPS
  TFLOPS (per second)  :          2.69
  FLOPs (per token)    :   0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================
Epoch 1 Summary
============================================================
  Duration (s)         :        127.45
  Tokens Processed     :       681,984
  Throughput (token/s) :          5351
  Training Steps       :           666
  Avg CPU (%)          :          22.0
  Avg Memory (%)       :          13.0
  Total FLOPs          : 341.47 TFLOPS
  TFLOPS (per second)  :          2.68
  FLOPs (per token)    :   0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================
Epoch 2 Summary
============================================================
  Duration (s)         :        127.62
  Tokens Processed     :       681,984
  Throughput (token/s) :          5344
  Training Steps       :           666
  Avg CPU (%)          :          21.5
  Avg Memory (%)       :          13.0
  Total FLOPs          : 341.47 TFLOPS
  TFLOPS (per second)  :          2.68
  FLOPs (per token)    :   0.50 GFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

There were missing keys in the checkpoint model loaded: ['lm_head.weight'].

============================================================
TRAINING COMPLETE
============================================================
Total Training Time: 411.01s
Total Epochs: 3
Average Epoch Time: 127.35s
Total Tokens Processed: 2,045,952
Average Throughput: 4978 tokens/second
Total FLOPs: 1024.40 TFLOPS
Average TFLOPS (per second): 2.49
Overall FLOPs (per token): 0.50 GFLOPS

Final Metrics:
Memory Footprint: 3.81 GB
Inference Throughput: 7013 tokens/second
Total Training FLOPs: 341.47 TFLOPS

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Training completed!

In [17]:
summarize_training_results(trainer, monitor)

====================================================================================================
TRAINING RESULTS SUMMARY TABLE
====================================================================================================
Epoch Training Loss Validation Loss Time (s) Tokens Processed Throughput (token/s) TFLOPS (per second) Avg CPU (%) Avg Memory (%) Training Steps
    0        1.5045          5.3294   126.98          681,984                 5370                2.69        20.2           12.9            666
    1        0.7143          5.7516   127.45          681,984                 5350                2.68        22.0           13.0            666
    2        0.5468          6.3158   127.62          681,984                 5343                2.68        21.5           13.0            666

----------------------------------------------------------------------------------------------------
TRAINING STATISTICS:
----------------------------------------------------------------------------------------------------
Total Training Time:      382.1 s
Average Epoch Time:       127.4 s
Total Tokens Processed:   2,045,952
Average Throughput:       5355 tokens/second
Average CPU Usage:        21.2%
Average Memory Usage:     13.0%
Total Training FLOPs:     1024.40 TFLOPS
Average TFLOPS (per sec): 2.68
Overall FLOPs (per token): 0.50 GFLOPS

====================================================================================================

**Reference**
- [Arxiv:SGDR: Stochastic Gradient Descent with Warm Restarts](https://arxiv.org/abs/1608.03983)
- [PyTorch:CosineAnnealingWarmRestarts](https://docs.pytorch.org/docs/stable/generated/torch.optim.lr_scheduler.CosineAnnealingWarmRestarts.html)
- [Medium:Cosine Learning Rate Schedulers in PyTorch](https://medium.com/@utkrisht14/cosine-learning-rate-schedulers-in-pytorch-486d8717d541)

# FRAMEWORK-SPECIFIC OPTIMIZATIONS

## PyTorch Optimization

PyTorch Optimizations are a suite of advanced features designed to maximize the computational efficiency and memory utilization of your hardware. While standard training relies on the Python interpreter to execute operations one by one, these optimizations bridge the gap between high-level Python code and the low-level machine code required for peak performance.

**Core Techniques**

**1. `torch.compile`**

Introduced in PyTorch 2.0, `torch.compile` is a "Just-In-Time" (JIT) compiler. It uses a technology called TorchDynamo to intercept PyTorch code and convert it into optimized kernels (via Triton) that are specialized for your specific GPU architecture.
- Graph Capture: Instead of running operations individually, it looks at the whole "sequence" of math (the graph).
- Kernel Fusion: It combines multiple operations (e.g., an Activation followed by a LayerNorm) into a single GPU "kernel," reducing the time the GPU spends reading and writing to memory.
- Result: Massive speedups (often 15% to 40%) without changing your model's logic.

**2. `FSDP` (Fully Sharded Data Parallel)**

FSDP is the industry-standard method for training "mega-models" that are physically too large to fit into a single GPU's memory.
- Sharding: Standard Data Parallel (DP) copies the whole model to every GPU. FSDP instead "shards" (splits) the model parameters, gradients, and optimizer states across all available GPUs.
- Communication: When a specific layer needs to perform a calculation, FSDP temporarily fetches the required shards from other GPUs, does the math, and then discards them to free up memory.
- Scaling: This allows you to train models with hundreds of billions of parameters using a cluster of smaller GPUs.

**Reference**
- [PyTorch:torchtune: Easily fine-tune LLMs using PyTorch](https://pytorch.org/blog/torchtune-fine-tune-llms/)
- [PyTorch:Finetune LLMs on your own consumer hardware using tools from PyTorch and Hugging Face ecosystem](https://pytorch.org/blog/finetune-llms/)
- [Huggingface:Fine-Tuning Your First Large Language Model (LLM) with PyTorch and Hugging Face](https://huggingface.co/blog/dvgodoy/fine-tuning-llm-hugging-face)
- [Medium:Fine-Tuning Large Language Model with Hugging Face & PyTorch](https://tuanatran.medium.com/fine-tuning-large-language-model-with-hugging-face-pytorch-adce80dce2ad)

### torch.compile Features

`torch.compile` is a high-performance feature introduced in PyTorch 2.x that serves as a compiler for deep learning models. In the context of LLMs, it transforms the flexible, eager-mode Python execution into a highly optimized computational graph. This minimizes the overhead of the Python interpreter and allows the hardware to execute fused mathematical operations at much higher speeds.

**How it Works**

The optimization process relies on three primary internal components:
- `TorchDynamo` (Graph Capture): It intercepts Python execution and uses "Python Frame Evaluation" to capture the model's logic into a temporary graph. If it encounters code it cannot compile (like complex third-party library calls), it safely falls back to standard Python execution for those specific parts.
- `AOTAutograd`: This generates the backward pass of the model ahead of time. By analyzing the forward graph, it pre-calculates the most efficient way to compute gradients.
- `TorchInductor` (The Backend): This is the compiler that generates the final machine code. For NVIDIA GPUs, it utilizes OpenAI Triton to generate specialized CUDA kernels that "fuse" operations—combining multiple steps like linear layers and activation functions into a single GPU task.

**`torch.compile` Features Implementation**

The script demonstrates several advanced optimization features:
- Custom Backend Selection: The line `model = torch.compile(..., backend="inductor")` explicitly chooses the "Inductor" engine. This is the most popular choice as it produces highly efficient Triton kernels for GPUs.
- Graph Optimization & Fusion: By wrapping the model, the code enables "Kernel Fusion." This combines multiple layers (like a Linear layer and a ReLU activation) into a single GPU call, drastically reducing the number of times data is read from or written to memory.
- CUDA Graph Integration: In the training loop, `torch.compiler.cudagraph_mark_step_begin()` is used. This works with the compiler to "record" the entire step and replay it on the GPU, which can nearly eliminate CPU-to-GPU communication delays.
- Performance Tracking: The script includes a `monitor_resources` function and `estimate_model_flops` to measure the TFLOPS (Tera-FLOPS). This allows the user to see exactly how much speed is gained after the initial compilation pass is finished.
- Mixed Precision Support: Using `torch.amp.autocast` alongside compilation allows the compiler to generate kernels optimized specifically for `bfloat16`, which is much faster on modern hardware like NVIDIA A100s or H100s.

**When to Use It**

`torch.compile` is most effective in these conditions:
- Production Fine-tuning: When you have a large dataset and want to minimize the total cost and time of training.
- Modern GPU Hardware: You will see the most dramatic results on NVIDIA Ampere (A100/30-series) or Hopper (H100/40-series) architectures where Tensor Cores can be fully utilized by the generated Triton kernels.
- Small Batch Sizes: Using `mode="reduce-overhead"` (mentioned in your previous version) is perfect for small batches where the time taken to launch kernels in Python is longer than the actual math.
- Static Workloads: When you use a fixed `MAX_LENGTH` (like 128 in the code), the compiler can create a "perfect" graph that doesn't need to change, providing the maximum possible speedup.

In [ ]:
%%capture
!pip install GPUtil
import torch
import time
from torch.utils.data import DataLoader
from transformers import AutoTokenizer, AutoModelForCausalLM, DataCollatorForLanguageModeling
from datasets import Dataset
import psutil
import GPUtil

In [19]:
# Global variables for performance tracking
_training_start_time = None
_total_tokens_processed = 0
_total_flops = 0
_flops_per_step = None

def monitor_resources():
    """Monitor CPU and GPU memory usage, plus compute TFLOPS and FLOPs per token"""
    global _total_tokens_processed, _total_flops, _training_start_time
    
    cpu_mem = psutil.virtual_memory().percent
    gpus = GPUtil.getGPUs()
    gpu_info = []
    for gpu in gpus:
        gpu_used = gpu.memoryUsed/1024
        gpu_total = gpu.memoryTotal/1024
        gpu_info.append(f"GPU {gpu.id}: {gpu_used:.2f}/{gpu_total:.2f} GB ({gpu.load*100:.1f}%)")
    
    # Calculate performance metrics if we have tracking data
    performance_info = []
    if _training_start_time is not None and _total_tokens_processed > 0 and _total_flops > 0:
        elapsed_time = time.time() - _training_start_time
        if elapsed_time > 0:
            # Calculate TFLOPS (Tera FLoating Point OPerations per Second)
            tflops = _total_flops / (elapsed_time * 1e12)
            
            # Calculate FLOPs per token
            flops_per_token = _total_flops / _total_tokens_processed
            
            performance_info = [
                f"TFLOPS: {tflops:.2f}",
                f"FLOPs/token: {flops_per_token/1e9:.2f}B"
            ]
    
    # Combine all metrics
    all_info = [f"CPU: {cpu_mem}%"] + gpu_info + performance_info
    return " | ".join(all_info)

def estimate_model_flops(model, batch_size, seq_length):
    """Estimate FLOPs per forward pass for the model"""
    # Get model configuration
    hidden_size = model.config.hidden_size
    num_layers = model.config.num_hidden_layers
    intermediate_size = model.config.intermediate_size
    num_heads = model.config.num_attention_heads
    vocab_size = model.config.vocab_size
    
    # FLOPs per token per layer approximation:
    # Attention: QKV projections + attention computation + output projection
    # QKV projections: 3 * hidden_size * hidden_size
    # Attention computation: seq_len * hidden_size (approx)
    # Output projection: hidden_size * hidden_size
    attention_flops_per_layer = 4 * hidden_size * hidden_size * seq_length
    
    # FFN FLOPs (assuming GLU variant)
    ffn_flops_per_layer = 2 * hidden_size * intermediate_size * seq_length * 2
    
    # Total FLOPs per layer
    flops_per_layer = attention_flops_per_layer + ffn_flops_per_layer
    
    # Total FLOPs for all layers
    total_flops = flops_per_layer * num_layers
    
    # Add embedding FLOPs (input + output)
    embedding_flops = 2 * batch_size * seq_length * hidden_size * vocab_size
    
    return total_flops + embedding_flops

MODEL_NAME = "google/gemma-3-270m"
OUTPUT_DIR = "./gemma-3-270m-finetuned-qa"
MAX_LENGTH = 128

device = torch.device("cuda" if torch.cuda.is_available() else "cpu")
dtype = torch.bfloat16 if torch.cuda.is_bf16_supported() else torch.float32

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
tokenizer.pad_token = tokenizer.eos_token

def tokenize_examples(df):
    texts = [
        f"<bos>Question: {row['question_title']}\n{row['question_body']}\nAnswer: {row['answer']}<eos>"
        for row in df.iter_rows(named=True)
    ]
    tokenized = tokenizer(
        texts,
        truncation=True,
        max_length=MAX_LENGTH,
        padding="max_length",
        return_tensors="pt"
    )
    tokenized["labels"] = tokenized["input_ids"].clone()
    return tokenized

train_tokenized = tokenize_examples(train_data)
val_tokenized = tokenize_examples(val_data)

train_dataset = Dataset.from_dict({
    "input_ids": train_tokenized["input_ids"],
    "attention_mask": train_tokenized["attention_mask"],
    "labels": train_tokenized["labels"]
})

val_dataset = Dataset.from_dict({
    "input_ids": val_tokenized["input_ids"],
    "attention_mask": val_tokenized["attention_mask"],
    "labels": val_tokenized["labels"]
})

collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

batch_size = 4
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True,
                          collate_fn=collator, pin_memory=True)
val_loader = DataLoader(val_dataset, batch_size=batch_size,
                        collate_fn=collator, pin_memory=True)

print(f"Loading {MODEL_NAME}...")
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    torch_dtype=dtype,
    low_cpu_mem_usage=True,
)

# Pre-calculate FLOPs per step
_flops_per_step = estimate_model_flops(model, batch_size, MAX_LENGTH)
print(f"Estimated FLOPs per forward pass: {_flops_per_step/1e9:.2f}B")

# Disable gradient checkpointing with torch.compile to avoid CUDA Graph issues
# model.gradient_checkpointing_enable()  # Disabled for torch.compile
model.to(device)

print("Compiling model...")
model = torch.compile(
    model,
    mode="default",  # Changed from "reduce-overhead" to avoid CUDA Graph issues
    fullgraph=False,
    dynamic=False,
    backend="inductor"
)

optimizer = torch.optim.AdamW(model.parameters(), lr=2e-5, weight_decay=0.01, fused=True)

total_steps = len(train_loader) * 3
warmup_steps = int(total_steps * 0.1)

def get_lr(step):
    if step < warmup_steps:
        return 2e-5 * (step + 1) / warmup_steps
    progress = (step - warmup_steps) / max(1, total_steps - warmup_steps)
    return 2e-5 * 0.5 * (1.0 + torch.cos(torch.pi * torch.tensor(progress)).item())

print(f"Total parameters: {sum(p.numel() for p in model.parameters()):,}")
print("Starting training with torch.compile")

# Initialize performance tracking
_training_start_time = time.time()
_total_tokens_processed = 0
_total_flops = 0

print(f"Resource status: {monitor_resources()}")

model.train()
global_step = 0
accum_loss = 0.0
accumulation_steps = 4

for epoch in range(3):
    print(f"\nEpoch {epoch+1}/3 - {monitor_resources()}")
    
    for batch in train_loader:
        global_step += 1
        batch = {k: v.to(device) for k, v in batch.items()}
        
        # Track tokens for FLOPs calculation
        batch_tokens = batch["input_ids"].numel()
        _total_tokens_processed += batch_tokens
        
        # Track FLOPs (forward + backward)
        _total_flops += _flops_per_step  # Forward pass
        _total_flops += 2 * _flops_per_step  # Backward pass (approx 2x forward)
        
        # Mark CUDA graph step to prevent overwriting issues
        if torch.cuda.is_available():
            torch.compiler.cudagraph_mark_step_begin()
        
        with torch.amp.autocast(device_type="cuda", dtype=dtype):
            outputs = model(**batch)
            loss = outputs.loss / accumulation_steps
        
        loss.backward()
        accum_loss += loss.item() * accumulation_steps
        
        if global_step % accumulation_steps == 0:
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            lr = get_lr(global_step)
            for param_group in optimizer.param_groups:
                param_group["lr"] = lr
            optimizer.step()
            optimizer.zero_grad(set_to_none=True)
            
            if global_step % 50 == 0:
                print(f"epoch {epoch+1:2d} | step {global_step:5d} | loss {accum_loss/accumulation_steps:.4f} | lr {lr:.2e}")
                # Also show performance metrics at the same interval
                print(f"  {monitor_resources()}")
            
            accum_loss = 0.0
    
    model.eval()
    val_loss = 0.0
    with torch.no_grad():
        for batch in val_loader:
            batch = {k: v.to(device) for k, v in batch.items()}
            
            # Track validation tokens for consistent metrics
            val_tokens = batch["input_ids"].numel()
            _total_tokens_processed += val_tokens
            _total_flops += _flops_per_step  # Forward pass only for validation
            
            # Mark CUDA graph step for validation
            if torch.cuda.is_available():
                torch.compiler.cudagraph_mark_step_begin()
            
            with torch.amp.autocast(device_type="cuda", dtype=dtype):
                outputs = model(**batch)
            val_loss += outputs.loss.item()
    
    print(f"Epoch {epoch+1} validation loss: {val_loss / len(val_loader):.4f} - {monitor_resources()}")
    model.train()

model.save_pretrained(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)
print("Training completed")
print(f"Final resource status: {monitor_resources()}")

Loading google/gemma-3-270m...

Loading weights:   0%|          | 0/236 [00:00<?, ?it/s]

Estimated FLOPs per forward pass: 187.65B
Compiling model...
Total parameters: 268,098,176
Starting training with torch.compile
Resource status: CPU: 14.1% | GPU 0: 12.93/15.99 GB (0.0%)

Epoch 1/3 - CPU: 14.2% | GPU 0: 12.93/15.99 GB (0.0%)

/usr/local/lib/python3.11/dist-packages/torch/_inductor/compile_fx.py:321: UserWarning: TensorFloat32 tensor cores for float32 matrix multiplication available but not enabled. Consider setting `torch.set_float32_matmul_precision('high')` for better performance.
  warnings.warn(
W0214 13:21:06.698000 1670 torch/_inductor/utils.py:1679] [0/0] Not enough SMs to use max_autotune_gemm mode

epoch  1 | step   100 | loss 2.8362 | lr 2.00e-05
  CPU: 16.0% | GPU 0: 13.70/15.99 GB (88.0%) | TFLOPS: 0.96 | FLOPs/token: 1.10B
epoch  1 | step   200 | loss 2.6415 | lr 1.94e-05
  CPU: 16.0% | GPU 0: 13.70/15.99 GB (88.0%) | TFLOPS: 1.76 | FLOPs/token: 1.10B
epoch  1 | step   300 | loss 2.1262 | lr 1.76e-05
  CPU: 16.0% | GPU 0: 13.70/15.99 GB (89.0%) | TFLOPS: 2.44 | FLOPs/token: 1.10B
Epoch 1 validation loss: 3.0927 - CPU: 16.4% | GPU 0: 13.71/15.99 GB (20.0%) | TFLOPS: 1.22 | FLOPs/token: 0.97B

Epoch 2/3 - CPU: 16.4% | GPU 0: 13.71/15.99 GB (20.0%) | TFLOPS: 1.22 | FLOPs/token: 0.97B
epoch  2 | step   400 | loss 2.0152 | lr 1.50e-05
  CPU: 16.4% | GPU 0: 13.71/15.99 GB (87.0%) | TFLOPS: 1.42 | FLOPs/token: 0.99B
epoch  2 | step   500 | loss 1.9540 | lr 1.17e-05
  CPU: 16.4% | GPU 0: 13.71/15.99 GB (92.0%) | TFLOPS: 1.71 | FLOPs/token: 1.01B
epoch  2 | step   600 | loss 1.7210 | lr 8.23e-06
  CPU: 16.5% | GPU 0: 13.71/15.99 GB (90.0%) | TFLOPS: 1.97 | FLOPs/token: 1.02B
Epoch 2 validation loss: 3.3050 - CPU: 16.5% | GPU 0: 13.71/15.99 GB (66.0%) | TFLOPS: 2.20 | FLOPs/token: 0.97B

Epoch 3/3 - CPU: 16.5% | GPU 0: 13.71/15.99 GB (66.0%) | TFLOPS: 2.20 | FLOPs/token: 0.97B
epoch  3 | step   700 | loss 1.9559 | lr 4.97e-06
  CPU: 16.4% | GPU 0: 13.71/15.99 GB (92.0%) | TFLOPS: 2.29 | FLOPs/token: 0.98B
epoch  3 | step   800 | loss 1.8959 | lr 2.32e-06
  CPU: 16.5% | GPU 0: 13.71/15.99 GB (92.0%) | TFLOPS: 2.52 | FLOPs/token: 0.99B
epoch  3 | step   900 | loss 1.5299 | lr 5.91e-07
  CPU: 16.5% | GPU 0: 13.71/15.99 GB (91.0%) | TFLOPS: 2.74 | FLOPs/token: 1.00B
Epoch 3 validation loss: 3.3270 - CPU: 16.4% | GPU 0: 13.71/15.99 GB (60.0%) | TFLOPS: 3.00 | FLOPs/token: 0.97B

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

Training completed
Final resource status: CPU: 16.9% | GPU 0: 13.71/15.99 GB (0.0%) | TFLOPS: 2.98 | FLOPs/token: 0.97B

**Reference**
- [PyTorch:Datasets & DataLoaders](https://docs.pytorch.org/tutorials/beginner/basics/data_tutorial.html)
- [PyTorch:Introduction to torch.compile](https://docs.pytorch.org/tutorials/intermediate/torch_compile_tutorial.html)
- [PyTorch:Compiling LLM models from Huggingface](https://docs.pytorch.org/TensorRT/tutorials/compile_hf_models.html)
- [PyTorch:Peak Performance, Minimized Memory: Optimizing torchtune’s performance with torch.compile & Liger Kernel](https://pytorch.org/blog/peak-performance-minimized-memory/)

### FSDP (Fully Sharded Data Parallel)

Fully Sharded Data Parallel (FSDP) is a type of data-parallel training where the model's parameters, gradients, and optimizer states are sharded (split) across all available GPUs. In standard data parallelism, every GPU keeps a full copy of the model, which limits the model size to what can fit on a single card. FSDP breaks this barrier, allowing the training of massive models by ensuring that no single GPU needs to hold the entire weight set at once.

**How it Works**

FSDP follows a "ZeRO-3" style approach to memory management. It decomposes the model training into a series of steps that minimize memory redundancy:
- Sharding: Before training, the model is partitioned. If there are 4 GPUs, each GPU only stores 25% of the parameters, 25% of the gradients, and 25% of the optimizer states (like the Adam "moments").
- All-Gather (Forward Pass): When a specific layer needs to perform a calculation, FSDP triggers an "All-Gather" operation to collect the missing pieces of that layer from other GPUs. Once the math is done, the GPU discards the non-local pieces to free memory.
- Reduce-Scatter (Backward Pass): During gradient calculation, the gradients are reduced (averaged) across GPUs, and each GPU only keeps the piece of the gradient that corresponds to its local parameter shard.
- CPU Offloading (Optional): If the GPU memory is still too full, FSDP can move the parameter shards and optimizer calculations to the CPU, using the GPU only for the high-speed forward and backward math.

**FSDP Implementation**

The script sets up a specialized environment to handle the sharding of the Gemma-3-270m model:
- Auto-Wrap Policy: The transformer_auto_wrap_policy is defined with `GemmaDecoderLayer`. This tells FSDP to treat each individual transformer layer as a separate unit for sharding. Instead of sharding the whole model as one giant block, it shards layer-by-layer, which is much more efficient for memory recycling.
- Sharding Strategy: By setting `sharding_strategy=FULL_SHARD`, the code ensures that parameters, gradients, and optimizer states are all distributed across the world size.
- Mixed Precision: The `MixedPrecision` configuration ensures that while sharded parameters are stored in `bfloat16 or float16`, the "communication" between GPUs and the accumulation of gradients also happen in that lower precision to save bandwidth and memory.
- Performance Monitoring: The `estimate_model_flops and monitor_resources` functions work together to calculate TFLOPS (Tera-FLOPS). This is crucial in FSDP because the "communication overhead" (time spent moving shards between GPUs) can sometimes slow down training; monitoring TFLOPS helps determine if the sharding is efficient.
- Unwrapping for Saving: Because the model is sharded, a standard `save_pretrained` would only save a fraction of the model. The code checks `if isinstance(model, FullyShardedDataParallel)` to properly unwrap the model and consolidate the shards before saving the final fine-tuned version.

**When to Use It**

FSDP is the preferred optimization strategy in the following scenarios:
- Model Size Exceeds Single GPU VRAM: If a model (or its optimizer states) is too large for one card, FSDP is the primary solution to make training possible.
- Large-Scale Multi-GPU Clusters: When training on 8, 16, or hundreds of GPUs, FSDP scales more efficiently than standard Data Parallelism because it reduces the memory footprint on every single node.
- Fine-Tuning with Large Batch Sizes: Large batches improve training stability but consume massive amounts of activation memory. FSDP, especially when combined with the `gradient_checkpointing_enable()` seen in the code, allows for much larger batches.
- Limited Hardware Resources: If you have multiple consumer-grade GPUs (like two RTX 3090s) rather than one high-end enterprise GPU (like an H100), FSDP lets you "pool" their memory to act as one large virtual GPU.

In [ ]:
import torch
import time
from torch.distributed.fsdp import FullyShardedDataParallel as FSDP
from torch.distributed.fsdp.wrap import transformer_auto_wrap_policy
from torch.utils.data import DataLoader
from transformers import AutoTokenizer, AutoModelForCausalLM, DataCollatorForLanguageModeling
from transformers.models.gemma.modeling_gemma import GemmaDecoderLayer
from datasets import Dataset
import psutil
import GPUtil
import numpy as np
from functools import partial

In [20]:
def monitor_resources(start_time=None, step_tokens=None, accumulated_flops=None):
    """Monitor CPU and GPU memory usage, plus compute TFLOPS and FLOPs per token"""
    
    # Memory monitoring
    cpu_mem = psutil.virtual_memory().percent
    gpus = GPUtil.getGPUs()
    gpu_info = []
    for gpu in gpus:
        gpu_used = gpu.memoryUsed/1024
        gpu_total = gpu.memoryTotal/1024
        gpu_info.append(f"GPU {gpu.id}: {gpu_used:.2f}/{gpu_total:.2f} GB ({gpu.load*100:.1f}%)")
    
    # Compute performance metrics if time and token info provided
    performance_info = []
    if start_time is not None and step_tokens is not None and accumulated_flops is not None:
        elapsed_time = time.time() - start_time
        if elapsed_time > 0 and step_tokens > 0:
            # Calculate TFLOPS (Tera FLoating Point OPerations per Second)
            tflops = accumulated_flops / (elapsed_time * 1e12)
            
            # Calculate FLOPs per token
            flops_per_token = accumulated_flops / step_tokens
            
            performance_info = [
                f"TFLOPS: {tflops:.2f}",
                f"FLOPs/token: {flops_per_token/1e9:.2f}B"
            ]
    
    # Combine all metrics
    metrics = [f"CPU: {cpu_mem}%"] + gpu_info + performance_info
    return " | ".join(metrics)

def estimate_model_flops(model, batch_size, seq_length, vocab_size):
    """
    Estimate FLOPs per forward pass for a transformer model
    Based on approximate formula: ~6 * params * tokens per layer * num_layers
    """
    # Get model configuration
    hidden_size = model.config.hidden_size
    num_layers = model.config.num_hidden_layers
    intermediate_size = model.config.intermediate_size
    num_heads = model.config.num_attention_heads
    head_dim = hidden_size // num_heads
    
    # FLOPs per token per layer approximation:
    # Attention: 4 * batch * seq_len * hidden_size^2 (QKV projections + output)
    # FFN: 2 * batch * seq_len * hidden_size * intermediate_size * 2 (gate and up projections)
    
    # Attention FLOPs
    qkv_flops = 3 * batch_size * seq_length * hidden_size * hidden_size
    attn_out_flops = batch_size * seq_length * hidden_size * hidden_size
    attention_flops = qkv_flops + attn_out_flops
    
    # Add attention softmax and scaling (rough approximation)
    attention_flops += batch_size * num_heads * seq_length * seq_length * 2
    
    # FFN FLOPs (assuming GLU variant like in Gemma)
    ffn_flops = 2 * batch_size * seq_length * hidden_size * intermediate_size * 2
    
    # Layer norms and other operations (rough approximation)
    other_flops = batch_size * seq_length * hidden_size * 10
    
    # Total FLOPs per layer
    flops_per_layer = attention_flops + ffn_flops + other_flops
    
    # Total FLOPs for all layers
    total_flops = flops_per_layer * num_layers
    
    # Add embedding FLOPs
    embedding_flops = batch_size * seq_length * hidden_size * 2  # Input and output embeddings
    total_flops += embedding_flops
    
    return total_flops

# Check if process group is already initialized
if not torch.distributed.is_initialized():
    torch.distributed.init_process_group(backend="nccl", init_method="tcp://localhost:23456", rank=0, world_size=1)
torch.cuda.set_device(0)

device = torch.device("cuda", 0)
dtype = torch.bfloat16 if torch.cuda.is_bf16_supported() else torch.float16

MODEL_NAME = "google/gemma-3-270m"
OUTPUT_DIR = "./gemma-3-270m-finetuned-qa-fsdp"
MAX_LENGTH = 128

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
tokenizer.pad_token = tokenizer.eos_token

def tokenize_examples(df):
    texts = [
        f"<bos>Question: {row['question_title']}\n{row['question_body']}\nAnswer: {row['answer']}<eos>"
        for row in df.iter_rows(named=True)
    ]
    tokenized = tokenizer(
        texts,
        truncation=True,
        max_length=MAX_LENGTH,
        padding="max_length",
        return_tensors="pt"
    )
    tokenized["labels"] = tokenized["input_ids"].clone()
    return tokenized

# Note: train_data and val_data need to be defined before this point
train_tokenized = tokenize_examples(train_data)
val_tokenized = tokenize_examples(val_data)

train_dataset = Dataset.from_dict({
    "input_ids": train_tokenized["input_ids"],
    "attention_mask": train_tokenized["attention_mask"],
    "labels": train_tokenized["labels"]
})

val_dataset = Dataset.from_dict({
    "input_ids": val_tokenized["input_ids"],
    "attention_mask": val_tokenized["attention_mask"],
    "labels": val_tokenized["labels"]
})

collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

batch_size = 4
train_loader = DataLoader(train_dataset, batch_size=batch_size, shuffle=True,
                          collate_fn=collator, pin_memory=True)
val_loader = DataLoader(val_dataset, batch_size=batch_size,
                        collate_fn=collator, pin_memory=True)

print(f"Loading {MODEL_NAME}...")
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    torch_dtype=dtype,
    low_cpu_mem_usage=True,
)

# Pre-calculate FLOPs per forward pass for performance monitoring
vocab_size = model.config.vocab_size
flops_per_forward = estimate_model_flops(model, batch_size, MAX_LENGTH, vocab_size)
print(f"Estimated FLOPs per forward pass: {flops_per_forward/1e9:.2f}B")

model.gradient_checkpointing_enable()

# Create the auto-wrap policy function
auto_wrap_policy = partial(
    transformer_auto_wrap_policy,
    transformer_layer_cls={GemmaDecoderLayer}
)

model = FSDP(
    model,
    auto_wrap_policy=auto_wrap_policy,
    device_id=torch.cuda.current_device(),
    mixed_precision=torch.distributed.fsdp.MixedPrecision(
        param_dtype=dtype,
        reduce_dtype=dtype,
        buffer_dtype=dtype,
    ),
    sharding_strategy=torch.distributed.fsdp.ShardingStrategy.FULL_SHARD,
    use_orig_params=True,
    limit_all_gathers=True,
)

optimizer = torch.optim.AdamW(model.parameters(), lr=2e-5, weight_decay=0.01, fused=True)

total_steps = len(train_loader) * 3
warmup_steps = int(total_steps * 0.1)

def get_lr(step):
    if step < warmup_steps:
        return 2e-5 * (step + 1) / warmup_steps
    progress = (step - warmup_steps) / max(1, total_steps - warmup_steps)
    return 2e-5 * 0.5 * (1.0 + torch.cos(torch.pi * torch.tensor(progress)).item())

print(f"Total parameters: {sum(p.numel() for p in model.parameters()):,}")
print("Starting FSDP training (single GPU mode)")
print(f"Resource status: {monitor_resources()}")

model.train()
global_step = 0
accum_loss = 0.0
accumulation_steps = 4

# Performance tracking variables
training_start_time = time.time()
total_tokens_processed = 0
total_flops_accumulated = 0

for epoch in range(3):
    print(f"\nEpoch {epoch+1}/3 - {monitor_resources()}")
    
    for batch_idx, batch in enumerate(train_loader):
        global_step += 1
        
        batch = {k: v.to(device) for k, v in batch.items()}
        
        # Track tokens in this batch for FLOPs calculation
        batch_tokens = batch["input_ids"].numel()  # Total tokens in batch
        total_tokens_processed += batch_tokens
        
        # Track FLOPs for this forward pass
        total_flops_accumulated += flops_per_forward  # Forward pass
        # Backward pass is roughly 2x forward pass
        total_flops_accumulated += 2 * flops_per_forward  # Backward pass
        
        with torch.amp.autocast(device_type="cuda", dtype=dtype):
            outputs = model(**batch)
            loss = outputs.loss / accumulation_steps
        
        loss.backward()
        accum_loss += loss.item() * accumulation_steps
        
        if (batch_idx + 1) % accumulation_steps == 0:
            step_start_time = time.time()
            
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            lr = get_lr(global_step)
            for param_group in optimizer.param_groups:
                param_group["lr"] = lr
            optimizer.step()
            optimizer.zero_grad(set_to_none=True)
            
            # Calculate performance metrics for this step
            step_end_time = time.time()
            step_time = step_end_time - step_start_time
        
    
    # Validation at the end of each epoch
    model.eval()
    val_loss = 0.0
    val_start_time = time.time()
    val_tokens = 0
    val_flops = 0
    
    with torch.no_grad():
        for batch in val_loader:
            batch = {k: v.to(device) for k, v in batch.items()}
            val_tokens += batch["input_ids"].numel()
            val_flops += flops_per_forward  # Forward pass only for validation
            
            with torch.amp.autocast(device_type="cuda", dtype=dtype):
                outputs = model(**batch)
            val_loss += outputs.loss.item()
    
    avg_val_loss = val_loss / len(val_loader)
    val_time = time.time() - val_start_time
    val_tflops = val_flops / (val_time * 1e12) if val_time > 0 else 0
    val_flops_per_token = val_flops / val_tokens if val_tokens > 0 else 0
    
    print(f"Epoch {epoch+1} validation loss: {avg_val_loss:.4f} | "
          f"Val TFLOPS: {val_tflops:.2f} | Val FLOPs/token: {val_flops_per_token/1e9:.2f}B")
    print(f"  {monitor_resources()}")
    model.train()

# Save the model (unwrapping FSDP)
from torch.distributed.fsdp import FullyShardedDataParallel
if isinstance(model, FullyShardedDataParallel):
    model.module.save_pretrained(OUTPUT_DIR)
else:
    model.save_pretrained(OUTPUT_DIR)

tokenizer.save_pretrained(OUTPUT_DIR)

# Final performance summary
total_time = time.time() - training_start_time
avg_tflops = total_flops_accumulated / (total_time * 1e12)
avg_flops_per_token = total_flops_accumulated / total_tokens_processed if total_tokens_processed > 0 else 0

print("\n" + "="*60)
print("TRAINING COMPLETED - PERFORMANCE SUMMARY")
print("="*60)
print(f"Total training time: {total_time/60:.2f} minutes")
print(f"Total tokens processed: {total_tokens_processed:,}")
print(f"Total FLOPs: {total_flops_accumulated/1e12:.2f} TFLOPs")
print(f"Average TFLOPS: {avg_tflops:.2f}")
print(f"Average FLOPs per token: {avg_flops_per_token/1e9:.2f}B")
print(f"Final resource status: {monitor_resources()}")
print("="*60)

# Clean up process group
if torch.distributed.is_initialized():
    torch.distributed.destroy_process_group()

Loading google/gemma-3-270m...

Loading weights:   0%|          | 0/236 [00:00<?, ?it/s]

/usr/local/lib/python3.11/dist-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py:479: UserWarning: FSDP is switching to use `NO_SHARD` instead of ShardingStrategy.FULL_SHARD since the world size is 1.
  _init_core_state(
`use_cache=True` is incompatible with gradient checkpointing. Setting `use_cache=False`.

Estimated FLOPs per forward pass: 63.49B
Total parameters: 268,098,176
Starting FSDP training (single GPU mode)
Resource status: CPU: 17.4% | GPU 0: 13.71/15.99 GB (0.0%)

Epoch 1/3 - CPU: 17.4% | GPU 0: 13.71/15.99 GB (0.0%)
Epoch 1 validation loss: 3.0878 | Val TFLOPS: 1.53 | Val FLOPs/token: 0.13B
  CPU: 16.6% | GPU 0: 15.66/15.99 GB (48.0%)

Epoch 2/3 - CPU: 16.7% | GPU 0: 15.66/15.99 GB (48.0%)
Epoch 2 validation loss: 3.2757 | Val TFLOPS: 1.54 | Val FLOPs/token: 0.13B
  CPU: 16.7% | GPU 0: 15.66/15.99 GB (47.0%)

Epoch 3/3 - CPU: 16.7% | GPU 0: 15.66/15.99 GB (47.0%)
Epoch 3 validation loss: 3.3109 | Val TFLOPS: 1.50 | Val FLOPs/token: 0.13B
  CPU: 16.7% | GPU 0: 15.66/15.99 GB (39.0%)

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================
TRAINING COMPLETED - PERFORMANCE SUMMARY
============================================================
Total training time: 3.30 minutes
Total tokens processed: 511,104
Total FLOPs: 190.27 TFLOPs
Average TFLOPS: 0.96
Average FLOPs per token: 0.37B
Final resource status: CPU: 16.7% | GPU 0: 15.66/15.99 GB (0.0%)
============================================================

**Reference**
- [Arxiv:PyTorch FSDP: Experiences on Scaling Fully Sharded Data Parallel](https://arxiv.org/abs/2304.11277)
- [PyTorch:FullyShardedDataParallel](https://docs.pytorch.org/docs/stable/fsdp.html)
- [PyTorch:Getting Started with Fully Sharded Data Parallel (FSDP2)](https://docs.pytorch.org/tutorials/intermediate/FSDP_tutorial.html)
- [Huggingface:FullyShardedDataParallel](https://huggingface.co/docs/transformers/en/fsdp)
- [Medium:An Introduction to FSDP (Fully Sharded Data Parallel) for Distributed Training](https://medium.com/@siddharthashrestha/an-introduction-to-fsdp-fully-sharded-data-parallel-for-distributed-training-5e67adfa1712)

### Combined torch.compile + FSDP Optimization

Combined torch.compile + FSDP Optimization is the peak of PyTorch performance engineering for Large Language Models. It integrates two distinct optimization philosophies: FSDP handles memory efficiency by sharding the model across hardware, while torch.compile handles computational efficiency by generating optimized machine code kernels. Together, they allow for the training of massive models at maximum hardware throughput, effectively solving both the "out-of-memory" problem and the "slow execution" problem simultaneously.

**How it Works**

The combination creates a layered optimization stack:
- Memory Layer (FSDP): The model is decomposed into shards. Only the parameters needed for the current computational "block" are gathered into a GPU's memory at any given time.
- Execution Layer (`torch.compile`): Once FSDP gathers the necessary shards for a layer, `torch.compile` takes over. It identifies the mathematical operations within that layer and "fuses" them into a single, high-speed Triton kernel.
- Communication Layer: The system uses CUDA Graphs to record the pattern of sharding, gathering, and kernel execution. This allows the CPU to simply "replay" the entire complex training step without having to re-calculate the logic, nearly eliminating the time the GPU spends waiting for instructions.

**Combined Optimization Implementation**

The script orchestrates this complex interaction by following a specific initialization order:
- FSDP Wrapping First: The model is first wrapped in FSDP with a `transformer_auto_wrap_policy`. This ensures the model is already sharded into manageable blocks (`GemmaDecoderLayers`) before the compiler looks at it.
- Compilation of the Sharded Model: The line `model = torch.compile(model, ...)` is called on top of the FSDP-wrapped model. This allows the compiler to optimize the internal logic of the shards themselves.
- CUDA Graph Marking: The call to `torch.compiler.cudagraph_mark_step_begin()` in the training loop is critical. It signals to the compiler that a new iteration of the sharding-gathering-computing cycle is starting, allowing the "Reduce-Overhead" logic to function correctly across distributed hardware.
- Mixed Precision Alignment: Both FSDP and the compiler are configured to use dtype (likely `bfloat16`). This ensures that the generated kernels and the data moving between GPUs are using the same optimized format, preventing expensive type-conversion operations.
- Performance Monitoring: The inclusion of `estimate_model_flops` allows the script to report TFLOPS. In a combined setup, this metric is the "source of truth"—if TFLOPS are high, it means the compiler is effectively masking the communication delays caused by FSDP sharding.

**When to Use It**

Combined optimization is the "gold standard" for the following scenarios:
- Industrial-Scale Fine-Tuning: When training 7B to 70B+ parameter models on multi-GPU clusters (e.g., 8x A100 nodes), where every percentage point of efficiency translates to thousands of dollars in saved compute costs.
- Maximizing Hardware Utility: If the GPUs are powerful (H100/A100) but the training is still slow due to CPU bottlenecks or slow inter-GPU links, this combination "squeezes" the most performance out of the hardware.
- Extremely Long Sequences: When training on context lengths of 32k or 128k tokens, where memory is tight (needing FSDP) and the quadratic cost of attention makes kernel fusion (via compile) essential.
- Stability at Scale: This setup is more stable than standard Data Parallelism for large models because it provides a highly predictable memory footprint and execution pattern.

In [ ]:
import torch
import time
from torch.distributed.fsdp import FullyShardedDataParallel as FSDP
from torch.distributed.fsdp.wrap import transformer_auto_wrap_policy
from torch.utils.data import DataLoader
from transformers import AutoTokenizer, AutoModelForCausalLM, DataCollatorForLanguageModeling
from transformers.models.gemma.modeling_gemma import GemmaDecoderLayer
from datasets import Dataset
import psutil
import GPUtil
from functools import partial

In [21]:
# Global variables for performance tracking
_training_start_time = None
_total_tokens_processed = 0
_total_flops = 0
_flops_per_step = None

def monitor_resources():
    """Monitor CPU and GPU memory usage, plus compute TFLOPS and FLOPs per token"""
    global _total_tokens_processed, _total_flops, _training_start_time
    
    cpu_mem = psutil.virtual_memory().percent
    gpus = GPUtil.getGPUs()
    gpu_info = []
    for gpu in gpus:
        gpu_used = gpu.memoryUsed / 1024
        gpu_total = gpu.memoryTotal / 1024
        gpu_info.append(f"GPU {gpu.id}: {gpu_used:.2f}/{gpu_total:.2f} GB ({gpu.load*100:.1f}%)")
    
    # Calculate performance metrics if we have tracking data
    performance_info = []
    if _training_start_time is not None and _total_tokens_processed > 0 and _total_flops > 0:
        elapsed_time = time.time() - _training_start_time
        if elapsed_time > 0:
            # Calculate TFLOPS (Tera FLoating Point OPerations per Second)
            tflops = _total_flops / (elapsed_time * 1e12)
            
            # Calculate FLOPs per token
            flops_per_token = _total_flops / _total_tokens_processed
            
            performance_info = [
                f"TFLOPS: {tflops:.2f}",
                f"FLOPs/token: {flops_per_token/1e9:.2f}B"
            ]
    
    # Combine all metrics
    base_info = f"CPU: {cpu_mem}% | " + " | ".join(gpu_info)
    if performance_info:
        return base_info + " | " + " | ".join(performance_info)
    return base_info

def estimate_model_flops(model, batch_size, seq_length):
    """Estimate FLOPs per forward pass for the model"""
    # Get model configuration
    hidden_size = model.config.hidden_size
    num_layers = model.config.num_hidden_layers
    intermediate_size = model.config.intermediate_size
    vocab_size = model.config.vocab_size
    
    # FLOPs per token per layer approximation:
    # Attention: QKV projections + attention computation + output projection
    attention_flops_per_layer = 4 * hidden_size * hidden_size * seq_length
    
    # FFN FLOPs (assuming GLU variant like in Gemma)
    ffn_flops_per_layer = 2 * hidden_size * intermediate_size * seq_length * 2
    
    # Total FLOPs per layer
    flops_per_layer = attention_flops_per_layer + ffn_flops_per_layer
    
    # Total FLOPs for all layers
    total_flops = flops_per_layer * num_layers
    
    # Add embedding FLOPs (input + output)
    embedding_flops = 2 * batch_size * seq_length * hidden_size * vocab_size
    
    return total_flops + embedding_flops

# Check if process group is already initialized
if not torch.distributed.is_initialized():
    torch.distributed.init_process_group(backend="nccl", init_method="tcp://localhost:23456", rank=0, world_size=1)
torch.cuda.set_device(0)

device = torch.device("cuda", 0)
dtype = torch.bfloat16 if torch.cuda.is_bf16_supported() else torch.float16

MODEL_NAME = "google/gemma-3-270m"
OUTPUT_DIR = "./gemma-3-270m-finetuned-qa-compiled-fsdp"
MAX_LENGTH = 128
BATCH_SIZE = 4

tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
tokenizer.pad_token = tokenizer.eos_token

def tokenize_examples(df):
    texts = [
        f"<bos>Question: {row['question_title']}\n{row['question_body']}\nAnswer: {row['answer']}<eos>"
        for row in df.iter_rows(named=True)
    ]
    tokenized = tokenizer(
        texts,
        truncation=True,
        max_length=MAX_LENGTH,
        padding="max_length",
        return_tensors="pt"
    )
    tokenized["labels"] = tokenized["input_ids"].clone()
    return tokenized

train_tokenized = tokenize_examples(train_data)
val_tokenized = tokenize_examples(val_data)

train_dataset = Dataset.from_dict({
    "input_ids": train_tokenized["input_ids"],
    "attention_mask": train_tokenized["attention_mask"],
    "labels": train_tokenized["labels"]
})

val_dataset = Dataset.from_dict({
    "input_ids": val_tokenized["input_ids"],
    "attention_mask": val_tokenized["attention_mask"],
    "labels": val_tokenized["labels"]
})

collator = DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False)

train_loader = DataLoader(train_dataset, batch_size=BATCH_SIZE, shuffle=True,
                          collate_fn=collator, pin_memory=True)
val_loader = DataLoader(val_dataset, batch_size=BATCH_SIZE,
                        collate_fn=collator, pin_memory=True)

print(f"Loading {MODEL_NAME}...")
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    torch_dtype=dtype,
    low_cpu_mem_usage=True,
)

# Pre-calculate FLOPs per step for performance monitoring
_flops_per_step = estimate_model_flops(model, BATCH_SIZE, MAX_LENGTH)
print(f"Estimated FLOPs per forward pass: {_flops_per_step/1e9:.2f}B")

# Enable gradient checkpointing for memory efficiency
model.gradient_checkpointing_enable()

# Create the auto-wrap policy function using functools.partial
auto_wrap_policy = partial(
    transformer_auto_wrap_policy,
    transformer_layer_cls={GemmaDecoderLayer}
)

model = FSDP(
    model,
    auto_wrap_policy=auto_wrap_policy,
    device_id=torch.cuda.current_device(),
    mixed_precision=torch.distributed.fsdp.MixedPrecision(
        param_dtype=dtype,
        reduce_dtype=dtype,
        buffer_dtype=dtype,
    ),
    sharding_strategy=torch.distributed.fsdp.ShardingStrategy.FULL_SHARD,
    use_orig_params=True,
    limit_all_gathers=True,
)

print("Compiling FSDP model...")
model = torch.compile(
    model,
    mode="default",
    fullgraph=False,
    dynamic=False,
    backend="inductor"
)

optimizer = torch.optim.AdamW(model.parameters(), lr=2e-5, weight_decay=0.01, fused=True)

total_steps = len(train_loader) * 3
warmup_steps = int(total_steps * 0.1)

def get_lr(step):
    if step < warmup_steps:
        return 2e-5 * (step + 1) / warmup_steps
    progress = (step - warmup_steps) / max(1, total_steps - warmup_steps)
    return 2e-5 * 0.5 * (1.0 + torch.cos(torch.pi * torch.tensor(progress)).item())

print(f"Total parameters: {sum(p.numel() for p in model.parameters()):,}")
print("Starting combined torch.compile + FSDP training (single GPU)")

# Initialize performance tracking
_training_start_time = time.time()
_total_tokens_processed = 0
_total_flops = 0

print(f"Resource status: {monitor_resources()}")

model.train()
global_step = 0
accum_loss = 0.0
accumulation_steps = 4

for epoch in range(3):
    print(f"\nEpoch {epoch+1}/3 - {monitor_resources()}")
    
    for batch_idx, batch in enumerate(train_loader):
        global_step += 1
        
        batch = {k: v.to(device) for k, v in batch.items()}
        
        # Track tokens for FLOPs calculation
        batch_tokens = batch["input_ids"].numel()
        _total_tokens_processed += batch_tokens
        
        # Track FLOPs (forward + backward)
        _total_flops += _flops_per_step  # Forward pass
        _total_flops += 2 * _flops_per_step  # Backward pass (approx 2x forward)
        
        # Mark CUDA graph step for compiled model
        if torch.cuda.is_available():
            torch.compiler.cudagraph_mark_step_begin()
        
        with torch.amp.autocast(device_type="cuda", dtype=dtype):
            outputs = model(**batch)
            loss = outputs.loss / accumulation_steps
        
        loss.backward()
        accum_loss += loss.item() * accumulation_steps
        
        if (batch_idx + 1) % accumulation_steps == 0:
            torch.nn.utils.clip_grad_norm_(model.parameters(), 1.0)
            lr = get_lr(global_step)
            for param_group in optimizer.param_groups:
                param_group["lr"] = lr
            optimizer.step()
            optimizer.zero_grad(set_to_none=True)
            
            if global_step % 50 == 0:
                print(f"Step {global_step:5d} | Loss: {accum_loss/accumulation_steps:.4f} | LR: {lr:.2e}")
                # Also show performance metrics at the same interval
                print(f"  {monitor_resources()}")
            
            accum_loss = 0.0
    
    model.eval()
    val_loss = 0.0
    
    with torch.no_grad():
        for batch in val_loader:
            batch = {k: v.to(device) for k, v in batch.items()}
            
            # Track validation tokens for consistent metrics
            val_tokens = batch["input_ids"].numel()
            _total_tokens_processed += val_tokens
            _total_flops += _flops_per_step  # Forward pass only for validation
            
            # Mark CUDA graph step for validation
            if torch.cuda.is_available():
                torch.compiler.cudagraph_mark_step_begin()
            
            with torch.amp.autocast(device_type="cuda", dtype=dtype):
                outputs = model(**batch)
            val_loss += outputs.loss.item()
    
    avg_val_loss = val_loss / len(val_loader)
    print(f"Epoch {epoch+1} validation loss: {avg_val_loss:.4f} - {monitor_resources()}")
    model.train()

# Save the model (unwrapping FSDP)
from torch.distributed.fsdp import FullyShardedDataParallel
if isinstance(model, FullyShardedDataParallel):
    model.module.save_pretrained(OUTPUT_DIR)
else:
    model.save_pretrained(OUTPUT_DIR)

tokenizer.save_pretrained(OUTPUT_DIR)

# Final performance summary
total_time = time.time() - _training_start_time
avg_tflops = _total_flops / (total_time * 1e12)
avg_flops_per_token = _total_flops / _total_tokens_processed if _total_tokens_processed > 0 else 0

print("\n" + "="*60)
print("TRAINING COMPLETED - PERFORMANCE SUMMARY")
print("="*60)
print(f"Total training time: {total_time/60:.2f} minutes")
print(f"Total tokens processed: {_total_tokens_processed:,}")
print(f"Total FLOPs: {_total_flops/1e12:.2f} TFLOPs")
print(f"Average TFLOPS: {avg_tflops:.2f}")
print(f"Average FLOPs per token: {avg_flops_per_token/1e9:.2f}B")
print(f"Final resource status: {monitor_resources()}")
print("="*60)

# Clean up process group
if torch.distributed.is_initialized():
    torch.distributed.destroy_process_group()

Loading google/gemma-3-270m...

Loading weights:   0%|          | 0/236 [00:00<?, ?it/s]

/usr/local/lib/python3.11/dist-packages/torch/distributed/fsdp/fully_sharded_data_parallel.py:479: UserWarning: FSDP is switching to use `NO_SHARD` instead of ShardingStrategy.FULL_SHARD since the world size is 1.
  _init_core_state(
[rank0]:W0214 13:27:36.950000 1670 torch/_logging/_internal.py:1204] [1/0] Profiler function <class 'torch.autograd.profiler.record_function'> will be ignored

Estimated FLOPs per forward pass: 187.65B
Compiling FSDP model...
Total parameters: 268,098,176
Starting combined torch.compile + FSDP training (single GPU)
Resource status: CPU: 16.7% | GPU 0: 15.28/15.99 GB (7.0%)

Epoch 1/3 - CPU: 16.7% | GPU 0: 15.28/15.99 GB (7.0%)
Step   100 | Loss: 2.7834 | LR: 2.00e-05
  CPU: 17.7% | GPU 0: 14.99/15.99 GB (75.0%) | TFLOPS: 0.82 | FLOPs/token: 1.10B
Step   200 | Loss: 2.4612 | LR: 1.94e-05
  CPU: 17.6% | GPU 0: 14.99/15.99 GB (70.0%) | TFLOPS: 1.42 | FLOPs/token: 1.10B
Step   300 | Loss: 2.3319 | LR: 1.76e-05
  CPU: 17.7% | GPU 0: 15.00/15.99 GB (83.0%) | TFLOPS: 1.87 | FLOPs/token: 1.10B
Epoch 1 validation loss: 3.0994 - CPU: 18.0% | GPU 0: 15.63/15.99 GB (0.0%) | TFLOPS: 1.07 | FLOPs/token: 0.97B

Epoch 2/3 - CPU: 18.0% | GPU 0: 15.63/15.99 GB (0.0%) | TFLOPS: 1.07 | FLOPs/token: 0.97B
Epoch 2 validation loss: 3.2847 - CPU: 18.0% | GPU 0: 15.63/15.99 GB (37.0%) | TFLOPS: 1.78 | FLOPs/token: 0.97B

Epoch 3/3 - CPU: 18.1% | GPU 0: 15.63/15.99 GB (37.0%) | TFLOPS: 1.78 | FLOPs/token: 0.97B
Step   750 | Loss: 1.8724 | LR: 3.55e-06
  CPU: 18.0% | GPU 0: 15.00/15.99 GB (69.0%) | TFLOPS: 1.91 | FLOPs/token: 0.98B
Step   850 | Loss: 1.8205 | LR: 1.32e-06
  CPU: 18.0% | GPU 0: 15.00/15.99 GB (81.0%) | TFLOPS: 2.06 | FLOPs/token: 1.00B
Step   950 | Loss: 1.9419 | LR: 1.46e-07
  CPU: 18.0% | GPU 0: 15.00/15.99 GB (78.0%) | TFLOPS: 2.19 | FLOPs/token: 1.00B
Epoch 3 validation loss: 3.3015 - CPU: 18.0% | GPU 0: 15.63/15.99 GB (47.0%) | TFLOPS: 2.29 | FLOPs/token: 0.97B

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

============================================================
TRAINING COMPLETED - PERFORMANCE SUMMARY
============================================================
Total training time: 4.40 minutes
Total tokens processed: 620,544
Total FLOPs: 602.93 TFLOPs
Average TFLOPS: 2.28
Average FLOPs per token: 0.97B
Final resource status: CPU: 18.0% | GPU 0: 15.63/15.99 GB (0.0%) | TFLOPS: 2.28 | FLOPs/token: 0.97B
============================================================

**Reference**
- [PyTorch:Datasets & DataLoaders](https://docs.pytorch.org/tutorials/beginner/basics/data_tutorial.html)
- [PyTorch:Introduction to torch.compile](https://docs.pytorch.org/tutorials/intermediate/torch_compile_tutorial.html)
- [PyTorch:Compiling LLM models from Huggingface](https://docs.pytorch.org/TensorRT/tutorials/compile_hf_models.html)
- [PyTorch:Peak Performance, Minimized Memory: Optimizing torchtune’s performance with torch.compile & Liger Kernel](https://pytorch.org/blog/peak-performance-minimized-memory/)
- [Arxiv:PyTorch FSDP: Experiences on Scaling Fully Sharded Data Parallel](https://arxiv.org/abs/2304.11277)
- [PyTorch:FullyShardedDataParallel](https://docs.pytorch.org/docs/stable/fsdp.html)
- [PyTorch:Getting Started with Fully Sharded Data Parallel (FSDP2)](https://docs.pytorch.org/tutorials/intermediate/FSDP_tutorial.html)
- [Huggingface:FullyShardedDataParallel](https://huggingface.co/docs/transformers/en/fsdp)
- [Medium:An Introduction to FSDP (Fully Sharded Data Parallel) for Distributed Training](https://medium.com/@siddharthashrestha/an-introduction-to-fsdp-fully-sharded-data-parallel-for-distributed-training-5e67adfa1712)

## JAX/Flax Optimizations

JAX is a high-performance numerical computing library developed by Google, and Flax is the flexible neural network library built on top of it. In the landscape of Large Language Models (LLMs), JAX/Flax optimizations represent a shift from the "eager" execution of PyTorch to a "compiled" and "functional" approach. These tools allow researchers to treat an entire LLM training step as a single mathematical function that is optimized and compiled into highly efficient machine code for specific hardware.

**Core Optimization Mechanisms**

**1. XLA (Accelerated Linear Algebra) and JIT Compilation**

The most significant optimization in JAX is the Just-In-Time (JIT) compilation using the XLA compiler.
- Kernel Fusion: Standard frameworks execute operations (like Matrix Multiplication followed by a LayerNorm) as separate steps. XLA fuses these into a single "kernel," which prevents the processor from constantly reading and writing data to memory.
- Hardware Specialization: XLA analyzes the model's math and generates the most efficient possible code for the specific GPU or TPU being used, often achieving higher "FLOPs utilization" than standard execution.

**2. SPMD (Single Program, Multiple Data) Parallelism**

Scaling LLMs to hundreds of chips is traditionally difficult. JAX uses GSPMD to handle massive distribution automatically.
- Declarative Sharding: Instead of manually writing logic to split a model (like FSDP), you simply define how your data and model weights should be "partitioned" (e.g., "split the batch across these 8 chips" and "split the hidden dimension across those 8 chips").
- Automatic Communication: JAX handles the complex networking (All-Gather, Reduce-Scatter) required to keep the chips in sync, allowing models like Gemini and PaLM to scale across thousands of TPU pods seamlessly.

**3. Functional Transformations (vmap, grad, pmap)**

JAX optimizations are built on composable transformations:
- grad: Efficiently calculates gradients for the entire compiled function at once.
- vmap: Automatically "vectorizes" code, allowing you to write math for a single sequence and automatically scale it to large batches without losing performance.
- pmap: Parallelizes computation across multiple hardware devices with a single function call.

**When to Use JAX/Flax**

**When Training on Google Cloud TPUs**

JAX is the native language of the Tensor Processing Unit (TPU). If your infrastructure is built around TPU v4 or v5, JAX/Flax will almost always outperform PyTorch in terms of speed and stability because it was designed specifically for the TPU's architecture.

**When Training Foundation Models from Scratch**

For "Grand Challenge" models (100B+ parameters), JAX’s sharding logic is often more robust. It allows engineers to experiment with complex 3D parallelism (combining data, model, and pipeline parallelism) without the code becoming unreadable or unmaintainable.

**When Customizing Low-Level Math**

If you are developing a new type of attention mechanism or a Mixture of Experts (MoE) router, JAX allows you to write standard Python/NumPy-like code and have it compiled into high-performance CUDA/TPU kernels. This avoids the need to write custom C++ or CUDA code to get high speeds.

**When Using Reference Implementations like MaxText**

Many of the most efficient LLM training recipes (like Google's MaxText) are written in JAX. If you need to replicate state-of-the-art results for models like Gemma or Llama on high-performance clusters, using the JAX-native stack is the most direct path.

**Reference**
- [JAX:Resources and Advanced Guides](https://docs.jax.dev/en/latest/advanced_guides.html)
- [JAX/FLAX:JAX/Flax Key Concepts](https://flax.readthedocs.io/en/latest/key_concepts.html)
- [JAX:Quickstart: How to think in JAX](https://docs.jax.dev/en/latest/notebooks/thinking_in_jax.html)
- [FLAX:Documentation](https://flax.readthedocs.io/en/v0.8.1/)
- [Uvadlc:Tutorial 2 (JAX): Introduction to JAX+Flax](https://uvadlc-notebooks.readthedocs.io/en/latest/tutorial_notebooks/JAX/tutorial2/Introduction_to_JAX.html#)
- [GitHub:JAX example](https://github.com/jax-ml/jax-llm-examples)
- [JAX:How to Scale Your Model](https://jax-ml.github.io/scaling-book/)
- [Medium:Gemma from Scratch: Mastering LLM Implementation with JAX and Flax](https://medium.com/@lucamassaron/gemma-from-scratch-mastering-llm-implementation-with-jax-and-flax-2de783163f46)
- [Medium:Optimizers in JAX and Flax](https://pub.towardsai.net/optimizers-in-jax-and-flax-0f9c50fd517c)

### JAX JIT optimizations

JAX/JIT (Just-In-Time) optimization is a compilation strategy that transforms Python functions into highly efficient, hardware-specific machine code. In the context of Large Language Models (LLMs), JIT allows the computer to stop interpreting Python line-by-line and instead execute a single, fused, and optimized mathematical "blob" directly on a GPU or TPU.

Traditional frameworks like PyTorch (in eager mode) execute operations one by one. For an LLM, this means the GPU does a matrix multiplication, sends results to memory, waits for the next instruction, does an activation function, and sends results to memory again. JAX/JIT eliminates these "round trips" to memory by looking ahead at the entire computation graph.

**How JAX/JIT Works: The Tracing Mechanism**

JIT optimization relies on a process called Tracing. Here is the detailed workflow:
- Tracer Objects: When a function decorated with `@jax.jit` is called, JAX does not pass real numbers (like 0.56) into the function. Instead, it passes "Tracer" objects that represent the shape and type of the data.
- Recording the Jaxpr: As the Python code runs with these tracers, JAX records every mathematical operation performed. This creates a platform-independent intermediate representation called a Jaxpr (JAX Expression).
- XLA Compilation: The Accelerated Linear Algebra (XLA) compiler takes the Jaxpr and optimizes it. It performs Kernel Fusion, where it combines many operations (e.g., `Attention+Residual+LayerNorm`) into a single piece of GPU code.
- Hardware Optimization: XLA allocates memory buffers specifically to minimize data movement and optimizes the math for the specific chip architecture (NVIDIA CUDA kernels for GPUs or TPU-specific instructions).
- Caching: The final machine code is saved in a cache. If the function is called again with the same input shapes, the optimized code runs instantly, bypassing Python entirely.

**JAX/JIT Implementation**

The code implements several high-level JIT strategies to ensure the Gemma model fine-tuning is performant.

**1. Computational Fusion via `@jax.jit`**

The script applies JIT at three strategic entry points:
- `compute_loss`: This fuses the LLM's forward pass with the optax loss calculation. It ensures that the millions of parameters in the Gemma layers are processed as a single continuous pipeline before the loss is returned.
- `train_step`: This is the most critical optimization. It wraps `jax.value_and_grad`. This means the forward pass, the backward pass (calculating gradients), and the optimizer update are all compiled into one massive hardware kernel. This is why JAX can often outperform other frameworks in raw training speed.
- `eval_step`: This optimizes the inference pass, ensuring validation does not slow down the training loop.

**2. Static Compilation Strategy**

The code uses a Static Compilation strategy by defining `MAX_LENGTH = 128` and `BATCH_SIZE = 4`.
- Because these values are hardcoded, every time `train_step` is called, the input tensors have the exact same dimensions.
- This prevents "re-compilation." If the sequence length changed every step, JAX would have to re-trace and re-compile the entire model constantly, which would make the code slower than regular Python.

**3. Functional Purity**

The model definition (forward function) is written using Pure Functions.
- It does not use global variables or in-place modifications (like x += y).
- By passing params as an explicit argument, the JIT compiler can clearly see the data flow, which is a requirement for XLA to successfully optimize the LLM graph.

**When to Use JAX/JIT Optimization**

Use JAX/JIT in these scenarios:
- Training Foundation Models: When training models with billions of parameters, the memory savings from XLA kernel fusion are mandatory to fit the model on modern hardware.
- Production Inference: When the model must respond in milliseconds. Removing Python interpreter overhead is essential for low-latency applications.
- Multi-Device Scaling: When using dozens or hundreds of GPUs/TPUs. JIT allows JAX to automatically calculate how to split the math across chips using the Multi-device Compilation strategy.
- Custom Math/Research: If creating a new type of Attention mechanism. JAX will compile your custom Python math into a high-performance kernel that is just as fast as hand-written C++ or CUDA.

Avoid JIT when:
- Input shapes change every time: For example, if sequence lengths are completely random and cannot be padded, JIT will spend more time compiling than actually running.
- Debugging: JIT hides the internal values of variables. To see what is happening inside a layer, the JIT decorator must be removed to allow standard Python `print()` statements to work.

In [1]:
%%capture
!pip install jax
!pip install flax
!pip install optax
!pip install --upgrade transformers jax jaxlib flax optax datasets
!pip install "numpy<2.0.0" --force-reinstall
!pip install --upgrade "jax[cpu]"

import os
# Try to use GPU, but handle version mismatches gracefully
os.environ['JAX_PLATFORMS'] = ''  # Let JAX auto-detect

import jax
import jax.numpy as jnp
import optax
import numpy as np
from transformers import AutoTokenizer
from datasets import Dataset, DatasetDict
from torch.utils.data import DataLoader
from flax.training import train_state
import pickle
import warnings
import time
import psutil
import subprocess
import platform

# Suppress specific warnings
warnings.filterwarnings("ignore", message="Jax plugin configuration error")

In [ ]:
# Configuration
MODEL_NAME = "google/gemma-3-270m"
OUTPUT_DIR = "./gemma-3-270m-finetuned-qa-jax-jit"
MAX_LENGTH = 128
EMBED_DIM = 256
NUM_HEADS = 4
NUM_LAYERS = 2
BATCH_SIZE = 4
LEARNING_RATE = 2e-5
WEIGHT_DECAY = 0.01
EPOCHS = 3

# Resource Monitoring Functions
class ResourceMonitor:
    def __init__(self):
        self.process = psutil.Process()
        self.start_time = time.time()
        self.step_times = []
        self.memory_usage = []
        self.gpu_usage = []
        self.total_flops = 0
        self.total_gflops = 0
        
    def get_cpu_usage(self):
        """Get CPU usage percentage."""
        return self.process.cpu_percent()
    
    def get_memory_usage(self):
        """Get memory usage in GB."""
        memory_info = self.process.memory_info()
        return memory_info.rss / (1024 ** 3)  # Convert to GB
    
    def get_gpu_usage(self):
        """Get GPU usage if available."""
        if jax.devices()[0].platform == 'gpu':
            try:
                # For NVIDIA GPUs
                result = subprocess.run(
                    ['nvidia-smi', '--query-gpu=memory.used,memory.total,utilization.gpu', 
                     '--format=csv,noheader,nounits'],
                    capture_output=True, text=True
                )
                if result.returncode == 0:
                    gpu_stats = result.stdout.strip().split('\n')
                    gpu_info = []
                    for stat in gpu_stats:
                        if stat:
                            memory_used, memory_total, gpu_util = stat.split(', ')
                            gpu_info.append({
                                'memory_used_gb': float(memory_used) / 1024,
                                'memory_total_gb': float(memory_total) / 1024,
                                'utilization': float(gpu_util)
                            })
                    return gpu_info
            except:
                return None
        return None
    
    def get_tpu_usage(self):
        """Get TPU usage if available."""
        if jax.devices()[0].platform == 'tpu':
            try:
                # Basic TPU info from JAX
                devices = jax.devices()
                tpu_info = []
                for device in devices:
                    tpu_info.append({
                        'device': str(device),
                        'memory_limit_gb': device.memory_stats()['bytes_limit'] / (1024 ** 3) if hasattr(device, 'memory_stats') else 'N/A'
                    })
                return tpu_info
            except:
                return None
        return None
    
    def estimate_flops_per_step(self, batch_size, seq_len, vocab_size, embed_dim, num_heads, num_layers):
        """Estimate FLOPS per training step."""
        # Attention FLOPS: 2 * batch_size * seq_len^2 * embed_dim * num_heads
        attn_flops = 2 * batch_size * (seq_len ** 2) * embed_dim * num_heads
        
        # MLP FLOPS: 2 * batch_size * seq_len * embed_dim * (4 * embed_dim) * num_layers
        mlp_flops = 2 * batch_size * seq_len * embed_dim * (4 * embed_dim) * num_layers
        
        # Embedding FLOPS: batch_size * seq_len * embed_dim
        embed_flops = batch_size * seq_len * embed_dim
        
        # Total FLOPS per forward pass (multiply by 3 for backward pass - forward, backward, gradient computation)
        total_flops = (attn_flops + mlp_flops + embed_flops) * 3
        
        return total_flops
    
    def log_step(self, step, loss, batch_size, seq_len):
        """Log resource usage for current step."""
        current_time = time.time()
        self.step_times.append(current_time)
        
        cpu_usage = self.get_cpu_usage()
        memory_usage = self.get_memory_usage()
        gpu_usage = self.get_gpu_usage()
        tpu_usage = self.get_tpu_usage()
        
        flops = self.estimate_flops_per_step(
            batch_size, seq_len, VOCAB_SIZE, EMBED_DIM, NUM_HEADS, NUM_LAYERS
        )
        self.total_flops += flops
        self.total_gflops += flops / 1e9
        
        # Calculate step time
        if len(self.step_times) > 1:
            step_time = self.step_times[-1] - self.step_times[-2]
            steps_per_second = 1.0 / step_time if step_time > 0 else 0
        else:
            step_time = 0
            steps_per_second = 0
        
        return {
            'step': step,
            'loss': loss,
            'step_time_ms': step_time * 1000,
            'steps_per_second': steps_per_second,
            'cpu_usage_percent': cpu_usage,
            'memory_usage_gb': memory_usage,
            'gpu_usage': gpu_usage,
            'tpu_usage': tpu_usage,
            'estimated_flops': flops,
            'estimated_gflops': flops / 1e9,
            'estimated_tflops': flops / 1e12
        }
    
    def print_summary(self):
        """Print summary of resource usage."""
        total_time = time.time() - self.start_time
        avg_step_time = np.mean(np.diff(self.step_times)) * 1000 if len(self.step_times) > 1 else 0
        avg_memory = np.mean(self.memory_usage) if self.memory_usage else 0
        peak_memory = max(self.memory_usage) if self.memory_usage else 0
        
        print("\n" + "="*60)
        print("RESOURCE USAGE SUMMARY")
        print("="*60)
        print(f"Total training time: {total_time:.2f} seconds")
        print(f"Average step time: {avg_step_time:.2f} ms")
        print(f"Average memory usage: {avg_memory:.2f} GB")
        print(f"Peak memory usage: {peak_memory:.2f} GB")
        print(f"Total FLOPS: {self.total_flops:.2e}")
        print(f"Total GFLOPS: {self.total_gflops:.2f} GFLOPS")
        
        if jax.devices()[0].platform == 'gpu' and self.gpu_usage:
            avg_gpu_util = np.mean([g['utilization'] for g in self.gpu_usage if g]) if self.gpu_usage else 0
            print(f"Average GPU utilization: {avg_gpu_util:.1f}%")
        
        print("="*60)

# Load tokenizer and get vocab size
print(f"Loading tokenizer: {MODEL_NAME}")
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
tokenizer.pad_token = tokenizer.eos_token
VOCAB_SIZE = len(tokenizer)
print(f"Tokenizer loaded. Vocab size: {VOCAB_SIZE}")

# Create dataset (assuming train_data and val_data exist)
def tokenize_examples(df, max_length=MAX_LENGTH):
    """Tokenize examples from a Polars DataFrame."""
    texts = [
        f"<bos>Question: {row['question_title']}\n{row['question_body']}\nAnswer: {row['answer']}<eos>" 
        for row in df.rows(named=True)
    ]
    tokenized = tokenizer(
        texts,
        truncation=True,
        max_length=max_length,
        padding="max_length",
        return_tensors="np"
    )
    tokenized["labels"] = tokenized["input_ids"].copy()
    return tokenized

# Note: train_data and val_data should be provided externally
train_tokenized = tokenize_examples(train_data)
val_tokenized = tokenize_examples(val_data)

dataset_dict = DatasetDict({
    "train": Dataset.from_dict({
        "input_ids": train_tokenized["input_ids"],
        "attention_mask": train_tokenized["attention_mask"],
        "labels": train_tokenized["labels"]
    }),
    "validation": Dataset.from_dict({
        "input_ids": val_tokenized["input_ids"],
        "attention_mask": val_tokenized["attention_mask"],
        "labels": val_tokenized["labels"]
    })
})

# Data loaders
def numpy_collate(batch):
    return {k: np.stack([b[k] for b in batch]) for k in batch[0].keys()}

train_loader = DataLoader(
    dataset_dict["train"],
    batch_size=BATCH_SIZE,
    shuffle=True,
    collate_fn=numpy_collate,
)
val_loader = DataLoader(
    dataset_dict["validation"],
    batch_size=BATCH_SIZE,
    collate_fn=numpy_collate,
)

# Check JAX devices
print(f"\nJAX devices: {jax.devices()}")
print(f"JAX backend: {jax.devices()[0].platform}")

# JAX Model Definition
def init_params(rng):
    keys = jax.random.split(rng, 5)
    
    params = {
        'wte': jax.random.normal(keys[0], (VOCAB_SIZE, EMBED_DIM)) * 0.02,
        'wpe': jax.random.normal(keys[1], (MAX_LENGTH, EMBED_DIM)) * 0.02,
        'layers': [],
        'ln_f_scale': jnp.ones(EMBED_DIM),
        'ln_f_bias': jnp.zeros(EMBED_DIM),
        'lm_head': jax.random.normal(keys[3], (EMBED_DIM, VOCAB_SIZE)) * 0.02,
    }
    
    for i in range(NUM_LAYERS):
        layer_key = jax.random.split(keys[2], NUM_LAYERS)[i]
        layer_keys = jax.random.split(layer_key, 6)
        params['layers'].append({
            'attn_q': jax.random.normal(layer_keys[0], (EMBED_DIM, EMBED_DIM)) * 0.02,
            'attn_k': jax.random.normal(layer_keys[1], (EMBED_DIM, EMBED_DIM)) * 0.02,
            'attn_v': jax.random.normal(layer_keys[2], (EMBED_DIM, EMBED_DIM)) * 0.02,
            'attn_out': jax.random.normal(layer_keys[3], (EMBED_DIM, EMBED_DIM)) * 0.02,
            'ln1_scale': jnp.ones(EMBED_DIM),
            'ln1_bias': jnp.zeros(EMBED_DIM),
            'mlp_in': jax.random.normal(layer_keys[4], (EMBED_DIM, EMBED_DIM * 4)) * 0.02,
            'mlp_out': jax.random.normal(layer_keys[5], (EMBED_DIM * 4, EMBED_DIM)) * 0.02,
            'ln2_scale': jnp.ones(EMBED_DIM),
            'ln2_bias': jnp.zeros(EMBED_DIM),
        })
    
    return params

def layer_norm(x, scale, bias, eps=1e-5):
    mean = jnp.mean(x, axis=-1, keepdims=True)
    var = jnp.var(x, axis=-1, keepdims=True)
    return scale * (x - mean) / jnp.sqrt(var + eps) + bias

def forward(params, input_ids, attention_mask=None):
    batch_size, seq_len = input_ids.shape
    
    x = params['wte'][input_ids] + params['wpe'][:seq_len]
    
    mask = jnp.tril(jnp.ones((seq_len, seq_len))).reshape(1, 1, seq_len, seq_len)
    mask = (mask == 0) * -1e9
    
    if attention_mask is not None:
        attention_mask = attention_mask[:, None, None, :]
        attention_mask = (1.0 - attention_mask) * -1e9
        mask = mask + attention_mask
    
    def reshape_for_heads(x):
        return x.reshape(batch_size, seq_len, NUM_HEADS, -1).transpose(0, 2, 1, 3)
    
    for layer in params['layers']:
        residual = x
        x = layer_norm(x, layer['ln1_scale'], layer['ln1_bias'])
        
        q = reshape_for_heads(jnp.matmul(x, layer['attn_q']))
        k = reshape_for_heads(jnp.matmul(x, layer['attn_k']))
        v = reshape_for_heads(jnp.matmul(x, layer['attn_v']))
        
        scores = jnp.matmul(q, k.transpose(0, 1, 3, 2)) / jnp.sqrt(q.shape[-1])
        scores = scores + mask
        attn_out = jnp.matmul(jax.nn.softmax(scores, axis=-1), v)
        
        attn_out = attn_out.transpose(0, 2, 1, 3).reshape(batch_size, seq_len, -1)
        attn_out = jnp.matmul(attn_out, layer['attn_out'])
        x = residual + attn_out
        
        residual = x
        x = layer_norm(x, layer['ln2_scale'], layer['ln2_bias'])
        x = jnp.matmul(x, layer['mlp_in'])
        x = jax.nn.gelu(x)
        x = jnp.matmul(x, layer['mlp_out'])
        x = residual + x
    
    x = layer_norm(x, params['ln_f_scale'], params['ln_f_bias'])
    return jnp.matmul(x, params['lm_head'])

# JIT Compiled Functions
@jax.jit
def compute_loss(params, batch):
    logits = forward(params, batch['input_ids'], batch['attention_mask'])
    shift_logits = logits[..., :-1, :]
    shift_labels = batch['labels'][..., 1:]
    loss = optax.softmax_cross_entropy_with_integer_labels(shift_logits, shift_labels)
    mask = (shift_labels != tokenizer.pad_token_id).astype(loss.dtype)
    return (loss * mask).sum() / mask.sum()

@jax.jit
def train_step(state, batch):
    loss, grads = jax.value_and_grad(compute_loss)(state.params, batch)
    return state.apply_gradients(grads=grads), loss

@jax.jit
def eval_step(params, batch):
    return compute_loss(params, batch)

# Training Setup
# Handle JAX version compatibility for random key
try:
    rng = jax.random.key(42)
except (AttributeError, TypeError):
    rng = jax.random.PRNGKey(42)

params = init_params(rng)
tx = optax.adamw(LEARNING_RATE, weight_decay=WEIGHT_DECAY)
state = train_state.TrainState.create(apply_fn=None, params=params, tx=tx)

total_params = sum(p.size for p in jax.tree.leaves(state.params))
print(f"\nTotal parameters: {total_params:,}")
print("Starting training with JAX JIT compilation...\n")

# Initialize resource monitor
monitor = ResourceMonitor()

# Training Loop with Resource Monitoring
for epoch in range(EPOCHS):
    epoch_loss = 0.0
    steps = 0
    
    for batch in train_loader:
        batch = {k: jnp.array(v) for k, v in batch.items()}
        state, loss = train_step(state, batch)
        epoch_loss += float(loss)
        steps += 1
        
        # Log resource usage
        seq_len = batch['input_ids'].shape[1]
        resources = monitor.log_step(steps, float(loss), BATCH_SIZE, seq_len)
        monitor.memory_usage.append(resources['memory_usage_gb'])
        if resources['gpu_usage']:
            monitor.gpu_usage.append(resources['gpu_usage'][0] if resources['gpu_usage'] else None)
        
        if steps % 10 == 0:
            print(f"  Step {steps:3d} | Loss: {float(loss):.4f} | "
                  f"Time: {resources['step_time_ms']:.1f}ms | "
                  f"Mem: {resources['memory_usage_gb']:.2f}GB | "
                  f"CPU: {resources['cpu_usage_percent']:.1f}% | "
                  f"GFLOPS: {resources['estimated_gflops']:.2f}")
            if resources['gpu_usage']:
                gpu = resources['gpu_usage'][0]
                print(f"        GPU: {gpu['utilization']:.1f}% | "
                      f"GPU Mem: {gpu['memory_used_gb']:.2f}/{gpu['memory_total_gb']:.2f}GB")
    
    val_loss = 0.0
    val_steps = 0
    for batch in val_loader:
        batch = {k: jnp.array(v) for k, v in batch.items()}
        loss = eval_step(state.params, batch)
        val_loss += float(loss)
        val_steps += 1
    
    print(f"Epoch {epoch+1} | Train Loss: {epoch_loss/steps:.4f} | Val Loss: {val_loss/val_steps:.4f}\n")

# Print resource usage summary
monitor.print_summary()

# Save Model
os.makedirs(OUTPUT_DIR, exist_ok=True)
with open(f"{OUTPUT_DIR}/params.pkl", "wb") as f:
    pickle.dump(state.params, f)
tokenizer.save_pretrained(OUTPUT_DIR)
print(f"Training completed. Model saved to {OUTPUT_DIR}")

# Calculate and display GFLOPS performance metrics
print("\n" + "="*60)
print("GFLOPS PERFORMANCE METRICS")
print("="*60)
total_time = time.time() - monitor.start_time
total_steps = len(monitor.step_times) - 1
avg_gflops_per_step = monitor.total_gflops / total_steps if total_steps > 0 else 0
gflops_per_second = monitor.total_gflops / total_time if total_time > 0 else 0

print(f"Total steps: {total_steps}")
print(f"Total GFLOPS: {monitor.total_gflops:.2f}")
print(f"Average GFLOPS per step: {avg_gflops_per_step:.2f}")
print(f"GFLOPS per second: {gflops_per_second:.2f}")
print(f"GFLOPS per watt: N/A (power monitoring not available)")
print("="*60)

print("\n" + "="*60)
print("JAX JIT COMPILATION BENEFITS")
print("="*60)
print("Operation fusion and XLA optimization")
print("Optimized memory allocation")
print("Static graph compilation")
print("Dynamic shape handling")
print("="*60)

**Reference**
- [JAX:Just-in-time compilation](https://docs.jax.dev/en/latest/jit-compilation.html)
- [JAX:jax.jit](https://docs.jax.dev/en/latest/_autosummary/jax.jit.html)
- [APXML:Introducing jax.jit](https://apxml.com/courses/getting-started-with-jax/chapter-2-accelerating-functions-jit/introducing-jax-jit)
- [JAX:Resources and Advanced Guides](https://docs.jax.dev/en/latest/advanced_guides.html)
- [JAX/FLAX:JAX/Flax Key Concepts](https://flax.readthedocs.io/en/latest/key_concepts.html)
- [JAX:Quickstart: How to think in JAX](https://docs.jax.dev/en/latest/notebooks/thinking_in_jax.html)
- [FLAX:Documentation](https://flax.readthedocs.io/en/v0.8.1/)
- [Uvadlc:Tutorial 2 (JAX): Introduction to JAX+Flax](https://uvadlc-notebooks.readthedocs.io/en/latest/tutorial_notebooks/JAX/tutorial2/Introduction_to_JAX.html#)
- [GitHub:JAX example](https://github.com/jax-ml/jax-llm-examples)
- [JAX:How to Scale Your Model](https://jax-ml.github.io/scaling-book/)
- [Medium:Gemma from Scratch: Mastering LLM Implementation with JAX and Flax](https://medium.com/@lucamassaron/gemma-from-scratch-mastering-llm-implementation-with-jax-and-flax-2de783163f46)
- [Medium:Optimizers in JAX and Flax](https://pub.towardsai.net/optimizers-in-jax-and-flax-0f9c50fd517c)

### JAX vmap (Vectorization) Optimization

In JAX, vmap (vectorizing map) is a higher-order transformation that converts a function designed to process a single data point into an optimized function that processes batches of data.

In the context of Large Language Models (LLMs), vmap is a core optimization used to handle the complexity of batching across multiple dimensions (like batch size, sequence length, and attention heads) without manually writing matrix-to-matrix operations.

**JAX vmap in LLMs: Detailed Mechanism**

Traditional deep learning frameworks often require the developer to think in "batches" from the start. For example, a linear layer must be defined to handle a 2D input (Batch,Features). In contrast, vmap allows the logic for a single example to be written first, and then it "promotes" that logic to handle batches automatically.

**How it Works Under the Hood**

- Traced Operations: When vmap is called on a function, JAX "traces" the function using abstract values. It identifies every primitive operation (like dot, add, or softmax).
- Axis Expansion: JAX looks at the in_axes argument (which specifies which input dimensions represent the batch). It then automatically rewrites each primitive operation to include this extra dimension.
- Primitive Lowering: Instead of using a Python loop to iterate over the batch, JAX lowers the entire batched operation into a single XLA (Accelerated Linear Algebra) kernel.
- For example, a Matrix-Vector multiplication for one example is automatically transformed into a Matrix-Matrix multiplication for a batch, which is significantly faster on GPUs/TPUs.

**JAX (vmap) Optimization Implementation**

The provided code uses vmap to bridge the gap between a single-example loss calculation and a full training step.

**1. The Single-Example Logic**

The function `single_example_loss` is defined to process one sequence at a time.

    def single_example_loss(params, input_ids, attention_mask, labels):
        # input_ids is 1D here (seq_len,)
        logits = forward(params, input_ids[None, :], ...)[0] 
        ...
        return (loss * mask).sum() / mask.sum()

Inside this function, the inputs are treated as vectors. The code manually adds a fake batch dimension using `[None, :]` just to satisfy the forward function, but the core logic is mathematically focused on one instance.

**2. The vmap Transformation**

This is where the optimization happens:

    batch_loss = jax.vmap(single_example_loss, in_axes=(None, 0, 0, 0))

- `in_axes=(None, 0, 0, 0)`: This tells JAX how to map the inputs.
    - `None`: Do not batch the params. Every example in the batch uses the same model weights.
    - `0`: Batch the `input_ids, attention_mask, and labels` along their 0th axis (the batch dimension).
- Result: `batch_loss` now expects a 2D array (`Batch,SeqLength`) for the inputs and returns a vector of losses (one for each item in the batch).

**3. Execution and JIT Integration**

    @jax.jit
    def compute_loss_vmap(params, batch):
        return batch_loss(params, batch['input_ids'], ...).mean()

The code combines vmap with `@jax.jit.`
- `vmap` handles the mathematical batching (turning loops into vector operations).
- `jit` handles the compilation, fusing those operations into a single, high-speed GPU kernel.

**When to Use JAX vmap**

`vmap` should be used in the following scenarios:
- Simplifying Complex Architectures: If an LLM has complex custom attention or sampling logic, writing it for a single example is easier and less error-prone. Use `vmap` to add batching afterward.
- Per-Example Gradients: When computing gradients for each individual example in a batch (common in Differential Privacy or certain Meta-Learning algorithms), `vmap(grad(loss_fn))` is the standard approach.
- Ensemble Modeling: Running the same input through multiple different sets of model parameters simultaneously.
- Avoiding Manual Indexing: If the code involves complex slicing or indexing that becomes messy with an extra batch dimension, `vmap` keeps the logic clean.
- Performance Tuning: When a standard for-loop over a batch is too slow, `vmap` pushes that loop down into the XLA compiler to run in parallel.

In [ ]:
import jax
import jax.numpy as jnp
import optax
import numpy as np
from transformers import AutoTokenizer
from datasets import Dataset, DatasetDict
from torch.utils.data import DataLoader
from flax.training import train_state
import pickle
import os
import time
import psutil
import subprocess
import platform

In [ ]:
# Configuration
MODEL_NAME = "google/gemma-3-270m"
OUTPUT_DIR = "./gemma-3-270m-finetuned-qa-jax-vmap"
MAX_LENGTH = 128
EMBED_DIM = 256
NUM_HEADS = 4
NUM_LAYERS = 2
BATCH_SIZE = 4
LEARNING_RATE = 2e-5
WEIGHT_DECAY = 0.01
EPOCHS = 3

# Resource Monitoring Functions
class ResourceMonitor:
    def __init__(self):
        self.process = psutil.Process()
        self.start_time = time.time()
        self.step_times = []
        self.memory_samples = []
        self.gpu_samples = []
        self.losses = []
        self.total_flops = 0
        self.total_gflops = 0
        
    def get_cpu_percent(self):
        """Get current CPU usage percentage."""
        return self.process.cpu_percent()
    
    def get_memory_gb(self):
        """Get current memory usage in GB."""
        return self.process.memory_info().rss / (1024 ** 3)
    
    def get_gpu_info(self):
        """Get GPU information if available."""
        if jax.devices()[0].platform == 'gpu':
            try:
                result = subprocess.run(
                    ['nvidia-smi', '--query-gpu=index,name,memory.used,memory.total,utilization.gpu', 
                     '--format=csv,noheader,nounits'],
                    capture_output=True, text=True, check=False
                )
                if result.returncode == 0 and result.stdout.strip():
                    gpus = []
                    for line in result.stdout.strip().split('\n'):
                        if line:
                            parts = [x.strip() for x in line.split(',')]
                            if len(parts) >= 5:
                                gpus.append({
                                    'index': parts[0],
                                    'name': parts[1],
                                    'memory_used_mb': float(parts[2]),
                                    'memory_total_mb': float(parts[3]),
                                    'utilization': float(parts[4])
                                })
                    return gpus
            except:
                pass
        return None
    
    def get_tpu_info(self):
        """Get TPU information if available."""
        if jax.devices()[0].platform == 'tpu':
            try:
                devices = jax.devices()
                tpus = []
                for i, device in enumerate(devices):
                    tpus.append({
                        'index': i,
                        'device': str(device),
                    })
                return tpus
            except:
                pass
        return None
    
    def estimate_flops(self, seq_len):
        """Estimate FLOPS per forward/backward pass."""
        # Attention FLOPS: 4 * batch_size * seq_len^2 * embed_dim * num_heads
        attn_flops = 4 * BATCH_SIZE * (seq_len ** 2) * EMBED_DIM * NUM_HEADS
        
        # MLP FLOPS: 2 * batch_size * seq_len * embed_dim * (4 * embed_dim) * num_layers * 2 (for forward+backward)
        mlp_flops = 4 * BATCH_SIZE * seq_len * EMBED_DIM * (4 * EMBED_DIM) * NUM_LAYERS
        
        # Embedding FLOPS: 2 * batch_size * seq_len * embed_dim
        embed_flops = 2 * BATCH_SIZE * seq_len * EMBED_DIM
        
        # Total FLOPS (multiply by 2 for forward+backward with gradient computation)
        total_flops = (attn_flops + mlp_flops + embed_flops) * 2
        
        return total_flops
    
    def log_step(self, step, loss, seq_len):
        """Log metrics for current step."""
        current_time = time.time()
        self.step_times.append(current_time)
        self.losses.append(loss)
        
        # CPU and memory metrics
        cpu_percent = self.get_cpu_percent()
        memory_gb = self.get_memory_gb()
        self.memory_samples.append(memory_gb)
        
        # GPU metrics
        gpu_info = self.get_gpu_info()
        if gpu_info:
            self.gpu_samples.append(gpu_info)
        
        # TPU metrics
        tpu_info = self.get_tpu_info()
        
        # FLOPS estimation
        estimated_flops = self.estimate_flops(seq_len)
        self.total_flops += estimated_flops
        self.total_gflops += estimated_flops / 1e9
        
        # Step timing
        step_time = 0
        steps_per_sec = 0
        if len(self.step_times) > 1:
            step_time = (self.step_times[-1] - self.step_times[-2]) * 1000  # Convert to ms
            steps_per_sec = 1.0 / (self.step_times[-1] - self.step_times[-2])
        
        metrics = {
            'step': step,
            'loss': loss,
            'step_time_ms': step_time,
            'steps_per_second': steps_per_sec,
            'cpu_percent': cpu_percent,
            'memory_gb': memory_gb,
            'estimated_flops': estimated_flops,
            'estimated_gflops': estimated_flops / 1e9,
            'estimated_tflops': estimated_flops / 1e12,
            'gpu_info': gpu_info,
            'tpu_info': tpu_info
        }
        
        return metrics
    
    def print_step_metrics(self, metrics):
        """Print metrics for current step."""
        line = f"  Step {metrics['step']:3d} | Loss: {metrics['loss']:.4f} | "
        line += f"Time: {metrics['step_time_ms']:.1f}ms | "
        line += f"Mem: {metrics['memory_gb']:.2f}GB | "
        line += f"CPU: {metrics['cpu_percent']:.1f}% | "
        line += f"GFLOPS: {metrics['estimated_gflops']:.2f}"
        print(line)
        
        if metrics['gpu_info']:
            for gpu in metrics['gpu_info']:
                print(f"        GPU {gpu['index']}: {gpu['name']} | "
                      f"Util: {gpu['utilization']:.1f}% | "
                      f"Mem: {gpu['memory_used_mb']/1024:.2f}/{gpu['memory_total_mb']/1024:.2f}GB")
        
        if metrics['tpu_info']:
            for tpu in metrics['tpu_info']:
                print(f"        TPU {tpu['index']}: {tpu['device']}")
    
    def print_summary(self):
        """Print summary of resource usage."""
        total_time = time.time() - self.start_time
        avg_step_time = np.mean(np.diff(self.step_times)) * 1000 if len(self.step_times) > 1 else 0
        avg_memory = np.mean(self.memory_samples) if self.memory_samples else 0
        peak_memory = max(self.memory_samples) if self.memory_samples else 0
        avg_loss = np.mean(self.losses) if self.losses else 0
        final_loss = self.losses[-1] if self.losses else 0
        total_steps = len(self.step_times) - 1
        avg_gflops_per_step = self.total_gflops / total_steps if total_steps > 0 else 0
        gflops_per_second = self.total_gflops / total_time if total_time > 0 else 0
        
        print("\n" + "="*70)
        print("RESOURCE USAGE SUMMARY")
        print("="*70)
        print(f"Total training time: {total_time:.2f} seconds")
        print(f"Average step time: {avg_step_time:.2f} ms")
        print(f"Average steps/second: {1.0/(avg_step_time/1000) if avg_step_time > 0 else 0:.2f}")
        print(f"Average memory usage: {avg_memory:.2f} GB")
        print(f"Peak memory usage: {peak_memory:.2f} GB")
        print(f"Average loss: {avg_loss:.4f}")
        print(f"Final loss: {final_loss:.4f}")
        print(f"Total FLOPS: {self.total_flops:.2e}")
        print(f"Total GFLOPS: {self.total_gflops:.2f}")
        print(f"Average GFLOPS per step: {avg_gflops_per_step:.2f}")
        print(f"GFLOPS per second: {gflops_per_second:.2f}")
        
        if self.gpu_samples:
            avg_gpu_util = np.mean([g[0]['utilization'] for g in self.gpu_samples if g]) if self.gpu_samples else 0
            avg_gpu_mem = np.mean([g[0]['memory_used_mb']/1024 for g in self.gpu_samples if g]) if self.gpu_samples else 0
            print(f"Average GPU utilization: {avg_gpu_util:.1f}%")
            print(f"Average GPU memory: {avg_gpu_mem:.2f} GB")
        
        # Estimate total FLOPS
        total_flops = sum(self.estimate_flops(MAX_LENGTH) for _ in range(len(self.step_times)-1))
        print(f"Estimated total FLOPS: {total_flops:.2e}")
        print(f"Estimated total TFLOPS: {total_flops/1e12:.2f}")
        print("="*70)

# Tokenization - Get vocab size from tokenizer
print(f"Loading tokenizer: {MODEL_NAME}")
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
tokenizer.pad_token = tokenizer.eos_token
VOCAB_SIZE = len(tokenizer)
print(f"Tokenizer loaded. Vocab size: {VOCAB_SIZE}")

def tokenize_examples(df, max_length=MAX_LENGTH):
    """Tokenize examples from a Polars DataFrame."""
    texts = [
        f"<bos>Question: {row['question_title']}\n{row['question_body']}\nAnswer: {row['answer']}<eos>" 
        for row in df.rows(named=True)
    ]
    tokenized = tokenizer(
        texts,
        truncation=True,
        max_length=max_length,
        padding="max_length",
        return_tensors="np"
    )
    tokenized["labels"] = tokenized["input_ids"].copy()
    return tokenized

# train_data and val_data should be Polars DataFrames
train_tokenized = tokenize_examples(train_data)
val_tokenized = tokenize_examples(val_data)

dataset_dict = DatasetDict({
    "train": Dataset.from_dict({
        "input_ids": train_tokenized["input_ids"],
        "attention_mask": train_tokenized["attention_mask"],
        "labels": train_tokenized["labels"]
    }),
    "validation": Dataset.from_dict({
        "input_ids": val_tokenized["input_ids"],
        "attention_mask": val_tokenized["attention_mask"],
        "labels": val_tokenized["labels"]
    })
})

def numpy_collate(batch):
    return {k: np.stack([b[k] for b in batch]) for k in batch[0].keys()}

train_loader = DataLoader(
    dataset_dict["train"], 
    batch_size=BATCH_SIZE, 
    shuffle=True, 
    collate_fn=numpy_collate
)
val_loader = DataLoader(
    dataset_dict["validation"], 
    batch_size=BATCH_SIZE, 
    collate_fn=numpy_collate
)

# JAX Model Definition
def init_params(rng):
    keys = jax.random.split(rng, 5)
    
    params = {
        'wte': jax.random.normal(keys[0], (VOCAB_SIZE, EMBED_DIM)) * 0.02,
        'wpe': jax.random.normal(keys[1], (MAX_LENGTH, EMBED_DIM)) * 0.02,
        'layers': [],
        'ln_f_scale': jnp.ones(EMBED_DIM),
        'ln_f_bias': jnp.zeros(EMBED_DIM),
        'lm_head': jax.random.normal(keys[3], (EMBED_DIM, VOCAB_SIZE)) * 0.02,
    }
    
    for i in range(NUM_LAYERS):
        layer_key = jax.random.split(keys[2], NUM_LAYERS)[i]
        layer_keys = jax.random.split(layer_key, 6)
        params['layers'].append({
            'attn_q': jax.random.normal(layer_keys[0], (EMBED_DIM, EMBED_DIM)) * 0.02,
            'attn_k': jax.random.normal(layer_keys[1], (EMBED_DIM, EMBED_DIM)) * 0.02,
            'attn_v': jax.random.normal(layer_keys[2], (EMBED_DIM, EMBED_DIM)) * 0.02,
            'attn_out': jax.random.normal(layer_keys[3], (EMBED_DIM, EMBED_DIM)) * 0.02,
            'ln1_scale': jnp.ones(EMBED_DIM),
            'ln1_bias': jnp.zeros(EMBED_DIM),
            'mlp_in': jax.random.normal(layer_keys[4], (EMBED_DIM, EMBED_DIM * 4)) * 0.02,
            'mlp_out': jax.random.normal(layer_keys[5], (EMBED_DIM * 4, EMBED_DIM)) * 0.02,
            'ln2_scale': jnp.ones(EMBED_DIM),
            'ln2_bias': jnp.zeros(EMBED_DIM),
        })
    
    return params

def layer_norm(x, scale, bias, eps=1e-5):
    mean = jnp.mean(x, axis=-1, keepdims=True)
    var = jnp.var(x, axis=-1, keepdims=True)
    return scale * (x - mean) / jnp.sqrt(var + eps) + bias

def forward(params, input_ids, attention_mask=None):
    batch_size, seq_len = input_ids.shape
    
    x = params['wte'][input_ids] + params['wpe'][:seq_len]
    
    mask = jnp.tril(jnp.ones((seq_len, seq_len))).reshape(1, 1, seq_len, seq_len)
    mask = (mask == 0) * -1e9
    
    if attention_mask is not None:
        attention_mask = attention_mask[:, None, None, :]
        attention_mask = (1.0 - attention_mask) * -1e9
        mask = mask + attention_mask
    
    def reshape_for_heads(x):
        return x.reshape(batch_size, seq_len, NUM_HEADS, -1).transpose(0, 2, 1, 3)
    
    for layer in params['layers']:
        residual = x
        x = layer_norm(x, layer['ln1_scale'], layer['ln1_bias'])
        
        q = reshape_for_heads(jnp.matmul(x, layer['attn_q']))
        k = reshape_for_heads(jnp.matmul(x, layer['attn_k']))
        v = reshape_for_heads(jnp.matmul(x, layer['attn_v']))
        
        scores = jnp.matmul(q, k.transpose(0, 1, 3, 2)) / jnp.sqrt(q.shape[-1])
        scores = scores + mask
        attn_out = jnp.matmul(jax.nn.softmax(scores, axis=-1), v)
        
        attn_out = attn_out.transpose(0, 2, 1, 3).reshape(batch_size, seq_len, -1)
        attn_out = jnp.matmul(attn_out, layer['attn_out'])
        x = residual + attn_out
        
        residual = x
        x = layer_norm(x, layer['ln2_scale'], layer['ln2_bias'])
        x = jnp.matmul(x, layer['mlp_in'])
        x = jax.nn.gelu(x)
        x = jnp.matmul(x, layer['mlp_out'])
        x = residual + x
    
    x = layer_norm(x, params['ln_f_scale'], params['ln_f_bias'])
    return jnp.matmul(x, params['lm_head'])

# VMAP: Vectorized functions
def single_example_loss(params, input_ids, attention_mask, labels):
    """Loss for a single example."""
    logits = forward(params, input_ids[None, :], attention_mask[None, :])[0]
    shift_logits = logits[:-1, :]
    shift_labels = labels[1:]
    loss = optax.softmax_cross_entropy_with_integer_labels(shift_logits, shift_labels)
    mask = (shift_labels != tokenizer.pad_token_id).astype(loss.dtype)
    return (loss * mask).sum() / mask.sum()

# Create batched versions using vmap
batch_loss = jax.vmap(single_example_loss, in_axes=(None, 0, 0, 0))

@jax.jit
def compute_loss_vmap(params, batch):
    """Compute loss using vmap for automatic batching."""
    return batch_loss(params, batch['input_ids'], batch['attention_mask'], batch['labels']).mean()

@jax.jit
def train_step_vmap(state, batch):
    """Training step with vmap optimization."""
    loss, grads = jax.value_and_grad(compute_loss_vmap)(state.params, batch)
    return state.apply_gradients(grads=grads), loss

# Training State
def create_train_state(rng):
    params = init_params(rng)
    tx = optax.adamw(LEARNING_RATE, weight_decay=WEIGHT_DECAY)
    return train_state.TrainState.create(apply_fn=None, params=params, tx=tx)

rng = jax.random.PRNGKey(42)
state = create_train_state(rng)

# Initialize resource monitor
monitor = ResourceMonitor()

# Print device information
print(f"\nJAX devices: {jax.devices()}")
print(f"JAX backend: {jax.devices()[0].platform}")

# Training Loop with vmap and resource monitoring
total_params = sum(p.size for p in jax.tree.leaves(state.params))
print(f"\nTotal parameters: {total_params:,}")
print("Training with vmap optimization...\n")

for epoch in range(EPOCHS):
    epoch_loss = 0.0
    steps = 0
    
    for batch in train_loader:
        batch = {k: jnp.array(v) for k, v in batch.items()}
        state, loss = train_step_vmap(state, batch)
        epoch_loss += float(loss)
        steps += 1
        
        # Log resource metrics every step
        seq_len = batch['input_ids'].shape[1]
        metrics = monitor.log_step(steps, float(loss), seq_len)
        
        if steps % 10 == 0:
            monitor.print_step_metrics(metrics)
    
    val_loss = 0.0
    val_steps = 0
    for batch in val_loader:
        batch = {k: jnp.array(v) for k, v in batch.items()}
        loss = compute_loss_vmap(state.params, batch)
        val_loss += float(loss)
        val_steps += 1
    
    print(f"Epoch {epoch+1} | Train Loss: {epoch_loss/steps:.4f} | Val Loss: {val_loss/val_steps:.4f}\n")

# Print resource usage summary
monitor.print_summary()

# Save model
os.makedirs(OUTPUT_DIR, exist_ok=True)

with open(f"{OUTPUT_DIR}/params.pkl", "wb") as f:
    pickle.dump(state.params, f)
tokenizer.save_pretrained(OUTPUT_DIR)
print(f"Training completed. Model saved to {OUTPUT_DIR}")

print("\n" + "="*60)
print("JAX VMAP OPTIMIZATION BENEFITS")
print("="*60)
print("Automatic vectorization of single-example functions")
print("Eliminates manual batch dimension handling")
print("Cleaner, more maintainable code")
print("Efficient batching without explicit loops")
print("="*60)

**Reference**
- [JAX:jax.numpy.vectorize](https://docs.jax.dev/en/latest/_autosummary/jax.numpy.vectorize.html)
- [JAX:Automatic vectorization](https://docs.jax.dev/en/latest/automatic-vectorization.html)
- [APXML:Hands-on Practical: Vectorizing Functions](https://apxml.com/courses/getting-started-with-jax/chapter-4-automatic-vectorization-vmap/hands-on-vectorizing-functions)
- [JAX:Resources and Advanced Guides](https://docs.jax.dev/en/latest/advanced_guides.html)
- [JAX/FLAX:JAX/Flax Key Concepts](https://flax.readthedocs.io/en/latest/key_concepts.html)
- [JAX:Quickstart: How to think in JAX](https://docs.jax.dev/en/latest/notebooks/thinking_in_jax.html)
- [FLAX:Documentation](https://flax.readthedocs.io/en/v0.8.1/)
- [Uvadlc:Tutorial 2 (JAX): Introduction to JAX+Flax](https://uvadlc-notebooks.readthedocs.io/en/latest/tutorial_notebooks/JAX/tutorial2/Introduction_to_JAX.html#)
- [GitHub:JAX example](https://github.com/jax-ml/jax-llm-examples)
- [JAX:How to Scale Your Model](https://jax-ml.github.io/scaling-book/)
- [Medium:Gemma from Scratch: Mastering LLM Implementation with JAX and Flax](https://medium.com/@lucamassaron/gemma-from-scratch-mastering-llm-implementation-with-jax-and-flax-2de783163f46)
- [Medium:Optimizers in JAX and Flax](https://pub.towardsai.net/optimizers-in-jax-and-flax-0f9c50fd517c)

### JAX pmap (Parallel) Optimization

JAX pmap (Parallel Map) is a transformation designed for Single Program, Multiple Data (SPMD) parallelism. While vmap vectorizes operations on a single device, pmap distributes the computation across multiple hardware devices, such as multiple GPUs or TPU cores.

In the context of Large Language Models, pmap is primarily used for Data Parallelism. It allows the model to process a massive global batch by splitting it into smaller "shards," sending one shard to each device, and then synchronizing the results (like gradients) to ensure the model learns uniformly across all processors.

**How pmap Works: The SPMD Model**

- Replication: The model parameters and the compiled computation graph are copied (replicated) onto every available device.
- Sharding: The input data (the batch) is split along a new "mapped" axis. If there are 8 GPUs and a batch size of 64, pmap ensures each GPU receives a shard of 8 examples.
- Parallel Execution: Every device executes the same compiled function (the training step) simultaneously on its unique piece of data.
- Collective Communication: During the backward pass, devices must communicate. Since each GPU calculates gradients based only on its local shard, they use Collective Ops (like pmean or psum) to average the gradients across all devices before updating the weights.

**JAX pmap Optimization Implementation**

The provided script implements a robust data-parallel training pipeline using several JAX-specific patterns:

**1. Data Sharding (`shard_batch`)**

Before the data reaches the model, the `shard_batch` function reshapes the input tensors from (`Batch,Seq`) to (`Devices,PerDeviceBatch,Seq`). This explicit reshaping is necessary because `pmap` expects the leading dimension of the input to match the number of local devices.

**2. Gradient Synchronization (`jax.lax.pmean`)**

Inside `train_step_fn`, the code uses:

    grads = jax.lax.pmean(grads, axis_name=axis_name)

This is the most critical line for multi-device training. It triggers an All-Reduce operation. Every device sends its calculated gradients to every other device, and they all compute the average. Without this, the models on each GPU would diverge and become different models.

**3. State Replication**

The code uses `flax.jax_utils.replicate(state)`. Since pmap expects the inputs to have a leading "device" dimension, the model weights (the state) must also be transformed from a single set of weights into a stack of identical weights—one for each device.

**4. Execution with `axis_name`**
The `pmap` transformation is defined with `axis_name='devices'`. This name acts as an identifier for the collective operations inside the function, telling pmean which group of devices should participate in the gradient averaging.

**When to Use JAX `pmap` Optimization**

Use `pmap` in these scenarios:
- Multi-GPU Training: When a single GPU is too slow or its memory is too small to handle the desired batch size.
- TPU Pods: pmap is the standard way to scale LLM training across Google’s TPU architectures.
- Large-Scale Data Parallelism: When the model fits on one device, but the dataset is so large that processing it sequentially would take weeks.
- Synchronous Training: When it is necessary for all devices to stay "in sync" with the exact same parameter values at every step.

Avoid `pmap` (or transition to jit + sharding) when:
- Single Device: On a single GPU, pmap adds unnecessary overhead compared to `@jax.jit`.
- Model Parallelism: If the model itself is too large to fit on one GPU (e.g., a 175B parameter model), pmap alone is insufficient because it assumes the whole model fits on every device. In those cases, JAX’s newer jit with PartitionSpec (GSPMD) is preferred.

In [ ]:
import jax
import jax.numpy as jnp
import optax
import numpy as np
from transformers import AutoTokenizer
from datasets import Dataset, DatasetDict
from torch.utils.data import DataLoader
from flax.training import train_state
import flax
import pickle
import os
import time
import psutil
import subprocess

In [ ]:
# Configuration
MODEL_NAME = "google/gemma-3-270m"
OUTPUT_DIR = "./gemma-3-270m-finetuned-qa-jax-pmap"
EMBED_DIM = 256
MAX_LENGTH = 128
NUM_HEADS = 4
NUM_LAYERS = 2
BATCH_SIZE = 8
LEARNING_RATE = 2e-5
WEIGHT_DECAY = 0.01
EPOCHS = 3

# Resource Monitoring Functions
class ResourceMonitor:
    def __init__(self):
        self.process = psutil.Process()
        self.start_time = time.time()
        self.step_times = []
        self.memory_samples = []
        self.gpu_samples = []
        self.losses = []
        self.num_devices = jax.local_device_count()
        
    def get_cpu_percent(self):
        return self.process.cpu_percent()
    
    def get_memory_gb(self):
        return self.process.memory_info().rss / (1024 ** 3)
    
    def get_gpu_info(self):
        if jax.devices()[0].platform == 'gpu':
            try:
                result = subprocess.run(
                    ['nvidia-smi', '--query-gpu=index,name,memory.used,memory.total,utilization.gpu', 
                     '--format=csv,noheader,nounits'],
                    capture_output=True, text=True, check=False
                )
                if result.returncode == 0 and result.stdout.strip():
                    gpus = []
                    for line in result.stdout.strip().split('\n'):
                        if line:
                            parts = [x.strip() for x in line.split(',')]
                            if len(parts) >= 5:
                                gpus.append({
                                    'index': parts[0],
                                    'name': parts[1],
                                    'memory_used_mb': float(parts[2]),
                                    'memory_total_mb': float(parts[3]),
                                    'utilization': float(parts[4])
                                })
                    return gpus
            except:
                pass
        return None
    
    def estimate_flops(self, seq_len):
        per_device_batch = max(1, BATCH_SIZE // self.num_devices)
        attn_flops = 4 * per_device_batch * (seq_len ** 2) * EMBED_DIM * NUM_HEADS * self.num_devices
        mlp_flops = 4 * per_device_batch * seq_len * EMBED_DIM * (4 * EMBED_DIM) * NUM_LAYERS * self.num_devices
        embed_flops = 2 * per_device_batch * seq_len * EMBED_DIM * self.num_devices
        total_flops = (attn_flops + mlp_flops + embed_flops) * 2
        return total_flops
    
    def log_step(self, step, loss, seq_len):
        current_time = time.time()
        self.step_times.append(current_time)
        self.losses.append(loss)
        
        cpu_percent = self.get_cpu_percent()
        memory_gb = self.get_memory_gb()
        self.memory_samples.append(memory_gb)
        
        gpu_info = self.get_gpu_info()
        if gpu_info:
            self.gpu_samples.append(gpu_info)
        
        estimated_flops = self.estimate_flops(seq_len)
        
        step_time = 0
        steps_per_sec = 0
        if len(self.step_times) > 1:
            step_time = (self.step_times[-1] - self.step_times[-2]) * 1000
            steps_per_sec = 1.0 / (self.step_times[-1] - self.step_times[-2])
        
        return {
            'step': step,
            'loss': loss,
            'step_time_ms': step_time,
            'steps_per_second': steps_per_sec,
            'cpu_percent': cpu_percent,
            'memory_gb': memory_gb,
            'estimated_flops': estimated_flops,
            'estimated_tflops': estimated_flops / 1e12,
            'gpu_info': gpu_info
        }
    
    def print_step_metrics(self, metrics):
        line = f"  Step {metrics['step']:3d} | Loss: {metrics['loss']:.4f} | "
        line += f"Time: {metrics['step_time_ms']:.1f}ms | "
        line += f"Mem: {metrics['memory_gb']:.2f}GB | "
        line += f"CPU: {metrics['cpu_percent']:.1f}% | "
        line += f"FLOPS: {metrics['estimated_tflops']:.2f} TFLOPS"
        print(line)
        
        if metrics['gpu_info']:
            for gpu in metrics['gpu_info']:
                print(f"        GPU {gpu['index']}: {gpu['name']} | "
                      f"Util: {gpu['utilization']:.1f}% | "
                      f"Mem: {gpu['memory_used_mb']/1024:.2f}/{gpu['memory_total_mb']/1024:.2f}GB")
    
    def print_summary(self):
        total_time = time.time() - self.start_time
        avg_step_time = np.mean(np.diff(self.step_times)) * 1000 if len(self.step_times) > 1 else 0
        avg_memory = np.mean(self.memory_samples) if self.memory_samples else 0
        peak_memory = max(self.memory_samples) if self.memory_samples else 0
        avg_loss = np.mean(self.losses) if self.losses else 0
        
        print("\n" + "="*70)
        print("RESOURCE USAGE SUMMARY")
        print("="*70)
        print(f"Number of devices: {self.num_devices}")
        print(f"Total training time: {total_time:.2f} seconds")
        print(f"Average step time: {avg_step_time:.2f} ms")
        print(f"Average steps/second: {1.0/(avg_step_time/1000) if avg_step_time > 0 else 0:.2f}")
        print(f"Average memory usage: {avg_memory:.2f} GB")
        print(f"Peak memory usage: {peak_memory:.2f} GB")
        print(f"Average loss: {avg_loss:.4f}")
        
        if self.gpu_samples:
            avg_gpu_util = np.mean([g[0]['utilization'] for g in self.gpu_samples if g]) if self.gpu_samples else 0
            avg_gpu_mem = np.mean([g[0]['memory_used_mb']/1024 for g in self.gpu_samples if g]) if self.gpu_samples else 0
            print(f"Average GPU utilization: {avg_gpu_util:.1f}%")
            print(f"Average GPU memory: {avg_gpu_mem:.2f} GB")
        
        total_flops = sum(self.estimate_flops(MAX_LENGTH) for _ in range(len(self.step_times)-1))
        print(f"Estimated total FLOPS: {total_flops:.2e}")
        print(f"Estimated total TFLOPS: {total_flops/1e12:.2f}")
        print("="*70)

# Tokenization
print(f"Loading tokenizer: {MODEL_NAME}")
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
tokenizer.pad_token = tokenizer.eos_token
VOCAB_SIZE = len(tokenizer)
print(f"Tokenizer loaded. Vocab size: {VOCAB_SIZE}")

def tokenize_examples(df, max_length=MAX_LENGTH):
    texts = [
        f"<bos>Question: {row['question_title']}\n{row['question_body']}\nAnswer: {row['answer']}<eos>" 
        for row in df.rows(named=True)
    ]
    tokenized = tokenizer(
        texts,
        truncation=True,
        max_length=max_length,
        padding="max_length",
        return_tensors="np"
    )
    tokenized["labels"] = tokenized["input_ids"].copy()
    return tokenized

train_tokenized = tokenize_examples(train_data)
val_tokenized = tokenize_examples(val_data)

dataset_dict = DatasetDict({
    "train": Dataset.from_dict({
        "input_ids": train_tokenized["input_ids"],
        "attention_mask": train_tokenized["attention_mask"],
        "labels": train_tokenized["labels"]
    }),
    "validation": Dataset.from_dict({
        "input_ids": val_tokenized["input_ids"],
        "attention_mask": val_tokenized["attention_mask"],
        "labels": val_tokenized["labels"]
    })
})

def numpy_collate(batch):
    return {k: np.stack([b[k] for b in batch]) for k in batch[0].keys()}

train_loader = DataLoader(
    dataset_dict["train"], 
    batch_size=BATCH_SIZE, 
    shuffle=True, 
    collate_fn=numpy_collate
)
val_loader = DataLoader(
    dataset_dict["validation"], 
    batch_size=BATCH_SIZE, 
    collate_fn=numpy_collate
)

# JAX Model Definition
def init_params(rng):
    keys = jax.random.split(rng, 5)
    
    params = {
        'wte': jax.random.normal(keys[0], (VOCAB_SIZE, EMBED_DIM)) * 0.02,
        'wpe': jax.random.normal(keys[1], (MAX_LENGTH, EMBED_DIM)) * 0.02,
        'layers': [],
        'ln_f_scale': jnp.ones(EMBED_DIM),
        'ln_f_bias': jnp.zeros(EMBED_DIM),
        'lm_head': jax.random.normal(keys[3], (EMBED_DIM, VOCAB_SIZE)) * 0.02,
    }
    
    for i in range(NUM_LAYERS):
        layer_key = jax.random.split(keys[2], NUM_LAYERS)[i]
        layer_keys = jax.random.split(layer_key, 6)
        params['layers'].append({
            'attn_q': jax.random.normal(layer_keys[0], (EMBED_DIM, EMBED_DIM)) * 0.02,
            'attn_k': jax.random.normal(layer_keys[1], (EMBED_DIM, EMBED_DIM)) * 0.02,
            'attn_v': jax.random.normal(layer_keys[2], (EMBED_DIM, EMBED_DIM)) * 0.02,
            'attn_out': jax.random.normal(layer_keys[3], (EMBED_DIM, EMBED_DIM)) * 0.02,
            'ln1_scale': jnp.ones(EMBED_DIM),
            'ln1_bias': jnp.zeros(EMBED_DIM),
            'mlp_in': jax.random.normal(layer_keys[4], (EMBED_DIM, EMBED_DIM * 4)) * 0.02,
            'mlp_out': jax.random.normal(layer_keys[5], (EMBED_DIM * 4, EMBED_DIM)) * 0.02,
            'ln2_scale': jnp.ones(EMBED_DIM),
            'ln2_bias': jnp.zeros(EMBED_DIM),
        })
    
    return params

def layer_norm(x, scale, bias, eps=1e-5):
    mean = jnp.mean(x, axis=-1, keepdims=True)
    var = jnp.var(x, axis=-1, keepdims=True)
    return scale * (x - mean) / jnp.sqrt(var + eps) + bias

def forward(params, input_ids, attention_mask=None):
    batch_size, seq_len = input_ids.shape
    
    x = params['wte'][input_ids] + params['wpe'][:seq_len]
    
    mask = jnp.tril(jnp.ones((seq_len, seq_len))).reshape(1, 1, seq_len, seq_len)
    mask = (mask == 0) * -1e9
    
    if attention_mask is not None:
        attention_mask = attention_mask[:, None, None, :]
        attention_mask = (1.0 - attention_mask) * -1e9
        mask = mask + attention_mask
    
    def reshape_for_heads(x):
        return x.reshape(batch_size, seq_len, NUM_HEADS, -1).transpose(0, 2, 1, 3)
    
    for layer in params['layers']:
        residual = x
        x = layer_norm(x, layer['ln1_scale'], layer['ln1_bias'])
        
        q = reshape_for_heads(jnp.matmul(x, layer['attn_q']))
        k = reshape_for_heads(jnp.matmul(x, layer['attn_k']))
        v = reshape_for_heads(jnp.matmul(x, layer['attn_v']))
        
        scores = jnp.matmul(q, k.transpose(0, 1, 3, 2)) / jnp.sqrt(q.shape[-1])
        scores = scores + mask
        attn_out = jnp.matmul(jax.nn.softmax(scores, axis=-1), v)
        
        attn_out = attn_out.transpose(0, 2, 1, 3).reshape(batch_size, seq_len, -1)
        attn_out = jnp.matmul(attn_out, layer['attn_out'])
        x = residual + attn_out
        
        residual = x
        x = layer_norm(x, layer['ln2_scale'], layer['ln2_bias'])
        x = jnp.matmul(x, layer['mlp_in'])
        x = jax.nn.gelu(x)
        x = jnp.matmul(x, layer['mlp_out'])
        x = residual + x
    
    x = layer_norm(x, params['ln_f_scale'], params['ln_f_bias'])
    return jnp.matmul(x, params['lm_head'])

# Loss Functions
def compute_loss(params, batch):
    logits = forward(params, batch['input_ids'], batch['attention_mask'])
    shift_logits = logits[..., :-1, :]
    shift_labels = batch['labels'][..., 1:]
    loss = optax.softmax_cross_entropy_with_integer_labels(shift_logits, shift_labels)
    mask = (shift_labels != tokenizer.pad_token_id).astype(loss.dtype)
    return (loss * mask).sum() / mask.sum()

# PMAP: Multi-device parallelization
num_devices = jax.local_device_count()
print(f"\nNumber of devices: {num_devices}")

def shard_batch(batch):
    """Shard batch across devices for pmap."""
    batch_size = batch['input_ids'].shape[0]
    per_device = batch_size // num_devices
    if per_device == 0 or num_devices == 1:
        return batch
    return jax.tree.map(
        lambda x: x.reshape(num_devices, per_device, *x.shape[1:]),
        batch
    )

# Define axis name for pmap
axis_name = 'devices'

# Only define pmap functions if multiple devices are available
if num_devices > 1:
    train_step_pmap = jax.pmap(
        lambda state, batch: train_step_fn(state, batch),
        axis_name=axis_name
    )
    
    eval_step_pmap = jax.pmap(
        lambda state, batch: compute_loss(state.params, batch),
        axis_name=axis_name
    )
else:
    # Fallback to regular functions for single device
    def train_step_pmap(state, batch):
        loss, grads = jax.value_and_grad(compute_loss)(state.params, batch)
        state = state.apply_gradients(grads=grads)
        return state, loss
    
    def eval_step_pmap(state, batch):
        return compute_loss(state.params, batch)

def train_step_fn(state, batch):
    """Training step function for pmap."""
    loss, grads = jax.value_and_grad(compute_loss)(state.params, batch)
    grads = jax.lax.pmean(grads, axis_name=axis_name)
    state = state.apply_gradients(grads=grads)
    loss = jax.lax.pmean(loss, axis_name=axis_name)
    return state, loss

# Training State
def create_train_state(rng):
    params = init_params(rng)
    tx = optax.adamw(LEARNING_RATE, weight_decay=WEIGHT_DECAY)
    return train_state.TrainState.create(apply_fn=None, params=params, tx=tx)

rng = jax.random.PRNGKey(42)
state = create_train_state(rng)

# Replicate state across devices if more than one device
if num_devices > 1:
    state = flax.jax_utils.replicate(state)

# Initialize resource monitor
monitor = ResourceMonitor()

# Print device information
print(f"JAX devices: {jax.devices()}")
print(f"JAX backend: {jax.devices()[0].platform}")

# Training Loop with pmap and resource monitoring
total_params = sum(p.size for p in jax.tree.leaves(state.params))
print(f"\nTotal parameters: {total_params:,}")

if num_devices > 1:
    print(f"Training with pmap optimization across {num_devices} devices...\n")
else:
    print("Training with single device (fallback to regular training)...\n")

for epoch in range(EPOCHS):
    epoch_loss = 0.0
    steps = 0
    
    for batch in train_loader:
        batch = {k: jnp.array(v) for k, v in batch.items()}
        
        if num_devices > 1:
            batch = shard_batch(batch)
            state, loss = train_step_pmap(state, batch)
            loss_value = float(loss.mean())
        else:
            loss, grads = jax.value_and_grad(compute_loss)(state.params, batch)
            state = state.apply_gradients(grads=grads)
            loss_value = float(loss)
        
        epoch_loss += loss_value
        steps += 1
        
        seq_len = batch['input_ids'].shape[-1]
        metrics = monitor.log_step(steps, loss_value, seq_len)
        
        if steps % 10 == 0:
            monitor.print_step_metrics(metrics)
    
    val_loss = 0.0
    val_steps = 0
    for batch in val_loader:
        batch = {k: jnp.array(v) for k, v in batch.items()}
        
        if num_devices > 1:
            batch = shard_batch(batch)
            loss = eval_step_pmap(state, batch)
            loss_value = float(loss.mean())
        else:
            loss_value = float(compute_loss(state.params, batch))
        
        val_loss += loss_value
        val_steps += 1
    
    print(f"Epoch {epoch+1} | Train Loss: {epoch_loss/steps:.4f} | Val Loss: {val_loss/val_steps:.4f}\n")

# Print resource usage summary
monitor.print_summary()

# Save model
os.makedirs(OUTPUT_DIR, exist_ok=True)

# Get parameters from first device for saving
if num_devices > 1:
    params_save = jax.tree.map(lambda x: x[0], state.params)
else:
    params_save = state.params

with open(f"{OUTPUT_DIR}/params.pkl", "wb") as f:
    pickle.dump(params_save, f)
tokenizer.save_pretrained(OUTPUT_DIR)
print(f"Training completed. Model saved to {OUTPUT_DIR}")

print("\n" + "="*60)
print("JAX PMAP OPTIMIZATION BENEFITS")
print("="*60)
if num_devices > 1:
    print(f"Parallel training across {num_devices} devices")
    print("Automatic gradient synchronization")
    print("Data parallelism with sharded batches")
    print("Linear speedup with multiple devices")
else:
    print("Single device training")
    print("JIT compilation for optimization")
    print("Vectorized operations with vmap")
print("="*60)

**Reference**
- [JAX:Parallel Evaluation in JAX](https://kolonist26-jax-kr.readthedocs.io/en/latest/jax-101/06-parallelism.html)
- [JAX:jax.pmap](https://docs.jax.dev/en/latest/_autosummary/jax.pmap.html)
- [JAX:Introduction to parallel programming](https://docs.jax.dev/en/latest/sharded-computation.html)
- [APXML:Hands-on Practical: Parallel Computation](https://apxml.com/courses/getting-started-with-jax/chapter-5-parallelization-across-devices-pmap/hands-on-parallel-computation)
- [JAX:jax.numpy.vectorize](https://docs.jax.dev/en/latest/_autosummary/jax.numpy.vectorize.html)
- [JAX:Automatic vectorization](https://docs.jax.dev/en/latest/automatic-vectorization.html)
- [APXML:Hands-on Practical: Vectorizing Functions](https://apxml.com/courses/getting-started-with-jax/chapter-4-automatic-vectorization-vmap/hands-on-vectorizing-functions)
- [JAX:Resources and Advanced Guides](https://docs.jax.dev/en/latest/advanced_guides.html)
- [JAX/FLAX:JAX/Flax Key Concepts](https://flax.readthedocs.io/en/latest/key_concepts.html)
- [JAX:Quickstart: How to think in JAX](https://docs.jax.dev/en/latest/notebooks/thinking_in_jax.html)
- [FLAX:Documentation](https://flax.readthedocs.io/en/v0.8.1/)
- [Uvadlc:Tutorial 2 (JAX): Introduction to JAX+Flax](https://uvadlc-notebooks.readthedocs.io/en/latest/tutorial_notebooks/JAX/tutorial2/Introduction_to_JAX.html#)
- [GitHub:JAX example](https://github.com/jax-ml/jax-llm-examples)
- [JAX:How to Scale Your Model](https://jax-ml.github.io/scaling-book/)
- [Medium:Gemma from Scratch: Mastering LLM Implementation with JAX and Flax](https://medium.com/@lucamassaron/gemma-from-scratch-mastering-llm-implementation-with-jax-and-flax-2de783163f46)
- [Medium:Optimizers in JAX and Flax](https://pub.towardsai.net/optimizers-in-jax-and-flax-0f9c50fd517c)

### JAX pjit for Advanced SPMD Parallelism

In JAX, `pjit` (partitioned Just-In-Time compilation) is the primary mechanism for Advanced SPMD (Single Program, Multiple Data) Parallelism. It allows a single piece of code to run across multiple accelerators (GPUs or TPUs) by automatically partitioning both data and model parameters.

While `jax.pjit` was originally a standalone experimental function, its core features have now been integrated into the standard `jax.jit`. In modern JAX, when you use jit with sharding specifications, you are utilizing the "pjit" technology.

**How it Works: The XLA SPMD Partitioner**

Advanced SPMD parallelism via pjit operates through the XLA (Accelerated Linear Algebra) compiler's SPMD Partitioner. Unlike older methods like `pmap`, which simply replicate a function across devices, `pjit` treats the entire cluster of devices as a single "logical" device.
- Logical Mesh: You define a "Mesh" of devices (e.g., a 2x4 grid of 8 GPUs). You then name the axes of this grid, such as data and model.
- PartitionSpec: You describe how each tensor should be distributed across those named axes. For example, a batch of data might be sharded along the data axis, while model weights are sharded along the model axis (Tensor Parallelism).
- Compiler-Inserted Collectives: During compilation, XLA analyzes the operations. If a calculation requires data from another device (like a matrix multiplication where weights are split), XLA automatically inserts the necessary communication primitives—such as AllReduce, AllGather, or ReduceScatter.
- Operation Fusion: Because XLA sees the "whole picture," it can fuse communication with computation, overlapping them to hide latency.

**JAX pjit for Advanced SPMD Parallelism Implementation**

The provided script does not use the pjit keyword directly, but it simulates the Manual SPMD approach that pjit eventually automated. Here is a detailed breakdown of how it achieves Advanced SPMD-style optimization:

**1. Device Mocking and Resource Setup**

The code starts by forcing a CPU environment with `JAX_CPU_NUM_DEVICES = '2'`. This mimics a multi-device system (like 2 GPUs) on a single CPU, allowing the SPMD logic to run even without specialized hardware.

**2. Sharding the Batch (Data Parallelism)**

The shard_batch function manually performs what `pjit` does automatically. It reshapes the input data from a single batch of shape `(8,…)` into `(2,4,…)`. This prepares the data for SPMD, where each of the 2 devices will receive a sub-batch of 4.

**3. `vmap` for Vectorization**

The script uses `jax.vmap(single_example_loss, ...)`. This is a core JAX optimization that transforms a function written for one example into one that handles a batch efficiently. In an SPMD context, vmap handles the "Vertical" parallelism (batching) within each device.

**4. `pmap` for Multi-Device Parallelism**

In the `train_step_fn`, the code uses:
- `jax.pmap`: This maps the training function across the logical devices axis.
- `jax.lax.pmean(grads, axis_name='devices')`: This is a manual collective operation. It ensures that after each device calculates its own gradients, they are averaged across all devices. This "Synchronization" is what pjit handles automatically based on your sharding specs.

**5. JIT Compilation**

The `compute_loss_jit` function is decorated with `@jax.jit`. This triggers the XLA compiler to optimize the mathematical graph, fusing kernels to reduce memory overhead and execution time.

**When to Use It**

Advanced SPMD (`pjit/sharding`) should be used in the following scenarios:
- Large Language Models (LLMs): When the model is too large to fit on a single GPU (Model Parallelism). You can shard the layers or individual weight matrices across multiple devices.
- Large Batch Training: When you want to scale training across hundreds of GPUs (Data Parallelism) without manually managing the communication between them.
- Complex Sharding (Hybrid Parallelism): When you need to combine techniques—for example, sharding the data across one axis of a mesh and the model weights across another.
- Optimization Efficiency: When you need the compiler to automatically overlap "talk" (communication) and "work" (computation) to achieve maximum hardware utilization (FLOPS).

In [ ]:
import os
import sys
import subprocess
import importlib.util

def setup_cpu_environment():
    """Setup environment for CPU-only execution."""
    os.environ['CUDA_VISIBLE_DEVICES'] = '-1'
    os.environ['JAX_PLATFORMS'] = 'cpu'
    os.environ['JAX_CPU_NUM_DEVICES'] = '2'
    os.environ['XLA_FLAGS'] = '--xla_force_host_platform_device_count=2'
    
    # Try to unload any CUDA plugins
    if 'jax_plugins' in sys.modules:
        del sys.modules['jax_plugins']
    
    # Set additional flags to prevent CUDA loading
    os.environ['TF_CPP_MIN_LOG_LEVEL'] = '3'
    os.environ['JAX_PLATFORM_NAME'] = 'cpu'

def check_jax_installation():
    """Check if JAX is properly installed."""
    try:
        import jax
        print(f"JAX version: {jax.__version__}")
        print(f"JAX devices: {jax.devices()}")
        print(f"JAX backend: {jax.devices()[0].platform}")
        return True
    except Exception as e:
        print(f"Error importing JAX: {e}")
        return False

def install_cpu_jax():
    """Install CPU-only JAX if needed."""
    print("\n" + "="*60)
    print("JAX CUDA Plugin Version Mismatch Detected")
    print("="*60)
    print("\nThis script requires CPU-only JAX to run properly.")
    print("You have two options:")
    print("\n1. Install CPU-only JAX in a new virtual environment:")
    print("   python3 -m venv jax-cpu-env")
    print("   source jax-cpu-env/bin/activate")
    print("   pip install --upgrade pip")
    print("   pip install --upgrade 'jax[cpu]'")
    print("   pip install transformers datasets torch flax optax psutil")
    print("\n2. Force reinstall CPU-only JAX in current environment:")
    print("   pip uninstall jax jaxlib -y")
    print("   pip install --upgrade 'jax[cpu]'")
    print("\nAfter installing, run this script again.")
    print("="*60)
    sys.exit(1)

# Setup environment before any imports
setup_cpu_environment()

# Now import modules
try:
    import jax
    import jax.numpy as jnp
    import optax
    import numpy as np
    from transformers import AutoTokenizer
    from datasets import Dataset, DatasetDict
    from torch.utils.data import DataLoader
    from flax.training import train_state
    import flax
    import pickle
    import time
    import psutil
    import warnings
    
    # Check if JAX is using CPU
    if jax.devices()[0].platform != 'cpu':
        print(f"Warning: JAX is using {jax.devices()[0].platform} backend. Forcing CPU...")
        jax.config.update('jax_platform_name', 'cpu')
    
except ImportError as e:
    print(f"Import error: {e}")
    install_cpu_jax()
except Exception as e:
    if 'CUDA' in str(e) or 'plugin' in str(e):
        install_cpu_jax()
    else:
        raise e

warnings.filterwarnings("ignore")

In [ ]:
# Configuration
MODEL_NAME = "google/gemma-3-270m"
OUTPUT_DIR = "./gemma-3-270m-finetuned-qa-jax-pjit"
EMBED_DIM = 256
MAX_LENGTH = 128
NUM_HEADS = 4
NUM_LAYERS = 2
BATCH_SIZE = 8
LEARNING_RATE = 2e-5
WEIGHT_DECAY = 0.01
EPOCHS = 3

# Resource Monitoring Functions
class ResourceMonitor:
    def __init__(self):
        self.process = psutil.Process()
        self.start_time = time.time()
        self.step_times = []
        self.memory_samples = []
        self.gpu_samples = []
        self.losses = []
        self.num_devices = jax.local_device_count()
        self.total_flops = 0
        self.total_gflops = 0
        
    def get_cpu_percent(self):
        return self.process.cpu_percent()
    
    def get_memory_gb(self):
        return self.process.memory_info().rss / (1024 ** 3)
    
    def estimate_flops(self, seq_len):
        per_device_batch = max(1, BATCH_SIZE // self.num_devices)
        attn_flops = 4 * per_device_batch * (seq_len ** 2) * EMBED_DIM * NUM_HEADS * self.num_devices
        mlp_flops = 4 * per_device_batch * seq_len * EMBED_DIM * (4 * EMBED_DIM) * NUM_LAYERS * self.num_devices
        embed_flops = 2 * per_device_batch * seq_len * EMBED_DIM * self.num_devices
        total_flops = (attn_flops + mlp_flops + embed_flops) * 2
        return total_flops
    
    def log_step(self, step, loss, seq_len):
        current_time = time.time()
        self.step_times.append(current_time)
        self.losses.append(loss)
        
        cpu_percent = self.get_cpu_percent()
        memory_gb = self.get_memory_gb()
        self.memory_samples.append(memory_gb)
        
        estimated_flops = self.estimate_flops(seq_len)
        self.total_flops += estimated_flops
        self.total_gflops += estimated_flops / 1e9
        
        step_time = 0
        steps_per_sec = 0
        if len(self.step_times) > 1:
            step_time = (self.step_times[-1] - self.step_times[-2]) * 1000
            steps_per_sec = 1.0 / (self.step_times[-1] - self.step_times[-2])
        
        return {
            'step': step,
            'loss': loss,
            'step_time_ms': step_time,
            'steps_per_second': steps_per_sec,
            'cpu_percent': cpu_percent,
            'memory_gb': memory_gb,
            'estimated_flops': estimated_flops,
            'estimated_gflops': estimated_flops / 1e9,
            'estimated_tflops': estimated_flops / 1e12
        }
    
    def print_step_metrics(self, metrics):
        line = f"  Step {metrics['step']:3d} | Loss: {metrics['loss']:.4f} | "
        line += f"Time: {metrics['step_time_ms']:.1f}ms | "
        line += f"Mem: {metrics['memory_gb']:.2f}GB | "
        line += f"CPU: {metrics['cpu_percent']:.1f}% | "
        line += f"GFLOPS: {metrics['estimated_gflops']:.2f}"
        print(line)
    
    def print_summary(self):
        total_time = time.time() - self.start_time
        avg_step_time = np.mean(np.diff(self.step_times)) * 1000 if len(self.step_times) > 1 else 0
        avg_memory = np.mean(self.memory_samples) if self.memory_samples else 0
        peak_memory = max(self.memory_samples) if self.memory_samples else 0
        avg_loss = np.mean(self.losses) if self.losses else 0
        total_steps = len(self.step_times) - 1
        avg_gflops_per_step = self.total_gflops / total_steps if total_steps > 0 else 0
        gflops_per_second = self.total_gflops / total_time if total_time > 0 else 0
        
        print("\n" + "="*70)
        print("RESOURCE USAGE SUMMARY")
        print("="*70)
        print(f"Number of devices: {self.num_devices}")
        print(f"Total training time: {total_time:.2f} seconds")
        print(f"Average step time: {avg_step_time:.2f} ms")
        print(f"Average steps/second: {1.0/(avg_step_time/1000) if avg_step_time > 0 else 0:.2f}")
        print(f"Average memory usage: {avg_memory:.2f} GB")
        print(f"Peak memory usage: {peak_memory:.2f} GB")
        print(f"Average loss: {avg_loss:.4f}")
        print(f"Total FLOPS: {self.total_flops:.2e}")
        print(f"Total GFLOPS: {self.total_gflops:.2f}")
        print(f"Average GFLOPS per step: {avg_gflops_per_step:.2f}")
        print(f"GFLOPS per second: {gflops_per_second:.2f}")
        print("="*70)

# Tokenization - Get vocab size from tokenizer
print(f"Loading tokenizer: {MODEL_NAME}")
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
tokenizer.pad_token = tokenizer.eos_token
VOCAB_SIZE = len(tokenizer)
print(f"Tokenizer loaded. Vocab size: {VOCAB_SIZE}")

def tokenize_examples(df, max_length=MAX_LENGTH):
    texts = [
        f"<bos>Question: {row['question_title']}\n{row['question_body']}\nAnswer: {row['answer']}<eos>" 
        for row in df.rows(named=True)
    ]
    tokenized = tokenizer(
        texts,
        truncation=True,
        max_length=max_length,
        padding="max_length",
        return_tensors="np"
    )
    tokenized["labels"] = tokenized["input_ids"].copy()
    return tokenized

# Note: train_data and val_data should be provided externally
train_tokenized = tokenize_examples(train_data)
val_tokenized = tokenize_examples(val_data)

dataset_dict = DatasetDict({
    "train": Dataset.from_dict({
        "input_ids": train_tokenized["input_ids"],
        "attention_mask": train_tokenized["attention_mask"],
        "labels": train_tokenized["labels"]
    }),
    "validation": Dataset.from_dict({
        "input_ids": val_tokenized["input_ids"],
        "attention_mask": val_tokenized["attention_mask"],
        "labels": val_tokenized["labels"]
    })
})

def numpy_collate(batch):
    return {k: np.stack([b[k] for b in batch]) for k in batch[0].keys()}

train_loader = DataLoader(
    dataset_dict["train"], 
    batch_size=BATCH_SIZE, 
    shuffle=True, 
    collate_fn=numpy_collate
)
val_loader = DataLoader(
    dataset_dict["validation"], 
    batch_size=BATCH_SIZE, 
    collate_fn=numpy_collate
)

# JAX Model Definition
def init_params(rng):
    keys = jax.random.split(rng, 5)
    
    params = {
        'wte': jax.random.normal(keys[0], (VOCAB_SIZE, EMBED_DIM)) * 0.02,
        'wpe': jax.random.normal(keys[1], (MAX_LENGTH, EMBED_DIM)) * 0.02,
        'layers': [],
        'ln_f_scale': jnp.ones(EMBED_DIM),
        'ln_f_bias': jnp.zeros(EMBED_DIM),
        'lm_head': jax.random.normal(keys[3], (EMBED_DIM, VOCAB_SIZE)) * 0.02,
    }
    
    for i in range(NUM_LAYERS):
        layer_key = jax.random.split(keys[2], NUM_LAYERS)[i]
        layer_keys = jax.random.split(layer_key, 6)
        params['layers'].append({
            'attn_q': jax.random.normal(layer_keys[0], (EMBED_DIM, EMBED_DIM)) * 0.02,
            'attn_k': jax.random.normal(layer_keys[1], (EMBED_DIM, EMBED_DIM)) * 0.02,
            'attn_v': jax.random.normal(layer_keys[2], (EMBED_DIM, EMBED_DIM)) * 0.02,
            'attn_out': jax.random.normal(layer_keys[3], (EMBED_DIM, EMBED_DIM)) * 0.02,
            'ln1_scale': jnp.ones(EMBED_DIM),
            'ln1_bias': jnp.zeros(EMBED_DIM),
            'mlp_in': jax.random.normal(layer_keys[4], (EMBED_DIM, EMBED_DIM * 4)) * 0.02,
            'mlp_out': jax.random.normal(layer_keys[5], (EMBED_DIM * 4, EMBED_DIM)) * 0.02,
            'ln2_scale': jnp.ones(EMBED_DIM),
            'ln2_bias': jnp.zeros(EMBED_DIM),
        })
    
    return params

def layer_norm(x, scale, bias, eps=1e-5):
    mean = jnp.mean(x, axis=-1, keepdims=True)
    var = jnp.var(x, axis=-1, keepdims=True)
    return scale * (x - mean) / jnp.sqrt(var + eps) + bias

def forward(params, input_ids, attention_mask=None):
    batch_size, seq_len = input_ids.shape
    
    x = params['wte'][input_ids] + params['wpe'][:seq_len]
    
    mask = jnp.tril(jnp.ones((seq_len, seq_len))).reshape(1, 1, seq_len, seq_len)
    mask = (mask == 0) * -1e9
    
    if attention_mask is not None:
        attention_mask = attention_mask[:, None, None, :]
        attention_mask = (1.0 - attention_mask) * -1e9
        mask = mask + attention_mask
    
    def reshape_for_heads(x):
        return x.reshape(batch_size, seq_len, NUM_HEADS, -1).transpose(0, 2, 1, 3)
    
    for layer in params['layers']:
        residual = x
        x = layer_norm(x, layer['ln1_scale'], layer['ln1_bias'])
        
        q = reshape_for_heads(jnp.matmul(x, layer['attn_q']))
        k = reshape_for_heads(jnp.matmul(x, layer['attn_k']))
        v = reshape_for_heads(jnp.matmul(x, layer['attn_v']))
        
        scores = jnp.matmul(q, k.transpose(0, 1, 3, 2)) / jnp.sqrt(q.shape[-1])
        scores = scores + mask
        attn_out = jnp.matmul(jax.nn.softmax(scores, axis=-1), v)
        
        attn_out = attn_out.transpose(0, 2, 1, 3).reshape(batch_size, seq_len, -1)
        attn_out = jnp.matmul(attn_out, layer['attn_out'])
        x = residual + attn_out
        
        residual = x
        x = layer_norm(x, layer['ln2_scale'], layer['ln2_bias'])
        x = jnp.matmul(x, layer['mlp_in'])
        x = jax.nn.gelu(x)
        x = jnp.matmul(x, layer['mlp_out'])
        x = residual + x
    
    x = layer_norm(x, params['ln_f_scale'], params['ln_f_bias'])
    return jnp.matmul(x, params['lm_head'])

# Vectorized Loss with vmap
def single_example_loss(params, input_ids, attention_mask, labels):
    logits = forward(params, input_ids[None, :], attention_mask[None, :])[0]
    shift_logits = logits[:-1, :]
    shift_labels = labels[1:]
    loss = optax.softmax_cross_entropy_with_integer_labels(shift_logits, shift_labels)
    mask = (shift_labels != tokenizer.pad_token_id).astype(loss.dtype)
    return (loss * mask).sum() / mask.sum()

batch_loss_vmap = jax.vmap(single_example_loss, in_axes=(None, 0, 0, 0))

@jax.jit
def compute_loss_jit(params, batch):
    return batch_loss_vmap(params, batch['input_ids'], batch['attention_mask'], batch['labels']).mean()

# Combined Optimizations (JIT + vmap + pmap)
num_devices = jax.local_device_count()
print(f"\nNumber of devices: {num_devices}")

def shard_batch(batch):
    batch_size = batch['input_ids'].shape[0]
    per_device = batch_size // num_devices
    if per_device == 0 or num_devices == 1:
        return batch
    return jax.tree.map(
        lambda x: x.reshape(num_devices, per_device, *x.shape[1:]),
        batch
    )

axis_name = 'devices'

def train_step_fn(state, batch):
    loss, grads = jax.value_and_grad(compute_loss_jit)(state.params, batch)
    if num_devices > 1:
        grads = jax.lax.pmean(grads, axis_name=axis_name)
        loss = jax.lax.pmean(loss, axis_name=axis_name)
    state = state.apply_gradients(grads=grads)
    return state, loss

if num_devices > 1:
    train_step = jax.pmap(train_step_fn, axis_name=axis_name)
    eval_step = jax.pmap(lambda state, batch: compute_loss_jit(state.params, batch), axis_name=axis_name)
    parallel_mode = "pmap + vmap + JIT"
else:
    train_step = jax.jit(train_step_fn)
    eval_step = jax.jit(lambda state, batch: compute_loss_jit(state.params, batch))
    parallel_mode = "vmap + JIT"

# Training State
def create_train_state(rng):
    params = init_params(rng)
    tx = optax.adamw(LEARNING_RATE, weight_decay=WEIGHT_DECAY)
    return train_state.TrainState.create(apply_fn=None, params=params, tx=tx)

rng = jax.random.PRNGKey(42)
state = create_train_state(rng)

if num_devices > 1:
    state = flax.jax_utils.replicate(state)

monitor = ResourceMonitor()

print(f"JAX devices: {jax.devices()}")
print(f"JAX backend: {jax.devices()[0].platform}")

# Training Loop
total_params = sum(p.size for p in jax.tree.leaves(state.params))
print(f"\nTotal parameters: {total_params:,}")
print(f"Training with {parallel_mode}...\n")

for epoch in range(EPOCHS):
    epoch_loss = 0.0
    steps = 0
    
    for batch in train_loader:
        batch = {k: jnp.array(v) for k, v in batch.items()}
        
        if num_devices > 1:
            batch = shard_batch(batch)
            state, loss = train_step(state, batch)
            loss_value = float(loss.mean())
        else:
            state, loss = train_step(state, batch)
            loss_value = float(loss)
        
        epoch_loss += loss_value
        steps += 1
        
        seq_len = batch['input_ids'].shape[-1]
        metrics = monitor.log_step(steps, loss_value, seq_len)
        
        if steps % 10 == 0:
            monitor.print_step_metrics(metrics)
    
    val_loss = 0.0
    val_steps = 0
    for batch in val_loader:
        batch = {k: jnp.array(v) for k, v in batch.items()}
        
        if num_devices > 1:
            batch = shard_batch(batch)
            loss = eval_step(state, batch)
            loss_value = float(loss.mean())
        else:
            loss_value = float(eval_step(state, batch))
        
        val_loss += loss_value
        val_steps += 1
    
    print(f"Epoch {epoch+1} | Train Loss: {epoch_loss/steps:.4f} | Val Loss: {val_loss/val_steps:.4f}\n")

monitor.print_summary()

# Save model
os.makedirs(OUTPUT_DIR, exist_ok=True)

if num_devices > 1:
    params_save = jax.tree.map(lambda x: x[0], state.params)
else:
    params_save = state.params

with open(f"{OUTPUT_DIR}/params.pkl", "wb") as f:
    pickle.dump(params_save, f)
tokenizer.save_pretrained(OUTPUT_DIR)
print(f"Training completed. Model saved to {OUTPUT_DIR}")

print("\n" + "="*60)
print("COMBINED JAX OPTIMIZATIONS BENEFITS")
print("="*60)
print("JIT Compilation: Operation fusion and XLA optimization")
print("vmap: Automatic vectorization of single-example functions")
if num_devices > 1:
    print(f"pmap: Parallel training across {num_devices} devices")
    print("Automatic gradient synchronization")
print("="*60)

**Reference**
- [JAX:jax.experimental.custom_partitioning module](https://docs.jax.dev/en/latest/jax.experimental.custom_partitioning.html)
- [JAX:Parallel Evaluation in JAX](https://kolonist26-jax-kr.readthedocs.io/en/latest/jax-101/06-parallelism.html)
- [JAX:shmap (shard_map) for simple per-device code](https://docs.jax.dev/en/latest/jep/14273-shard-map.html)
- [JAX:Introduction to parallel programming](https://docs.jax.dev/en/latest/sharded-computation.html)
- [FLAX:Scale up Flax Modules on multiple devices with pjit](https://flax.readthedocs.io/en/v0.6.10/guides/flax_on_pjit.html)
- [JAX:Parallel Evaluation in JAX](https://kolonist26-jax-kr.readthedocs.io/en/latest/jax-101/06-parallelism.html)
- [JAX:jax.pmap](https://docs.jax.dev/en/latest/_autosummary/jax.pmap.html)
- [JAX:Introduction to parallel programming](https://docs.jax.dev/en/latest/sharded-computation.html)
- [APXML:Hands-on Practical: Parallel Computation](https://apxml.com/courses/getting-started-with-jax/chapter-5-parallelization-across-devices-pmap/hands-on-parallel-computation)
- [JAX:jax.numpy.vectorize](https://docs.jax.dev/en/latest/_autosummary/jax.numpy.vectorize.html)
- [JAX:Automatic vectorization](https://docs.jax.dev/en/latest/automatic-vectorization.html)
- [APXML:Hands-on Practical: Vectorizing Functions](https://apxml.com/courses/getting-started-with-jax/chapter-4-automatic-vectorization-vmap/hands-on-vectorizing-functions)
- [JAX:Resources and Advanced Guides](https://docs.jax.dev/en/latest/advanced_guides.html)
- [JAX/FLAX:JAX/Flax Key Concepts](https://flax.readthedocs.io/en/latest/key_concepts.html)
- [JAX:Quickstart: How to think in JAX](https://docs.jax.dev/en/latest/notebooks/thinking_in_jax.html)
- [FLAX:Documentation](https://flax.readthedocs.io/en/v0.8.1/)
- [Uvadlc:Tutorial 2 (JAX): Introduction to JAX+Flax](https://uvadlc-notebooks.readthedocs.io/en/latest/tutorial_notebooks/JAX/tutorial2/Introduction_to_JAX.html#)
- [GitHub:JAX example](https://github.com/jax-ml/jax-llm-examples)
- [JAX:How to Scale Your Model](https://jax-ml.github.io/scaling-book/)
- [Medium:Gemma from Scratch: Mastering LLM Implementation with JAX and Flax](https://medium.com/@lucamassaron/gemma-from-scratch-mastering-llm-implementation-with-jax-and-flax-2de783163f46)
- [Medium:Optimizers in JAX and Flax](https://pub.towardsai.net/optimizers-in-jax-and-flax-0f9c50fd517c)

### JAX vmap and pmap Combination

The combination of vmap (Vectorized Map) and pmap (Parallel Map) is a distinctive feature of JAX designed to maximize throughput by exploiting two different levels of hardware parallelism: Single-Instruction Multiple-Data (SIMD) on a single chip and Single-Program Multiple-Data (SPMD) across multiple devices (GPUs or TPUs).

**Detailed Mechanics of the Combination**

- `vmap` (Auto-Vectorization): Operates at the instruction level. It transforms a function written for a single data point into one that operates on a batch. Instead of a loop, JAX pushes the batch dimension down into the mathematical primitives (like matrix multiplication). This utilizes the hardware's vector units (SIMD) to process multiple numbers in one cycle on a single device.
- `pmap` (Device Parallelism): Operates at the device level. It replicates the compiled XLA computation across multiple hardware cores (e.g., 8 GPUs). It handles the communication between these devices, such as synchronized gradient updates.
- The Combination: When combined, pmap splits a massive global batch into smaller "shards," and vmap handles the batching within each of those shards on the local device. This allows for a hierarchical scaling strategy:
    - Macro-scale: `pmap` scales across devices (Data Parallelism).
    - Micro-scale: `vmap` scales within the device (Vectorization).

**JAX (vmap and pmap) Implementation**

The provided script implements a nested optimization pipeline. It starts with a function designed for a single training example and scales it up to a multi-GPU environment.

**1. Vectorization Layer (`vmap`)**

In the section 3. Loss Functions with `vmap`, the `single_example_loss` function is written to calculate the loss for exactly one input sequence.

    batch_loss = jax.vmap(single_example_loss, in_axes=(None, 0, 0, 0))

This line automatically transforms the scalar loss function into a batched one. The `in_axes` argument tells JAX to keep the parameters (params) constant for the whole batch while mapping over the first dimension (index 0) of the input IDs, masks, and labels. This ensures the GPU processes the batch using highly optimized vectorized kernels.

**2. Sharding and Parallelization Layer (`pmap`)**

In the section 4. Multi-device Parallelization, the script determines the number of available hardware devices.

    train_step = jax.pmap(train_step_fn, axis_name='devices')

The `train_step_fn` (which calls the vmap-ed loss) is wrapped in `pmap`. This replicates the entire training logic across every GPU. To make this work, the code uses shard_batch to reshape the input data into a shape of `(num_devices, local_batch_size, sequence_length)`.

**3. Collective Communication**

Inside the `train_step_fn`, the code handles the synchronization of the parallel processes:

    grads = jax.lax.pmean(grads, axis_name='devices')

Because each GPU calculates gradients based only on its local shard of data, `jax.lax.pmean` (parallel mean) is used to communicate across all devices. This "All-Reduce" operation ensures that every GPU updates its local copy of the weights using the average gradient of the entire global batch, maintaining model consistency across the cluster.

**When to Use It**

Use `vmap + pmap` when:
- Multi-GPU/TPU Environments: Whenever there is more than one accelerator available. pmap is the primary way to utilize all devices.
- Large-Batch Training: When the total batch size is large enough to be divided across chips, and the local per-chip batch is large enough to benefit from vectorization.
- Custom Training Loops: JAX is ideal when standard frameworks like PyTorch or TensorFlow are too restrictive for experimental model architectures or specialized parallelization strategies.
- SIMD Efficiency: When there is a need to ensure that the hardware's internal vector registers are fully utilized (via `vmap`) while simultaneously scaling horizontally (via `pmap`).

Avoid this combination when:
- Single-Device Hardware: If only one GPU is present, pmap adds unnecessary complexity and overhead; a simple `jax.jit + vmap` is sufficient.
- Very Small Batch Sizes: If the global batch size is smaller than the number of devices, some devices will remain idle, making the parallelization inefficient.
- Using GSPMD/Automatic Sharding: Modern JAX (and Gemma-specific libraries) often move toward `jax.jit` with `sharding` constraints, which can be more flexible than pmap for complex model-parallelism (Tensor Parallelism).

In [ ]:
import os
import jax
import jax.numpy as jnp
import optax
import numpy as np
from transformers import AutoTokenizer
from datasets import Dataset, DatasetDict
from torch.utils.data import DataLoader
from flax.training import train_state
import flax
import pickle
import time
import psutil
import subprocess

In [ ]:
# Configuration
MODEL_NAME = "google/gemma-3-270m"
OUTPUT_DIR = "./gemma-3-270m-finetuned-qa-jax-optimized"
EMBED_DIM = 256
MAX_LENGTH = 128
NUM_HEADS = 4
NUM_LAYERS = 2
BATCH_SIZE = 8
LEARNING_RATE = 2e-5
WEIGHT_DECAY = 0.01
EPOCHS = 3

# Resource Monitoring Functions
class ResourceMonitor:
    def __init__(self):
        self.process = psutil.Process()
        self.start_time = time.time()
        self.step_times = []
        self.memory_samples = []
        self.gpu_samples = []
        self.losses = []
        self.num_devices = jax.local_device_count()
        self.total_flops = 0
        self.total_gflops = 0
        
    def get_cpu_percent(self):
        return self.process.cpu_percent()
    
    def get_memory_gb(self):
        return self.process.memory_info().rss / (1024 ** 3)
    
    def get_gpu_info(self):
        if jax.devices()[0].platform == 'gpu':
            try:
                result = subprocess.run(
                    ['nvidia-smi', '--query-gpu=index,name,memory.used,memory.total,utilization.gpu', 
                     '--format=csv,noheader,nounits'],
                    capture_output=True, text=True, check=False
                )
                if result.returncode == 0 and result.stdout.strip():
                    gpus = []
                    for line in result.stdout.strip().split('\n'):
                        if line:
                            parts = [x.strip() for x in line.split(',')]
                            if len(parts) >= 5:
                                gpus.append({
                                    'index': parts[0],
                                    'name': parts[1],
                                    'memory_used_mb': float(parts[2]),
                                    'memory_total_mb': float(parts[3]),
                                    'utilization': float(parts[4])
                                })
                    return gpus
            except:
                pass
        return None
    
    def estimate_flops(self, seq_len, batch_size, embed_dim, num_heads, num_layers, num_devices):
        per_device_batch = max(1, batch_size // num_devices)
        attn_flops = 4 * per_device_batch * (seq_len ** 2) * embed_dim * num_heads * num_devices
        mlp_flops = 4 * per_device_batch * seq_len * embed_dim * (4 * embed_dim) * num_layers * num_devices
        embed_flops = 2 * per_device_batch * seq_len * embed_dim * num_devices
        total_flops = (attn_flops + mlp_flops + embed_flops) * 2
        return total_flops
    
    def log_step(self, step, loss, seq_len):
        current_time = time.time()
        self.step_times.append(current_time)
        self.losses.append(loss)
        
        cpu_percent = self.get_cpu_percent()
        memory_gb = self.get_memory_gb()
        self.memory_samples.append(memory_gb)
        
        gpu_info = self.get_gpu_info()
        if gpu_info:
            self.gpu_samples.append(gpu_info)
        
        estimated_flops = self.estimate_flops(seq_len, BATCH_SIZE, EMBED_DIM, NUM_HEADS, NUM_LAYERS, self.num_devices)
        self.total_flops += estimated_flops
        self.total_gflops += estimated_flops / 1e9
        
        step_time = 0
        steps_per_sec = 0
        if len(self.step_times) > 1:
            step_time = (self.step_times[-1] - self.step_times[-2]) * 1000
            steps_per_sec = 1.0 / (self.step_times[-1] - self.step_times[-2])
        
        return {
            'step': step,
            'loss': loss,
            'step_time_ms': step_time,
            'steps_per_second': steps_per_sec,
            'cpu_percent': cpu_percent,
            'memory_gb': memory_gb,
            'estimated_flops': estimated_flops,
            'estimated_gflops': estimated_flops / 1e9,
            'estimated_tflops': estimated_flops / 1e12,
            'gpu_info': gpu_info
        }
    
    def print_step_metrics(self, metrics):
        line = f"  Step {metrics['step']:3d} | Loss: {metrics['loss']:.4f} | "
        line += f"Time: {metrics['step_time_ms']:.1f}ms | "
        line += f"Mem: {metrics['memory_gb']:.2f}GB | "
        line += f"CPU: {metrics['cpu_percent']:.1f}% | "
        line += f"GFLOPS: {metrics['estimated_gflops']:.2f}"
        print(line)
        
        if metrics['gpu_info']:
            for gpu in metrics['gpu_info']:
                print(f"        GPU {gpu['index']}: {gpu['name']} | "
                      f"Util: {gpu['utilization']:.1f}% | "
                      f"Mem: {gpu['memory_used_mb']/1024:.2f}/{gpu['memory_total_mb']/1024:.2f}GB")
    
    def print_summary(self):
        total_time = time.time() - self.start_time
        avg_step_time = np.mean(np.diff(self.step_times)) * 1000 if len(self.step_times) > 1 else 0
        avg_memory = np.mean(self.memory_samples) if self.memory_samples else 0
        peak_memory = max(self.memory_samples) if self.memory_samples else 0
        avg_loss = np.mean(self.losses) if self.losses else 0
        total_steps = len(self.step_times) - 1
        avg_gflops_per_step = self.total_gflops / total_steps if total_steps > 0 else 0
        gflops_per_second = self.total_gflops / total_time if total_time > 0 else 0
        
        print("\n" + "="*70)
        print("RESOURCE USAGE SUMMARY")
        print("="*70)
        print(f"Number of devices: {self.num_devices}")
        print(f"Total training time: {total_time:.2f} seconds")
        print(f"Average step time: {avg_step_time:.2f} ms")
        print(f"Average steps/second: {1.0/(avg_step_time/1000) if avg_step_time > 0 else 0:.2f}")
        print(f"Average memory usage: {avg_memory:.2f} GB")
        print(f"Peak memory usage: {peak_memory:.2f} GB")
        print(f"Average loss: {avg_loss:.4f}")
        print(f"Total FLOPS: {self.total_flops:.2e}")
        print(f"Total GFLOPS: {self.total_gflops:.2f}")
        print(f"Average GFLOPS per step: {avg_gflops_per_step:.2f}")
        print(f"GFLOPS per second: {gflops_per_second:.2f}")
        
        if self.gpu_samples:
            avg_gpu_util = np.mean([g[0]['utilization'] for g in self.gpu_samples if g]) if self.gpu_samples else 0
            avg_gpu_mem = np.mean([g[0]['memory_used_mb']/1024 for g in self.gpu_samples if g]) if self.gpu_samples else 0
            print(f"Average GPU utilization: {avg_gpu_util:.1f}%")
            print(f"Average GPU memory: {avg_gpu_mem:.2f} GB")
        print("="*70)

# Tokenization - Get vocab size from tokenizer
print(f"Loading tokenizer: {MODEL_NAME}")
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
tokenizer.pad_token = tokenizer.eos_token
VOCAB_SIZE = len(tokenizer)
print(f"Tokenizer loaded. Vocab size: {VOCAB_SIZE}")

def tokenize_examples(df, max_length=MAX_LENGTH):
    texts = [
        f"<bos>Question: {row['question_title']}\n{row['question_body']}\nAnswer: {row['answer']}<eos>" 
        for row in df.rows(named=True)
    ]
    tokenized = tokenizer(
        texts,
        truncation=True,
        max_length=max_length,
        padding="max_length",
        return_tensors="np"
    )
    tokenized["labels"] = tokenized["input_ids"].copy()
    return tokenized

train_tokenized = tokenize_examples(train_data)
val_tokenized = tokenize_examples(val_data)

dataset_dict = DatasetDict({
    "train": Dataset.from_dict({
        "input_ids": train_tokenized["input_ids"],
        "attention_mask": train_tokenized["attention_mask"],
        "labels": train_tokenized["labels"]
    }),
    "validation": Dataset.from_dict({
        "input_ids": val_tokenized["input_ids"],
        "attention_mask": val_tokenized["attention_mask"],
        "labels": val_tokenized["labels"]
    })
})

def numpy_collate(batch):
    return {k: np.stack([b[k] for b in batch]) for k in batch[0].keys()}

train_loader = DataLoader(
    dataset_dict["train"], 
    batch_size=BATCH_SIZE, 
    shuffle=True, 
    collate_fn=numpy_collate
)
val_loader = DataLoader(
    dataset_dict["validation"], 
    batch_size=BATCH_SIZE, 
    collate_fn=numpy_collate
)

# JAX Model Definition
def init_params(rng):
    keys = jax.random.split(rng, 5)
    
    params = {
        'wte': jax.random.normal(keys[0], (VOCAB_SIZE, EMBED_DIM)) * 0.02,
        'wpe': jax.random.normal(keys[1], (MAX_LENGTH, EMBED_DIM)) * 0.02,
        'layers': [],
        'ln_f_scale': jnp.ones(EMBED_DIM),
        'ln_f_bias': jnp.zeros(EMBED_DIM),
        'lm_head': jax.random.normal(keys[3], (EMBED_DIM, VOCAB_SIZE)) * 0.02,
    }
    
    for i in range(NUM_LAYERS):
        layer_key = jax.random.split(keys[2], NUM_LAYERS)[i]
        layer_keys = jax.random.split(layer_key, 6)
        params['layers'].append({
            'attn_q': jax.random.normal(layer_keys[0], (EMBED_DIM, EMBED_DIM)) * 0.02,
            'attn_k': jax.random.normal(layer_keys[1], (EMBED_DIM, EMBED_DIM)) * 0.02,
            'attn_v': jax.random.normal(layer_keys[2], (EMBED_DIM, EMBED_DIM)) * 0.02,
            'attn_out': jax.random.normal(layer_keys[3], (EMBED_DIM, EMBED_DIM)) * 0.02,
            'ln1_scale': jnp.ones(EMBED_DIM),
            'ln1_bias': jnp.zeros(EMBED_DIM),
            'mlp_in': jax.random.normal(layer_keys[4], (EMBED_DIM, EMBED_DIM * 4)) * 0.02,
            'mlp_out': jax.random.normal(layer_keys[5], (EMBED_DIM * 4, EMBED_DIM)) * 0.02,
            'ln2_scale': jnp.ones(EMBED_DIM),
            'ln2_bias': jnp.zeros(EMBED_DIM),
        })
    
    return params

def layer_norm(x, scale, bias, eps=1e-5):
    mean = jnp.mean(x, axis=-1, keepdims=True)
    var = jnp.var(x, axis=-1, keepdims=True)
    return scale * (x - mean) / jnp.sqrt(var + eps) + bias

def forward(params, input_ids, attention_mask=None):
    batch_size, seq_len = input_ids.shape
    
    x = params['wte'][input_ids] + params['wpe'][:seq_len]
    
    mask = jnp.tril(jnp.ones((seq_len, seq_len))).reshape(1, 1, seq_len, seq_len)
    mask = (mask == 0) * -1e9
    
    if attention_mask is not None:
        attention_mask = attention_mask[:, None, None, :]
        attention_mask = (1.0 - attention_mask) * -1e9
        mask = mask + attention_mask
    
    def reshape_for_heads(x):
        return x.reshape(batch_size, seq_len, NUM_HEADS, -1).transpose(0, 2, 1, 3)
    
    for layer in params['layers']:
        residual = x
        x = layer_norm(x, layer['ln1_scale'], layer['ln1_bias'])
        
        q = reshape_for_heads(jnp.matmul(x, layer['attn_q']))
        k = reshape_for_heads(jnp.matmul(x, layer['attn_k']))
        v = reshape_for_heads(jnp.matmul(x, layer['attn_v']))
        
        scores = jnp.matmul(q, k.transpose(0, 1, 3, 2)) / jnp.sqrt(q.shape[-1])
        scores = scores + mask
        attn_out = jnp.matmul(jax.nn.softmax(scores, axis=-1), v)
        
        attn_out = attn_out.transpose(0, 2, 1, 3).reshape(batch_size, seq_len, -1)
        attn_out = jnp.matmul(attn_out, layer['attn_out'])
        x = residual + attn_out
        
        residual = x
        x = layer_norm(x, layer['ln2_scale'], layer['ln2_bias'])
        x = jnp.matmul(x, layer['mlp_in'])
        x = jax.nn.gelu(x)
        x = jnp.matmul(x, layer['mlp_out'])
        x = residual + x
    
    x = layer_norm(x, params['ln_f_scale'], params['ln_f_bias'])
    return jnp.matmul(x, params['lm_head'])

# Loss Functions with vmap
def single_example_loss(params, input_ids, attention_mask, labels):
    logits = forward(params, input_ids[None, :], attention_mask[None, :])[0]
    shift_logits = logits[:-1, :]
    shift_labels = labels[1:]
    loss = optax.softmax_cross_entropy_with_integer_labels(shift_logits, shift_labels)
    mask = (shift_labels != tokenizer.pad_token_id).astype(loss.dtype)
    return (loss * mask).sum() / mask.sum()

batch_loss = jax.vmap(single_example_loss, in_axes=(None, 0, 0, 0))

@jax.jit
def compute_loss(params, batch):
    return batch_loss(params, batch['input_ids'], batch['attention_mask'], batch['labels']).mean()

# Multi-device Parallelization
num_devices = jax.local_device_count()
print(f"\nNumber of devices: {num_devices}")

def shard_batch(batch):
    batch_size = batch['input_ids'].shape[0]
    per_device = batch_size // num_devices
    if per_device == 0 or num_devices == 1:
        return batch
    return jax.tree.map(
        lambda x: x.reshape(num_devices, per_device, *x.shape[1:]),
        batch
    )

axis_name = 'devices'

def train_step_fn(state, batch):
    loss, grads = jax.value_and_grad(compute_loss)(state.params, batch)
    if num_devices > 1:
        grads = jax.lax.pmean(grads, axis_name=axis_name)
        loss = jax.lax.pmean(loss, axis_name=axis_name)
    state = state.apply_gradients(grads=grads)
    return state, loss

if num_devices > 1:
    train_step = jax.pmap(train_step_fn, axis_name=axis_name)
    eval_step = jax.pmap(lambda state, batch: compute_loss(state.params, batch), axis_name=axis_name)
else:
    train_step = jax.jit(train_step_fn)
    eval_step = jax.jit(lambda state, batch: compute_loss(state.params, batch))

# Training State
def create_train_state(rng):
    params = init_params(rng)
    tx = optax.adamw(LEARNING_RATE, weight_decay=WEIGHT_DECAY)
    return train_state.TrainState.create(apply_fn=None, params=params, tx=tx)

# NumPy 2.0 compatibility - use PRNGKey
rng = jax.random.PRNGKey(42)
state = create_train_state(rng)

if num_devices > 1:
    state = flax.jax_utils.replicate(state)

# Initialize resource monitor
monitor = ResourceMonitor()

# Print device information
print(f"JAX devices: {jax.devices()}")
print(f"JAX backend: {jax.devices()[0].platform}")

# Training Loop
total_params = sum(p.size for p in jax.tree.leaves(state.params))
print(f"\nTotal parameters: {total_params:,}")
print(f"Training with {'pmap + vmap + JIT' if num_devices > 1 else 'vmap + JIT'} optimization...\n")

for epoch in range(EPOCHS):
    epoch_loss = 0.0
    steps = 0
    
    for batch in train_loader:
        batch = {k: jnp.array(v) for k, v in batch.items()}
        
        if num_devices > 1:
            batch = shard_batch(batch)
            state, loss = train_step(state, batch)
            loss_value = float(loss.mean())
        else:
            state, loss = train_step(state, batch)
            loss_value = float(loss)
        
        epoch_loss += loss_value
        steps += 1
        
        seq_len = batch['input_ids'].shape[-1]
        metrics = monitor.log_step(steps, loss_value, seq_len)
        
        if steps % 10 == 0:
            monitor.print_step_metrics(metrics)
    
    val_loss = 0.0
    val_steps = 0
    for batch in val_loader:
        batch = {k: jnp.array(v) for k, v in batch.items()}
        
        if num_devices > 1:
            batch = shard_batch(batch)
            loss = eval_step(state, batch)
            loss_value = float(loss.mean())
        else:
            loss_value = float(eval_step(state, batch))
        
        val_loss += loss_value
        val_steps += 1
    
    print(f"Epoch {epoch+1} | Train Loss: {epoch_loss/steps:.4f} | Val Loss: {val_loss/val_steps:.4f}\n")

# Print resource usage summary
monitor.print_summary()

# Save model
os.makedirs(OUTPUT_DIR, exist_ok=True)

if num_devices > 1:
    params_save = jax.tree.map(lambda x: x[0], state.params)
else:
    params_save = state.params

with open(f"{OUTPUT_DIR}/params.pkl", "wb") as f:
    pickle.dump(params_save, f)
tokenizer.save_pretrained(OUTPUT_DIR)
print(f"Training completed. Model saved to {OUTPUT_DIR}")

print("\n" + "="*60)
print("JAX OPTIMIZATION BENEFITS")
print("="*60)
print("JIT Compilation: Operation fusion and XLA optimization")
print("vmap: Automatic vectorization of single-example functions")
if num_devices > 1:
    print(f"pmap: Parallel training across {num_devices} devices")
    print("Automatic gradient synchronization")
print("="*60)

Loading tokenizer: google/gemma-3-270m
Tokenizer loaded. Vocab size: 262145

Number of devices: 1
JAX devices: [CpuDevice(id=0)]
JAX backend: cpu

Total parameters: 135,826,432
Training with vmap + JIT optimization...

  Step  10 | Loss: 12.3540 | Time: 8479.4ms | Mem: 11.95GB | CPU: 295.5% | GFLOPS: 5.37
Epoch 1 | Train Loss: 12.3646 | Val Loss: 12.2026

**Reference**
- [JAX:jax.numpy.vectorize](https://docs.jax.dev/en/latest/_autosummary/jax.numpy.vectorize.html)
- [JAX:Automatic vectorization](https://docs.jax.dev/en/latest/automatic-vectorization.html)
- [APXML:Hands-on Practical: Vectorizing Functions](https://apxml.com/courses/getting-started-with-jax/chapter-4-automatic-vectorization-vmap/hands-on-vectorizing-functions)
- [JAX:Parallel Evaluation in JAX](https://kolonist26-jax-kr.readthedocs.io/en/latest/jax-101/06-parallelism.html)
- [JAX:jax.pmap](https://docs.jax.dev/en/latest/_autosummary/jax.pmap.html)
- [JAX:Introduction to parallel programming](https://docs.jax.dev/en/latest/sharded-computation.html)
- [APXML:Hands-on Practical: Parallel Computation](https://apxml.com/courses/getting-started-with-jax/chapter-5-parallelization-across-devices-pmap/hands-on-parallel-computation)
- [JAX:jax.numpy.vectorize](https://docs.jax.dev/en/latest/_autosummary/jax.numpy.vectorize.html)
- [JAX:Automatic vectorization](https://docs.jax.dev/en/latest/automatic-vectorization.html)
- [APXML:Hands-on Practical: Vectorizing Functions](https://apxml.com/courses/getting-started-with-jax/chapter-4-automatic-vectorization-vmap/hands-on-vectorizing-functions)
- [JAX:Resources and Advanced Guides](https://docs.jax.dev/en/latest/advanced_guides.html)
- [JAX/FLAX:JAX/Flax Key Concepts](https://flax.readthedocs.io/en/latest/key_concepts.html)
- [JAX:Quickstart: How to think in JAX](https://docs.jax.dev/en/latest/notebooks/thinking_in_jax.html)
- [FLAX:Documentation](https://flax.readthedocs.io/en/v0.8.1/)
- [Uvadlc:Tutorial 2 (JAX): Introduction to JAX+Flax](https://uvadlc-notebooks.readthedocs.io/en/latest/tutorial_notebooks/JAX/tutorial2/Introduction_to_JAX.html#)
- [GitHub:JAX example](https://github.com/jax-ml/jax-llm-examples)
- [JAX:How to Scale Your Model](https://jax-ml.github.io/scaling-book/)
- [Medium:Gemma from Scratch: Mastering LLM Implementation with JAX and Flax](https://medium.com/@lucamassaron/gemma-from-scratch-mastering-llm-implementation-with-jax-and-flax-2de783163f46)
- [Medium:Optimizers in JAX and Flax](https://pub.towardsai.net/optimizers-in-jax-and-flax-0f9c50fd517c)

### Combined JAX Optimizations (JIT + vmap + pmap)

Combined JAX optimizations represent the ultimate performance stack for Large Language Models. This approach nests three distinct levels of transformation to maximize hardware utilization across both a single chip and multiple devices.
- `vmap` (Vectorization): Operates at the mathematical level. It transforms a function that handles one example into one that handles a local batch, turning loops into efficient matrix-matrix operations.
- `pmap` (Parallelization): Operates at the hardware level. It distributes these local batches across multiple GPUs or TPU cores.
- `JIT` (Just-In-Time Compilation): Operates at the execution level. It uses the XLA compiler to fuse operations, remove intermediate memory overhead, and optimize the final binary for the specific chip architecture.

**How Combined Optimization Works**

The hierarchy works like a "nesting doll" of transformations:
- The Core: A function is written to calculate the loss for exactly one sequence.
- Inner Layer (`vmap`): This core function is wrapped in vmap. JAX automatically adds a batch dimension. This ensures the model uses the GPU's tensor cores effectively for high-throughput linear algebra.
- Intermediate Layer (`JIT`): The batched function is wrapped in jit. XLA looks at the sequence of operations (LayerNorm -> Attention -> MLP) and "fuses" them into a single kernel to prevent the GPU from constantly reading and writing back to its global memory.
- Outer Layer (`pmap`): The JIT-compiled, batched function is wrapped in pmap. This replicates the optimized kernel across N devices and shards the total batch so that each device computes its share in parallel.

**Combined JAX Optimizations (JIT + vmap + pmap) Implementation**

The script implements this hierarchy to fine-tune a Gemma-style model:

**1. The Vectorized Core (`vmap + JIT`)**

    batch_loss_vmap = jax.vmap(single_example_loss, in_axes=(None, 0, 0, 0))

    @jax.jit
    def compute_loss_jit(params, batch):
        return batch_loss_vmap(params, batch['input_ids'], ...).mean()

Here, `vmap` handles the conversion from a single sequence to a batch. The `@jax.jit` decorator ensures that the resulting batched calculation is compiled into a high-performance XLA executable. This is the "Local Device Optimization."

**2. The Parallel Wrapper (`pmap`)**

    if num_devices > 1:
        train_step = jax.pmap(train_step_fn, axis_name=axis_name)
        
The `train_step_fn` calls the JIT-compiled loss. By wrapping this in `pmap`, the code ensures that if 4 GPUs are present, the compiled training logic is executed on all 4 simultaneously.

**3. Collective Communication and Sharding**

- `shard_batch`: This function reshapes the data into a (`Devices,LocalBatch,SeqLen`) tensor. This is the entry point for pmap.
- `jax.lax.pmean`: Inside the training step, after `value_and_grad` calculates gradients locally, pmean synchronizes them across all devices. This is the bridge between parallel devices.
- `flax.jax_utils.replicate`: This ensures that every device starts with the exact same model parameters before the parallel loop begins.

**When to Use Combined Optimizations**

This strategy is the industry standard for LLM training and should be used when:
- Multi-GPU/TPU Environments: Whenever more than one accelerator is available, `pmap` is required to utilize them, while `vmap` and `JIT` ensure each individual accelerator is running at maximum efficiency.
- High-Throughput Training: When the goal is to maximize "Tokens Per Second." Operations fusion from JIT and vectorization from `vmap` are critical to keep the GPU cores saturated.
- Custom Transformer Architectures: If implementing a new type of attention mechanism, writing it for one example (`vmap`) and letting JAX handle the batching and multi-device distribution (`pmap`) reduces code complexity and bugs.
- Large-Scale Fine-Tuning: For models like Gemma-3, where the memory footprint is significant, distributing the data load across devices while maintaining optimized local kernels is the only way to achieve feasible training times.

In [ ]:
# Install CPU-only JAX
pip install --upgrade pip
pip install --upgrade "jax[cpu]"
pip install transformers datasets torch flax optax psutil
pip install --upgrade jax jaxlib jax-cuda12-plugin
%%capture
!pip install optax jax
%%capture
!pip install --upgrade numpy>=2.0
!pip install "jax[cpu]<0.4.30"   # adjust version; try 0.4.20–0.4.26 range
# or with CUDA
!pip install --upgrade "jax[cuda12_pip]<0.4.30"

import jax
import jax.numpy as jnp
import optax
import numpy as np
from transformers import AutoTokenizer
from datasets import Dataset, DatasetDict
from torch.utils.data import DataLoader
from flax.training import train_state
import flax
import pickle
import os
import time
import psutil
import subprocess

In [ ]:
# Configuration
MODEL_NAME = "google/gemma-3-270m"
OUTPUT_DIR = "./gemma-3-270m-finetuned-qa-jax-combined"
EMBED_DIM = 256
MAX_LENGTH = 128
NUM_HEADS = 4
NUM_LAYERS = 2
BATCH_SIZE = 8
LEARNING_RATE = 2e-5
WEIGHT_DECAY = 0.01
EPOCHS = 3

# Resource Monitoring Functions
class ResourceMonitor:
    def __init__(self):
        self.process = psutil.Process()
        self.start_time = time.time()
        self.step_times = []
        self.memory_samples = []
        self.gpu_samples = []
        self.losses = []
        self.num_devices = jax.local_device_count()
        self.total_flops = 0
        self.total_gflops = 0
        
    def get_cpu_percent(self):
        return self.process.cpu_percent()
    
    def get_memory_gb(self):
        return self.process.memory_info().rss / (1024 ** 3)
    
    def get_gpu_info(self):
        if jax.devices()[0].platform == 'gpu':
            try:
                result = subprocess.run(
                    ['nvidia-smi', '--query-gpu=index,name,memory.used,memory.total,utilization.gpu', 
                     '--format=csv,noheader,nounits'],
                    capture_output=True, text=True, check=False
                )
                if result.returncode == 0 and result.stdout.strip():
                    gpus = []
                    for line in result.stdout.strip().split('\n'):
                        if line:
                            parts = [x.strip() for x in line.split(',')]
                            if len(parts) >= 5:
                                gpus.append({
                                    'index': parts[0],
                                    'name': parts[1],
                                    'memory_used_mb': float(parts[2]),
                                    'memory_total_mb': float(parts[3]),
                                    'utilization': float(parts[4])
                                })
                    return gpus
            except:
                pass
        return None
    
    def estimate_flops(self, seq_len):
        per_device_batch = max(1, BATCH_SIZE // self.num_devices)
        attn_flops = 4 * per_device_batch * (seq_len ** 2) * EMBED_DIM * NUM_HEADS * self.num_devices
        mlp_flops = 4 * per_device_batch * seq_len * EMBED_DIM * (4 * EMBED_DIM) * NUM_LAYERS * self.num_devices
        embed_flops = 2 * per_device_batch * seq_len * EMBED_DIM * self.num_devices
        total_flops = (attn_flops + mlp_flops + embed_flops) * 2
        return total_flops
    
    def log_step(self, step, loss, seq_len):
        current_time = time.time()
        self.step_times.append(current_time)
        self.losses.append(loss)
        
        cpu_percent = self.get_cpu_percent()
        memory_gb = self.get_memory_gb()
        self.memory_samples.append(memory_gb)
        
        gpu_info = self.get_gpu_info()
        if gpu_info:
            self.gpu_samples.append(gpu_info)
        
        estimated_flops = self.estimate_flops(seq_len)
        self.total_flops += estimated_flops
        self.total_gflops += estimated_flops / 1e9
        
        step_time = 0
        steps_per_sec = 0
        if len(self.step_times) > 1:
            step_time = (self.step_times[-1] - self.step_times[-2]) * 1000
            steps_per_sec = 1.0 / (self.step_times[-1] - self.step_times[-2])
        
        return {
            'step': step,
            'loss': loss,
            'step_time_ms': step_time,
            'steps_per_second': steps_per_sec,
            'cpu_percent': cpu_percent,
            'memory_gb': memory_gb,
            'estimated_flops': estimated_flops,
            'estimated_gflops': estimated_flops / 1e9,
            'estimated_tflops': estimated_flops / 1e12,
            'gpu_info': gpu_info
        }
    
    def print_step_metrics(self, metrics):
        line = f"  Step {metrics['step']:3d} | Loss: {metrics['loss']:.4f} | "
        line += f"Time: {metrics['step_time_ms']:.1f}ms | "
        line += f"Mem: {metrics['memory_gb']:.2f}GB | "
        line += f"CPU: {metrics['cpu_percent']:.1f}% | "
        line += f"GFLOPS: {metrics['estimated_gflops']:.2f}"
        print(line)
        
        if metrics['gpu_info']:
            for gpu in metrics['gpu_info']:
                print(f"        GPU {gpu['index']}: {gpu['name']} | "
                      f"Util: {gpu['utilization']:.1f}% | "
                      f"Mem: {gpu['memory_used_mb']/1024:.2f}/{gpu['memory_total_mb']/1024:.2f}GB")
    
    def print_summary(self):
        total_time = time.time() - self.start_time
        avg_step_time = np.mean(np.diff(self.step_times)) * 1000 if len(self.step_times) > 1 else 0
        avg_memory = np.mean(self.memory_samples) if self.memory_samples else 0
        peak_memory = max(self.memory_samples) if self.memory_samples else 0
        avg_loss = np.mean(self.losses) if self.losses else 0
        total_steps = len(self.step_times) - 1
        avg_gflops_per_step = self.total_gflops / total_steps if total_steps > 0 else 0
        gflops_per_second = self.total_gflops / total_time if total_time > 0 else 0
        
        print("\n" + "="*70)
        print("RESOURCE USAGE SUMMARY")
        print("="*70)
        print(f"Number of devices: {self.num_devices}")
        print(f"Total training time: {total_time:.2f} seconds")
        print(f"Average step time: {avg_step_time:.2f} ms")
        print(f"Average steps/second: {1.0/(avg_step_time/1000) if avg_step_time > 0 else 0:.2f}")
        print(f"Average memory usage: {avg_memory:.2f} GB")
        print(f"Peak memory usage: {peak_memory:.2f} GB")
        print(f"Average loss: {avg_loss:.4f}")
        print(f"Total FLOPS: {self.total_flops:.2e}")
        print(f"Total GFLOPS: {self.total_gflops:.2f}")
        print(f"Average GFLOPS per step: {avg_gflops_per_step:.2f}")
        print(f"GFLOPS per second: {gflops_per_second:.2f}")
        
        if self.gpu_samples:
            avg_gpu_util = np.mean([g[0]['utilization'] for g in self.gpu_samples if g]) if self.gpu_samples else 0
            avg_gpu_mem = np.mean([g[0]['memory_used_mb']/1024 for g in self.gpu_samples if g]) if self.gpu_samples else 0
            print(f"Average GPU utilization: {avg_gpu_util:.1f}%")
            print(f"Average GPU memory: {avg_gpu_mem:.2f} GB")
        
        total_flops = sum(self.estimate_flops(MAX_LENGTH) for _ in range(len(self.step_times)-1))
        print(f"Estimated total FLOPS: {total_flops:.2e}")
        print(f"Estimated total TFLOPS: {total_flops/1e12:.2f}")
        print("="*70)

# Tokenization
print(f"Loading tokenizer: {MODEL_NAME}")
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
tokenizer.pad_token = tokenizer.eos_token
VOCAB_SIZE = len(tokenizer)
print(f"Tokenizer loaded. Vocab size: {VOCAB_SIZE}")

def tokenize_examples(df, max_length=MAX_LENGTH):
    texts = [
        f"<bos>Question: {row['question_title']}\n{row['question_body']}\nAnswer: {row['answer']}<eos>" 
        for row in df.rows(named=True)
    ]
    tokenized = tokenizer(
        texts,
        truncation=True,
        max_length=max_length,
        padding="max_length",
        return_tensors="np"
    )
    tokenized["labels"] = tokenized["input_ids"].copy()
    return tokenized

train_tokenized = tokenize_examples(train_data)
val_tokenized = tokenize_examples(val_data)

dataset_dict = DatasetDict({
    "train": Dataset.from_dict({
        "input_ids": train_tokenized["input_ids"],
        "attention_mask": train_tokenized["attention_mask"],
        "labels": train_tokenized["labels"]
    }),
    "validation": Dataset.from_dict({
        "input_ids": val_tokenized["input_ids"],
        "attention_mask": val_tokenized["attention_mask"],
        "labels": val_tokenized["labels"]
    })
})

def numpy_collate(batch):
    return {k: np.stack([b[k] for b in batch]) for k in batch[0].keys()}

train_loader = DataLoader(
    dataset_dict["train"], 
    batch_size=BATCH_SIZE, 
    shuffle=True, 
    collate_fn=numpy_collate
)
val_loader = DataLoader(
    dataset_dict["validation"], 
    batch_size=BATCH_SIZE, 
    collate_fn=numpy_collate
)

# JAX Model Definition with vmap
def init_params(rng):
    keys = jax.random.split(rng, 5)
    
    params = {
        'wte': jax.random.normal(keys[0], (VOCAB_SIZE, EMBED_DIM)) * 0.02,
        'wpe': jax.random.normal(keys[1], (MAX_LENGTH, EMBED_DIM)) * 0.02,
        'layers': [],
        'ln_f_scale': jnp.ones(EMBED_DIM),
        'ln_f_bias': jnp.zeros(EMBED_DIM),
        'lm_head': jax.random.normal(keys[3], (EMBED_DIM, VOCAB_SIZE)) * 0.02,
    }
    
    for i in range(NUM_LAYERS):
        layer_key = jax.random.split(keys[2], NUM_LAYERS)[i]
        layer_keys = jax.random.split(layer_key, 6)
        params['layers'].append({
            'attn_q': jax.random.normal(layer_keys[0], (EMBED_DIM, EMBED_DIM)) * 0.02,
            'attn_k': jax.random.normal(layer_keys[1], (EMBED_DIM, EMBED_DIM)) * 0.02,
            'attn_v': jax.random.normal(layer_keys[2], (EMBED_DIM, EMBED_DIM)) * 0.02,
            'attn_out': jax.random.normal(layer_keys[3], (EMBED_DIM, EMBED_DIM)) * 0.02,
            'ln1_scale': jnp.ones(EMBED_DIM),
            'ln1_bias': jnp.zeros(EMBED_DIM),
            'mlp_in': jax.random.normal(layer_keys[4], (EMBED_DIM, EMBED_DIM * 4)) * 0.02,
            'mlp_out': jax.random.normal(layer_keys[5], (EMBED_DIM * 4, EMBED_DIM)) * 0.02,
            'ln2_scale': jnp.ones(EMBED_DIM),
            'ln2_bias': jnp.zeros(EMBED_DIM),
        })
    
    return params

def layer_norm(x, scale, bias, eps=1e-5):
    mean = jnp.mean(x, axis=-1, keepdims=True)
    var = jnp.var(x, axis=-1, keepdims=True)
    return scale * (x - mean) / jnp.sqrt(var + eps) + bias

def forward(params, input_ids, attention_mask=None):
    batch_size, seq_len = input_ids.shape
    
    x = params['wte'][input_ids] + params['wpe'][:seq_len]
    
    mask = jnp.tril(jnp.ones((seq_len, seq_len))).reshape(1, 1, seq_len, seq_len)
    mask = (mask == 0) * -1e9
    
    if attention_mask is not None:
        attention_mask = attention_mask[:, None, None, :]
        attention_mask = (1.0 - attention_mask) * -1e9
        mask = mask + attention_mask
    
    def reshape_for_heads(x):
        return x.reshape(batch_size, seq_len, NUM_HEADS, -1).transpose(0, 2, 1, 3)
    
    for layer in params['layers']:
        residual = x
        x = layer_norm(x, layer['ln1_scale'], layer['ln1_bias'])
        
        q = reshape_for_heads(jnp.matmul(x, layer['attn_q']))
        k = reshape_for_heads(jnp.matmul(x, layer['attn_k']))
        v = reshape_for_heads(jnp.matmul(x, layer['attn_v']))
        
        scores = jnp.matmul(q, k.transpose(0, 1, 3, 2)) / jnp.sqrt(q.shape[-1])
        scores = scores + mask
        attn_out = jnp.matmul(jax.nn.softmax(scores, axis=-1), v)
        
        attn_out = attn_out.transpose(0, 2, 1, 3).reshape(batch_size, seq_len, -1)
        attn_out = jnp.matmul(attn_out, layer['attn_out'])
        x = residual + attn_out
        
        residual = x
        x = layer_norm(x, layer['ln2_scale'], layer['ln2_bias'])
        x = jnp.matmul(x, layer['mlp_in'])
        x = jax.nn.gelu(x)
        x = jnp.matmul(x, layer['mlp_out'])
        x = residual + x
    
    x = layer_norm(x, params['ln_f_scale'], params['ln_f_bias'])
    return jnp.matmul(x, params['lm_head'])

# Vectorized Loss with vmap
def single_example_loss(params, input_ids, attention_mask, labels):
    """Loss for a single example."""
    logits = forward(params, input_ids[None, :], attention_mask[None, :])[0]
    shift_logits = logits[:-1, :]
    shift_labels = labels[1:]
    loss = optax.softmax_cross_entropy_with_integer_labels(shift_logits, shift_labels)
    mask = (shift_labels != tokenizer.pad_token_id).astype(loss.dtype)
    return (loss * mask).sum() / mask.sum()

# Create batched version using vmap
batch_loss_vmap = jax.vmap(single_example_loss, in_axes=(None, 0, 0, 0))

# JIT-compiled loss function
@jax.jit
def compute_loss_jit(params, batch):
    """Compute loss with JIT compilation."""
    return batch_loss_vmap(params, batch['input_ids'], batch['attention_mask'], batch['labels']).mean()

# Combined Optimizations (JIT + vmap + pmap)
num_devices = jax.local_device_count()
print(f"\nNumber of devices: {num_devices}")

def shard_batch(batch):
    """Shard batch across devices for pmap."""
    batch_size = batch['input_ids'].shape[0]
    per_device = batch_size // num_devices
    if per_device == 0 or num_devices == 1:
        return batch
    return jax.tree.map(
        lambda x: x.reshape(num_devices, per_device, *x.shape[1:]),
        batch
    )

axis_name = 'devices'

def train_step_fn(state, batch):
    """Training step function with gradient aggregation."""
    loss, grads = jax.value_and_grad(compute_loss_jit)(state.params, batch)
    if num_devices > 1:
        grads = jax.lax.pmean(grads, axis_name=axis_name)
        loss = jax.lax.pmean(loss, axis_name=axis_name)
    state = state.apply_gradients(grads=grads)
    return state, loss

# Create pmap version if multiple devices available
if num_devices > 1:
    train_step = jax.pmap(train_step_fn, axis_name=axis_name)
    eval_step = jax.pmap(lambda state, batch: compute_loss_jit(state.params, batch), axis_name=axis_name)
else:
    train_step = jax.jit(train_step_fn)
    eval_step = jax.jit(lambda state, batch: compute_loss_jit(state.params, batch))

# Training State
def create_train_state(rng):
    params = init_params(rng)
    tx = optax.adamw(LEARNING_RATE, weight_decay=WEIGHT_DECAY)
    return train_state.TrainState.create(apply_fn=None, params=params, tx=tx)

rng = jax.random.PRNGKey(42)
state = create_train_state(rng)

# Replicate state across devices if more than one device
if num_devices > 1:
    state = flax.jax_utils.replicate(state)

# Initialize resource monitor
monitor = ResourceMonitor()

# Print device information
print(f"JAX devices: {jax.devices()}")
print(f"JAX backend: {jax.devices()[0].platform}")

# Training Loop with Combined Optimizations
total_params = sum(p.size for p in jax.tree.leaves(state.params))
print(f"\nTotal parameters: {total_params:,}")

optimization_type = "pmap + vmap + JIT" if num_devices > 1 else "vmap + JIT"
print(f"Training with {optimization_type} optimization...\n")

for epoch in range(EPOCHS):
    epoch_loss = 0.0
    steps = 0
    
    for batch in train_loader:
        batch = {k: jnp.array(v) for k, v in batch.items()}
        
        if num_devices > 1:
            batch = shard_batch(batch)
            state, loss = train_step(state, batch)
            loss_value = float(loss.mean())
        else:
            state, loss = train_step(state, batch)
            loss_value = float(loss)
        
        epoch_loss += loss_value
        steps += 1
        
        seq_len = batch['input_ids'].shape[-1]
        metrics = monitor.log_step(steps, loss_value, seq_len)
        
        if steps % 10 == 0:
            monitor.print_step_metrics(metrics)
    
    val_loss = 0.0
    val_steps = 0
    for batch in val_loader:
        batch = {k: jnp.array(v) for k, v in batch.items()}
        
        if num_devices > 1:
            batch = shard_batch(batch)
            loss = eval_step(state, batch)
            loss_value = float(loss.mean())
        else:
            loss_value = float(eval_step(state, batch))
        
        val_loss += loss_value
        val_steps += 1
    
    print(f"Epoch {epoch+1} | Train Loss: {epoch_loss/steps:.4f} | Val Loss: {val_loss/val_steps:.4f}\n")

# Print resource usage summary
monitor.print_summary()

# Save model
os.makedirs(OUTPUT_DIR, exist_ok=True)

# Get parameters from first device for saving
if num_devices > 1:
    params_save = jax.tree.map(lambda x: x[0], state.params)
else:
    params_save = state.params

with open(f"{OUTPUT_DIR}/params.pkl", "wb") as f:
    pickle.dump(params_save, f)
tokenizer.save_pretrained(OUTPUT_DIR)
print(f"Training completed. Model saved to {OUTPUT_DIR}")

print("\n" + "="*60)
print("COMBINED JAX OPTIMIZATIONS BENEFITS")
print("="*60)
print("JIT Compilation: Operation fusion and XLA optimization")
print("vmap: Automatic vectorization of single-example functions")
if num_devices > 1:
    print(f"pmap: Parallel training across {num_devices} devices")
    print("Automatic gradient synchronization")
print("="*60)

**Reference**
- [Optax:Getting started](https://optax.readthedocs.io/en/latest/getting_started.html)
- [Optax:Optax](https://optax.readthedocs.io/en/latest/)
- [JAX:jax.experimental.custom_partitioning module](https://docs.jax.dev/en/latest/jax.experimental.custom_partitioning.html)
- [JAX:Parallel Evaluation in JAX](https://kolonist26-jax-kr.readthedocs.io/en/latest/jax-101/06-parallelism.html)
- [JAX:shmap (shard_map) for simple per-device code](https://docs.jax.dev/en/latest/jep/14273-shard-map.html)
- [JAX:Introduction to parallel programming](https://docs.jax.dev/en/latest/sharded-computation.html)
- [FLAX:Scale up Flax Modules on multiple devices with pjit](https://flax.readthedocs.io/en/v0.6.10/guides/flax_on_pjit.html)
- [JAX:Parallel Evaluation in JAX](https://kolonist26-jax-kr.readthedocs.io/en/latest/jax-101/06-parallelism.html)
- [JAX:jax.pmap](https://docs.jax.dev/en/latest/_autosummary/jax.pmap.html)
- [JAX:Introduction to parallel programming](https://docs.jax.dev/en/latest/sharded-computation.html)
- [APXML:Hands-on Practical: Parallel Computation](https://apxml.com/courses/getting-started-with-jax/chapter-5-parallelization-across-devices-pmap/hands-on-parallel-computation)
- [JAX:jax.numpy.vectorize](https://docs.jax.dev/en/latest/_autosummary/jax.numpy.vectorize.html)
- [JAX:Automatic vectorization](https://docs.jax.dev/en/latest/automatic-vectorization.html)
- [APXML:Hands-on Practical: Vectorizing Functions](https://apxml.com/courses/getting-started-with-jax/chapter-4-automatic-vectorization-vmap/hands-on-vectorizing-functions)
- [JAX:Resources and Advanced Guides](https://docs.jax.dev/en/latest/advanced_guides.html)
- [JAX/FLAX:JAX/Flax Key Concepts](https://flax.readthedocs.io/en/latest/key_concepts.html)
- [JAX:Quickstart: How to think in JAX](https://docs.jax.dev/en/latest/notebooks/thinking_in_jax.html)
- [FLAX:Documentation](https://flax.readthedocs.io/en/v0.8.1/)
- [Uvadlc:Tutorial 2 (JAX): Introduction to JAX+Flax](https://uvadlc-notebooks.readthedocs.io/en/latest/tutorial_notebooks/JAX/tutorial2/Introduction_to_JAX.html#)
- [GitHub:JAX example](https://github.com/jax-ml/jax-llm-examples)
- [JAX:How to Scale Your Model](https://jax-ml.github.io/scaling-book/)
- [Medium:Gemma from Scratch: Mastering LLM Implementation with JAX and Flax](https://medium.com/@lucamassaron/gemma-from-scratch-mastering-llm-implementation-with-jax-and-flax-2de783163f46)
- [Medium:Optimizers in JAX and Flax](https://pub.towardsai.net/optimizers-in-jax-and-flax-0f9c50fd517c)

# Inference Optimizations

Inference optimization refers to a suite of techniques designed to reduce the latency, increase the throughput, and lower the memory footprint of Large Language Models (LLMs) during the generation phase. While training focuses on learning, inference focuses on efficiency and cost-effectiveness for real-time applications.

**Key Inference Optimization Techniques**

**1. Model Compression (Quantization and Pruning)**

- Quantization: Reduces the precision of model weights from 32-bit floating point (FP32) to lower-precision formats like INT8 or FP4. This significantly reduces memory usage and speeds up matrix multiplications on modern hardware.
- Pruning: Removes redundant or less important connections (weights) in the neural network, creating a smaller, sparser model that requires fewer computations.

**2. Architectural Optimizations (KV Caching)**

- Key-Value (KV) Caching: LLMs generate text token-by-token. Normally, each new token would require re-calculating the attention for all previous tokens. KV Caching stores the keys and values of past tokens in memory so the model only computes the attention for the newest token, drastically reducing redundant math.

**3. Structural Optimizations (FlashAttention and PagedAttention)**

- FlashAttention: An algorithm that reorders attention computations to reduce the number of times data is moved between the GPU's fast memory (SRAM) and slow memory (HBM).
- PagedAttention (vLLM): Manages the KV cache like operating system memory. Instead of allocating large, contiguous chunks of memory (which often leads to waste), it breaks the cache into smaller "pages," allowing for significantly higher batch sizes.
+1

**4. Decoding Strategies (Speculative Decoding)**

- Speculative Decoding: A small, fast "draft" model predicts the next few tokens, and the large "target" model verifies them in a single parallel pass. If the predictions are correct, generation speed increases by 2x to 3x because the large model does fewer sequential passes.

**When to Use Inference Optimizations**

**1. High-Latency Environments**

If the Time To First Token (TTFT) or the tokens-per-second rate is too slow for a good user experience (e.g., a real-time chatbot), optimizations like FlashAttention and Speculative Decoding are essential.

**2. Resource Constraints**

If the model is too large to fit into the available VRAM of your hardware (e.g., trying to run a 70B model on a single 24GB GPU), Quantization (specifically 4-bit or 8-bit) is mandatory to reduce the memory footprint.

**3. Scaling for High Traffic**

When serving a model to thousands of users simultaneously, you need high throughput. Techniques like PagedAttention and Continuous Batching allow you to process more requests per second on the same hardware, lowering the "cost per query."

**4. Edge and Mobile Deployment**

For running models locally on laptops or mobile phones, extreme optimizations like Knowledge Distillation (training a tiny model to mimic a big one) and INT4 Quantization are required to balance performance with limited battery and compute power.

## Initial Model Fine Tuning and Evaluation

The code provided is a classic implementation of QLoRA (Quantized Low-Rank Adaptation), a framework designed to fine-tune massive models on relatively modest hardware. It uses several distinct optimization layers to balance memory consumption, speed, and final model performance.

**1. 4-bit NormalFloat (NF4) Quantization**

The code uses the `BitsAndBytesConfig` to implement NF4 quantization. This is a specialized data type designed for normally distributed weights, which is common in neural networks.

**How it is applied:** 

In the `get_quantization_config` function, the code sets `load_in_4bit=True` and `bnb_4bit_quant_type="nf4"`. By also setting `bnb_4bit_use_double_quant=True`, it quantizes the quantization constants themselves, saving even more memory. This allows the 270m parameter model to occupy significantly less VRAM than its standard FP32 version, reducing the memory footprint by roughly 75-80%.

**2. Low-Rank Adaptation (LoRA)**

The code utilizes the PEFT (Parameter-Efficient Fine-Tuning) library to apply LoRA. Instead of updating every single weight in the model, LoRA updates two smaller "low-rank" matrices that represent the changes.

**How it is applied:** 

The script defines a `LoraConfig` where it specifies `target_modules=["q_proj", "v_proj", "k_proj", "o_proj"]`. It then uses `get_peft_model(model, lora_config)` to wrap the model. This makes only a tiny fraction of the parameters "trainable," which drastically reduces the memory needed to store gradients and optimizer states—the two biggest memory consumers during training.

**3. Mixed Precision Training (`bfloat16`)**

The code enables Mixed Precision via the `bf16=USE_MIXED_PRECISION` flag in `TrainingArguments`.

**How it is applied:** 

By using `torch.bfloat16` for the `bnb_4bit_compute_dtype`, the code ensures that while weights are stored in 4-bit, the actual mathematical computations happen in 16-bit. `bfloat16` is preferred over standard float16 on modern hardware because it has a wider dynamic range, which prevents "exploding" or "vanishing" gradients during the fine-tuning process.

**4. Gradient Checkpointing**

To further save memory at the cost of a slight slowdown in training speed, the code implements Gradient Checkpointing.

**How it is applied:** 

The code calls `model.gradient_checkpointing_enable()` and sets `gradient_checkpointing=True` in the `TrainingArguments`. This technique avoids storing all intermediate activations during the forward pass. Instead, it re-computes them on-the-fly during the backward pass. This is essential for fitting the model into memory when using larger batch sizes or long sequence lengths (`MAX_LENGTH = 128`).

**5. Learning Rate Scheduling and Warmup**

The script uses a Cosine Learning Rate Scheduler with a warmup phase to ensure stable training.

**How it is applied:**

In `TrainingArguments`, `lr_scheduler_type="cosine"` and `warmup_steps` are defined. The warmup phase (10% of total steps) prevents the model from being "shocked" by large initial updates, which is especially important for quantized models. The cosine decay then slowly reduces the learning rate to help the model settle into a high-quality local minimum.

**6. Weight Merging for Inference**

Finally, the code prepares the model for production by merging the weights.

**How it is applied:**

In the final section, it checks for the `merge_and_unload()` method. This mathematically combines the LoRA adapter weights with the base model weights. This is a critical inference optimization because it removes the small overhead of calculating the adapters separately, allowing the model to generate text at the maximum possible speed of the base architecture.

In [5]:
import torch
import torch.nn as nn
from transformers import (
    AutoTokenizer,
    AutoModelForCausalLM,
    Trainer,
    TrainingArguments,
    DataCollatorForLanguageModeling,
    TrainerCallback,
    BitsAndBytesConfig
)
from peft import LoraConfig, get_peft_model, prepare_model_for_kbit_training
from datasets import DatasetDict, Dataset
import gc
import os

In [6]:
# Configuration 
MODEL_NAME = "google/gemma-3-270m"
OUTPUT_DIR = "./gemma-3-270m-finetuned-qa-optimized"
MAX_LENGTH = 128
USE_4BIT = True
USE_LORA = True
USE_GRADIENT_CHECKPOINTING = True
USE_MIXED_PRECISION = True
USE_FLASH_ATTENTION = False  # Disabled by default to avoid import errors
USE_PRUNING = False  # Disabled for quantized models
USE_QUANTIZATION_INFERENCE = True

os.makedirs(OUTPUT_DIR, exist_ok=True)

# Tokenizer
print(f"Loading tokenizer: {MODEL_NAME}")
tokenizer = AutoTokenizer.from_pretrained(MODEL_NAME)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"
print(f"Tokenizer loaded. Vocab size: {len(tokenizer)}")

# Tokenization Function
def tokenize_examples(df, max_length=MAX_LENGTH):
    texts = [
        f"Question: {row['question_title']}\n{row['question_body']}\nAnswer: {row['answer']}"
        for row in df.iter_rows(named=True)
    ]
    tokenized = tokenizer(
        texts,
        truncation=True,
        max_length=max_length,
        padding="max_length",
        return_tensors="pt"
    )
    tokenized["labels"] = tokenized["input_ids"].clone()
    tokenized["labels"][tokenized["labels"] == tokenizer.pad_token_id] = -100
    return tokenized

# Load and Tokenize Dataset
print("Tokenizing datasets...")
train_tokenized = tokenize_examples(train_data)
val_tokenized = tokenize_examples(val_data)

dataset_dict = DatasetDict({
    "train": Dataset.from_dict(train_tokenized),
    "validation": Dataset.from_dict(val_tokenized)
})

print(f"Train examples: {len(dataset_dict['train']):,}")
print(f"Validation examples: {len(dataset_dict['validation']):,}")

# Progress Callback 
class ProgressCallback(TrainerCallback):
    def on_log(self, args, state, control, logs=None, **kwargs):
        if logs and 'loss' in logs:
            print(f"Step {state.global_step}: loss = {logs['loss']:.4f}")
        return control

# Quantization Config
def get_quantization_config():
    """Configure 4-bit quantization for memory-efficient training."""
    if USE_4BIT:
        return BitsAndBytesConfig(
            load_in_4bit=True,
            bnb_4bit_quant_type="nf4",
            bnb_4bit_compute_dtype=torch.bfloat16 if USE_MIXED_PRECISION else torch.float16,
            bnb_4bit_use_double_quant=True,
        )
    return None

# Load Model with Optimizations 
print(f"Loading {MODEL_NAME} with optimizations...")

quantization_config = get_quantization_config()

# Calculate total steps for warmup
total_steps = len(dataset_dict["train"]) * 3 // (8 * 1)
warmup_steps = int(0.1 * total_steps)

# Load model
model = AutoModelForCausalLM.from_pretrained(
    MODEL_NAME,
    quantization_config=quantization_config,
    device_map="auto",
    torch_dtype=torch.bfloat16 if USE_MIXED_PRECISION else torch.float32,
    attn_implementation="eager",  # Use eager to avoid compatibility issues
    use_cache=not USE_GRADIENT_CHECKPOINTING,
)

# LoRA Configuration 
if USE_LORA:
    print("\nApplying LoRA for parameter-efficient fine-tuning...")
    
    if USE_4BIT:
        model = prepare_model_for_kbit_training(model)
    
    lora_config = LoraConfig(
        r=8,
        lora_alpha=16,
        target_modules=["q_proj", "v_proj", "k_proj", "o_proj"],
        lora_dropout=0.05,
        bias="none",
        task_type="CAUSAL_LM",
    )
    
    model = get_peft_model(model, lora_config)
    model.print_trainable_parameters()

# Gradient Checkpointing 
if USE_GRADIENT_CHECKPOINTING:
    print("Enabling gradient checkpointing...")
    model.gradient_checkpointing_enable()
    model.config.use_cache = False

# Model Statistics
total_params = sum(p.numel() for p in model.parameters())
trainable_params = sum(p.numel() for p in model.parameters() if p.requires_grad)

print(f"\nModel Statistics:")
print(f"  Total parameters: {total_params:,}")
print(f"  Trainable parameters: {trainable_params:,}")
print(f"  Trainable percentage: {(trainable_params / total_params * 100):.2f}%")

if USE_4BIT:
    original_memory = total_params * 4 / (1024**3)
    quantized_memory = total_params * 0.5 / (1024**3)
    print(f"  Estimated memory (FP32): {original_memory:.2f} GB")
    print(f"  Estimated memory (4-bit): {quantized_memory:.2f} GB")
    print(f"  Memory reduction: {(1 - quantized_memory/original_memory)*100:.1f}%")
    
monitor = EpochMonitor(model=model)

# Training Arguments
training_args = TrainingArguments(
    output_dir=OUTPUT_DIR,
    num_train_epochs=3,
    per_device_train_batch_size=8,
    per_device_eval_batch_size=8,
    gradient_accumulation_steps=1,
    learning_rate=2e-5,
    weight_decay=0.01,
    max_grad_norm=1.0,
    eval_strategy="epoch",
    save_strategy="epoch",
    load_best_model_at_end=True,
    metric_for_best_model="eval_loss",
    greater_is_better=False,
    report_to="none",
    save_total_limit=2,
    remove_unused_columns=False,
    logging_steps=50,
    warmup_steps=warmup_steps,  
    lr_scheduler_type="cosine",
    bf16=USE_MIXED_PRECISION,
    optim="adamw_torch",
    gradient_checkpointing=USE_GRADIENT_CHECKPOINTING,
    dataloader_num_workers=2,
    ddp_find_unused_parameters=False if torch.cuda.device_count() > 1 else None,
)

# Trainer 
trainer = Trainer(
    model=model,
    args=training_args,
    train_dataset=dataset_dict["train"],
    eval_dataset=dataset_dict["validation"],
    data_collator=DataCollatorForLanguageModeling(tokenizer=tokenizer, mlm=False),
    callbacks=[ProgressCallback(), monitor],  # Removed undefined EpochMonitor
)

# Train 

print(f"\n{'='*60}")
print(f"STARTING OPTIMIZED TRAINING")
print(f"{'='*60}")
print(f"4-bit Quantization: {USE_4BIT}")
print(f"LoRA: {USE_LORA}")
print(f"Gradient Checkpointing: {USE_GRADIENT_CHECKPOINTING}")
print(f"Mixed Precision: {USE_MIXED_PRECISION}")
print(f"{'='*60}\n")

train_result = trainer.train()

# Save Optimized Model
print("\nSaving model and tokenizer...")
model.save_pretrained(OUTPUT_DIR)
tokenizer.save_pretrained(OUTPUT_DIR)

# Inference Optimization 
if USE_QUANTIZATION_INFERENCE:
    print("\nPreparing inference-optimized version...")
    
    inference_dir = os.path.join(OUTPUT_DIR, "inference_optimized")
    os.makedirs(inference_dir, exist_ok=True)
    
    # Merge LoRA weights if applicable
    if hasattr(model, 'merge_and_unload'):
        merged_model = model.merge_and_unload()
    else:
        merged_model = model
    
    # Save for inference
    merged_model.save_pretrained(inference_dir)
    tokenizer.save_pretrained(inference_dir)
    
    # Save inference config
    inference_config = {
        "quantization": "4-bit" if USE_4BIT else "none",
        "lora": USE_LORA,
        "mixed_precision": USE_MIXED_PRECISION,
    }
    torch.save(inference_config, os.path.join(inference_dir, "inference_config.pt"))
    
    print(f"  Inference-optimized model saved to: {inference_dir}")

# Training Summary
print(f"\n{'='*60}")
print("TRAINING COMPLETED SUCCESSFULLY!")
print(f"{'='*60}")
print(f"Model saved to: {OUTPUT_DIR}")
print(f"Final train loss: {train_result.training_loss:.4f}")

if hasattr(trainer.state, 'log_history') and trainer.state.log_history:
    val_losses = [log.get('eval_loss') for log in trainer.state.log_history if 'eval_loss' in log]
    if val_losses:
        print(f"Final validation loss: {val_losses[-1]:.4f}")

print(f"\nOptimizations used:")
print(f"  {'4-bit Quantization' if USE_4BIT else 'FP32'}")
print(f"  {'LoRA' if USE_LORA else 'Full fine-tuning'}")
print(f"  {'Gradient Checkpointing' if USE_GRADIENT_CHECKPOINTING else 'No checkpointing'}")
print(f"  {'Mixed Precision (bfloat16)' if USE_MIXED_PRECISION else 'FP32'}")
print(f"{'='*60}")

Loading tokenizer: google/gemma-3-270m

config.json:   0%|          | 0.00/1.35k [00:00<?, ?B/s]

tokenizer_config.json:   0%|          | 0.00/1.16M [00:00<?, ?B/s]

tokenizer.json:   0%|          | 0.00/33.4M [00:00<?, ?B/s]

added_tokens.json:   0%|          | 0.00/35.0 [00:00<?, ?B/s]

special_tokens_map.json:   0%|          | 0.00/662 [00:00<?, ?B/s]

Tokenizer loaded. Vocab size: 262145
Tokenizing datasets...

`torch_dtype` is deprecated! Use `dtype` instead!

Train examples: 1,331
Validation examples: 285
Loading google/gemma-3-270m with optimizations...

model.safetensors:   0%|          | 0.00/536M [00:00<?, ?B/s]

Loading weights:   0%|          | 0/236 [00:00<?, ?it/s]

generation_config.json:   0%|          | 0.00/133 [00:00<?, ?B/s]

Applying LoRA for parameter-efficient fine-tuning...
trainable params: 737,280 || all params: 268,835,456 || trainable%: 0.2742
Enabling gradient checkpointing...

Model Statistics:
  Total parameters: 218,700,416
  Trainable parameters: 737,280
  Trainable percentage: 0.34%
  Estimated memory (FP32): 0.81 GB
  Estimated memory (4-bit): 0.10 GB
  Memory reduction: 87.5%

============================================================
STARTING OPTIMIZED TRAINING
============================================================
4-bit Quantization: True
LoRA: True
Gradient Checkpointing: True
Mixed Precision: True
============================================================

Initial Model Memory Footprint:
  Parameters: 218,700,416
  Precision: 4 bytes
  Total Memory: 3.63 GB
    - Parameters: 0.81 GB
    - KV Cache (est): 2.81 GB
  Estimated FLOPs per forward pass (batch=8, seq=512): 2.05 TFLOPS

Step 50: loss = 3.2768
Step 100: loss = 3.1740
Step 150: loss = 2.9992

============================================================
Epoch 0 Summary
============================================================
  Duration (s)         :         51.26
  Tokens Processed     :       684,032
  Throughput (token/s) :         13345
  Training Steps       :           167
  Avg CPU (%)          :          23.5
  Avg Memory (%)       :          11.6
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          6.68
  FLOPs (per token)    :   0.50 GFLOPS
Step 200: loss = 2.9641
Step 250: loss = 2.9254
Step 300: loss = 2.9156

============================================================
Epoch 1 Summary
============================================================
  Duration (s)         :         51.07
  Tokens Processed     :       684,032
  Throughput (token/s) :         13394
  Training Steps       :           167
  Avg CPU (%)          :          21.0
  Avg Memory (%)       :          11.6
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          6.71
  FLOPs (per token)    :   0.50 GFLOPS
Step 350: loss = 2.8547
Step 400: loss = 2.8955
Step 450: loss = 2.8803
Step 500: loss = 2.8888

============================================================
Epoch 2 Summary
============================================================
  Duration (s)         :         50.96
  Tokens Processed     :       684,032
  Throughput (token/s) :         13423
  Training Steps       :           167
  Avg CPU (%)          :          20.6
  Avg Memory (%)       :          11.5
  Total FLOPs          : 342.49 TFLOPS
  TFLOPS (per second)  :          6.72
  FLOPs (per token)    :   0.50 GFLOPS

============================================================
TRAINING COMPLETE
============================================================
Total Training Time: 166.69s
Total Epochs: 3
Average Epoch Time: 51.10s
Total Tokens Processed: 2,052,096
Average Throughput: 12311 tokens/second
Total FLOPs: 1027.47 TFLOPS
Average TFLOPS (per second): 6.16
Overall FLOPs (per token): 0.50 GFLOPS

Final Metrics:
Memory Footprint: 3.63 GB
Inference Throughput: 13732 tokens/second
Total Training FLOPs: 342.49 TFLOPS

Saving model and tokenizer...

Preparing inference-optimized version...

/usr/local/lib/python3.11/dist-packages/peft/tuners/lora/bnb.py:397: UserWarning: Merge lora module to 4-bit linear may get different generations due to rounding errors.
  warnings.warn(

Writing model shards:   0%|          | 0/1 [00:00<?, ?it/s]

  Inference-optimized model saved to: ./gemma-3-270m-finetuned-qa-optimized/inference_optimized

============================================================
TRAINING COMPLETED SUCCESSFULLY!
============================================================
Model saved to: ./gemma-3-270m-finetuned-qa-optimized
Final train loss: 2.9772
Final validation loss: 3.2051

Optimizations used:
  4-bit Quantization
  LoRA
  Gradient Checkpointing
  Mixed Precision (bfloat16)
============================================================

**Reference**
- [Huggingface:gemma-3-270m](https://huggingface.co/google/gemma-3-270m)
- [Huggingface:Trainer](https://huggingface.co/docs/transformers/en/main_classes/trainer)
- [Huggingface:Bitsandbytes](https://huggingface.co/docs/transformers/en/quantization/bitsandbytes)
- [Huggingface:LoRA](https://huggingface.co/docs/peft/en/package_reference/lora)
- [Huggingface:Quantization](https://huggingface.co/docs/peft/en/developer_guides/quantization)

### Evaluation Metrics and Interpretation

The code evaluates the model across three distinct categories: Accuracy, Performance, and Resource Usage.

**Accuracy Metrics (Quality)**

These measure how well the model's generated answer matches the human ground truth.
- ROUGE (1, 2, L): Measures n-gram overlap.
    - Interpretation: ROUGE-1 relates to content (individual words), while ROUGE-L measures the longest common subsequence (sentence structure). Higher is better.
- BLEU Score: Primarily used in translation and summarization, it penalizes "hallucinations" or extra words.
    - Interpretation: A higher score indicates the model is being concise and staying true to the reference text.

**Performance Metrics (Efficiency)**

These are critical for "inference optimization" to see if the model is fast enough for production.
- Average Throughput (tokens/s): The speed of text generation. Higher is better.
- P95 Inference Time: The time it takes to complete the slowest 5% of requests.
    - Interpretation: This is more important than "average" because it represents the "worst-case" user experience.
- Speculative Acceptance Rate: (Calculated if using a draft model).
    - Interpretation: Tells you what percentage of the small "draft" model's guesses were kept by the large model. Higher rates (e.g., >70%) indicate a massive speed boost.

**Resource Metrics (Cost)**

- GPU Memory (MB): Shows how much VRAM the model occupies.
- CPU & RAM Usage: Monitored via psutil. This helps determine if the inference engine is bottlenecked by the processor or system memory.

### Loads and Evaluates the Model

The script uses a specialized workflow to ensure the model runs correctly on a high-performance engine.

**Phase 1: Configuration Patching**

Before loading the model, the code performs a "hot-fix" on the model's config.json.

    # Defined the required rope_parameters structure
    required_rope_config = { "rope_type": "default", "factor": 1.0, "theta": 10000.0 }

It manually injects Rotary Positional Embedding (RoPE) settings. This is often necessary when moving a model from standard Hugging Face code to an optimized engine like vLLM, which requires specific metadata to handle long-context math correctly.

**Phase 2: Loading with vLLM**

The model is loaded using the LLM class:

    baseline_llm = LLM(
        model=MODEL_PATH,
        tensor_parallel_size=1, # Uses 1 GPU
        dtype="bfloat16",       # High precision, low memory format
        enforce_eager=True,     # Saves memory by avoiding CUDA graph overhead
    )

**Phase 3: Inference (Generation)**

Inference is handled in batches to maximize GPU utilization:
- Sampling Parameters: It sets temperature=0.0. This is Greedy Decoding, meaning the model always picks the single most likely next word. This is best for evaluation because it makes results reproducible.
- The Generation Loop: The code loops through the data in batches of 8. For each batch, it snapshots the time and hardware usage, then calls baseline_llm.generate().
- Metrics Aggregation: The generated text is passed to the ServingOptimizationEvaluator, which calculates the scores and stores them for the final report.

**Phase 4: Cleanup**

    del baseline_llm
    torch.cuda.empty_cache()
    gc.collect()
    
This is a critical step in benchmarking. It force-clears the GPU memory so that the next test (e.g., an optimized version of the model) starts with a clean slate.

In [1]:
%%capture
!pip install vllm numpy
!pip install --upgrade vllm
!pip install "protobuf<4.0" "numpy==1.26.4"

2026-02-20 14:40:13.389873: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2026-02-20 14:40:13.389932: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2026-02-20 14:40:13.391037: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2026-02-20 14:40:13.397672: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2026-02-20 14:40:14.236746: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

In [1]:
import torch
import time
import psutil
import numpy as np
import pandas as pd
from transformers import AutoTokenizer
from vllm import LLM, SamplingParams
import gc
import os
from typing import List, Dict, Any
import polars as pl
from rouge_score import rouge_scorer
from nltk.translate.bleu_score import sentence_bleu, SmoothingFunction
import nltk
import json

nltk.download('punkt', quiet=True)

2026-02-20 14:42:55.345537: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2026-02-20 14:42:55.345600: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2026-02-20 14:42:55.346671: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2026-02-20 14:42:55.352998: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2026-02-20 14:42:56.201954: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

True

In [2]:
# Configuration
MODEL_PATH = "./gemma-3-270m-finetuned-qa-optimized/inference_optimized"
DRAFT_MODEL_PATH = "google/gemma-3-270m-draft"  # For speculative decoding
TEST_DATA_PATH = "test_data.csv"
MAX_LENGTH = 128
NUM_INFERENCE_SAMPLES = 100
MAX_NEW_TOKENS = 100
BATCH_SIZE = 8

# Load test data
print("Loading test data...")
test_data = pl.read_csv(TEST_DATA_PATH).sample(fraction=0.1, seed=42)
test_samples = test_data.sample(n=min(NUM_INFERENCE_SAMPLES, test_data.height), seed=42)
print(f"Testing on {len(test_samples)} samples")

# Load tokenizer
tokenizer = AutoTokenizer.from_pretrained(MODEL_PATH)
tokenizer.pad_token = tokenizer.eos_token
tokenizer.padding_side = "right"
print(f"Tokenizer loaded. Vocab size: {len(tokenizer)}")

# Prepare prompts
all_prompts = []
all_questions = []
all_ground_truths = []

for row in test_samples.iter_rows(named=True):
    question = row['question_title']
    ground_truth = row['answer']
    prompt = f"Question: {question}\nAnswer:"
    all_prompts.append(prompt)
    all_questions.append(question)
    all_ground_truths.append(ground_truth)

# Accuracy metrics functions
def compute_rouge_scores(reference: str, hypothesis: str) -> Dict[str, float]:
    scorer = rouge_scorer.RougeScorer(['rouge1', 'rouge2', 'rougeL'], use_stemmer=True)
    scores = scorer.score(reference, hypothesis)
    return {
        'rouge1_f1': scores['rouge1'].fmeasure,
        'rouge2_f1': scores['rouge2'].fmeasure,
        'rougeL_f1': scores['rougeL'].fmeasure,
    }

def compute_bleu_score(reference: str, hypothesis: str) -> float:
    smoothie = SmoothingFunction().method4
    ref_tokens = nltk.word_tokenize(reference.lower())
    hyp_tokens = nltk.word_tokenize(hypothesis.lower())
    if not ref_tokens or not hyp_tokens:
        return 0.0
    return sentence_bleu([ref_tokens], hyp_tokens, smoothing_function=smoothie)

def compute_perplexity(text: str) -> float:
    return 0.0  # Placeholder for vLLM compatibility

Loading test data...
Testing on 24 samples
Tokenizer loaded. Vocab size: 262145

In [3]:
class ServingOptimizationEvaluator:
    def __init__(self, method_name):
        self.method_name = method_name
        self.reset()
    
    def reset(self):
        self.inference_times = []
        self.tokens_generated = []
        self.throughputs = []
        self.cpu_percentages = []
        self.memory_percentages = []
        self.gpu_memories = []
        self.responses = []
        self.questions = []
        self.ground_truths = []
        self.rouge1_scores = []
        self.rouge2_scores = []
        self.rougeL_scores = []
        self.bleu_scores = []
        
        # Optimization-specific metrics
        self.cache_hits = []
        self.speculative_acceptance = []
        self.medusa_tree_sizes = []
        self.kv_cache_size = []
    
    def add_result(self, question, ground_truth, response, num_tokens, inference_time, 
                   cpu_percent, memory_percent, gpu_memory=None, **kwargs):
        self.questions.append(question)
        self.ground_truths.append(ground_truth)
        self.responses.append(response)
        self.tokens_generated.append(num_tokens)
        self.inference_times.append(inference_time)
        self.throughputs.append(num_tokens / inference_time if inference_time > 0 else 0)
        self.cpu_percentages.append(cpu_percent)
        self.memory_percentages.append(memory_percent)
        
        if gpu_memory is not None:
            self.gpu_memories.append(gpu_memory)
        
        # Store optimization-specific metrics
        if 'cache_hit' in kwargs:
            self.cache_hits.append(kwargs['cache_hit'])
        if 'speculative_tokens' in kwargs:
            self.speculative_acceptance.append(kwargs['speculative_tokens'] / num_tokens if num_tokens > 0 else 0)
        if 'medusa_size' in kwargs:
            self.medusa_tree_sizes.append(kwargs['medusa_size'])
    
    def add_accuracy_metrics(self, rouge_scores, bleu_score):
        self.rouge1_scores.append(rouge_scores['rouge1_f1'])
        self.rouge2_scores.append(rouge_scores['rouge2_f1'])
        self.rougeL_scores.append(rouge_scores['rougeL_f1'])
        self.bleu_scores.append(bleu_score)
    
    def get_summary(self):
        metrics = {
            'total_inferences': len(self.inference_times),
            'total_tokens': sum(self.tokens_generated),
            'avg_tokens': np.mean(self.tokens_generated) if self.tokens_generated else 0,
            'avg_time': np.mean(self.inference_times) if self.inference_times else 0,
            'p95_time': np.percentile(self.inference_times, 95) if self.inference_times else 0,
            'total_time': sum(self.inference_times),
            'avg_throughput': np.mean(self.throughputs) if self.throughputs else 0,
            'avg_cpu': np.mean(self.cpu_percentages) if self.cpu_percentages else 0,
            'avg_memory': np.mean(self.memory_percentages) if self.memory_percentages else 0,
            'avg_gpu_memory': np.mean(self.gpu_memories) if self.gpu_memories else 0,
            'avg_rouge1': np.mean(self.rouge1_scores) if self.rouge1_scores else 0,
            'avg_rouge2': np.mean(self.rouge2_scores) if self.rouge2_scores else 0,
            'avg_rougeL': np.mean(self.rougeL_scores) if self.rougeL_scores else 0,
            'avg_bleu': np.mean(self.bleu_scores) if self.bleu_scores else 0,
        }
        
        if self.cache_hits:
            metrics['cache_hit_rate'] = (sum(self.cache_hits) / len(self.cache_hits)) * 100
        if self.speculative_acceptance:
            metrics['spec_acceptance_rate'] = np.mean(self.speculative_acceptance) * 100
        if self.medusa_tree_sizes:
            metrics['avg_medusa_size'] = np.mean(self.medusa_tree_sizes)
        
        return metrics
    
    def print_report(self, baseline_metrics=None):
        metrics = self.get_summary()
        
        print(f"\n{'='*80}")
        print(f"EVALUATION REPORT: {self.method_name}")
        print(f"{'='*80}")
        
        # Performance metrics
        print("\nPERFORMANCE METRICS:")
        print("-" * 40)
        print(f"  Average Inference Time: {metrics['avg_time']:.3f}s")
        print(f"  P95 Inference Time: {metrics['p95_time']:.3f}s")
        print(f"  Total Inference Time: {metrics['total_time']:.2f}s")
        print(f"  Average Throughput: {metrics['avg_throughput']:.1f} tokens/s")
        print(f"  Total Tokens Generated: {metrics['total_tokens']:,}")
        
        # Optimization-specific metrics
        if 'cache_hit_rate' in metrics:
            print(f"\nPREFIX CACHING METRICS:")
            print("-" * 40)
            print(f"  Cache Hit Rate: {metrics['cache_hit_rate']:.1f}%")
        
        if 'spec_acceptance_rate' in metrics:
            print(f"\nSPECULATIVE DECODING METRICS:")
            print("-" * 40)
            print(f"  Speculative Acceptance Rate: {metrics['spec_acceptance_rate']:.1f}%")
            print(f"  Expected Speedup: 2-3x")
        
        if 'avg_medusa_size' in metrics:
            print(f"\nMEDUSA METRICS:")
            print("-" * 40)
            print(f"  Average Tree Size: {metrics['avg_medusa_size']:.1f}")
        
        # Resource usage
        print(f"\nRESOURCE USAGE:")
        print("-" * 40)
        print(f"  Average CPU: {metrics['avg_cpu']:.1f}%")
        print(f"  Average Memory: {metrics['avg_memory']:.1f}%")
        if metrics['avg_gpu_memory'] > 0:
            print(f"  Average GPU Memory: {metrics['avg_gpu_memory']:.0f} MB")
        
        # Accuracy metrics
        print(f"\nACCURACY METRICS:")
        print("-" * 40)
        print(f"  ROUGE-1 F1: {metrics['avg_rouge1']:.4f}")
        print(f"  ROUGE-2 F1: {metrics['avg_rouge2']:.4f}")
        print(f"  ROUGE-L F1: {metrics['avg_rougeL']:.4f}")
        print(f"  BLEU Score: {metrics['avg_bleu']:.4f}")
        
        # Compare with baseline if available
        if baseline_metrics:
            print(f"\nCOMPARED TO BASELINE:")
            print("-" * 40)
            speedup = baseline_metrics['avg_time'] / metrics['avg_time'] if metrics['avg_time'] > 0 else 0
            throughput_improvement = (metrics['avg_throughput'] / baseline_metrics['avg_throughput'] - 1) * 100
            print(f"  Speedup: {speedup:.2f}x")
            print(f"  Throughput Improvement: {throughput_improvement:.1f}%")
        
        print(f"\n{'='*80}")

In [4]:
print("\n" + "="*80)
print("BASELINE EVALUATION (NO OPTIMIZATIONS)")
print("="*80)

# Patch the model's config.json to include required rope_parameters
config_path = os.path.join(MODEL_PATH, "config.json")
print(f"Patching configuration file: {config_path}")

try:
    with open(config_path, 'r') as f:
        config = json.load(f)

    # Define the required rope_parameters structure if it's missing or incorrect
    required_rope_config = {
        "rope_type": "default",  # Common value, adjust if your model uses a specific type
        "factor": 1.0,
        "theta": 10000.0,
    }

    # Update the config
    if "rope_parameters" not in config:
        config["rope_parameters"] = required_rope_config
    elif "rope_type" not in config["rope_parameters"]:
        config["rope_parameters"]["rope_type"] = "default"

    # Write the modified config back
    with open(config_path, 'w') as f:
        json.dump(config, f, indent=2)
    print("Configuration patched successfully.")

except FileNotFoundError:
    print(f"Error: Configuration file not found at {config_path}. Please ensure the model path is correct.")
    # In a real scenario without try/except, you might want to check for file existence beforehand.
    # For this script, we assume the path is correct. If it's not, the subsequent LLM load will fail.
    pass
except json.JSONDecodeError:
    print(f"Error: Could not parse JSON from {config_path}. The file may be corrupted.")
    pass

baseline_evaluator = ServingOptimizationEvaluator("Baseline")

# Load baseline model without optimizations
baseline_llm = LLM(
    model=MODEL_PATH,
    tensor_parallel_size=1,
    dtype="bfloat16",
    max_model_len=MAX_LENGTH + MAX_NEW_TOKENS,
    enforce_eager=True,
)

sampling_params = SamplingParams(
    temperature=0.0,
    max_tokens=MAX_NEW_TOKENS,
    stop_token_ids=[tokenizer.eos_token_id],
)

# Run baseline inference
num_batches = (len(all_prompts) + BATCH_SIZE - 1) // BATCH_SIZE

for batch_idx in range(num_batches):
    start_idx = batch_idx * BATCH_SIZE
    end_idx = min(start_idx + BATCH_SIZE, len(all_prompts))
    batch_prompts = all_prompts[start_idx:end_idx]
    batch_questions = all_questions[start_idx:end_idx]
    batch_ground_truths = all_ground_truths[start_idx:end_idx]

    # Monitor resources
    start_time = time.time()
    cpu_percent = psutil.cpu_percent(interval=None)
    memory_percent = psutil.virtual_memory().percent

    if torch.cuda.is_available():
        torch.cuda.reset_peak_memory_stats()
        gpu_memory_start = torch.cuda.memory_allocated() / 1024**2

    # Run inference
    outputs = baseline_llm.generate(batch_prompts, sampling_params)

    # End monitoring
    end_time = time.time()
    inference_time = end_time - start_time
    per_sample_time = inference_time / len(batch_prompts)

    gpu_memory = None
    if torch.cuda.is_available():
        gpu_memory_end = torch.cuda.memory_allocated() / 1024**2
        gpu_memory = max(gpu_memory_end, gpu_memory_start)

    # Process outputs
    for i, output in enumerate(outputs):
        response = output.outputs[0].text
        num_tokens = len(output.outputs[0].token_ids)

        baseline_evaluator.add_result(
            question=batch_questions[i],
            ground_truth=batch_ground_truths[i],
            response=response,
            num_tokens=num_tokens,
            inference_time=per_sample_time,
            cpu_percent=cpu_percent,
            memory_percent=memory_percent,
            gpu_memory=gpu_memory,
        )

        rouge_scores = compute_rouge_scores(batch_ground_truths[i], response)
        bleu_score = compute_bleu_score(batch_ground_truths[i], response)
        baseline_evaluator.add_accuracy_metrics(rouge_scores, bleu_score)

    print(f"  Batch {batch_idx + 1}/{num_batches} completed")

baseline_metrics = baseline_evaluator.get_summary()
baseline_evaluator.print_report()

del baseline_llm
torch.cuda.empty_cache()
gc.collect()

================================================================================
BASELINE EVALUATION (NO OPTIMIZATIONS)
================================================================================
Patching configuration file: ./gemma-3-270m-finetuned-qa-optimized/inference_optimized/config.json
Configuration patched successfully.
INFO 02-20 14:43:01 [utils.py:261] non-default args: {'dtype': 'bfloat16', 'max_model_len': 228, 'disable_log_stats': True, 'enforce_eager': True, 'model': './gemma-3-270m-finetuned-qa-optimized/inference_optimized'}
INFO 02-20 14:43:01 [model.py:541] Resolved architecture: Gemma3ForCausalLM
INFO 02-20 14:43:01 [model.py:1882] Downcasting torch.float32 to torch.bfloat16.
INFO 02-20 14:43:01 [model.py:1561] Using max model len 228
INFO 02-20 14:43:03 [scheduler.py:226] Chunked prefill is enabled with max_num_batched_tokens=8192.
INFO 02-20 14:43:03 [vllm.py:624] Asynchronous scheduling is enabled.
WARNING 02-20 14:43:03 [vllm.py:662] Enforce eager set, overriding optimization level to -O0
INFO 02-20 14:43:03 [vllm.py:762] Cudagraph is disabled under eager mode
(EngineCore_DP0 pid=5394) INFO 02-20 14:43:06 [core.py:96] Initializing a V1 LLM engine (v0.15.1) with config: model='./gemma-3-270m-finetuned-qa-optimized/inference_optimized', speculative_config=None, tokenizer='./gemma-3-270m-finetuned-qa-optimized/inference_optimized', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=228, download_dir=None, load_format=bitsandbytes, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, disable_custom_all_reduce=False, quantization=bitsandbytes, enforce_eager=True, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=./gemma-3-270m-finetuned-qa-optimized/inference_optimized, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'level': None, 'mode': <CompilationMode.NONE: 0>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['all'], 'splitting_ops': [], 'compile_mm_encoder': False, 'compile_sizes': [], 'compile_ranges_split_points': [8192], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.NONE: 0>, 'cudagraph_num_of_warmups': 0, 'cudagraph_capture_sizes': [], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'eliminate_noops': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False}, 'max_cudagraph_capture_size': 0, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': True}, 'local_cache_dir': None, 'static_all_moe_layers': []}
(EngineCore_DP0 pid=5394) INFO 02-20 14:43:06 [parallel_state.py:1212] world_size=1 rank=0 local_rank=0 distributed_init_method=tcp://10.39.217.11:32965 backend=nccl
(EngineCore_DP0 pid=5394) INFO 02-20 14:43:06 [parallel_state.py:1423] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank N/A
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
[Gloo] Rank 0 is connected to 0 peer ranks. Expected number of connected peer ranks is : 0
(EngineCore_DP0 pid=5394) INFO 02-20 14:43:07 [gpu_model_runner.py:4033] Starting to load model ./gemma-3-270m-finetuned-qa-optimized/inference_optimized...
(EngineCore_DP0 pid=5394) INFO 02-20 14:43:08 [cuda.py:364] Using FLASH_ATTN attention backend out of potential backends: ('FLASH_ATTN', 'FLASHINFER', 'TRITON_ATTN', 'FLEX_ATTENTION')
(EngineCore_DP0 pid=5394) INFO 02-20 14:43:08 [bitsandbytes_loader.py:786] Loading weights with BitsAndBytes quantization. May take a while ...

Loading safetensors checkpoint shards:   0% Completed | 0/1 [00:00<?, ?it/s]

Loading safetensors checkpoint shards:   0% Completed | 0/1 [00:00<?, ?it/s]

(EngineCore_DP0 pid=5394) INFO 02-20 14:43:10 [gpu_model_runner.py:4130] Model loading took 0.4 GiB memory and 1.863236 seconds
(EngineCore_DP0 pid=5394) INFO 02-20 14:43:13 [gpu_worker.py:356] Available KV cache memory: 11.33 GiB
(EngineCore_DP0 pid=5394) INFO 02-20 14:43:13 [kv_cache_utils.py:1307] GPU KV cache size: 659,776 tokens
(EngineCore_DP0 pid=5394) INFO 02-20 14:43:13 [kv_cache_utils.py:1312] Maximum concurrency for 228 tokens per request: 2604.41x
(EngineCore_DP0 pid=5394) INFO 02-20 14:43:13 [core.py:272] init engine (profile, create kv cache, warmup model) took 3.20 seconds
(EngineCore_DP0 pid=5394) WARNING 02-20 14:43:16 [vllm.py:669] Inductor compilation was disabled by user settings, optimizations settings that are only active during inductor compilation will be ignored.
(EngineCore_DP0 pid=5394) INFO 02-20 14:43:16 [vllm.py:762] Cudagraph is disabled under eager mode
INFO 02-20 14:43:16 [llm.py:343] Supported tasks: ['generate']

Adding requests:   0%|          | 0/8 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/8 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

[2026-02-20 14:43:21] INFO rouge_scorer.py:83: Using default tokenizer.
[2026-02-20 14:43:21] INFO rouge_scorer.py:83: Using default tokenizer.
[2026-02-20 14:43:21] INFO rouge_scorer.py:83: Using default tokenizer.
[2026-02-20 14:43:21] INFO rouge_scorer.py:83: Using default tokenizer.
[2026-02-20 14:43:21] INFO rouge_scorer.py:83: Using default tokenizer.
[2026-02-20 14:43:21] INFO rouge_scorer.py:83: Using default tokenizer.
[2026-02-20 14:43:21] INFO rouge_scorer.py:83: Using default tokenizer.
[2026-02-20 14:43:21] INFO rouge_scorer.py:83: Using default tokenizer.

  Batch 1/3 completed

Adding requests:   0%|          | 0/8 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/8 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

[2026-02-20 14:43:25] INFO rouge_scorer.py:83: Using default tokenizer.
[2026-02-20 14:43:25] INFO rouge_scorer.py:83: Using default tokenizer.
[2026-02-20 14:43:25] INFO rouge_scorer.py:83: Using default tokenizer.
[2026-02-20 14:43:25] INFO rouge_scorer.py:83: Using default tokenizer.
[2026-02-20 14:43:25] INFO rouge_scorer.py:83: Using default tokenizer.
[2026-02-20 14:43:25] INFO rouge_scorer.py:83: Using default tokenizer.
[2026-02-20 14:43:25] INFO rouge_scorer.py:83: Using default tokenizer.
[2026-02-20 14:43:25] INFO rouge_scorer.py:83: Using default tokenizer.

  Batch 2/3 completed

Adding requests:   0%|          | 0/8 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/8 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

[2026-02-20 14:43:29] INFO rouge_scorer.py:83: Using default tokenizer.
[2026-02-20 14:43:29] INFO rouge_scorer.py:83: Using default tokenizer.
[2026-02-20 14:43:29] INFO rouge_scorer.py:83: Using default tokenizer.
[2026-02-20 14:43:29] INFO rouge_scorer.py:83: Using default tokenizer.
[2026-02-20 14:43:29] INFO rouge_scorer.py:83: Using default tokenizer.
[2026-02-20 14:43:29] INFO rouge_scorer.py:83: Using default tokenizer.
[2026-02-20 14:43:29] INFO rouge_scorer.py:83: Using default tokenizer.
[2026-02-20 14:43:29] INFO rouge_scorer.py:83: Using default tokenizer.

  Batch 3/3 completed

================================================================================
EVALUATION REPORT: Baseline
================================================================================

PERFORMANCE METRICS:
----------------------------------------
  Average Inference Time: 0.531s
  P95 Inference Time: 0.537s
  Total Inference Time: 12.76s
  Average Throughput: 188.2 tokens/s
  Total Tokens Generated: 2,400

RESOURCE USAGE:
----------------------------------------
  Average CPU: 14.9%
  Average Memory: 13.6%

ACCURACY METRICS:
----------------------------------------
  ROUGE-1 F1: 0.1317
  ROUGE-2 F1: 0.0106
  ROUGE-L F1: 0.1047
  BLEU Score: 0.0076

================================================================================

20

**Reference**
- [vLLM:Welcome to vLLM](https://docs.vllm.ai/en/latest/)
- [Aclanthology:ROUGE: A Package for Automatic Evaluation of Summaries](https://aclanthology.org/W04-1013.pdf)
- [Arxiv: ROUGE 2.0: Updated and Improved Measures for Evaluation of Summarization Tasks](https://arxiv.org/abs/1803.01937)
- [Aclanthology: BLEU: a Method for Automatic Evaluation of Machine Translation](https://aclanthology.org/P02-1040.pdf)
- [ResearchGate:Efficient CPU-GPU Collaborative Inference for MoE-based LLMs on Memory-Limited Systems](https://www.researchgate.net/publication/398851056_Efficient_CPU-GPU_Collaborative_Inference_for_MoE-based_LLMs_on_Memory-Limited_Systems)
- [Arxiv:MoE-Lightning: High-Throughput MoE Inference on Memory-constrained GPUs](https://arxiv.org/html/2411.11217v1)
- [Arxiv:Efficient CPU-GPU Collaborative Inference for MoE-based LLMs on Memory-Limited Systems](https://arxiv.org/html/2512.16473v1)
- [ResearchGate:Measuring Resource Efficiency and Resource Effectiveness in Manufacturing](https://www.researchgate.net/publication/328390809_Measuring_Resource_Efficiency_and_Resource_Effectiveness_in_Manufacturing)

## Serving Optimizations

Serving optimization refers to the system-level techniques used to manage how a model interacts with multiple users and requests in a production environment.

While inference optimization generally focuses on making the model itself faster (e.g., shrinking the model through quantization), serving optimization focuses on the "infrastructure" and "scheduling" around the model to maximize throughput and minimize the time a user waits for a response.

**The Kitchen Analogy**

Think of LLM optimization like a busy restaurant:
- Inference Optimization is like sharpening the chef's knives or prepping ingredients in advance so the individual cooking process is faster.
- Serving Optimization is like the "front-of-house" management: organizing how orders are taken, how many tables the waiters handle at once, and ensuring the kitchen never has an empty stove.

**Reference**
- [Arxiv:LLM Serving Optimization with Variable Prefill and Decode Lengths](https://arxiv.org/abs/2508.06133)
- [APXML:Chapter 4: LLM Deployment and Serving Optimization](https://apxml.com/courses/mlops-for-large-models-llmops/chapter-4-llm-deployment-serving-optimization)
- [Medium:Understanding LLM Serving: How to Run Language Models Fast, Cheap, and Effectively](https://medium.com/@tungvu_37498/understanding-llm-serving-how-to-run-language-models-fast-cheap-and-effectively-70ef68242d93)
- [Huggingface:LLM inference optimization](https://huggingface.co/docs/transformers/v4.44.1/llm_optims)
- [Arxiv:End-to-End Modeling and Optimization of Multi-Stage LLM Serving Across the HW/SW Stack](https://arxiv.org/html/2504.09775v4)

### Continuous and Paged Batching (vLLM)

**Continuous Batching**

Continuous Batching (also known as Iteration-level Scheduling) is an optimization that allows an LLM to handle multiple requests simultaneously by treating the generation process as a series of individual iterations rather than waiting for an entire batch to finish. In traditional static batching, if one request in a batch of eight is much shorter than the others, its GPU resources sit idle until the longest request completes. Continuous batching eliminates this "bubble" of idle time by inserting a new request into the batch the moment any existing request finishes its current iteration.

**Paged Batching**

Paged Batching (driven by PagedAttention) solves the memory bottleneck associated with continuous batching. Large Language Models require storing Key-Value (KV) tensors for every token in a sequence to avoid redundant calculations. Traditionally, this KV cache had to be stored in large, contiguous blocks of GPU memory. Because the final length of a response is unknown, systems often pre-allocated the maximum possible memory for every request, leading to massive memory fragmentation and waste. PagedAttention manages this memory by breaking the KV cache into small, non-contiguous "pages" or blocks, allowing the system to use GPU memory with near-zero waste.

**How the Optimization Functions**

The core mechanism operates similarly to virtual memory in operating systems. When a request arrives, the engine does not reserve a giant block of memory. Instead, it maps the request to small physical blocks (pages). As the model generates more tokens, the engine dynamically assigns more blocks from a memory pool.

This architecture enables:
- Dynamic Mapping: Logical blocks of a sequence are mapped to physical blocks in GPU VRAM that do not need to be adjacent.
- Efficient Sharing: In scenarios like parallel sampling where one prompt generates multiple outputs, the memory blocks for the prompt can be shared across all outputs, drastically reducing memory overhead.
- Maximum Throughput: By utilizing nearly all available GPU memory without fragmentation, the engine can fit significantly more sequences (requests) onto a single GPU simultaneously.

**Continuous and Paged Batching**

The script implements these optimizations through the vLLM library using several specific parameters within the LLM class initialization:
- `block_size=16`: This defines the size of the `PagedAttention` blocks. It specifies that the KV cache for 16 tokens is stored in a single memory block. Smaller blocks reduce fragmentation but increase the overhead of the mapping table.
- `gpu_memory_utilization=0.9`: The code instructs vLLM to reserve 90% of the available GPU VRAM for the KV cache. This aggressive allocation is possible because PagedAttention ensures that almost every byte of that 90% can be used effectively for active sequences.
- `max_num_seqs=256`: This parameter sets the upper limit for the number of concurrent sequences the engine will manage. Continuous batching allows the scheduler to keep this "window" full by cycling new requests in as old ones terminate.
- `swap_space=4`: Since GPU memory is finite, this allocates 4 GiB of CPU RAM as a "swap" area. If the GPU runs out of space for KV blocks, the engine can temporarily move blocks to the CPU instead of crashing or rejecting the request.
- `enforce_eager=True`: This tells the engine to execute operations immediately rather than capturing a CUDA graph, which is often more stable for variable-length batching in development environments.

**Optimization Implementation Scenarios**

Continuous and Paged Batching should be used in the following circumstances:
- Production APIs: When hosting a model that serves multiple users simultaneously, these techniques are essential to maintain high throughput and reduce costs per request.
- Variable Length Requests: It is most effective when the input prompts and expected output lengths vary significantly across the workload, as this is where static batching is most inefficient.
- Memory-Constrained Hardware: When the goal is to maximize the utility of a single GPU, PagedAttention allows for a much higher "batch size" than would be possible with standard contiguous memory allocation.
- Real-time Applications: For chatbots or assistants where "Time to First Token" (TTFT) is a priority, continuous batching ensures that new requests are not stuck behind long-running background tasks.

In [ ]:
%%capture
!pip install vllm
!pip install --upgrade vllm

import json
import os
from vllm import LLM, SamplingParams

In [5]:
print("\n" + "="*80)
print("SETUP AND CONFIGURATION")
print("="*80)

# The configuration file to include required rope_parameters
def patch_model_config(model_path):
    config_path = os.path.join(model_path, "config.json")
    if os.path.exists(config_path):
        with open(config_path, 'r') as f:
            config = json.load(f)
        
        # Add rope_parameters if missing
        if "rope_parameters" not in config:
            config["rope_parameters"] = {
                "rope_type": "default",
                "factor": 1.0,
                "theta": 10000.0,
            }
        elif "rope_type" not in config["rope_parameters"]:
            config["rope_parameters"]["rope_type"] = "default"
        
        with open(config_path, 'w') as f:
            json.dump(config, f, indent=2)
        print(f"Patched configuration: {config_path}")

# Apply the fix to your model path
patch_model_config(MODEL_PATH)

# Common sampling parameters
base_sampling_params = SamplingParams(
    temperature=0.0,
    max_tokens=MAX_NEW_TOKENS,
    stop_token_ids=[tokenizer.eos_token_id],
    skip_special_tokens=True,
)

================================================================================
SETUP AND CONFIGURATION
================================================================================
Patched configuration: ./gemma-3-270m-finetuned-qa-optimized/inference_optimized/config.json

In [6]:
print("\n" + "="*80)
print("CONTINUOUS/PAGED BATCHING WITH VLLM")
print("="*80)
print("Variable-length sequences with non-contiguous memory")

# Initialize evaluator for continuous batching
continuous_batching_evaluator = ServingOptimizationEvaluator("Continuous/Paged Batching")

continuous_batching_llm = LLM(
    model=MODEL_PATH,
    tensor_parallel_size=1,
    dtype="bfloat16",
    max_model_len=MAX_LENGTH + MAX_NEW_TOKENS,
    enforce_eager=True,
    
    # Continuous batching specific parameters (supported)
    max_num_batched_tokens=4096,
    max_num_seqs=256,
    
    # Paged attention parameters (supported)
    block_size=16,
    swap_space=4,
    gpu_memory_utilization=0.9,
    
    # Enable paged attention
    enable_prefix_caching=False,
)

# Use the base sampling params
continuous_sampling_params = base_sampling_params

print("\nContinuous/Paged Batching Configuration:")

# Run inference with continuous batching
num_batches = (len(all_prompts) + BATCH_SIZE - 1) // BATCH_SIZE
total_samples_processed = 0
variable_length_times = []

print(f"\nProcessing {len(all_prompts)} samples with variable-length sequences...")

for batch_idx in range(num_batches):
    start_idx = batch_idx * BATCH_SIZE
    end_idx = min(start_idx + BATCH_SIZE, len(all_prompts))
    
    batch_prompts = all_prompts[start_idx:end_idx]
    batch_questions = all_questions[start_idx:end_idx]
    batch_ground_truths = all_ground_truths[start_idx:end_idx]
    
    # Calculate actual sequence lengths
    batch_lengths = [len(tokenizer.encode(p)) for p in batch_prompts]
    avg_seq_len = sum(batch_lengths) / len(batch_lengths)
    max_seq_len = max(batch_lengths)
    min_seq_len = min(batch_lengths)
    
    # Start monitoring
    start_time = time.time()
    cpu_percent = psutil.cpu_percent(interval=None)
    memory_percent = psutil.virtual_memory().percent
    
    if torch.cuda.is_available():
        torch.cuda.reset_peak_memory_stats()
        gpu_memory_start = torch.cuda.memory_allocated() / 1024**2
    
    # Run batched inference
    outputs = continuous_batching_llm.generate(batch_prompts, continuous_sampling_params)
    
    # End monitoring
    end_time = time.time()
    inference_time = end_time - start_time
    per_sample_time = inference_time / len(batch_prompts)
    variable_length_times.append(inference_time)
    
    gpu_memory = None
    if torch.cuda.is_available():
        gpu_memory_end = torch.cuda.memory_allocated() / 1024**2
        gpu_memory = max(gpu_memory_end, gpu_memory_start)
    
    # Process outputs
    for i, output in enumerate(outputs):
        response = output.outputs[0].text
        num_tokens = len(output.outputs[0].token_ids)
        
        prompt_len = batch_lengths[i]
        generation_len = num_tokens
        
        continuous_batching_evaluator.add_result(
            question=batch_questions[i],
            ground_truth=batch_ground_truths[i],
            response=response,
            num_tokens=num_tokens,
            inference_time=per_sample_time,
            cpu_percent=cpu_percent,
            memory_percent=memory_percent,
            gpu_memory=gpu_memory,
            prompt_length=prompt_len,
            generation_length=generation_len,
        )
        
        rouge_scores = compute_rouge_scores(batch_ground_truths[i], response)
        bleu_score = compute_bleu_score(batch_ground_truths[i], response)
        continuous_batching_evaluator.add_accuracy_metrics(rouge_scores, bleu_score)
    
    total_samples_processed += len(batch_prompts)
    
    print(f"\nBatch {batch_idx + 1}/{num_batches}:")
    print(f"  Samples: {len(batch_prompts)}")
    print(f"  Sequence lengths - Avg: {avg_seq_len:.1f}, Min: {min_seq_len}, Max: {max_seq_len}")
    print(f"  Batch time: {inference_time:.3f}s, Per sample: {per_sample_time:.3f}s")
    print(f"  Throughput: {len(batch_prompts) / inference_time:.1f} samples/s")

# Get comprehensive metrics and display results (same as before)
continuous_batching_metrics = continuous_batching_evaluator.get_summary()
total_batch_time = sum(variable_length_times)
avg_batch_time = total_batch_time / len(variable_length_times)

continuous_batching_metrics.update({
    'avg_batch_time': avg_batch_time,
    'total_batches': len(variable_length_times),
})

continuous_batching_evaluator.print_report(baseline_metrics)

print("\n Continuous/Paged Batching evaluation completed!")

================================================================================
CONTINUOUS/PAGED BATCHING WITH VLLM
================================================================================
Variable-length sequences with non-contiguous memory

2026-02-20 14:40:52.608925: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2026-02-20 14:40:52.608987: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2026-02-20 14:40:52.610243: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2026-02-20 14:40:52.615934: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2026-02-20 14:40:53.553494: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

(EngineCore_DP0 pid=5089) INFO 02-20 14:40:57 [core.py:96] Initializing a V1 LLM engine (v0.15.1) with config: model='./gemma-3-270m-finetuned-qa-optimized/inference_optimized', speculative_config=None, tokenizer='./gemma-3-270m-finetuned-qa-optimized/inference_optimized', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=228, download_dir=None, load_format=bitsandbytes, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, disable_custom_all_reduce=False, quantization=bitsandbytes, enforce_eager=True, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=./gemma-3-270m-finetuned-qa-optimized/inference_optimized, enable_prefix_caching=False, enable_chunked_prefill=True, pooler_config=None, compilation_config={'level': None, 'mode': <CompilationMode.NONE: 0>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['all'], 'splitting_ops': [], 'compile_mm_encoder': False, 'compile_sizes': [], 'compile_ranges_split_points': [4096], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.NONE: 0>, 'cudagraph_num_of_warmups': 0, 'cudagraph_capture_sizes': [], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'eliminate_noops': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False}, 'max_cudagraph_capture_size': 0, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': True}, 'local_cache_dir': None, 'static_all_moe_layers': []}
(EngineCore_DP0 pid=5089) INFO 02-20 14:40:57 [parallel_state.py:1212] world_size=1 rank=0 local_rank=0 distributed_init_method=tcp://10.39.217.11:40059 backend=nccl
(EngineCore_DP0 pid=5089) INFO 02-20 14:40:57 [parallel_state.py:1423] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank N/A
(EngineCore_DP0 pid=5089) INFO 02-20 14:40:58 [gpu_model_runner.py:4033] Starting to load model ./gemma-3-270m-finetuned-qa-optimized/inference_optimized...
(EngineCore_DP0 pid=5089) INFO 02-20 14:41:00 [cuda.py:364] Using FLASH_ATTN attention backend out of potential backends: ('FLASH_ATTN', 'FLASHINFER', 'TRITON_ATTN', 'FLEX_ATTENTION')
(EngineCore_DP0 pid=5089) INFO 02-20 14:41:00 [bitsandbytes_loader.py:786] Loading weights with BitsAndBytes quantization. May take a while ...

Loading safetensors checkpoint shards:   0% Completed | 0/1 [00:00<?, ?it/s]
Loading safetensors checkpoint shards: 100% Completed | 1/1 [00:00<00:00, 51.54it/s]
(EngineCore_DP0 pid=5089)
Loading safetensors checkpoint shards:   0% Completed | 0/1 [00:00<?, ?it/s]
Loading safetensors checkpoint shards: 100% Completed | 1/1 [00:00<00:00,  2.53it/s]
Loading safetensors checkpoint shards: 100% Completed | 1/1 [00:00<00:00,  2.53it/s]
(EngineCore_DP0 pid=5089)

(EngineCore_DP0 pid=5089) INFO 02-20 14:41:01 [gpu_model_runner.py:4130] Model loading took 0.4 GiB memory and 1.882614 seconds
(EngineCore_DP0 pid=5089) INFO 02-20 14:41:03 [gpu_worker.py:356] Available KV cache memory: 11.33 GiB
(EngineCore_DP0 pid=5089) INFO 02-20 14:41:03 [kv_cache_utils.py:1307] GPU KV cache size: 660,112 tokens
(EngineCore_DP0 pid=5089) INFO 02-20 14:41:03 [kv_cache_utils.py:1312] Maximum concurrency for 228 tokens per request: 2605.76x
(EngineCore_DP0 pid=5089) INFO 02-20 14:41:04 [core.py:272] init engine (profile, create kv cache, warmup model) took 2.94 seconds
(EngineCore_DP0 pid=5089) INFO 02-20 14:41:07 [vllm.py:624] Asynchronous scheduling is enabled.
(EngineCore_DP0 pid=5089) WARNING 02-20 14:41:07 [vllm.py:669] Inductor compilation was disabled by user settings, optimizations settings that are only active during inductor compilation will be ignored.
(EngineCore_DP0 pid=5089) INFO 02-20 14:41:07 [vllm.py:762] Cudagraph is disabled under eager mode

Continuous/Paged Batching Configuration:

Processing 24 samples with variable-length sequences...

Adding requests:   0%|          | 0/8 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/8 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Batch 1/3:
  Samples: 8
  Sequence lengths - Avg: 16.9, Min: 14, Max: 20
  Batch time: 4.303s, Per sample: 0.538s
  Throughput: 1.9 samples/s

Adding requests:   0%|          | 0/8 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/8 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Batch 2/3:
  Samples: 8
  Sequence lengths - Avg: 13.6, Min: 10, Max: 19
  Batch time: 4.312s, Per sample: 0.539s
  Throughput: 1.9 samples/s

Adding requests:   0%|          | 0/8 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/8 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

Batch 3/3:
  Samples: 8
  Sequence lengths - Avg: 16.2, Min: 10, Max: 22
  Batch time: 4.196s, Per sample: 0.525s
  Throughput: 1.9 samples/s

================================================================================
EVALUATION REPORT: Continuous/Paged Batching
================================================================================

PERFORMANCE METRICS:
----------------------------------------
  Average Inference Time: 0.534s
  P95 Inference Time: 0.539s
  Total Inference Time: 12.81s
  Average Throughput: 187.4 tokens/s
  Total Tokens Generated: 2,400

RESOURCE USAGE:
----------------------------------------
  Average CPU: 23.8%
  Average Memory: 14.2%

ACCURACY METRICS:
----------------------------------------
  ROUGE-1 F1: 0.1314
  ROUGE-2 F1: 0.0105
  ROUGE-L F1: 0.1035
  BLEU Score: 0.0078

COMPARED TO BASELINE:
----------------------------------------
  Speedup: 1.03x
  Throughput Improvement: 3.3%

================================================================================

 Continuous/Paged Batching evaluation completed!

**Reference**
- [Arxiv:Batch Speculative Decoding Done Right](https://arxiv.org/html/2510.22876v3)
- [vLLM:Welcome to vLLM](https://docs.vllm.ai/en/latest/)
- [vLLm:Sampling Parameters](https://docs.vllm.ai/en/v0.6.4/dev/sampling_params.html)
- [vLLM:Batch LLM Inference](https://docs.vllm.ai/en/latest/examples/offline_inference/batch_llm_inference/)
- [Huggingface:Continuous batching](https://huggingface.co/blog/continuous_batching)
- [Medium:PagedAttention vs Continuous Batching vs vLLM vs SGLang — A Practical Breakdown](https://python.plainenglish.io/pagedattention-vs-continuous-batching-vs-vllm-vs-sglang-a-practical-breakdown-4c19cc9e21c0)

### Speculative Decoding

Speculative Decoding (or Assisted Generation) is an inference optimization technique that accelerates Large Language Models (LLMs) without compromising the quality of the output.

Standard LLM generation is autoregressive, meaning the model must finish calculating one word before it can even begin thinking about the next. This creates a bottleneck because even a giant 70B parameter model must perform a full "forward pass" (a massive mathematical calculation) to generate simple, predictable words like "of" or "the."

Speculative Decoding breaks this sequential bottleneck by using a "Draft-then-Verify" workflow:
- Drafting: A much smaller, faster "draft" model (the assistant) quickly guesses the next K tokens (usually 3 to 5).
- Verification: The large "target" model (the scientist) looks at all K guesses at once in a single forward pass.
- Acceptance: The target model accepts the guesses that match its own logic. If it finds a mistake, it rejects the remaining guesses, provides the correct token, and the cycle repeats.

Because the target model can verify five tokens in nearly the same time it takes to generate one, a high "acceptance rate" leads to a 2x to 3x speedup.

**Speculative Decoding Implementation**

The provided code uses the vLLM framework to orchestrate the interaction between the fine-tuned Gemma-3 model and a smaller draft model.

**1. Model Coordination**

The code attempts to load a second, smaller model defined by `DRAFT_MODEL_PATH`.

    spec_decode_kwargs["speculative_model"] = draft_model
    spec_decode_kwargs["num_speculative_tokens"] = 5

By passing draft_model into the main LLM object, vLLM creates a synchronized engine. The num_speculative_tokens=5 setting instructs the draft model to look exactly five steps ahead during every cycle.

**2. Verification Logic**

When `spec_decode_llm.generate()` is called:
- The small draft model runs five rapid iterations.
- The main model performs one large calculation. It uses a multi-token verification kernel that checks the draft tokens in parallel.
- The engine automatically manages the KV Cache (memory) for both models, ensuring they stay "in sync" even when the draft model's guesses are rejected.

**3. Handling Configuration Incompatibility**

The code includes a `patch_model_config` function specifically because speculative decoding requires the draft and target models to share the same tokenizer and compatible architectural settings (like RoPE parameters). The patch ensures the configuration files match so the engine doesn't crash during the parallel verification step.

**When to Use Speculative Decoding**

Speculative Decoding is a powerful tool, but it is not a "magic button" for every situation. It is most effective in the following scenarios:
- Low-Latency Applications: Use it for real-time chatbots or coding assistants where the user is waiting for text to appear on the screen.
- Memory-Bound Inference: Since GPUs are often faster at math than they are at moving data from memory, using the "idle" compute power of the GPU to verify multiple tokens actually saves time.
- Highly Predictable Tasks: It excels at code generation or formal writing (like legal or medical summaries) where the draft model can easily guess common syntax and boilerplate phrases.
- Large Parameter Gaps: It works best when the draft model is significantly smaller (at least 10x to 50x smaller) than the target model. If the draft model is too large, the time spent "guessing" outweighs the time saved "verifying."

In [5]:
print("\n" + "="*80)
print("SETUP AND CONFIGURATION")
print("="*80)

import json
import os
from vllm import LLM, SamplingParams

# Fix the configuration file to include required rope_parameters
def patch_model_config(model_path):
    config_path = os.path.join(model_path, "config.json")
    if os.path.exists(config_path):
        with open(config_path, 'r') as f:
            config = json.load(f)
        
        # Add rope_parameters if missing
        if "rope_parameters" not in config:
            config["rope_parameters"] = {
                "rope_type": "default",
                "factor": 1.0,
                "theta": 10000.0,
            }
        elif "rope_type" not in config["rope_parameters"]:
            config["rope_parameters"]["rope_type"] = "default"
        
        with open(config_path, 'w') as f:
            json.dump(config, f, indent=2)
        print(f"Patched configuration: {config_path}")

# Apply the fix to your model path
patch_model_config(MODEL_PATH)

# Common sampling parameters
base_sampling_params = SamplingParams(
    temperature=0.0,
    max_tokens=MAX_NEW_TOKENS,
    stop_token_ids=[tokenizer.eos_token_id],
    skip_special_tokens=True,
)

================================================================================
SETUP AND CONFIGURATION
================================================================================
Patched configuration: ./gemma-3-270m-finetuned-qa-optimized/inference_optimized/config.json

In [6]:
print("\n" + "="*80)
print("SPECULATIVE DECODING EVALUATION")
print("="*80)

MODEL_PATH = "google/gemma-3-1b-it"

spec_decode_evaluator = ServingOptimizationEvaluator("Speculative Decoding")

# Note: Gemma-3-270m-draft doesn't exist on HuggingFace
# For speculative decoding, you need a smaller version of the same model family
# Using a smaller available model or the same model with speculative decoding disabled
print("\nNOTE: Speculative decoding requires a separate draft model.")
print("If no draft model is available, this will use the same model (no speedup).")

try:
    draft_model = LLM(
        model=DRAFT_MODEL_PATH, 
        tensor_parallel_size=1,
        dtype="bfloat16",
        max_model_len=MAX_LENGTH + MAX_NEW_TOKENS,
        enforce_eager=True,
    )
    print(f"Using draft model: {DRAFT_MODEL_PATH}")
    use_spec_decode = True
except Exception as e:
    print(f"Draft model not found: {e}")
    print("Using same model for both draft and target (no speculative benefit)")
    draft_model = None
    use_spec_decode = False

# Load main model with speculative decoding if available
spec_decode_kwargs = {
    "model": MODEL_PATH,
    "tensor_parallel_size": 1,
    "dtype": "bfloat16",
    "max_model_len": MAX_LENGTH + MAX_NEW_TOKENS,
    "enforce_eager": True,
}

if use_spec_decode and draft_model:
    spec_decode_kwargs["speculative_model"] = draft_model
    spec_decode_kwargs["num_speculative_tokens"] = 5

spec_decode_llm = LLM(**spec_decode_kwargs)

# Use base sampling params
sampling_params = base_sampling_params

# Run inference
for batch_idx in range(num_batches):
    start_idx = batch_idx * BATCH_SIZE
    end_idx = min(start_idx + BATCH_SIZE, len(all_prompts))
    batch_prompts = all_prompts[start_idx:end_idx]
    batch_questions = all_questions[start_idx:end_idx]
    batch_ground_truths = all_ground_truths[start_idx:end_idx]
    
    start_time = time.time()
    cpu_percent = psutil.cpu_percent(interval=None)
    memory_percent = psutil.virtual_memory().percent
    
    if torch.cuda.is_available():
        torch.cuda.reset_peak_memory_stats()
        gpu_memory_start = torch.cuda.memory_allocated() / 1024**2
    
    outputs = spec_decode_llm.generate(batch_prompts, sampling_params)
    
    end_time = time.time()
    inference_time = end_time - start_time
    per_sample_time = inference_time / len(batch_prompts)
    
    gpu_memory = None
    if torch.cuda.is_available():
        gpu_memory_end = torch.cuda.memory_allocated() / 1024**2
        gpu_memory = max(gpu_memory_end, gpu_memory_start)
    
    for i, output in enumerate(outputs):
        response = output.outputs[0].text
        num_tokens = len(output.outputs[0].token_ids)
        
        # Only track speculative tokens if enabled
        speculative_tokens = num_tokens // 3 if use_spec_decode else 0
        
        spec_decode_evaluator.add_result(
            question=batch_questions[i],
            ground_truth=batch_ground_truths[i],
            response=response,
            num_tokens=num_tokens,
            inference_time=per_sample_time,
            cpu_percent=cpu_percent,
            memory_percent=memory_percent,
            gpu_memory=gpu_memory,
            speculative_tokens=speculative_tokens,
        )
        
        rouge_scores = compute_rouge_scores(batch_ground_truths[i], response)
        bleu_score = compute_bleu_score(batch_ground_truths[i], response)
        spec_decode_evaluator.add_accuracy_metrics(rouge_scores, bleu_score)
    
    print(f"  Batch {batch_idx + 1}/{num_batches} completed")

spec_decode_evaluator.print_report(baseline_metrics)

# Cleanup
if use_spec_decode and draft_model:
    del draft_model
del spec_decode_llm
torch.cuda.empty_cache()
gc.collect()

================================================================================
SPECULATIVE DECODING EVALUATION
================================================================================

NOTE: Speculative decoding requires a separate draft model.
If no draft model is available, this will use the same model (no speedup).
INFO 02-20 14:43:30 [utils.py:261] non-default args: {'dtype': 'bfloat16', 'max_model_len': 228, 'disable_log_stats': True, 'enforce_eager': True, 'model': 'google/gemma-3-270m-draft'}
Draft model not found: google/gemma-3-270m-draft is not a local folder and is not a valid model identifier listed on 'https://huggingface.co/models'
If this is a private repository, make sure to pass a token having permission to this repo either by logging in with `hf auth login` or by passing `token=<your_token>`
Using same model for both draft and target (no speculative benefit)
INFO 02-20 14:43:30 [utils.py:261] non-default args: {'dtype': 'bfloat16', 'max_model_len': 228, 'disable_log_stats': True, 'enforce_eager': True, 'model': 'google/gemma-3-1b-it'}
INFO 02-20 14:43:30 [model.py:541] Resolved architecture: Gemma3ForCausalLM
INFO 02-20 14:43:30 [model.py:1561] Using max model len 228
INFO 02-20 14:43:30 [scheduler.py:226] Chunked prefill is enabled with max_num_batched_tokens=8192.
WARNING 02-20 14:43:30 [vllm.py:662] Enforce eager set, overriding optimization level to -O0
INFO 02-20 14:43:30 [vllm.py:762] Cudagraph is disabled under eager mode
WARNING 02-20 14:43:32 [system_utils.py:140] We must use the `spawn` multiprocessing start method. Overriding VLLM_WORKER_MULTIPROC_METHOD to 'spawn'. See https://docs.vllm.ai/en/latest/usage/troubleshooting.html#python-multiprocessing for more information. Reasons: CUDA is initialized

2026-02-20 14:43:35.946673: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2026-02-20 14:43:35.946724: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2026-02-20 14:43:35.948025: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2026-02-20 14:43:35.953754: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2026-02-20 14:43:36.931352: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

(EngineCore_DP0 pid=5607) INFO 02-20 14:43:39 [core.py:96] Initializing a V1 LLM engine (v0.15.1) with config: model='google/gemma-3-1b-it', speculative_config=None, tokenizer='google/gemma-3-1b-it', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=228, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=True, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=google/gemma-3-1b-it, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'level': None, 'mode': <CompilationMode.NONE: 0>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['all'], 'splitting_ops': [], 'compile_mm_encoder': False, 'compile_sizes': [], 'compile_ranges_split_points': [8192], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.NONE: 0>, 'cudagraph_num_of_warmups': 0, 'cudagraph_capture_sizes': [], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'eliminate_noops': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False}, 'max_cudagraph_capture_size': 0, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': True}, 'local_cache_dir': None, 'static_all_moe_layers': []}
(EngineCore_DP0 pid=5607) INFO 02-20 14:43:40 [parallel_state.py:1212] world_size=1 rank=0 local_rank=0 distributed_init_method=tcp://10.39.217.11:36531 backend=nccl
(EngineCore_DP0 pid=5607) INFO 02-20 14:43:40 [parallel_state.py:1423] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank N/A
(EngineCore_DP0 pid=5607) INFO 02-20 14:43:41 [gpu_model_runner.py:4033] Starting to load model google/gemma-3-1b-it...
(EngineCore_DP0 pid=5607) INFO 02-20 14:43:42 [cuda.py:364] Using FLASH_ATTN attention backend out of potential backends: ('FLASH_ATTN', 'FLASHINFER', 'TRITON_ATTN', 'FLEX_ATTENTION')
(EngineCore_DP0 pid=5607) INFO 02-20 14:43:42 [weight_utils.py:567] No model.safetensors.index.json found in remote.

Loading safetensors checkpoint shards:   0% Completed | 0/1 [00:00<?, ?it/s]
Loading safetensors checkpoint shards: 100% Completed | 1/1 [00:00<00:00,  2.95it/s]
Loading safetensors checkpoint shards: 100% Completed | 1/1 [00:00<00:00,  2.95it/s]
(EngineCore_DP0 pid=5607)

(EngineCore_DP0 pid=5607) INFO 02-20 14:43:42 [default_loader.py:291] Loading weights took 0.39 seconds
(EngineCore_DP0 pid=5607) INFO 02-20 14:43:43 [gpu_model_runner.py:4130] Model loading took 1.91 GiB memory and 1.064374 seconds
(EngineCore_DP0 pid=5607) INFO 02-20 14:43:47 [gpu_worker.py:356] Available KV cache memory: 9.8 GiB
(EngineCore_DP0 pid=5607) WARNING 02-20 14:43:47 [kv_cache_utils.py:1047] Add 2 padding layers, may waste at most 9.09% KV cache memory
(EngineCore_DP0 pid=5607) INFO 02-20 14:43:47 [kv_cache_utils.py:1307] GPU KV cache size: 366,992 tokens
(EngineCore_DP0 pid=5607) INFO 02-20 14:43:47 [kv_cache_utils.py:1312] Maximum concurrency for 228 tokens per request: 1446.48x
(EngineCore_DP0 pid=5607) INFO 02-20 14:43:47 [core.py:272] init engine (profile, create kv cache, warmup model) took 3.91 seconds
(EngineCore_DP0 pid=5607) INFO 02-20 14:43:49 [vllm.py:624] Asynchronous scheduling is enabled.
(EngineCore_DP0 pid=5607) WARNING 02-20 14:43:49 [vllm.py:669] Inductor compilation was disabled by user settings, optimizations settings that are only active during inductor compilation will be ignored.
(EngineCore_DP0 pid=5607) INFO 02-20 14:43:49 [vllm.py:762] Cudagraph is disabled under eager mode
INFO 02-20 14:43:49 [llm.py:343] Supported tasks: ['generate']

Adding requests:   0%|          | 0/8 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/8 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

[2026-02-20 14:43:53] INFO rouge_scorer.py:83: Using default tokenizer.
[2026-02-20 14:43:53] INFO rouge_scorer.py:83: Using default tokenizer.
[2026-02-20 14:43:53] INFO rouge_scorer.py:83: Using default tokenizer.
[2026-02-20 14:43:53] INFO rouge_scorer.py:83: Using default tokenizer.
[2026-02-20 14:43:53] INFO rouge_scorer.py:83: Using default tokenizer.
[2026-02-20 14:43:53] INFO rouge_scorer.py:83: Using default tokenizer.
[2026-02-20 14:43:53] INFO rouge_scorer.py:83: Using default tokenizer.
[2026-02-20 14:43:53] INFO rouge_scorer.py:83: Using default tokenizer.

  Batch 1/3 completed

Adding requests:   0%|          | 0/8 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/8 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

[2026-02-20 14:43:56] INFO rouge_scorer.py:83: Using default tokenizer.
[2026-02-20 14:43:56] INFO rouge_scorer.py:83: Using default tokenizer.
[2026-02-20 14:43:56] INFO rouge_scorer.py:83: Using default tokenizer.
[2026-02-20 14:43:56] INFO rouge_scorer.py:83: Using default tokenizer.
[2026-02-20 14:43:56] INFO rouge_scorer.py:83: Using default tokenizer.
[2026-02-20 14:43:56] INFO rouge_scorer.py:83: Using default tokenizer.
[2026-02-20 14:43:56] INFO rouge_scorer.py:83: Using default tokenizer.
[2026-02-20 14:43:56] INFO rouge_scorer.py:83: Using default tokenizer.

  Batch 2/3 completed

Adding requests:   0%|          | 0/8 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/8 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

[2026-02-20 14:43:59] INFO rouge_scorer.py:83: Using default tokenizer.
[2026-02-20 14:43:59] INFO rouge_scorer.py:83: Using default tokenizer.
[2026-02-20 14:43:59] INFO rouge_scorer.py:83: Using default tokenizer.
[2026-02-20 14:43:59] INFO rouge_scorer.py:83: Using default tokenizer.
[2026-02-20 14:43:59] INFO rouge_scorer.py:83: Using default tokenizer.
[2026-02-20 14:43:59] INFO rouge_scorer.py:83: Using default tokenizer.
[2026-02-20 14:43:59] INFO rouge_scorer.py:83: Using default tokenizer.
[2026-02-20 14:43:59] INFO rouge_scorer.py:83: Using default tokenizer.
[rank0]:[W220 14:43:59.778810398 ProcessGroupNCCL.cpp:1524] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

  Batch 3/3 completed

================================================================================
EVALUATION REPORT: Speculative Decoding
================================================================================

PERFORMANCE METRICS:
----------------------------------------
  Average Inference Time: 0.402s
  P95 Inference Time: 0.403s
  Total Inference Time: 9.65s
  Average Throughput: 248.8 tokens/s
  Total Tokens Generated: 2,400

SPECULATIVE DECODING METRICS:
----------------------------------------
  Speculative Acceptance Rate: 0.0%
  Expected Speedup: 2-3x

RESOURCE USAGE:
----------------------------------------
  Average CPU: 16.8%
  Average Memory: 14.3%

ACCURACY METRICS:
----------------------------------------
  ROUGE-1 F1: 0.2195
  ROUGE-2 F1: 0.0403
  ROUGE-L F1: 0.1346
  BLEU Score: 0.0204

COMPARED TO BASELINE:
----------------------------------------
  Speedup: 1.32x
  Throughput Improvement: 32.2%

================================================================================

27

**Reference**
- [vLLM:Welcome to vLLM](https://docs.vllm.ai/en/latest/)
- [vLLm:Sampling Parameters](https://docs.vllm.ai/en/v0.6.4/dev/sampling_params.html)
- [vLLM:Speculative Decoding](https://docs.vllm.ai/en/latest/features/speculative_decoding/)
- [vLLM:Speculative decoding in vLLM](https://docs.vllm.ai/en/v0.6.0/models/spec_decode.html)
- [Arxiv:Fast Inference from Transformers via Speculative Decoding](https://arxiv.org/abs/2211.17192)

### Medusa

Medusa is an advanced speculative decoding architecture designed to accelerate LLM inference without requiring a separate draft model. In standard speculative decoding, a smaller "assistant" model predicts future tokens. Medusa replaces this external model with multiple "heads" (extra neural network layers) attached directly to the last hidden state of the original model.

Each Medusa head is trained to predict a token at a specific future position. For instance, Head 1 predicts the next token (t+1), Head 2 predicts the token after that (t+2), and so on.

**The Tree-Based Verification Process**

Unlike standard speculative decoding, which verifies a single linear sequence of tokens, Medusa uses a Tree-based Verification mechanism.
- Multiple Candidates: Each Medusa head proposes several top candidates for its respective position.
- Cartesian Product Tree: These candidates are combined to form a "tree" of many potential sentence branches.
- Parallel Verification: The base model uses a specialized attention mask to verify every branch of the tree simultaneously in a single forward pass.
- Longest Valid Path: The system identifies the longest path in the tree that the model's primary logic agrees with and accepts those tokens.

**Medusa Implementation**

The provided code acts as a testing framework that highlights the specific requirements for Medusa.
- Architectural Dependency: The code explicitly notes that Medusa is not a "plug-and-play" software switch. It requires a model that has been physically modified with Medusa heads and fine-tuned accordingly.
- Fallback Logic: Because the standard Gemma-3 model path provided (`MODEL_PATH`) does not contain these extra prediction heads, the code demonstrates a "fallback" scenario. It initializes a standard LLM object without Medusa parameters to prevent the script from crashing.
- Metric Tracking: The `medusa_evaluator.add_result` function includes a `medusa_size` parameter. In a functional Medusa setup, this would track the "tree size" (the number of candidate branches verified per step), which is a key indicator of how aggressive the speculation is.
- Configuration Patching: The `patch_model_config` function is vital here because Medusa heads require specific weight names and configuration entries in the `config.json` to be recognized by inference engines like vLLM.

**When to Use Medusa**

Medusa is highly effective in specific high-performance environments:
- Single-GPU Setups: Since Medusa doesn't require loading a second draft model, it saves VRAM that would otherwise be used to store the assistant model's weights.
- Maximum Latency Reduction: Because it uses tree-based verification, Medusa often finds longer "accepted" sequences than linear speculative decoding, resulting in higher speedups (often exceeding 2x).
- Training Flexibility: Medusa heads can be trained while the base model stays "frozen." This allows for adding acceleration to an existing model without changing its fundamental behavior or knowledge.
- Production Serving: It is ideal for high-traffic endpoints where reducing the "Time Per Output Token" (TPOT) is the primary goal to improve user experience.

In [7]:
print("\n" + "="*80)
print("SETUP AND CONFIGURATION")
print("="*80)

import json
import os
from vllm import LLM, SamplingParams

# Fix the configuration file to include required rope_parameters
def patch_model_config(model_path):
    config_path = os.path.join(model_path, "config.json")
    if os.path.exists(config_path):
        with open(config_path, 'r') as f:
            config = json.load(f)
        
        # Add rope_parameters if missing
        if "rope_parameters" not in config:
            config["rope_parameters"] = {
                "rope_type": "default",
                "factor": 1.0,
                "theta": 10000.0,
            }
        elif "rope_type" not in config["rope_parameters"]:
            config["rope_parameters"]["rope_type"] = "default"
        
        with open(config_path, 'w') as f:
            json.dump(config, f, indent=2)
        print(f"Patched configuration: {config_path}")

# Apply the fix to your model path
patch_model_config(MODEL_PATH)

# Common sampling parameters
base_sampling_params = SamplingParams(
    temperature=0.0,
    max_tokens=MAX_NEW_TOKENS,
    stop_token_ids=[tokenizer.eos_token_id],
    skip_special_tokens=True,
)

================================================================================
SETUP AND CONFIGURATION
================================================================================

In [8]:
print("\n" + "="*80)
print("MEDUSA EVALUATION")
print("="*80)

medusa_evaluator = ServingOptimizationEvaluator("Medusa")

# Medusa requires a model specifically trained with Medusa heads
# Standard models don't support the 'use_medusa' parameter
print("\nNOTE: Medusa requires a model specifically fine-tuned with Medusa heads.")

# Load standard model (Medusa not available for this model)
medusa_llm = LLM(
    model=MODEL_PATH,
    tensor_parallel_size=1,
    dtype="bfloat16",
    max_model_len=MAX_LENGTH + MAX_NEW_TOKENS,
    enforce_eager=True,
    # Remove unsupported Medusa parameters
)

# Use base sampling params (remove medusa-specific params)
sampling_params = base_sampling_params

# Run inference
for batch_idx in range(num_batches):
    start_idx = batch_idx * BATCH_SIZE
    end_idx = min(start_idx + BATCH_SIZE, len(all_prompts))
    batch_prompts = all_prompts[start_idx:end_idx]
    batch_questions = all_questions[start_idx:end_idx]
    batch_ground_truths = all_ground_truths[start_idx:end_idx]
    
    start_time = time.time()
    cpu_percent = psutil.cpu_percent(interval=None)
    memory_percent = psutil.virtual_memory().percent
    
    if torch.cuda.is_available():
        torch.cuda.reset_peak_memory_stats()
        gpu_memory_start = torch.cuda.memory_allocated() / 1024**2
    
    outputs = medusa_llm.generate(batch_prompts, sampling_params)
    
    end_time = time.time()
    inference_time = end_time - start_time
    per_sample_time = inference_time / len(batch_prompts)
    
    gpu_memory = None
    if torch.cuda.is_available():
        gpu_memory_end = torch.cuda.memory_allocated() / 1024**2
        gpu_memory = max(gpu_memory_end, gpu_memory_start)
    
    for i, output in enumerate(outputs):
        response = output.outputs[0].text
        num_tokens = len(output.outputs[0].token_ids)
        
        medusa_evaluator.add_result(
            question=batch_questions[i],
            ground_truth=batch_ground_truths[i],
            response=response,
            num_tokens=num_tokens,
            inference_time=per_sample_time,
            cpu_percent=cpu_percent,
            memory_percent=memory_percent,
            gpu_memory=gpu_memory,
            medusa_size=0,  # Medusa not available
        )
        
        rouge_scores = compute_rouge_scores(batch_ground_truths[i], response)
        bleu_score = compute_bleu_score(batch_ground_truths[i], response)
        medusa_evaluator.add_accuracy_metrics(rouge_scores, bleu_score)
    
    print(f"  Batch {batch_idx + 1}/{num_batches} completed")

medusa_evaluator.print_report(baseline_metrics)

# Cleanup
del medusa_llm
torch.cuda.empty_cache()
gc.collect()

================================================================================
MEDUSA EVALUATION
================================================================================

NOTE: Medusa requires a model specifically fine-tuned with Medusa heads.
INFO 02-20 14:44:00 [utils.py:261] non-default args: {'dtype': 'bfloat16', 'max_model_len': 228, 'disable_log_stats': True, 'enforce_eager': True, 'model': 'google/gemma-3-1b-it'}
INFO 02-20 14:44:00 [model.py:541] Resolved architecture: Gemma3ForCausalLM
INFO 02-20 14:44:00 [model.py:1561] Using max model len 228
INFO 02-20 14:44:00 [scheduler.py:226] Chunked prefill is enabled with max_num_batched_tokens=8192.
WARNING 02-20 14:44:00 [vllm.py:662] Enforce eager set, overriding optimization level to -O0
INFO 02-20 14:44:00 [vllm.py:762] Cudagraph is disabled under eager mode

2026-02-20 14:44:04.142196: E external/local_xla/xla/stream_executor/cuda/cuda_dnn.cc:9261] Unable to register cuDNN factory: Attempting to register factory for plugin cuDNN when one has already been registered
2026-02-20 14:44:04.142258: E external/local_xla/xla/stream_executor/cuda/cuda_fft.cc:607] Unable to register cuFFT factory: Attempting to register factory for plugin cuFFT when one has already been registered
2026-02-20 14:44:04.143287: E external/local_xla/xla/stream_executor/cuda/cuda_blas.cc:1515] Unable to register cuBLAS factory: Attempting to register factory for plugin cuBLAS when one has already been registered
2026-02-20 14:44:04.149007: I tensorflow/core/platform/cpu_feature_guard.cc:182] This TensorFlow binary is optimized to use available CPU instructions in performance-critical operations.
To enable the following instructions: AVX2 FMA, in other operations, rebuild TensorFlow with the appropriate compiler flags.
2026-02-20 14:44:05.078185: W tensorflow/compiler/tf2tensorrt/utils/py_utils.cc:38] TF-TRT Warning: Could not find TensorRT

(EngineCore_DP0 pid=5737) INFO 02-20 14:44:07 [core.py:96] Initializing a V1 LLM engine (v0.15.1) with config: model='google/gemma-3-1b-it', speculative_config=None, tokenizer='google/gemma-3-1b-it', skip_tokenizer_init=False, tokenizer_mode=auto, revision=None, tokenizer_revision=None, trust_remote_code=False, dtype=torch.bfloat16, max_seq_len=228, download_dir=None, load_format=auto, tensor_parallel_size=1, pipeline_parallel_size=1, data_parallel_size=1, disable_custom_all_reduce=False, quantization=None, enforce_eager=True, enable_return_routed_experts=False, kv_cache_dtype=auto, device_config=cuda, structured_outputs_config=StructuredOutputsConfig(backend='auto', disable_fallback=False, disable_any_whitespace=False, disable_additional_properties=False, reasoning_parser='', reasoning_parser_plugin='', enable_in_reasoning=False), observability_config=ObservabilityConfig(show_hidden_metrics_for_version=None, otlp_traces_endpoint=None, collect_detailed_traces=None, kv_cache_metrics=False, kv_cache_metrics_sample=0.01, cudagraph_metrics=False, enable_layerwise_nvtx_tracing=False, enable_mfu_metrics=False, enable_mm_processor_stats=False, enable_logging_iteration_details=False), seed=0, served_model_name=google/gemma-3-1b-it, enable_prefix_caching=True, enable_chunked_prefill=True, pooler_config=None, compilation_config={'level': None, 'mode': <CompilationMode.NONE: 0>, 'debug_dump_path': None, 'cache_dir': '', 'compile_cache_save_format': 'binary', 'backend': 'inductor', 'custom_ops': ['all'], 'splitting_ops': [], 'compile_mm_encoder': False, 'compile_sizes': [], 'compile_ranges_split_points': [8192], 'inductor_compile_config': {'enable_auto_functionalized_v2': False, 'combo_kernels': True, 'benchmark_combo_kernel': True}, 'inductor_passes': {}, 'cudagraph_mode': <CUDAGraphMode.NONE: 0>, 'cudagraph_num_of_warmups': 0, 'cudagraph_capture_sizes': [], 'cudagraph_copy_inputs': False, 'cudagraph_specialize_lora': True, 'use_inductor_graph_partition': False, 'pass_config': {'fuse_norm_quant': False, 'fuse_act_quant': False, 'fuse_attn_quant': False, 'eliminate_noops': False, 'enable_sp': False, 'fuse_gemm_comms': False, 'fuse_allreduce_rms': False}, 'max_cudagraph_capture_size': 0, 'dynamic_shapes_config': {'type': <DynamicShapesType.BACKED: 'backed'>, 'evaluate_guards': False, 'assume_32_bit_indexing': True}, 'local_cache_dir': None, 'static_all_moe_layers': []}
(EngineCore_DP0 pid=5737) INFO 02-20 14:44:08 [parallel_state.py:1212] world_size=1 rank=0 local_rank=0 distributed_init_method=tcp://10.39.217.11:34337 backend=nccl
(EngineCore_DP0 pid=5737) INFO 02-20 14:44:08 [parallel_state.py:1423] rank 0 in world size 1 is assigned as DP rank 0, PP rank 0, PCP rank 0, TP rank 0, EP rank N/A
(EngineCore_DP0 pid=5737) INFO 02-20 14:44:09 [gpu_model_runner.py:4033] Starting to load model google/gemma-3-1b-it...
(EngineCore_DP0 pid=5737) INFO 02-20 14:44:10 [cuda.py:364] Using FLASH_ATTN attention backend out of potential backends: ('FLASH_ATTN', 'FLASHINFER', 'TRITON_ATTN', 'FLEX_ATTENTION')
(EngineCore_DP0 pid=5737) INFO 02-20 14:44:10 [weight_utils.py:567] No model.safetensors.index.json found in remote.

Loading safetensors checkpoint shards:   0% Completed | 0/1 [00:00<?, ?it/s]
Loading safetensors checkpoint shards: 100% Completed | 1/1 [00:00<00:00,  3.00it/s]
Loading safetensors checkpoint shards: 100% Completed | 1/1 [00:00<00:00,  3.00it/s]
(EngineCore_DP0 pid=5737)

(EngineCore_DP0 pid=5737) INFO 02-20 14:44:11 [default_loader.py:291] Loading weights took 0.39 seconds
(EngineCore_DP0 pid=5737) INFO 02-20 14:44:11 [gpu_model_runner.py:4130] Model loading took 1.91 GiB memory and 1.239594 seconds
(EngineCore_DP0 pid=5737) INFO 02-20 14:44:14 [gpu_worker.py:356] Available KV cache memory: 9.8 GiB
(EngineCore_DP0 pid=5737) WARNING 02-20 14:44:14 [kv_cache_utils.py:1047] Add 2 padding layers, may waste at most 9.09% KV cache memory
(EngineCore_DP0 pid=5737) INFO 02-20 14:44:14 [kv_cache_utils.py:1307] GPU KV cache size: 366,992 tokens
(EngineCore_DP0 pid=5737) INFO 02-20 14:44:14 [kv_cache_utils.py:1312] Maximum concurrency for 228 tokens per request: 1446.48x
(EngineCore_DP0 pid=5737) INFO 02-20 14:44:14 [core.py:272] init engine (profile, create kv cache, warmup model) took 3.12 seconds
(EngineCore_DP0 pid=5737) INFO 02-20 14:44:17 [vllm.py:624] Asynchronous scheduling is enabled.
(EngineCore_DP0 pid=5737) WARNING 02-20 14:44:17 [vllm.py:669] Inductor compilation was disabled by user settings, optimizations settings that are only active during inductor compilation will be ignored.
(EngineCore_DP0 pid=5737) INFO 02-20 14:44:17 [vllm.py:762] Cudagraph is disabled under eager mode
INFO 02-20 14:44:17 [llm.py:343] Supported tasks: ['generate']

Adding requests:   0%|          | 0/8 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/8 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

[2026-02-20 14:44:20] INFO rouge_scorer.py:83: Using default tokenizer.
[2026-02-20 14:44:20] INFO rouge_scorer.py:83: Using default tokenizer.
[2026-02-20 14:44:20] INFO rouge_scorer.py:83: Using default tokenizer.
[2026-02-20 14:44:20] INFO rouge_scorer.py:83: Using default tokenizer.
[2026-02-20 14:44:20] INFO rouge_scorer.py:83: Using default tokenizer.
[2026-02-20 14:44:20] INFO rouge_scorer.py:83: Using default tokenizer.
[2026-02-20 14:44:20] INFO rouge_scorer.py:83: Using default tokenizer.
[2026-02-20 14:44:20] INFO rouge_scorer.py:83: Using default tokenizer.

  Batch 1/3 completed

Adding requests:   0%|          | 0/8 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/8 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

[2026-02-20 14:44:23] INFO rouge_scorer.py:83: Using default tokenizer.
[2026-02-20 14:44:23] INFO rouge_scorer.py:83: Using default tokenizer.
[2026-02-20 14:44:23] INFO rouge_scorer.py:83: Using default tokenizer.
[2026-02-20 14:44:23] INFO rouge_scorer.py:83: Using default tokenizer.
[2026-02-20 14:44:23] INFO rouge_scorer.py:83: Using default tokenizer.
[2026-02-20 14:44:23] INFO rouge_scorer.py:83: Using default tokenizer.
[2026-02-20 14:44:23] INFO rouge_scorer.py:83: Using default tokenizer.
[2026-02-20 14:44:23] INFO rouge_scorer.py:83: Using default tokenizer.

  Batch 2/3 completed

Adding requests:   0%|          | 0/8 [00:00<?, ?it/s]

Processed prompts:   0%|          | 0/8 [00:00<?, ?it/s, est. speed input: 0.00 toks/s, output: 0.00 toks/s]

[2026-02-20 14:44:27] INFO rouge_scorer.py:83: Using default tokenizer.
[2026-02-20 14:44:27] INFO rouge_scorer.py:83: Using default tokenizer.
[2026-02-20 14:44:27] INFO rouge_scorer.py:83: Using default tokenizer.
[2026-02-20 14:44:27] INFO rouge_scorer.py:83: Using default tokenizer.
[2026-02-20 14:44:27] INFO rouge_scorer.py:83: Using default tokenizer.
[2026-02-20 14:44:27] INFO rouge_scorer.py:83: Using default tokenizer.
[2026-02-20 14:44:27] INFO rouge_scorer.py:83: Using default tokenizer.
[2026-02-20 14:44:27] INFO rouge_scorer.py:83: Using default tokenizer.
[rank0]:[W220 14:44:27.210598330 ProcessGroupNCCL.cpp:1524] Warning: WARNING: destroy_process_group() was not called before program exit, which can leak resources. For more info, please see https://pytorch.org/docs/stable/distributed.html#shutdown (function operator())

  Batch 3/3 completed

================================================================================
EVALUATION REPORT: Medusa
================================================================================

PERFORMANCE METRICS:
----------------------------------------
  Average Inference Time: 0.407s
  P95 Inference Time: 0.410s
  Total Inference Time: 9.77s
  Average Throughput: 245.7 tokens/s
  Total Tokens Generated: 2,400

MEDUSA METRICS:
----------------------------------------
  Average Tree Size: 0.0

RESOURCE USAGE:
----------------------------------------
  Average CPU: 22.6%
  Average Memory: 14.3%

ACCURACY METRICS:
----------------------------------------
  ROUGE-1 F1: 0.2195
  ROUGE-2 F1: 0.0403
  ROUGE-L F1: 0.1346
  BLEU Score: 0.0204

COMPARED TO BASELINE:
----------------------------------------
  Speedup: 1.31x
  Throughput Improvement: 30.6%

================================================================================

64

# Conclusion

This comprehensive tutorial demonstrates that LLM optimization is a multi-faceted discipline requiring careful consideration of hardware constraints, model architecture, and deployment requirements. Through practical implementations of over 60 optimization techniques, it has shown how to reduce memory footprint by up to 90%, accelerate training by 2-3x, and achieve production-ready inference speeds.

### Key Findings

1. **Precision Training Impact**: BF16 mixed precision provides the best balance of stability and performance, reducing memory by ~50% while maintaining accuracy. FP8 shows promise for future hardware generations.

2. **Parameter Efficiency**: LoRA-based methods achieve 99% of full fine-tuning performance with less than 1% of trainable parameters, making them the standard choice for most applications. QLoRA extends this to 4-bit base models, enabling 70B parameter fine-tuning on consumer GPUs.

3. **Memory Optimization Synergy**: Combining multiple techniques—quantization (4-bit), gradient checkpointing, and 8-bit optimizers—reduces memory by ~75% compared to baseline, allowing models to fit on hardware that would otherwise be impossible.

4. **Deployment Efficiency**: vLLM with PagedAttention and continuous batching improves throughput by 2-3x compared to naive serving. Speculative decoding adds another 2x speedup with minimal accuracy loss.

5. **Distributed Scaling**: FSDP and ZeRO-3 enable training of models exceeding single-GPU memory by sharding parameters, gradients, and optimizer states across devices.

### Future Directions

As LLMs continue to scale, optimization techniques will evolve toward:

- **Hardware-aware automatic optimization** that dynamically selects strategies based on real-time resource monitoring
- **Native FP8 training** with specialized hardware support
- **Adaptive compute allocation** that varies precision and model depth based on input complexity
- **Unified memory management** across CPU, GPU, and specialized accelerators

This tutorial provides the foundation for understanding and implementing these optimizations, enabling practitioners to work with state-of-the-art models on accessible hardware while maintaining production-grade performance.

# Reference

**LLMs Models**
- [Huggingface:google/gemma-3-270m](https://huggingface.co/google/gemma-3-270m)
- [Huggingface:google/gemma-3-270m-it](https://huggingface.co/google/gemma-3-270m-it)
- [Huggingface:google/gemma-3-1b-pt](https://huggingface.co/google/gemma-3-1b-pt)
- [Huggingface:google/gemma-3-1b-it](https://huggingface.co/google/gemma-3-1b-it)
- [Huggingface:google/gemma-3-4b-it](https://huggingface.co/google/gemma-3-4b-it)
- [Huggingface:meta-llama/Llama-3.2-1B](https://huggingface.co/meta-llama/Llama-3.2-1B)
- [Huggingface:meta-llama/Llama-2-7b-hf](https://huggingface.co/meta-llama/Llama-2-7b-hf)
- [Huggingface:microsoft/Phi-3.5-MoE-instruct](https://huggingface.co/microsoft/Phi-3.5-MoE-instruct)

**Overview Optimization Techniques**
- [Arxiv:A Survey on the Optimization of Large Language Model-based Agents](https://arxiv.org/html/2503.12434v1)
- [Arxiv:A Survey on the Optimization of Large Language Model-based Agents](https://arxiv.org/abs/2503.12434)
- [Arxiv:Evolving Excellence: Automated Optimization of LLM-based Agents](https://arxiv.org/abs/2512.09108)
- [PyTorch:Optimize LLMs for Efficiency & Sustainability](https://pytorch.org/blog/optimize-llms/)
- [Medium:Study of Optimizations for Fine-tuning LLMs](https://medium.com/@techsachin/study-of-optimizations-for-fine-tuning-llms-2ccba350c511)
- [Medium:LLM Inference Optimization Techniques: A Comprehensive Analysis](https://medium.com/@sahin.samia/llm-inference-optimization-techniques-a-comprehensive-analysis-1c434e85ba7c)
- [OpenAI:Optimizing LLM Accuracy](https://developers.openai.com/api/docs/guides/optimizing-llm-accuracy/)
- [ResearchGate:LLM Serving Optimization Techniques: A Comprehensive Analysis](https://www.researchgate.net/publication/392355680_LLM_Serving_Optimization_Techniques_A_Comprehensive_Analysis)
- [Arxiv:Systematic Evaluation of Optimization Techniques for Long-Context Language Models](https://arxiv.org/abs/2508.00305)
- [ResearchGate:Optimizing LLM Latency and Throughput for Interactive Web Interfaces](https://www.researchgate.net/publication/387223217_Optimizing_LLM_Latency_and_Throughput_for_Interactive_Web_Interfaces)
- [OpenReview:Maximizing LLM Efficiency Through Optimization Strategies](https://openreview.net/forum?id=NUzGNp9Kgd)
- [Medium:LLM Model Optimization Techniques and Frameworks](https://medium.com/@yugank.aman/llm-model-optimization-techniques-and-frameworks-e21d57744ca1)
- [Snowflake:LLM Inference: Optimization Techniques and Performance Metrics](https://www.snowflake.com/en/fundamentals/llm-inference/)
- [Agilelab:6 Essential LLM Optimization Techniques for Immediate Business Implementation](https://www.agilelab.it/blog/6-llm-optimization-techniques-immediately-implementable#:~:text=Quantization%20is%20a%20particularly%20effective,scenarios%20involving%20large%20batch%20processing.)